### ISSUE TITLE
Item marker offset

### ISSUE THREAD

**Issue by spyhunter99** [osmdroid/osmdroid#100]
I'd like to be able to set a x,y coordinate offset for icons placed on the map. Right now, it looks like the enum HotSpot is the only option that I have. Is there another way? If not, I'd like to request that this feature be added.

**Comment by MKergall** [comment]
This feature is available when using the [OSMBonusPack](https://code.google.com/p/osmbonuspack) Marker (setAnchor method, similar to Google Maps API V2).
