### ISSUE TITLE
When will there be a new release?

### ISSUE THREAD

**Issue by InI4** [osmdroid/osmdroid#1001]
## Issue Type
[X ] Question

## Description and/or steps/code to reproduce the problem
My own project is a bit of a mess currently, so I am not ready for testing right now, but I've seen a lot of good stuff merging into the code, so I'd like to know, when I can hope to have them packaged?

### Version of osmdroid the issue relates to:
6.1.0

**Comment by spyhunter99** [comment]
good question. i think it's pretty close. @monsieurtanuki opinions?

**Comment by monsieurtanuki** [comment]
To me the following issues are virtually closed:
* #182
* #707
* #757
* #812
* #816
* #906 (maybe)
* #909
* #954
* #955
* #965
* #969
* #970
* #989
* #992

I'd like to fix #1005 before the next version - I should be able to do that within a week.
I think #999 deserves to be fixed for the next version too.

In the issue and PR lists there is a bit of confusion about polygons (#934, #937, #933, #890, #857, #485) and about icons and markers (#994, #954).
Perhaps we can put some items on the shelf, and in the meanwhile make decisions about:
* how we can improve the polyline/gon display performances - what's pending, what can be done next, what works, what sounds like a good idea, what is tricky
* if we can deprecate `ItemizedOverlay` and focus only on clean `Marker` instead

**Comment by InI4** [comment]
Thank you for the reply and the good work!

**Comment by spyhunter99** [comment]
snapshots updated

**Comment by InI4** [comment]
Can you please look into #1040 this is really a problem here. Thx.

**Comment by spyhunter99** [comment]
today if #1040 is resolved

**Comment by monsieurtanuki** [comment]
@spyhunter99 It just happened this week (6.0.2), didn't it?

**Comment by monsieurtanuki** [comment]
I guess we can close this one.

**Comment by spyhunter99** [comment]
i pushed a snapshot last night if it helps
