### ISSUE TITLE
Latest Xamarin bindings

### ISSUE THREAD

**Issue by isr-mlambert** [osmdroid/osmdroid#1003]
## Issue Type

[x ] Question
[ ] Bug
[x ] Improvement
[ ] Build system related
[ ] Performance
[ ] Documentation

## Description and/or steps/code to reproduce the problem

It is possible to get the latest metadata.xml for xamarin? The latest version is for 5.0.1.

## Environment

Xamarin - android

### Version of osmdroid the issue relates to:

5.6.5

**Comment by neilboyd** [comment]
See https://github.com/osmdroid/OsmdroidXamarin/issues/8 or https://github.com/osmdroid/OsmdroidXamarin/issues/12
As you can see it's not being maintained. Volunteers would be appreciated.
