### ISSUE TITLE
Offline first for tile download

### ISSUE THREAD

**Issue by monsieurtanuki** [osmdroid/osmdroid#1004]
## Issue Type

- [x] Improvement
- [x] Performance

## Description and/or steps/code to reproduce the problem

The process in order to get the tiles works more or less that way:
* we have an ordered list of providers
* some are embedded (zip files, SQLite)
* some are on the internet
* at least one provider is an approximation (`MapTileApproximater`)
* and we try to find the tile bitmap from this ordered list of providers - and when we find it we don't check the following providers

Problem: assuming we don't have the tile in our embedded providers and assuming we have a low connectivity, we will be waiting during the tile downloading, and _in the meanwhile we display nothing_. If we had no connectivity at all, then we would immediately skip the download provider and display the tile provided by the approximation provider.

The solution would be something like:
* putting the embedded and approximation providers first in `MapTileProviderBasic` (as "offline")
* when we find the tile in those providers, if the tile is up to date, this is it
* if we found a downgraded version of the tile (expired or approximated), we display it but we keep looking for it in the next providers of the list (presumably "online")
* doing so we display immediately an approximation of the tile, while searching for a better version online

### Version of osmdroid the issue relates to:

6.0.2

**Comment by InI4** [comment]
Isn't this, when tile is in database, show it immediately from there, then do the usual expiry, reload stuff and update in case we have a finished new version? Would be so cewl.

**Comment by monsieurtanuki** [comment]
@InI4 More or less, but it don't know if we can be specific about "in database" or not: we'll let the user set its own tile providers list order.
The order is currently "best providers" first; the goal is "fastest providers first", while still looking for an up-to-date tile.
Can we enforce the provider list order? To do that we'll need to know for each provider its tile relevancy (expired / scaled / up-to-date) and its access speed (local database / local file / network / notoriously slow server). Then we can add a method in the provider array, something like "reorder according to relevancy or speed".

**Comment by InI4** [comment]
OK, you are thinking really big right now. Cool, just do not forget to release the stuff already done ;-)

To make it really messy, you could allow these relevancy ratings to interact, i.e. tile x has relevancy 2.0, age 0 days, scale 1.0 from local, but relevancy 5, age 4 days and scale 2.0 from net. So wtf is better? And does this make sense on tile base, or couldn't that create a "patchwork" out put on the screen? 

I am mostly for the speed thing, so fastest first, maybe best async and lazy after that, so I'd probably keep it as simple as very few sources and a clear linear ranking in terms of speed and accuracy.

**Comment by monsieurtanuki** [comment]
@InI4 I'll work on that after the next release (6.1.0).
Btw:
* it's already potentially a patchwork if you have several providers
* it's already async
* I think the tile downloads are already on FIFO or LIFO
* I note your idea of download cancel - I'm not sure it's implemented now

What I had in mind is:
* either we respect the user's provider order
* or the user asks us to reorder relevancy-wise
* or the user asks us to reorder speed-wise

And regardless of that initial order or reorder aspect, the process will be:
* to loop on the provider list
* to display the first available tile, regardless of its status
* to keep looking until we find an up-to-date version of the tile

**Comment by secaw** [comment]
Hmm, doesn't this get a bit too complicated? Isn't the basic idea very simple: if we need to download a map tile and it's not already in cache (status expired) then while downloadig display an approximated one? Couldn't this be done directly in `MapTileDownloader` ?

For the record: I already have a different approach to `MapTileProviderBasic`, thus derived my own `MapTileProviderArray`. My provider order is:

1) MapTileFileArchiveProvider, if any (tile source unaware, see #688)
2) Custom mapsForgeTileProvider, if any (has a map bounding box check)
3) MapTileFileStorageProviderBase
4) MapTileDownloader
5) MapTileApproximater

This may result in a patchwork of different offline maps with an underlying online map, but it's pretty straightforward to me.

**Comment by monsieurtanuki** [comment]
@secaw It's not as complicated as it may appear.
The initial issue was about this: if I get a tile from a provider, I display it (like now) and if ever its status is not "up to date" I keep looking for it in the remaining providers (instead of stopping like now).

In your case it would mean that reordering as 4. MapTileApproximater 5. MapTileDownloader would work almost as you suggest.

The user has the possibility to reorder manually its provider list accordingly (like now and like you do), or as mentioned with @InI4 we may provide a way to "reorder list by speed or relevancy".

I find it rather elegant that way:
* the user has full control over the provider list order
* each provider has the same simple way of working (get a tile)
* the current algorithm isn't that impacted (instead of stopping immediately we'll display but still be looking for a better tile status if relevant)

I'm afraid that what you suggest (impact on `MapTileDownloader`) would cause confusion:
* the implemented simple work (get a tile) would be warped (get a `MapTileApproximater` tile _and then_ get a tile)
* difficult to maintain (remember that the `MapTileApproximater` has its own providers)
* messy if someone uses several `MapTileDownloader`s
* not working if someone doesn't use `MapTileDownloader`s but still needs the `MapTileApproximater`

**Comment by secaw** [comment]
@monsieurtanuki Ok, get your point re `MapTileDownloader`. So it would have to be done in `MapTileProviderArray`. What about CPU and thus battery usage? If we render bitmap tiles with the approximater that are downloaded within the next second anyways, it's overly intensive, isn't it? So maybe this should be an opt-in. I really like the basic idea though!

**Comment by monsieurtanuki** [comment]
@secaw Indeed there will be extra work for CPU, but I don't believe it will be such a problem. Anyway we're only talking about the new tiles (that are not in the SQL cache), which by construction are less and less numerous - unless you always go in the same direction without going back - like "Grasshopper" in Kung Fu ;)

And if we implement the "download cancel" suggested by @InI4, there will be less "I needed that tile 30 seconds ago which wasn't downloaded yet because of my slow internet connection and now I moved and it's useless but as it's in the queue I still download it" useless battery consuming downloads.

Even for user experience, the fact that the user knows instantly where she is (even approximately) will lower the demand on useless tile downloads.

I can use a settable "relevancy flag" ("first tile wins" vs. "best tile eventually wins"). I don't have clear ideas about opt-in / opt-out for the moment.

**Comment by InI4** [comment]
I like the basic thinking about responsiveness! However I doubt more but a few users want to reorder their tile preference. There should be a very good default built in anyway. Yes, and I forgot about quickly rescaling a tile as approximation.

**Comment by monsieurtanuki** [comment]
Actually it was VERY easy to implement: in your `MapTileProviderArray` (such as `MapTileProviderBasic`) you just have to put the offline providers first, and then the online provider(s). There already was some kind of "if the tile is expired/scaled, keep looking for the tile in the remaining providers" algorithm.
I'm about to PR.

**Comment by monsieurtanuki** [comment]
Just PR'ed in #1063 
Not related to this PR: I noticed that there were sometime some hiccups when panning the map. Would look like some `invalidate`s have been removed. Investigating...

**Comment by secaw** [comment]
Cool, looking forward to testing. Re 'hiccups' - noticed that too!

**Comment by secaw** [comment]
Wow, just moved the download provider behind the approximater in my `MapTileProviderArray` provider list like you suggested. Such a simple change for such a big improvement! It now behaves exactly like most of the other major map APIs, where maps just seem to 'sharpen' while new tiles are being downloaded. Great.

**Comment by monsieurtanuki** [comment]
@secaw Unfortunately it's not that easy. I just ran some tests without internet, and there are some lousy side effects, like the tile approximations being stored in the memory cache and then considered as the legitimate source for other approximation. Some fine tuning is needed.

**Comment by secaw** [comment]
@monsieurtanuki I can not reproduce this, but I did have problems regarding the new preCache in conjunction with overlapping mapsforge maps. I decided not to use the preCache in the end as in my opinion there's too much unnecessary computation going on, especially regarding mapsforge, which is expensive anyways. Didn't see a big visible change actually too. Maybe usage of preCache in `MapTileProviderBasic` should be an option as well?

I have another question regarding the preCache: Are the MapTileListComputers there only for preCache, or generally for the tileCache?

Since the order of providers changes in direction to what I have for some time now, it might make sense to integrate the following into `MapTileProviderArray` (We don't want to continue with an offline provider, if an available cached tile is just expired) - this might actually solve the 'side effects' you're seeing:

```
@Override
public void mapTileRequestExpiredTile(MapTileRequestState aState, Drawable aDrawable) {
    // Call through to the super first so aState.getCurrentProvider() still contains the proper
    // provider.
    nextDelay(aState.getMapTile());
    super.mapTileRequestExpiredTile(aState, aDrawable);

    // Continue through the provider chain
    MapTileModuleProviderBase nextProvider;

    // !!!!!!!!! We don't want to continue with an offline provider, if an available cached tile is just expired
    if(ExpirableBitmapDrawable.getState(aDrawable) == ExpirableBitmapDrawable.EXPIRED) {
        boolean providerIsAnOfflineProvider = false;
        do {
            nextProvider = findNextAppropriateProvider(aState);
            if (nextProvider != null) {
                providerIsAnOfflineProvider = !nextProvider.getUsesDataConnection();
            }
        } while ((nextProvider != null) && providerIsAnOfflineProvider);
    } else {
        nextProvider = findNextAppropriateProvider(aState);
    }
    // !!!!!!!!!

    if (nextProvider != null) {
        nextProvider.loadMapTileAsync(aState);
    } else {
        remove(aState.getMapTile());
    }
}
```

**Comment by monsieurtanuki** [comment]
@secaw
> Maybe usage of preCache in MapTileProviderBasic should be an option as well?

Perhaps, especially because it was not as successful as expected (cf. #812), but for the moment I'm more specifically on the current issue.

> Are the MapTileListComputers there only for preCache, or generally for the tileCache?

The same `List<MapTileListComputer> MapTileCache.mComputers` is used for both pre-cache and tile-cache.

Regarding your code suggestion I'm not sure it goes in the right direction. It's not a matter of "am I online/offline" (though it's where I detected the display bug), I think it's more like "OK the last provider (the downloader) failed, but it's not 100% a failure at the level of the provider array, as before there were some scaled version of the tile". I assume that's where the problem is: the difference between "we couldn't even compute an approximation" and "we only have an approximation and that's good enough". Intersecting the delay feature that prevents "gazillion of UnknownHostException" (#989).

I'm working on it...

**Comment by monsieurtanuki** [comment]
I confirm: the problem I'm experiencing now is due to the delays.

The delays were added recently in order to prevent tons of `IOException`s from being written in the logs when you're online and that the tile provider server is (for some reason) unavailable. If we cannot get the tile, we wait 5s, then 15s before we try again (cf. `MapTileProviderArray.mExponentialBackoffDurationInMillisDefault`), instead of constantly retrying uselessly when the user is panning the map.

The delays are currently set at the provider array level for each tile.
The problem is when:
* I manage to approximate a tile
* therefore I display it
* but as its status is not "up to date", I keep trying with the next providers
* eventually the download provider is there, doesn't work because we're offline, it's a failure and therefore the delay is set to 5 seconds for this tile
* if I pan far to the east and then pan back within the 5 seconds, my tile is not in the memory cache anymore and if I want to compute it it won't be possible before the delay is elapsed
* as a result, when I pan back many tiles are blank

Solution 1 is to say at the (tile, provider array) level: OK it's a (download) failure but we've managed to approximate the tile just before, so don't start the delay on this tile. But we'll still get #989 when the tile server is down.

Solution 2 is to ignore the delays when we're offline. Should be easy to implement.

Solution 3 is to attach the notion of delay directly to where it initially belongs - the downloaders. Should be a little less easy to implement, but it would make sense functionally.

I say: solution 3 - with solution 2 as plan B.

**Comment by monsieurtanuki** [comment]
Ouch.

Solutions 2 and 3 are not that clean: it means that if we're online but with the tile server down, we'll keep approximating the tile and then fail to download it (the first time because the server is down, the next times because the delay is on), and again and again. Tons of approximation computations.

Solution 4 could be: if we fail to get the tile with the last provider of the list (it means that we never managed to get an up-to-date version of the tile), we check if we managed to get at least an expired or scaled version. If so, the "good-enough" version is displayed (currently working that way) but we need to keep a track like "btw the expired/scaled version is good enough until the delay is reached".
The delay is currently the time span where you cannot try to get a tile.
A new way of thinking could be: I attach a delay AND a minimum status to a tile. During this delay, as soon as I've got a version of this tile with at least this status, I'm OK and I don't try other providers.

To be continued... (I won't be working on the subject this week-end)

**Comment by secaw** [comment]
Ok, I get it, obviously didn't test with slow network. I agree that solution 4 sounds most promising.

**Comment by monsieurtanuki** [comment]
I'm a bit trapped into a tile cache gc side-effect.
Hopefully tomorrow I'll be able to fix it.

**Comment by monsieurtanuki** [comment]
Just PR'ed and fixed the memory cache GC side-effect.

**Comment by monsieurtanuki** [comment]
Just PR'ed and fixed the hiccups too.

**Comment by secaw** [comment]
Fantastic, on first glance everything's working nice and smooth. Again, a great improvement. Wouldn't it make sense to cut 6.0.2 soon?

**Comment by monsieurtanuki** [comment]
> Wouldn't it make sense to cut 6.0.2 soon?

No objection. Still fighting with travis on this issue though.

**Comment by spyhunter99** [comment]
we can but the question is does this branch make it before or after?

**Comment by monsieurtanuki** [comment]
The sooner we merge the better. I have no strong opinions regarding version numbers.

**Comment by monsieurtanuki** [comment]
Merged.
