### ISSUE TITLE
Offline tiles with the assets folder

### ISSUE THREAD

**Issue by proki13** [osmdroid/osmdroid#1006]
## Issue Type

[X ] Question
[ ] Bug
[ ] Improvement
[ ] Build system related
[ ] Performance
[ ] Documentation

## Description and/or steps/code to reproduce the problem : 

First, what I want to do is basically creating an android app with my own offline map.

What I've done so far :

- I collected the zone/map I was looking for on OpenStreetMap which gave me an .osm file
- I customized the osm file by adding some stuff I need.
- I want to use the lib osmdroid to show the map I collected.
- By browsing the web/the wiki, I understood that I had to convert my .osm file into "tiles". I used Maperitive because I read that MOBAC is outdated and no longer working with osmdroid. So now I have 5 folders (14/15/16/17/18) which matches the different zoom levels and a tiles.json with this inside :

`
"tilejson":"1.0.0", 
    "name":"My Map", 
    "description":"Made with Maperitive", 
    "attribution":"Map data © OpenStreetMap contributors", 
    "tiles":
    [
        "tiles/{z}/{x}/{y}.png"
    ], 
    "minzoom":14, 
    "maxzoom":18, 
    "bounds":
    [
        1.4378766077000047, 
        43.551285304388166, 
        1.5115619816907016, 
        43.572615337724216
    ], 
    "center":
    [
        1.4747192946953531, 
        43.561950321056187, 
        14
    `]

And this is my code so far :

`public class MainActivity extends AppCompatActivity {
   
    MapView map = null;
    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        //IDK what to do with this
        AssetManager assetManager = getAssets();

        map = (MapView) findViewById(R.id.map);
        map.setTileSource(new XYTileSource("tiles", 14, 18, 256, ".png", new String[] {}));
        //....
        map.setUseDataConnection(false); //optional, but a good way to prevent loading from the network and test your zip loading.
        IMapController mapController = map.getController();
        mapController.setZoom(14F);
        GeoPoint startPoint = new GeoPoint(1.4747192946953531F,43.561950321056187F,14F);
        mapController.setCenter(startPoint);
    }

    public void onResume(){
        super.onResume();
        //this will refresh the osmdroid configuration on resuming.
        //if you make changes to the configuration, use
        //SharedPreferences prefs = PreferenceManager.getDefaultSharedPreferences(this);
        //Configuration.getInstance().load(this, PreferenceManager.getDefaultSharedPreferences(this));
        map.onResume(); //needed for compass, my location overlays, v6.0.0 and up
    }

    public void onPause(){
        super.onPause();
        //this will refresh the osmdroid configuration on resuming.
        //if you make changes to the configuration, use
        //SharedPreferences prefs = PreferenceManager.getDefaultSharedPreferences(this);
        //Configuration.getInstance().save(this, prefs);
        map.onPause();  //needed for compass, my location overlays, v6.0.0 and up
    }
}`

- I created a folder "assets" on my android project tree and [I put this inside :](https://i.stack.imgur.com/AovSC.png) (yes I don't know if I need the zip or not so I put both)

But so far what I'm getting on the app is an "empty" map, so I guess I'm doing something wrong/not loading correctly my tiles. I searched a lot on internet for a solution but everything I've tried is not working aswell :'(

If somebody can help me fixing my problem I'd be grateful !

PS : the zip + the unzip is only 16Mb ..

### Version of osmdroid the issue relates to:

6.0.1

**Comment by spyhunter99** [comment]
the path in assets needs to be
/tileSourceName/z/x/y.png

loading a zip in assets isn't supported that i know, you can copy from assets to app private storage or anywhere on device then load it that way

**Comment by proki13** [comment]
So can I directly use my directory "tiles/z/x/y.png" to show the map ? 
Or do I need to use the zip file, copy it in a private storage ... ?

**Comment by spyhunter99** [comment]
well "tile source name" needs to map to the "name" used in your "Tile Source". 

Or if you're lazy, use "Mapnik" which aligns to the default tile source. See TileSourceFactory

both approaches should work.

**Comment by spyhunter99** [comment]
Zips and databases are not read from assets and would have to be copied out before loading the map.  Good luck
