### ISSUE TITLE
pbf format

### ISSUE THREAD

**Issue by b0c1** [osmdroid/osmdroid#101]
Hi,
osmdroid support pbf format? or other format from this site?
http://download.geofabrik.de/europe/hungary.html

Thanks

**Comment by kurtzmarc** [comment]
We currently do not support pbf, however osmdroid has the interfaces for writing your own modular tile provider if you choose. [pbf](http://wiki.openstreetmap.org/wiki/PBF_Format) is a protobuf binary format.
