### ISSUE TITLE
Build release APK without signing it

### ISSUE THREAD

**Issue by Rudloff** [osmdroid/osmdroid#1013]
## Issue Type

* [ ] Question
* [ ] Bug
* [ ] Improvement
* [x] Build system related
* [ ] Performance
* [ ] Documentation

## Description and/or steps/code to reproduce the problem

We recently packaged the OpenStreetMapViewer app on [F-Droid](https://f-droid.org/).
The F-Droid build server signs the apps separately from the build process so we don't have a signing key in `local.properties` or `gradle.properties`. But your build process skips the `assembleRelease` task if there is no signing key (this seems to be introduced by the gradle-fury plugin), so we had to patch `build.gradle` to force enable this task: https://gitlab.com/fdroid/fdroiddata/blob/cf02d0ba63af70868d093c248df2c694bbfe127d/metadata/org.osmdroid.txt#L35

However, this is not very clean. Would it be possible to add a way to build a release APK without signing it?

### Version of osmdroid the issue relates to:

6.0.1

**Comment by spyhunter99** [comment]
I'll take this one,  it's fixable

**Comment by spyhunter99** [comment]
@Rudloff can you check out branch bug/#1013 and try your build on that. I think i disabled the check for the signing key

**Comment by Rudloff** [comment]
I tried to build 124843a9793ec281c08dfd8b97370d5c2c12ad30 but I get an error:
```
Execution failed for task ':OpenStreetMapViewer:validateReleaseSigning'.
> Keystore file not set for signing config release
```

I think you should rewrite this condition to only keep `task.name.equals("validateReleaseSigning")`: https://github.com/osmdroid/osmdroid/blob/124843a9793ec281c08dfd8b97370d5c2c12ad30/gradle/android-support.gradle#L62

**Comment by spyhunter99** [comment]
a simple solution would be to compile with the build version containing `-SNAPSHOT`. is that an option?

**Comment by Rudloff** [comment]
Would that mean the APK version name will contain `SNAPSHOT`? This might confuse F-Droid users.

**Comment by licaon-kter** [comment]
Updated: https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/org.osmdroid.yml#L50

/close this
