### ISSUE TITLE
Disable all map's listeners in Fragment

### ISSUE THREAD

**Issue by kofee-cup** [osmdroid/osmdroid#1014]
## Issue Type

[X] Question

### Version of osmdroid the issue relates to:

6.0.0 - Android API 21 (min), API 23 (target)

-------

Hello everyone ! 

I need some help regarding whether or not something is possible. (And, if someone has a hint or the solution, feel free to help ;) )

For my project, I need to have like a minimap on the screen, above everything, that I can move/destroy with my finger. Like the video in Youtube app, sorta. 

_Actually, I manage to create a small fragment inside a `FrameLayout` that hover above the layout and display a "`MapFragment`" without UI (which I configure, so, that's the right behavior). 
However, I didn't manage to add the proper "drag and drop" listener or touch listener. I have the feeling that the touch listener of the map (the one used to move it) get the action, but not the listener of the FrameLayout._ 

**EDIT : I can move the FrameLayout but only when the fragment is not created inside. When the map is instantiated, its listener is taking over.** 

Is there a way to disable every touch listener ? 

Thank you very much,

Kofee

**Comment by spyhunter99** [comment]
would it be possible to have a transparent view on top of the map? then you can intercept all touch events

**Comment by kofee-cup** [comment]
Actually that's what I did yesterday evening.
I created a parent FrameLayout with two FrameLayout inside, one that welcome the map and the other to intercept touch event that I dispatch to parent.
It works well!

However it disable the zoom button, which I would have like to keep. That's why I'm asking this since in the GMaps Map View, there's something to disable UI listeners.

**Comment by spyhunter99** [comment]
you can use your own zoom buttons that are on top of the transparent view

**Comment by kofee-cup** [comment]
Does that mean it doesn't have any methods to "kill" the UI controls ? 

I will try that, thank you.

**Comment by spyhunter99** [comment]
yeah i think the answer is no at the moment, feel free to open a pr if you want to implement it.

**Comment by kofee-cup** [comment]
Thank you for the opportunity but I'm don't have enough skills in Android and Java to contribute to an API like this yet. 
And thank you for your time !

**Comment by kofee-cup** [comment]
Thank you for the opportunity but I'm don't have enough skills in Android and Java to contribute to an API like this yet. 
And thank you for your time !
