### ISSUE TITLE
MapView - setOnCameraChangedListener

### ISSUE THREAD

**Issue by rmuhamed** [osmdroid/osmdroid#102]
Hi everybody!

There is anyway to "listen" camera events? I've tried to set OnCameChangeListener to mapView or mapController but i noticed that classes didin't implement the according interface.

I have no idea the correct way to add this feature...

Any help will be great!

Thanks in advance.

**Comment by ziem** [comment]
You can set MapListener and get notified when onScroll or onZoom event occurs.

**Comment by rmuhamed** [comment]
ziem,

It's a good approach. I'll try in that way.

Thanks!
