### ISSUE TITLE
Low resolution

### ISSUE THREAD

**Issue by ghost** [osmdroid/osmdroid#1020]
On my lenovo p2 all zoom levels are extremely low resolution.
Using the open map app from fdroid.

**Comment by spyhunter99** [comment]
there's an option in the setting menu. i think it's "scale tiles to resolution". try turning it off and see if it helps

**Comment by Swedneck** [comment]
There is no such setting.

**Comment by spyhunter99** [comment]
ahh sorry, in most (but not all) of the samples, there's an action bar (top right) ... button. It's listed a "scale tiles"

**Comment by Swedneck** [comment]
Ah yes, that works for the samples that has it. However that results in things being unreadably small.
I presume this is to do with #49?

**Comment by monsieurtanuki** [comment]
Technically there's an additional fine tuning option: `MapView.setTilesScaleFactor(float)`
> [more than] 1.0 enlarges map display, < 1.0 shrinks map display

I don't think there's a demo about it, though.

**Comment by monsieurtanuki** [comment]
@ghost Was it helpful? Can we close this issue?

**Comment by monsieurtanuki** [comment]
Closed because a @ghost cannot answer.
