### ISSUE TITLE
SingleTapConfirmed gesture listener doesn't work since 6.0

### ISSUE THREAD

**Issue by johan974** [osmdroid/osmdroid#1026]
[X] Bug

## Description and/or steps/code to reproduce the problem

For 5 years I processed 'single tap confirmed' touches in the following way: 

1 - Definition of gesture detector: 

mDetector = new GestureDetectorCompat( getActivity(), new GetSingleTapEvents());
mapView.setOnTouchListener( new View.OnTouchListener() {
      @Override
      public boolean onTouch(View v, MotionEvent event) {
          mDetector.onTouchEvent(event);
          return rootView.onTouchEvent( event);
       }
    });

2 - The GestureDetector: 

class GetSingleTapEvents extends GestureDetector.SimpleOnGestureListener {
    @Override
    public boolean onDown( MotionEvent event) {  // entered only once 
            return true;
     }
    @Override
    public boolean onSingleTapConfirmed( MotionEvent e) {
           // process the event - single tap confired
   }
}

## Environment
Osmdroid 6.0.1 with

### If it's a bug, version(s) of android this affects:
Android 7.0

### Version of osmdroid the issue relates to:

All previous releases were ok. 
Since Osmdroid 6.0.

I really hope you have a solution to this problem. An alternative way is ok. 
I need the single tap because of other standard map gestures. 
I put the app into a mode that 'single taps' are starting to make a route on the map.

**Comment by monsieurtanuki** [comment]
@johan974 Would that be OK for your needs?
````java
mapView.getOverlayManager().add(new Overlay() {
	@Override
	public void draw(Canvas c, MapView osmv, boolean shadow) {
		// do nothing
	}

	@Override
	public boolean onSingleTapConfirmed(MotionEvent e, MapView mapView) {
		// do what you want
		return true;
	}
});
````

**Comment by monsieurtanuki** [comment]
@johan974 I just tested it again, successfully. Why would the `@Override` of `onSingleTapConfirmed` be invalid?
````java
package org.osmdroid.views.overlay;

public abstract class Overlay implements OverlayConstants {
//...
	public abstract void draw(final Canvas c, final MapView osmv, final boolean shadow);
//...
	/**
	 * By default does nothing ({@code return false}). If you handled the Event, return {@code true}
	 * , otherwise return {@code false}. If you returned {@code true} none of the following Overlays
	 * or the underlying {@link MapView} has the chance to handle this event.
	 */
	public boolean onSingleTapConfirmed(final MotionEvent e, final MapView mapView) {
		return false;
	}
//...
}
````

**Comment by johan974** [comment]
S U P E R B !!!    Thank you very much. 

The methods have changed: the have an extra 'mapview' parameter. 

I can draw polygons again!. I will close the issue.
