### ISSUE TITLE
Demo does not show current location

### ISSUE THREAD

**Issue by andriy-svirskyy** [osmdroid/osmdroid#1027]
## Issue Type

[ ] Bug

## Description and/or steps/code to reproduce the problem
From Demo launch the topmost app [OSMDroid Sample map (Start here)] - map is displayed but there is no current position indicator.

Device location is set to On, mode is High accuracy

### If it's a bug, version(s) of android this affects:

6.0

### Version of osmdroid the issue relates to:

6.0.1 release

**Comment by spyhunter99** [comment]
Just tested it, it works.  you may have missed the 'ask for permissions' on
the intro part

**Comment by andriy-svirskyy** [comment]
You are right, my mistake.

Works as expected
