### ISSUE TITLE
When pinch zooming out, sometimes the map pans

### ISSUE THREAD

**Issue by spyhunter99** [osmdroid/osmdroid#103]
I think what's happening is that the gesture detector is a bit too sensitive and when pinching to zoom out, any trailing touch can be interpreted as a pan the map movement. A quiet period after a zoom in/out gesture is executed may be needed to help suppress this

**Comment by kurtzmarc** [comment]
Possibly related to #85?

**Comment by spyhunter99** [comment]
perhaps. i'm not really sure what the root cause is, but it's annoying as hell

**Comment by spyhunter99** [comment]
resolved with #130
