### ISSUE TITLE
Missing info in osmdroid-wiki, section : Add Map Scale bar overlay

### ISSUE THREAD

**Issue by Steph155** [osmdroid/osmdroid#1032]
## Issue Type
[ ] Documentation

## Description

You gave a code to show how to add a map scalebar overlay.
There is something missing in there :

`mScaleBarOverlay.setScaleBarOffset(dm.widthPixels / 2, 10);` 

The dm variable's type is DisplayMetrics. It should not be omitted.

**Comment by spyhunter99** [comment]
thanks i'll update it shortly

**Comment by spyhunter99** [comment]
updated
