### ISSUE TITLE
Map center being reset by animation callback

### ISSUE THREAD

**Issue by conej730** [osmdroid/osmdroid#1035]
## Issue Type

[x] Question

## Description and/or steps/code to reproduce the problem

We're migrating our Android application from google maps to OSMDroid.  In our map Fragment, we set the center `map.getController().setCenter(mCenter)` to some value appropriate for the map being requested.  However when the map is actually displayed to the user, it is centered on -37.43, 88.94, which is out in the southern Indian Ocean.  I've watched the calls to setCenter in MapController, and I see the center value we've set being passed in through the MapController's replayCalls.  However after that call, setCenter is being called by setZoomLevel in MapView.  This seems to be happening as a result of an onAnimationUpdate call, and the center point passed into setCenter is retrieved from MapView's Projection's current Center.  So ValueAnimator is calling onAnimationUpdate in MapController's ZoomAnimator Listener, and the projection that is loaded when setZoomLevel is then called on the MapView is on centered on this other point.  I'm not quite sure what the original animation is that's resulting in this callback though?  I hadn't seen this as a closed or open issue, but is this behavior that has been seen and is there some way to avoid that animation update moving the center of the map after it's been set without breaking the multitouch functionality?  I've attached a screenshot of the call stack at the time setCenter is being called if that's helpful.

![screen shot 2018-05-18 at 4 31 27 pm](https://user-images.githubusercontent.com/13803101/40260347-b4846170-5abf-11e8-9ea3-94232411757e.png)

### Version of osmdroid the issue relates to:

6.0.1

**Comment by monsieurtanuki** [comment]
@conej730 In your call stack you have (unexpectedly) some kind of pinch gesture call (`MapView.setMultiTouchScale`).
In the normal `setCenter` there's no animation, you just recenter the map directly to that geo place. `animateTo` would involve an animation.
My assumption is that you call `setCenter` while something else is running, like a pinch gesture zoom animation.
That may lead to confusion, between the pinch gesture zoom animation (recentering the map from geo point A to geo point B) and your `setCenter` call (recentering the map).
What functionally triggers your call to `setCenter`? The detection of a pinch gesture?

**Comment by conej730** [comment]
@monsieurtanuki so the setCenter call is happening on the onCreateView when creating the map.  I was also calling zoomTo which in there which seems to be the culprit.

**Comment by conej730** [comment]
@monsieurtanuki thanks for the help on that.  Yes switching to just calling setZoom on the controller in the onCreateView solved this for me.

**Comment by monsieurtanuki** [comment]
@conej730 Cool!
