### ISSUE TITLE
6.0.2 IMapController lacks API, MapController offers

### ISSUE THREAD

**Issue by InI4** [osmdroid/osmdroid#1042]
## Issue Type

[ X] Question
[ X] Improvement

## Description and/or steps/code to reproduce the problem

This is a minor quirks.

Trying to investigate #1040 I realize, that there is a new 6.0.2 method for simultaneously changing position and zoom. I wanted to use this, but then realize I programmed against `IMapController` and not `MapController` and the abstract interface lacks the new feature.

### Version of osmdroid the issue relates to:

6.0.2-SNAPSHOT

**Comment by monsieurtanuki** [comment]
`IMapController` is
> An interface that resembles the Google Maps API MapController class and is implemented by the osmdroid `MapController` class

I don't know how relevant this definition is today. And when I developed the position+zoom change in `MapController`, I didn't want to impact `IMapController` too, with potential side-effects.
@spyhunter99 As an old-timer, what's your view on this issue?

**Comment by spyhunter99** [comment]
i think the interface exists because at one point, someone wanted to have a single api that can be used with both google maps v1 and with osmdroid. I think the usage of the google maps version is probably minimal to the point where it can be deprecated. The iMapController interface should be maintained though. I know of a few users that have custom implementations.

**Comment by cbalster** [comment]
I would guess there are exactly 0 users that depend on maps api v1 compatibility since you can't get an api key for it for several years now.  :+1: for keeping the interface though to support custom implementations.

**Comment by spyhunter99** [comment]
ok moving forward, i'll add deprecation notices to the google wrapper stuff and try to get imapcontroller up to date

**Comment by spyhunter99** [comment]
@InI4 the only method i could see that was missing in the interface was this one
````
void animateTo(final IGeoPoint point, final Double pZoom, final Long pSpeed);
````
is that what this issue is referring to?
