### ISSUE TITLE
Force reload of TileOverlay

### ISSUE THREAD

**Issue by conej730** [osmdroid/osmdroid#1044]
## Issue Type

[x ] Question

## Description and/or steps/code to reproduce the problem

I'm using a TileOverly to display weather tiles that we're downloading from our CDN.  I'm wondering is there a way to invalidate the current tiles and force a reload of the overlay tiles?  Currently if the time since the tiles were downloaded (or really the timestamp on the downloaded weather tiles since we may be downloading weather from the past) varies by more than 10 minutes from the timestamp we now want for weather, I'm clearing out the cache for that tile source.  However I haven't worked out how to then tell the TileProvider to go and fetch new tiles for the current view.  Is that currently possible?

### Version of osmdroid the issue relates to:

6.0.1

**Comment by spyhunter99** [comment]
you can force it to redraw via invalidate, but for reloading tiles, i think you need to ensure that your imagery server is setting an expires http header on tile requests. this should cause the tiles to invalidate

**Comment by spyhunter99** [comment]
Base map imagery for osm is like 7-10 days expiration from the server. If the weather images are set to expire in 10 minutes, then it should just work as is. @conej730 can you confirm that the weather tiles have a short expiration time? If it doesn't then we'll have to hack up the provider code to enable overrides on a per provided basis.

**Comment by conej730** [comment]
Unfortunately because of the way weather tiles are used in other components I can't have them change the expiration and it's currently set to a week.  So what I've done is to keep track of how old they are and if we go beyond 10 minutes then I'll clear the cache using the sqlWriter.

**Comment by spyhunter99** [comment]
i wonder if we can expose a new protected method in the tile provider that will enable you to subclass it and override it with your own expires configuration. it may be more efficient (maybe)

**Comment by monsieurtanuki** [comment]
@conej730 Just PR'ed #1062.
````java
final MapTileDownloader downloaderProvider = new MapTileDownloader(pTileSource, tileWriter,
		aNetworkAvailablityCheck) {
	
	static private final long TEN_MINUTES = 10 * 60 * 1000;

	@Override
	protected long computeExpirationTime(final Long pHttpExpiresTime) {
		return System.currentTimeMillis() + TEN_MINUTES;
	}
};
````
Does it help?

**Comment by conej730** [comment]
Hi @monsieurtanuki sorry I didn't see this earlier, but yeah I think would work well for us.  I'll give it a try to confirm.

**Comment by monsieurtanuki** [comment]
@conej730 With the new `TileDownloader` class, the syntax is slightly different:
````java
final MapTileDownloader downloaderProvider = new MapTileDownloader(pTileSource, tileWriter,
		aNetworkAvailablityCheck);
downloaderProvider.setTileDownloader(new TileDownloader() {

	static private final long TEN_MINUTES = 10 * 60 * 1000;

	@Override
	protected long computeExpirationTime(final Long pHttpExpiresTime) {
		return System.currentTimeMillis() + TEN_MINUTES;
	}
});
````

**Comment by monsieurtanuki** [comment]
@conej730 ping

**Comment by monsieurtanuki** [comment]
@conej730 ping

**Comment by conej730** [comment]
Sorry guys clearly I've been working on other projects, but I'm pulling changes in now for testing.  Will let you know if I have any issues.
