### ISSUE TITLE
osmdroid in osmbonuspackv.6.5.1 XYTileSource atile dont work

### ISSUE THREAD

**Issue by Berg230481** [osmdroid/osmdroid#1045]
Hi
MKergal say:
This is related to osmdroid => please post the issue in osmdroid repository.

In the new Version this dont work`, how works?
```
kp = new XYTileSource("custom",
                                1, 16, 256, ".jpg", new String[]{
                                "http://map1",
                                "http://map2",
                                "http://map3",
                                "http://map4"
                        }) {

                           /* @Override
                            public String getTileURLString(MapTileDownloader aTile) {
                                return getBaseUrl() + "/" + aTile.getZoomLevel() + "/" + aTile.getX() + "/" + aTile.getY() + ".jpg?key=xyf";

                            }*/

                        };
```
thank you

[x ] Question
[x ] Bug
[ ] Improvement
[ ] Build system related
[ ] Performance
[ ] Documentation

**Comment by spyhunter99** [comment]
what exactly is the problem? compile error?

**Comment by Berg230481** [comment]
No, the lib dont find it.

But i have solve with :


@Override public StringgetTileURLString(final long pMapTileIndex) {
     return getBaseUrl() + MapTileIndex.getZoom(pMapTileIndex) +"/" + MapTileIndex.getX(pMapTileIndex) +"/" + MapTileIndex.getY(pMapTileIndex) +".jpg?key"; }



Am 26.05.2018 um 01:29 schrieb spyhunter99:

**Comment by spyhunter99** [comment]
so i'm assuming this was due to the api change from 5.x to 6.x . See the changelog and upgrade guide in the wiki for more info. closing for now
