### ISSUE TITLE
recycled images in GroundOverlay2 cause exceptions

### ISSUE THREAD

**Issue by pasniak** [osmdroid/osmdroid#1049]
## Issue Type

[x] Question
[x] Bug

## Description and/or steps/code to reproduce the problem

Add a layer with an recycled image; draw() of such layer causes exceptions on getHeight and getWidth.  I think the fix is to add an isRecycled check:

```
		if(null == mImage || mImage.isRecycled() || shadow) {
			return;
		}
```

### If it's a bug, version(s) of android this affects:

All

### Version of osmdroid the issue relates to:

6ac47eda457ef619235ce0039ac88fe226ac481d

**Comment by cbalster** [comment]
Won't this just mask an underlying issues? A recycled image shouldn't be drawn, right?

**Comment by pasniak** [comment]
I have a parallel process which fetches overlying image bitmaps in chunks, and, if they are already in place, recycles them and nullifies them (I get few bitmaps par second).   The images are part of an overlay and they might be part of a map on the screen.  If I do not recycle images before nullyfying them (which seem recommendation for newer OS versions) it works fine.  I do not see major change in RAM usage so I guess this is solved....
