### ISSUE TITLE
onMapPanningFinished?

### ISSUE THREAD

**Issue by spyhunter99** [osmdroid/osmdroid#105]
Is there an event I can listen to for identifying when a given map motion event has finished? My use case is that I want to query a database when the map has stopped moving, then load geopoints into an icon overlay based on the bounding box if the current view, that way stuff it's loaded into memory that's out of view of the current map.

**Comment by ziem** [comment]
[MapListener](https://github.com/osmdroid/osmdroid/blob/master/osmdroid-android/src/main/java/org/osmdroid/events/MapListener.java) is the only available map movement listener. You can find more here: https://github.com/osmdroid/osmdroid/issues/102.

**Comment by spyhunter99** [comment]
thanks
