### ISSUE TITLE
Zoom buttons flipped for RTL layouts

### ISSUE THREAD

**Issue by XMitja** [osmdroid/osmdroid#1053]
## Issue Type

[ ] Question
[X ] Bug
[ ] Improvement
[ ] Build system related
[ ] Performance
[ ] Documentation

## Description and/or steps/code to reproduce the problem

Select "Force RTL Layout direction" in Developer Options and use any map with the default zoom buttons

### If it's a bug, version(s) of android this affects:

All

### Version of osmdroid the issue relates to:

6.0.1
![screenshot_1528309070](https://user-images.githubusercontent.com/2546009/41057373-e228a920-69be-11e8-9328-107c25f88d66.png)

**Comment by monsieurtanuki** [comment]
@XMitja You're right, definitely lousy zoom buttons.

@spyhunter99 Looks like another good reason to implement custom zoom buttons instead of standard Android's.

**Comment by spyhunter99** [comment]
agreed. the built in zoom controls are provided by android, nothing we can do about it beside stop using it and roll our own solution.

**Comment by monsieurtanuki** [comment]
Fixed by #1190. Feel free to reopen.
