### ISSUE TITLE
How to implement OnlineTileSourceBase in Osmdroid 6.0+

### ISSUE THREAD

**Issue by djnotes** [osmdroid/osmdroid#1054]
## Issue Type

[ x] Question
[ ] Bug
[ ] Improvement
[ ] Build system related
[ ] Performance
[ ] Documentation

## Description and/or steps/code to reproduce the problem
The following piece of code in the Wiki for creating an OnlineTileSourceBase does not work:   
```
mMapView.setTileSource(new OnlineTileSourceBase("USGS Topo", ResourceProxy.string.custom, 0, 18, 256, "", 
               new String[] { "http://basemap.nationalmap.gov/ArcGIS/rest/services/USGSTopo/MapServer/tile/" }) {
               @Override
               public String getTileURLString(MapTile aTile) {
                    return getBaseUrl() + aTile.getZoomLevel() + "/" + aTile.getY() + "/" + aTile.getX()
				+ mImageFilenameEnding;
               }
          });

```
The current version of the constructor for this class is as follows:  
```
mMapView.setTileSource(new OnlineTileSourceBase("myMapnik", 0, 18, 256, "",
                new String[]{"http://192.168.5.15/osm_tiles"}) {
            @Override
            public String getTileURLString(long pMapTileIndex) {
                return null;
            }
        });
```
I have created a mapnik server at 192.168.5.15, so that requesting http://192.168.5.15/osm_tiles/0/0/0.png via browser gives me a map tile as follows:    
![Map](https://i.stack.imgur.com/PzuXw.png)

How can I implement the new version of `OnlineTileSourceBase`?
## Environment
Android 

### Version of osmdroid the issue relates to:

6.0.1

**Comment by monsieurtanuki** [comment]
@djnotes I just edited the [wiki page](https://github.com/osmdroid/osmdroid/wiki/Map-Sources).
For osmdroid versions >= 6 it's something like this:
````
mMapView.setTileSource(new OnlineTileSourceBase("USGS Topo", 0, 18, 256, "", 
               new String[] { "http://basemap.nationalmap.gov/ArcGIS/rest/services/USGSTopo/MapServer/tile/" }) {
               @Override
               public String getTileURLString(long pMapTileIndex) {
                    return getBaseUrl()
                           + MapTileIndex.getZoom(pMapTileIndex)
                           + "/" + MapTileIndex.getY(pMapTileIndex)
                           + "/" + MapTileIndex.getX(pMapTileIndex)
                           + mImageFilenameEnding;
               }
          });
````

**Comment by djnotes** [comment]
Thank you @monsieurtanuki. Works like a charm.
