### ISSUE TITLE
Redundant test target

### ISSUE THREAD

**Issue by cbalster** [osmdroid/osmdroid#1058]
## Issue Type

[x] Improvement
[x] Build system related
[x] Performance

## Description and/or steps/code to reproduce the problem

As far as I can tell the build target 11 is redundant since target 1 already is api 8. The "g" variant is only used for building the GoogleWrapperSample but this is minSdk = 9 and therefore is excluded anyway.
See:
https://github.com/osmdroid/osmdroid/blob/4a7cdadeaa2b5e533e7a72141e100a4038f132e0/.travis.yml#L60

and

https://github.com/osmdroid/osmdroid/blob/4a7cdadeaa2b5e533e7a72141e100a4038f132e0/GoogleWrapperSample/build.gradle#L55

### Version of osmdroid the issue relates to:

master

**Comment by spyhunter99** [comment]
good catch. actually i'm probable going to drop the google stuff from the settings.gradle file and be done with it, then the travis script can be further reduced. We really need avds on travis that `work`. It's only a matter of time before the google overlords remove the api8 images entirely from the download catalog

**Comment by cbalster** [comment]
I'm actually cleaning up parts of the travis build right now and will try to get newer avds working again. I'll let you know what I was able to do.

**Comment by spyhunter99** [comment]
good luck, i've attempted it countless times, always ending in defeat.

**Comment by cbalster** [comment]
Just a quick update: I got things working again for the most part and also was able to shave off a bit on build times. It's mostly a matter of sorting out some minor Details now and cleaning up my branch. I'm a bit short on time currently but I hope to PR some time next week.
