### ISSUE TITLE
OSM Compass is Disappeared

### ISSUE THREAD

**Issue by kurniawanrizzki** [osmdroid/osmdroid#1060]
## Issue Type

[ ] Question
[ ] Bug

## Description and/or steps/code to reproduce the problem

I have a problem regarding to the compass usage in OSM, previously i was implement it and it worked, but the compass is not shown recently, question is it known issue? or there are some of my code that need to be adjusted if any changes related with dependency or else. Below is sample code how i implement it. @spyhunter99 

`CompassOverlay co = new CompassOverlay(context, osmMapView);`
 `co.enableCompass();`
 `osmMapView.getOverlays().add(co);`

### If it's a bug, version(s) of android this affects:

All

### Version of osmdroid the issue relates to:

4.2

**Comment by moonlotus** [comment]
Even I am facing the same issue. Compass overlay is working on my old device(Moto x play). The same code is not displaying the compass in the new sevice (Moto G5s plus). Is it because of anychange in the orientation sensor? I am using osmdroid distribution 6.0.1.

**Comment by kurniawanrizzki** [comment]
are you sure it is running in your old device? because i also try it using 4.1.2 OS and still same, no compass displayed.

**Comment by secaw** [comment]
@moonlotus The Moto G5s Plus doesn't seem to have a magnetometer sensor, see https://forums.lenovo.com/t5/Moto-G5S-Moto-G5S-Plus/Moto-G5s-Plus-compass/td-p/3769776

**Comment by monsieurtanuki** [comment]
As stated by @secaw, if you don't have a sensor the compass won't be displayed (`CompassOverlay.mAzimuth == Float.NaN`)

Am I dreaming or there used to be in osmdroid a "map orientation compass" similar to Google Map's? If not, shouldn't we implement it: a compass that follows the map orientation, and that restores the north on top when clicked upon? Of course that would be part of another issue, like a new feature issue.

**Comment by kurniawanrizzki** [comment]
Thank you for @secaw and @monsieurtanuki , i was found the root cause, and it's already solved. Inside `InternalCompassOrientationProvider.class` , it still use `Sensor.TYPE_ORIENTATION` as a sensor trigger to show/hide the compass which is already deprecated. So, the compass will be defined such as like this : 

`CompasOverlay compass = new CompassOverlay(context, new AdjustCompassOrientation(context), osm);`
`//AdjustCompassOrientation is a class that implement SensorEventListener, IOrientationProvider`

**Comment by golnarSheikhBahaie** [comment]
u should use  getApplicationContext() instead of using context .

**Comment by WRPSoft** [comment]
Hello to all,

Due to the fact that according to some users of my app, the problem with the missing compass rose seems to persist on many Xiaomi (Redmi and Poco) phones in 2024, I modified the **InternalCompassOrientationProvider** slightly.

I don't know if this is still useful after such a long time, but with the integrated fallbacks, the compass rose is now also displayed on these phones and the compass function works. 

The entire code is attached (zip file).


	public boolean startOrientationProvider(IOrientationConsumer orientationConsumer) {
        mOrientationConsumer = orientationConsumer;
        boolean result = false;

        // first old OSMDroid handling
        final Sensor sensor = mSensorManager.getDefaultSensor(Sensor.TYPE_ORIENTATION);
        if (sensor != null)
            result = mSensorManager.registerListener(this, sensor, SensorManager.SENSOR_DELAY_UI);
        else // now the fallbacks
        {
            final Sensor rotationsensor = mSensorManager.getDefaultSensor(Sensor.TYPE_ROTATION_VECTOR);
            if (rotationsensor != null)
                result = mSensorManager.registerListener(this, rotationsensor, SensorManager.SENSOR_DELAY_UI);
            else {
                final Sensor accelerometer = mSensorManager.getDefaultSensor(Sensor.TYPE_ACCELEROMETER);
                final Sensor magnetometer = mSensorManager.getDefaultSensor(Sensor.TYPE_MAGNETIC_FIELD);
                if (accelerometer != null && magnetometer != null)
                    result = mSensorManager.registerListener(this, accelerometer, SensorManager.SENSOR_DELAY_UI) &&
                            mSensorManager.registerListener(this, magnetometer, SensorManager.SENSOR_DELAY_UI);
            }
        }
        return result;
    }

...

    //
    // SensorEventListener
    //

    @Override
    public void onAccuracyChanged(final Sensor sensor, final int accuracy) {
        // This is not interesting for us at the moment
    }

    private static final float ALPHA = 0.2F; //1 / 16F;//adjust sensitivity

    private float[] LPF(float[] input, float[] output) {
        if (output == null) return input;
        for (int i = 0; i < input.length; i++) {
            output[i] = output[i] + ALPHA * (input[i] - output[i]);
        }
        return output;
    }

    private float[] mMatrixR = new float[9];
    private float[] mMatrixValues = new float[3];
    private float[] gravity;
    private float[] geomagnetic;

    @Override
    public void onSensorChanged(final SensorEvent event) {
        // first old OSMDroid handling
        if (event.sensor.getType() == Sensor.TYPE_ORIENTATION) {
            if (event.values != null) {
                mAzimuth = event.values[0];
                if (mOrientationConsumer != null)
                    mOrientationConsumer.onOrientationChanged(mAzimuth, this);
            }
        } else // now the fallbacks
        {
            if (event.sensor.getType() == Sensor.TYPE_ROTATION_VECTOR) {
                // Get rotation matrix
                SensorManager.getRotationMatrixFromVector(mMatrixR, event.values);
                SensorManager.getOrientation(mMatrixR, mMatrixValues);
                mAzimuth = (float) Math.toDegrees(mMatrixValues[0]);
                if (mOrientationConsumer != null)
                    mOrientationConsumer.onOrientationChanged(mAzimuth, this);
            } else {
                if (event.sensor.getType() == Sensor.TYPE_ACCELEROMETER)
                    // gravity = applyLowPassFilter(event.values.clone(), gravity);
                    gravity = LPF(event.values.clone(), gravity);
                if (event.sensor.getType() == Sensor.TYPE_MAGNETIC_FIELD)
                    // geomagnetic = applyLowPassFilter(event.values.clone(), geomagnetic);
                    geomagnetic = LPF(event.values.clone(), geomagnetic);
                if (gravity != null && geomagnetic != null) {
                    float R[] = new float[9];
                    float I[] = new float[9];
                    boolean success = SensorManager.getRotationMatrix(R, I, gravity, geomagnetic);
                    if (success) {
                        float orientation[] = new float[3];
                        SensorManager.getOrientation(R, orientation);
                        mAzimuth = (float) Math.toDegrees(orientation[0]);
                        if (mOrientationConsumer != null)
                            mOrientationConsumer.onOrientationChanged(mAzimuth, this);
                    }
                }
            }
        }
    }



[MyInternalCompassOrientationProvider.zip](https://github.com/user-attachments/files/17531554/MyInternalCompassOrientationProvider.zip)
