### ISSUE TITLE
Informations about the project and the crew ?

### ISSUE THREAD

**Issue by shebu** [osmdroid/osmdroid#1064]
Please note: issues related to or caused by osmbonuspack will be closed with a
suggestion to open an issue at https://github.com/MKergall/osmbonuspack

(feel free to delete whatever doesn't apply)

## Issue Type

[x] Question
[ ] Bug
[ ] Improvement
[ ] Build system related
[ ] Performance
[ ] Documentation

## Description and/or steps/code to reproduce the problem
Hi, 
First, this is not an issue, not even a question related to using osmdroid...
I just want to inform you that I'm writing a re edition of my book about Android development (in french), and, as Google Maps is not free anymore, I've switched from Google Maps to osmdroid in a chapter talking about geolocation and maps. 
I would like to add a couple of words to present the project, the crew, the main contributors, etc., and I've found nothing like this on the documentation. 
Do you have such informations easily available ?

Best regards, 

Sylvain Hébuterne

### If it's a bug, version(s) of android this affects:

All

### Version of osmdroid the issue relates to:

5.6.5

**Comment by MKergall** [comment]
Some input: 

Purposes of the project: 
I think they can be summerized as follow:
1) Provide a lib to handle OpenStreetMaps maps (tiles) on Android
2) Be flexible enough to support alternative tile sources as much as possible
3) With an API as close as possible to Google Maps API. 

Crew and contributors: 
Initiated in 2008 by Nicolas Gramlich, with help from kurtzmarc and Neil Boyd. 
Current key contributors: spyhunter, monsieurtanuki.

**Comment by neilboyd** [comment]
What @MKergall said, with a minor correction:
It was initiated by Nicolas Gramlich and completed to a working product. I started using it and discovered that it crashed too much and so I made some fixes to make it stable. Since Nicolas was no longer interested in maintaining it, I became the maintainer.
The other contributors can speak for themselves 😁

**Comment by monsieurtanuki** [comment]
Additional comments:
* obviously it's open source
* the features are not limited to Google Maps API's
* it would make sense to mention also @MKergall's [OSMBonusPack](https://github.com/MKergall/osmbonuspack/wiki/Features)

**Comment by shebu** [comment]
Thank you for all these infos ! I'll add this in my book. 

You did a great job ! it's even easier to use than the Google Maps API... Well done !
