### ISSUE TITLE
Error decoding map tiles

### ISSUE THREAD

**Issue by cbalster** [osmdroid/osmdroid#1065]
## Issue Type

[x] Bug

## Description and/or steps/code to reproduce the problem

On API 16, 17 and 18 emulators I see an intermittent problem in `OpenStreetMapTileProviderDirectTest > test_getMapTile_found()`:
`org.osmdroid.views.util.OpenStreetMapTileProviderDirectTest > test_getMapTile_found[test-api18(AVD) - 4.3.1] [31mFAILED [0m
junit.framework.AssertionFailedError: Expect tile to be not null from path /data/data/org.osmdroid/files/osmdroid/OpenStreetMapTileProviderTest.png` 

Corresponding logcat is:
`D/skia    ( 2011): --- decoder->decode returned false`
`E/BitmapFactory( 2011): Unable to decode stream: java.lang.IllegalArgumentException: Problem decoding into existing bitmap`
`D/OsmDroid( 2011): /data/data/org.osmdroid/files/osmdroid/OpenStreetMapTileProviderTest.png is an invalid image file, deleting...`

Full logcat: https://api.travis-ci.org/v3/job/396125120/log.txt

Currently I assume this is a problem with the handling of reusable bitmaps on different API levels and the implementation of `org.osmdroid.tileprovider.BitmapPool` and related classes. I didn't investigate further though yet.

### If it's a bug, version(s) of android this affects:

Currently observed in 16, 17, 18

### Version of osmdroid the issue relates to:

6.0.2

**Comment by spyhunter99** [comment]
@cbalster do we have a test case for this that reliably reproduces it or was it just in the normal travis build?

**Comment by cbalster** [comment]
I saw this bug pretty consistently on API 16, 17 and 18 Emulators on travis in `OpenStreetMapTileProviderDirectTest > test_getMapTile_found`. If you enable these (default abi) in your travis yml and run the build 2-3 times without hitting these you can be pretty sure it's fixed.

**Comment by cbalster** [comment]
I'm pretty sure I know what the problem is. I will try to get a fix done or
post more details tomorrow.

**Comment by spyhunter99** [comment]
on 17, looks like the root cause is an ssl issue.

**Comment by cbalster** [comment]
This us unrelated to this bug, since the tile used used here is not fetched
from a server.
BUT this shows #1061 is not resolved yet. :/
