### ISSUE TITLE
Duplicate tile download code

### ISSUE THREAD

**Issue by cbalster** [osmdroid/osmdroid#1067]
## Issue Type

[x] Improvement

## Description and/or steps/code to reproduce the problem

There is basically identical code for tile downloading in `org.osmdroid.tileprovider.cachemanager.CacheManager.forceLoadTile()` and `org.osmdroid.tileprovider.modules.MapTileDownloader.TileLoader.downloadTile()` which should be consolidated. Especially as they diverge since https://github.com/osmdroid/osmdroid/commit/f8fe850464d6714e15af93e706291350f6acdf91 

### Version of osmdroid the issue relates to:

5.6.5 and up

**Comment by monsieurtanuki** [comment]
@cbalster Something like creating a real class out of the inner class `MapTileDownloader.TileLoader` I guess.

**Comment by cbalster** [comment]
Yes, I would suggest to create a new interface and a configuration setting too so it is possibly to use a different implementation (I have okhttp in mind here). Would need some thought about the interface design though to make this flexible enough.

**Comment by monsieurtanuki** [comment]
I guess a class would even make more sense than an interface, with a `downloadTile` method that calls methods to open, use and close the connection. This class would be something very close to `MapTileDownloader.TileLoader`. And for more specific needs regarding the connection (like okhttp), this class (and its connection related methods) can be overridden.

**Comment by cbalster** [comment]
I'm leaning more towards the "programming to an interface" paradigm here, as I think it's a clearer contract, but don't have that strong of an opinion about it.
It would probably need to be a little more than just one method here, since for example in okhttp the outputstream needs to be closed again. So there would at least have to be another cleanup method to be called after we're done with the stream.
I can try to look into this, but am a little short on time at the moment.

**Comment by monsieurtanuki** [comment]
Currently starting to work on the subject.

**Comment by monsieurtanuki** [comment]
Just PR'ed #1080. Dealing precisely with this issue: now we use a unique code for tile download.
@cbalster If you want to go further with custom http libs I guess now it's easier.

**Comment by monsieurtanuki** [comment]
Just merged.

@cbalster Feel free to upgrade `TileDownloader` according to your needs.

**Comment by cbalster** [comment]
Nice! I will try to give this a go in the next days.
