### ISSUE TITLE
How to display different TileSource at the same time

### ISSUE THREAD

**Issue by pwc1993** [osmdroid/osmdroid#1072]
## Issue Type
[ ] Question
### Version of osmdroid the issue relates to:

6.0.1

**Comment by secaw** [comment]
With `MBTilesFileArchive` and `GEMFFileArchive` this already is the deafult behavior, meaning they'll always be displayed on top of any online tile source, as they don't have an integrated tile source definition.
For those and all other archives (as in `IArchiveFile`s) like `DatabaseFileArchive` and `ZipFileArchive` you can `setIgnoreTileSource(true)` (see #688).
This means that you basically have to construct your own `IArchiveFile` list within your custom `MapTileProviderBasic`.
With mapsforge it's not that easy. Although mapsforge is not tile source aware, it'll always give you a tile, no matter if it's within the current map's region, thus covering the world with a grey surface outside the map's area.

**Comment by pwc1993** [comment]
I used mapsforge to cover mbtiles, and what I'd like to see is mapsforge road and mbtiles image overlay, but mapsforge has a gray surface outside the map's area ,It blocks the mbtiles,change the theme of mapsforge can't remove the surface,so I can't  see them at the same time.
In addition,the online resource  ,like google-satellitesImage and google-road how to loading at the same time ,MapView.setTileSource just can add one source .It's my first time to use OSMDroid ,I'm so sorry to your delay

**Comment by pwc1993** [comment]
When mapsforge is used, it will covering the world with a grey surface outside the map's area.I try to change the 'map-background' or ' map-background-outside' in the theme file to remove the surface , but it like that can only use the RGB type ,so it can't be changed to the ARGB type.I have an OnlineTileSource (google-map) then a MapsForgeTileProvider as a overlay covering it,because of the outside surface ,I can't see the google-map.
![img_20180705_094158](https://user-images.githubusercontent.com/19483970/42298296-bf67c490-8037-11e8-901b-9b11b90f6b36.png)
 it's my demo
![screenshot_20180705-093927](https://user-images.githubusercontent.com/19483970/42298324-df0b254e-8037-11e8-9b28-10f8aebe4c05.png)
it's Locus Map
@secaw

**Comment by secaw** [comment]
Try using an extended `MapsForgeTileSource` with a custom `renderTile(final long pMapTileIndex)` where you set
`RendererJob mapGeneratorJob = new RendererJob(tile, mapDatabase, theme, model, scale, false, false);`
to
`RendererJob mapGeneratorJob = new RendererJob(tile, mapDatabase, theme, model, scale, true, false);`

This will enable transparency for the mapsforge renderer. In my experience it doesn't work with every mapsforge map file though.

**Comment by spyhunter99** [comment]
looks like this is answered, closing for now
