### ISSUE TITLE
Android Studio / Compilation is not supported

### ISSUE THREAD

**Issue by monsieurtanuki** [osmdroid/osmdroid#1075]
## Issue Type

- [x] Bug
- [x] Build system related

## Description and/or steps/code to reproduce the problem

With Android Studio 3.1.3, after cloning the latest master, I have the following error message:
````
Unsupported Modules Detected: Compilation is not supported for following modules: osmdroid.
Unfortunately you can't have non-Gradle Java modules and Android-Gradle modules in one project.
````
One impact is that now in this project Android Studio doesn't even recognize `Fragment` as a class.

My first guess is that it's related to the latest merge (#1068) because:
* I assume that merge deals with build/gradle (as far as I understand those concepts)
* before I pulled the latest master everything worked fine - and I had a decently recent version

### Version of osmdroid the issue relates to:

6.0.2

**Comment by monsieurtanuki** [comment]
<img width="295" alt="20180703 1075 1" src="https://user-images.githubusercontent.com/11576431/42211200-49a8dd32-7eb3-11e8-8bb0-7349d7f0d31a.png">

That makes it rather difficult to contribute, though it doesn't impact the actual build/run.

I managed to have `Fragment` being recognized by replacing 
````
compile "com.android.support:support-v4:${project.property('android-support.version')}"
````
with
````
compile "com.android.support:support-v4:27.1.1"
````

But I cannot get the `org.osmdroid.*` classes :(
Help!

**Comment by cbalster** [comment]
Probably a caching issue with you Android Studio installation. Have you tried "File" -> "Invalidate Caches/Restart"?

**Comment by spyhunter99** [comment]
i'm still on 3.0.1. everytime you upgrade gradle, android studio, or any of the build plugins, it's like playing russian roulette. I just upgraded and now i get these gems
![image](https://user-images.githubusercontent.com/1975321/42274773-eb7f28b6-7f5b-11e8-9b9f-a8fffa7260e7.png)

i also can't open any projects anymore.

**Comment by spyhunter99** [comment]
ok my issue was an incompatible plugin. i remove that one and everything appears to go ok. although it's complaining about debug vs release variants

**Comment by monsieurtanuki** [comment]
@cbalster Just tried, but it didn't work.
I'll try uninstalling android studio.

**Comment by cbalster** [comment]
@monsieurtanuki Weird, I have zero issues with Android Studio, also on 3.1.3 - in the past cleaning the cache and/or build -> rebuild project always solved similar issues for me. I'm pretty certain my commit is unrelated to your issues, since it mainly dealt with the travis configuration which is not involved at all in local builds.

**Comment by monsieurtanuki** [comment]
I uninstalled then re-installed Android Studio, then managed to make things work after about 2 hours of tries. Phew!
