### ISSUE TITLE
How do i get map from MapView of osm ?

### ISSUE THREAD

**Issue by hearbeathorror** [osmdroid/osmdroid#1083]
Hi,

I am trying to use the snapshot version of the developer build as i need to implement polylines, but then i do not know how to get map from mapview. I have this in a fragment and already inflated via an xml. I do not want to use Google MapView but want to use osm.

Please guide.
Thanks

**Comment by cbalster** [comment]
Just get the view via findViewById() and cast it to MapView?

**Comment by spyhunter99** [comment]
` how to get map from mapview. `

what?

**Comment by hearbeathorror** [comment]
@spyhunter99 : so i would like to draw polylines. In GoogleWrapperSample u have used GoogleMapview to get the map object using MapFactory method. But i want to use OSM maps and OSM map view. Is there a way i can draw polylines on the mapView ? or is there a way for me to get the map instance from the mapView? Because if i understand the code correctly, the method that draws or adds polylines, requires a map object.

Please assist

Thanks

**Comment by cbalster** [comment]
GoogleWrapperSample is deprecated by now, which basically means you shouldn't use the MapsApi but instead use the osmdroid api instead. The OpenStreetMapViewer sample app should cover all your needs. Out of curiosity: Are you planning on replacing GoogleMaps 1 to 1 in an existing app or using osmdroid alongside GoogleMaps? Or are you creating a new app from scratch?

**Comment by spyhunter99** [comment]
There's plenty of examples both in the wiki and in in the source for the sample app

**Comment by hearbeathorror** [comment]
@spyhunter99 : not really replacing google maps, but trying as much possible not to use them, just a requirement .. I managed to draw a polyline.. i did not need a map to do so. MapView.getOverlay() has some method if i remember correctly to add the polyline to it. And this polyline object would have all the GeoPoints added to it.

Thanks alot. 

Just an added question, any idea when 6.0.2 snapshot will be released? I am actually using snapshot sdk for the polylines :( .
