### ISSUE TITLE
How to animate a polyline using the osmdroid library?

### ISSUE THREAD

**Issue by ladyeli** [osmdroid/osmdroid#1089]
## Issue Type

[X] Question

## Description and/or steps/code to reproduce the problem
Hello,

I want to make a polyline between a set of coordinates animated, so that it is drawn gradually. I tried some things, but until now without success. Can someone give me a clue, how can I accomplish this?

Thanks in advance!

### Version of osmdroid the issue relates to:

6.0.1

**Comment by spyhunter99** [comment]
You should be able to use a timer task and a polyline, calling set points
or add point as needed,  then redraw the map with invalidate

**Comment by ladyeli** [comment]
@spyhunter99 If I use a timer task the animation will always happen only on the predefined points, but not between them (there will be no interpolation). What I want to achieve is something like this: https://github.com/amalChandran/trail-android 
The problem is that this is for Google Maps and not for OpenStreetMap.

**Comment by monsieurtanuki** [comment]
From what I read in [amalChadran's polyline class](https://github.com/amalChandran/trail-android/blob/master/app/src/main/java/com/amalbit/animationongooglemap/PolylineBased/MapAnimator.java), it's about:
* doing the interpolation yourself - you don't provide just the start and the end of the road but all necessary points, including in the curves, in a base polyline
* using an animation in order to handle the progress - beside the base polyline you use a secondary polyline which is a subset of the base one (e.g. the first n%), and which has another color

**Comment by monsieurtanuki** [comment]
Working on it...

**Comment by ladyeli** [comment]
I did it with the ValueAnimator, but still there is no interpolation, because the whole line is drawn only where the coordinates are set, which results in a different speed of the animation at the different parts of the line, depending on the distance.

**Comment by monsieurtanuki** [comment]
Just finished :)

I need to clean up the code now. Shouldn't be that long.

**Comment by monsieurtanuki** [comment]
@ladyeli Something like that [milestones demo (More Samples / Data / 10K race in Paris)](https://www.youtube.com/watch?v=nl3AB052_tEl) I guess.
Just PR'ed in #1094.

**Comment by ladyeli** [comment]
@monsieurtanuki Yes exactly like that. Thank you very much !!!

**Comment by monsieurtanuki** [comment]
@ladyeli OK to close this issue?

**Comment by ladyeli** [comment]
@monsieurtanuki Yes, thank you again!

**Comment by monsieurtanuki** [comment]
@ladyeli You're welcome!

**Comment by spyhunter99** [comment]
@monsieurtanuki are we ready for release?

**Comment by monsieurtanuki** [comment]
@spyhunter99 I have no pending developments, therefore as far as I'm concerned, yes.
