### ISSUE TITLE
limits of zip file archive?

### ISSUE THREAD

**Issue by spyhunter99** [osmdroid/osmdroid#109]
What are the limits of zip file archive? Is it a size based limitation, quantity of tiles? can we have more than one archive to split them up and overcome size limits?

**Comment by kurtzmarc** [comment]
There is some discussion about this on the old Google Code site:

https://code.google.com/p/osmdroid/issues/detail?id=115
https://code.google.com/p/osmdroid/issues/detail?id=132
https://code.google.com/p/osmdroid/issues/detail?id=372
