### ISSUE TITLE
Empty tile grid (emulator)

### ISSUE THREAD

**Issue by openBDM** [osmdroid/osmdroid#1095]
## Issue Type

[x ] Question
[ ] Bug
[ ] Improvement
[ ] Build system related
[ ] Performance
[ ] Documentation

## Description and/or steps/code to reproduce the problem
Trying to implement osmdroid using gradle and followed the steps in : https://github.com/osmdroid/osmdroid/wiki/How-to-use-the-osmdroid-library

But when I launch the activity with the map it only displays a gray grid with no map tiles. Could this be an emulator issue? Just got started and left all the default settings.

I'm using the needed permissions:

`<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.example.myapplication">

    <uses-sdk
        android:minSdkVersion="8"
        android:targetSdkVersion="22" />

    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.READ_PHONE_STATE" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />`

and my gradle looks like:
`compile 'org.osmdroid:osmdroid-android:6.0.1'`

while using `mavenCentral()` repository

The code for the maps activity : 
`package com.example.myapplication;

import android.content.Context;
import android.preference.PreferenceManager;
import android.support.v7.app.AppCompatActivity;

import org.osmdroid.config.Configuration;
import org.osmdroid.tileprovider.constants.OpenStreetMapTileProviderConstants;
import org.osmdroid.tileprovider.tilesource.TileSourceFactory;
import android.os.Bundle;

import org.osmdroid.views.MapView;

public class MapWithLocations extends AppCompatActivity {

    MapView map = null;
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        Context ctx = getApplicationContext();
        Configuration.getInstance().load(ctx, PreferenceManager.getDefaultSharedPreferences(ctx));

        setContentView(R.layout.activity_map_with_locations);

        map = (MapView) findViewById(R.id.map);
        map.setTileSource(TileSourceFactory.MAPNIK);
    }

    public void onResume() {
        super.onResume();
        map.onResume();
    }

    public void onPause(){
        super.onPause();
        map.onPause();
    }
}`

## Environment
Android Emulator nexus 5.

### If it's a bug, version(s) of android this affects:

All

### Version of osmdroid the issue relates to:

6.0.1
![image](https://user-images.githubusercontent.com/41287133/42751368-d2f4a7ba-88ea-11e8-9368-bb1eed07f156.png)

**Comment by spyhunter99** [comment]
Did you do the permissions prompt?

**Comment by openBDM** [comment]
@spyhunter99 How do I get this permissions prompt on the emulator? I figured because it's on the emulator you dont get it

**Comment by spyhunter99** [comment]
https://github.com/osmdroid/osmdroid/blob/master/OpenStreetMapViewer/src/main/java/org/osmdroid/intro/PermissionsFragment.java

it must be done before loading the content view of the map. It should actually still show the map without this though. Did you check the logcat? Does the emulator have an sdcard attached?

**Comment by openBDM** [comment]
@spyhunter99 I added the following to my android manifest file: 
`android:usesCleartextTraffic="true"`

and now i'm getting the following (different) result : 
![image](https://user-images.githubusercontent.com/41287133/42759784-808375b0-8908-11e8-9f6d-4a851c7acae8.png)

is this supposed to happen?

**Comment by spyhunter99** [comment]
ahh. It's the tile source, they just changed to ssl only, however it seems to be change somewhat frequently. We're going to publish a new version shortly with the fix for that baked in. You can also use a different tile source in the mean time

**Comment by openBDM** [comment]
@spyhunter99 thanks! As per cleartext solution i applied in the manifest it now works :) How would I go about changing the tile source? like so? : https://github.com/osmdroid/osmdroid/wiki/Map-Sources ? Any specific solution you could recommend? :)

**Comment by spyhunter99** [comment]
try this

https://github.com/osmdroid/osmdroid/blob/master/osmdroid-android/src/main/java/org/osmdroid/tileprovider/tilesource/TileSourceFactory.java#L99

then apply it with map.setTileSource(...)
