### ISSUE TITLE
Polygon.OnClickListener not available 

### ISSUE THREAD

**Issue by ladyeli** [osmdroid/osmdroid#1096]
## Issue Type

[X] Question
[ ] Bug
[ ] Improvement
[X ] Build system related
[ ] Performance
[ ] Documentation

## Description and/or steps/code to reproduce the problem
Hello,
I want to use the OnClickListener Interface for the Polygon, but it is somehow not available. I have imported all libraries using gradle.
When I open the class Polygon here in the git repository, I see that the onClickListener is implemented there, but when I open the same class in my project I don't see it. Am I doing something wrong or there is a bug?

### If it's a bug, version(s) of android this affects:

All

### Version of osmdroid the issue relates to:

6.0.1

**Comment by spyhunter99** [comment]
looks like it was added in march 2018, meaning it's probably only available on the 6.0.2-SNAPSHOT version

**Comment by ladyeli** [comment]
@spyhunter99 So, how can I use it now?

**Comment by spyhunter99** [comment]
change your build file to use the snapshot version instead of 6.0.1

**Comment by ladyeli** [comment]
@spyhunter99 I tried, but it gives me the following error:
Failed to resolve: org.osmdroid:osmdroid-android:6.0.2-SNAPSHOT

**Comment by spyhunter99** [comment]
https://github.com/osmdroid/osmdroid#want-the-latest-and-greatest
add the sonatype repo

**Comment by ladyeli** [comment]
Ok, thanks a lot! 
And when is it expected to release the new version?

**Comment by spyhunter99** [comment]
today
