### ISSUE TITLE
OverlayManager class

### ISSUE THREAD

**Issue by mdakram** [osmdroid/osmdroid#110]
@kurtzmarc @neilboyd i was looking into OverlayManager class and found these lines

 if (mTilesOverlay != null && mTilesOverlay.isEnabled()) {
            mTilesOverlay.draw(c, pMapView, true);
        }

        if (mTilesOverlay != null && mTilesOverlay.isEnabled()) {
            mTilesOverlay.draw(c, pMapView, false);
        }

        for (final BaseOverlay overlay : mOverlayList) {
            if (overlay.isEnabled()) {
                overlay.draw(c, pMapView, true);
            }
        }

        for (final BaseOverlay overlay : mOverlayList) {
            if (overlay.isEnabled()) {
                overlay.draw(c, pMapView, false);
            }
        }

the boolean argument when passed true it return right away doing nothing.

1. I don't show any difference when i remove draw(c, pMapView, true); 
2. Is Osmdroid drawing any shadow anywhere as i dont see can we just remove shadow thing??

**Comment by kurtzmarc** [comment]
As part of the Google Maps v1 API, Overlays get two passes to draw. Once to draw a shadow layer, and once to draw regular. A typical behavior during the shadow layer is to draw an icon in grayscale with a skew to give the illusion of 3D depth to the maps. Although we don't take advantage of this (maybe we do in the location overlay), the API specifies that we give Overlays the opportunity to do this. If you don't want to use the shadow layer, add a 

     if (shadow)
         return;

to your draw() method.
