### ISSUE TITLE
cannot draw polyline to the north pole

### ISSUE THREAD

**Issue by copypasteearth** [osmdroid/osmdroid#1109]
im trying to draw a polyline to the north pole the best I can do is a little bit off of the north pole but if I do exactly (90,0) it is just invisible you cant even see the polyline

this picture is with Geopoint set to (-90.00001,0.0) as you can see it is not going all the way to the marker and id like a solution where the polyline goes all the way to the north pole
![northpole](https://user-images.githubusercontent.com/6181334/43040742-d5ca5088-8d19-11e8-968f-f2d13d9f01de.PNG)

```
GeoPoint gp =  new GeoPoint(gplat,gplon);
            GeoPoint ap =  new GeoPoint(aplat,aplon);
            GeoPoint north = new GeoPoint(-90.00001,0.0);
Polyline polyline = new Polyline();
                polyline.addPoint(north);
                polyline.addPoint(gp);
                polyline.addPoint(ap);
                polyline.addPoint(north);
                polyline.setColor(Color.RED);
                polyline.setWidth(20);
                map.getOverlays().add(polyline);
```

**Comment by spyhunter99** [comment]
it's a limitation of the projection, the best you can do is +-85 and change

**Comment by copypasteearth** [comment]
Ahhh ok guess thatll have to do
