### ISSUE TITLE
Possible copyright issue

### ISSUE THREAD

**Issue by anonymous-person** [osmdroid/osmdroid#111]
I was planning on using your library in my commercial product, but it was rejected by our legal team.

Specifically, `osmdroid-master/osmdroid-master/osmdroid-android/src/main/java/microsoft/mappoint/TileSystem.java` includes some code with a Microsoft Copyright in it and therefore contains commercial software.  Sample code was apparently derived from something found on [MSDN](https://msdn.microsoft.com/en-us/library/bb259689.aspx)

There, it is a C# source file.  So obviously, the osmdroid author ported the sample code to Java.  Comparing the two files, I see they are very similar, but not identical.  I noticed the navigation menu on the top to the page has “Documentation” highlighted in blue, presumably denoting this article is considered documentation.  If I click on the Samples navigation item, it takes me to: https://code.msdn.microsoft.com/

> # Developer code samples
> 
> Each sample is licensed to you by the party distributing it. Microsoft does not guarantee the
> samples or grant rights for any sample distributed by a party other than Microsoft. Use of this 
> site is subject to the Terms of Use.
> https://msdn.microsoft.com/en-US/cc300389.aspx 

Where §2.b says

> Software on Documentation Portals. Software accessible on the Documentation Portals is 
> made available by the designated publisher under the associated license terms. If Software 
> is accessible on the Documentation Portals without license terms, then subject subsection 
> (c) below you may use it to design, develop, and test your programs. _**If any such Software 
> without license terms is marked as “sample” or “example,” then you may use it under the 
> terms of the Microsoft Limited Public License.**_

Then I read this in the [MSLPL](https://www.openhub.net/licenses/mslpl):

> (F) Platform Limitation - The licenses granted in sections 2(A) and 2(B) extend only to the 
> software or derivative works that you create that _**run on a Microsoft Windows operating 
> system product**_.

This is where our legal team gets nervous.  They say because of this clause, it can’t be used on Android. 

I see this issue was raised in 2011, but nothing appears to have been done to resolve the issue:  https://groups.google.com/forum/#!topic/osmdroid/z0HOrEoLT6g

Can the author please contact Microsoft to get their explicit permission, and update the attribution/license accordingly?  Otherwise, we feel the terms are too ambiguous to justify the risks of using osmdroid.  :(

**Comment by neilboyd** [comment]
My feeling is that

>If I click on the Samples navigation item

Is taking you down the wrong path. That refers to the samples found on that page, not the small piece of sample code in the documentation.

However, I will try contacting the original msdn author since it's still not clear.

**Comment by kurtzmarc** [comment]
I think we could write our own class from scratch using freely available resources such as:

http://wiki.openstreetmap.org/wiki/Slippy_map_tilenames
http://www.movable-type.co.uk/scripts/latlong.html

and shed the Mircosoft connection.

**Comment by neilboyd** [comment]
I followed a few more links and agree with the original poster.  As I remember we used this class because we were previously using another class that had bugs.  But then later we added a wrapper around this to fix problems going around the limits.  The point is that it's not quite as simple as it might seem.  But it should be quite doable.  If you're copying code, remember to read the terms of use!

**Comment by spyhunter99** [comment]
ok so what's the action here? do we need to dtich the Microsoft code in favor of something else?

**Comment by neilboyd** [comment]
@spyhunter99 that seems like the best thing. I only used the Microsoft code because it seemed pointless to reinvent the wheel, but then it turned out to be buggy anyway, so if the licensing if causing problems then let's just get rid of it.

**Comment by spyhunter99** [comment]
bigger than a bread box. TileSystem is referenced in lots of places

**Comment by spyhunter99** [comment]
in progress

**Comment by spyhunter99** [comment]
i'm stopping work at this junction. geospatial projections are not my forte and would like to enlist the help of @kurtzmarc, @neilboyd or anyone else with more knowledge in this area

**Comment by monsieurtanuki** [comment]
@spyhunter99 I think we could ditch `microsoft.mappoint.TileSystem` altogether, as the vast majority of the relevant tile system code now comes from `org.osmdroid.util.TileSystem`. Would you like me to do it?

**Comment by monsieurtanuki** [comment]
`microsoft.mappoint.TileSystem` is now `Deprecated` and not used anymore (#1028).
This class and `org.osmdroid.TileSystemMathTest` are to be removed, at an appropriate time.

**Comment by monsieurtanuki** [comment]
@spyhunter99 OK to get rid of `microsoft.mappoint.TileSystem` and `org.osmdroid.TileSystemMathTest` for release 6.0.2?
