### ISSUE TITLE
zoomToBoundingBox doing nothing on a "point" bounding box

### ISSUE THREAD

**Issue by MKergall** [osmdroid/osmdroid#1116]
## Issue Type

[ ] Question
[X ] Bug
[ ] Improvement
[ ] Build system related
[ ] Performance
[ ] Documentation

## Description and/or steps/code to reproduce the problem

When calling zoomToBoundingBox on a box which is defined from a single point, nothing happens. 

I didn't test, but I guess the same issue occurs if we have a bounding box from 2 or more points all having exactly the same lat (or same lon). 

Expected result: center on the bounding box center, and zoom at the maximum value allowed by the mapview settings. 

Root cause: this test in zoomToBoundingBox: 

		if (nextZoom == Double.MIN_VALUE) {
			return; 
		}

### Version of osmdroid the issue relates to:
6.0.1 and 6.0.2. 
Probably introduced in 6.0.0.

**Comment by monsieurtanuki** [comment]
@MKergall There's no obvious behavior in this limit case. Of course the map should be centered (which is not the case now and needs to be fixed), but I would rather say I'd like the zoom level to remain unchanged.
Possible solutions include adding a fallback zoom parameter (actual zoom value, MIN, MAX, UNCHANGED).

**Comment by monsieurtanuki** [comment]
@MKergall Just PR'ed #1117.
I added a fallback zoom parameter (that must contain a real zoom value, forget about the meta MIN/MAX/UNCHANGED).
The "More Samples / Events / AnimateTo" demo now starts with 4 tests around Manhattan (single point, single latitude, single longitude, normal)

**Comment by MKergall** [comment]
I don't see that situation as a limit case. If the requested bounding box is "very" small, the view should zoom as much as possible, until reaching the mapview max zoom level. 
"Point" bounding box is just one case of such situations. 
In other words, fallback parameters were already existing: it's the mapview max/min zoom levels. No need to add one as a parameter.

**Comment by monsieurtanuki** [comment]
Just merge #1121 in order to have a more verbose and explicit code, with a maximum zoom parameter.

**Comment by MKergall** [comment]
In your use case with "Animate to demo", the issue (max zoom level = 29) is making clear that such a value for the mapview max level is irrelevant, because as you said it has little to do with a tile provider limit. In my apps, I always change the max zoom level value to 21. 

Anyway, I agree your change brings desired results to anybody, thanks a lot for this fix!

**Comment by monsieurtanuki** [comment]
@MKergall You're welcome!
