### ISSUE TITLE
Change map orientation with animation

### ISSUE THREAD

**Issue by anikdas012** [osmdroid/osmdroid#1119]
## Issue Type

[*] Question

## Description and/or steps/code to reproduce the problem
I am using `MapView.setMapOrientation()` method for changing mapview's orientation. Now I want to add some animation while changing orientation. Can you suggest me how to do it?

### Version of osmdroid the issue relates to:

6.0.1

**Comment by monsieurtanuki** [comment]
Quickly said: use an animation where you gradually increase the orientation. You can find inspiration in the demo app "More samples / Events / AnimateTo" for the possible result, and in `MapController.animateTo` for the code.

**Comment by monsieurtanuki** [comment]
I think I'm going to add this orientation feature to `MapController.animateTo`. This makes sense in at least two cases: when the user played with rotations and we want to animate to a place/zoom with a "clean" orientation of 0, and for some places where the standard map is not 0-oriented (e.g. Barcelona).

**Comment by monsieurtanuki** [comment]
Just merged #1120: `MapController.animateTo` with an orientation parameter

@anikdas012 Feel free to use it and to close this issue.

**Comment by monsieurtanuki** [comment]
@anikdas012 ping
