### ISSUE TITLE
getNetworkAvailable doesn't work on android x86  4.0 ( virtualbox )

### ISSUE THREAD

**Issue by magic-solution** [osmdroid/osmdroid#112]
Hi,
networkInfo.isAvailable()  always return false ..  I suggest this patch ( it work for me )

	@Override
	public boolean getNetworkAvailable() {
		final NetworkInfo[] networkInfo = mConnectionManager.getAllNetworkInfo();
		boolean isAvailable = false;

		if(networkInfo == null)
		   return isAvailable;

		for(int i=0; i<  networkInfo.length ; i++)
		{
			if( networkInfo[i].isAvailable() || networkInfo[i].isConnected()  )
			{
				isAvailable = true;
				break;
			}
		}
		return isAvailable;
	}

**Comment by neilboyd** [comment]
This doesn't seem right.  The current code checks the **active** network like this
```
final NetworkInfo networkInfo = mConnectionManager.getActiveNetworkInfo();
return networkInfo != null && networkInfo.isAvailable();
```

This method is called for every tile that's downloaded so this seems like a lot of unnecessary overhead to check connectivity of networks that are not active.

Or maybe I misunderstood the javadocs for [`getActiveNetworkInfo`](http://developer.android.com/reference/android/net/ConnectivityManager.html#getActiveNetworkInfo()) because it talks about the **default** network.

**Comment by spyhunter99** [comment]
i too, have ran into issues where osmdroid refuses to download tiles on x86 using ethernet. x86 using wifi works just fine though.

**Comment by neilboyd** [comment]
Please could you clarify what we're talking about here.  I understood VirtualBox to mean Genymotion. Do you mean that if the host machine is connected to ethernet it doesn't work but when connected to wifi it does work? Maybe the code above works around that, but is it the correct fix logically?

**Comment by magic-solution** [comment]
For me  networkInfo[i].isAvailable() always retune false I need to add networkInfo[i].isConnected() else never work , I use Ethernet and not tested with wifi.  

or maybe ( not tested ) 

final NetworkInfo networkInfo = mConnectionManager.getActiveNetworkInfo();
return networkInfo != null && ( networkInfo.isAvailable() || networkInfo.isConnected() );

**Comment by spyhunter99** [comment]
Sorry for confusing things. I have a similar issue with a laptop running android x86 natively. Map tiles refuse to load over ethernet when connected, but load just fine over wifi. I also have another machine running x86 android that doesn't have wifi (ethernet only) and thus wasn't unable to get maps to pull over the network.

**Comment by spyhunter99** [comment]
@magic-solution i just tested on my x86 setup here too. Ethernet always returns isConnected=false isAvailable=false. Must be a bug in x86 project. I modified NetworkAvailableCheck to check for Build.HARDWARE.contains("android_x86) then added a flag to check for it in getNetworkAvailable

**Comment by spyhunter99** [comment]
fixed

**Comment by neilboyd** [comment]
By referencing Build.HARDWARE you have increased the minSdk from 7 to 8. You should either do so completely or work around it here.

**Comment by spyhunter99** [comment]
damn. how much of an impact is this? it's probably less than 1% per https://developer.android.com/about/dashboards/index.html

**Comment by spyhunter99** [comment]
fixed

**Comment by neilboyd** [comment]
@spyhunter99 To answer your previous question, it probably reasonable to increase it to 10, but it just needs to be done.
