### ISSUE TITLE
How to implement OSM (OpenStreetMap) with building extrusion, 3D models integration, and how to customise the style of it?

### ISSUE THREAD

**Issue by Emixam23** [osmdroid/osmdroid#1126]
## Issue Type

[x] Question
[x] Documentation

## Description

Documentation about
  - Building extrusion
  - 3D models
  - Ground elevation
  - Building style customisation
  - Map tiles customisation

## Environment

Android
iOS
ReactJs

## Question

Hi ! 

I am coming today because I am hesitating about which technologie I should use. I was first interested by Mapbox that I used before but one of my friend told me that OSM would perfectly fit what I am looking for :) I think he is right, however, I can't find a lot of documentation about it.. Maybe I am just not typing the right key words ...

What I trying to achieve is something as http://demo.f4map.com/#lat=48.0079408&lon=0.1958507&zoom=18&camera.theta=70.546&camera.phi=-90.345. 

I would like to have a map for my app (ReactJs, Android and iOS) with the following customisations/possibilities

  - Building extrusion
  - 3D models
  - Ground elevation
  - Building style customisation
  - Map tiles customisation

However, as I said, I can't find nothing about how to implement it in Android, iOS, or ReactJs.. I can achieve it with Mapbox and Unity3D, but is it possible through OSM only? If yes, then how does work the customisation of the tile and the extruded building? Do OSM provide a dashboard like Mapbox?

I followed this README https://github.com/osmdroid/osmdroid/wiki/How-to-use-the-osmdroid-library about Android. I haven't checked yet iOS and ReactJs

Thanks for any help, any link, any documentation :)

**Comment by monsieurtanuki** [comment]
@Emixam23 osmdroid is basically about displaying pre-computed 256x256 png map tiles.
No 3D, no vectors.
The raw data used to compute the map tiles may come from OSM, but we don't access raw data in osmdroid.

**Comment by Emixam23** [comment]
I see ok thank you :)
