### ISSUE TITLE
MapTileDownloader raises ECONNRESET exception

### ISSUE THREAD

**Issue by andaluz** [osmdroid/osmdroid#113]
IDE: Eclipse Juno
osmdroid-lib: 4.3
Android target: 14+

Hello guys,
I added osmdroid-lib 4.3 successfully to my project in Eclipse and fetching maptiles from openstreetmap.org works well. The problem is when I fetch maptiles from localhost. My app runs a server listening on localhost as tileserver. I can see this is working until the maptile data has sent to the osmdroidm than I get the following exception:

W/org.osmdroid.tileprovider.modules.MapTileDownloader(32732): IOException downloading 
MapTile: /14/xxx/xxx : java.net.SocketException: recvfrom failed: ECONNRESET (Connection reset by peer)

When I do that on my mobilebroswer, I successfully receive a tile, but from osmdroid-lib I get this exception. So my serverside is not that wrong otherwise I won't get the tile from a browser.
I simply did: http://localhost:8888/x/xxx/xxx.png on my mobile browser and it works.

osmdroid-lib works when I use openstreetmap.org as tile source. I'm really stuck here and I hope you can help me with a solution.

**Comment by kurtzmarc** [comment]
Hmmm, your server is resetting the connection for some reason. Does your server only accept from certain user-agents (we use something like "osmdroid" when requesting tiles from HTTP)?

**Comment by andaluz** [comment]
No @kurtzmarc, my server accepts anything over tcp. My server is not a full featured webserver, it's a simple TCP server. I parse the http to get the request and than from there I do the actual request. After getting the results back, I simply pass forward the result to osmdroid.

I got this concept perfectly working on iOS, using Rout-me library, which is similar to osmdroid.
The weird thing is, everything works well, like accepting request from osmdroid, fetching the requested tile and sending the tile to osmdroid. But always after sending the tile to osmdroid, osmdroid raises the ECONNRESET exception.

I've googled a lot, but can't seem to find an anwer.
I also tried:
System.setProperty("http.keepAlive", "false");
before every request, unfortunately without success.

**Comment by kurtzmarc** [comment]
Cross-posted here: http://stackoverflow.com/questions/30025913/osmdroid-lib-with-android-server-results-in-econnreset

**Comment by kurtzmarc** [comment]
It sounds like you're rolling your own HTTP server. This can be quite tricky. The only other suggestion I would have is to use a well-tested embedded server like Jetty.

**Comment by andaluz** [comment]
Thnx for your answer. The funny thing is, if I request a tile from my the Android browser like:
http://127.0.0.1:8888/14/1234/1234.png it works. I assume osmdroid uses a HttpClient-kind of class (for performing the http-request) that has issues with http response format which the browser simply ignores. 

Anyway, I'll investigate this problem later.
I tried to include osmdroid project, so I can modify or debug the MapTileDownloader, but I ended up with a load of errors because about missing dependencies and so on. I really couldn't get it working in Eclipse. Tried to import the project in Android Studio (I haven't played with this IDE much), but the same result. Importing Mapbox project in Android Studio is without a problem, but that project uses Gradle I don't have experience with.
I guess I need to spend a weekend to play with Android Studio and Gradle.

**Comment by neilboyd** [comment]
Is this still an issue?

**Comment by andaluz** [comment]
Yes, but I just started using Android Studio, so I come with an answer soon, hopefully this week.

**Comment by spyhunter99** [comment]
ping

**Comment by spyhunter99** [comment]
sounds like an issue on your end. reopen if you confirm its an osmdroid issue
