### ISSUE TITLE
Map drag locks up

### ISSUE THREAD

**Issue by ashutler** [osmdroid/osmdroid#1132]
I have an issue which I can't work out a fix for an don't believe it is something within my own code.

Displaying a MapView with KML paths displayed using Overlays, if I attempt to drag the map to re-centre it, it will on occasions freeze the map.

## Issue Type

[ ] Question
[ ] Bug
[ ] Improvement
[ ] Build system related
[ *] Performance
[ ] Documentation

A picture/video is worth a thousand words so please watch the video of the issue here:
[https://1drv.ms/v/s!AqMLT_6xLnbwgqtWsOap1L-jWpuR-w](https://1drv.ms/v/s!AqMLT_6xLnbwgqtWsOap1L-jWpuR-w)

## Environment

I am using a MapView with overlays to draw the KML paths. 

### Version of osmdroid the issue relates to:

6.0.2

**Comment by monsieurtanuki** [comment]
Possible reasons for this presumably performance issue:
* too many points in your paths
=> how many points do you have in your paths?
* drawing `Polygon` (displayed as `Path` - which is slow) whereas `Polyline`s are faster (displayed as `Canvas.drawLines`)
=> do you display as `Polygon` or as `Polyline`?

**Comment by ashutler** [comment]
I have spent the day investigating the problem I was having.  It appears the issue was nothing to do with OsmDroid at all but down to the fact that the Fragment containing the map was in an activity that used a ViewPager.  The drag left/right was being intercepted by the ViewPager.  Thanks anyway!
