### ISSUE TITLE
Can we use the default tile provider in this library to build commercial apps?

### ISSUE THREAD

**Issue by welkie** [osmdroid/osmdroid#1139]
I would like to know if we're allowed to use the default tile provider in this library (appears to be Mapnik) for any app we create, including commercial apps.

Background:

I'm developing an app that I hope will grow to many users, and the app uses OSM data. I've already come up with a way to batch load only the OSM data I need into my own database infrequently, that way the users aren't putting a direct load on the free Overpass API server the community has provided. But I also want maps in my app. I would prefer to avoid using Google Maps if I can use OSM instead.

## Issue Type

[x] Question
[ ] Bug
[ ] Improvement
[ ] Build system related
[ ] Performance
[ ] Documentation

**Comment by StevenTB** [comment]
@welkie Hi, 

You can find the policy here : https://operations.osmfoundation.org/policies/tiles/

> Heavy use (e.g. distributing an app that uses tiles from openstreetmap.org) is forbidden without prior permission from the System Administrators.

**Comment by welkie** [comment]
Thanks for the link.
