### ISSUE TITLE
Zoom levels

### ISSUE THREAD

**Issue by tpstigers** [osmdroid/osmdroid#114]
I've been working with osmdroid for use with offline maps.  I cannot get a mapview to zoom beyond level 18.  Everywhere I look on the Internet, the mantra is that if my tiles support a zoom level, then osmdroid supports the zoom level.  This is clearly not the case.  The offline tiles I use are .mbtiles I bake myself using TileMill.  I have extracted them to ensure that zoom levels beyond 18 do indeed exist.  I have appropriately configured mapView.setMaxZoomLevel in my code.  But still no love.

I am inclined to believe that this is not a bug but simply a limitation of the library.  My hope is that I can get this confirmed.

Thank you.

**Comment by ziem** [comment]
Which tile source are you using? [Mapnik](https://github.com/osmdroid/osmdroid/blob/master/osmdroid-android/src/main/java/org/osmdroid/tileprovider/tilesource/TileSourceFactory.java#L63) which is default tile source has max zoom level set to 18. If you want to override it, create your own tile source.

**Comment by tpstigers** [comment]
Did you read anything I wrote?

**Comment by kurtzmarc** [comment]
Tile source (describes the tile properties) is different than tile provider (where they come from). Are you setting a tile source on your tile provider (or on the MapView itself). If not, you're using the default MAPNIK tile source. What size are your tiles? 256x256 or larger?

**Comment by tpstigers** [comment]
That explains it perfectly.  Thank you.
