### ISSUE TITLE
Can not understand about WRITE_EXTERNAL_STORAGE

### ISSUE THREAD

**Issue by altair86** [osmdroid/osmdroid#1140]
Can not understand.
Since version 5.6, you can not request WRITE_EXTERNAL_STORAGE?
If so, then I have an empty map.
Is it possible not to request WRITE_EXTERNAL_STORAGE?

### Version of osmdroid the issue relates to:

6.0.2

**Comment by spyhunter99** [comment]
the map should still render without the permission. The bottom line is that the library needs a place to store the tile cache. I need a writable directory. See the StorageUtils class. If writable storage is available, it will auto select the largest available. If none are available, application private storage is used.

We haven't done anything to prevent requesting external storage write permission, that's all in your app. We've also specified that it should be requested as many people have larger storage external sdcard's vs built in storage on their phone. Previous versions always went to `/sdcard/osmdroid`. With the new permissions with android 6.0, that was not always going to work so we rewrote everything to find the best writable storage available and to default to app private storage

**Comment by spyhunter99** [comment]
> Since version 5.6, you can not request WRITE_EXTERNAL_STORAGE?
did you read this somewhere?

**Comment by spyhunter99** [comment]
i think the change was made in 5.6.x. external storage isn't required anymore.

**Comment by spyhunter99** [comment]
write external storage is no longer required. if we don't have it, it will write to application private storage and "should" be just fine like that. reopen if needed
