### ISSUE TITLE
[Question] Can i add map layer views like satellite, terrain ? 

### ISSUE THREAD

**Issue by hearbeathorror** [osmdroid/osmdroid#1142]
Hi, I would like to know if we have any matching values for different layer types the way google maps supports.

Kindly assist.
Thanks

**Comment by spyhunter99** [comment]
matching values? not sure what you mean

**Comment by hearbeathorror** [comment]
hi @spyhunter99, matching values in the sense, in google maps, when we tap on the layers fab, we get options like terrain, default and satellite, that is what i meant. Do we have these map layers in osm? Please help

**Comment by spyhunter99** [comment]
so there's the tile source factory, which has a ton of tiles sources. The demo app has a menu that lets you switch on most samples (but not all of them)

**Comment by hearbeathorror** [comment]
@spyhunter99 : thanks, i went through the sample, but none of them has satellite view :( . i am missing a  specific sample?  https://help.openstreetmap.org/questions/41270/how-can-i-show-osm-map-as-satellite-view-in-my-application, something similar to this question is what i am looking for .

**Comment by MKergall** [comment]
For Satellite views, you have at least 2 tile source providers that are supported in osmdroid: 

- MapQuest => with restrictions on high zoom levels
- MapBox => result can be seen using OSMNavigator.

**Comment by spyhunter99** [comment]
there's a few usgs tiles source, bing has a few too. Did you try them?

**Comment by spyhunter99** [comment]
i believe the answer is yes.

**Comment by hearbeathorror** [comment]
@spyhunter99 : yes i tried the bing one for road and a usgc one for terrian mode, for satellite mode however i did not try mapbox, is osm navigator part of the osm demo?

**Comment by MKergall** [comment]
https://github.com/MKergall/osmbonuspack/wiki/OSMNavigator

**Comment by hearbeathorror** [comment]
@MKergall, @spyhunter99  : Thank you.
