### ISSUE TITLE
Fatal Exception: android.util.AndroidRuntimeException: Animators may only be run on Looper threads

### ISSUE THREAD

**Issue by johan974** [osmdroid/osmdroid#1146]
Please note: issues related to or caused by osmbonuspack will be closed with a
suggestion to open an issue at https://github.com/MKergall/osmbonuspack

## Issue Type
[X ] Bug

## Description and/or steps/code to reproduce the problem

My app ran well using 6.0.1. Now with 6.0.2. the app immediately crashes. 

Fatal Exception: android.util.AndroidRuntimeException: Animators may only be run on Looper threads
       at android.animation.ValueAnimator.start(ValueAnimator.java:1011)
       at android.animation.ValueAnimator.start(ValueAnimator.java:1065)
       at org.osmdroid.views.MapController.animateTo(MapController.java:156)
       at org.osmdroid.views.MapController.animateTo(MapController.java:130)
       at nl.xyz.waypoints.HybridMap$3.run(HybridMap.java:1145)
       at java.lang.Thread.run(Thread.java:764)

## Environment
Osmdroid 6.0.2.
Android 8.0

### If it's a bug, version(s) of android this affects:
Android 8.0
Others I don't know. 

### Version of osmdroid the issue relates to:
6.0.2

**Comment by spyhunter99** [comment]
hmm @monsieurtanuki have you seen this before?

**Comment by monsieurtanuki** [comment]
Looks a bit like #1118.
The thing is that obviously the animations must take place in the UI thread.
What happened between 6.0.1 and 6.0.2: I don't know.
But an easy fix is to run all animations explicitly in the UI thread, like that:
````java
mMapView.post(new Runnable() {
    @Override
    public void run() {
        mMapView.getController().setZoom(12.);
        mMapView.getController().animateTo(new GeoPoint(45., 2));
    }
});
````
@johan974 Can you try to run your animation with the `MapView.post` syntax?
