### ISSUE TITLE
animateTo() occasionally fails to move map

### ISSUE THREAD

**Issue by InI4** [osmdroid/osmdroid#1148]
## Issue Type

[X ] Bug

## Description and/or steps/code to reproduce the problem

I just released an Osmdroid 6.0.2 based build to the alpha testers of my app. As it turns out occasionally `animateTo()` fail to move the map. It always seem to zoom, but not move. We are not sure, as zooms are rare and the issue itself happens but is hard to reproduce.

The corresponding code sequence is
```
                myLocationNewOverlay.disableFollowLocation(); 
                ((MapController)mapController).animateTo(gp, Double.valueOf(zoom), null);
```

(The app features a list of favourite locations and this is the code to actually display such a favorite location out of the list).

Im might have seen this once, but wasn't sure. Mixed hints from users I gathered so far:

- Maybe it only happens, when the target location `gp` is far away from the current focus.
- Maybe it happens, when the map tiles of the target are not loaded yet, cause it does not seem to happen more than once per location.
- Maybe followLocation() is not disabled in time, as it seem to happen, when transfering from "following to not following". No fails in case "not following to not following" or "not following to following (i.e. reenble follow in UI) have been recognized yet.

## Environment

Various Android 7.0 and up.

### If it's a bug, version(s) of android this affects:

7.0 and up

### Version of osmdroid the issue relates to:

6.0.2

**Comment by MKergall** [comment]
same as #1116 ?

**Comment by monsieurtanuki** [comment]
> Maybe it only happens, when the target location gp is far away from the current focus.

In the "Animate To" demo we go from Manhattan zoom 11 to Alabama zoom 6 to Alaska zoom 3. Do you go further than that, distance-wise or zoom-span-wise?

> Maybe it happens, when the map tiles of the target are not loaded yet, cause it does not seem to happen more than once per location.

The map moves regardless of the the tiles being loaded. If you run the same "Animate To" demo from a fresh OpenStreetMapViewer app with no tiles, you'll see that it's not a problem to have empty tiles.

> Maybe followLocation() is not disabled in time, as it seem to happen, when transfering from "following to not following". No fails in case "not following to not following" or "not following to following (i.e. reenble follow in UI) have been recognized yet.

Maybe more something like that. I'm not an expert on the subject, but I've already experienced unwanted feedback from my smartphone when using the "follow location" feature.

**Comment by InI4** [comment]
Can it be, that `animateTo()` on 6.0.2 needs to be called on UI-Thread, where it could be (successfully) called on any thread before? That combined with a spurious exception I found in app logs, could explain the behaviour. So far an extra `runOnUIThread()` seems to workaround things.

**Comment by InI4** [comment]
I do not either. #1116 sounds related. The point is, when you know it has to run on UI thread it is actually ok. There is an annotation for that, isn't it?

**Comment by InI4** [comment]
Of course UI stuff needs to be run on UI thread, but somehow 6.0.0 and older were coping with animation calls from outside UI thread. I mean with a complex component you never know if an API spawns its own thread until you read the code. 

Enforcing` animateTo() `calls to UI thread works around the problem, so I close this now.
