### ISSUE TITLE
Problem with osmdroidthird party :Mapfactory .getmap() raises error 

### ISSUE THREAD

**Issue by imeneLa** [osmdroid/osmdroid#115]
i want to use the osmdroid_third party  4.3 library in order to use google fonctionnalities such as : animate camera ,animation...  i used this code :https://github.com/osmdroid/osmdroid/blob/master/GoogleWrapperSample/src/org/osmdroid/google/sample/GoogleWrapperSample.java especially in what concerns osmap this line doesn't work mMap = MapFactory.getMap(mapView); (the error is:The type com.google.android.maps.MapView cannot be resolved. It is indirectly referenced from required .class files) and i need it to work ,i need mMap in order to call animate camera . Please,Can any one help me ?

**Comment by neilboyd** [comment]
Did you first check for Google Maps support like that class does in `onPrepareOptionsMenu`?

**Comment by evansgelist** [comment]
I had a similar problem. I used the jar files. It is necessary to add the following to gradle
compileSdkVersion "Google Inc.:Google APIs:22"
and
dependencies {
    compile files('libs/osmdroid-android-4.3.jar')
    compile files('libs/osmdroid-packager-4.3.jar')
    compile files('libs/osmdroid-third-party-4.3.jar')
    compile files('libs/slf4j-android-1.6.1-RC1.jar')
    compile 'com.google.android.gms:play-services:7.5.0'
}

Everything will work well

**Comment by spyhunter99** [comment]
@imeneLa is your problem resolved?

**Comment by spyhunter99** [comment]
I was just able to build so I'm marking this closed. reopen if it's still an issue
