### ISSUE TITLE
Projection/BoundingBox won't change when map orientates

### ISSUE THREAD

**Issue by goransleko** [osmdroid/osmdroid#1154]
## Issue Type

[x] Question
[x] Bug

## Description and/or steps/code to reproduce the problem
I'm trying to get top left and bottom right coordinates of visible map, in order to calculate map center with offset. The coordinates seem fine at start, but when my map orientates (setMapOrientation), they stay the same. Here's the function I'm calling:

    private Projection projection;
    private void generateProjection() {

        mapView.setMapOrientation(mapView.getMapOrientation() - 10);

        projection = mapView.getProjection();

        BoundingBox boundingBox = mapView.getProjection().getBoundingBox();
        Log.e("PROJECTION BOX", boundingBox.toString());

        IGeoPoint topLeftGeoPoint = projection.fromPixels(0, 0);
        IGeoPoint bottomRightGeoPoint = projection.fromPixels(mapView.getWidth(), mapView.getHeight());
        
        Log.e("PROJECTION TOP LEFT", topLeftGeoPoint.toString());
        Log.e("PROJECTION BOTTOM RIGHT", bottomRightGeoPoint.toString());
    }

### If it's a bug, version(s) of android this affects:

All

### Version of osmdroid the issue relates to:

6.0.2

**Comment by monsieurtanuki** [comment]
@goransleko I think you should first apply the rotation to your screen pixels using `Projection.rotateAndScalePoint` - or `unrotateAndScalePoint`, I never remember ;)

**Comment by goransleko** [comment]
@monsieurtanuki Thanks, but what should I put in for parameters (int x, int y)? I can't really find any useful example. :/

**Comment by monsieurtanuki** [comment]
@goransleko Those methods transform a pixel into a rotated/unrotated pixel:
* put in (x,y) your pixel values, like `(0,0)` or `(mapView.getWidth(), mapView.getHeight())`
* you get a `Point`
* use that `Point` as an input for `fromPixels`

Or something like that...

**Comment by goransleko** [comment]
@monsieurtanuki Thanks! Seems like it's working now, although my map center with offset is still wrong when rotating. But that's probably on my code for calculating center offset. 
There probably isn't any example for map with center offset and rotation?

**Comment by monsieurtanuki** [comment]
@goransleko I can understand map center + offset, but if you add rotation it's getting a little bit complex for me ;)
Perhaps you should apply to your computed offset the reverse function (unrotate/rotate).

**Comment by goransleko** [comment]
Ok, thanks. Closing this then.
