### ISSUE TITLE
FolderOverlay should check for isEnabled when drawing.

### ISSUE THREAD

**Issue by Maradox** [osmdroid/osmdroid#1155]
`FolderOverlay` supports `setEnabled` as it is also an `Overlay` itself.
However, `FolderOverlay.draw` does not check the value of `enabled`.

Should be something like this:
```
if(!shadow && enabled) {
  this.mOverlayManager.onDraw(canvas, osm);
}
```

**Comment by farmazon3000** [comment]
Why this is closed? I have the same problem - I'm using FolderOverlay which doe not repsect enabled. Please reopen!

**Comment by farmazon3000** [comment]
Thank god we have Kotlin people, you can fix it with extension:
```
fun FolderOverlay.flushEnabledToItems(enabled: Boolean) {
    items.forEach {
        it.isEnabled = enabled
    }
}
```

I must admit this is not the first time Kotlin is saving my life.

**Comment by farmazon3000** [comment]
This is so cooool! You can even do it this way:
```
fun FolderOverlay.enable() {
    items.forEach {
        it.isEnabled = this.isEnabled
    }
}
```
