### ISSUE TITLE
How close are we to the next version?

### ISSUE THREAD

**Issue by spyhunter99** [osmdroid/osmdroid#1163]
Hi folks, I've been busy lately and haven't had much time to work on this project or any others. Is there any consensus on if we are running for another version? any blocking issues that must be resolved?

**Comment by InI4** [comment]
You might had more testers, if snapshots would work easier #1157

**Comment by spyhunter99** [comment]
My guess is that it's a gradle thing  when referencing aar snapshots I
think you have to change the dependeny line slightly. I think the index
readme has an example

**Comment by spyhunter99** [comment]
Try this
`compile 'org.osmdroid:osmdroid-android:6.0.3-SNAPSHOT:debug@aar'`

**Comment by InI4** [comment]
Apart from using `api` instead of `compile`, this is fine.

**Comment by InI4** [comment]
Did some random testing and some extended daily use with the SNAPSHOT here and things look good.

**Comment by monsieurtanuki** [comment]
I have currently no major work in progress. I've just merged #1149.
For #1152 we need to wait until the next version of Mapsforge is released. No rush.
Therefore, I'm OK for a new osmdroid version now.

**Comment by nicolae1992** [comment]
Failed to resolve: org.osmdroid:osmdroid-android:6.0.3-SNAPSHOT

**Comment by monsieurtanuki** [comment]
@spyhunter99 My last major contribution (#1195) to the next release is already merged.
I assume the next steps would be a snaphot, tests, then an official release.

**Comment by spyhunter99** [comment]
snapshots updated

**Comment by spyhunter99** [comment]
i can do the release today if we are ready

**Comment by monsieurtanuki** [comment]
I developed some fixes about the zoom buttons that haven't been tested yet by other people than me.
I guess a snapshot refresh would make sense first.

**Comment by spyhunter99** [comment]
snapshots updated

**Comment by spyhunter99** [comment]
WRT zoom buttons. My minimal testing, looks pretty good. the only issue we had with the old branch of strange android lifecycle issues, such as when a fragment was removed, then the timer triggers to hide the zoom buttons. Or when the app's onPause is called, then the timer triggers. This looks and performs well

**Comment by monsieurtanuki** [comment]
No complaint about the new zoom buttons from the 3 testers (@spyhunter99, @InI4 and me).
I guess it's a go! for a new release, once the target api 26 issue is fixed.

**Comment by spyhunter99** [comment]
ok i'll start the release process shortly, doing a release for my apache project at the moment

**Comment by spyhunter99** [comment]
[x] tagged
[x] sonatype release in progress
[x] playstore rollout started
[x] github release published

**Comment by monsieurtanuki** [comment]
Well done!

**Comment by cbalster** [comment]
nice!
