### ISSUE TITLE
OpenGL?

### ISSUE THREAD

**Issue by spyhunter99** [osmdroid/osmdroid#117]
Has anyone considered using an OpenGL view for Osmdroid? I'm curious to see if we could get better performance, especially with lots of map items and overlays

**Comment by mohican** [comment]
it would be awesome!

**Comment by spyhunter99** [comment]
So I've recently played around with turning hardware acceleration on and performance is definitely better. I'm not sure why it's recommended to turn it off but the performance becomes good enough for me

**Comment by neilboyd** [comment]
Some overlays use(d) some unsupported methods. The [original issue](https://code.google.com/p/osmdroid/issues/detail?id=413) is still open.

**Comment by spyhunter99** [comment]
@neilboyd looks like master, and at least few releases of the demo app have had hardware acceleration turned on. After reading the contents of the old ticket, it looks like everything is "fixed". I thought that at one point the documentation had a recommendation to turn off hardware acceleration. I don't see it anywhere at the moment. That's leads me to believe that all issues related to hardware acceleration are fixed. Is that accurate?

**Comment by neilboyd** [comment]
It's turned on in the sample app [manifest](https://github.com/osmdroid/osmdroid/blob/master/OpenStreetMapViewer/src/main/AndroidManifest.xml)
