### ISSUE TITLE
Mapbox wants https requests

### ISSUE THREAD

**Issue by sapia123** [osmdroid/osmdroid#1175]
## Issue Type

[X ] Bug

## Description and/or steps/code to reproduce the problem

Create an App which points to MapBox as Tilesource.

In src/main/java/org/osmdroid/tileprovider/tilesource/MapBoxTileSource.java the baseurl is pointed to http but MapBox rejects those requests. So it needs to be changed to https.

### Version of osmdroid the issue relates to:

6.0.2

**Comment by monsieurtanuki** [comment]
@sapia123 I've just checked, and I had the same result for both the current osmdroid MapBox implementation
`http://api.tiles.mapbox.com/v4/mapbox.mapbox-streets-v7/1/0/0.png?access_token=my_access_token`
and the latest according to the [Mapbox doc](https://www.mapbox.com/api-documentation/#retrieve-tiles)
`https://api.mapbox.com/v4/mapbox.mapbox-streets-v7/1/0/0.png?access_token=my_access_token`

By curiosity, on which url did you have problems?

**Comment by monsieurtanuki** [comment]
@sapia123 I meant, I had good results for both http and https URLs.
Regardless, I switched the osmdroid code to https for Mapbox in #1177.
