### ISSUE TITLE
The osmbonuspack's Marker touch area problem

### ISSUE THREAD

**Issue by RezApp** [osmdroid/osmdroid#119]
When I changed the anchor of the marker and rotated the map using setMapOrientation, The marker's touch area was changed.
for example when I set the anchor BOTTOM_CENTER and setMapOrientation(180), I must touch bottom of the marker where there isn't any marker.

**Comment by kurtzmarc** [comment]
If this is specific to osmbonuspack then you should post the issue there. For a solution, the hit-test rectangle must be rotated before performing the hit-test with GeometryMath.getBoundingBoxForRotatatedRectangle().
