### ISSUE TITLE
Child views of MapView don't stay attached to their geo-position

### ISSUE THREAD

**Issue by schildbach** [osmdroid/osmdroid#1191]
## Issue Type

[x] Bug

## Description and/or steps/code to reproduce the problem

When adding views to the MapView, those views are shown/layouted, but if the map is scrolled or zoomed the added views don't follow their geo-position. I'd expect them to always stay attached to their geo-position. Google Maps v1 handles this correctly.

I currently work around this by adding an overlay and from within Overlay.draw() I call myView.requestLayout(). It works, although the layouting only happens on the next frame of the scroll, resulting in slightly "wobbly" views.

### If it's a bug, version(s) of android this affects:

I tried on 9.0

### Version of osmdroid the issue relates to:

6.0.2

**Comment by monsieurtanuki** [comment]
Similar to #909

**Comment by monsieurtanuki** [comment]
Just PR'ed #1195

**Comment by monsieurtanuki** [comment]
I've just merged #1195, that puts back the calls to method `mapView.requestLayout`, which should solve this issue.
@schildbach Feel free to test.

**Comment by monsieurtanuki** [comment]
Then I guess we can close this issue, and if needed later you can create an enhancement issue.

**Comment by schildbach** [comment]
Any idea when 6.0.3 will be released?

**Comment by monsieurtanuki** [comment]
I need to fix #1196 first, but development-wise I think nothing else is expected.
