### ISSUE TITLE
MapController: Method for animating GeoPoints into view

### ISSUE THREAD

**Issue by schildbach** [osmdroid/osmdroid#1192]
## Issue Type

[x] Improvement

## Description and/or steps/code to reproduce the problem

I'm always missing a method to comfortably animate a number of GeoPoints into view. By this I mean that the final zoom and center point is chosen such that the given GeoPoints are just within view, but the view is as zoomed in as possible.

Currently (inheriting from my Google Maps v1-based code) I use a combination of zoomToSpan() and setCenter(), but it's not possible to combine these two into one animation. As far as I can tell, this API limitation is still the same in osmdroid.

### Version of osmdroid the issue relates to:

6.0.2

**Comment by monsieurtanuki** [comment]
@schildbach I think what you describe can be done with method `mapView.zoomToBoundingBox`, can't it?

**Comment by schildbach** [comment]
Yes, you're right. Didn't expect that method on MapView itself, since all movement-related methods are in the controller. Thanks for the hint!
