### ISSUE TITLE
No Automatic Zoom Controls in Latest 6.0.3-SNAPSHOT?

### ISSUE THREAD

**Issue by InI4** [osmdroid/osmdroid#1196]
I actually wanted to reopen #825 , but I either lack the rights to do so, or I do not find the corresponding action on the site.

## Issue Type

[X ] Question
[X] Bug
[X ] Documentation

## Description and/or steps/code to reproduce the problem

Automatic Zoom Controls do not happen any more:

In my app I had zoom controls appear automatically when map is tapped, this used to work fine with 6.0.2 and with some previous 6.0.3 snapshots, but does not seem to happen with the current snapshot any more: I simply do not get zoom controls at all now. 

Is this a regression?
Do I need to handle the API differently?
For example implement the reaction to the tap myself?

## Environment

Own App, 
Android 9 and 4,2.2, but I guess, this is not the problem
Build job gradle changed from 6.0.2 release to 6.0.3-SNAPSHOT

### If it's a bug, version(s) of android this affects:

Android 9 and 4,2.2, but I guess, this is not the problem

### Version of osmdroid the issue relates to:

6.0.3-SNAPSHOT

**Comment by monsieurtanuki** [comment]
@InI4 With the latest 6.0.3-SNAPSHOT you're supposed to have _different_ zoom buttons: not the standard and to-be-deprecated Android ones, but custom made ones.

If you use the demo, can you at least see those zoom buttons?

The new zoom buttons are directly drawn on the `MapView` canvas, and by default are horizontally centered and at the bottom (like the standard version). Could it be that your `MapView`'s child views hide the canvas at this part of the screen (I couldn't tell I never use child views).

How to control the zoom buttons:
* `mapView.getZoomController().setVisibility`
* `mapView.getZoomController().getDisplay()` setters

**Comment by InI4** [comment]
LOL, Ok, I found them. It is a bit like you say, but not entirely: To see which version is running I have a greyish "Debug" label over the bottom center of the map in debug builds. The buttons are now below that.

But there are more problems with the buttons:

1. They are very tiny. I needed to rescale them to         `mMap.getZoomController().getDisplay().setDrawingSizes(140, 80.0f, 10); ` to make them reasonable sized (slightly bigger than the old ones then. Nice!
1.  The left and the right bottom (Zoom in and out) are exchanged compared to previous version.
1. The Minus-Icon is 90° rotated, i.e. a vertical bar.

Cannot all be my sucking app, can it?

**Comment by monsieurtanuki** [comment]
My comments:
1. the fact that you didn't see the buttons because you have a (presumably) child view on top of it means that drawing directly on the map canvas may not be the right solution. Having child views for zoom buttons on top of every other child views?
1. regarding size, I'm going to create png files in the res/drawable drawers. Same size as `ic_center_map` (mdpi 48 pixels, h 72, xh 96, xxh 144, xxxh 192). I'll also remove `CustomZoomButtonsDisplay.setDrawingSizes`.
1. fair enough. Easy to fix
1. very strange! Will probably be fixed using png files.

**Comment by monsieurtanuki** [comment]
Oh, I'll keep the same design.

**Comment by monsieurtanuki** [comment]
I've just tried with 48dp icons: they look too big. And they are twice as tall as the standard zoom buttons.

@InI4 I suggest we go for the 36dp version (see examples below), I think they look OK. If the click zone seems too little, we can make it bigger than the icon. What do you think about it?

Here with 48dp buttons:
![device-2018-11-17-191753](https://user-images.githubusercontent.com/11576431/48663780-ae4f5580-ea9d-11e8-969b-6f245bb8156a.png)

Here with 36dp buttons:
![device-2018-11-17-193536](https://user-images.githubusercontent.com/11576431/48663943-10a95580-eaa0-11e8-8546-b6be91eca9c0.png)

Here with 24dp buttons:
![device-2018-11-17-194005](https://user-images.githubusercontent.com/11576431/48663986-a1803100-eaa0-11e8-95b3-f28b2bf429e7.png)

**Comment by InI4** [comment]
Yes, 36dp look good here. 

BTW I actually didn't want to censor your button scaling feature, my initial proposal targeted more in the direction of useful defaults: The buttons I got (then) were more like 10dp compared to your screenshots.

**Comment by monsieurtanuki** [comment]
@InI4 OK for 36dp then.
Oh, anyway the button scaling feature was not such a good idea.
Just PR'ed #1198: ready to test?

**Comment by InI4** [comment]
Just did a new build of my app, but the snapshot isn't updated yes, is it?

**Comment by monsieurtanuki** [comment]
The snapshot is now up to date.

**Comment by InI4** [comment]
Works here and looks good!

**Comment by monsieurtanuki** [comment]
@spyhunter99 As you used to work on the custom zoom buttons feature, any comment about the latest version?

**Comment by InI4** [comment]
Ah, sry, for being slow, another party spoiler might be the `setMarginPadding()` method. It is very hard to find numbers where the controls are actually displayed. I do not believe, this is intended. I will look into it more, but just wanted to issue the warning in time. And, I think this API is needed, however, it needs to get fixed.

- `setMarginPadding(0,0)` - buttons smashed together
- `setMarginPadding(25,16)` - buttons gone, though these numbersshould be the default according to source of constructor AS shows me.
- `setMarginPadding(1,1)` - buttons shifted wide and in huge distance
- `setMarginPadding(2,2)` - buttons shifted even further wide and in huge distance

It seems like the distance is not pixels, but rather "half buttons" or so. I will have a closer look into this.

**Comment by monsieurtanuki** [comment]
@InI4 Regarding margin and padding the unit is not pixel but "fraction of the zoom icon", the default values being `.5f` for each.

**Comment by InI4** [comment]
@monsieurtanuki I realized, somehow Android Studio presented me the decompiled sources of the previous snapshot. All fine and working! Sorry for realizing too late.

**Comment by monsieurtanuki** [comment]
@InI4 What about closing this issue?
I believe that's the last pending issue for the next release.
