### ISSUE TITLE
Question about north must be in [-85.05112877980659,85.05112877980659] crash

### ISSUE THREAD

**Issue by Bubu** [osmdroid/osmdroid#1206]
## Issue Type

[x] Question
[ ] Bug
[ ] Improvement
[ ] Build system related
[ ] Performance
[ ] Documentation

We are getting a crash in out Telegram-FOSS version as described here: https://github.com/Telegram-FOSS-Team/Telegram-FOSS/issues/275 (full stacktrace there)

```
E/AndroidRuntime( 9958): java.lang.IllegalArgumentException: north must be in [-85.05112877980659,85.05112877980659]
E/AndroidRuntime( 9958): 	at org.osmdroid.util.BoundingBox.set(BoundingBox.java:67)
E/AndroidRuntime( 9958): 	at org.osmdroid.views.Projection.refresh(Projection.java:649)
```

As described in that issue I tried investigating where this might come from but are currently stuck. It's not directly triggered by our application code but instead seems to happen in a re-draw cycle? Any ideas what we might be doing wrong here? 

### Version of osmdroid the issue relates to:

6.0.3

**Comment by spyhunter99** [comment]
those are the maximum bounds allowed by the web mercator projection. any idea what the offending coordinate is or where it is coming from?

**Comment by schildbach** [comment]
I've got a similar problem:

```
 java.lang.IllegalArgumentException: south must be in [-85.05112877980659,85.05112877980659]
at org.osmdroid.util.BoundingBox.set(BoundingBox.java:69)
at org.osmdroid.util.BoundingBox.<init>(BoundingBox.java:43)
at org.osmdroid.util.BoundingBox.increaseByScale(BoundingBox.java:260)
```

As you can see, in my case it's `increaseByScale()` whch violates the boundary. I'd argue some clipping should happen (maybe optional), otherwise any code transforming map coordinates will soon look like a try/catch warzone.

**Comment by schildbach** [comment]
And in this case
```
java.lang.IllegalArgumentException: east must be in [-180.0,180.0]
        at org.osmdroid.util.BoundingBox.set(BoundingBox.java:73)
        at org.osmdroid.util.BoundingBox.<init>(BoundingBox.java:43)
        at org.osmdroid.util.BoundingBox.increaseByScale(BoundingBox.java:260)
```

I'd say the longitude should be wrapped.

**Comment by schildbach** [comment]
> Feel like coding it?

Yeah, why not. If this topic has been discussed before, feel free to point me at it.

**Comment by monsieurtanuki** [comment]
Actually I cannot remember other issues about these limits or more specifically about method `increaseByScale`.
I guess all you need to know for a new overloaded version of method `increaseByScale` is in the comments of this issue.

**Comment by schildbach** [comment]
See https://github.com/osmdroid/osmdroid/pull/1208

**Comment by s-ilnar** [comment]
I have the same problem.

` Caused by: java.lang.IllegalArgumentException: south must be in [-85.05112877980658,85.05112877980658]
        at org.osmdroid.util.BoundingBox.set(BoundingBox.java:69)
        at org.osmdroid.util.BoundingBox.<init>(BoundingBox.java:43)`


```
BoundingBox boundingBox = new BoundingBox(maxLat, maxLong, minLat, minLong);
mapView.zoomToBoundingBox(boundingBox.increaseByScale(1.3f), false);
mapController.setCenter(boundingBox.getCenterWithDateLine());
```

**Comment by monsieurtanuki** [comment]
@Bubu Is your problem now fixed, using @schildbach's #1208 or not?

**Comment by Bubu** [comment]
AFAIK the problem disappeared at some point. I'm somehow remembering that we weren't able to reproduce it anymore even before integrating this patch, but either way this doesn't really matter all that much now.

**Comment by schildbach** [comment]
My contribution fixes the issue for east/west. For north/south, it still happens occasionally.

**Comment by monsieurtanuki** [comment]
@Cetusek The problem is not with your bounding box north `to be in [-85.05112877980658,85.05112877980658]`, as it's `51.1199983`. I think the problem comes from the fact that in your case north==south. Trying to zoom to that bounding box doesn't make much sense, does it?
* do you have the issue when north and south are different?
* could you try with `zoomToBoundingBox(polyline.getBounds(), false, 50, 10, null)` instead, where 10 is the arbitrary max zoom level for `zoomToBoundingBox`?

**Comment by Cetusek** [comment]
You are right. I have the test path consisting of two poins which lie on the same parallel. So north == south. I wanted to show it centered on the map. Now I know I have to chage slightly the bounds in this case. But the excepion message is misleading. Thank you for your explanation.

**Comment by Cetusek** [comment]
It doesn't work. I made the test:

```
Log.i("MY_APP", "bounds: "+polyline.getBounds().toString());
polyline.getBounds().setLatSouth(polyline.getBounds().getLatSouth() + 0.01);
polyline.getBounds().setLonWest(polyline.getBounds().getLonWest() + 0.01);
Log.i("MY_APP", "bounds: "+polyline.getBounds().toString());
zoomToBoundingBox(polyline.getBounds(), false, 50);
```
Result is:
```
I/MY_APP: bounds: N:51.1199983; E:19.199; S:51.1199983; W:19.12
I/MY_APP: bounds: N:51.1199983; E:19.199; S:51.1299983; W:19.130000000000003
I/MY_APP: uncaught exception: java.lang.IllegalArgumentException: north must be in [-85.05112877980658,85.05112877980658]
        at org.osmdroid.util.BoundingBox.set(BoundingBox.java:74)
        at org.osmdroid.views.Projection.refresh(Projection.java:705)
        at org.osmdroid.views.Projection.<init>(Projection.java:111)
        at org.osmdroid.views.Projection.<init>(Projection.java:123)
        at org.osmdroid.views.MapView.zoomToBoundingBox(MapView.java:558)
        at org.osmdroid.views.MapView.zoomToBoundingBox(MapView.java:584)
        at pl.marek.stepwatcher.map.presenter.OsmMapPresenter.showRoute(OsmMapPresenter.java:278)
```
With the line ```zoomToBoundingBox(polyline.getBounds(), false, 50, 10, null)``` is the same.

**Comment by wogno** [comment]
Hi. I have the same issue when I use ShapeConvertisor.convert(map. shapfile). Can I get your solution, please?
