### ISSUE TITLE
BoundingBox: 360 degrees vs 180 degrees?

### ISSUE THREAD

**Issue by schildbach** [osmdroid/osmdroid#1207]
https://github.com/osmdroid/osmdroid/blob/e1ab630826f7b360d39a81ab96f57328f5e6bb51/osmdroid-android/src/main/java/org/osmdroid/util/BoundingBox.java#L223

Maybe I'm wrong, but a couple of times in this class only 180° is used as a "wrap around delta" for longitude, rather than 360°. Can this be right?

**Comment by monsieurtanuki** [comment]
@schildbach I believe you're right, it looks like a mistake. I guess `org.osmdroid.views.MapView.getTileSystem().cleanLongitude(longitude);` should be used more systematically in `BoundingBox`.

Additional remarks:
* it's still `180` that we should use in `static` method `getCenterLongitude` (as there was a division by 2 just before)
* btw, does method `increaseByScale` makes sense anyway, multiplying the latitude and the longitude by the same factor? Aren't there more relevant ways to make a `BoundingBox` bigger / smaller?
