### ISSUE TITLE
Some of the markers shown on wrong position when dragging map with 6.0.3 ONLY

### ISSUE THREAD

**Issue by wharnisch** [osmdroid/osmdroid#1213]
Sometimes all markers are drawn on right positions, sometimes some of the markers shown on wrong position when dragging map - they seem to move in the same directions as the dragging, but with greater speed.  Some others of the marker are drawn on right position. 

## Issue Type

[ ] Question
[ x] Bug
[ ] Improvement
[ ] Build system related
[ ] Performance
[ ] Documentation

## Description and/or steps/code to reproduce the problem

Sorry but till now I don't know how to reproduce this - still trying.

### If it's a bug, version(s) of android this affects:

All

### Version of osmdroid the issue relates to:

6.0.3

Same source code of adding markers worked without problems at least with versions 6.0.0 to 6.0.2

**Comment by wharnisch** [comment]
Found a workaround to prevent the problem:

Subclassed the "Marker" class. Overrided "draw" method like this:

  @Override
  public void draw(Canvas canvas, MapView mapView, boolean shadow)
  {
    canvas.save();
    canvas.setMatrix(new Matrix());
    super.draw(canvas, mapView, shadow);
    canvas.restore();
  }

This prevents the problem to occur.

**Comment by monsieurtanuki** [comment]
I don't manage to reproduce this issue.
Very strange.
But if you have a fix that means you are able to reproduce the issue: could you create a tiny demo where this bug happens? Something like "if I have a map with that zoom/center, and 4 markers, then if I pan the map the markers go faster than the map".
Btw I checked in the code and couldn't see anything related to a bad canvas.save / canvas.restore operation.

**Comment by wharnisch** [comment]
Found the problem - my fault - sorry.

Problem is: my app draws many markers. Some of the Icons of the markers are from resources, some of them are drawn programmatically (by subclassing Drawable). In one of the Drawables drawn programmatically 'canvas.translate' was called without being reset. So when all the markers are drawn by osmdroid as long as only icons from resources are drawn everything is ok. As soon as the first marker using a Drawable implemented programmatically (containing 'canvas.translate') is drawn, all the following markers are translated to wrong positions and the error grows after each programmatically drawn Drawable.

osmdroid 6.0.0 to 6.0.2 was not affected by this, osmdroid 6.0.3 is affected. I suppose this is because of 'optimization 2' in 'drawAt' method of Marker in 6.0.3.

I now solved the problem by calling canvas.save/canvas.restore in the draw method of my subclassed Drawable.

Regards and sorry again

**Comment by monsieurtanuki** [comment]
No problem!
Actually the "optimization 2 in drawAt" wasn't only optimization but also included a bug fix.

My 2 cents: if you can avoid the "canvas.save/restore" operation, it's better for the performances. And if you only use "translate" and draw programmatically, I assume you can replace your "translate" operation using offsets in your draw operations.
