### ISSUE TITLE
Code Cleanup

### ISSUE THREAD

**Issue by cbalster** [osmdroid/osmdroid#1214]
## Issue Type

[x ] Improvement

## Description and/or steps/code to reproduce the problem

There's quite a lot of misc cleanup to be done that accumulated over time.
This seems like a good time for a first step.

### Version of osmdroid the issue relates to:

6.0.3

**Comment by monsieurtanuki** [comment]
I guess it's done now, isn't it?

**Comment by cbalster** [comment]
There is more to do but this can be closed after #1215
