### ISSUE TITLE
Fast clic on new zoom buttons

### ISSUE THREAD

**Issue by MKergall** [osmdroid/osmdroid#1218]
## Issue Type

[ ] Question
[X ] Bug
[ ] Improvement
[ ] Build system related
[ ] Performance
[ ] Documentation

## Description and/or steps/code to reproduce the problem
Click quickly and repeatedly on the Minus zoom button: in many cases, clicks are not handled as clicks on the zoom-out button, but as clicks on the map => thus zooming in again. 

Same issue of course with the Plus zoom button, but less obvious as the consequence is also a zoom-in. 

(except this - annoying - issue, those new zoom buttons are quite good)

## Environment
Happens both on emulator (with the mouse), and tapping on an actual device. 

### Version of osmdroid the issue relates to:
6.0.3

**Comment by monsieurtanuki** [comment]
Fixed in #1219

**Comment by monsieurtanuki** [comment]
@MKergall Feel free to reopen if not solved by #1219.
