### ISSUE TITLE
Add doc about Milestones

### ISSUE THREAD

**Issue by pasniak** [osmdroid/osmdroid#1226]
## Issue Type

[ ] Question
[ ] Bug
[ ] Improvement
[ ] Build system related
[ ] Performance
[x] Documentation

## Description 
I gather this is powerful but I am struggling to figure out how those classes compose.

### If it's a bug, version(s) of android this affects:

All

### Version of osmdroid the issue relates to:

6.0.2

**Comment by monsieurtanuki** [comment]
I'm struggling too, though I designed them!
You're right, I should write a doc about them.

**Comment by spyhunter99** [comment]
the demos are pretty awesome. animation is quite cool! so, there's that.

**Comment by pasniak** [comment]
The marathon one? Yes it is quite impressive but complicated.   I was looking for some simple stuff, place text (based on x) in the middle of line; every x miles; change line color every x km...

**Comment by monsieurtanuki** [comment]
I've just added a page in the wiki: [Milestones feature](https://github.com/osmdroid/osmdroid/wiki/Milestones-feature)
Tell me what you think.
