### ISSUE TITLE
tileSizePixels should be removed from constructor

### ISSUE THREAD

**Issue by enderk** [osmdroid/osmdroid#123]
Currently tilesizePixel provided by ITileSource and keeping it at MapView constructor confusing

**Comment by neilboyd** [comment]
That would make for some very awkward calculations

**Comment by kurtzmarc** [comment]
IIRC we don't even use the tileSize passed to the constructor. See also this comment in [#81](https://github.com/osmdroid/osmdroid/issues/81#issuecomment-93753519).
