### ISSUE TITLE
error: cannot find symbol class GeoPackage and so on

### ISSUE THREAD

**Issue by anonym24** [osmdroid/osmdroid#1231]
![screenshot_18](https://user-images.githubusercontent.com/8851301/49857050-305f3f80-fdfa-11e8-895c-0dee727aca02.png)

**Comment by spyhunter99** [comment]
does it build via the command line? how did you get this error message?

**Comment by HelgeApps** [comment]
@spyhunter99 I just opened the project in Android Studio

**Comment by anonym24** [comment]
@spyhunter99 I just opened the project in Android Studio

**Comment by anonym24** [comment]
Nevermind. Seems **OpenStreetMapViewer** is for production (Google Play) anyway.

as I understand I need **osmdroid-simple-map**

In `settings.gradle` we can remove OpenStreetMapViewer and other

```
//libraries
include ':osmdroid-android'
include ':osmdroid-mapsforge'
include ':osmdroid-geopackage'
include ':osmdroid-wms'

//sample apps
//include ':OpenStreetMapViewer'

include ':osmdroid-simple-map'

//jdk specific tools and applications
//include ':OSMMapTilePackager'
//include ':osmdroid-server-jdk'

//dist package
include ':osmdroid-dist'

```
