### ISSUE TITLE
OSMDroid map fails to open with some devices.

### ISSUE THREAD

**Issue by fariz-sirajli** [osmdroid/osmdroid#1232]
Hi. My app works perfectly but recently i realized that it does not show tiles in some devices. I researched error message on web and found this 
https://stackoverflow.com/questions/40100080/osmdroid-maps-not-loading-on-my-device
It's exactly the same case. The solution suggested there (Changing default location of Sqlite db)is not actual now. Following function are not found

OpenStreetMapTileProviderConstants.setCachePath(...)
OpenStreetMapTileProviderConstants.setCacheSizes(...)
OpenStreetMapTileProviderConstants.setOfflineMapsPath(...)
OpenStreetMapTileProviderConstants.setUserAgentValue(...)
So how can i solve it?
Thanks for attention.

**Comment by spyhunter99** [comment]
`Configuration.getInstance()...`

**Comment by spyhunter99** [comment]
Also the wiki references this. https://github.com/osmdroid/osmdroid/wiki/FAQ#can-i-change-where-osmdroid-looks-for-tile-archives-and-the-location-of-the-tile-cache
