### ISSUE TITLE
SimpleFastPointOverlay text labels not rotated (and hard to read)

### ISSUE THREAD

**Issue by pasniak** [osmdroid/osmdroid#1234]
[ ] Question
[ ] Bug
[x] Improvement
[ ] Build system related
[ ] Performance
[ ] Documentation

## Description and/or steps/code to reproduce the problem

setMapOrientation() on a map containing SimpleFastPointOverlay with text labels; the labels are not rotated (and hard to read upside down...)

See below on how I fixed the labels in my class inheriting from SimpleFastPointOverlay

### Version of osmdroid the issue relates to:
master around 6.1.0

```
    protected void drawPointAt(Canvas canvas, float x, float y, boolean showLabel, String label, Paint pointStyle, Paint textStyle) {

        canvas?.save()
        canvas?.rotate(-mapView.mapOrientation, x, y)

        if(mStyle.mSymbol == SimpleFastPointOverlayOptions.Shape.CIRCLE)
            canvas.drawCircle(x, y, mStyle.mCircleRadius, pointStyle);
        else
            canvas.drawRect(x - mStyle.mCircleRadius, y - mStyle.mCircleRadius
                    , x + mStyle.mCircleRadius, y + mStyle.mCircleRadius
                    , pointStyle);

        if(showLabel && label != null)
            canvas.drawText(label, x, y - mStyle.mCircleRadius - 5, textStyle);

        canvas?.restore()
    }



```

**Comment by monsieurtanuki** [comment]
@pasniak Feel free to PR.

My 2 cents: in your code, check first if the map orientation equals 0. In this case you can avoid the canvas operation you added (save/rotate/restore), for better performances.

**Comment by spyhunter99** [comment]
working it now
