### ISSUE TITLE
 DefaultResourceProxyImpl  

### ISSUE THREAD

**Issue by omfg74** [osmdroid/osmdroid#1238]
Please note: issues related to or caused by osmbonuspack will be closed with a
suggestion to open an issue at https://github.com/MKergall/osmbonuspack

(feel free to delete whatever doesn't apply)

## Issue Type

[  DefaultResourceProxyImpl  can not resolve ] Question
[  DefaultResourceProxyImpl  does not exists] Bug
[ ] Improvement
[ ] Build system related
[ ] Performance
[ ] Documentation

## Description and/or steps/code to reproduce the problem

Cant extend  DefaultResourceProxyImpl  when trying to create custom resoaurce proxy

### If it's a bug, version(s) of android this affects:

All

### Version of osmdroid the issue relates to:

6.0.2

**Comment by spyhunter99** [comment]
It was removed a few years ago. No longer needed nor necessary. what problem are you trying to solve?

**Comment by omfg74** [comment]
I was trying to add my own bitmaps to the map instance and i did not find how to do it. Also i could not find a large documentation on osmdroid

**Comment by spyhunter99** [comment]
nearly everything has some kind of `setImage` or `setIcon` method. What documentation are you missing? There's a lot in the wiki, the github site, javadocs, sample projects, etc..

**Comment by spyhunter99** [comment]
reopen if needed

**Comment by scaidermern** [comment]
https://github.com/osmdroid/osmdroid/wiki/How-to-use-the-osmdroid-library#create-a-custom-resource-proxy still refers to `DefaultResourceProxyImpl`, doesn't it?

**Comment by spyhunter99** [comment]
the very next line is....

````
Applies only to versions prior to 5.2
````
