### ISSUE TITLE
tileSize should provide X and Y (width and height) separately

### ISSUE THREAD

**Issue by enderk** [osmdroid/osmdroid#124]
Map tile should not have to be square.

**Comment by neilboyd** [comment]
That would make for some very awkward calculations

**Comment by spyhunter99** [comment]
@enderk what's the use case for this?

**Comment by enderk** [comment]
Sorry for late response, so basically we have a game project, which has a map, using rectangular images which are produced by iso hexagon. Can be checked at


http://beta.medievan.com

**Comment by spyhunter99** [comment]
Pist, you're going to want to switch to SSL. Passwords in the clear are not cool.

Anyhow, assuming you're building a mobile version of that app, the best recommendation I can give is to preprocess the map imagery and host them on your web site. There's a bunch of tools you can use to do this, Geoserver, MOBAC, and probably many more.

Looks cool by the way!

**Comment by spyhunter99** [comment]
going to close this as it's not easily implemented since we heavily rely on osm slippy map still crs
