### ISSUE TITLE
download map

### ISSUE THREAD

**Issue by Bird-Gold** [osmdroid/osmdroid#1248]
Can you do a background download map management? Open the service download

**Comment by monsieurtanuki** [comment]
@Bird-Gold Something like [`CacheManager`](https://github.com/osmdroid/osmdroid/blob/master/osmdroid-android/src/main/java/org/osmdroid/tileprovider/cachemanager/CacheManager.java)?

**Comment by monsieurtanuki** [comment]
@Bird-Gold Did that answer your question? If so, please close the issue.

**Comment by monsieurtanuki** [comment]
Assuming the CacheManager was the solution, I'm closing the issue.
@Bird-Gold Feel free to open a new issue if needed.
