### ISSUE TITLE
Get one single tile from TilesOverlay in Osmdroid

### ISSUE THREAD

**Issue by khnoize** [osmdroid/osmdroid#1249]
Hello, I'm on 6.0.2, and currently, I've added an overlay from geoserver using XYTileSource.

       GeoserverTile tileRoadsEtc = new GeoserverTile(context,wmsName,
                0,18,256,
                "png",GeoserverTile.TILE_URL);
        MapTileProviderBasic tileHolder = new MapTileProviderBasic(context);
        tileHolder.setTileRequestCompleteHandler(mv.getTileRequestCompleteHandler());
        tileHolder.setTileSource(tileRoadsEtc);
        TilesOverlay tilesOverlay = new TilesOverlay(tileHolder,context);
        tilesOverlay.setLoadingBackgroundColor(Color.TRANSPARENT);
        mv.getOverlays().add(tilesOverlay);
        mv.invalidate();

With GeoserverTile extending class XYTileSource.

I might not fully understand, but I think that TilesOverlay here consists of multiple tiles that together form the looks of the geoserver overlay.

Now I need to create a situation where when I click somewhere in the mapview, I can get one single tile from the TilesOverlay above, that located in place where I clicked. Is that possible?

Later, I will also need the bounding box, and x/y position of that tile. Thank you.

**Comment by monsieurtanuki** [comment]
When you click on a `MapView` you can get the `GeoPoint` of your click pixel.
From the `GeoPoint` and the current zoom level you can compute the corresponding tile id (something like z,x,y).
From the tile id you can get:
* the actual 256x256 bitmap (that will almost never be centered on your click, though)
* the tile bounding box

@khnoize Is that what you want?

**Comment by khnoize** [comment]
Yes, I think so. Now, I have computed the GeoPoint and zoom level using this guide:
https://wiki.openstreetmap.org/wiki/Slippy_map_tilenames#Lon..2Flat._to_tile_numbers_2

And now I have the tile id like:
"zoom: 12, xtile: 3329, ytile: 2141".

Now, how do I get the actual 256x256 bitmap and the tile bounding box?

Thank you.

**Comment by khnoize** [comment]
I'm sorry that probably I still don't really understand many things surrounding these. So I'm still going around bounding box this time.

So, I've tried your code above, with slight modification as some functions no longer exists (for example, there's no "getTileSystem().getLongitudeFromTileX()" function in osmdroid 6.0.2, but it has "getTileSystem().getLongitudeFromX01()", but minus the zoom parameter). So, I'm not really sure if I would have the correct result.

    private void test1249(final double pDoubleZoomLevel, final MotionEvent e) {
        final Point point = new Point();
        mapView.getProjection().rotateAndScalePoint((int) e.getX(), (int) e.getY(), point);
        final double tileSize = TileSystem.getTileSize(pDoubleZoomLevel);
        final int zoom = (int) pDoubleZoomLevel;
        final int maxTile = 1 << zoom;
        int tileX = TileSystem.getTileFromMercator(mapView.getProjection().getMercatorXFromPixel(point.x), tileSize);

        while(tileX < 0) {
            tileX += maxTile;
        }
        while(tileX >= maxTile) {
            tileX -= maxTile;
        }
        int tileY = TileSystem.getTileFromMercator(mapView.getProjection().getMercatorYFromPixel(point.y), tileSize);
        while(tileY < 0) {
            tileY += maxTile;
        }
        while(tileY >= maxTile) {
            tileY -= maxTile;
        }
        Log.e("MapView", "zoom:" + zoom);
        Log.e("MapView", "tileX:" + tileX);
        Log.e("MapView", "tileY:" + tileY);

        final double west = getTileSystem().getLongitudeFromX01(tileX);
        final double east = getTileSystem().getLongitudeFromX01((tileX + 1) % maxTile);
        final double north = getTileSystem().getLatitudeFromY01(tileY);
        final double south = getTileSystem().getLatitudeFromY01((tileY + 1) % maxTile);
        Log.e("MapView", "north:" + north);
        Log.e("MapView", "east:" + east);
        Log.e("MapView", "south:" + south);
        Log.e("MapView", "west:" + west);
    }

Above code gave me following result:

    30935-30935/com.example.app E/MapView: zoom:12
    30935-30935/com.example.app E/MapView: tileX:3329
    30935-30935/com.example.app E/MapView: tileY:2139

    30935-30935/com.example.app E/MapView: north:-90.0
    30935-30935/com.example.app E/MapView: east:1198620.0
    30935-30935/com.example.app E/MapView: south:-90.0
    30935-30935/com.example.app E/MapView: west:1198260.0

The coordinates for the bounding box is nowhere near my location where I click at the mapview. I've clicked around "-8.037988, 112.641901" coordinate, in Indonesia, but the bounding box coordinates the code gave me was "-90.0,1198620.0,-90.0,1198260.0", which nowhere to be found in the map.

Could you please point me where I go wrong? Or is this have something to do about the projection, as the default projection of osmdroid is "EPSG:3857", while I'm trying to justify the result on "EPSG:4326" in mind?

**Comment by monsieurtanuki** [comment]
@khnoize [Meet the future](https://www.youtube.com/watch?v=P_5l6rIUu4A): `getTileSystem().getLongitudeFromTileX()` was introduced in version 6.0.3.
As 6.0.3 is not deemed 100% stable by some users I would not recommend you to use this version just for this method; you'd be better off (at least temporarily) [copying the code](https://github.com/osmdroid/osmdroid/blob/master/osmdroid-android/src/main/java/org/osmdroid/util/TileSystem.java#L739).

By the way it's rather bold to assume that methods with similar names have the same results - cf. `Math.cos`, `Math.acos` and `Math.cosh` ;)

I'm not an expert on EPSG projections; regarding the "EPSG:3857" / "EPSG:4326" possible confusions you may have to implement your own `TileSystem` (cf. [`TileSystemWebMercator`](https://github.com/osmdroid/osmdroid/blob/master/osmdroid-android/src/main/java/org/osmdroid/util/TileSystemWebMercator.java), #971).

**Comment by khnoize** [comment]
Solved my issues regarding this, thank you very much for your helps!
