### ISSUE TITLE
Get Tile XY Coordinate By Variables (Lat/Long, Bounding Box, Zoom Level)

### ISSUE THREAD

**Issue by khnoize** [osmdroid/osmdroid#1252]
So, Now I have the map tile I need on issue:
https://github.com/osmdroid/osmdroid/issues/1249

And having variables such as:
- Lat/long
- Zoom level
- Bounding box of the tile

How do I get the exact x/y coordinate of the tile (256 x 256 in size), which is at the same time, located at the lat/long coordinate that I have in the mapview, using above variables? Or if there are more variables that I need, please tell me.

Thank you.

**Comment by monsieurtanuki** [comment]
@khnoize I'm not sure I understand what you want. `TileSystem.getTileXFromLongitude` perhaps?

**Comment by khnoize** [comment]
Um, I am on 6.0.3, and there are no "getTileXFromLongitude" from "TIleSystem" in that version of osmdroid. Also, I'm not sure, but I think, from the naming, it would return something like "x:3000, y:2000"? Which I usually get from computing lat, long, and zoom level.

But the result I need is the x/y of the tile, and since my tile size is 256, the returning value should be no more than that, like "x:128 / y:75" or so.

What I mean is, for example, I have:
```
lat: -8.102738577783164
longitude: 112.67578125
```

And I have the map tile, which is pointed by above lat/long. So, inside that tile, what value of the tile's x/y that the lat/long above pointing?

That's what I'm currently looking, and I hope my sentences can be better and clear enough, since I'm not a native speaker, I'm really sorry if that was not good enough and probably confusing. Thank you Mr. @monsieurtanuki .

**Comment by khnoize** [comment]
`if I were you I would use Projection.toPixels, to be applied to your North-West corner, your South-West corner, and the click GeoPoint, then use a rule of three in order to compute the [0,1] values of your X and Y`

Thank you. I hope it's not too much to ask, but please show me how it's done for, let's say I have a coordinate and the tile bounding box as follows:

```
Lat: -7.009802414125957
Long: 113.96199790692953
Tile bounding box: -7.010941890090234,113.961181640625,-7.008215836663404,113.96392822265625
```
How should I implement your suggestion into java using osmdroid?

**Comment by monsieurtanuki** [comment]
````
final double xBetween0and1 = ((double) 461 - 113) / (582 - 113)
final double yBetween0and1 = ((double) 1192 - 922) / (1392 - 922)
````

**Comment by khnoize** [comment]
```
final double xBetween0and1 = ((double) 461 - 113) / (582 - 113)
final double yBetween0and1 = ((double) 1192 - 922) / (1392 - 922)
```

Wow, thank you so much! Just solved my issues with your helps! Really appreciate it. Thank you so much for your patience.
