### ISSUE TITLE
Problem in wiki

### ISSUE THREAD

**Issue by hatamiarash7** [osmdroid/osmdroid#1268]
## Issue Type

- Documentation

## Description and/or steps/code to reproduce the problem

There is a problem in wiki page. [This section](https://github.com/osmdroid/osmdroid/wiki/How-to-use-the-osmdroid-library#how-do-i-place-icons-on-the-map-with-a-click-listener)

The `ItemizedOverlayWithFocus()` function need context but it's not mentioned in the wiki

`public ItemizedOverlayWithFocus(final Context pContext, final List<Item> aList, final OnItemGestureListener<Item> aOnItemTapListener)`

**Comment by spyhunter99** [comment]
thanks, it's been updated

**Comment by neoacevedo** [comment]
The Wiki also needs to be updated in [Tile Caching](https://github.com/osmdroid/osmdroid/wiki/Tile-Caching) section. Currently are some deprecated/unexisting methods for version 6.1.0
