### ISSUE TITLE
Update Polyline

### ISSUE THREAD

**Issue by tomwassink** [osmdroid/osmdroid#1269]
## Issue Type

[ ] Question

## Description and/or steps/code to reproduce the problem

I want to update a Polyline.  I add new points to the GeoPoint array and use setPoints to update Polyline. After that I call invalidate():

mPath.setPoints(points);
mMapView.invalidate();

With GoogleMaps API this works. Why does this not work?

### Version of osmdroid the issue relates to:

6.0.2

**Comment by MKergall** [comment]
I use the same method in my apps, and it works. Your issue is somewhere else. 
Provide more relevant code (including mPath declaration). 

(note that current osmdroid version is 6.0.3, but drawing a Polyline was working in 6.0.2)

**Comment by tomwassink** [comment]
Got it working! Thanks.

The issue was that you need to call the method setPoints before adding it to the MapView. This is not required for GoogleMaps.
