### ISSUE TITLE
Is there any way to draw a heading arrow on the current location circle?

### ISSUE THREAD

**Issue by Netpolice** [osmdroid/osmdroid#1271]
mBlueDot = new GroundOverlay();
                mBlueDot.setImage(getResources().getDrawable(R.drawable.circle));
               mBlueDot.setTransparency(0.5f);

Would like to have a heading arrow on the current location, showing which direction is heading in front.
Is there any method on this?

Thank you.

![image](https://user-images.githubusercontent.com/2885170/52938742-5fb39f00-339d-11e9-9487-cec1230543b4.png)

**Comment by MKergall** [comment]
For such need, I like the DirectedLocationOverlay. 
You can customize its icon, with setDirectionArrow(). 
And if it doesn't exactly fit your need, you can use its code (simple and clean) as a good starting base.

**Comment by Netpolice** [comment]
Thanks for your help. I added the DirectedLocationOverlay, however, is there any specify function I need to enable it? There is a arrow on the map but no change on the direction when rotate the device. Thank you.

**Comment by spyhunter99** [comment]
on top, meaning drawn on top of all other layers

**Comment by Netpolice** [comment]
Yes. There is another layers I have added on the mapview, now, the arrow is under the layer. Therefore, is there any way to add the DirectedLocationOverlay on top of all other overlays(layers).

**Comment by spyhunter99** [comment]
layers, aside from the map files, are drawn in reverse order, so removing and readding the directed overlay when you add to new layers should do the trick. you can also override the defaultoverlaymanager and do your own drawing routines to force a specific draw order

**Comment by MKergall** [comment]
@Netpolice  DirectedLocationOverlay is not "self-animated". You will have to handle its positionning/bearing yourself.

**Comment by Netpolice** [comment]
@MKergall I thought it is "self-animated", but I solved this problem already. Getting the current bearing and setBearing() to the DirectedLocationOverlay  ^^

Now, there is only the layer problem, may try @spyhunter99 suggestion.

Thank you both.
