### ISSUE TITLE
How to show an offline mapsforge map initially/immediately when the app starts?

### ISSUE THREAD

**Issue by TomasJohansson** [osmdroid/osmdroid#1272]
## Issue Type

[x] Question
[x] Bug
[ ] Improvement
[ ] Build system related
[ ] Performance
[x] Documentation

## Description and/or steps/code to reproduce the problem

Download the attached zip file "OsmDroidMapsforge_problem_showing_map_initially.zip" (680 kb) with a small Android project, including three small mapsforge maps (.map files) in an assets folder which should become copied into the tablet when running the app.
Unzip it and open it with Android Studio and run the app in a USB connected Android device.

## Environment

Android Studio 3.3.1.
I have tested the app in the attached zip file with two tablets (Android 4.4 and 7.1).
The below described behaviour is the same for both those tablets.

### If it's a bug, version(s) of android this affects:

All versions probably (at least 4.4 and 7.1 which I have tested)

### Version of osmdroid the issue relates to:

osmdroid 6.0.3 and mapsforge 0.8.0

## Problem

The problem is: How can you show a map with mapsforge files immediately when the app starts (i.e. without delaying with any further interaction such as e.g. clicking a button)?
It seems necessary with some kind of delay, for example triggering a dialog when the user can select a map file.
(while some things need to finish in the background I suppose?)

In the attached example code, it does not work when trying to show the map immediately, but there is also a workaround with some delay in a thread, and when that code is used then it works.
See the comments below at the end of the onCreate method.

```java
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        MapsForgeTileSource.createInstance(this.getApplication());

        Context ctx = getApplicationContext();
        Configuration.getInstance().load(ctx, PreferenceManager.getDefaultSharedPreferences(ctx));

        setContentView(R.layout.activity_main);
        mMapView = (MapView) findViewById(R.id.map);

        // Here is the relevant part:
        //showOfflineMaps(); // this does NOT work
        // However, the following works, but WHY ?
        showMapsforgeMapsDelayed(); // this method invokes the above method "showOfflineMaps" from a thread
    }
	
    private void showOfflineMaps() {
        final File[] maps = assetsFileHelper.getAllMapsforgeFilesInOsmDroidDirectory();

        XmlRenderTheme theme = null;
        MapsForgeTileSource fromFiles = MapsForgeTileSource.createFromFiles(maps, theme, "rendertheme-v4");
        MapsForgeTileProvider forge = new MapsForgeTileProvider(
                new SimpleRegisterReceiver(getApplicationContext()),
                fromFiles, null);

        mMapView.setTileProvider(forge);

        mMapView.getController().setZoom(fromFiles.getMinimumZoomLevel());
        mMapView.zoomToBoundingBox(fromFiles.getBoundsOsmdroid(), true);
    }
	
    private void showMapsforgeMapsDelayed() {
        final int milliseconds = 100; // 100 milliseconds seems to be enough for the maps to become displayed without having to click the GUI button
        final FragmentActivity activity = this;
        final Thread thread = new Thread(new Runnable() {
            public void run() {
                try {
                    Thread.sleep(milliseconds);
                } catch (InterruptedException e) {
                    e.printStackTrace();
                }
                activity.runOnUiThread(new Runnable(){
                    @Override
                    public void run() {
                        showOfflineMaps();
                    }
                });
            }
        });
        thread.start();
    }
```	

The following page has a section "Code setup":
https://github.com/osmdroid/osmdroid/wiki/Mapsforge

I suspect that some of that setup code is triggering something in the background but it will not have finished soon enough when the activity is created.
Maybe something is missing in that documentation?
Maybe there is some callback method that should be implemented to do something when everything needed has really finished in the background, rather than adding a delay as I did in the attached code example?
[OsmDroidMapsforge_problem_showing_map_initially.zip](https://github.com/osmdroid/osmdroid/files/2877001/OsmDroidMapsforge_problem_showing_map_initially.zip)

**Comment by monsieurtanuki** [comment]
Perhaps it's the infamous `post` bug: if you need to do something about the mapview display, you can put it in the `onCreate` part but embedded in a `mapview.post` syntax.

**Comment by TomasJohansson** [comment]
> Perhaps it's the infamous `post` bug: if you need to do something about the mapview display, you can put it in the `onCreate` part but embedded in a `mapview.post` syntax.

Thank you @monsieurtanuki 
It seems as it is the "zoomToBoundingBox" that needs to be used from the post method.
If I change the code I posted above for this issue, into the following, then indeed the map will be displayed:
```java
XmlRenderTheme theme = null;
final MapsForgeTileSource fromFiles = MapsForgeTileSource.createFromFiles(maps, theme, "rendertheme-v4");
MapsForgeTileProvider forge = new MapsForgeTileProvider(
        new SimpleRegisterReceiver(getApplicationContext()),
        fromFiles, null);
mMapView.setTileProvider(forge);
mMapView.getController().setZoom(fromFiles.getMinimumZoomLevel());
mMapView.post(
    new Runnable() {
        @Override
        public void run() {
            mMapView.zoomToBoundingBox(fromFiles.getBoundsOsmdroid(), true);
        }
    }
);
```

I suggest that the osmdroid developers put that information into the [documentation page for osmdroid-mapsforge](https://github.com/osmdroid/osmdroid/wiki/Mapsforge).

**Comment by monsieurtanuki** [comment]
It has nothing to do specifically with Mapsforge; it's just that there are some init steps for the `MapView` that need to be completed (among them: having a width and a height). Which explains the need of the `post` syntax.

I've just added a chapter in the [FAQ](https://github.com/osmdroid/osmdroid/wiki/FAQ).
@TomasJohansson Please feel free to close this issue if relevant.

**Comment by TomasJohansson** [comment]
Okay, so it is not *specific* for Mapsforge only, but it is applicable for Mapsforge code.
Therefore, IMHO, the [documentation code example for mapsforge](https://github.com/osmdroid/osmdroid/wiki/Mapsforge) could also be more clear about this, since it is currently written as if it is okay to invoke the methods in sequence.
(with "mMapView.getController()..." and then "mMapView.zoomToBoundingBox..." directly after)

I suppose it is a very common situation that you want to zoom automatically to the bounding box. (or is it not?)
If so, would it not be desirable to make the setup code easier i.e. with less verbose code, so that you can invoke those methods in sequence in an onReady method?
I mean, the osmdroid developers might add a convenience methods to be able to do something like this:

```java
protected void onCreate(Bundle savedInstanceState) {
	...
    mMapView.getController().setZoom(fromFiles.getMinimumZoomLevel());
    mMapView.zoomToBoundingBoxAfterLayoutHasCompleted(fromFiles.getBoundsOsmdroid(), true);
}
public class MapView extends ViewGroup implements IMapView, MultiTouchObjectCanvas<Object> {
    ...
    public void zoomToBoundingBoxAfterLayoutHasCompleted(final BoundingBox boundingBox, final boolean animated) {
        final MapView mMapView = this;
        post(
            new Runnable() {
                @Override
                public void run() {
                    mMapView.zoomToBoundingBox(boundingBox, animated);
                }
            }
        );
    }
}
```

Okay I can close the issue since there is a solution i.e. use the post method.
Thank you.

**Comment by monsieurtanuki** [comment]
@TomasJohansson Fair enough, I've just fixed the osmdroid vs. Mapsforge doc too.

I understand that the `View.post` syntax can be a bit annoying, but I'm not 100% convinced by your suggestion as there are other map set up cases (e.g. centering the map) that would need the same "AfterLayoutHasCompleted" additional methods.

The best we can do I guess is to be more explicit in the doc and in the code samples.

**Comment by vidhyablrgithub** [comment]
I ran this code. [OsmDroidMapsforge_problem_showing_map_initially.zip](https://github.com/osmdroid/osmdroid/files/2877001/OsmDroidMapsforge_problem_showing_map_initially.zip)

It is throwing 2023-12-10 17:53:48.029 15334-15440/egolabsapps.basicodemine.offlinemaps E/SQLiteLog: (1) no such table: tiles
2023-12-10 17:53:48.029 15334-15440/egolabsapps.basicodemine.offlinemaps W/OsmDroid: Error getting db stream: /0/0/0
    android.data
