### ISSUE TITLE
CPU usage MapView

### ISSUE THREAD

**Issue by tomwassink** [osmdroid/osmdroid#1273]
[X] Performance

## Description and/or steps/code to reproduce the problem

I have a fragment with a MapView. Code to initialize is as follows:

protected void initViews(){
		if (ContextCompat.checkSelfPermission(getActivity(), Manifest.permission.ACCESS_FINE_LOCATION) == PackageManager.PERMISSION_GRANTED) {
			mMapView.setTileSource(TileSourceFactory.MAPNIK);
			mMapView.setClickable(false);
			mMapView.setMultiTouchControls(true);
			mMapView.setBuiltInZoomControls(true);
			mMapController = mMapView.getController();
			setMapZoomlevel();

			mListCounter = 0;
			mPathInit = false;

			mPath = new Polyline(mMapView);
			mPath.setColor(Color.RED);
			mPath.setWidth(7);
			mMapView.getOverlayManager().add(mPath);

			mScaleBar = new ScaleBarOverlay(mMapView);
			mMyLocationOverlay = new MyCustomLocationOverlay(this.getActivity());

			mMapOverlays = mMapView.getOverlays();
			mMapOverlays.add(mScaleBar);
			mMapOverlays.add(mMyLocationOverlay);

			mMapView.setMapOrientation(0);

			// Acquire a reference to the system Location Manager and get last known location
			LocationManager locationManager = (LocationManager) this.getActivity().getSystemService(Context.LOCATION_SERVICE);
			String locationProvider = LocationManager.GPS_PROVIDER;
			Location lastKnownLocation = locationManager.getLastKnownLocation(locationProvider);
			if (lastKnownLocation != null) {
				GeoPoint lastKnownLatLng = new GeoPoint(lastKnownLocation.getLatitude(), lastKnownLocation.getLongitude());
				mMyLocationOverlay.setLocation(lastKnownLatLng);
				mMapController.setCenter(lastKnownLatLng);
			}

			mViewInit = true;
		}
    }

After initialization there are no updates to the map.

When I check the CPU usage with the profiler in Android Studio I see a constant CPU usage of ~15%. 

When I do the same with GoogleMaps API CPU is between 0 and 5%.

Why does OSMdroid requires constantly CPU power and so much more then GoogleMaps?

Thanks in advance!

### If it's a bug, version(s) of android this affects:

All

### Version of osmdroid the issue relates to:

6.0.3

**Comment by monsieurtanuki** [comment]
@tomwassink I hope we can do less than this 15% CPU usage.
As you seem to feel at ease with the profiler, could you see which parts of your code use the most CPU?
My hunch: the `LocationManager`.
Then we can focus on the features that need to be optimized.

**Comment by tomwassink** [comment]
My own custom overlay was the issue (apologizes....). CPU load is now very low. 

I'm now using DirectedLocationOverlay and that one works. I used my own one as in the past DirectedLocationOverlay did not support your own bitmap.

Custom overlay code:

`public class MyCustomLocationOverlay extends Overlay {

	protected final Paint mPaint = new Paint();
    protected final Bitmap mArrow;
    protected GeoPoint mLocation = null;
    protected float mBearing = 0;
    private final Point screenCoords = new Point();
	
	public MyCustomLocationOverlay(final Context context) {
        mArrow = BitmapFactory.decodeResource(context.getResources(), R.drawable.arrow_jepster);
	}
	
    public void setLocation(final GeoPoint geoPoint) {
        this.mLocation = geoPoint;
   	}

    public GeoPoint getMyLocation() {
    	return this.mLocation;
    }
    
    public void setBearing(float bearing) {
        this.mBearing = bearing;
   }

    @Override
    public void draw(final Canvas canvas, final MapView mapView, final boolean shadow) {
            if (!shadow && this.mLocation != null) {
                    final Projection projection = mapView.getProjection();
                    Matrix matrix = new Matrix();
                    matrix.postRotate(mBearing);
                    Bitmap rotatedArrow = Bitmap.createBitmap(
                        mArrow, 
                        0, 0, 
                        mArrow.getWidth(), 
                        mArrow.getHeight(), 
                        matrix, 
                        true
                    );
                    
                    projection.toPixels(this.mLocation, screenCoords);
                    // add the rotated marker to the canvas
                    canvas.drawBitmap(
                        rotatedArrow, 
                        screenCoords.x - (rotatedArrow.getWidth()  / 2), 
                        screenCoords.y - (rotatedArrow.getHeight() / 2), 
                        null
                    );
                    mapView.postInvalidate();
            }
    }

}`

**Comment by monsieurtanuki** [comment]
@tomwassink You could close the issue then, am I right?
My 2 cents: regarding your code I don't think you need the `mapView.postInvalidate();` part in the `draw` method.
