### ISSUE TITLE
Color transparency of strokecap in polyline

### ISSUE THREAD

**Issue by Ruediger34** [osmdroid/osmdroid#1280]
Probably a bug in the color transparency of a polyline combinated with setStrokeCap()?

## Issue Type
[x] Question
[x] Bug
## Description and/or steps/code to reproduce the problem

If I add a polyline to the mapview and set the color and strokecap like so:

    roadPolyline.setColor(Color.parseColor("#800000FF"));
    roadPolyline.getPaint().setStrokeCap(Paint.Cap.ROUND);

I would expect that the strokecap also has this "transparent" color.

Is this a bug or do I have to set the color transparency of the strokecap on another method explicitly ?

![grafik](https://user-images.githubusercontent.com/20127481/53298347-d8e34400-382c-11e9-96b1-c72212a9a1a5.png)

### If it's a bug, version(s) of android this affects:
Probably all
### Version of osmdroid the issue relates to:
6.0.3

**Comment by monsieurtanuki** [comment]
@Ruediger34 Behind osmdroid's polyline, we use method `Canvas.drawLines(float[] pts, int offset, int count, Paint);`.
If just for a test you directly use `Canvas.drawLines`, do you still have those darker disks at each vertex?

**Comment by Ruediger34** [comment]
Ok, I tested and got the following result:

![grafik](https://user-images.githubusercontent.com/20127481/53303434-8759aa00-386a-11e9-9ec1-a1325ff24b03.png)

This occurs always if the lines are overlapping. Very disappointing.

I suspect there's nothing we can do to solve this?

**Comment by monsieurtanuki** [comment]
If you find the good Paint set up, please share it with us.

Could you try with a Polygon instead of a Polyline, just to see the vertices?
Polygons use Path, Polylines use Canvas.drawLines.

**Comment by spyhunter99** [comment]
this issue is that each line segment is drawn individually. We used to have squared off ends which caused some funky rendering issues and switched to the rounded ends. When the line has a transparency, both line segments overlap a bit because the start point and end point are the same. To be more specific, the drawing of segment 0 ends at point x,y and segment 1 starts at x,y. Thus with a transparency it's drawn twice at that point. 

If you use a solid line color with no transparency, this shouldn't occur. It might be possible to set the last point in a segment to no end cap or a 100% transparent version. Therefore the next segment would then paint it just once. It may work for relatively straight lines, but there will probably be overlap with closer to 90 degree bends.

**Comment by Ruediger34** [comment]
@spyhunter99 yes, this only occurs with transparency.

Ok, probably the solution is to use canvas.drawPath instead of drawLine.
With canvas.drawLine:
![grafik](https://user-images.githubusercontent.com/20127481/53304431-6185d280-3875-11e9-906d-33ac0c085b6f.png)


With canvas.drawPath:
![grafik](https://user-images.githubusercontent.com/20127481/53304366-a1988580-3874-11e9-8976-91f50079f7c6.png)

**Comment by spyhunter99** [comment]
i'm pretty sure there's a reason we use draw line instead of path. It was either performance related, or functioning correctly at zoom levels > 20. @monsieurtanuki probably remembers this as it was quite painful to get it performant and functional across all zoom levels

**Comment by monsieurtanuki** [comment]
@spyhunter99 Definitely performance issues like that!
That said, we might consider adding a boolean "usePathInsteadOfDrawlines" parameter in Polyline (default: false). I can't remember exactly what was wrong with Polyline vs Path, but if it's about zoom 22+ for instance, I guess users may prefer decent vertices (with Path) with still decent enough zoom levels (21 and lower).

**Comment by monsieurtanuki** [comment]
Why we use `Canvas.drawLines` instead of `Path` for `Polyline`: #834, #838.
@Ruediger34 Are you OK with potentially slower performances? Are you using large sets of data for your `Polyline`s, or big zoom levels (like 20+)?

**Comment by Ruediger34** [comment]
Interesting.
@monsieurtanuki Probably it's ok to have a performance impact but I can't estimate it in a real scenario.
My polylines have up to 400 geopoints (roundabout 20km) and I am using up to zoom level 19.

**Comment by monsieurtanuki** [comment]
@Ruediger34 OK, working on it. I just cannot guarantee it will be satisfactory.

**Comment by monsieurtanuki** [comment]
@Ruediger34 I've just PR'ed #1285.
You can already see the difference in the new "More Samples / Drawing / Draw a polyline on screen as Path" demo.
Please have a go in your own app too.
