### ISSUE TITLE
MapSnapshot callback returns unfinished(?) bitmap depending on zoom level

### ISSUE THREAD

**Issue by pasniak** [osmdroid/osmdroid#1281]
## Issue Type

[ ] Question
[x] Bug
[ ] Improvement
[ ] Build system related
[ ] Performance
[ ] Documentation

## Description and/or steps/code to reproduce the problem

I am trying to use the MapSnapshot to obtain a bitmap off the map (on touch at a map point so tiles are loaded at that touch point but possibly at lower zoom level).  The touch is supposed to show some detail.

Here's most permissive handler I could figure out. 
```
private fun snapshotBitmap(pMapView: MapView, lat: Double, lon: Double, onResult: (Bitmap)->Unit) =
    MapSnapshot(MapSnapshot.MapSnapshotable { mapSketch: MapSnapshot ->
        if (mapSketch.status == MapSnapshot.Status.CANVAS_OK) {
            onResult(mapSketch.bitmap)
            //mapSketch.onDetach()
        }
    }, tilesToAcceptAsSnapshot, pMapView.tileProvider, null,
        Projection(13.0,300,300,
            GeoPoint(lat, lon),0f,false,false))

private const val tilesToAcceptAsSnapshot = MapSnapshot.INCLUDE_FLAGS_ALL
```
and here's how I run it when I construct the view which appears on touch:
```
                                imageView {
                                    val snap = snapshotBitmap(map!!, lat, lon) {
                                        val drawable = BitmapDrawable(it)
                                        drawablesToRecycle += drawable
                                        image = drawable
                                        invalidate()
                                    }
                                    snap.run()
```
I would expect the callback to give me a fully finished bitmap (CANVAS_OK) but I see results vary based on the zoom level of my map! (If I zoom in my mapview I get a nice bitmap in the snap - if I zoom out I get gray bitmap i.e. no map, and even sometimes I get a partially drawn tile...)

## Environment

Trying in the emulator Android 8.0

### Version of osmdroid the issue relates to:

Close to the master's head (36b9bb190b45b6a9876b1861c0e1e117d38f4589)

**Comment by monsieurtanuki** [comment]
Quick answer: don't use INCLUDE_FLAGS_ALL, use UPTODATE instead.

With ALL, you say that you don't care about the status of the tiles. That makes sense if you make a snapshot of the currently displayed map, when obviously the displayed tiles are good enough for you and are already kept in the memory cache (which is the source of MapSnapshots).

With UPTODATE, you say that you only want to be called back when the tiles are up to date. If needed, tiles will be downloaded first. In your case, when you want MapSnapshots of another zoom level, that makes sense.

**Comment by pasniak** [comment]
INCLUDE_FLAG_UPTODATE does not seem to help.  Now I seem to get nothing :/

**Comment by pasniak** [comment]
I had zoomLevel 12.75 and I was not gettign the bitmap. Now that I switched back to 13.0 I get the bitmap...

**Comment by monsieurtanuki** [comment]
Have a look at #1277.
I manage to display USA states map snapshots, even starting from an empty tile cache database: the needed tiles are automatically downloaded.
