### ISSUE TITLE
Osmdroid GPS location offline

### ISSUE THREAD

**Issue by av131996** [osmdroid/osmdroid#1283]
Hello! I am using osmdroid 6.0.3 to develop an app with an offline map. I have a GPS connection. My location was present on the map until few hours ago, but now it isnt't. This is happening on my mobile, on simulator everything is ok. Is it a limit of gps location you can use in a day or something like this?

**Comment by spyhunter99** [comment]
No there's no rate limiting. If you have the osmdroid demo app, there's a diagnostics page that may help. And you can get another data point to see if it's a device thing or an environmental issue. Maybe there's an application life cycle issue with your app. Lifecycle stuff is important with gps
