### ISSUE TITLE
is there any function to add marker on user click 

### ISSUE THREAD

**Issue by wisdomrider** [osmdroid/osmdroid#1284]
Searched a lot but not got any help how can we implement marker when user clicks on mapview

**Comment by spyhunter99** [comment]
The sample app has a number of press to plot examples

**Comment by monsieurtanuki** [comment]
Like in the demo, "More samples / bookmarks / bookmark samples" with a long click.

**Comment by monsieurtanuki** [comment]
@wisdomrider Did that answer your question? If so please close the issue.

**Comment by wisdomrider** [comment]
yes i got it

**Comment by monsieurtanuki** [comment]
It looks like the issue is solved: I'm closing it.
@wisdomrider Feel free to open a new one if needed.
