### ISSUE TITLE
MAPNIK Problem

### ISSUE THREAD

**Issue by Glenn1Wang** [osmdroid/osmdroid#1288]
Problem downloading MapTile /7/68/63 HTTP response:Forbidden

**Comment by monsieurtanuki** [comment]
I've just successfully downloaded MAPNIK tile 7/68/63, adding those lines to a random sample in osmdroid demo:
````java
new Thread(new Runnable() {
	@Override
	public void run() {
		final OnlineTileSourceBase onlineTileSourceBase = TileSourceFactory.MAPNIK;
		final TileDownloader tileDownloader = new TileDownloader();
		final long mapTileIndex = MapTileIndex.getTileIndex(7, 68, 63);
		Drawable drawable1 = null;
		final IFilesystemCache cache = new TileWriter();
		try {
			drawable1 = tileDownloader.downloadTile(mapTileIndex, cache, onlineTileSourceBase);
		} catch(Exception e) {
			//
		}
	}
}).start();
````

For the record, this is the resulting tile:
![63](https://user-images.githubusercontent.com/11576431/53726136-a5786900-3e6d-11e9-968e-4504458e5b19.png)

That said, your "forbidden" problem looks similar to #1286:
* do you get the "forbidden" error for _all_ the to-be-downloaded tiles?
* how come you guys are "forbidden"? Do you use several threads to download the tiles (I mean, beyond the default osmdroid system), which would explain why osmdroid would tag you as too demanding people and punish you accordingly?
* I've just sent the following mail to the MAPNIK guys, I'll keep you posted

>  Hi there
I'm an admin for osmdroid on github, and this week-end some users reported "forbidden" access to MAPNIK tiles (https://a.tile.openstreetmap.org/...).
Is there a way to know which apps were recently banned (by "User-Agent" I guess), and how long this ban will last? (if it's not permanent)
As an osmdroid developer, I would like to understand how we could make things better regarding MAPNIK usage, therefore any help is welcomed.
Thanks in advance for your answers, and thanks for the fantastic job!
Regards

**Comment by InI4** [comment]
Digging into things, I also realized, that I once hat the calls active to change the USER-AGENT for my app. Then, after some API change, that call was not working any more and so my app (#1286) did probably also run with the default user agent again, which is probably a very bad idea. (I will crosspost this to #1286).

**Comment by Glenn1Wang** [comment]
First of all, thank you very much.
I get the forbidden error for all the to-be-downloaded tiles.Actually,i just want to show the map,but the map hasn't changed when i zoom in.I don't know if it's my problem of calling too many times.
My code:
mapView.setTileSource(TileSourceFactory.MAPNIK);

**Comment by monsieurtanuki** [comment]
@Glenn1Wang cf. #1286
What is the value of `Configuration.getInstance().getUserAgentValue()` that you find after `mapView.setTileSource(TileSourceFactory.MAPNIK);`?

**Comment by Glenn1Wang** [comment]
@monsieurtanuki
osmdroid

**Comment by Glenn1Wang** [comment]
when i code 
Configuration.getInstance().setUserAgentValue("github-firefishy-map/0.1");

My app work again！But i don't know what that means

**Comment by monsieurtanuki** [comment]
@Glenn1Wang You're right: the idea is actually to change the user agent value, because the default ("osmdroid") has been banned and anyway you're supposed to overwrite this value.

But you should NOT use the value you just used: it links to another github user for one of his apps.
Please use instead something like:
````java
Configuration.getInstance().setUserAgentValue("github-glenn1wang-myapp");
````
Can you do it and confirm you app is still working?

**Comment by Glenn1Wang** [comment]
@monsieurtanuki
This solved my problem！Thanks very much

**Comment by monsieurtanuki** [comment]
@Glenn1Wang You're welcome!
