### ISSUE TITLE
Osmdroid using cleartext http. Not allowed with Android 9

### ISSUE THREAD

**Issue by scoutant** [osmdroid/osmdroid#1290]
With Android 9, cleartext http is not allowed. HttpS is required.

If compile and targetting Android 9 ( targetSdkVersion 28), Osmdroid will NOT load any tile when running on Android 9. No matter the tile provider.

While not fixed a workaround is to instrument the Manifest. 
   <application
        android:usesCleartextTraffic="true"

## Issue Type

[ ] Question
[ X] Bug
[ ] Improvement
[ ] Build system related
[ ] Performance
[ ] Documentation

## Environment
targetSdkVersion 28 AND running on Android 9.

### If it's a bug, version(s) of android this affects:
9.0 only.

### Version of osmdroid the issue relates to:
all

**Comment by monsieurtanuki** [comment]
@scoutant "No matter the tile provider"? What about "USGS_TOPO" (for USA maps): the tile URLs are already in httpS.

Similar to #1287. Working on it: trying to update the old http tile URLs to httpS in `TileSourceFactory`.

**Comment by monsieurtanuki** [comment]
@scoutant You should also see MAPNIK tiles, provided that you set a proper user agent (cf. #1288).
I've just PR'ed #1291: please have a go with this fix.
Btw I added an [entry in the FAQ](https://github.com/osmdroid/osmdroid/wiki/FAQ) about this Android 9+ behavior. It's less permissive than your initial code suggestion, but I couldn't find time to test it.

**Comment by monsieurtanuki** [comment]
Solved by #1291
