### ISSUE TITLE
GeoPackage: OsmMapShapeConverter.addToMap() not work with feature points

### ISSUE THREAD

**Issue by alx696** [osmdroid/osmdroid#1295]
## Issue Type

[ ] Question
[X] Bug
[ ] Improvement
[ ] Build system related
[ ] Performance
[ ] Documentation

## Description and/or steps/code to reproduce the problem

Flow the wiki to display feature points. But `OsmMapShapeConverter.addToMap()` not work. Nothing display. Marker works fine, so data is ok:
```
    OsmMapShapeConverter converter = new OsmMapShapeConverter();
    GeoPackage geoPackage = geoPackageManager.open(databases.get(0));
    List<String> features = geoPackage.getFeatureTables();
    String featureTable = features.get(0);
    FeatureDao featureDao = geoPackage.getFeatureDao(featureTable);
    FeatureCursor featureCursor = featureDao.queryForAll();
    try {
      while (featureCursor.moveToNext()) {
        FeatureRow featureRow = featureCursor.getRow();
        GeoPackageGeometryData geometryData = featureRow.getGeometry();
        Geometry geometry = geometryData.getGeometry();
        String name = (String) featureRow.getValue("name");
        Log.w("名称", name);
        converter.addToMap(mapView, geometry);

        Point point = GeometryUtils.getCentroid(geometry);
        Marker pointMarker = new Marker(mapView);
        pointMarker.setPosition(
            new GeoPoint(
                point.getY(),
                point.getX()
            )
        );
        pointMarker.setAnchor(Marker.ANCHOR_CENTER, Marker.ANCHOR_BOTTOM);
        pointMarker.setTitle(name);
        mapView.getOverlays().add(pointMarker);
      }
    } finally {
      featureCursor.close();
    }
``` 

### If it's a bug, version(s) of android this affects:

Emulator x86_64 Andoird 9, OnePlus 3T Android 8.0, Samsung S8

### Version of osmdroid the issue relates to:

org.osmdroid:osmdroid-geopackage:6.0.3

>  I have check `org.osmdroid:osmdroid-geopackage:6.1.0-SNAPSHOT:debug@aar`. It's removed dependencies of `org.osmdroid:osmdroid-android:6.1.0-SNAPSHOT:debug@aar` and `mil.nga.geopackage` ... So, support of GeoPackage will change?

I try to update libary:
```
  implementation implementation 'mil.nga.geopackage:geopackage-android:3.1.0'
  implementation 'mil.nga:wkb:1.0.6'
  implementation 'org.osmdroid:osmdroid-geopackage:6.1.0-SNAPSHOT:debug@aar'
  implementation 'org.osmdroid:osmdroid-android:6.1.0-SNAPSHOT:debug@aar'
```
`OsmMapShapeConverter.addToMap()` also not work. And why `osmdroid-geopackage` use `mil.nga:wkb`, but `mil.nga.geopackage:geopackage-android` use `mil.nga.sf:sf-wkb`?

**Comment by bosborn** [comment]
Per OGC request, <code>mil.nga:wkb</code> was refactored into simple features libraries: [<code>mil.nga.sf:sf-wkb</code>](https://github.com/ngageoint/simple-features-wkb-java), [<code>mil.nga:sf</code>](https://github.com/ngageoint/simple-features-java)

[<code>geopackage-android</code>](https://github.com/ngageoint/geopackage-android) versions [3.0.0+](https://github.com/ngageoint/geopackage-android/releases/tag/3.0.0) were modified to use the simple features version

**Comment by spyhunter99** [comment]
looks like the last version used v2.0.1 of the nga libraries. @alx696 if you want to try and update with a pull request, i'll be more than happy to test

**Comment by alx696** [comment]
@spyhunter99 GeoPackage support looks like very basic.Even the ArcGIS and Google Map SDK. Only QGis have strong support(custom sytle, label and more). So, i only used `GeoPackage Geometry Type` to save data (with [Room Persistence Library](https://developer.android.com/topic/libraries/architecture/room)). @bosborn  I think maybe it is a better way to partly support GeoPackage.

A TypeConverter will help:
```
import androidx.room.TypeConverter;

import java.io.IOException;

import mil.nga.geopackage.geom.GeoPackageGeometryData;
import mil.nga.sf.Geometry;
import mil.nga.sf.LineString;
import mil.nga.sf.Point;

public class DbConverter {

  private static Geometry bytesToGeometry(byte[] bytes) {
    GeoPackageGeometryData geometryData = new GeoPackageGeometryData(4326);
    geometryData.fromBytes(bytes);
    return geometryData.getGeometry();
  }

  private static byte[] geometryToBytes(Geometry geometry) {
    GeoPackageGeometryData geometryData = new GeoPackageGeometryData(4326);
    geometryData.setGeometry(geometry);
    try {
      return geometryData.toBytes();
    } catch (IOException e) {
      e.printStackTrace();
      return null;
    }
  }

  @TypeConverter
  public static Point toPoint(byte[] bytes) {
    return (Point) bytesToGeometry(bytes);
  }

  @TypeConverter
  public static byte[] toBytes(Point point) {
    return geometryToBytes(point);
  }

  @TypeConverter
  public static LineString toLineString(byte[] bytes) {
    return (LineString) bytesToGeometry(bytes);
  }

  @TypeConverter
  public static byte[] toBytes(LineString lineString) {
    return geometryToBytes(lineString);
  }
}
```
