### ISSUE TITLE
Demo / Cache Analyzer / data don't scroll

### ISSUE THREAD

**Issue by monsieurtanuki** [osmdroid/osmdroid#1296]
## Issue Type

- [x] Bug

## Description and/or steps/code to reproduce the problem

In the demo app, the "Cache Analyzer" data cannot be scrolled: you cannot see data beyond the first screen.

### If it's a bug, version(s) of android this affects:

All

### Version of osmdroid the issue relates to:

6.0.3

**Comment by spyhunter99** [comment]
ok easy fix, i'll see if i can fix it up now

**Comment by spyhunter99** [comment]
fix in the next version, thanks for the report
