### ISSUE TITLE
Annouce: v6.1.0 cut and published

### ISSUE THREAD

**Issue by spyhunter99** [osmdroid/osmdroid#1298]
Notice only. v6.1.0 was cut this morning. Sonatype/central rollout should be complete globally within a few days. App rolled out on the play store.

**Comment by monsieurtanuki** [comment]
@spyhunter99 Thank you!

**Comment by MKergall** [comment]
Good news, thanks! 
My understanding of main 6.0.1 added value: 
- safer handling of the new Mapnik rule about user agent
- support MapsForge v0.10.0, meaning support of MapsForge v5 maps
Something else ?

**Comment by monsieurtanuki** [comment]
@MKergall At least there are also the [following features](https://github.com/osmdroid/osmdroid/milestone/11?closed=1)
* custom-made zoom buttons (#825)
* mapview "lite mode" (#990)
* refined milestones (#809)
