### ISSUE TITLE
Problem downloading MapTile

### ISSUE THREAD

**Issue by Raphael92** [osmdroid/osmdroid#1301]
kz.informenergo.manat W/org.osmdroid.tileprovider.modules.MapTileDownloader: Problem downloading MapTile: /16/46770/24026 HTTP response: HTTP/1.1 403 Forbidden

Version of osmdroid 4.3

**Comment by monsieurtanuki** [comment]
Probable duplicate with #1288
cf. [FAQ](https://github.com/osmdroid/osmdroid/wiki/FAQ#user-content-i-cannot-see-the-map-tiles-default-tile-provider-mapnik)
Feel free to reopen the issue if necessary.
