### ISSUE TITLE
[Question] Compass overlay over map using osmdroid 6.1

### ISSUE THREAD

**Issue by Andyeyo** [osmdroid/osmdroid#1302]
## Issue Type
[ ] Question
[ ] Bug

## Description and/or steps/code to reproduce the problem

Hi, I'm using osmdroid 6.1 to add a compass overlay, but it is not displayed on the map. My code is the following:

```
this.mCompassOverlay = new CompassOverlay(ctx, new InternalCompassOrientationProvider(ctx), map);
        this.mCompassOverlay.enableCompass();
        map.getOverlays().add(this.mCompassOverlay);
```
### If it's a bug, version(s) of android this affects:
API 23

### Version of osmdroid the issue relates to:

6.1.0

I expect the compass overlay runs and I can detect the maps orientation, but it does not work

**Comment by monsieurtanuki** [comment]
@Andyeyo I cannot help that much as the compass sensor doesn't work on my smartphone:
````java
final String TAG = "CompassOverlayTest";
final SensorManager sensorManager = (SensorManager) context.getSystemService(Context.SENSOR_SERVICE);
if (sensorManager == null) {
	Log.e(TAG, "no sensor manager");
} else {
	final Sensor sensor = sensorManager.getDefaultSensor(Sensor.TYPE_ORIENTATION);
	if (sensor == null) {
		Log.e(TAG, "no orientation sensor");
	} else {
		final boolean registered = sensorManager.registerListener(new SensorEventListener() {
			@Override
			public void onSensorChanged(SensorEvent sensorEvent) {

			}

			@Override
			public void onAccuracyChanged(Sensor sensor, int i) {

			}
		}, sensor, SensorManager.SENSOR_DELAY_UI);
		Log.e(TAG, "registered:" + registered);
	}
}
````

Could you add those lines to your code, in order to check that the sensor set up is OK on your smartphone?
Perhaps we should add methods in `CompassOverlay` in order to know if the set up is fine.

**Comment by spyhunter99** [comment]
The demo app has a diagnostics page on it that may help. This sample works on my test devices.  https://github.com/osmdroid/osmdroid/blob/master/OpenStreetMapViewer/src/main/java/org/osmdroid/samplefragments/location/CompassRoseSample.java

 Maybe the device in question does not have a compass?

**Comment by Andyeyo** [comment]
> @Andyeyo I cannot help that much as the compass sensor doesn't work on my smartphone:
> 
> ```java
> final String TAG = "CompassOverlayTest";
> final SensorManager sensorManager = (SensorManager) context.getSystemService(Context.SENSOR_SERVICE);
> if (sensorManager == null) {
> 	Log.e(TAG, "no sensor manager");
> } else {
> 	final Sensor sensor = sensorManager.getDefaultSensor(Sensor.TYPE_ORIENTATION);
> 	if (sensor == null) {
> 		Log.e(TAG, "no orientation sensor");
> 	} else {
> 		final boolean registered = sensorManager.registerListener(new SensorEventListener() {
> 			@Override
> 			public void onSensorChanged(SensorEvent sensorEvent) {
> 
> 			}
> 
> 			@Override
> 			public void onAccuracyChanged(Sensor sensor, int i) {
> 
> 			}
> 		}, sensor, SensorManager.SENSOR_DELAY_UI);
> 		Log.e(TAG, "registered:" + registered);
> 	}
> }
> ```
> 
> Could you add those lines to your code, in order to check that the sensor set up is OK on your smartphone?
> Perhaps we should add methods in `CompassOverlay` in order to know if the set up is fine.

Thank you very much, I will run my app with your code.
