### ISSUE TITLE
MyLocationNewOverlay.getLocation() is null and runOnFirstFix not executed

### ISSUE THREAD

**Issue by bmalex88** [osmdroid/osmdroid#1303]
## Issue Type

[ ] Question
[x] Bug
[ ] Improvement
[ ] Build system related
[ ] Performance
[ ] Documentation

## Description and/or steps/code to reproduce the problem

I have a straightforward method that is called after the users grants location access permissions from the main activity's `onPermissionsGranted()` method. Problem is, not only the location is not retrieved (which could also be caused by latency) but the Runnable specified as argument for `runOnFirstFix` is never run either.
Location is enabled and permissions are all alright. I don't find any reason for which this should not work or at least try to run.
I am running this on Android Pie (9) and compileSdkVersion is 28.

    private void getCurrentLocation() {
        LocationManager locationManager = (LocationManager)getSystemService(Context.LOCATION_SERVICE);
        Criteria criteria = new Criteria();
        criteria.setAccuracy(Criteria.ACCURACY_FINE);
        String bestProvider = locationManager.getBestProvider(criteria, true);

        Timber.i("bestProvider %s", bestProvider);

        GpsMyLocationProvider provider = new GpsMyLocationProvider(this.getBaseContext());
        provider.addLocationSource(LocationManager.GPS_PROVIDER);
        provider.addLocationSource(LocationManager.NETWORK_PROVIDER);
        provider.setLocationUpdateMinDistance(100);
        provider.setLocationUpdateMinTime(10000);

        myLocationOverlay = new MyLocationNewOverlay(provider, mMapView);
        if (!myLocationOverlay.enableMyLocation()) {
            Timber.i("Location not enabled");
        }

        myLocationOverlay.setDrawAccuracyEnabled(true);
        Bitmap icon = BitmapFactory.decodeResource(getResources(), R.drawable.ic_target);
        myLocationOverlay.setPersonIcon(icon);

        myLocationOverlay.runOnFirstFix(new Runnable() {
            @Override
            public void run() {
                // never reaches this point
                Timber.i("runOnFirstFix");
                if (myLocationOverlay.getMyLocation() == null) {
                    Timber.i("Location nott retrieved");
                }
            }
        });

        mMapView.getOverlays().add(myLocationOverlay);

        if (myLocationOverlay.getMyLocation() == null) {
            // could be too early
            Timber.i("Location not retrieved");
        }
    }

### If it's a bug, version(s) of android this affects:

All

### Version of osmdroid the issue relates to:

6.1.0

**Comment by bmalex88** [comment]
I have tried with the default `LocationListener` and it works. I can get the location

            // Acquire a reference to the system Location Manager
            LocationManager locationManager = (LocationManager) this.getSystemService(Context.LOCATION_SERVICE);

            // Define a listener that responds to location updates
            LocationListener locationListener = new LocationListener() {
                public void onLocationChanged(Location location) {
                    // Called when a new location is found by the network location provider.
                    Timber.i("Location: %f", location.getLatitude());
                }

                public void onStatusChanged(String provider, int status, Bundle extras) {
                    Timber.i("Location status: %s %d", provider, status);
                }

                public void onProviderEnabled(String provider) {
                    Timber.i("Provider enabled %s", provider);
                }

                public void onProviderDisabled(String provider) {
                    Timber.i("Provider disabled %s", provider);
                }
            };

            // Register the listener with the Location Manager to receive location updates
            if (ContextCompat.checkSelfPermission( this, android.Manifest.permission.ACCESS_COARSE_LOCATION ) == PackageManager.PERMISSION_GRANTED ) {
                Timber.i("Location access granted");
                locationManager.requestLocationUpdates(LocationManager.GPS_PROVIDER, 10000, 100, locationListener);
            }

**Comment by spyhunter99** [comment]
did this work correctly for you on the previous version of osmdroid? as a reminder, the runtime permission must be granted before creating the mylocation overlay

**Comment by bmalex88** [comment]
> 
> 
> did this work correctly for you on the previous version of osmdroid? as a reminder, the runtime permission must be granted before creating the mylocation overlay

No. I updated from 6.0.2 to 6.1.0 because I thought it would fix it, in fact. A strange behavior that perhaps can give a hint is that the compass is inverted (the red needle pointing to N is pointing to S)

**Comment by bmalex88** [comment]
No, it did not work

**Comment by spyhunter99** [comment]
i just tested it too and added some sample code to one of the sample fragments. Both reported issues work provided permissions are granted. Whatever see you have, it may be device specific issue. What version of android?

**Comment by bmalex88** [comment]
I have the Pie version. I am rewriting the entire application an will dedicate to this issue separately. If this happens again, I will create another issue with specific details. This can be closed.  Thanks
