### ISSUE TITLE
setBuiltInZoomControls is deprecated but...

### ISSUE THREAD

**Issue by neoacevedo** [osmdroid/osmdroid#1304]
Please note: issues related to or caused by osmbonuspack will be closed with a
suggestion to open an issue at https://github.com/MKergall/osmbonuspack

(feel free to delete whatever doesn't apply)

## Issue Type

[x] Question
[ ] Bug
[ ] Improvement
[ ] Build system related
[ ] Performance
[x] Documentation

## Description and/or steps/code to reproduce the problem

**setBuiltInZoomControls** is deprecated but **getZoomController().setVisibility()** is also deprecated, so, how to enable/disable zoom controls?

### If it's a bug, version(s) of android this affects:

Not a bug

### Version of osmdroid the issue relates to:

6.1.0

**Comment by monsieurtanuki** [comment]
@neoacevedo 
cf. [`StarterMapFragment`](https://github.com/osmdroid/osmdroid/blob/master/OpenStreetMapViewer/src/main/java/org/osmdroid/StarterMapFragment.java#L174)
````java
mMapView.getZoomController().setVisibility(CustomZoomButtonsController.Visibility.SHOW_AND_FADEOUT);
````
What is deprecated in that?
* [`MapView.getZoomController` is not](https://github.com/osmdroid/osmdroid/blob/master/osmdroid-android/src/main/java/org/osmdroid/views/MapView.java#L1854)
* [`CustomZoomButtonsController.setVisibility` is not](https://github.com/osmdroid/osmdroid/blob/master/osmdroid-android/src/main/java/org/osmdroid/views/CustomZoomButtonsController.java#L91)

**Comment by neoacevedo** [comment]
It's weird. Today `getZoomController().setVisibility` has been unmarked as depreated :\

**Comment by monsieurtanuki** [comment]
@neoacevedo For the record I'm also currently experiencing weird things with the latest release of Android Studio, things like "this method is never used" though it's obvious the method is actually used. Also in other projects than osmdroid.
