### ISSUE TITLE
6.1.0 Offline sqlite: IllegalArgumentException: bound must be positive

### ISSUE THREAD

**Issue by alx696** [osmdroid/osmdroid#1305]
[X] Bug

## Description and/or steps/code to reproduce the problem
XYTileSource with offline tile sqlite, when move or scale map:
```
E/AndroidRuntime: FATAL EXCEPTION: Thread-55
    Process: red.lilu.app.locus, PID: 12401
    java.lang.IllegalArgumentException: bound must be positive
        at java.util.Random.nextInt(Random.java:388)
        at org.osmdroid.tileprovider.tilesource.OnlineTileSourceBase.getBaseUrl(OnlineTileSourceBase.java:67)
        at org.osmdroid.tileprovider.tilesource.XYTileSource.getTileURLString(XYTileSource.java:42)
        at org.osmdroid.tileprovider.modules.MapTileDownloader$TileLoader.loadTile(MapTileDownloader.java:223)
        at org.osmdroid.tileprovider.MapTilePreCache.search(MapTilePreCache.java:125)
        at org.osmdroid.tileprovider.MapTilePreCache.access$100(MapTilePreCache.java:30)
        at org.osmdroid.tileprovider.MapTilePreCache$1.run(MapTilePreCache.java:41)
        at org.osmdroid.util.GarbageCollector$1.run(GarbageCollector.java:31)
        at java.lang.Thread.run(Thread.java:764)
E/AbstractTracker: Can't create handler inside thread that has not called Looper.prepare()
D/OSTracker: OS Event: crash
E/AbstractTracker: mTrackerAsyncQueryHandler is null
```
## Environment
Samsung S8, Android 8.0

### If it's a bug, version(s) of android this affects:
All

### Version of osmdroid the issue relates to:
6.1.0

6.1.0-SNAPSHOT:debug@aar works fine.

**Comment by monsieurtanuki** [comment]
@alx696 Are you sure you're offline? Your log shows `MapTileDownloader$TileLoader.loadTile`, which means an actual download attempt.
Besides, the line that crashes is in `OnlineTileSourceBase`: `mBaseUrls[random.nextInt(mBaseUrls.length)]`, which is strange.
What is the set-up of your XYTileSource? (URLs for instance)

**Comment by alx696** [comment]
@monsieurtanuki I have both offline source and overlay online source:
```
    mapView.setTileSource(
        new XYTileSource("Google-Satellite", 6, 20, 256, ".jpg", new String[]{})
    );
    mapView.setUseDataConnection(false);
...
    final ITileSource googleTileSource = new OnlineTileSourceBase(
        "GoogleCn-" + type, 6, 20, 256, ".jpg",
        new String[]{
            "http://mt0.google.cn/vt/lyrs=" + type,
            "http://mt1.google.cn/vt/lyrs=" + type,
            "http://mt2.google.cn/vt/lyrs=" + type,
            "http://mt3.google.cn/vt/lyrs=" + type
        }
    ) {
      @Override
      public String getTileURLString(long mapTileIndex) {
//            mImageFilenameEnding;
        return getBaseUrl()
            + "&z="
            + MapTileIndex.getZoom(mapTileIndex)
            + "&x=" + MapTileIndex.getX(mapTileIndex)
            + "&y=" + MapTileIndex.getY(mapTileIndex);
      }
    };
    final MapTileProviderBasic googleTileProvider = new MapTileProviderBasic(getApplicationContext());
    googleTileProvider.setTileSource(googleTileSource);
    googleTileProvider.getTileRequestCompleteHandlers().add(mapView.getTileRequestCompleteHandler());
    TilesOverlay tilesOverlay = new TilesOverlay(googleTileProvider, getBaseContext());
    tilesOverlay.setLoadingBackgroundColor(Color.TRANSPARENT);
      mapView.getOverlays()
          .add(tilesOverlay);
```
And i have try to remove the google tile overlay, but also crash! Same code, `6.1.0` crash, `6.1.0-SNAPSHOT:debug@aar` works.

**Comment by spyhunter99** [comment]
`OnlineTileSourceBase.java:67` has not changed in 2011. Looking at your config, you probably want a MapTileProviderArray and have separate tile providers for online and offline sources. MapTileProviderBasic is actually an array that checks the cache, offline, assets and then the downloader. With a 0 length url list, this will cause the downloaded to fail. We should probably guard against this though.

One work around is to just define a url, even if it points to localhost or an empty string might work. Or you can construct a custom tile provider so that you can control what the tile loading yourself.

**Comment by alx696** [comment]
@spyhunter99 Thanks for your suggest! After add a empty baseUrl to the `XYTileSource`, `6.1.0` works:
```
    mapView.setTileSource(
        new XYTileSource("Google-Satellite", 6, 20, 256, ".jpg", new String[]{""})
    );
```
I do not want to construct a custom tile provider. This will bring a lot of work. OnlineTileSource just an addition map type, user can change between different map source.

@monsieurtanuki Looks like `mBaseUrls[random.nextInt(mBaseUrls.length)]` required at least one baseUrl since `6.1.0`.

**Comment by monsieurtanuki** [comment]
> Looks like mBaseUrls[random.nextInt(mBaseUrls.length)] required at least one baseUrl since 6.1.0.

@alx696 It must be something else:
* the last time [`OnlineTileSourceBase.getBaseUrl` was edited](https://github.com/osmdroid/osmdroid/blame/master/osmdroid-android/src/main/java/org/osmdroid/tileprovider/tilesource/OnlineTileSourceBase.java#L66) was 5 years ago, not by me, and was about "normalizing line ends"
* class `OnlineTileSourceBase` [before my recent changes](https://github.com/osmdroid/osmdroid/blame/c62232573995abf53e90a84388367d25c907be04/osmdroid-android/src/main/java/org/osmdroid/tileprovider/tilesource/OnlineTileSourceBase.java) (about a month ago), obviously with the same code for `OnlineTileSourceBase.getBaseUrl`
* `random.nextInt(0)` always throws an `IllegalArgumentException("bound must be positive")` exception, cf. [java class `Random`](https://docs.oracle.com/javase/8/docs/api/java/util/Random.html#nextInt--)
