### ISSUE TITLE
Bug: Icon AlertDialog vanishes, when CustomZoomButtons vanish

### ISSUE THREAD

**Issue by MeckyD** [osmdroid/osmdroid#1318]
[ ] Question
[X ] Bug
[ ] Improvement
[ ] Build system related
[ ] Performance
[ ] Documentation

When opening an AlertDialog with an onClickListener on a Marker, and adding an Icon to this AlertDialog, the Icon will always vanish, when the CustomZoomButtons of the Map vanish.

Bad solution for me so far:

map.getZoomController().setShowFadeOutDelays(1000000,1000);

Setting the FadeOutDelays to a very high value (one Million ms in this example) while the AlertDialog is shown, and replace the Delay Value to normal (5000ms) again, when the AlertDialog is being closed.

### If it's a bug, version(s) of android this affects:

All

### Version of osmdroid the issue relates to:

6.1.0

**Comment by monsieurtanuki** [comment]
Are you using the same icon for the AlertDialog and for the custom zoom?

**Comment by MeckyD** [comment]
Thanks for your answer monsieurtanuki,

no im using different drawables. The icons for the zoom are both default from osmdroid ( + and - on a white background). The Icons used in the AlertDialog are svg's imported as VectorAssets (typical marker icons in different colors).

**Comment by monsieurtanuki** [comment]
I'm not an expert on drawing SVGs and VectorAssets, but there's no reason why a private `Paint` that is created explicitly with a `new` statement (cf. [code](https://github.com/osmdroid/osmdroid/blob/master/osmdroid-android/src/main/java/org/osmdroid/views/CustomZoomButtonsDisplay.java#L93)) would be reused by an unrelated `AlertDialog` not even coded by osmdroid!
That being said, during the fade out animation the display is refreshed (cf. [code](https://github.com/osmdroid/osmdroid/blob/master/osmdroid-android/src/main/java/org/osmdroid/views/CustomZoomButtonsController.java#L44)), which may at least explain why something happens gradually to your `AlertDialog`.
That sounds rather like an Android side-effect.
Maybe if you create explicitly a bitmap once for all from your VectorAssets using an explicit `Paint` (and not `null`), you won't have the same problem. Can you try that?

**Comment by MeckyD** [comment]
Didn't change anything. But i think you are right, that this Bug rather depends on Android side, and not osmdroid. I noticed, that sometimes, when a part of the screen refreshes, the Icon also vanishes. For example, when a tile didn't load yet, the alert dialog opens, and then the tile finished downloading and gets viewed, then the icon vanishes.

Never the less, thanks a lot for your help. :)
