### ISSUE TITLE
Different coordinate systems with custom map tiles

### ISSUE THREAD

**Issue by koraxis** [osmdroid/osmdroid#132]
Hi everyone,

I want to develop a journey planning app using osmdroid , but customers have their own maps(pre rendered map tiles on their servers) and use coordinate systems other than WGS84. Is it possible( or is it easy to implement) to use other coordinate systems?

If it is possible , then where should i start to work on it? 

Thank you for your time.

**Comment by neilboyd** [comment]
It's been discussed before but it won't be easy because Mercator is a bit too fundamentally built in.

**Comment by kurtzmarc** [comment]
What sort of coordinate systems are the tiles in?

**Comment by koraxis** [comment]
It changes from customer to customer but mostly bessel 1841 or GRS80

**Comment by koraxis** [comment]
Should i focus on the TileSystem class for changing the coordinate system? Or are there other classes and packages to look at ?

**Comment by kurtzmarc** [comment]
You should probably target the TileSystem. Like Neil, I am skeptical that it will be possible due to how tied to Mercator we are.

**Comment by spyhunter99** [comment]
a potential (freeish) solution: have the customer import their data into geoserver. The map data can then be exposed via geoserver's wms service in whatever projection you want. Then use MOBAC connected to the wms endpoint to create offline maps which can then be hosted on a server using the correct projection (or deployed to the android devices for offline tiles). There's also a WMS client that someone made for osmdroid. It may need some work to make it stable but it's a potential solution

**Comment by spyhunter99** [comment]
digging up this old thread. if there's an algorithm to convert to/from lat/long wgs84 to your desired projection then all that's needed is a custom ITileSource to translate the the slippy style urls into your desired projection. That said, your server will need to be able to produce tiles based on the geographic bounds. They are already chopped up and the server is not capable to stitching them back together then there isn't too much we can do

**Comment by spyhunter99** [comment]
operation timeout. please reopen or comment back if you have further questions
