### ISSUE TITLE
Question: How to keep map centered while multi-touch zooming?

### ISSUE THREAD

**Issue by valkoz** [osmdroid/osmdroid#1329]
## Issue Type

[X] Question
[ ] Bug
[ ] Improvement
[ ] Build system related
[ ] Performance
[ ] Documentation

## Description and/or steps/code to reproduce the problem

Is there a way to keep the map centered when multi-touch zoom is enabled? I mean, when user pinches the map  to zoom it, map center jumps to pinch, but I need the map center stay the same.

### If it's a bug, version(s) of android this affects:

All

### Version of osmdroid the issue relates to:

6.1.0

**Comment by spyhunter99** [comment]
most of the work is done in the multitouch controller, so if you want a more specialize behavior, i'd suggest starting there

**Comment by valkoz** [comment]
Thank you, i created a custom touch listener and it works fine.
