### ISSUE TITLE
Error in GeocoderNominatim.maxresult only returns a value.

### ISSUE THREAD

**Issue by steniobarroso** [osmdroid/osmdroid#1332]
Please note: issues related to or caused by osmbonuspack will be closed with a
suggestion to open an issue at https://github.com/MKergall/osmbonuspack

(feel free to delete whatever doesn't apply)

## Issue Type

[ ] Question
[x ] Bug
[ ] Improvement
[ ] Build system related
[ ] Performance
[ ] Documentation

### If it's a bug, version(s) of android this affects:

All

### Version of osmdroid the issue relates to:

6.0.2
getFromLocation(double latitude, double longitude, int maxResults)
Returns an array of Addresses that are known to describe the area immediately surrounding the given latitude and longitude.

só retorna um valor mesmo colocando um valor muito alto em maxresult.

**Comment by MKergall** [comment]
Please note: issues related to or caused by osmbonuspack will be closed with a
suggestion to open an issue at https://github.com/MKergall/osmbonuspack (and in english of course)
