### ISSUE TITLE
ERROR while building the cloned item

### ISSUE THREAD

**Issue by utsab-bbc** [osmdroid/osmdroid#1333]
## Issue Type
[ ] Bug
[ ] Build system related

## Description and/or steps/code to reproduce the problem

i cloned and tried to build and this happened.

![Capture](https://user-images.githubusercontent.com/35037970/57066940-59bb3200-6ced-11e9-9757-de9f2ccd3d16.JPG)

### Version of osmdroid the issue relates to:

6.0.2

**Comment by spyhunter99** [comment]
did you by chance change anything? perhaps updated the gradle android plugin or gradle versions?

**Comment by utsab-bbc** [comment]
yes

**Comment by spyhunter99** [comment]
try reverting the change

**Comment by utsab-bbc** [comment]
worked thanks @spyhunter99
