### ISSUE TITLE
GetProjection NullPointerException

### ISSUE THREAD

**Issue by SopraSteriaAndroid** [osmdroid/osmdroid#1334]
## Issue Type

[ ] Question
[X ] Bug
[ ] Improvement
[ ] Build system related
[ ] Performance
[ ] Documentation

## Description and/or steps/code to reproduce the problem

When the user moves the map and changes the rotation or zoom level of the map very quickly a NullPointerException appears. Here is the stack :

`java.lang.NullPointerException: Attempt to invoke virtual method 'void org.osmdroid.views.Projection.adjustOffsets(double, double, boolean, int)' on a null object reference
        at org.osmdroid.views.MapView.getProjection(MapView.java:354)
        at org.osmdroid.views.MapView.getMapCenter(MapView.java:676)
        at org.osmdroid.views.MapView.getMapCenter(MapView.java:669)`

In our application we are using the function getMapCenter() to calculate a distance from an other point.

### Version of osmdroid the issue relates to:

6.0.3

**Comment by spyhunter99** [comment]
hmm, strange. looking into this now

**Comment by spyhunter99** [comment]
i'm guessing this is a fun concurrency problem whereby the project is set to null while the call to getProjection is called

**Comment by spyhunter99** [comment]
@SopraSteriaAndroid so i think this is fixed, although i wasn't able to reproduce it before or after the change. i'll update the snapshots shortly.  if you can test and/or attempt to reproduce, i'd appreciate it
