### ISSUE TITLE
Neighbor tiles loaded not patterned

### ISSUE THREAD

**Issue by sdarvish** [osmdroid/osmdroid#1342]
## Issue Type

[ ] Question
[x ] Bug
[ ] Improvement
[ ] Build system related
[ ] Performance
[ ] Documentation

##Using a different Tile Source
We have dedicated a private server to our map view, and we have set the below codes for arranging the tiles, however at the loading and loaded points, it shows tiles irrelevant to the ones surroundings:
```
    mapView?.setTileSource(object : OnlineTileSourceBase(
            "USGS Topo", 0, 18, 256, ".png",
            arrayOf("http://192.168.200.14/tile/")
        ) {
            override fun getTileURLString(pMapTileIndex: Long): String {
                Log.d("Address : ", "TST")

                var address =
                    baseUrl + MapTileIndex.getZoom(pMapTileIndex) + "/" + MapTileIndex.getY(
                        pMapTileIndex
                    ) + "/" + MapTileIndex.getX(pMapTileIndex) + mImageFilenameEnding

                Log.d("Address : ", address)

                return (address)
            }
        })
```
Please find attached the screenshot of the issue.
![Screenshot_20190520-154341](https://user-images.githubusercontent.com/5301170/58018629-8efeb700-7b18-11e9-86fa-c97b671f3fb9.png)

### If it's a bug, version(s) of android this affects:

All

### Version of osmdroid the issue relates to:

6.0.2

**Comment by spyhunter99** [comment]
looks a lot like your url is uses a different pattern. Default is Z/X/Y, however yours may be Z/Y/X or some other variant. I'd suggest clearing the map tile cache and zooming all the way out and observe what parts of the world are in the wrong place. It may help you figure it out

**Comment by sdarvish** [comment]
thanks, it work for me, 
but on [this](https://github.com/osmdroid/osmdroid/wiki/Map-Sources#using-a-different-tile-source) page its wrong and use Z/Y/X , please make it correct
