### ISSUE TITLE
animateTo() causes double map View invalidation()

### ISSUE THREAD

**Issue by pasniak** [osmdroid/osmdroid#1343]
## Issue Type

[ ] Question
[x] Bug
[ ] Improvement
[ ] Build system related
[x] Performance
[ ] Documentation

## Description and/or steps/code to reproduce the problem:

In master, `setExpectedCenter` has invalidate() at the end: 
```
	public void setExpectedCenter(final IGeoPoint pGeoPoint, final long pOffsetX, final long pOffsetY) {
...
        if (!after.equals(before)) {
        	ScrollEvent event = null;
			for (MapListener mapListener: mListners) {
				mapListener.onScroll(event != null ? event : (event = new ScrollEvent(this, 0, 0)));
			}
		}
		invalidate();
	}
```

and it is called from `MapAnimatorListener.onAnimationUpdate`:
```
        @Override
        public void onAnimationUpdate(ValueAnimator valueAnimator) {
...
            if (mCenterEnd != null) {
...
                mMapController.mMapView.setExpectedCenter(mCenter);
            }
            mMapController.mMapView.invalidate();
        }
    }
```

causing invalidate() to be called twice, when I call IMapController.animateTo(my_desired_new_point) to get the map to move smoothly to the new point.

**Comment by pasniak** [comment]
I also noticed if I use setCenter() instead animateTo() I do not get unnecessary call into draw() of my custom overlay() ; the latter is costly to redraw.  setCenter() gives me less "smooth" UX.

Changing osmdroid code does not help... 
```
        @Override
        public void onAnimationUpdate(ValueAnimator valueAnimator) {
...
                mMapController.mMapView.setExpectedCenter(mCenter);
            }
            else {
                mMapController.mMapView.invalidate();
            }
        }
```

**Comment by pasniak** [comment]
I timed my custom's overlay's `draw(canvas: Canvas, mapView: MapView, shadow: Boolean)` and it is not too slow (1ms). In fact, really the problem is that the custom overlay disappears and reappears when `animateTo()` (to reposition the map) is called. It does not when I change my position cot to call `setCenter()`.

**Comment by monsieurtanuki** [comment]
I don't think it's a bug to call invalidate() several times, as this doesn't trigger an immediate synchronous refresh of the display. More likely, both calls will provoke a unique display refresh.
That's the theory. On the other hand, if you actually saw that all invalidate() calls trigger a distinct display refresh, then it would be worth to be less generous with invalidate() calls.

**Comment by pasniak** [comment]
Closing this issue; I identified perf problem due to duplicate overlay.
