### ISSUE TITLE
MapVew.resetProjection() is private

### ISSUE THREAD

**Issue by pasniak** [osmdroid/osmdroid#1344]
## Issue Type

[ ] Question
[ ] Bug
[x] Improvement

## Description and/or steps/code to reproduce the problem

Does it make sense to deprecated protected method to a private one? Especially if I can just call mProjection = null given mProjection is protected...
```
	/**
	 * Use {@link #resetProjection()} instead
	 * @param p
	 */
	@Deprecated
	protected void setProjection(Projection p){
		mProjection = p;
	}

	private void resetProjection(){
		mProjection = null;
	}

```

**Comment by monsieurtanuki** [comment]
I rather think that mProjection should be private.
