### ISSUE TITLE
New feature: ScaleDiskOverlay

### ISSUE THREAD

**Issue by monsieurtanuki** [osmdroid/osmdroid#1346]
## Issue Type

- [x] Improvement

## Description and/or steps/code to reproduce the problem

Create a new Overlay that displays:
- a disk or a circle (an ellipse?)
- around a GeoPoint or a pixel on the screen
- whose radius is x meters
- with a possible displayed label indicating the radius size
- with a possible click action displaying the radius size
- with a minimum pixel size under which it's not displayed

### Version of osmdroid the issue relates to:

6.1.0

**Comment by MKergall** [comment]
Polygon.pointsAsCircle(GeoPoint center, double radiusInMeters)

- displayed label indicating the radius size => why ? far too specific need. 
- click action => setInfoWindow
- minimum pixel size under which it's not displayed => could be a (really useful) feature of any Polygon.

**Comment by monsieurtanuki** [comment]
@MKergall Thank you for your feedback.
The point is to have a simple circle on the map, something like "5 minutes away from that place" on a city map (500 meters?) - therefore I think the Polygon is too heavy for that. And the label is useful - though it can be optional.

**Comment by MKergall** [comment]
I don't see why Polygon would be too heavy. Ultimately, the circle will be drawn as a polygon.

**Comment by monsieurtanuki** [comment]
Well, my previous experiments and PRs with Polygons and Polylines make me rather defensive: if I can avoid them, I'm better off.
Besides, it will be a simple canvas.drawCircle, like the ScaleBarOverlay is something like canvas.drawRect (and not a Polyline): rather straightforward.
Comparing that with computing enough step points on a Polygon so that it looks like a real circle, with all the possible rendering issues (even for users that don't use Polygons themselves): the game isn't worth the candle IMHO.
Anyway, we can imagine an abstract class and different implementations of the draw method, one with a Polygon and the other with drawCircle.

That being said, feel free to create an additional issue regarding the "if the Polygon is too small, don't display it / use a default display" option.

**Comment by MKergall** [comment]
I understand. 
That said, thanks to all those PRs, Polygon and Polyline are pretty good now. 

And I'm worried about always adding new overlays inside osmdroid core. 
In fact, I would recommend to remove some of them, obsolete or redundant (PathOverlay, ItemizedOverlay* and ItemizedIconOverlay, ClickableIconOverlay).

**Comment by monsieurtanuki** [comment]
I understand your point about new overlays, but this one is definitely a need I had for my app, and a feature I see in other urban maps.

Regarding garbage collecting about deprecated overlays, I'm rather in favour of it. That deserves a specific issue and a roll-out program ("by January 1st 2020 classes x y and z won't be available anymore and this is the transition path for your code").

**Comment by monsieurtanuki** [comment]
Just PR'ed #1354 

This is what it can look like (cf. demo "More Samples / Data / Markers"):
![Screenshot_2019-06-07-10-04-32](https://user-images.githubusercontent.com/11576431/59091151-000ede80-890f-11e9-995b-4d9deb427958.png)
