### ISSUE TITLE
New feature: SpeechBalloonOverlay

### ISSUE THREAD

**Issue by monsieurtanuki** [osmdroid/osmdroid#1347]
## Issue Type

- [x] Improvement

## Description and/or steps/code to reproduce the problem

The idea is to be able to display:
- text
- in a speech balloon
- related to a GeoPoint or a pixel
- that can be moved (dragged)
- possibly with a fade out display from text line 2, with a "see more" button

That should look a bit like Lonely Planet top destination maps, at the beginning of the books.

### Version of osmdroid the issue relates to:

6.1.0

**Comment by MKergall** [comment]
Except the fade out display, what is missing in the current Marker infowindow ? 

- A Marker can be dragged (setDraggable). 
- A "See more" button is already present - but hidden - in the default infowindow layout, and can easily be activated when inheriting from Marker.

**Comment by monsieurtanuki** [comment]
@MKergall Thank you for your feedback
The idea is to drag the "infowindow", not the Marker. Something like "it's too crowded there, let's move the infowindow where there are no overlaps" (same text bubble but moved, and expanded arrow connecting it to the GeoPoint). Without moving the Marker's GeoPoint.

**Comment by MKergall** [comment]
Oh, OK, understood.

**Comment by monsieurtanuki** [comment]
@MKergall I guess that also means that we need something more flexible than `InfoWindow` for `Marker`. I understand that `InfoWindow` works as a displayed `View` on top of the `MapView`, but what if we want to display something directly on the `Canvas`? (like my speech balloon or like the `ItemizedOverlayWithFocus` that you like so much...)

We need `InfoWinfow` to `implement` something like:
````java
void setRelatedObject(Object relatedObject);
Object getRelatedObject();
void open(Object object, GeoPoint position, int offsetX, int offsetY);
void close();
void draw(Canvas c);
void onDetach();
boolean isOpen();
````

Then both "`View` mode" and "draw on `Canvas` mode" can coexist for a `Marker`.

**Comment by monsieurtanuki** [comment]
Draft version of draggable speech balloons:
![Screenshot_2019-06-10-16-23-56](https://user-images.githubusercontent.com/11576431/59202315-7e33e500-8b9c-11e9-9b6c-e5af09d223fd.png)
