### ISSUE TITLE
GroundOverlay2 with coordinates for each image angle

### ISSUE THREAD

**Issue by PaoloDozio** [osmdroid/osmdroid#1361]
## Issue Type

[ ] Question
[ ] Bug
[X] Improvement
[ ] Build system related
[ ] Performance
[ ] Documentation

## Description and/or steps/code to reproduce the problem
I used this lines of code to put an image over the map

```
GroundOverlay2 overlay = new GroundOverlay2();
overlay.setTransparency(0.5f);
overlay.setImage(bitmap);
overlay.setPosition(new GeoPoint(50.0,-127.5), new GeoPoint( 21.0, -66.5));
mMapView.getOverlayManager().add(overlay);
```

but the image is not correct aligned with the map.
Is it possible to provide to the GroundOverlay2 class the 4 coordinates of the 4 angles of the image?
The image should be "distorted" in order to be visualised correctly.
The image is aligned correctly only in the 2 angles where the coordinates are specified.
Do you have any suggestion to solve this issue?

### If it's a bug, version(s) of android this affects:

All

### Version of osmdroid the issue relates to:

6.1.0

**Comment by monsieurtanuki** [comment]
I guess that would mean being able to compute the right `Matrix` to transform your bitmap's rectangle `[(0, 0), (width, 0), (width, height), (0, height)]` into a quadrilateral `[topleft, topright, bottomright, bottomleft]`.
I don't know much about `Matrix`, but I think that should solve your issue, in a new `GroundOverlay4` class.

**Comment by monsieurtanuki** [comment]
Perhaps using method [`Matrix.setPolyToPoly`](https://developer.android.com/reference/android/graphics/Matrix.html#setPolyToPoly(float[],%20int,%20float[],%20int,%20int)):

> boolean setPolyToPoly(float[] src, int srcIndex, float[] dst, int dstIndex, int pointCount)
Set the matrix such that the specified src points would map to the specified dst points.

@PaoloDozio Do you feel like coding and testing that?

**Comment by PaoloDozio** [comment]
> Do you feel like coding and testing that?

Yes.. I can coding and test, but I don't know how to use Matrix..
If you write the line of code to add, I will try to use my data to test if it is working correctly..
Let me know.

**Comment by monsieurtanuki** [comment]
Try something like that:
````java
public class GroundOverlay4 extends Overlay {

    private final Matrix mMatrix = new Matrix();
    private final Paint mPaint = new Paint();
    private final float[] mMatrixSrc = new float[8];
    private final float[] mMatrixDst = new float[8];

    private GeoPoint mTopLeft;
    private GeoPoint mTopRight;
    private GeoPoint mBottomRight;
    private GeoPoint mBottomLeft;

    private Bitmap mImage;
    private float mBearing;
    private float mTransparency;

    public GroundOverlay4() {
        super();
        mBearing = 0.0f;
        setTransparency(0.0f);
    }

    public void setImage(Bitmap image){
        mImage = image;
        if (mImage == null) {
            return;
        }
        final int width = mImage.getWidth();
        final int height = mImage.getHeight();
        mMatrixSrc[0] = 0;
        mMatrixSrc[1] = 0;
        mMatrixSrc[2] = width;
        mMatrixSrc[3] = 0;
        mMatrixSrc[4] = width;
        mMatrixSrc[5] = height;
        mMatrixSrc[6] = 0;
        mMatrixSrc[7] = height;
    }

    public Bitmap getImage(){
        return mImage;
    }

    public void setPosition(final GeoPoint pTopLeft,
                            final GeoPoint pTopRight,
                            final GeoPoint pBottomRight,
                            final GeoPoint pBottomLeft
                            )
    {
        mTopLeft = new GeoPoint(pTopLeft);
        mTopRight = new GeoPoint(pTopRight);
        mBottomRight = new GeoPoint(pBottomRight);
        mBottomLeft = new GeoPoint(pBottomLeft);
    }

    public float getBearing(){
        return mBearing;
    }
    
    public void setBearing(float bearing){
        mBearing = bearing;
    }
    
    public void setTransparency(float transparency){
        mTransparency = transparency;
        mPaint.setAlpha(255-(int)(mTransparency * 255));
    }
    
    public float getTransparency(){
        return mTransparency;
    }
    
    @Override
    public void draw(Canvas canvas, Projection pj)
    {
        if(mImage == null) {
            return;
        }
        computeMatrix();
        canvas.drawBitmap(mImage, mMatrix, mPaint);
    }

    private void computeMatrix() {
        final long topLeftCornerX = pj.getLongPixelXFromLongitude(mTopLeft.getLongitude());
        final long topLeftCornerY = pj.getLongPixelYFromLatitude(mTopLeft.getLatitude());
        final long topRightCornerX = pj.getLongPixelXFromLongitude(mTopRight.getLongitude());
        final long topRightCornerY = pj.getLongPixelYFromLatitude(mTopRight.getLatitude());
        final long bottomRightCornerX = pj.getLongPixelXFromLongitude(mBottomRight.getLongitude());
        final long bottomRightCornerY = pj.getLongPixelYFromLatitude(mBottomRight.getLatitude());
        final long bottomLeftCornerX = pj.getLongPixelXFromLongitude(mBottomLeft.getLongitude());
        final long bottomLeftCornerY = pj.getLongPixelYFromLatitude(mBottomLeft.getLatitude());

        mMatrixDst[0] = (float) topLeftCornerX;
        mMatrixDst[1] = (float) topLeftCornerY;
        mMatrixDst[2] = (float) topRightCornerX;
        mMatrixDst[3] = (float) topRightCornerY;
        mMatrixDst[4] = (float) bottomRightCornerX;
        mMatrixDst[5] = (float) bottomRightCornerY;
        mMatrixDst[6] = (float) bottomLeftCornerX;
        mMatrixDst[7] = (float) bottomLeftCornerY;
        
        mMatrix.setPolyToPoly(mMatrixSrc, 0, mMatrixDst, 0, 4);
    }
}
````

**Comment by PaoloDozio** [comment]
> ```java
> GroundOverlay4
> ```

Thanks for the code.. I will try tonight...

**Comment by PaoloDozio** [comment]
It works perfectly!!!
Thanks..
Just a little modification in the code.
pj parameter was missing..


```
    public void draw(Canvas canvas, Projection pj)
    {
        if(mImage == null) {
            return;
        }
        computeMatrix(pj);
        canvas.drawBitmap(mImage, mMatrix, mPaint);
    }

    private void computeMatrix(Projection pj) {

```

Here below you can see the image over the map.. There is a small rotation, but this rotation is a must to have the perfect alignment..

![image](https://user-images.githubusercontent.com/46484640/60288686-0ba16400-9915-11e9-90d4-424e408884cf.png)

**Comment by monsieurtanuki** [comment]
@PaoloDozio Wonderful! I'm currently deploying `GroundOverlay4`.
Would it be possible for you to give an example of an image (url) and its 4 corners' `GeoPoint`s, in order to build a demo?

**Comment by PaoloDozio** [comment]
> @PaoloDozio Wonderful! I'm currently deploying `GroundOverlay4`.
> Would it be possible for you to give an example of an image (url) and its 4 corners' `GeoPoint`s, in order to build a demo?

Sure..
The image is this

![image](https://user-images.githubusercontent.com/46484640/60370767-bbe79900-99f7-11e9-85a6-f3673b07b659.png)


The function for test the functionality could be something like this

```
static void AddImageMap4(MapView map_OSM, Bitmap bitmap
	                                             , double lat_top_left,      double lon_top_left
	                                             , double lat_top_right,     double lon_top_right
	                                             , double lat_bottom_left,  double lon_bottom_left
	                                             , double lat_bottom_right, double lon_bottom_right
						 , float transparancy) {
        if (bitmap != null) {
            GroundOverlay4 overlay = new GroundOverlay4();
            overlay.setTransparency(transparancy / 100);
            overlay.setImage(bitmap);
            overlay.setPosition(new GeoPoint(lat_top_left, lon_top_left)
			                  , new GeoPoint(lat_top_right,lon_top_right)
			                  , new GeoPoint(lat_bottom_right,lon_bottom_right)
			                  , new GeoPoint(lat_bottom_left,lon_bottom_left)
							);
            map_OSM.getOverlayManager().add(overlay);
        }
    }

```


and you can call with this


```
AddImageMap4(map_OSM,bitmap,
                          46.2083792, 12.6017574, 
                          46.2086345, 12.6147794, 
                          46.1994257, 12.6021224,
                          46.1997145, 12.6151668,
                          20);
```

**Comment by monsieurtanuki** [comment]
@PaoloDozio Thanks! I'll try to work on it Sunday.

**Comment by MKergall** [comment]
@monsieurtanuki & @PaoloDozio 
Great job! 
2 remarks: 
- Is it complicated to "merge" GroundOverlay2 and GroundOverlay4 in a single class, as done by [GroundOverlay Google API](https://developers.google.com/android/reference/com/google/android/gms/maps/model/GroundOverlay)? 
- And then just name it "GroundOverlay"?... (I can get rid of existing OBP GroundOverlay, if this is causing you troubles)

**Comment by monsieurtanuki** [comment]
I can do this by the end of the week.

**Comment by monsieurtanuki** [comment]
Done. I kept the 2 corner matrix different from the 4 corner matrix, because I wasn't sure about the performances. In an ideal world we would use only one matrix: less confusion in the code.

**Comment by MKergall** [comment]
Is it already pushed somewhere?

**Comment by monsieurtanuki** [comment]
in this [commit](https://github.com/osmdroid/osmdroid/pull/1364/commits/ddbcbbece2e916af772b9092ba5d4870938fefec)

**Comment by MKergall** [comment]
Possible to add this getter before releasing? 

/**
     * @return the list of bounds, as: 
     *  - top-left, bottom-right, if 2 bounds
     *  - clock-wise from top-left, if 4 bounds
     */
	public ArrayList<GeoPoint> getAllBounds(){
        ArrayList<GeoPoint> bounds = new ArrayList<GeoPoint>(4);
	    if (mTopRight == null) {
            bounds.add(mTopLeft);
            bounds.add(mBottomRight);
        } else {
            bounds.add(mTopLeft);
            bounds.add(mTopRight);
            bounds.add(mBottomRight);
            bounds.add(mBottomLeft);
        }
        return bounds;
	}

**Comment by monsieurtanuki** [comment]
@MKergall I've just added 4 standard getters for the corners, that you can use for your own specific needs.

**Comment by MKergall** [comment]
@monsieurtanuki Better than nothing. Thanks.
