### ISSUE TITLE
app crash on Marker definition

### ISSUE THREAD

**Issue by dehkordy** [osmdroid/osmdroid#1362]
I used eclipse and osmdroid.jar file . app show map but when add marker app crash in this line :

Marker startMarker = new Marker(mMapView);

### If it's a bug, version(s) of android this affects:

All

### Version of osmdroid the issue relates to:

6.1.0

**Comment by spyhunter99** [comment]
anymore info on this?

**Comment by dehkordy** [comment]
Hi 
i used aar 6.1.0 file , unzip it and change classes.jar to osmdroid.jar and use as lib in Eclipse 
i can show google map on app with this code : 
mMapView = new MapView(this);
		mMapView.setTilesScaledToDpi(true);
		mMapView.setBuiltInZoomControls(false);
		mMapView.setMultiTouchControls(true);

		
		rl.addView(mMapView, new RelativeLayout.LayoutParams(LayoutParams.FILL_PARENT,
				LayoutParams.FILL_PARENT));

		// zoom to the netherlands
		mMapView.getController().setZoom(1.);
		mMapView.getController().setCenter(new GeoPoint(32, 50));

		// Add tiles layer with custom tile source
		final MapTileProviderBasic tileProvider = new MapTileProviderBasic(getApplicationContext());
		final ITileSource tileSource = new XYTileSource("FietsRegionaal",  3, 18, 256, ".png",
				new String[] { "http://overlay.openstreetmap.nl/openfietskaart-rcn/" });
		
		final OnlineTileSourceBase GoogleHybrid = new XYTileSource("Google-Hybrid",
				0, 19, 256, ".png", new String[] {
				"http://mt0.google.com",
				"http://mt1.google.com",
				"http://mt2.google.com",
				"http://mt3.google.com",

				}) {
				@Override
				public String getTileURLString(long pMapTileIndex) {
					return getBaseUrl() + "/vt/lyrs=y&x=" + MapTileIndex.getX(pMapTileIndex) + "&y=" +MapTileIndex.getY(pMapTileIndex) + "&z=" + MapTileIndex.getZoom(pMapTileIndex);
				}
			};
		
		tileProvider.setTileSource(GoogleHybrid);
		tileProvider.getTileRequestCompleteHandlers().add(mMapView.getTileRequestCompleteHandler());
		final TilesOverlay tilesOverlay = new TilesOverlay(tileProvider, this.getBaseContext());
		tilesOverlay.setLoadingBackgroundColor(Color.TRANSPARENT);
		mMapView.getOverlays().add(tilesOverlay);

		GeoPoint startPoint = new GeoPoint(32, 50);
        
        /*
        Marker startMarker = new Marker(mMapView);
        startMarker.setPosition(startPoint);
        startMarker.setAnchor(Marker.ANCHOR_CENTER, Marker.ANCHOR_BOTTOM);
        mMapView.getOverlays().add(startMarker);
*/
		but app crash on this line :   Marker startMarker = new Marker(mMapView);  


Thanks .

**Comment by spyhunter99** [comment]
probably failing due to a missing resource....by using eclipse for android projects, you are just making your life harder. we don't really support this configuration nor does google.

do you have a stacktrace or a line number where its failing

**Comment by spyhunter99** [comment]
i think if you include all the resource files from the aar into your project, it should work. since this hasn't been updated in a few months, i'm closing it. reopen if needed
