### ISSUE TITLE
Online tile source with center

### ISSUE THREAD

**Issue by pasniak** [osmdroid/osmdroid#1363]
Is it possible/hard to add an online tile source which follows the following schema:
...clon=-79.34796142578125&clat=40.73429841520857&zoom=8&width=920&height=630
?

clon/clat are the image center 
zoom is the same zoom level as openstreetmaps
width/height are pixel sizes (fixed 920x630)

## Issue Type

[x] Question

**Comment by spyhunter99** [comment]
yes, its just a matter of formatting the url correctly. also keep in mind that if the source projection is different from web mercator, then you may have alignment issues

**Comment by monsieurtanuki** [comment]
I guess that would involve the following `TileSystem` methods:
* `getMercatorXFromLongitude`
* `getMercatorYFromLatitude`
* `getTileFromMercator`

**Comment by pasniak** [comment]
I could not figure it out :(  I got as far as reverse out zoom level, x, and y (tile coords?) out off pMapTileIndex passed into getTileURLString.  How do I get tile Lat/Lon out of tile x/y coords?

**Comment by monsieurtanuki** [comment]
Something like that should do the trick:
````java
final int tileSize = TileSystem.getTileSize();
final double mapSize = TileSystem.MapSize((double)zoom);
final int tileY = TileSystem.getTileFromMercator(tileSystem.getMercatorYFromLatitude(latitude, mapSize, true), tileSize));
final int tileX = TileSystem.getTileFromMercator(tileSystem.getMercatorXFromLongitude(longitude, mapSize, true), tileSize));
````

Maybe we should add a dedicated "getTile" method in `TileSystem`. I also noticed, when coding a test, that there's a side-effect for longitude "far-east". To be fixed.

**Comment by pasniak** [comment]
1) I am in a method overriding OnlineTileSourceBase.getTileURLString(pMapTileIndex: Long)... I do not see a tileSystem object (to call getMercatorYFromLatitude which is a non-static function).

2) Maybe it is something obvious but tileX/tileY above are int... (ex: 1530, 1100) How do I get Latitude/Longitude **in degrees**?  (Those are latitude/longitude inputs above)

**Comment by monsieurtanuki** [comment]
@pasniak Fair enough, I was converting the other way around:
* the input is the map tile index (z/x/y)
* and you need to compute the center (longitude, latitude) of the corresponding tile in order to feed the download URL

Step 1 is to compute the "X01" of the longitude and the "Y01" of the latitude of the center of the tile.
"X01" and "Y01" refer to the whole world being projected into a [0,1] x [0,1] square (in `double`). For instance, 0 is the north and the west limit, and 1 is the south and west limit. And (.5, .5) is the center of a world map (which is btw the center of the 0/0/0 tile).
Step 2 is to use the `TileSystemWebMercator.getLongitudeFromX01` and `TileSystemWebMercator.getLatitudeFromY01` methods in order to get the coordinates.

````java
// input: a map tile index (long) named "index"
final int zoom = MapTileIndex.getZoom(index);
final int tileX = MapTileIndex.getX(index);
final int tileY = MapTileIndex.getY(index);
final double x01 = ((double)(2 * tileX + 1)) / (1 << (zoom + 1));
final double y01 = ((double)(2 * tileY + 1)) / (1 << (zoom + 1));
final double latitude = MapView.getTileSystem().getLatitudeFromY01(y01);
final double longitude = MapView.getTileSystem().getLongitudeFromX01(x01);
````

Or something like that.

**Comment by pasniak** [comment]
That works... kind of :) I see [urls](https://mrms.nssl.noaa.gov/qvs/product_viewer/render_multi_domain_product_layer.php?prod_root=SHSR&year=2019&month=7&day=11&hour=1&minute=48&clon=-80.595703125&clat=26.8994400196206&zoom=11&width=920&height=630) emitted multiple times; the url works in Firefox but the app ultimately crashes with OOM. The image is 920px × 630px; does it matter? (forcing 256/256 does not work....)

**Comment by monsieurtanuki** [comment]
@pasniak As @spyhunter99 already mentioned, it can be problematic if the projection the tiles come from is not exactly what we at osmdroid are using (cf. [`TileSystemWebMercator`](https://github.com/osmdroid/osmdroid/blob/master/osmdroid-android/src/main/java/org/osmdroid/util/TileSystemWebMercator.java)). And at osmdroid we also only deal with square tiles, not rectangle tiles - so far.
My answer was more on the "TileToLatLng" aspect of your issue.
