### ISSUE TITLE
Map images and .aux.xml file

### ISSUE THREAD

**Issue by PaoloDozio** [osmdroid/osmdroid#1365]
## Issue Type

[X] Question
[ ] Bug
[ ] Improvement
[ ] Build system related
[ ] Performance
[ ] Documentation

## Description and/or steps/code to reproduce the problem

I found these very high quality map images .jpg with a related .aux.xml file.
For example I have the image W11R_03_10.jpg

![image](https://user-images.githubusercontent.com/46484640/60369442-f2231980-99f3-11e9-9440-9dfd3dcaf8e8.png)

and the related W11R_03_10.jpg.aux.xml

```
<PAMDataset>
  <GeoTransform> 6.3400166192197241e+005, 2.4996304641589999e+000, 0.0000000000000000e+000, 5.0480000401870431e+006, 0.0000000000000000e+000,-2.4999779924459999e+000</GeoTransform>
  <Metadata domain="IMAGE_STRUCTURE">
    <MDI key="COMPRESSION">JPEG</MDI>
    <MDI key="INTERLEAVE">PIXEL</MDI>
    <MDI key="SOURCE_COLOR_SPACE">YCbCr</MDI>
  </Metadata>
  <PAMRasterBand band="1">
    <Metadata domain="IMAGE_STRUCTURE">
      <MDI key="COMPRESSION">JPEG</MDI>
    </Metadata>
  </PAMRasterBand>
  <PAMRasterBand band="2">
    <Metadata domain="IMAGE_STRUCTURE">
      <MDI key="COMPRESSION">JPEG</MDI>
    </Metadata>
  </PAMRasterBand>
  <PAMRasterBand band="3">
    <Metadata domain="IMAGE_STRUCTURE">
      <MDI key="COMPRESSION">JPEG</MDI>
    </Metadata>
  </PAMRasterBand>
</PAMDataset>
```

I don't know this type of GPS coordinate.
How would like to use all the files .jpg and .xml in my App with OSMDroid library.
Is it possible to use all the images as a map?
Or is it possible to add these images as overlay using the information in the XML file?

 Thanks and sorry for my low knowledge in GPS coordinate..

**Comment by monsieurtanuki** [comment]
@PaoloDozio I couldn't find a text saying that Tabacco Map is allowing the external use of its tiles; please send the URL where it's mentioned.
Besides that, I don't know anything about this xml tile format.

**Comment by PaoloDozio** [comment]
Ok. Thanks. Maybe the images cannot be used.
Could you remove this post?
Thanks.

**Comment by spyhunter99** [comment]
i only think neil can delete issues, you can edit the issue and just remove the content, then close it
