### ISSUE TITLE
NPE in MyLocationNewOverlay.setLocation()

### ISSUE THREAD

**Issue by InI4** [osmdroid/osmdroid#1368]
## Issue Type

[X ] Bug

## Description and/or steps/code to reproduce the problem

I found the following (rare but) stacktrace in my apps Crashlytics
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void org.osmdroid.views.MapView.postInvalidate()' on a null object reference
       at org.osmdroid.views.overlay.mylocation.MyLocationNewOverlay.setLocation + 444(MyLocationNewOverlay.java:444)
       at org.osmdroid.views.overlay.mylocation.MyLocationNewOverlay.enableMyLocation + 459(MyLocationNewOverlay.java:459)
```

Note, the line numbers are probably wrong, as I am using a fork of 6.1.0, as I rely on the fix of #1299, otherwise my app crashes my app too often.

The calling `MyLocationNewOverlay.enableMyLocation()` does also do an `MapView.postInvalidate()` , but with a `null` check, whereas `setLocation()` just calls that `postInvalidate()` and runs into this `NullPointerException`.

1. Not both `postInvalidate()` might be needed.
2. It should be null checked in any case.

### If it's a bug, version(s) of android this affects:

Crashlytics on a Samsung S9 with Android 9.

### Version of osmdroid the issue relates to:

6.1.0 fork, as explained above, I need the fix for #1299, otherwise 6.1.0+ are useless for me.

**Comment by monsieurtanuki** [comment]
Feel free to send a PR with the additional `mMapview != null` check in `setLocation`, that's a quick fix!

Should/could `postInvalidate` be called less often: maybe, maybe not, anyway `postInvalidate` doesn't trigger an immediate refresh. As very close calls eventually trigger the same unique refresh, I don't think we need to spend too much time trying to remove those calls.

**Comment by InI4** [comment]
resolved by above PR
