### ISSUE TITLE
A question about OSM Map data quantity

### ISSUE THREAD

**Issue by wangzi6578** [osmdroid/osmdroid#1370]
Hi，there，
Today,I found a question about OSM map, i get road data from any  one city  in osm map, it about 100M, but i get total country's road data, it only about 1G,however, it contains hundreds cities,that's incredible，is there any expert could solve my doubt

**Comment by InI4** [comment]
This is the wrong space to discuss OSM packaging, this is about a library for using OSM in apps.

Having said this, packaging and level of detail is varying in in so many cases and lots of variants are available, that the question is not eas to answer in the requested generality.

Precision your question and then ask it here: https://stackoverflow.com/questions/tagged/openstreetmap

**Comment by spyhunter99** [comment]
sounds about right for vector data.
