### ISSUE TITLE
KMZ maps

### ISSUE THREAD

**Issue by onuff** [osmdroid/osmdroid#1372]
Hello}
add support  KMZ maps

Please note: issues related to or caused by osmbonuspack will be closed with a
suggestion to open an issue at https://github.com/MKergall/osmbonuspack

(feel free to delete whatever doesn't apply)

## Issue Type

[ ] Question
[ ] Bug
[ ] Improvement
[ ] Build system related
[ ] Performance
[ ] Documentation

### If it's a bug, version(s) of android this affects:

All

### Version of osmdroid the issue relates to:

6.0.2

**Comment by monsieurtanuki** [comment]
Obviously related to osmbonuspack, [which supports KML](https://github.com/MKergall/osmbonuspack/wiki).
Closing the issue on osmdroid: have a go with osmbonuspack!

**Comment by onuff** [comment]
you did not understand.
this are maps,
not point

**Comment by monsieurtanuki** [comment]
@onuff I'm no sure I know what it's about. Could you please add links to "KMZ maps" reference or samples?

**Comment by onuff** [comment]
https://yadi.sk/i/M_F-kustIA4ATg
https://yadi.sk/i/MuAKXVOuGFNNwg
https://yadi.sk/d/s7H7zunoBLnIvQ
https://yadi.sk/i/YghwCU2whB8apw
https://yadi.sk/d/7-QsGQSTIc9SXQ

**Comment by monsieurtanuki** [comment]
The last link "подход.kmz" is exactly what I mean by KMZ file, which is handled by osmbonuspack as I stated before.
To be 100% accurate, I'm sure osmbonuspack handles "KML" format, perhaps not KMZ, but KMZ is just a ZIP file containing a KML file and additional resources.

**Comment by spyhunter99** [comment]
concur, however there are certain feature sets of kml and kmz that are not supported by osmbonuspack, such as animations and i think network references whereby the kml or kmz requires another set of downloads.

**Comment by MKergall** [comment]
Yes, OSMBonusPack supports KMZ files, with restrictions. 
Full details (and restrictions) here: https://github.com/MKergall/osmbonuspack/wiki/KML

**Comment by onuff** [comment]
Sorry, it is possible to add the map kmz?
