### ISSUE TITLE
Advanced Polyline drawing

### ISSUE THREAD

**Issue by mat8854** [osmdroid/osmdroid#1378]
## Issue Type

[X ] Improvement

## Description and/or steps/code to reproduce the problem

Neither the base library nor osmbonuspack support advanced Polyline drawing like:
* Polylines with a simple border
![Screenshot_1564570518](https://user-images.githubusercontent.com/2643309/62206683-a5d04e00-b392-11e9-96a4-a2a2efc2ff4c.png)

* Polylines with segments of different colors. Examples from Leaflet here: http://hgoebl.github.io/Leaflet.MultiOptionsPolyline/demo/

We began some prototyping for our needs. Like modifications to the Paint object with Shaders etc.:
* https://developer.android.com/reference/android/graphics/Shader in the LineDrawer class https://github.com/osmdroid/osmdroid/blob/master/osmdroid-android/src/main/java/org/osmdroid/views/overlay/LineDrawer.java

Are there already existing solutions we are missing?

### Version of osmdroid the issue relates to:

6.1.0

**Comment by monsieurtanuki** [comment]
Some answers may be found in [milestones](https://github.com/osmdroid/osmdroid/wiki/Milestones-feature).

**Comment by mat8854** [comment]
Yes, but milestones do not cover everything we need. We can play back some extensions to osmdroid. Before we have to test them more before.

**Comment by spyhunter99** [comment]
cool!

**Comment by mat8854** [comment]
Will open a PR.

A gradient with LinearGradient is now also included:
![Screenshot_1567023841](https://user-images.githubusercontent.com/2643309/63890210-c1a33000-c9e2-11e9-804d-1336ca3ead3d.png)

**Comment by monsieurtanuki** [comment]
@mat8854 Awesome! Don't forget to include a demo, something like a Tour de France stage.

**Comment by mat8854** [comment]
Haha yes. Will include some real data Polylines in the sample app (train, car, bicycle). Forgot to track a TVG ride from Marseille few month ago. Tour de France data should be public somewhere.

**Comment by monsieurtanuki** [comment]
@mat8854 Great job!

**Comment by Haukinger** [comment]
Is there any documentation about how to use this feature?

I'm trying to get a gradient into my polyline, but it's always painted with the highest color, no matter what scalars I add to the mapping.

**Comment by monsieurtanuki** [comment]
@Haukinger I guess you should take a look at the [dedicated wiki page](https://github.com/osmdroid/osmdroid/wiki/Polyline-advanced-display-styles), and at the demo code (can't remember now the name of the sample in the demo app).

**Comment by mat8854** [comment]
@Haukinger You should copy a sample from this [file](OpenStreetMapViewer/src/main/java/org/osmdroid/samplefragments/drawing/ShowAdvancedPolylineStyles.java), see in function `setupExamples()`. They work.
@monsieurtanuki I was waiting for the 6.1.6 release. Is there a schedule?

**Comment by Haukinger** [comment]
@monsieurtanuki I figured it out, now it works fine. Two things that weren't obvious to me at first:

* ColorMappingRanges assigns colors to scalars lower than the color
 I wanted to color the interval 0...1, so I should have input colors for 0.000001 (not 0) and 1. I think `if(pScalar <= entry.getKey())` would be better without breaking anything.
* One has to input exactly one scalar for each GeoPoint
This is not clear from the examples, as far as I could see, as the numbers don't seem to match there.

**Comment by mat8854** [comment]
@Haukinger @monsieurtanuki Such things only manifest when people start using the features. Should be changed yes.

**Comment by monsieurtanuki** [comment]
Regarding `ColorMappingRanges`, I don't know if `pScalar <= entry.getKey()` makes more sense than `<`. It depends on the logic behind. How do other people do with ranges in the vast world of code? I presume than in some cases it makes sense to use the same color for values 1.99999 and 2, and in other cases for values 2 and 2.000001. I guess the solutions would be to:
* in osmdroid, add a "strict comparison?" boolean parameter in the constructor `ColorMappingRanges`, with an explicit javadoc entry - I can do that
* for users, add something like a `Float.MIN_VALUE` to the input list whenever it's relevant

Regarding the scalar/`GeoPoint` being one-to-one, @mat8854 could you fix your data (I believe the problem was at least with the Himalayan data).

@spyhunter99 Once both those minor fixes are merged - and I'm sure that could be done by the end of the week - when would you be ready for a new osmdroid version?

**Comment by monsieurtanuki** [comment]
OK, @mat8854 you've just fixed the data, and I was supposed to push a "strict/not strict comparison" code. I coded it. Then committed. But Android Studio 3.6.1 decided to change the way it looks and to display the "push" window so big that the "ok" button is out of reach...

**Comment by monsieurtanuki** [comment]
Finally managed to push my code in #1505. Merged.

**Comment by monsieurtanuki** [comment]
Done.
