### ISSUE TITLE
It takes a very long time to build a map

### ISSUE THREAD

**Issue by s-ilnar** [osmdroid/osmdroid#1380]
#1193 I already asked a similar question.

[ x] Question
[ ] Bug
[ ] Improvement
[ ] Build system related
[ ] Performance
[ ] Documentation

## Description and/or steps/code to reproduce the problem
Hello! Thanks for your work!

**Is this the problem only with me?**
This is problem -> https://drive.google.com/file/d/1R9LnZ8n1HWngGeD8Fx2_r537q-AD5RlM/view?usp=drivesdk
My application is also long too ..

For the test I used this application: https://play.google.com/store/apps/details?id=org.osmdroid&hl=ru

### If it's a bug, version(s) of android this affects:

I checked for 7.1 and 9.0

### Version of osmdroid the issue relates to:

6.1.0

**Comment by monsieurtanuki** [comment]
I guess you're using the default tiles (openstreetmap). Do you still find it slow with other tile sources, like opentopo?

**Comment by spyhunter99** [comment]
thats about what is expected due to osm's tile policy. we can definitely make it faster but they do not want us to do so. It is free after all. you can either use another tile source or host your own server

**Comment by s-ilnar** [comment]
> I guess you're using the default tiles (openstreetmap). Do you still find it slow with other tile sources, like opentopo?

Using another source becomes faster. 



> thats about what is expected due to osm's tile policy. we can definitely make it faster but they do not want us to do so. It is free after all. you can either use another tile source or host your own server

Yes, we will soon post our OSM map source.


I will definitely report the results! I hope the speed will be like in google maps)
