### ISSUE TITLE
Offline map higher level zoom 

### ISSUE THREAD

**Issue by liuzy1993** [osmdroid/osmdroid#1382]
Offline map zooms downloaded using Mobile Atlas Creator can only be 2 to 15 levels. What do I need to do if I need a higher map zoom?

**Comment by spyhunter99** [comment]
find a tile source that goes to a higher res or use the map tile approximator, which will render the closest tile stretched to fit. mapsforge can get you vector maps that render on demand, so there's that.

**Comment by monsieurtanuki** [comment]
@liuzy1993 Feel free to reopen this issue if needed.
