### ISSUE TITLE
release vote?

### ISSUE THREAD

**Issue by spyhunter99** [osmdroid/osmdroid#1384]
we are over do. i can cut a release anytime really, but unfortunately ive lost track of the issues. does anything need to be fixed and/or merged before this is cut?

**Comment by monsieurtanuki** [comment]
Hi @spyhunter99!

Comments about some PR's:
* #1364 (which solves #1361) - new feature, should have a very limited impact. Succesfully tested by @PaoloDozio
* #1358 (#1347) - totally new feature I created an issue for, should have a very limited impact. @MKergall was enthousiastic
* #1354 (#1346) - totally new feature I created an issue for, should have a very limited impact. Screenshots available on the issue page
* #1353 (#1348, #1294) - improvement, should have a limited impact. Expected by @PaoloDozio and @pasniak 
* #1285 (#1280) - improvement, should have a limited impact. Expected by @conej730 and @Ruediger34
* #1152 (#1145) - improvement, possible impact on MapsForge. Expected by @secaw and @pavelkv96

**Comment by InI4** [comment]
https://github.com/osmdroid/osmdroid/pull/1353 I'd really like to experiment with this, but it is not high priority, so I hesitate to do it, without an release in range (I prefer to build my releases on lib releases).

**Comment by MKergall** [comment]
#1364 I'd really like to have it in this release.

**Comment by PaoloDozio** [comment]
#1353 (#1348, #1294) - I'd really like to have it in this release.
#1364 (which solves #1361) - Succesfully tested by me but it is not mandatory for release.

**Comment by Ruediger34** [comment]
#1353 and #1285 would be very nice

**Comment by spyhunter99** [comment]
ok thanks for the feedback. ill carve out some osmdroid time this weekend

**Comment by conej730** [comment]
hey @spyhunter99 any updates on the new release?

**Comment by spyhunter99** [comment]
build is in progress now. we have a test failure unfortunately.....

org.osmdroid.util.MyMathTest > testComputeCirclePoint FAILED
    junit.framework.AssertionFailedError at MyMathTest.java:66

@monsieurtanuki know anything about this? or anyone?

**Comment by spyhunter99** [comment]
junit.framework.AssertionFailedError: expected:<-10> but was:<10>

**Comment by spyhunter99** [comment]
changing lines 66, 70, 74 from output.y to -output.y resolves the test failures. not sure if this is the right way to go or not.  may be related to #1347

**Comment by monsieurtanuki** [comment]
@spyhunter99 Changing lines 66, 70 and 74 was the correct fix. Sorry about that. @pasniak already mentioned that problem (it's actually clockwise).
As an impact, not sure if the speech balloons are 100% accurate. But as it's a new feature, I guess we can tolerate some inaccuracy.

**Comment by spyhunter99** [comment]
mmk on it

**Comment by monsieurtanuki** [comment]
@spyhunter99 Thank you!
