### ISSUE TITLE
Disabling/Enabling RotationOvelay causes rotation jumps

### ISSUE THREAD

**Issue by worldsnas** [osmdroid/osmdroid#1385]
## Issue Type

[ ] Question
[x] Bug
[ ] Improvement
[ ] Build system related
[ ] Performance
[ ] Documentation

## Description of the problem
if we add the rotation overlay but disable the overlay and set map rotation manually when we enable it again it jumps to the last rotation that was set by the user and wont follow the fixed rotation we applied on map and causes a UI jump

### If it's a bug, version(s) of android this affects:

All

### Version of osmdroid the issue relates to:

6.0.2

there is a very easy way to fix this and that is by passing mEnabled paramter to gestureDetector and let capture the user events but block publishing it (PR on it's way!).

**Comment by spyhunter99** [comment]
merged

**Comment by spyhunter99** [comment]
https://github.com/osmdroid/osmdroid/pull/1386
