### ISSUE TITLE
Loading tiles when virtually over-zooming beyond existing tiles.

### ISSUE THREAD

**Issue by apacha** [osmdroid/osmdroid#1388]
## Issue Type

[ ] Question
[ ] Bug
[x] Improvement
[ ] Build system related
[ ] Performance
[ ] Documentation

## Description

This is a feature request for improvement. The scenario is the following: We have custom tiles for certain zoom levels 4-15. Now the user zooms in beyond the finest available layer (e.g., 17), upon which OSMDroid virtually over-zooms the existing tiles (which is great). Unfortunately, it does not load neighboring tiles, so panning creates gray spaces until the user zooms back to a level that has tiles available.

See this video for a visualization:
![ezgif com-resize](https://user-images.githubusercontent.com/594497/63869774-01edb880-c9b9-11e9-985e-5f6231aa4160.gif)

It would be great if OSMDroid could also load and over-zoom neighboring tiles, even if those tiles are only available at a coarser zoom-level and have to be upscaled.

### Version of osmdroid the issue relates to:

6.1.0

**Comment by monsieurtanuki** [comment]
@apacha The `MapTileApproximater` - when part of your `MapTileProviderArray` - is supposed to deal with those cases. Are you [using it](https://github.com/osmdroid/osmdroid/blob/master/osmdroid-android/src/main/java/org/osmdroid/tileprovider/MapTileProviderBasic.java#L104)?

**Comment by apacha** [comment]
That is EXACTLY what I was looking for. You are the BEST!
