### ISSUE TITLE
Animating markers on mapview

### ISSUE THREAD

**Issue by adolfdsilva** [osmdroid/osmdroid#139]
Hi,
I'm using the google Maps marker animation logic given here.
https://gist.github.com/broady/6314689

My marker gets animated,but after each marker.setPosition(newPosition); I need to call mapView.invalidate();which refreshes the entire map resulting in very sluggish animation.

Is there any workaround?

**Comment by RezaOruji** [comment]
i have the same problem too.
@adolfdsilva  could you find a solution ?

**Comment by spyhunter99** [comment]
Can you invalidate just the market?

**Comment by RezaOruji** [comment]
@spyhunter99 does marker have this capability ? i couldn't find any `invalidate `method on `Marker `and `Overlay`

**Comment by spyhunter99** [comment]
apparently not. I bet @MKergall will have an idea

**Comment by MKergall** [comment]
Old pending issue: see [OSMBonusPack issue #88](https://github.com/MKergall/osmbonuspack/issues/88). 

You could try to use MapView.invalidateMapCoordinates(Rect dirty). 
The difficulty is to build this dirty rect. Most of the code can be found in Marker.draw method:
mPositionPixels is the marker position, and rect is the icon bounds. 
So dirty = rect.offset(mPositionPixels). 

@RezaOruji if you succeed, providing this feature as a Marker.invalidate method would be really relevant.

**Comment by RezaOruji** [comment]
@MKergall  Thank you . i will inform you  if it works.

**Comment by always-beta** [comment]
@RezaOruji Did you find a solution?

@MKergall 
From my test, no matter what I  invalidate is the whole mapview or a certain small area using invalidateMapCoordinates, ALL of my overlays onDrawItem are called, am I missing some other settings here?
If I use wrong rect for the invalidateMapCoordinate function, the overlay won't be refreshed but onDrawItem is still being called.

What I'm trying to do is refresh the user's location overlay's (customised one) rotation according to device orientation changes, the changes are very frequent and I also have bunch of other overlays on the map so the cpu becomes really busy if I invalidate the whole map all the time.
Any other workaround?

**Comment by MKergall** [comment]
@always-beta 
"no matter what I invalidate is the whole mapview or a certain small area using invalidateMapCoordinates, ALL of my overlays onDrawItem are called"
=> Yes, it's normal. All overlays draw methods have to be called (the osmdroid framework cannot guess which object has to be really drawn), but low level drawing calls are performed with a clipping set on the reduced area. 

You have to set your update frequency as a compromise between smooth display and cpu usage. Possible hint: redraw only if the rotation change is "significant" (above a certain level).

**Comment by always-beta** [comment]
@MKergall Yeah, thanks for the hint, I already used a compromised frequency.

Just one more question, where does the low level drawing calls that apply clipping area happen? In Android's View class or osmdroid framework?

**Comment by RezaOruji** [comment]
@always-beta  i wrote a method but i think it also invalidates the whole view : 
```
    public void invalidate(MapView mapView) {
        if (mIcon == null)
            return;

        final Projection pj = mapView.getProjection();

        pj.toPixels(mPosition, mPositionPixels);
        int width = mIcon.getIntrinsicWidth();
        int height = mIcon.getIntrinsicHeight();
        Rect rect = new Rect(0, 0, width, height);
        mapView.invalidateMapCoordinates(rect);
    }
```

**Comment by MKergall** [comment]
@always-beta Low-level drawing calls are the calls to Android drawing methods, inside the draw method of each overlay class. 
Examples: 
- Marker.draw is calling Overlay.drawAt, calling Drawable.draw(canvas) => low-level, Android. 
- Polyline.draw is calling Canvas.drawPath => low-level, Android.

**Comment by always-beta** [comment]
@MKergall got it.

@RezaOruji Yeah I tried that and it eventually triggers overlaymanager's onDraw which will iterate all overlays and redraw them.

I guess it's hard to do decent animations for overlays in my case since I have lots of overlays to show, I probably end up using another way to show what I'm trying to indicate rather than using overlay.

**Comment by spyhunter99** [comment]
operation timeout. please reopen or comment back if you have further questions
