### ISSUE TITLE
Problem with Tiles Overlay

### ISSUE THREAD

**Issue by tonydema** [osmdroid/osmdroid#1390]
## Issue Type

[x] Question
[x] Bug
[ ] Improvement
[ ] Build system related
[ ] Performance
[ ] Documentation

## Description and/or steps/code to reproduce the problem
I'm trying to load a second layer with hiking marked trail from:
https://hiking.waymarkedtrails.org/

On my android app in this way:

`  map = (MapView) view.findViewById(R.id.map);
        
        final MapTileProviderBasic tileProvider = new MapTileProviderBasic(getActivity().getApplicationContext());
        tileProvider.setTileSource(MAPNIK);
        
        final MapTileProviderBasic anotherTileProvider = new MapTileProviderBasic(getActivity().getApplicationContext());
        OnlineTileSourceBase hiking = new OnlineTileSourceBase("Hiking", 0, 19, 256, ".png",
                new String[] { "https://tile.waymarkedtrails.org/hiking/" }) {
            @Override
            public String getTileURLString(long pMapTileIndex) {
                return getBaseUrl()
                        + MapTileIndex.getZoom(pMapTileIndex)
                        + "/" + MapTileIndex.getY(pMapTileIndex)
                        + "/" + MapTileIndex.getX(pMapTileIndex)
                        + mImageFilenameEnding;
            }
        };
        
        anotherTileProvider.setTileSource(hiking);
        // anotherTileProvider.setTileSource(TileSourceFactory.FIETS_OVERLAY_NL);
        final TilesOverlay secondTilesOverlay = new TilesOverlay(anotherTileProvider, getActivity().getBaseContext());
        secondTilesOverlay.setLoadingBackgroundColor(Color.TRANSPARENT);
        
        GeoPoint startPoint = new GeoPoint(37.7510032, 14.9759253);
        IMapController mapController = map.getController();
        mapController.setZoom(15);
        mapController.setCenter(startPoint);
        
        map.setTileSource(MAPNIK);
        map.getOverlays().add(secondTilesOverlay);
        map.invalidate();`

I initialize an **OnlineTileSourceBase** object but it doesn't seem to work and I don't see any layer over the map.
while if try with:

`anotherTileProvider.setTileSource(TileSourceFactory.FIETS_OVERLAY_NL);`

it works so I think it's something my  **OnlineTileSourceBase** object 
I'm preatty sure that url where i take tiles is correct because if i go for example:

https://tile.waymarkedtrails.org/hiking/12/2216/1581.png

I see one of it.

Does anyone have any suggestions? 
thank you

## Environment
Android
### If it's a bug, version(s) of android this affects:
All

### Version of osmdroid the issue relates to:

6.1.0

**Comment by monsieurtanuki** [comment]
@tonydema It looks like you're interverting X and Y (cf. https://wiki.openstreetmap.org/wiki/Hiking_Maps). I suggest something like:
````java
new XYTileSource("Hiking", 0, 19, 256, ".png", new String[] { "https://tile.waymarkedtrails.org/hiking/" })
````

**Comment by tonydema** [comment]
@monsieurtanuki thanks 
I have I tried but nothing change.

I had instantiated the object in that way because documentation ( https://github.com/osmdroid/osmdroid/wiki/Map-Sources ) says that for that type of url ( https://tile.waymarkedtrails.org/hiking/{z}/{x}/{y}.png ) and osmdroid version >= 6 they tell to use this:

`mMapView.setTileSource(new OnlineTileSourceBase("USGS Topo", 0, 18, 256, "", 
               new String[] { "http://basemap.nationalmap.gov/ArcGIS/rest/services/USGSTopo/MapServer/tile/" }) {
               @Override
               public String getTileURLString(long pMapTileIndex) {
                    return getBaseUrl()
                           + MapTileIndex.getZoom(pMapTileIndex)
                           + "/" + MapTileIndex.getY(pMapTileIndex)
                           + "/" + MapTileIndex.getX(pMapTileIndex)
                           + mImageFilenameEnding;
               }
          });`

It is strange that they reverse X with Y but changing the order does't work too.
Perhaps some particular permission is missing!?

**Comment by monsieurtanuki** [comment]
@tonydema Read again the wiki text: _USGS, as well as many other ArcGis based sources, use **Zoom/Y/X** and thus require a **different URL pattern**._
In your more standard case it's Z/X/Y.

I've just tried successfully to use your tile provider:
* I used the code of demo [`SampleWithTilesOverlay`](https://github.com/osmdroid/osmdroid/blob/master/OpenStreetMapViewer/src/main/java/org/osmdroid/samples/SampleWithTilesOverlay.java)
* I replaced the tile layer part with this:
````java
mProvider.setTileSource(new XYTileSource("Hiking", 0, 19, 256, ".png",
		new String[]{"https://tile.waymarkedtrails.org/hiking/"},
		"TODO"));
````
Et voilà :
![Screenshot_2019-08-29-12-51-35](https://user-images.githubusercontent.com/11576431/63934530-e4255f80-ca5b-11e9-9a8d-f190096768ec.png)

**Comment by tonydema** [comment]
it's true! it works! thank you very much @monsieurtanuki
