### ISSUE TITLE
Marker SVG support?

### ISSUE THREAD

**Issue by markaw375** [osmdroid/osmdroid#1393]
Hi,

Does osmdroid support SVG for the map Markers?

Thanks,
Marcin

**Comment by mat8854** [comment]
The marker call needs a Drawable `setIcon(Drawable icon)`. 

We used this lib `implementation 'com.caverock:androidsvg:1.4'`. Loading and converting a SVG is a two-liner:
`SVG svg = SVG.getFromResource(context, svgRaw);`
`Drawable d = new PictureDrawable(svg.renderToPicture());`

I wrote a small article about the lib on my website a long time ago.

**Comment by spyhunter99** [comment]
not directly no, the above code should do the trick though
