### ISSUE TITLE
Problem with Polyline

### ISSUE THREAD

**Issue by GioJS** [osmdroid/osmdroid#1394]
Hi,
I'm using a Polyline to draw a path (and it works), but when I load a path from database is drawn as a Ring (but itsn't a Ring!).

this is the code
```java

polyline.color = Color.BLUE
polyline.width = 12.0f
for (point in list) {
    polyline.addPoint(GeoPoint(point.lat!!, point.lon!!))
 }

map.overlays.add(polyline)
```

Any suggestions?

P.S.
If you draw(using for example this [tool](https://arthur-e.github.io/Wicket/sandbox-gmaps3.html))  this linestring (extracted from my services) you can see that the line is not closed!
```LINESTRING(12.532974 41.955514,12.533171 41.955413,12.531689 41.954871,12.530356 41.955039,12.531458 41.954452,12.532138 41.953707,12.532584 41.953775,12.533388 41.954358,12.531523 41.954646)```

**Comment by mat8854** [comment]
Your code looks okay. What do you mean by 'Ring'??

**Comment by GioJS** [comment]
> Your code looks okay. What do you mean by 'Ring'??

Thanks for the reply.

I have [this ](https://pasteboard.co/Ivy5d6a.jpg) instread of [this](https://pasteboard.co/Ivy4SZo.png)

**Comment by mat8854** [comment]
So the last closing line is wrong? Are you sure your Array `list` is okay?

**Comment by GioJS** [comment]
> So the last closing line is wrong? Are you sure your Array `list` is okay?

Yes it is, if you look at the line string in the first post they're the same coordinates.
This is the log of my application:
```json
[{"lat":41.955514,"lon":12.532974},
 {"lat":41.955413,"lon":12.533171},
 {"lat":41.954871,"lon":12.531689},
 {"lat":41.955039,"lon":12.530356}, 
 {"lat":41.954452,"lon":12.531458},
 {"lat":41.953707,"lon":12.532138},
 {"lat":41.953775,"lon":12.532584}, 
 {"lat":41.954358,"lon":12.533388}, 
 {"lat":41.954646,"lon":12.531523}]```

**Comment by mehulpxm** [comment]
may I know what resolve this issue I have same issue
