### ISSUE TITLE
Draw Direction on Polyline

### ISSUE THREAD

**Issue by mehulpxm** [osmdroid/osmdroid#1396]
Hello,
I want to draw the direction on the map can you please suggest the proper example for that I didn't find anything proper from the earlier issue and the documentation.
version
6.1.0

**Comment by monsieurtanuki** [comment]
I'm not sure what you mean.
If you want something like displaying arrows that follow a Polyline's Path, Milestones are for you (cf. https://github.com/osmdroid/osmdroid/wiki/Milestones-feature).
Have a look at the corresponding samples in the demo app.
I hope this helps.

**Comment by mehulpxm** [comment]
can you please give me the url of that demo?

**Comment by monsieurtanuki** [comment]
The app named 'osmdroid' on google play.

**Comment by mehulpxm** [comment]
Thank you for the quick replies it solve my problem  and i am able to achive my expections by using milestones.
