### ISSUE TITLE
MapTileApproximater does not load tiles reliably

### ISSUE THREAD

**Issue by apacha** [osmdroid/osmdroid#1398]
## Issue Type
[x] Bug

## Description and/or steps/code to reproduce the problem
I'm using a `MapTileApproximater` on top of `MapTileFileArchiveProvider` to load tiles, even if for the highest zoom levels there are no more tiles available.

In general, this works fine, but the loading is unreliable and frequently leaves tiles unloaded, which creates quite large gray square, although card material is available. Once I start panning around or zooming, the respective tiles are loaded.

The effect is the following:
![Screenshot_1568985953](https://user-images.githubusercontent.com/594497/65332110-56521580-dbbe-11e9-830b-284e63a34852.png)

and this is how it should look like (what I get after a little panning):

![Screenshot_1568987157](https://user-images.githubusercontent.com/594497/65332111-56521580-dbbe-11e9-84bd-ea4758a9aaf5.png)

Please note two things:

* it does not matter how long I wait - the missing tiles are never loaded
* The problem does not occur when I'm not using the `MapTileApproximater` - then all tiles are loaded reliably (as long as they are available).

## Environment
osmdroid-android 6.0.3
Android SDK 29

**Comment by monsieurtanuki** [comment]
@apacha My 2 cents:
* does it happen with version 6.1.0?
* could you share your code that involves `MapTileApproximater`? (something like your own [`MapTileProviderBasic`](https://github.com/osmdroid/osmdroid/blob/master/osmdroid-android/src/main/java/org/osmdroid/tileprovider/MapTileProviderBasic.java)) Maybe the problem comes from the approximater's own providers

**Comment by apacha** [comment]
I cannot use version 6.1.0 because of [this bug](https://github.com/osmdroid/osmdroid/issues/1299), which is not acceptable for productive use and the fix will only be available in the next version.

Sure, here's basically how I use it (only the relevant parts):

    final IRegisterReceiver registerReceiver = new SimpleRegisterReceiver(context);
	final File mbtilesFile = FileUtilities.getMbtilesFile(context, mbTilePath);	
	final IArchiveFile[] files = {MBTilesFileArchive.getDatabaseFileArchive(mbtilesFile)};
	MapTileModuleProviderBase mapProvider = new MapTileFileArchiveProvider(registerReceiver, tileSource, files);
    
	MapTileApproximater approximater = new MapTileApproximater();
    approximater.addProvider(mapProvider);
    providerList.add(approximater);
	
	ITileSource tileSource = TileSourceFactory.DEFAULT_TILE_SOURCE;
    MapTileModuleProviderBase[] providers = providerList.toArray(new MapTileModuleProviderBase[providerList.size()]);
    // The providers that are actually used are stored in the providers-array
    MapTileProviderArray tileProviderArray = new MapTileProviderArray(tileSource, registerReceiver, providers);
	
	MapView mapView = new MapView(context, tileProviderArray);

**Comment by monsieurtanuki** [comment]
I don't know anything about the `IRegisterReceiver`, but that sounds like data fetch using callbacks.

With that in mind, I assume that sometimes the async provider cannot get the bitmap right away, which is why the approximater is called for that tile as a fallback.
The approximater uses the only provider it has - the same async provider - and computes an approximation with null bitmaps as input and therefore null bitmaps as output.
The bitmap tile is then stored as null with the "approximated" status.

It's deemed good enough (though not good enough for you as you see grey tiles), until you pan and the whole tiles are recomputed - more specifically those with the "approximated" status - at that time the tile callback have been triggered and the bitmaps are correctly loaded.

Does that make sense? (it's still a bug, though)

**Comment by apacha** [comment]
That sounds very much like the problem. Do you have any idea how to work around this issue?

**Comment by monsieurtanuki** [comment]
@apacha Regardless of the "callback" potential side-effect, I think there's something flawed in your code: in your provider list you only put the MapTileApproximater.
You should put your "async provider" first (`mapProvider`), then the approximater (which has only one provider, the "async" one) as a fallback.
Can please you try that?

**Comment by apacha** [comment]
Wow - you were right. It definitely improved the situation a lot once I use 

    // Add the regular provider as first provider, which should be queried first
    providerList.add(mapProvider);
    // Only if that provider does no longer have any tiles, it should fall back to the approximater
    providerList.add(approximater);

I still sometimes get gray tiles on higher zoom-levels, where only the approximater is available, but the effect is much less severe. Thanks for the tipp.

**Comment by monsieurtanuki** [comment]
@apacha Cool! Feel free to close the issue, assuming that what you experience with your app matches the way the approximater is supposed to work: the approximations are computed from lower levels only.

**Comment by apacha** [comment]
Unfortunately I ran into the next problem: I have multiple tile files and currently adding an approximator to all of them, which results in this behavior if I have an area where they potentially overlap:

![ezgif-1-0b2e3b57113e](https://user-images.githubusercontent.com/594497/65701803-37ea8f00-e082-11e9-9ba5-629101187184.gif)

Any idea how to resolve this conflict between the two tile providers, other than only approximating one of them? Because I have no idea why they are constantly overriding each other.

**Comment by monsieurtanuki** [comment]
I'm not sure what you set up looks like, but here are some thoughts:
* use only one Approximater
* for the Approximater, you may not need all the providers

N providers and 1 Approximater (with N or less providers)

**Comment by apacha** [comment]
You're a genius! Thanks to you I figured out the way how you can add multiple providers to a single approximater. Now it stopped blinking.
