### ISSUE TITLE
Cant load custom Tiles

### ISSUE THREAD

**Issue by oalfreda** [osmdroid/osmdroid#1399]
Please note: issues related to or caused by osmbonuspack will be closed with a
suggestion to open an issue at https://github.com/MKergall/osmbonuspack

(feel free to delete whatever doesn't apply)

## Issue Type

[x] Question
[ ] Bug
[ ] Improvement
[ ] Build system related
[ ] Performance
[ ] Documentation

## Description and/or steps/code to reproduce the problem
I managed to load the predefined Tiles like Mapnik or OpenTopo but i want to load the StamenWatercolour Tiles. The Stamen tile follow this pattern http://c.tile.stamen.com/watercolor/#Zoom/X/Y and i try loading them using this code

```
OnlineTileSourceBase sta= new XYTileSource("StamenMap", 1, 17, 256, ".jpg",
                new String[]{

                        "http://c.tile.stamen.com/watercolor/"
                        },
                "asdf");
        map.setTileSource(sta);
```
following an exmaple on this site https://github.com/osmdroid/osmdroid/wiki/Map-Sources.
But The Tiles all load blank when the app runs.

### If it's a bug, version(s) of android this affects:

All

### Version of osmdroid the issue relates to:

6.0.2

**Comment by monsieurtanuki** [comment]
Probably related to #1290 as your tiles come from http, not httpS.
I guess you can read @InI4's comments regarding `network_security_config.xml` in #1287, or have a look at #1291.

@oalfreda Does that make sense?

**Comment by oalfreda** [comment]
Yup, i followed the instructions and now it works flawlessly.
Thank you!
