### ISSUE TITLE
Touching Polyline hard to trigger

### ISSUE THREAD

**Issue by pasniak** [osmdroid/osmdroid#1400]
## Issue Type

[x] Question

## Description and/or steps/code to reproduce the problem

I have a general touch handling overlay + quite few overlays on my layer which are circle polylines (thin for there are many of them). The polylines have infowindows attached but they are annoyingly hard to trigger with touch on my high resolution tablets.  I need to touch many times to hit the thin lines.  Is there a way to improve sensitivity?  

I looked briefly at Polyline code: it depends screen density but the sensitivity seem closed for modifications.  

### If it's a bug, version(s) of android this affects:

All

### Version of osmdroid the issue relates to:

6.1.0

**Comment by monsieurtanuki** [comment]
@pasniak You're right, we should be able to change the touch sensitivity for `Polyline`s (cf. https://github.com/osmdroid/osmdroid/blob/master/osmdroid-android/src/main/java/org/osmdroid/views/overlay/Polyline.java#L220 I guess)
Feel free to send a pull request.

**Comment by pasniak** [comment]
PR created
