### ISSUE TITLE
I want to show text on polygon is there any direct method to show that?

### ISSUE THREAD

**Issue by mehulpxm** [osmdroid/osmdroid#1401]
Please note: issues related to or caused by osmbonuspack will be closed with a
suggestion to open an issue at https://github.com/MKergall/osmbonuspack

(feel free to delete whatever doesn't apply)

## Issue Type

Question

### If it's a bug, version(s) of android this affects:

All

### Version of osmdroid the issue relates to:

6.0.2

**Comment by monsieurtanuki** [comment]
I think it's possible to draw a texr on a Path. Can you try that?
Then the question is: how to get the Path of a Polygon?

**Comment by mehulpxm** [comment]
can you explain to me more in that?

**Comment by monsieurtanuki** [comment]
Oh, it's more like Milestones then, something like "I want to display something at every vertex / every n meters".
There are demos in the demo app, like "10k race in Paris", and there's a dedicated entry in the wiki too.
That's all I can do right now, with no access to my computer.
Tell me if that would suit your needs.

**Comment by spyhunter99** [comment]
there are a few examples for creating a text label at any lat lon and styling . see the marker class...
https://github.com/osmdroid/osmdroid/blob/master/OpenStreetMapViewer/src/main/java/org/osmdroid/samplefragments/milstd2525/MilStdMultipointOverlay.java#L239

**Comment by mehulpxm** [comment]
Hello @spyhunter99, your answer is much appreciated. but how can I give only one geopoint in the marker? because polygon has coordinate geopoints which draws polygon. so how can I find the center point from the polygon coordinates?

**Comment by monsieurtanuki** [comment]
@mehulpxm I think that once you used `setPoints`, `getInfoWindowLocation` will return the "center" of the `Polygon`.

**Comment by mehulpxm** [comment]
@monsieurtanuki  that's a polygon and i want to show the text on that it's not on the based on every meters or vertex.

**Comment by monsieurtanuki** [comment]
@mehulpxm Have you tried `getInfoWindowLocation`?

**Comment by mehulpxm** [comment]
@monsieurtanuki  no. let me check and revert you.

**Comment by mehulpxm** [comment]
![Screenshot_1569564604](https://user-images.githubusercontent.com/35398127/65746190-c6f7b580-e11b-11e9-816f-5b38c1416924.png)
it shows default icon istead of text.

**Comment by mehulpxm** [comment]
@spyhunter99 @monsieurtanuki  i got the expected result by this code .
`Marker m = new Marker(mapView);
m.setTextLabelBackgroundColor(Color.TRANSPARENT);
m.setTextLabelForegroundColor(backgroundColor);
m.setTextIcon("Hello");
m.setPosition(p.getInfoWindowLocation());
mapView.getOverlayManager().add(m);
mapView.invalidate();`
Thank you so much for your quick suggestion. saved my time a lot.
