### ISSUE TITLE
Regroup overlapping marker under one marker

### ISSUE THREAD

**Issue by Tvax** [osmdroid/osmdroid#1405]
## Issue Type

[ ] Question
[ ] Bug
[x] Improvement
[ ] Build system related
[x] Performance
[ ] Documentation

## Description and/or steps/code to reproduce the problem
If markers overlap each other hide them and create a unique marker that display the amount of markers being hidden. Refresh every time the zoom value change.

**Comment by monsieurtanuki** [comment]
I think it's in https://github.com/MKergall/osmbonuspack

**Comment by Tvax** [comment]
Indeed I just found out that there is this feature. But you have to do it manually. A tool that detects and regroup overlapping markers automatically is still needed.

**Comment by MKergall** [comment]
https://github.com/MKergall/osmbonuspack/wiki/Tutorial_3

**Comment by Tvax** [comment]
OK cool didn't find this one thank you !

**Comment by monsieurtanuki** [comment]
Seems fixed, then.
@Tvax Feel free to reopen if necessary or to create a new issue.
