### ISSUE TITLE
Improvement suggestion: Implement setPadding for CustomZoomButtonsDisplay

### ISSUE THREAD

**Issue by wharnisch** [osmdroid/osmdroid#1412]
Please note: issues related to or caused by osmbonuspack will be closed with a
suggestion to open an issue at https://github.com/MKergall/osmbonuspack

(feel free to delete whatever doesn't apply)

## Issue Type

[ ] Question
[ ] Bug
[x ] Improvement
[ ] Build system related
[ ] Performance
[ ] Documentation

## Description and/or steps/code to reproduce the problem

Many modern devices have 'notches' so normally you see margins at the edges of display so that an activity does not draw over the notches. If an activity draws a map it is very user friendly to use the whole display without margins. But one has to ensure that controls like zoom buttons are not drawn over notches, so you have to specify a padding area.

In class CustomZoomButtonsDisplay a method 'setMarginPadding' exists, but this method only supports to set a margins as fractions of the bitmap size and a padding as afractions of the bitmap size. From Android you get padding as 4 different padding values in pixels units (left, top, right, bottom). With 'setMarginPadding' you cannot specify 4 different values but only one value and specification of this value is inconvenient cause you have to convert pixels to fractions of bitmap size.

So I suggest to add a new method 'setPadding(int left, int top, int right, int bottom)' to class 'CustomZoomButtonsDisplay' with left, top, right, bottom in pixel units. These values should be added to those calculated by the existing 'setMarginPadding' method.

### If it's a bug, version(s) of android this affects:

No bug, improvement suggestion

### Version of osmdroid the issue relates to:

6.1.2

**Comment by spyhunter99** [comment]
sounds like a reasonable idea, want to do a pr for it?

**Comment by wharnisch** [comment]
Yes, I would I like very much contributing to this project and do a pull request for it. For this I have to fork the project, correct?

**Comment by monsieurtanuki** [comment]
@wharnisch I wish I could help you, github-wise, but I'm definitely not the good teacher for that.

My assumptions:
* go to https://github.com/osmdroid/osmdroid and click on the green button on the right "Clone or download"
* open Android Studio
* open the local project
* create a new branch called "feature/#1412" (from the bottom right "Git: master" label)
* code whatever you want to code
* when you're ready, commit and push
* that should be more or less like that

Good luck ;)

**Comment by wharnisch** [comment]
- Downloaded the project
- Opened the project locally
- Ready with implementing the improvement
- But: Cannot create the new branch - missing permissions?

**Comment by monsieurtanuki** [comment]
I assume you have to code on your own copy of osmdroid (something like wharnisch/osmdroid).
Then you can create a branch and code, and when you feel ready in the pull request process your branch will be added to osmdroid/osmdroid.
You cannot write directly on osmdroid/osmdroid.
Or something like that...
Good luck!

**Comment by wharnisch** [comment]
Thanks for your help!
Seems like it worked.
Regards

**Comment by monsieurtanuki** [comment]
Coded in #1426
