### ISSUE TITLE
TileSourceFactory for HikeBikeMap: IOException on Android 9

### ISSUE THREAD

**Issue by sgelb** [osmdroid/osmdroid#1413]
## Issue Type

[x] Bug

## Description and/or steps/code to reproduce the problem

Since Android 9, cleartext network connections are disabled by default and throw an IOException. The tile server url for HikeBikeMap in [TileSourceFactory](https://github.com/osmdroid/osmdroid/blob/74db8f3f603f33b54b4c4e8df71cc9be986c6599/osmdroid-android/src/main/java/org/osmdroid/tileprovider/tilesource/TileSourceFactory.java#L151) is still using the http scheme. This can be updated to https to fix this error.

### If it's a bug, version(s) of android this affects:

Android 9 and higher

### Version of osmdroid the issue relates to:

6.1.2

**Comment by spyhunter99** [comment]
thanks
