### ISSUE TITLE
AnimateTo doesn't always work on startup on Samsung devices

### ISSUE THREAD

**Issue by spyhunter99** [osmdroid/osmdroid#142]
I have an osmdroid map that stores the current zoom and lat/lon on pause and restores it onresume using animateTo. On Samsung devices, this simply does nothing. SetCenter works just fine however. As a work around, I detect the device type, then call the appropriate setting based on the device at app start up. Just figured I'd raise the issue here. Looking at the code, it looks like it could be a problem with the mReplayController or mMapView.isLayoutOccurred().

**Comment by spyhunter99** [comment]
https://github.com/osmdroid/osmdroid/pull/143 this may be related

**Comment by k3b** [comment]
@spyhunter99 have you tried to encapsulate MapView.setMapCenter() and MapView.setZoomLevel() the same was as #142? does this solve your issue?

**Comment by k3b** [comment]
Have you tried to the initial position (zoom, center, BoundingBoxE6) in

MapView.addOnFirstLayoutListener(new OnFirstLayoutListener() { ...});

**Comment by spyhunter99** [comment]
I have not, didn't even notice that it existed. The workaround that I'm currently using is to check the device manufacturer, then call a setCenter instead of animateTo on start up
