### ISSUE TITLE
Map dont show

### ISSUE THREAD

**Issue by CarrizoME** [osmdroid/osmdroid#1422]
Hi! Dont speak english good,sorry.

I follow the guide, but the map dont show.
I dont put the line "Configuration.getInstance()......" , because dont compile , not recognize the metod ".getINstance". 

## Issue Type

[x] Question
[x] Bug
[ ] Improvement
[ ] Build system related
[ ] Performance
[ ] Documentation

## Description and/or steps/code to reproduce the problem

-----------------------------------------------------------------------------
dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'androidx.appcompat:appcompat:1.1.0'
    implementation 'androidx.constraintlayout:constraintlayout:1.1.3'
    testImplementation 'junit:junit:4.12'

    implementation 'org.osmdroid:osmdroid-android:6.1.2'
    implementation 'org.osmdroid:osmdroid-wms:6.1.2'
    implementation 'org.osmdroid:osmdroid-mapsforge:6.1.2'

    androidTestImplementation 'androidx.test:runner:1.2.0'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.2.0'
}
----------------------------------------------------------------
public class MainActivity extends AppCompatActivity {

    MapView map =null;

    @Override
    protected void onCreate(Bundle savedInstanceState) {

        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        Context ctx = getApplicationContext();
        
        setContentView(R.layout.activity_main);

        map = (MapView) findViewById(R.id.map);
        map.setTileSource(TileSourceFactory.MAPNIK);

        map.setBuiltInZoomControls(true);
        map.setMultiTouchControls(true);

        IMapController mapController = map.getController();
        mapController.setZoom(9.5);
        GeoPoint startPoint = new GeoPoint(48.8583, 2.2944);
        mapController.setCenter(startPoint);

    }
----------------------------------------------------------------------------------
![WhatsApp Image 2019-10-10 at 18 43 28](https://user-images.githubusercontent.com/55456387/66608878-f089f580-eb8d-11e9-8f84-f39ed9127362.jpeg)
![WhatsApp Image 2019-10-10 at 18 43 28](https://user-images.githubusercontent.com/55456387/66608894-fa135d80-eb8d-11e9-8d60-0baee0d41084.jpeg)
![WhatsApp Image 2019-10-10 at 18 43 28](https://user-images.githubusercontent.com/55456387/66608903-00093e80-eb8e-11e9-9f5c-fe8e16f7f160.jpeg)

## Environment

Android Studio

### If it's a bug, version(s) of android this affects:

All

### Version of osmdroid the issue relates to:

6.1.2

**Comment by franciscojoliva** [comment]
Hi! It looks like you forgot to include ` Configuration.getInstance().load(applicationContext,
            PreferenceManager.getDefaultSharedPreferences(applicationContext))` before the setContentVIew in the onCreate of the activity.

You can see an example [here](https://github.com/osmdroid/osmdroid/wiki/How-to-use-the-osmdroid-library) 

Hope it helped!

**Comment by CarrizoME** [comment]
Thanks, Android Studio  not import "org.osmdroid.config.Configuration" then dont recognize the line "Configuration.getInstace...". I can fixed import that library manually .
