### ISSUE TITLE
Offline map&Online map

### ISSUE THREAD

**Issue by Glenn1Wang** [osmdroid/osmdroid#1423]
Can i view the online map at the same time when using an offline map file?

**Comment by monsieurtanuki** [comment]
You can use several providers, some being online, some being offline (like a local zip file).
They will all be used; on a given z/x/y the resulting tile will depend on who's first to provide the tile.
Does that answer your question?

**Comment by Glenn1Wang** [comment]
> You can use several providers, some being online, some being offline (like a local zip file).
> They will all be used; on a given z/x/y the resulting tile will depend on who's first to provide the tile.
> Does that answer your question?

Thank you very much！That solved my problem.
