### ISSUE TITLE
Scale of marker

### ISSUE THREAD

**Issue by liuzy1993** [osmdroid/osmdroid#1425]
When I use the marker to display the image, when I zoom the map, the size of the image does not change. I need the image to change as the map zooms. How should I solve it ?

**Comment by spyhunter99** [comment]
you can override the draw method of marker and do your own thing

you can also add a map events listener and set the image on the marker in question to a specific prerendered size based on zoom levels

**Comment by spyhunter99** [comment]
reopen if there are more questions
