### ISSUE TITLE
How to make the interface display only one map.

### ISSUE THREAD

**Issue by WangXianSong** [osmdroid/osmdroid#1431]
I don't want the interface to be able to slide indefinitely, how do I call the API so that the interface is fixed within a map.

## Issue Type

[√ ] Question
[ ] Bug
[ ] Improvement
[ ] Build system related
[ ] Performance
[ ] Documentation

## Description and/or steps/code to reproduce the problem
Just after loading the online tile map

### If it's a bug, version(s) of android this affects:

Android 6.0

### Version of osmdroid the issue relates to:

6.1.2

**Comment by InI4** [comment]
Did you try handling all touch events to the view in your app? 
That should prevent them to migrate to the map and avoid panning and zooming.

**Comment by WangXianSong** [comment]
> Did you try handling all touch events to the view in your app?
> That should prevent them to migrate to the map and avoid panning and zooming.

Thank you for your reply. Using touch events to limit user actions is a good idea, but I need to mark a lot of points on the map. Although the user can't see the other areas, I am still worried about the resource consumption.

I'm going to check how the map View in the source code repeats multiple maps, and then make the View display only one map.

**Comment by monsieurtanuki** [comment]
@WangXianSong Another solution could be to use `MapView.setScrollableAreaLimitLatitude` and `setScrollableAreaLimitLongitude`.
But I'm not sure what you mean with "display one map": perhaps `MapView.setHorizontalMapRepetitionEnabled` and `setVerticalMapRepetitionEnabled` would help, too.

**Comment by WangXianSong** [comment]
> @WangXianSong Another solution could be to use `MapView.setScrollableAreaLimitLatitude` and `setScrollableAreaLimitLongitude`.
> But I'm not sure what you mean with "display one map": perhaps `MapView.setHorizontalMapRepetitionEnabled` and `setVerticalMapRepetitionEnabled` would help, too.

Thank you for your reply. I mean, just `a world map` with boundaries.

I will check the class you mentioned, thank you very much.
