### ISSUE TITLE
我想把所有的polyLine放在marker的下面应该怎样做啊

### ISSUE THREAD

**Issue by zhujiang521** [osmdroid/osmdroid#1433]
我想把所有的polyLine放在marker的下面，但是我在OverlayWithIW没有找到关于地图层级的概念，我该怎样做？

**Comment by spyhunter99** [comment]
hmm google translates this to
    I want to put all the polyLines under the marker, but I didn't find the concept of map hierarchy in OverlayWithIW, what should I do?

not sure if you mean Z indexing, but basically, data is drawn on screen in the order they are added to the map. You can always either reorder the layers yourself, or override the default overlay manager if your own logic
