### ISSUE TITLE
Show the zoom value next to the scaleBarOverlay 

### ISSUE THREAD

**Issue by Conan42** [osmdroid/osmdroid#1434]
Please note: issues related to or caused by osmbonuspack will be closed with a
suggestion to open an issue at https://github.com/MKergall/osmbonuspack

(feel free to delete whatever doesn't apply)

## Issue Type

[* ] Question
[ ] Bug
[ ] Improvement
[ ] Build system related
[ ] Performance
[ ] Documentation

## Description and/or steps/code to reproduce the problem
Hi,

I would like to display the zoom value next to the scale bar, how can we do that, please?

Regards

Michel Guenin

### If it's a bug, version(s) of android this affects:

All

### Version of osmdroid the issue relates to:

6.1.2

**Comment by monsieurtanuki** [comment]
@Conan42 What do you mean with "zoom value"? Something like an integer from 0 to 19? A float?

**Comment by Conan42** [comment]
a floating "x12.5" for example next to the scale bar

**Comment by mat8854** [comment]
It is not supported out of the box. You can add a positioned TextView over the MapView in your XML layout.

Register a `MapListener` to read out the zoom level after each zoom event. You should use the `DelayedMapListener` version with a small delay for performance reasons (in the sample code below 100ms).

Kotlin sample code:
```
        map.addMapListener(DelayedMapListener(object : MapListener {
            override fun onScroll(event: ScrollEvent): Boolean {
                // handle scroll event
                return false
            }

            override fun onZoom(event: ZoomEvent): Boolean {
                // handle zoom event
                // update textview
                val df = DecimalFormat("##.#")
                txtZoomLevel.text = "x" + df.format(event.zoomLevel)
                return false
            }
        }, 100))
```

**Comment by spyhunter99** [comment]
looks like this is answered, reopen if there are further questions
