### ISSUE TITLE
Why the small zoom?

### ISSUE THREAD

**Issue by s-ilnar** [osmdroid/osmdroid#1435]
Please note: issues related to or caused by osmbonuspack will be closed with a
suggestion to open an issue at https://github.com/MKergall/osmbonuspack

(feel free to delete whatever doesn't apply)

## Issue Type

[x ] Question
[ ] Bug
[ ] Improvement
[ ] Build system related
[ ] Performance
[ ] Documentation

### If it's a bug, version(s) of android this affects:

All

### Version of osmdroid the issue relates to:

6.1.2

Hello! I am using "lite" mode OSMDroid https://github.com/osmdroid/osmdroid/issues/990#issuecomment-551425190 
Is this a normal result or am I doing something wrong? Why is the level of zoom low?

my code:
```
private final List<Overlay> mOverlays;
private final TileSystem mTileSystem = new TileSystemWebMercator();
final MapTileProviderBase mapTileProvider;

this.mOverlays = new ArrayList<>();
this.mapTileProvider = new MapTileProviderBasic(context);

final DisplayMetrics displayMetrics = getActivity().getResources().getDisplayMetrics();
int mapWidth = displayMetrics.widthPixels;
int height = (int) TypedValue.applyDimension(TypedValue.COMPLEX_UNIT_DIP, 150, getResources().getDisplayMetrics());


ScaleBarOverlay mScaleBarOverlay = new ScaleBarOverlay(context, mapWidth, mapHeight);
mScaleBarOverlay.setCentred(true);
mScaleBarOverlay.setScaleBarOffset(mapWidth / 2, 10);
this.mOverlays.add(mScaleBarOverlay);

private void download() {
	Marker marker = new Marker(new MapView(App.getAppContext()));
	marker.setPosition(new GeoPoint(55.724668, 52.444936));
	BoundingBox boundingBox = marker.getBounds();
        //OR  BoundingBox boundingBox = new BoundingBox(marker.getPosition().getLatitude(), 
        // marker.getPosition().getLongitude(), marker.getPosition().getLatitude(), 
         // marker.getPosition().getLongitude());

	mOverlays.add(marker);

	final double zoom = mTileSystem.getBoundingBoxZoom(boundingBox, mapWidth, mapHeight);
	final MapSnapshot mapSnapshot = new MapSnapshot(new MapSnapshot.MapSnapshotable() {
		@Override
		public void callback(final MapSnapshot pMapSnapshot) {
			if (pMapSnapshot.getStatus() != MapSnapshot.Status.CANVAS_OK) {
				return;
			}
			bitmap = Bitmap.createBitmap(pMapSnapshot.getBitmap());

			recyclerView.post(new Runnable() {
				@Override
				public void run() {
					notifyDataSetChanged();
				}
			});
		}
	}, MapSnapshot.INCLUDE_FLAG_UPTODATE, mapTileProvider, mOverlays,
			new Projection(zoom, mapWidth, mapHeight, boundingBox.getCenterWithDateLine(), 0, true, true, 0, 0));
   // mMapSnapshots.put(key, mapSnapshot);
	new Thread(mapSnapshot).start(); // TODO use AsyncTask, Executors instead?
}

<androidx.appcompat.widget.AppCompatImageView
	android:id="@+id/mapImage"
	android:layout_width="match_parent"
	android:layout_height="150dp"
	app:layout_constraintEnd_toEndOf="parent"
	app:layout_constraintStart_toStartOf="parent"
	app:layout_constraintTop_toTopOf="parent" />
```

p.s. If I enter zoom = 15, then ANR

result  (small zoom and camera not center)
<a href="https://ibb.co/5xNj0fs"><img src="https://i.ibb.co/5xNj0fs/7c69149f-3e49-46fb-84ec-397dbfa1567f.jpg" alt="7c69149f-3e49-46fb-84ec-397dbfa1567f" border="0"></a>

**Comment by monsieurtanuki** [comment]
@s-ilnar I cannot investigate very far.
That being said, I don't know what is the expected result for the bounding box _of a single marker_, and more specifically the resulting computed zoom.
My suggestions:
* try with a zoom that you compute yourself
* add a marker and get the bounds from the list of those 2 markers
* try from the demo, then progressively change your code in order to fit your initial needs

**Comment by s-ilnar** [comment]
Hello. 
guys, maybe someone already used MapSnapshot? Did you get the result? I can not understand my mistake :(

Maybe you can help me figure it out?
I uploaded a test project in [git ](https://github.com/s-ilnar/Osm-Test).
The result is not returned to the callback method.
