### ISSUE TITLE
Show markers from certain zoom level

### ISSUE THREAD

**Issue by mlendl** [osmdroid/osmdroid#1439]
I would like to show some marker overlays only on certain (higher) zoom level. Is it possible actually? 

[X] Question
[X] Improvement

### If it's a bug, version(s) of android this affects:

All

### Version of osmdroid the issue relates to:

6.1.2

**Comment by mat8854** [comment]
Keep a list of your added markers (with zoom level limit for each) and use the same construct to listen to zoom events as here: https://github.com/osmdroid/osmdroid/issues/1434#issuecomment-554359611 .

Enabling / disabling should work with:
```
var state: Boolean = false
marker.setEnabled(state)
marker.setVisible(state)
```

**Comment by spyhunter99** [comment]
looks like this is answered, reopen if there are further questions

**Comment by mlendl** [comment]
no thanks, works good
