### ISSUE TITLE
Critical Bug: Missing tiles in offline mode

### ISSUE THREAD

**Issue by babobka** [osmdroid/osmdroid#144]
I've got an app that uses osmdroid 4.3. The only mode I use is offline. Sometimes my app can not render few tiles. Seems like missing tiles. If I zoom in or zoom out, new tiles will be missed. I was following to osmdroid FAQ and I disabled hardware acceleration for map activity, but nothing good happens. Tiles are still missing. What do?

**Comment by spyhunter99** [comment]
i've noticed this issue too in offline mode. maybe someone can run a quick build with the debug flag on to see what going on. What tile source are you using? Zip? Sqlite?

**Comment by babobka** [comment]
Zip

**Comment by babobka** [comment]
If I remove tile folder and download map again, everything will be fine.

**Comment by babobka** [comment]
I know it's hard to fix. But how can I avoid that? Do you have a hack for this?

**Comment by spyhunter99** [comment]
Remove which folder? the /sdcard/osmdroid/tiles?

**Comment by babobka** [comment]
Yup. By the way, is there any method to determine the number of cached tiles? I think I can make a little fix.

**Comment by spyhunter99** [comment]
A fast way? not that I know of. Open the folder list the files and get length, recursively

**Comment by babobka** [comment]
I was thinking osmdroid stores in cache tiles that can be seen on the screen and clearTileCache() clears those tiles. Isn't it? Because,  clearTileCache doesn't remove png files from tile folders.

**Comment by spyhunter99** [comment]
I think clear tile cache clears the in memory cache, not the disk cache

**Comment by babobka** [comment]
That's what I am talking about. How can I get the number of tiles cached in memory?

**Comment by spyhunter99** [comment]
https://github.com/osmdroid/osmdroid/blob/master/osmdroid-android/src/main/java/org/osmdroid/tileprovider/MapTileProviderBase.java

You'd have to alter this class to get access to it,  not directly available at the moment (that I know of)

**Comment by babobka** [comment]
If bug is cache-related, what if I just disable memory caching? Can I do that?

**Comment by spyhunter99** [comment]
Give it a try

**Comment by spyhunter99** [comment]
@babobka any luck?

**Comment by babobka** [comment]
Nope. I moved to mapsforge.

**Comment by spyhunter99** [comment]
well, if you have time, try to recreate the problem with an sqlite db. i think the issue is zip specific

**Comment by spyhunter99** [comment]
any luck?

**Comment by cfsbhawkins** [comment]
We use offline tiles too and see this issue, with both hardware acceleration on and off, let me do some testing and see what I can do. I have noticed sqlite or mbtiles are better but the issue still exists. I will enable debug mode and see if I can see anything.

**Comment by spyhunter99** [comment]
need reproducible instructions. if we can't reliably reproduce the issue, then we can't fix it

**Comment by cfsbhawkins** [comment]
I can confirm using the latest 5.0 SNAPSHOT that using SQLLite files the missing tiles is gone.

**Comment by spyhunter99** [comment]
Meaning there are tiles missing? or that there are no longer tiles missing?

**Comment by cfsbhawkins** [comment]
This is no longer an issue.

**Comment by spyhunter99** [comment]
cool! thanks for looking at it
