### ISSUE TITLE
Draw Map

### ISSUE THREAD

**Issue by liuzy1993** [osmdroid/osmdroid#1442]
If I want to do some custom drawing operations on the map, such as encircling a school with red lines, how can I do it?

**Comment by InI4** [comment]
As I have done it:
You can draw whatever you want in a custom overlay. 
https://github.com/osmdroid/osmdroid/wiki/Making-Custom-Overlays

**Comment by liuzy1993** [comment]
Is there any difference between the effect and my own screenshot? Can you zoom in and out while drawing? Or how do you move the map?

**Comment by InI4** [comment]
An overlay is just over the Map, it can but don't has to take user interaction (i.e. touches), if it doesn't take them, they are forwarded to the map, so zoom gestures etc. work smoothly. But without more details the rest is speculation.

**Comment by spyhunter99** [comment]
there's a number of samples that do exactly this...

**Comment by spyhunter99** [comment]
map data is plotted, not painted as a static screen shot. you can zoom and pan etc and the drawings will always be rendered based on the data. see the various examples for drawing using the same app. The milstd2525 sample does a bunch of stuff that may be of interest, as well as the basic drawing examples.
