### ISSUE TITLE
I can auto-rotate the map using maps API OsmDroid?

### ISSUE THREAD

**Issue by s-ilnar** [osmdroid/osmdroid#1443]
Please note: issues related to or caused by osmbonuspack will be closed with a
suggestion to open an issue at https://github.com/MKergall/osmbonuspack

(feel free to delete whatever doesn't apply)

## Issue Type

[x ] Question
[ ] Bug
[ ] Improvement
[ ] Build system related
[ ] Performance
[ ] Documentation

### If it's a bug, version(s) of android this affects:

All

### Version of osmdroid the issue relates to:

6.1.2

A similar [query ](https://stackoverflow.com/questions/14320015/android-maps-auto-rotate/32232563)with google map.

Does anyone know how I can auto-rotate the map using maps API OsmDroid just like the google maps app does? Will I have to implement this functionality myself or is it in the API and i'm just not seeing it? I appreciate all help.

**Comment by spyhunter99** [comment]
I think there is a thing in the sample app for this already

**Comment by s-ilnar** [comment]
@spyhunter99  https://github.com/osmdroid/osmdroid/blob/master/OpenStreetMapViewer/src/main/java/org/osmdroid/samplefragments/location/SampleHeadingCompassUp.java Did I find it right?

**Comment by spyhunter99** [comment]
yes that is what i was referring to. does that meet your needs?

**Comment by mat8854** [comment]
@s-ilnar The feature you want is called "course-up" in navigation.

https://github.com/osmdroid/osmdroid/blob/master/OpenStreetMapViewer/src/main/java/org/osmdroid/samplefragments/location/SampleHeadingCompassUp.java implements it.

**Comment by s-ilnar** [comment]
There is no compass on the target devices. This example will not work without a compass?

```
PackageManager pm = getPackageManager();
if (!pm.hasSystemFeature(PackageManager.FEATURE_SENSOR_COMPASS)) {
    // This device does not have a compass, turn off the compass feature
}
```

**Comment by spyhunter99** [comment]
It should use GPS heading without a compass

**Comment by spyhunter99** [comment]
looks like this is answered, reopen if there are further questions
