### ISSUE TITLE
Documentation update for Fragment setup code

### ISSUE THREAD

**Issue by mat8854** [osmdroid/osmdroid#1449]
## Issue Type
[ X] Documentation

## Description and/or steps/code to reproduce the problem
I suggest a FAQ section update for best practices for map setup code in Fragments as I wrote in https://github.com/osmdroid/osmdroid/issues/1438#issuecomment-555174418 and here https://github.com/osmdroid/osmdroid/issues/1438#issuecomment-556826827 .

**Comment by mat8854** [comment]
Changes for updated Wiki section below:

At this stage of the lifecycle, the `MapView` is not 100% initialized yet; it may not even have a width or a height. The correct way is to use the `View.post` syntax.

### For Activities
````java
@Override
public void onCreate(Bundle savedInstanceState) {
	super.onCreate(savedInstanceState);

// ...
	mMapView = (MapView) findViewById(R.id.map);

	mMapView.post(
		new Runnable() {
			@Override
			public void run() {
				mMapView.zoomToBoundingBox(new BoundingBox(48, -2, 46, 5), false);
			}
		}
	);
}
````

### For Fragments
For Fragments you should put your own map manipulation code into the function `onViewCreated()`.

````java
@Override
public View onCreateView(LayoutInflater inflater, ViewGroup parent, Bundle savedInstanceState) {
    // just the inflate code
    return inflater.inflate(R.layout.your_fragment, parent, false);
}

@Override
public void onViewCreated(View view, Bundle savedInstanceState) {
    // put your own code here
    mMapView = (MapView) getActivity().findViewById(R.id.map);
    mMapView.post(
            new Runnable() {
                @Override
                public void run() {
                    mMapView.zoomToBoundingBox(new BoundingBox(48, -2, 46, 5), false);
                }
            }
    );
}
````

**Comment by spyhunter99** [comment]
i think everyone has wiki write access, feel free to paste in your changes

**Comment by mat8854** [comment]
It is updated now.

**Comment by spyhunter99** [comment]
cool, thanks
