### ISSUE TITLE
Resource not found: marker_default.png

### ISSUE THREAD

**Issue by babakmahmoudabadi** [osmdroid/osmdroid#145]
I have created a simple project using osmdroid. I want to show a specefic point on the map. I am using the following libraries in the project:
1. osmdroid-android-4.3.jar
2. slf4j-android-1.5.8.jar
Here is my code:

@Override
public void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    setContentView(R.layout.main);

    final MapView map = (MapView) findViewById(R.id.map);

    anotherOverlayItemArray = new ArrayList<OverlayItem>();

    anotherOverlayItemArray.add(new OverlayItem(
            "US", "US", new GeoPoint(38.883333, -77.016667)));

    ItemizedIconOverlay<OverlayItem> anotherItemizedIconOverlay = new ItemizedIconOverlay<OverlayItem>(
            this, anotherOverlayItemArray, null);
    map.getOverlays().add(anotherItemizedIconOverlay);
   }

I am getting the following error:
E/AndroidRuntime(4844): Caused by: java.lang.IllegalArgumentException: Resource not found: marker_default.png

Where am I going wrong?

**Comment by spyhunter99** [comment]
Essentially, you either have to provide a marker yourself, or grab the default markers from osmdroid and include them in your project. Osmdroid should be distributed as an AAR, but for whatever reason, it's a jar file, which excludes things like the default marker.

**Comment by neilboyd** [comment]
> for whatever reason

The reason is that osmdroid was created before the AAR format existed.
It would be nice to convert to AAR format and remove slf4j and the ResourceProxy.

**Comment by spyhunter99** [comment]
Easy enough, now that there's pretty decent android support for maven. i'll
volunteer

**Comment by babakmahmoudabadi** [comment]
I have downloaded osmdroid binary file from Maven central. 
How do I change default marker from osmdroid and include them in your project?
I use osmdroid bonus pack and the follwoing codes has same error.
please help me

@Override
    public void onCreate(Bundle savedInstanceState) {
      super.onCreate(savedInstanceState);
      setContentView(R.layout.main);

      final MapView map = (MapView) findViewById(R.id.map);

      
      GeoPoint startPoint = new GeoPoint(48.13, -1.63);    
      Marker startMarker = new Marker(map);
      startMarker.setPosition(startPoint);
      startMarker.setAnchor(Marker.ANCHOR_CENTER, Marker.ANCHOR_BOTTOM);
      map.getOverlays().add(startMarker);
    }

**Comment by spyhunter99** [comment]
You need to pull it from the osmdroid repo or supply your own marker

**Comment by spyhunter99** [comment]
there is another option, define your own version of the resource proxy and return whatever images you want

**Comment by spyhunter99** [comment]
last option, instead of attaching the jar to your project, attach the aar, which will be with the next release. The AAR will include the default icons

**Comment by babakmahmoudabadi** [comment]
I've found my problem, it was incorrect JAR file adding reference.
Thanks @spyhunter99.

**Comment by shivgy** [comment]
hi @babakmahmoudabadi  I'm getting the same problem. Please tell me how did you fixed it. What is the correct JAR file adding reference.

**Comment by babakmahmoudabadi** [comment]
@shivgy You have to create "libs" folder under root and then put all related jar files into it

**Comment by spyhunter99** [comment]
Timeout....
if you're using osmdroid < 5.x, the output is a JAR that does not include the default resources, either bring your own or borrow ours from the sample app

if you're using osmdroid >= 5.x, the output is an AAR that does include the default resources, so this shouldn't be an issue.

Read the wiki entry https://github.com/osmdroid/osmdroid/wiki right on the first page, "Include the binaries in your project:"

**Comment by shivgy** [comment]
I have kept my osmdroid-android-3.0.7.jar ; slf4j-android-1.5.8.jar and osmbonuspack_v5.1.jar in lib folder and had Build the Path and then Configured Build Path for javadoc location and source attachment. I can see the map but, could not display marker on it. it says could not find default-marker.png

**Comment by babakmahmoudabadi** [comment]
@spyhunter99  Iam using osmdroid-androdid-4.3.jar that include all default resources.
@shivgy  please note: libs Folder and you  dont neet to configure build path if you put all jar files into libs folder

**Comment by spyhunter99** [comment]
4.3 does NOT include any resources (like images, the src/main/res folder)


On Mon, Dec 14, 2015 at 7:54 AM, babakmahmoudabadi <notifications@github.com

**Comment by shivgy** [comment]
where can I get osmdroid-android-4.3.jar or the updated *.jar

**Comment by babakmahmoudabadi** [comment]
https://oss.sonatype.org/content/groups/public/org/osmdroid/osmdroid-android/4.3/

@spyhunter99 marker_default.png and other images exists in jar file  and it works :)

**Comment by djdance** [comment]
but how to use 5.1 AAR without gradle (old project)?
I've unzipped aar and extracted classes.jar, it works, but it crashes on a marker add:

***java.lang.NoClassDefFoundError: org.osmdroid.library.R$drawable***
```
        this.mOnMarkerDragListener = null;
        if(mDefaultIcon == null) {
            mDefaultIcon = resourceProxy.getResources().getDrawable(drawable.marker_default);
        }
```

**Comment by spyhunter99** [comment]
5.2 doesn't use the resource proxy any more. you may have more luck with it. what build system is it?

**Comment by djdance** [comment]
traditional old good build system (non-gradle)
looks like it wants drawables from AAR, but there is no AAR - only extracted **classes.jar**, and I copied all images from aar/res to project, but it not help: I think it misses not drawable itself but link to folder from R.. How to fix this? 

Thanks

**Comment by spyhunter99** [comment]
Probably time to upgrade. Whatever you're using for a build system, it will have to at least support AAR files.

**Comment by himagaran** [comment]
**How to add multiple markers with an array of geopoints?**
`GeoPoint startPoint = new GeoPoint(48.13, -1.63);    
  Marker startMarker = new Marker(map);
  startMarker.setPosition(startPoint);
  startMarker.setAnchor(Marker.ANCHOR_CENTER, Marker.ANCHOR_BOTTOM);
  map.getOverlays().add(startMarker);`

**Comment by spyhunter99** [comment]
A loop?
