### ISSUE TITLE
Get the coordinates of the screen center point

### ISSUE THREAD

**Issue by liuzy1993** [osmdroid/osmdroid#1451]
I want to create an icon in the middle of the screen and move the map to get its latitude and longitude on the map. How can I achieve this?

**Comment by pasniak** [comment]
`mapView.getMapCenter` will give you current "middle of the screen". Creating an "icon" is adding `Marker`, with icon: `Marker.setIcon(Drawable)`. To move the map use `mapView.controller.animateTo(pt)`

**Comment by spyhunter99** [comment]
looks like this is answered
