### ISSUE TITLE
Revise project outputs to AAR

### ISSUE THREAD

**Issue by spyhunter99** [osmdroid/osmdroid#146]
convert to AAR format
remove slf4j
remove the ResourceProxy (save this for rainy day)

**Comment by spyhunter99** [comment]
@neilboyd if you want to remove sfl4j, what do you want to use instead? or just the standard android logcat?

**Comment by neilboyd** [comment]
My idea was to use standard Android logging. I haven't thought this through, but isn't it part of the same story about using real Android resources? And using something like Robolectric?

**Comment by spyhunter99** [comment]
alright, i'm on it. i already have the aar part done and tested.

**Comment by spyhunter99** [comment]
@neilboyd i'll throw this over to you for the resource proxy stuff. this will probably be a breaking change.

**Comment by neilboyd** [comment]
@spyhunter99 I wasn't planning on working on this now.

I thought it was a relatively small change that becomes possible by using AAR format, but if you don't want to do it then you can make a new issue that I'll look at some time in the future.

**Comment by spyhunter99** [comment]
OK, we can revise this ticket to exclude the removal of the resource proxy and save it for another day
