### ISSUE TITLE
How would one go about creating a map thumbnail from features?

### ISSUE THREAD

**Issue by bmalex88** [osmdroid/osmdroid#1461]
## Issue Type

[x ] Question
[ ] Bug
[ ] Improvement
[ ] Build system related
[ ] Performance
[ ] Documentation

Hi. I am trying to get like a preview of a GPKG map from the features it contains. I am trying to use 

`Bitmap tile = featureTiles.drawTileQueryAll(1, 1, 12);

but it returns an empty thumbnail. Is there a method or combination of methods that can do this? Thanks

**Comment by monsieurtanuki** [comment]
@bmalex88 I don't know anything about GPKG maps, but for the thumbnail part you may be interested in the `MapSnapshot` feature. I hope this helps.

**Comment by spyhunter99** [comment]
you may want to ask the geopackage folks. there is a github project for raising issues
