### ISSUE TITLE
Using WeakReference for ExpandableListView variable

### ISSUE THREAD

**Issue by mat8854** [osmdroid/osmdroid#1469]
## Issue Type

[X ] Bug
[ X] Improvement

## Description and/or steps/code to reproduce the problem

Using a `WeakReference` for `ExpandableListView expListView` variable in [ SamplesMenuFragment](https://github.com/osmdroid/osmdroid/blob/master/OpenStreetMapViewer/src/main/java/org/osmdroid/samplefragments/ui/SamplesMenuFragment.java). Please see here #1463 

### If it's a bug, version(s) of android this affects:

All

### Version of osmdroid the issue relates to:

6.1.5

**Comment by monsieurtanuki** [comment]
Merged in #1470.
