### ISSUE TITLE
Zoom buttons should not zoom if touch started outside the button area

### ISSUE THREAD

**Issue by pasniak** [osmdroid/osmdroid#1471]
Issue Type

Touch behavior of Zoom buttons is a bit awkward. It would be great if they were "touch in the box" but not "slide touch into the box" to zoom. In my app, with fullscreen and soft controls when slide controls from below the always cause random zoom...

[x] Bug
[x] Improvement

## Description and/or steps/code to reproduce the problem

Touch anywhere then slide finger into zoom button area. See me moving mouse with button pressed on the emulator: ![Osmdroid 2019-12-31 18-04](https://user-images.githubusercontent.com/19778666/71636032-bd05b700-2c22-11ea-8d3d-9f6018ef8e7d.gif)

## Environment
master

### If it's a bug, version(s) of android this affects:

All

### Version of osmdroid the issue relates to:

6.1.6

Happy New Bug 2020!

**Comment by monsieurtanuki** [comment]
@pasniak I guess we can close the issue now, can't we?
