### ISSUE TITLE
accessors to SimpleFastPointOverlayOptions mSymbol and mCircleRadius

### ISSUE THREAD

**Issue by pasniak** [osmdroid/osmdroid#1472]
## Issue Type

[x] Improvement

## Description and/or steps/code to reproduce the problem

`SimpleFastPointOverlay` has protected `drawPointAt` so it is meant to be extended, but....

class `SimpleFastPointOverlayOptions` has bunch of setters of the style properties. But no getters.  This prevents nice inheritance from SimpleFastPointOverlay (I want to customize where labels are displayed in drawPointAt) - I have to hardcode instead of using mSymbol, mCircleRadius.... 

I suggest adding accessors to 
SimpleFastPointOverlay.mStyle, 
SimpleFastPointOverlayOptions.mSymbol, 
SimpleFastPointOverlayOptions.mCircleRadius.

Also mStyle is private and I have to make its copy to style my class. Given it is `private final` why not give it an accessor?

If you think it is ok, I can do changes and PR.

## Environment
master

### Version of osmdroid the issue relates to:

6.1.6

**Comment by monsieurtanuki** [comment]
@pasniak I have no objection to getters. Please send a PR.

**Comment by monsieurtanuki** [comment]
Merged in #1473
