### ISSUE TITLE
Improvement - Helper class for degree conversion

### ISSUE THREAD

**Issue by mat8854** [osmdroid/osmdroid#1481]
## Issue Type

[X ] Improvement

I would like add a small complete helper class for degree conversion. Many users have to convert back and forth between formats. I did not find any 3rd-party code in Java which covers all degree formats.

Features in short:
* Convert between DD, DDM and DMS.
* With minor format options.
* Basic argument checking (out of range).

Together with a test suite to cover all edge cases. 

Update: It is so basic it could be put int `GeoPoint` itself.

### Version of osmdroid the issue relates to:

6.1.5

**Comment by monsieurtanuki** [comment]
@mat8854 I guess that would be very similar to [AngleFormat](https://github.com/Proj4J/proj4j/blob/master/trunk/src/main/java/org/osgeo/proj4j/units/AngleFormat.java), wouldn't it?

**Comment by monsieurtanuki** [comment]
Related to #1479

**Comment by mat8854** [comment]
@monsieurtanuki Did not know that library. It is more than I wanted. I close this issue.
