### ISSUE TITLE
Slight pause when pinch zooming in and out during tile loading. Again.

### ISSUE THREAD

**Issue by sobolvb** [osmdroid/osmdroid#1488]
## Issue Type
[x] Question
[x] Performance
[x] Documentation

## Description and/or steps/code to reproduce the problem

I have exactly the same problem. Surprisingly, after so many years, the solution is still not explicitly indicated anywhere. Also, for some reason, the cache is deleted when I close the fragment. All tutorials are pretty old and no deprecated solutions are mentioned there.
Can someone tell me how to fix the pauses?

### If it's a bug, version(s) of android this affects:
9.0

### Version of osmdroid the issue relates to:
6.1.2

**Comment by sobolvb** [comment]
![photo_2020-01-21_13-05-27](https://user-images.githubusercontent.com/39006327/72779536-c9dc6000-3c4e-11ea-96a9-7722bc3c7e6b.jpg)
And also when creating the map looks like this. But just touch it (just touch, not zoom or move), how everything becomes normal

**Comment by monsieurtanuki** [comment]
@sobolvb You're right, this issue seems similar to #812.
In both cases, a large screen and many many tiles to display, which probably provokes a memory issue.
What kind of settings do you have for the tile cache - like in [MapTileProviderBasic](https://github.com/osmdroid/osmdroid/blob/master/osmdroid-android/src/main/java/org/osmdroid/tileprovider/MapTileProviderBasic.java#L113)?

**Comment by sobolvb** [comment]
> @sobolvb You're right, this issue seems similar to #812.
> In both cases, a large screen and many many tiles to display, which probably provokes a memory issue.
> What kind of settings do you have for the tile cache - like in [MapTileProviderBasic](https://github.com/osmdroid/osmdroid/blob/master/osmdroid-android/src/main/java/org/osmdroid/tileprovider/MapTileProviderBasic.java#L113)?


I apologize right away, I only work with the library for the second day and I don’t have a deep understanding of how this works. Everything I found before that was indicated as deprecated. What is "computers"? I see their mention for the first time and have not met in the wiki.

All that I tried to do for cache settings was taken from user messages and is:

```
            var computers = map!!.tileProvider.tileCache.protectedTileComputers
            // computers.clear();
            computers.add(MapTileAreaZoomComputer(-1));
            computers.add(MapTileAreaZoomComputer(1));
            computers.add(MapTileAreaBorderComputer(10));
            computers.add(MapTileAreaZoomComputer(-2));
            computers.add(MapTileAreaZoomComputer(2));
            var protect = MapTileArea(); 
            protect.set(3, 4, 7, 4, 7); // north-east side of the world in zoom
            protect.set(1, 4, 7, 4, 7); // north-east side of the world in zoom
            protect.set(2, 4, 7, 4, 7); // north-east side of the world in zoom
            protect.set(4, 4, 7, 4, 7); // north-east side of the world in zoom
            protect.set(0, 4, 7, 4, 7); // north-east side of the world in zoom
            computers.add(MapTileAreaComputer { pSource, pReuse ->
                return@MapTileAreaComputer protect
            })
```

**Comment by monsieurtanuki** [comment]
@sobolvb `getTileCache().getProtectedTileComputers()` is the list of the tile rectangles that must be kept in the cache because you know you'll probably need them soon (`MapTileAreaZoomComputer(-1)` and `MapTileAreaZoomComputer(1)` meaning the tiles that match the currently displayed tiles but at zoom-1 or zoom+1.
In first approach I would say that you are much too generous with the protected cache, and I would suggest, as a start, the same settings as in `MapTileProviderBasic`.

**Comment by sobolvb** [comment]
@monsieurtanuki ok, tomorrow i will try it.

**Comment by sobolvb** [comment]
@monsieurtanuki my final code. It only works if I have already loaded all the zoom levels. If I restart the application or even the fragment, everything blinks again when the zoom (with the Internet turned off too)


        val mySource = XYTileSource("HOT", 0, 20, 256, ".png", arrayOf("http://192.168.8.94/hot/"), "123")
        val sqlTileWriter = SqlTileWriter()
        val tileProvider = MapTileProviderBasic(activity!!.baseContext, mySource, sqlTileWriter)
        val tileOverlay = TilesOverlay(tileProvider, activity!!.baseContext)
        val mapController = map!!.controller
        mapController.setZoom(valdaySettings.scale)
        mapController.setCenter(startPoint)

        val mLocationOverlay = MyLocationNewOverlay(GpsMyLocationProvider(activity!!), map)
        mLocationOverlay.enableMyLocation()
        mLocationOverlay.enableMyLocation(GpsMyLocationProvider(activity!!))
        Configuration.getInstance().cacheMapTileOvershoot = 3090
        map!!.apply {
            overlayManager.add(tileOverlay)
            setBuiltInZoomControls(true)
            setMultiTouchControls(true)
            overlayManager.overlays().add(mLocationOverlay)
        }
        val registerReceiver = SimpleRegisterReceiver(activity!!)
        val assetsProvider = MapTileAssetsProvider(registerReceiver, activity!!.assets, mySource)
        val cacheProvider = getMapTileFileStorageProviderBase(registerReceiver, mySource, qwe)
        val archiveProvider = MapTileFileArchiveProvider(registerReceiver, mySource)
        val mapTileCache = map!!.tileProvider.tileCache
        mapTileCache.apply {
            // protected-cache-tile computers
            protectedTileComputers.add(MapTileAreaZoomComputer(-1))
            protectedTileComputers.add(MapTileAreaBorderComputer(1))
            setAutoEnsureCapacity(false)
            setStressedMemory(false)

            // pre-cache providers
            preCache.apply {
                addProvider(assetsProvider)
                addProvider(cacheProvider)
                addProvider(archiveProvider)
            }
        }`

**Comment by monsieurtanuki** [comment]
@sobolvb Please try with `setAutoEnsureCapacity(true)`

**Comment by sobolvb** [comment]
@monsieurtanuki  no changes :(

**Comment by monsieurtanuki** [comment]
@sobolvb My suggestion: try from the simplest configuration (e.g. no specific configuration for the mapview, with the standard "Mapnik" tile source I guess). Does it work? Then try each new configuration, one at a time, in order to see where it starts to bug.

**Comment by sobolvb** [comment]
I tried the light version:
```
 val mapController = map!!.controller
        val coord = (mapSettings.coordinates[0])
        val coord2 = (mapSettings.coordinates[1])
        val startPoint = GeoPoint(coord2, coord)
        mapController.setZoom(mapSettings.scale)
        mapController.setCenter(startPoint)
```

And it worked very quickly and smoothly, and most importantly without blinking. 

But when I added:
  ```
      val mySource = XYTileSource("HOT", 0, 20, 256, ".png", arrayOf(URL), "HOT")
        val tileProvider = MapTileProviderBasic(activity!!.baseContext, mySource, null)
        val tileOverlay = TilesOverlay(tileProvider, activity!!.baseContext)
        **overlayManager.add(tileOverlay)**

```
 Everything started to blink again at zoom.

And if add:
```
 val registerReceiver = SimpleRegisterReceiver(activity!!)
 val assetsProvider = MapTileAssetsProvider(registerReceiver, activity!!.assets, mySource)
 val cacheProvider = getMapTileFileStorageProviderBase(registerReceiver, mySource, null)
 val archiveProvider = MapTileFileArchiveProvider(registerReceiver, mySource)
 val mapTileCache = map!!.tileProvider.tileCache
 mapTileCache.apply {
     // protected-cache-tile computers
     protectedTileComputers.add(MapTileAreaZoomComputer(-1))
     protectedTileComputers.add(MapTileAreaBorderComputer(1))
     setAutoEnsureCapacity(true)
     setStressedMemory(false)
     // pre-cache providers
     preCache.apply {
         addProvider(assetsProvider)
         addProvider(cacheProvider)
         addProvider(archiveProvider)
     }
 }
```

I get a problem with SQL again
```
/SQLiteDatabase: Error inserting tile=[B@a604932 provider=HOT key=211256527 from {P:580;U:10467}
    android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: tiles.key, tiles.provider (code 1555 SQLITE_CONSTRAINT_PRIMARYKEY)
```

**Comment by monsieurtanuki** [comment]
@sobolvb What about a much simpler `mapView.setTileSource(...)`, from the default state (where everything works OK without blinking but with the default tiles)?
The way you code I think that you _add_ a tile overlay _on top_ of the default one, which I presume is not your goal, is it? I presume you only want your tiles.

**Comment by pasniak** [comment]
I also see weirdness  (tiles not loading until mapview touch,  not all tiles loaded) in my new custom transparent tile *overlays* (all while Javascript just works....).  I was not able to pinpoint the cause. Is there a tiled overlay test in the app?

**Comment by sobolvb** [comment]
@pasniak  try      `   tileOverlay.loadingBackgroundColor = Color.TRANSPARENT`

**Comment by sobolvb** [comment]
@monsieurtanuki 
Yes, that’s what I need. But it seems to me that this is already working, because the part of the world that is not downloaded from my server remains white. Or am I not understanding something?

**Comment by monsieurtanuki** [comment]
@sobolvb What do you need? Just your own tile source, or your tiles on top of the default tiles?

@pasniak It could be that the tile cache is at the "tile-index" level (z/x/y), which brings confusion when dealing with two unrelated tile overlays if they share the same cache. But haven't had a look at the code yet.

**Comment by monsieurtanuki** [comment]
@sobolvb Any luck with a mere `mapView.setTileSource(new XYTileSource("test", 0, 20, 256, ".png", arrayOf(URL), "test"))`?

@pasniak I had a look at the code: the tile cache is at the tile provider level (`MapTileProviderBase`), which I guess is different for each tile overlay.

**Comment by sobolvb** [comment]
> @sobolvb What about a much simpler `mapView.setTileSource(...)`, from the default state (where everything works OK without blinking but with the default tiles)?
> The way you code I think that you _add_ a tile overlay _on top_ of the default one, which I presume is not your goal, is it? I presume you only want your tiles.

@monsieurtanuki, 
Yes, I found that my tiles are added on top of the standard card, and if there is Internet access, it downloads them. But I need the card to select only one overlay - tiles from my local server. I can not find a way to remove the map by default, map.overlayManager.clear () does not help.

**Comment by monsieurtanuki** [comment]
@sobolvb I did mention `mapView.setTileSource(...)`: did you try that?

**Comment by sobolvb** [comment]
@monsieurtanuki yes, thx! Its work

**Comment by monsieurtanuki** [comment]
@sobolvb Then it looks like your issue is solved, isn't it?
@pasniak One of the first demos in the demo app (even before the "more samples" item) includes transparent additional tile overlays (around Netherlands I think). In your case, would that make sense to test it?
