### ISSUE TITLE
[Question] 6.1.6-SNAPSHOT not available

### ISSUE THREAD

**Issue by guustmc** [osmdroid/osmdroid#1492]
## Issue Type
[X ] Question

### Version of osmdroid the issue relates to:
6.1.6-SNAPSHOT

Hi,

I was wondering if it is possible to get the 6.1.6-SNAPSHOT version. It seems to be unavailable on OSS-Sonatype. 
It would be great if the library can be updated there, for the new version solves a quite annoying bug with flinging the map that I'd like to include in a release of an app.

**Comment by spyhunter99** [comment]
published 17:30 UTC 2020 feb 9, may take some time for global mirrors to be updated
