### ISSUE TITLE
OnMarkerDragListener No response

### ISSUE THREAD

**Issue by SmallWizards** [osmdroid/osmdroid#1493]
marker.setOnMarkerDragListener
Marker doesn't respond when dragging

### Version of osmdroid the issue relates to:

6.1.5

**Comment by mat8854** [comment]
@SmallWizards You mean it broke? I have a code base which uses 6.1.x (below 6..1.5) and it works.

**Comment by SmallWizards** [comment]
Hello, which version do you use? The 6.1.5 I used is really invalid. This is the code
![20200211203130](https://user-images.githubusercontent.com/23043972/74237108-b8e2b400-4d0d-11ea-8072-8891a97f1a1f.png)
@mat8854

**Comment by mat8854** [comment]
This code
```
    private fun setTestMarker(map: MapView) {
        var markerTest = Marker(map);

        markerTest.isDraggable = true
        markerTest.position = GeoPoint(54.0, 9.0)

        markerTest.setOnMarkerDragListener(object : OnMarkerDragListener {
            override fun onMarkerDrag(marker: Marker) {
                Log.d("DRAG", "onMarkerDrag()")
            }

            override fun onMarkerDragEnd(marker: Marker) {
                Log.d("DRAG", "onMarkerDragEnd()")
            }

            override fun onMarkerDragStart(marker: Marker) {
                Log.d("DRAG", "onMarkerDragStart()")
            }
        })

        map.overlayManager.add(markerTest)
    }
```

works on my system with `osmdroid 6.1.5` and lower versions too.

**Comment by SmallWizards** [comment]
OK, thank you. It's settled
