### ISSUE TITLE
Calculate polygon area

### ISSUE THREAD

**Issue by SmallWizards** [osmdroid/osmdroid#1494]
## Question

What API can you use to calculate the area of polygon?

### Version of osmdroid the issue relates to:

6.1.5

**Comment by spyhunter99** [comment]
there isn't one. for large areas, you'll need something complex to account for the curve of the earth, however for smaller areas, basic trig should be good enough. assuming the polygon doesn't 
have overlapping sectors, you can calculate the mid point, then calculate the area of triangles between every other point and its adjacent point, then add them up. there should be tons of examples on doing this. there is an api that we have for calculating distance in meters between two lat/lon points.

if you use a math formula, you'll probably have to convert lat/lon to radians first.

**Comment by SmallWizards** [comment]
OK, thank you
