### ISSUE TITLE
Question: Ground overlay feature and Inside Polygon Detection

### ISSUE THREAD

**Issue by NimaaZx** [osmdroid/osmdroid#1495]
Hello.
I'm newbie in working with osm library.
I have a question. I want to have ground overlay an image in my map for my android app. 
My image has a polygon shape not rectangle.
I want to set it on exact position.
I tried in google map sdk but could not find right solution for my problem.

Complete description with pictures are here:
https://stackoverflow.com/questions/60191867/how-to-use-ground-overlay-google-map-android-for-polygon-area-to-fit-the-map-ima

I'm tired of asking this. If you know how to handle this , please replay me.

Thank you.

**Comment by monsieurtanuki** [comment]
@NimaaZx If you're able to draw using KML, I suggest you add [osmbonuspack](https://github.com/MKergall/osmbonuspack/wiki) to osmdroid.

You may also use [`GroundOverlay4`](https://github.com/osmdroid/osmdroid/blob/master/osmdroid-android/src/main/java/org/osmdroid/views/overlay/GroundOverlay4.java) (cf. #1361).

**Comment by NimaaZx** [comment]
Thanks a lot. I could add my picture using GroundLayer4, I had to convert your code to Kotlin.
 there it is :
http://uupload.ir/files/clnk_f7326d12-878c-4344-be78-43ea13beae0e.png

my png picture that I added by ground-overlay4 have a border around it. as you know in png image , border is not visible but still exist . for example When I set position for bottom right. the bottom right of whole picture is used for to be set not only shape . it is obvious in my picture.  do you know how can manage this ? I want to import fictional map in over the park. do i have to use Square image ?

**Comment by monsieurtanuki** [comment]
If `GroundOverlay4` works decently for you, then you must adapt to it: provide an image (as a square or a rectangle) and the 4 lat/long coordinates of its corners - that you have to compute (or deduce) if you don't have them.

**Comment by NimaaZx** [comment]
thank you . it is not related but is it function in osmdroid to detection in polygon area ? I found https://stackoverflow.com/questions/15816928/test-of-point-inside-polygon-in-android . somebody said use google map sdk : import com.google.maps.android.PolyUtil;

boolean inside = PolyUtil.containsLocation(new LatLng(...), poly, true);

**Comment by NimaaZx** [comment]
thank you . it is not related but is it function in osmdroid to detection in polygon area ? I found https://stackoverflow.com/questions/15816928/test-of-point-inside-polygon-in-android . somebody said use google map sdk : 

```
import com.google.maps.android.PolyUtil;
boolean inside = PolyUtil.containsLocation(new LatLng(...), poly, true);
```

```

val geoPoints: MutableList<GeoPoint> = ArrayList()
        val latlng: MutableList<LatLng> = ArrayList()

        latlng.add(0, LatLng(35.790622,51.352919 ))
        latlng.add(0,LatLng(35.790617, 51.353059))
        latlng.add(0,LatLng(35.789847,51.352764 ))
        latlng.add(0,LatLng(35.789851,51.352619 ))
        latlng.add(0,LatLng(35.790622,51.352919 ))

        
        geoPoints.add(0, GeoPoint(35.790622,51.352919 ))
        geoPoints.add(0,GeoPoint(35.790617, 51.353059))
        geoPoints.add(0,GeoPoint(35.789847,51.352764 ))
        geoPoints.add(0,GeoPoint(35.789851,51.352619 ))
        geoPoints.add(0,GeoPoint(35.790622,51.352919 ))


        val polygon = Polygon() //see note below

        polygon.setFillColor(Color.argb(75, 255, 0, 0))
        geoPoints.add(geoPoints.get(0));    //forces the loop to close
        polygon.setPoints(geoPoints);
        polygon.setTitle("A sample polygon");
        map?.getOverlayManager()!!.add(polygon);

    val inside = PolyUtil.containsLocation(LatLng(35.790616,51.353058),latlng, true);
    if (inside==true)
        Log.d(TAG,"is in area")

    }
```
I tested it and it is worked but this PolyUtil.containsLocation needs "poly" as LatLng type , and Osmdroid using GeoPoints to draw polygon. i could create 2 list , one geopoints and latlng. it is duplicated list.

can i avoid it by a alternative way?

**Comment by monsieurtanuki** [comment]
@NimaaZx Well if it's not related, please close this issue and create another one, you'll have a better chance to get relevant answers on this additional topic.

**Comment by NimaaZx** [comment]
ok I understand. Thanks you again.
