### ISSUE TITLE
Current location not work

### ISSUE THREAD

**Issue by NimaaZx** [osmdroid/osmdroid#1496]
## Issue Type

[ ] Question
[X ] Bug
[ ] Improvement
[ ] Build system related
[ ] Performance
[ ] Documentation

Hello. Thanks to developer. 
I want to show current location of my phone with internet and GPS in building and indoor but it is never worked. I set all permission for run time.
As well as i installed open map demo app and current location is not worked!!

I have to say it is worked with GPS in outdoor.

is Osmdroid enough reliable for building an app for business usage?

How many devices do have this behaviour like my device?
I can send every log to you.

### If it's a bug, version(s) of android this affects: Viper custom rom - Android 7.1.2 
Xiaomi-Redmi note 3 kenzo
All

### Version of osmdroid the issue relates to:

6.1.2

**Comment by spyhunter99** [comment]
GPS requires the device to have a view of the sky. it won't work indoors. some location providers, such as the 'network gps provider' uses wifi and cellular to triangulate an approximate location. i think you just need to add that as a provider and you'll get whatever is available. other than that, there is no universal indoor geolocation service that i know of

**Comment by NimaaZx** [comment]
I installed custom rom. it seemed not used default provider that I called in my app. I tried adding some providers but nothing work. as I mention osm demo app in play store did not work either. I changed my rom and previous code is worked. I closed the issue. Maybe I will get similar issue on other device. at that moment I reopen it. Thanks a lot.
