### ISSUE TITLE
How to set minimum font size?

### ISSUE THREAD

**Issue by jollheef** [osmdroid/osmdroid#1499]
## Issue Type

- [x] Question

## Description

I have a device with a very small (640x360) resolution, so font size is okay only if really zoomed in, which makes the map unusable.

How to set the minimum font size to make sure that It'll not be smaller regardless of zoom?

## Environment

Google Glass EE2, Android 8.1.0.

### Version of osmdroid the issue relates to:

6.1.5

**Comment by spyhunter99** [comment]
map.setTilesScaledToDpi(true)

**Comment by jollheef** [comment]
Already tried `map.setTilesScaledToDpi(true)` before, no difference.

`map.setTilesScaleFactor(2)` make text bigger, but also make it very blurry.

**Comment by spyhunter99** [comment]
try a different tile source. these images are already rendered, so scaling will always make it blurry. nothing we can do about it. try mapsforge for rendering tiles on device

**Comment by monsieurtanuki** [comment]
An additional solution would be to use [`MapView.setTilesScaleFactor`](https://github.com/osmdroid/osmdroid/blob/master/osmdroid-android/src/main/java/org/osmdroid/views/MapView.java#L434). With that, you can control the display for an integer zoom level.
But as @spyhunter99 pointed out, that may look blurry for an "integer+.99" zoom level. Then a solution would be to display only integer zoom levels, using [`MapView.setZoomRounding`](https://github.com/osmdroid/osmdroid/blob/master/osmdroid-android/src/main/java/org/osmdroid/views/MapView.java#L1835), if that suits your needs.

**Comment by monsieurtanuki** [comment]
@jollheef Any result with a combination of `setTilesScaledToDpi`, `setTilesScaleFactor` and `setZoomRounding`? Another solution would be to use [another tile source](https://github.com/osmdroid/osmdroid/blob/master/osmdroid-android/src/main/java/org/osmdroid/tileprovider/tilesource/TileSourceFactory.java#L99), one with a better text look.
Beyond that there's nothing we can do about this issue: in osmdroid we manipulate tile images created by others. We can make tiles look smaller or bigger, but we cannot change the text inside.
Sorry about that. Please feel free to close the issue when it's ok with you.
