### ISSUE TITLE
get versionName of osmdroid library programmatically

### ISSUE THREAD

**Issue by mikebravoyes** [osmdroid/osmdroid#1500]
## Issue Type

[x] Question

## Description and/or steps/code to reproduce the problem

Is there an easy way to retrieve the current versionName (e.g. "6.1.2") of the osmdroid library? I tried the following, but in the last step, an exception is thrown.

```
String versionName = "?";	// default, unknown

MapView mapView    = findViewById(R.id.mapview);
Class mapClass     = mapView.getClass();
Package mapPackage = mapClass.getPackage();
String packageName = mapPackage.getName();    // = "org.osmdroid.views"
PackageManager pManager = this.getPackageManager();

try
{	// the next line throws NameNotFoundException
	PackageInfo pInfo = pManager.getPackageInfo(packageName, 0); 
	versionName = pInfo.versionName;
}
catch (PackageManager.NameNotFoundException e)
{
	e.printStackTrace();
}
```
Perhaps, I'm thinking too complicated, but an easy way - something like
`String versionName = mapView.getVersionName();`
doesn't seem to exist. Any ideas appreciated.

## Environment

Huawei P10 Lite, Android 8.0.0, SDK_INT 26 ("Oreo")

### Version of osmdroid the issue relates to:

6.1.2

**Comment by mikebravoyes** [comment]
@spyhunter99 
@mat8854 
@pasniak 
@linquize 

Does anybody of have an idea?

**Comment by spyhunter99** [comment]
There currently isn't, but i can add it..

**Comment by mikebravoyes** [comment]
@spyhunter99 
That would be great!

**Comment by spyhunter99** [comment]
any other properties you want in it?

**Comment by mat8854** [comment]
@mikebravoyes Oh, I tried the code snippet a few days ago out of curiosity. I got the same `NameNotFoundException` exception. First I thought it is related to Proguard / R8 enabled in a release build. But then the Exception would be `ClassNotFoundException`.

**Comment by mikebravoyes** [comment]
@spyhunter99 
No! For me just the String versionName (e.g. "6.1.6") would be perfect.

**Comment by spyhunter99** [comment]
`org.osmdroid.OsmdroidBuildInfo.VERSION`  returns 6.1.7-SNAPSHOT or whatever the current build version is.

**Comment by mikebravoyes** [comment]
@spyhunter99 
Thanks for your effort! 

But what is the correct entry in "build.gradle" now? Until yesterday it was:
```
dependencies {
    implementation group: 'org.osmdroid', name: 'osmdroid-android', version: '6.1.6'
}
```
I tried '6.1.7' and '6.1.7-SNAPSHOT', but none of them was working.
Error message in the Build Tab:

> ERROR: Failed to resolve: org.osmdroid:osmdroid-android:6.1.7
> Show in Project Structure dialog
> Affected Modules: app
>
