### ISSUE TITLE
how to load *.tif  files to osmdroid mapview

### ISSUE THREAD

**Issue by syau401** [osmdroid/osmdroid#1506]
Please note: issues related to or caused by osmbonuspack will be closed with a
suggestion to open an issue at https://github.com/MKergall/osmbonuspack
how to load *.tif  files to my osmdroid mapview
(feel free to delete whatever doesn't apply)

## Issue Type
Question
[√ ] Question
[ ] Bug
[ ] Improvement
[ ] Build system related
[ ] Performance
[ ] Documentation

### If it's a bug, version(s) of android this affects:

All

### Version of osmdroid the issue relates to:

6.1.2

**Comment by monsieurtanuki** [comment]
TIFF files are not supported natively on Android.
If it's possible, transform your files into PNG or JPEG format before.

**Comment by syau401** [comment]
if TIFF files are not supported natively on Android, how  to load *.png or *.jpeg files to osmdroid mapview

**Comment by syau401** [comment]
May I  load *.img or *.ers  files to my osmdroid mapview?

**Comment by syau401** [comment]
if TIFF files are not supported natively on Android, how to load *.png or *.jpeg files to osmdroid mapview?  and may I load *.img or *.ers files to my osmdroid mapview?

**Comment by spyhunter99** [comment]
If this is for geo tiff files, try gdal with geoserver
