### ISSUE TITLE
Tap on Multiple Markers: open multiple selection dialog

### ISSUE THREAD

**Issue by matrad** [osmdroid/osmdroid#151]
When tapping on a marker and the markers are so close, that we cannot detect on which marker the user tapped, there should be a possibility to get a list of marker items that we can show the user a "Multiple Selection Dialog"

**Comment by spyhunter99** [comment]
Is this for itemized icon overlays or the `Marker` class?

**Comment by monsieurtanuki** [comment]
@matrad I posted a solution for detecting all the items under a touch event in #1122.
Then you do what you want with them, including display your own "Multiple Selection Dialog".

**Comment by monsieurtanuki** [comment]
Closed: cf. solution in #1122
