### ISSUE TITLE
Unable to build from local

### ISSUE THREAD

**Issue by pizzetto** [osmdroid/osmdroid#1510]
## Issue Type

[ ] Question
[ ] Bug
[ ] Improvement
[x ] Build system related
[ ] Performance
[ ] Documentation

## Description and/or steps/code to reproduce the problem
I cloned the GitHub repo and followed the instructions from [here](https://github.com/osmdroid/osmdroid/wiki/How-to-build-osmdroid-from-source).

I run gradlew clean install but I get this error:

```
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine java version from '13.0.2'.

```

As soon I update gradle to 5.6.4 (I tried also updating to 6.1.2) I get this error:

```
Gradle sync failed: Cause: startup failed:
			script 'https://raw.githubusercontent.com/gradle-fury/gradle-fury/v1.1.4/gradle/maven-support.gradle': 1453: unable to resolve class org.gradle.api.internal.ClosureBackedAction 
			@ line 1453, column 13.
			new org.gradle.api.internal.ClosureBackedAction({
			^
			1 error
			Consult IDE log for more details (Help | Show Log) (23 s 857 ms)
```
As a result I'm not able to compile locally.

What am I doing wrong?
Thank you

## Environment

Windows 10 machine
Android Studio 3.6

### If it's a bug, version(s) of android this affects:

All

### Version of osmdroid the issue relates to:

6.1.2

**Comment by monsieurtanuki** [comment]
I've just had the same kind of problem with Android Studio 3.6.1 one hour ago.
As it's not the first problem I have with it, I switched back to Android Studio 3.5.3. And now I'm fine.

**Comment by pizzetto** [comment]
Confirmed, thank you!
