### ISSUE TITLE
Tiles in HIKEBIKEMAP not loaded as of release 6.1.3

### ISSUE THREAD

**Issue by mikebravoyes** [osmdroid/osmdroid#1516]
## Issue Type

[x] Bug

## Description and/or steps/code to reproduce the problem

@monsieurtanuki
There is a problem with TileSourceFactory.HIKEBIKEMAP - not a TilesOverlay, just a "normal" base map. It doesn't load any tiles at all.

All other tile sources that I have tested, are OK. No idea, what is so special about this map type.

I tested with all osmdroid releases between 6.1.2 (still OK) and 6.1.6. The failure was obviously introduced with 6.1.3. Its releases notes say:

> minor bug fixes
> esri shape viewer
> simplified "speech balloon" demo

## Environment

Huawei P10 Lite (Android 8.0.0) 
Samsung Galaxy Tab A 10.5 (Android 9)

### Version of osmdroid the issue relates to:

6.1.3 ... 6.1.6

**Comment by monsieurtanuki** [comment]
I guess it's related to the recent issue regarding the http/https access to tiles.
My suggestion for the time being: use instead either
````java
public static final OnlineTileSourceBase HIKEBIKEMAP = new XYTileSource("HikeBikeMap",
	 0, 18, 256, ".png",
	new String[] {
			"http://a.tiles.wmflabs.org/hikebike/",
			"http://b.tiles.wmflabs.org/hikebike/",
			"http://c.tiles.wmflabs.org/hikebike/"  });
````
or
````java
public static final OnlineTileSourceBase HIKEBIKEMAP = new XYTileSource("HikeBikeMap",
	 0, 18, 256, ".png",
	new String[] {
			"https://tiles.wmflabs.org/hikebike/"  });
````
(not fully tested, though)
Have a look at the [specific entry in the FAQ](https://github.com/osmdroid/osmdroid/wiki/FAQ#i-cannot-see-the-map-tiles-on-my-android-9), too.

**Comment by mikebravoyes** [comment]
@monsieurtanuki 
The suggestion with `network_security_config.xml` in the FAQ did not help.

But both of your suggestions work, although I don't understand why. MAPNIK and OPEN_SEAMAP also use the `https` syntax and have no problems.

Anyway, it's OK now. Thanks a lot!
