### ISSUE TITLE
ShapeFile support problem.

### ISSUE THREAD

**Issue by sun-jiao** [osmdroid/osmdroid#1518]
## Issue Type

[x] Bug

add shapefile to map view failed.

even the sample file TM_WORLD_BORDERS_SIMPL-0.3 is not supported.

some borders in the file can't show in map.

(And my own shapefile totally dosen't work.)

### Screenshot

https://github.com/sun-jiao/GitHubUse/blob/master/Screenshot_20200311-140846.png

### Code

```
File myshape = new File (getExternalFilesDir("TM_WORLD_BORDERS_SIMPL-0.3") +"/TM_WORLD_BORDERS_SIMPL-0.3.shp");
        List<Overlay>  folder = null;
        try {
            folder = ShapeConverter.convert(mMapView, myshape);
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        if (folder == null)
            Log.i("SHP", "onCreate: null");
        else{
            mMapView.getOverlayManager().addAll(folder);
            mMapView.invalidate();
        }
```

### known affected version: 

Android 10. 

### hardware

Google Pixel 3

### Version of osmdroid the issue relates to:

6.1.6

**Comment by mat8854** [comment]
@sun-jiao For further debugging you should post your own shp-file here. Since it is a binary file format you can use a third party tool for extracting the data (coordinates):
* https://mapshaper.org/
* https://wiki.openstreetmap.org/wiki/Shapefiles

The osmdroid `ShapeConverter` is a simple parser mapping the shape data to osmdroid equivalents. It returns a `List<Overlay>`.

**Comment by sun-jiao** [comment]
> @sun-jiao For further debugging you should post your own shp-file here. Since it is a binary file format you can use a third party tool for extracting the data (coordinates):
> 
> * https://mapshaper.org/
> * https://wiki.openstreetmap.org/wiki/Shapefiles
> 
> The osmdroid `ShapeConverter` is a simple parser mapping the shape data to osmdroid equivalents. It returns a `List<Overlay>`.

the sample file TM_WORLD_BORDERS_SIMPL-0.3 is not fully supported, too.

**Comment by sun-jiao** [comment]
> @sun-jiao For further debugging you should post your own shp-file here. Since it is a binary file format you can use a third party tool for extracting the data (coordinates):
> 
> * https://mapshaper.org/
> * https://wiki.openstreetmap.org/wiki/Shapefiles
> 
> The osmdroid `ShapeConverter` is a simple parser mapping the shape data to osmdroid equivalents. It returns a `List<Overlay>`.

and, our own shape file is here: 
https://drive.google.com/file/d/1O1Wqt7gPbsuWDd4rGaquEKM6OFNddRf3/view?usp=sharing

**Comment by mat8854** [comment]
Quick *.shp import into Google Earth from your file shows lots of rectangles. Is this correct?

![image](https://user-images.githubusercontent.com/2643309/77251743-68d20800-6c50-11ea-9626-172eab4c92de.png)

From http://thematicmapping.org/downloads/TM_WORLD_BORDERS_SIMPL-0.3.zip some countries look okay (AR). Others not (HI, DK). Only tried randomly.
![image](https://user-images.githubusercontent.com/2643309/77252258-f57dc580-6c52-11ea-8691-be418b821a90.png)
![image](https://user-images.githubusercontent.com/2643309/77252260-fb73a680-6c52-11ea-9e01-3854c3ca3d5c.png)
![image](https://user-images.githubusercontent.com/2643309/77252262-01698780-6c53-11ea-8ce4-27919631ad4e.png)

**Comment by spyhunter99** [comment]
this could be an artifact of the point reducer. maybe...or there is something fundamental that was missed in the conversion class

**Comment by mat8854** [comment]
Google Earth is complaining when importing TM_WORLD_BORDERS_SIMPL-0.3.shp :
![image](https://user-images.githubusercontent.com/2643309/77253045-3e844880-6c58-11ea-89c1-70f1ce77e364.png)
Translated: 
"Invalid data found"
"Some functions were not imported due to invalid or out of area coordinates."

**Comment by sun-jiao** [comment]
> Quick *.shp import into Google Earth from your file shows lots of rectangles. Is this correct?
> 


Yeah, it has lots of rectangles，but they are all over the world.

**Comment by mat8854** [comment]
@sun-jiao Yes, I see them all over the world. Your file is okay in Google Earth. Google Earth has also problems with the `TM_WORLD_BORDERS_SIMPL-0.3.shp` file.

But there seems to be something wrong with the osmdroid `ShapeConverter`. There are no unit test for verification. The file format does not look that complicated: https://en.wikipedia.org/wiki/Shapefile . Maybe there are also free tested Java shape file parsers.

**Comment by sun-jiao** [comment]
> @sun-jiao Yes, I see them all over the world. Your file is okay in Google Earth. Google Earth has also problems with the `TM_WORLD_BORDERS_SIMPL-0.3.shp` file.
> 
> But there seems to be something wrong with the osmdroid `ShapeConverter`. There are no unit test for verification. The file format does not look that complicated: https://en.wikipedia.org/wiki/Shapefile . Maybe there are also free tested Java shape file parsers.
> 
> Update. Quick Google search:
> 
> * https://stackoverflow.com/questions/2044876/does-anyone-know-of-a-library-in-java-that-can-parse-esri-shapefiles
> * http://docs.geotools.org/ under LGPL, https://github.com/geotools/geotools, API doc https://docs.geotools.org/stable/userguide/library/data/shape.html

yeah, I saw it. but I found osmdroid is using the same library, so I didn't try it.

**Comment by sun-jiao** [comment]
@mat8854 The `TM_WORLD_BORDERS_SIMPL-0.3.shp` file is shown perfectly in dabebro's Shapefile Over Map. ( https://play.google.com/store/apps/details?id=com.dabebro.somdemo&hl=zh ) And so  is my "rectangles".

If the file isn't correct, I think it's better to change the sample files provided in osmdroid's userguide.

**Comment by spyhunter99** [comment]
well there are shape file readers, but there few that are license compatible with osmdroid and will actually run on android. The convertor basically iterates over all objects in the shape file and attempts to convert them. If you have time, load file a file that isn't working correctly and step through the osmdroid shape converter and try and figure out what the issue is. The only "test" that exists is loading a shape file and visually comparing them against another reference point. Shapefiles are similar to KML, some programs interpret or extend the format in funky ways which can cause unpredictable output with different visualization tools.  The shape format also has quite a lot of intricate details related to holes, volumes, volumes with holes. Not everything is currently mapped to osmdroid overlays.

Geotools is a gigantic library and will probably never run on android due to their heavy usage of SPI. If you have a sample shape file that has an issue and can point me to specifics in the file, such as an id, name or lat lon, i can try and figure out what's going on

**Comment by sun-jiao** [comment]
> well there are shape file readers, …………
> 
> …………If you have a sample shape file that has an issue and can point me to specifics in the file, such as an id, name or lat lon, i can try and figure out what's going on

OK， thank you, I'll try it.

**Comment by mat8854** [comment]
> well there are shape file readers, but there few that are license compatible with osmdroid and will actually run on android. The convertor basically iterates over all objects in the shape file and attempts to convert them. If you have time, load file a file that isn't working correctly and step through the osmdroid shape converter and try and figure out what the issue is. The only "test" that exists is loading a shape file and visually comparing them against another reference point. Shapefiles are similar to KML, some programs interpret or extend the format in funky ways which can cause unpredictable output with different visualization tools. The shape format also has quite a lot of intricate details related to holes, volumes, volumes with holes. Not everything is currently mapped to osmdroid overlays.
> 
> Geotools is a gigantic library and will probably never run on android due to their heavy usage of SPI. If you have a sample shape file that has an issue and can point me to specifics in the file, such as an id, name or lat lon, i can try and figure out what's going on

@spyhunter99  Oh, I did not the library is that big. I meant just copying over the ShapeParser (if it was allowed by license). You are more familiar with this whole ShapeFile stuff ...

For own implementation one can use a script language to generate lots of test data files (valid, invalid, all edge cases). With a proven generator of course. Then verify the own parser output. If verification also needs visual comparison after rendering that is quite hard to do.

**Comment by sun-jiao** [comment]
@mat8854 @spyhunter99 
Problem resolved.
This shapefile has some Geo Points close to the 180° longitude, whose longitude is out of range. These numbers are slightly larger than 180.00 or smaller than -180.00. Because of which, the BondingBox throws a illegal argument exception. 
I have discussed with the GIS developer, who created the file using ArcGis and ENVI. We think it's due to an error during the floating-point arithmetic of these software. 
Considering the errors that these software may cause, I think it's a good idea to add an inspection operation: if the longitude and latitude is slightly out of range, we can adjust it to a critical value in the ShapeConverter.java. 

Thanks to all developers who helped me.
