### ISSUE TITLE
MapTileApproximater keep requesting and expiring scaled tiles

### ISSUE THREAD

**Issue by treenewbee** [osmdroid/osmdroid#1519]
## Issue Type

[ x ] Question
[ x ] Bug
[ ] Improvement
[ ] Build system related
[ x ] Performance
[ ] Documentation

## MapTileApproximater keep requesting and expiring scaled tiles nonstop, when no provider can return a tile successfully 
https://github.com/osmdroid/osmdroid/blob/d08366238d32291d22e84e698e0177392e49fbb1/osmdroid-android/src/main/java/org/osmdroid/tileprovider/modules/MapTileModuleProviderBase.java#L299

It hopes other provider will be able to get the tile in native zoom, so it make the scaled tile expires and fires up new request. But in a hopeless situation it just dry up all your cores to loop itself forever.  

### Version of osmdroid the issue relates to:

6.1.2

**Comment by monsieurtanuki** [comment]
I wouldn't call it a bug: it works the way it's supposed too. In limit cases, I do understand that it may need some improvement, though.
Another point: it doesn't "loop forever", it just works when needed. If your map is still, there's no reason why the tiles should be refreshed and the approximation computed - am I correct?

That being said, we need several things.

What is a "hopeless situation", and who says so?
Typically, for instance it could be a "no internet" situation. Or "slow internet".
In first approach let's say it's a "no internet": it's easier to detect.
We already detect that, either with `NetworkAvailabilityCheck` or more precisely with [`MapTileProviderBasic.isDowngradedMode`](https://github.com/osmdroid/osmdroid/blob/master/osmdroid-android/src/main/java/org/osmdroid/tileprovider/MapTileProviderBasic.java#L146).
And we already take that into consideration in [`MapTileProviderArray.getMapTile`](https://github.com/osmdroid/osmdroid/blob/master/osmdroid-android/src/main/java/org/osmdroid/tileprovider/MapTileProviderArray.java#L120): if we find a tile in the memory cache and if we are in downgraded mode, we consider that the tile is good enough, even if it's expired or scaled.

@treenewbee I guess what you want is already more or less covered in terms of "downgrade mode" code. The problem might be with the memory cache being emptied too often. What if you expand your memory cache: would that help? Something like `providerArray.getTileCache().ensureCapacity(50)`. Could you try that?

**Comment by treenewbee** [comment]
So I have two providers in MapTileProviderArray: one is completely offline provider extends MapTileModuleProviderBase with limited native zoom, another is MapTileApproximater to scale when out of native zoom. 

So I think the issue is I am using MapTileProviderArray but not overriding isDowngradedMode, so even when map is completely still, the tile requests are firing up non-stop when out of native zoom.

Then maybe isDowngradedMode should be abstract so people will know it needs to be implemented. 

I was looking at OfflineTileProvider as an example, which does not implement isDowngradeMode either. So I would suspect it will also suffering the same looping forever issue.

**Comment by monsieurtanuki** [comment]
The way you describe it, your code is very similar to `OfflineTileProvider`, am I correct?
You're right, `OfflineTileProvider` should override `isDowngradedMode` and return `true`.
But we cannot make `isDowngradedMode` abstract, for consistency reasons with all osmdroid user historical code.

I don't understand why non-stop tile requests actually fire on a still map. Do you have a code example of your provider array?

**Comment by treenewbee** [comment]
Yes I am doing very similar to `OfflineTileProvider`: 
```kotlin
class Array(pTileSource: ITileSource?, pRegisterReceiver: IRegisterReceiver?) :
    MapTileProviderArray(pTileSource, pRegisterReceiver) {
    init {
        val provider = Provider(4, 20)
        mTileProviderList.add(provider)
        val approximater = MapTileApproximater()
        approximater.addProvider(provider)
        mTileProviderList.add(MapTileApproximater())
    }
}
```
I think it keeps looping because:

The tile is not `ExpirableBitmapDrawable.UP_TO_DATE` and `isDowngradedMode` is false, so the scaled tile got back into the queue. 

https://github.com/osmdroid/osmdroid/blob/d08366238d32291d22e84e698e0177392e49fbb1/osmdroid-android/src/main/java/org/osmdroid/tileprovider/MapTileProviderArray.java#L136

The next round basically the same, Provider is out of native zoom so failed. MapTileApproximater got yet another scaled tile so expired, then it keeps looping.

**Comment by monsieurtanuki** [comment]
@treenewbee I've just tested:
* you're right - as it is, `OfflineTileProvider` can run an endless loop searching for approximations
* but everything works great with no endless loop (approximation are computed only once on a still map) with the forementioned
````java
@Override
protected boolean isDowngradedMode(long pMapTileIndex) {
	return true;
}
````

**Comment by monsieurtanuki** [comment]
@treenewbee Isn't everything fine if you override `isDowngradedMode`?

**Comment by treenewbee** [comment]
Yes, implementing `isDowngradedMode` fixed the issue, everything is working as expected.
