### ISSUE TITLE
Maps are displayed repeatedly

### ISSUE THREAD

**Issue by alicewang05** [osmdroid/osmdroid#152]
Hello,

I am trying load Mbtiles to the map. It is working fine, but there are so many maps display at the same time, I tried to increase the min zoom level, but could still move around to see them. Is there any way to disable this ? Thanks a lot.

Best Regards,
Alice

![example](https://cloud.githubusercontent.com/assets/12249700/9302821/79b4435a-44d1-11e5-9b05-a213dbfea972.png)

**Comment by ziem** [comment]
Try to set min zoom to higher value (e.g. 8).

**Comment by alicewang05** [comment]
Thanks for your quick response.

Currently what we are trying to do is show only one world map (fill the whole screen ideally) on the screen first, then allow user to zoom in to see more. Also we do not want user to be able to scroll around to see more maps. After increasing the min zoom level, did not solve this issue with multiple maps being drawn. I also tried to setScrollableAreaLimit(bound), does not work either.

Any idea to fix this, thanks a log. 

Best Regards,
Alice

**Comment by spyhunter99** [comment]
You can disable panning too by setting the bounds. Try something like this

        mMapView.setBuiltInZoomControls(false);
        mMapView.setMultiTouchControls(false);
        mMapView.setScrollableAreaLimit(mMapView.getBoundingBox());
        mMapView.setMaxZoomLevel(2);
        mMapView.setMinZoomLevel(2);

**Comment by spyhunter99** [comment]
to add, unfortunately, i don't think there's a way to disable wrap around (multiple views of the same tile when you're zoomed out) with osmdroid. It does exist on other, non-android, osm based map viewers though

**Comment by alicewang05** [comment]
Right, I see. Thank you for your help. 
Best Regards,
Alice

**Comment by spyhunter99** [comment]
related #183 #201
