### ISSUE TITLE
Polylines cut off then map rotated

### ISSUE THREAD

**Issue by pasniak** [osmdroid/osmdroid#1527]
## Issue Type

[ ] Question
[x] Bug

## Description and/or steps/code to reproduce the problem
When map is rotated (I hook map to the compass) a polyline which ends beyond the screen is cut off **on the screen** (instead off going off the screen).

### If it's a bug, version(s) of android this affects:

tested on a hardware tablet

### Version of osmdroid the issue relates to:
6.1.7-SNAPSHOT (building off master)

**Comment by monsieurtanuki** [comment]
I couldn't reproduce the issue.
Could you create a simple example, like an L-shaped Polyline, that is cut off.
Honestly, most of the Polylines that go beyond the screen ARE cut off, but beyond the visible part (something like twice the screen size further), therefore it shouldn't be a problem.

**Comment by pasniak** [comment]
Here's how NE-rly polyline looks like when facing S:
![Screenshot_2020-03-19-11-44-49](https://user-images.githubusercontent.com/19778666/77086595-e5b77480-69f9-11ea-84c7-b940f69d15e1.png)
Interestingly milestones go all the way. 

This seems to occur at certain low zoom levels.

**Comment by monsieurtanuki** [comment]
I didn't mean that the issue did not happen, I really meant that I needed a simple example to work on.
I tried to reproduce the "NE Polyine with map looking south" case, and that looks perfect on my smartphone.

**Comment by monsieurtanuki** [comment]
@pasniak Could be related to #1528: do you use `MapView.setMapCenterOffset`?

**Comment by monsieurtanuki** [comment]
@pasniak Could be solved by #1529. Please have a go.

**Comment by pasniak** [comment]
Great, yes I do use `setMapCenterOffset` and yes the issue is gone on bug/#1528. Thanks!

**Comment by monsieurtanuki** [comment]
That's good news!
