### ISSUE TITLE
Unexpected polyline drawing when map is rotated

### ISSUE THREAD

**Issue by Ruediger34** [osmdroid/osmdroid#1528]
## Issue Type

[ ] Question
[x] Bug
[ ] Improvement
[ ] Build system related
[ ] Performance
[ ] Documentation

## Description and/or steps/code to reproduce the problem

Hi,
I´ve identified a similar or other issue with polylines like #1527 . The following picture shows how it should be and if the map is rotated with the RotationGestureOverlay:
 
![grafik](https://user-images.githubusercontent.com/20127481/77174191-fa127480-6ac0-11ea-9043-5334970efafd.png)

This one occurs if I use the following code to rotate the map:

`mapController.animateTo(new GeoPoint(gpsLocation.getLatitude(), gpsLocation.getLongitude()), zoom, (long) 750, gpsLocation.getBearing());`
 
 
![grafik](https://user-images.githubusercontent.com/20127481/77174298-20381480-6ac1-11ea-9543-1fb5d528fc40.png)
![grafik](https://user-images.githubusercontent.com/20127481/77174303-23330500-6ac1-11ea-9b15-fc4419062a65.png)

If you need any further code sections, please let me know.

### If it's a bug, version(s) of android this affects:

All

### Version of osmdroid the issue relates to:

6.1.6

**Comment by monsieurtanuki** [comment]
Cannot reproduce the issue.
Please provide the code for a simple case with a small Polyline.

**Comment by Ruediger34** [comment]
Oh, I`m sorry - I have forgotten to tell that before the mapController.animateTo is called; 
I call setMapCenterOffset(0, 450);
If I set the setMapCenterOffset(0, 0); everything is fine. 
With different setMapCenterOffset(X, Y) values, also the position of the "visual polyline error" moves.

So it is probably related with the MapCenterOffset.

Can you reproduce it now?

**Comment by monsieurtanuki** [comment]
Very interesting!
The fix should be easy then.
For the moment we pre-crop the Paths into the screen before we draw them, not only for performance reasons but also because "at some point" Android doesn't draw "too wide Paths".
If I remember well we crop from the screen center with a radius of the screen radius, which is relevant for a no map offset situation.
With just a double radius crop parameter, we should be able to handle any map offset.

**Comment by monsieurtanuki** [comment]
I've just pushed #1529, which should fix the issue.
"Should"? Honestly for this one I'm in a "lazy bastard" mode, and I didn't find the will to build a test example from scratch.
@Ruediger34 Don't hesitate to test it, and tell us if it works!

**Comment by monsieurtanuki** [comment]
@Ruediger34 According to @pasniak in #1527 the fix works. Do you want to test for your own case or can we close the issue?

**Comment by Ruediger34** [comment]
@monsieurtanuki I have tested your PR #1529 and the bug is solved. 

Thank you very much for your fast and successful response.
