### ISSUE TITLE
No map in offline mode in v4.3

### ISSUE THREAD

**Issue by wisien92** [osmdroid/osmdroid#153]
Hi, 

I have been using osmdroid in version 4.2 and when I updated it to v4.3 (graddle) the are no tiles displayed. I have not changed code - should I ?

I have maps from atlas creator. They are in tiles.zip file in osmdroid folder. Inside zip there is MapquestOSM folder and there are tiles in .png format.

**Comment by spyhunter99** [comment]
What are you using for a tile source?

**Comment by wisien92** [comment]
OpenStreetMap MapQuest

**Comment by wisien92** [comment]
Podmieniłem pliki na format .JPEG i działa.
