### ISSUE TITLE
Direction arrow is white. It should be a more visible color. 

### ISSUE THREAD

**Issue by johan974** [osmdroid/osmdroid#1530]
Please note: issues related to or caused by osmbonuspack will be closed with a
suggestion to open an issue at https://github.com/MKergall/osmbonuspack

## Issue Type
[X] Bug

## Description and/or steps/code to reproduce the problem
When navigating with the (great) Osmdroid / Mapsforge / Osmbonuspack, the direction arrow was always green. Since upgrading from osmdroid 6.0.1 (or 3) to 6.1.6 the direction arrow turned to be white. The arrow is hardly visible. See the picture below. 

![afbeelding](https://user-images.githubusercontent.com/6309562/77252659-8a81be00-6c55-11ea-90cc-70954b72047f.png)

How can I change the (standard) direction arrow back to a visible color again? 

## Environment
Android 8. 

### If it's a bug, version(s) of android this affects:
Android 8, maybe other versions as well. 

### Version of osmdroid the issue relates to:
Osmdroid 6.1.6
Mapsforge 0.11.0
Osmbonuspack 6.6.0

**Comment by monsieurtanuki** [comment]
You're right, the direction arrow used to be:
![image](https://user-images.githubusercontent.com/11576431/77256614-a42fff00-6c6f-11ea-9667-9af444d18135.png)
We changed this icon 16 months ago, because we only had one dpi version and there was issue #1209 about not having a version for each dpi folder (h,m,xh,xxh,xxxh).
Another icon with only one color (white or green) wouldn't make sense either.

@johan974 What would you say about this one (two-tone "navigation" on [material.io](https://material.io/resources/icons/?icon=navigation&style=twotone)):
![image](https://user-images.githubusercontent.com/11576431/77256790-a5adf700-6c70-11ea-996b-f267405fb9e1.png)
In the meanwhile you can change the bitmap with `DirectedLocationOverlay.setDirectionArrow(Bitmap)`

**Comment by johan974** [comment]
I used it (finally) and saw that the icon is very small. It is much smaller than the previous one so I get a strange distance between the real center and where the two-tone is shown. 
Is it not possible to re-use the original one (by default)? It is much more nice than this one.

**Comment by johan974** [comment]
Does no one has the same problem during this 1.5 years?

**Comment by monsieurtanuki** [comment]
> I used it (finally) and saw that the icon is very small

Very surprising. If you take the "48" versions of this icon in the downloaded Android folders ([navigation-black-android.zip](https://github.com/osmdroid/osmdroid/files/4366419/navigation-black-android.zip)), it should be just a bit smaller than a big floating action button ("54"). Which seems big enough for a navigation icon.

> It is much smaller than the previous one so I get a strange distance between the real center and where the two-tone is shown.

Hmm, the center is just supposed to be at the middle of the icon, how big the icon may be.

> Is it not possible to re-use the original one (by default)?

I'm afraid not: we need 5 versions of the same icon of the 5 Android dpi configurations.

> It is much more nice than this one.

It's a matter of taste. I wasn't a big fan of green one - but that's not why we put a new icon.

> Does no one has the same problem during this 1.5 years?

Apparently. Or the other people were very shy.

**Comment by johan974** [comment]
Thank you for the Zip. I will try to test it today. To change the direction bitmap, you also have to change the yellow man. Do you have one yellow man available? 

**Thank you** again for the library! Since about 6 years I created an Andoid app for geocaching. I use it since then nearly every week.

**Comment by monsieurtanuki** [comment]
The yellow man was replaced in #1209 for the same reasons.
Could you please have a look at [material.io](https://material.io/resources/icons/?style=twotone) and try to find the most relevant icon for this purpose?

**Comment by johan974** [comment]
Thank you. It works. See this issue on [stackoverflow](https://stackoverflow.com/questions/60792234/osmdroid-change-the-default-white-color-of-the-direction-arrow-or-how-to-cu).

**Comment by monsieurtanuki** [comment]
I've just merged #1531 and #1532, that include the 48-twotone-navigation icon instead of the white arrow.

Btw:
* you didn't have to create images, they were included in the *dpi folders
* actually the yellow guy does exist in all dpi configurations (he's just a bit blurry)

Anyway the next version of osmdroid will use a more visible icon for navigation for both `MyLocationNewOverlay` and `DirectedLocationOverlay`.

**Comment by johan974** [comment]
Thank you very much. I am using the omsdroid, mapsforge and osmbonuspack for about 6 years weekly!!

**Comment by monsieurtanuki** [comment]
@johan974 Cool! Don't hesitate to ask for new features.

**Comment by oliverlockwood** [comment]
@monsieurtanuki what's the ETA for a version of osmdroid which includes this change?

Context: https://github.com/cyclestreets/android/issues/385 - I've recently upgraded our app to osmdroid `6.1.6` from `5.6.5`, and really dislike the new direction arrow.  The now one looks acceptable, so I'd rather avoid having to implement a workaround if I can avoid it 😄

**Comment by monsieurtanuki** [comment]
@oliverlockwood What's an "ETA"?
Regardless, I suppose that if you download the 5 dpi version of this icon (two-tone "navigation" on [material.io](https://material.io/resources/icons/?icon=navigation&style=twotone)):
![image](https://user-images.githubusercontent.com/11576431/77256790-a5adf700-6c70-11ea-996b-f267405fb9e1.png)
and just use `DirectedLocationOverlay.setDirectionArrow(Bitmap)` that should do the job, shouldn't it?

**Comment by oliverlockwood** [comment]
@monsieurtanuki thanks for the quick reply. That's more or less what I'm doing for now.

ETA is shorthand for estimated time, as in I wondered if you have any plans for releasing 6.1.7?

**Comment by monsieurtanuki** [comment]
> ETA is shorthand for estimated time

@oliverlockwood That is nonsense: the A stands for nothing! ;)

I haven't heard of any release plan for 6.1.7 in a near future. I don't know what would trigger it either: I've just created #1577 for that purpose.

**Comment by oliverlockwood** [comment]
Estimated Time of Arrival, then, if we're being picky 😂 

Thanks for creating #1577, I'll keep an eye on it.
