### ISSUE TITLE
Configuration method 'getInstance()' is not found

### ISSUE THREAD

**Issue by MahatmaGonnDir** [osmdroid/osmdroid#1535]
## Issue Type

[X] Question

## Description and/or steps/code to reproduce the problem
I followed the instruction "how to use the osmdroid library" (https://github.com/osmdroid/osmdroid/wiki/How-to-use-the-osmdroid-library). All worked fine expect for one line of code: line 22 ->  
Configuration.getInstance().load(ctx, PreferenceManager.getDefaultSharedPreferences(ctx)); 

throws an error: 
"cannot find symbol
        Configuration.getInstance().load(ctx, PreferenceManager.getDefaultSharedPreferences(ctx));
                     ^
  symbol:   method getInstance()"

without this line of code, the map is empty/unvisible on my mobile app. I also created a stackoverflow question for this: https://stackoverflow.com/questions/60848114/map-is-not-visible-in-openstreetmap-osm

## Environment
Android Studio (java project, not Kotlin)

### Version of osmdroid the issue relates to:

6.1.6

**Comment by monsieurtanuki** [comment]
I don't know how up-to-date the wiki is.
My suggestion: have a look at the demo app (available in Google Play), see which demo you like, and have a look at the corresponding code (like [`SampleMarker.java`](https://github.com/osmdroid/osmdroid/blob/master/OpenStreetMapViewer/src/main/java/org/osmdroid/samplefragments/data/SampleMarker.java) for the "Marker" demo).

**Comment by MahatmaGonnDir** [comment]
that's a bit sad I think, because this wiki is not really useful than. However I am struggeling get my App running. All I want is just to display the map on my screen (in an app). I hope you understand me. I do not really understand which classes I need for that.

**Comment by MahatmaGonnDir** [comment]
> I don't know how up-to-date the wiki is.
> My suggestion: have a look at the demo app (available in Google Play), see which demo you like, and have a look at the corresponding code (like [`SampleMarker.java`](https://github.com/osmdroid/osmdroid/blob/master/OpenStreetMapViewer/src/main/java/org/osmdroid/samplefragments/data/SampleMarker.java) for the "Marker" demo).

that's a bit sad I think, because this wiki is not really useful than. However I am struggeling get my App running. All I want is just to display the map on my screen (in an app). I hope you understand me. I do not really understand which classes I need for that.

**Comment by MahatmaGonnDir** [comment]
Ah I fixed it, the error was my wrong class which I imported. You have to "import org.osmdroid.config.Configuration;" not ".res.Configuration;

**Comment by monsieurtanuki** [comment]
@MahatmaGonnDir I hope you've managed to display your first map. If I understand well it's OK to close this issue, isn't it?

**Comment by MahatmaGonnDir** [comment]
@monsieurtanuki yes, you can close it. My app works now how I expect it

**Comment by monsieurtanuki** [comment]
That's good news!
