### ISSUE TITLE
OSMMapTile error

### ISSUE THREAD

**Issue by letanloc1998** [osmdroid/osmdroid#1537]
Please note: issues related to or caused by osmbonuspack will be closed with a
suggestion to open an issue at https://github.com/MKergall/osmbonuspack

(feel free to delete whatever doesn't apply)

## Issue Type

[ ] Question
[*] Bug
[ ] Improvement
[ ] Build system related
[ ] Performance
[ ] Documentation

## Description and/or steps/code to reproduce the problem

Using OSMMapTile I receive this error when run: .\OSMMapTilePackager -t Mapnik -d TramChim.zip -zmax 22 -n 10.80859 -s 10.63318 -e 105.68081 -w 105.40752  -u http://c.tile.openstreetmap.org/%d/%d/%d.png

.Error downloading: 'z=2 x=3 y=1' from URL: http://b.tile.openstreetmap.org/2/3/1.png : java.io.IOException: Server returned HTTP response code: 429 for URL: http://b.tile.openstreetmap.org/2/3/1.png
.Error downloading: 'z=0 x=0 y=0' from URL: http://b.tile.openstreetmap.org/0/0/0.png : java.io.IOException: Server returned HTTP response code: 429 for URL: http://b.tile.openstreetmap.org/0/0/0.png
.Error downloading: 'z=1 x=1 y=0' from URL: http://b.tile.openstreetmap.org/1/1/0.png : java.io.IOException: Server returned HTTP response code: 429 for URL: http://b.tile.openstreetmap.org/1/1/0.png
.Error downloading: 'z=2 x=3 y=1' from URL: http://b.tile.openstreetmap.org/2/3/1.png : java.io.IOException: Server returned HTTP response code: 429 for URL: http://b.tile.openstreetmap.org/2/3/1.png
.Error downloading: 'z=0 x=0 y=0' from URL: http://b.tile.openstreetmap.org/0/0/0.png : java.io.IOException: Server returned HTTP response code: 429 for URL: http://b.tile.openstreetmap.org/0/0/0.png
.Error downloading: 'z=1 x=1 y=0' from URL: http://b.tile.openstreetmap.org/1/1/0.png : java.io.IOException: Server returned HTTP response code: 429 for URL: http://b.tile.openstreetmap.org/1/1/0.png

### If it's a bug, version(s) of android this affects:

All

### Version of osmdroid the issue relates to:

6.1.2

**Comment by monsieurtanuki** [comment]
It's not an osmdroid bug - obviously the problem comes from an intensive use of the server: `Server returned HTTP response code: 429`:
> 429 Too Many Requests (RFC 6585)
The user has sent too many requests in a given amount of time. Intended for use with rate-limiting schemes.[59]

We're not supposed to rely heavily on "MAPNIK".
My suggestions:
* use another tile source
* ask for less tiles
* create your own tiles using OpenStreetMap's metadata

Feel free to reopen if you have good reasons to believe the issue is due to bad design in osmdroid.

**Comment by letanloc1998** [comment]
Thank you
