### ISSUE TITLE
load SHP file with ShapeConverter have no word 

### ISSUE THREAD

**Issue by syau401** [osmdroid/osmdroid#1541]
Please note: issues related to or caused by osmbonuspack will be closed with a
suggestion to open an issue at https://github.com/MKergall/osmbonuspack

(feel free to delete whatever doesn't apply)

## Issue Type

[X ] Question
[X ] Bug
[ ] Improvement
[ ] Build system related
[ ] Performance
[ ] Documentation

## Description and/or steps/code to reproduce the problem
I load SHP file. like this:ShapeConverter.convert(mapView,  shpFile),  but I can't see the words in the Overlay.(I can see point, line and Polygon in the Overlay)

### If it's a bug, version(s) of android this affects:

All

### Version of osmdroid the issue relates to:

6.1.2

**Comment by mat8854** [comment]
@syau401  Could be related to #1518 `ShapeConverter` issues.
