### ISSUE TITLE
Correct license URL in pom

### ISSUE THREAD

**Issue by niknetniko** [osmdroid/osmdroid#1542]
## Issue Type

- [x] Question
- [x] Build system related

## Description and/or steps/code to reproduce the problem

The pom file uses this license blok:
```xml
<license>
      <name>The Apache Software License, Version 2.0</name>
      <url>http://www.apache.org/licenses/</url>
      <distribution>http://www.apache.org/licenses/LICENSE-2.0</distribution>
</license>
```
However, looking at the [docs](http://maven.apache.org/ref/3.5.4/maven-model/maven.html#class_license), the `url` field should actually be `http://www.apache.org/licenses/LICENSE-2.0`, while the `distribution` should probably be `repo`.

(Context: I'm making a Gradle plugin to automatically collect licenses for my project, and osmdroid causes issue, since the url is not a license url.)

Should probably be changed at https://github.com/osmdroid/osmdroid/blob/14b4475a9237b65fd12b82601a6ff699c28ed9ab/gradle.properties#L102-L103

**Comment by spyhunter99** [comment]
thanks for pointing that out. I'll fix it
