### ISSUE TITLE
Osm map is shown below wms tile source URL

### ISSUE THREAD

**Issue by aadit33** [osmdroid/osmdroid#1543]
## Issue Type

[-] Question

## Description and/or steps/code to reproduce the problem

Is there a way to only load WMS layers and not load OSM layers at all. If there is no tile then it must come as transparent on the map screen. Is this possible ?

I have written below code to load wms tilesource

`        setTileSource(TTOSMTileSource(arrayOf(uri)))
`

```
class TTOSMTileSource(
    baseUrl: Array<String>? =null,
    name: String = "WMS_OSM", zoomMinLevel: Int = 5, zoomMaxLevel: Int = 19, tileSizePixels: Int = 256,
    imageFilenameEnding: String = ".png"
) : OnlineTileSourceBase
    (name, zoomMinLevel, zoomMaxLevel, tileSizePixels, imageFilenameEnding, baseUrl) {

    override fun getTileURLString(mapTileIndex: Long): String {
        return baseUrl.replace("{x}", MapTileIndex.getX(mapTileIndex).toString() + "")
            .replace("{y}", MapTileIndex.getY(mapTileIndex).toString() + "")
            .replace("{z}", MapTileIndex.getZoom(mapTileIndex).toString() + "")
    }
}

```
is there something like how google maps does?

`        googleMap.setMapType(GoogleMap.MAP_TYPE_NONE);
`

### Version of osmdroid the issue relates to:
6.1.5

**Comment by monsieurtanuki** [comment]
Quickly said (and maybe a bit wrong):
* [by default](https://github.com/osmdroid/osmdroid/blob/master/osmdroid-android/src/main/java/org/osmdroid/views/MapView.java#L222) your `MapView` uses a `MapTileProviderBasic` as a tile provider - maybe it's too much for you, maybe there are some [unwanted providers](https://github.com/osmdroid/osmdroid/blob/master/osmdroid-android/src/main/java/org/osmdroid/tileprovider/MapTileProviderBasic.java#92) that display the OSM tiles
* I think there's a way to set the "empty" tile as a color or as a bitmap/drawable - you could use `Color.TRANSPARENT` - the default being a grey tile if I remember well
* I'm not sure I see the point of `googleMap.setMapType(GoogleMap.MAP_TYPE_NONE);` - would you tell me in which cases that's relevant?

**Comment by aadit33** [comment]
i have to use this code to change background color while loading wms layer?

`mapview.getOverlayManager().getTilesOverlay().setLoadingBackgroundColor(ContextCompat.getColor(this, R.color.black));`

**Comment by monsieurtanuki** [comment]
Something like that. But `R.color.black` is not `Color.TRANSPARENT` I guess.

**Comment by spyhunter99** [comment]
pretty sure this is addressed, reopen if needed
