### ISSUE TITLE
org.osmdroid.library.R cannot be imported

### ISSUE THREAD

**Issue by pgleska** [osmdroid/osmdroid#1548]
## Issue Type

[ ] Bug
[ ] Build system related

## Description and/or steps/code to reproduce the problem

Hello everyone,

I've got the following issue:

`java.lang.NullPointerException: Attempt to invoke virtual method 'org.osmdroid.views.MapViewRepository org.osmdroid.views.MapView.getRepository()' on a null object reference
        at org.osmdroid.views.overlay.infowindow.InfoWindow.<init>(InfoWindow.java:53)
        at org.osmdroid.views.overlay.infowindow.BasicInfoWindow.<init>(BasicInfoWindow.java:54)
        at org.osmdroid.views.overlay.infowindow.MarkerInfoWindow.<init>(MarkerInfoWindow.java:42)
        at org.osmdroid.views.MapViewRepository.getDefaultMarkerInfoWindow(MapViewRepository.java:54)
        at org.osmdroid.views.overlay.Marker.<init>(Marker.java:115)
        at org.osmdroid.views.overlay.Marker.<init>(Marker.java:92)
        at com.thumbUp.ui.map.ChildFragmentOsmMap.displayMarkers(ChildFragmentOsmMap.java:197)`

in my procedure which is aim to display markers on the map:

`        
        private void displayMarkers(ListMapPointDTO mapPoints) {
            List<Marker> markers = poiMarkers.getItems();
            if (mapPoints.getMapPointDTOList() != null) {
                for (MapPointDTO mapPointDTO : mapPoints.getMapPointDTOList()) {
                    GeoPoint location = new GeoPoint(
                            mapPointDTO.getMapPointLocationModel().getLatitude(),
                            mapPointDTO.getMapPointLocationModel().getLongitude());
                
                boolean exist = false;
                for (Marker existingMarker : markers) {
                    if (existingMarker.getPosition().equals(location)) {
                        exist = true;
                        break;
                    }
                }

                if (!exist) {
                    Marker marker = new Marker(osmMap);

                    marker.setPosition(location);
                    marker.setOnMarkerClickListener((marker1, mapView) -> {
                        Bundle bundle = new Bundle();
                        bundle.putString("id", mapPointDTO.getMapPointLocationModel().getMapPointId());
                        Navigation.findNavController(getActivity(), R.id.nav_host_fragment).navigate(R.id.nav_point_details, bundle);
                        return true;
                    });
                    marker.setAnchor(Marker.ANCHOR_CENTER, Marker.ANCHOR_BOTTOM);
                    poiMarkers.add(marker);
                }
            }
        }

        poiMarkers.invalidate();
    }`

After my inspection it appeared that Android Studio cannot resolved R in org.osmdroid.library.R in class MapViewRepository.java at org.osmdroid.views.MapViewRepository.getDefaultMarkerInfoWindow(MapViewRepository.java:54)

### If it's a bug, version(s) of android this affects:

All

### Version of osmdroid the issue relates to:

6.1.5

Could you give me any advice how to resolve it?

Thank you in advance

**Comment by pasniak** [comment]
Do you always get it?

For me it is an intermittent (rare) error on which I spent puzzling quite some time very recently... I blamed my order of creation (in onCreate of my activity) of mapview and its overlay (with the markers). 

But the error reappeared in my testing.  It is occurring usually on switching out off my activity.

**Comment by monsieurtanuki** [comment]
It rather looks like you create infowindows with a `null` `MapView`:

`java.lang.NullPointerException: Attempt to invoke virtual method 'org.osmdroid.views.MapViewRepository org.osmdroid.views.MapView.getRepository()' on a null object reference`
* null MapView


`at org.osmdroid.views.overlay.infowindow.InfoWindow.<init>(InfoWindow.java:53)`
````java
mMapView.getRepository().add(this);
````
* in the constructor of `InfoWindow`

Why does this happen?...

**Comment by pgleska** [comment]
Well, finally I've found the reason. The layout which implies also the fragment class connected to it were changed before creating markes on the map. So it caused NullPointerException due to MapView didn't exist in a new View. Just a mistake in a program's logic.

Thank you for your help.
