### ISSUE TITLE
Advanced ColorMappingVariation should be able to reflect dynamic scalar range changes

### ISSUE THREAD

**Issue by tvaknin** [osmdroid/osmdroid#1551]
## Issue Type
[ ] Bug
[ ] Improvement

## Description and/or steps/code to reproduce the problem

I found that for small differences between the input scalars values there is a problem to reflect color differences, due to rounding of values.

Code Example:

float minfl =6613.0f ;
float maxfl = 6666.0f;

AdvancedPolylineExample PolyLine = (new AdvancedPolylineExample(mapView,"Test", "Title",
                    new ColorMappingVariationHue(minfl, maxfl, 0.0f, 360.0f, 1.0f, 0.5f),
                    false, Color.BLACK, false,
                    geoTemp, scalarArr));

Color results for the following scalars:

scalar 6613.0
mapping color-65536

scalar 6614.0
mapping color-**16777216**

scalar 6616.0 
mapping color-**16777216** (**Same Number as 6614**)

scalar 6618.0
mapping color-16777216

scalar 6621.0
mapping color-16777216

scalar 6621.0
mapping color-16777216

scalar 6623.0
mapping color-16777216

scalar 6626.0
mapping color-16777216

scalar 6629.0
mapping color-16777216

scalar 6631.0
mapping color-16777216

scalar 6634.0
mapping color-16777216

scalar 6637.0
mapping color-16777216

scalar 6639.0
mapping color-16777216

scalar 6642.0
mapping color-16777216

scalar 6649.0
mapping color-16777216

scalar 6654.0
mapping color-16777216

scalar 6656.0
mapping color-16777216

scalar 6662.0
mapping color-16777216

scalar 6666.0
mapping color-65536

scalar 6666.0
mapping color-65536

scalar 6666.0
mapping color-65536

Please let me know if you need more details.

### Version of osmdroid the issue relates to:
6.1.6

**Comment by tvaknin** [comment]
If think it was my implementation issue.

**Comment by tvaknin** [comment]
Sorry I think it's a real bug. When I try to repaint the line with new scalarStart and ScalarEnd the mentioned problem occurs.

**Comment by monsieurtanuki** [comment]
@tvaknin First, I'm glad you're using this brand new feature!

About the issue, in the OP you used the following code:
````java
new ColorMappingVariationHue(6613.0f, 6666.0f, 0.0f, 360.0f, 1.0f, 0.5f),
````
It means that you expect the following matches:
* 6613.0f => HSL(0.0f, 100%, 50%)
* 6639.5f => HSL(180.0f, 100%, 50%)
* 6666.0f => HSL(360.0f, 100%, 50%)

Am I correct so far?
In your latest post you talk about "repaint" and "new" scalar start and end: could you be more specific about it?

**Comment by tvaknin** [comment]
Hi,

First, It's a great feature!
It's works perfectly when you set the only once the Start scalar and End scalar.

My Use case is that I don't know before I start recording a trip what will be the range values of the scalars.

Therefore, I insert a wide range before. For example from -200m to 1600m [Altitudes].
At the end of the record I want to repaint with the updated range, on my example the updated range is 6613.0f to  6666.0f. 
So I create new PolyLine as above code with the updated range.

Now I expect to see all colors in the range 0-360 as you mentioned, relative to the recorded values.
But, in practice, I got wrong values as in the first post.

Screen shot of successful results when you insert the correct values before. 

![device-2020-04-13-213844](https://user-images.githubusercontent.com/43453293/80134719-d3f06080-85a7-11ea-871f-84b2772bfb74.png)

**Comment by monsieurtanuki** [comment]
@mat8854 invented those new features and deserves a pat on the back ;)

@tvaknin Basically, you say that things are not OK when you change an existing correct situation (Polyline, altitude range, color range). What do you change, and how? (some code please)

**Comment by mat8854** [comment]
@tvaknin @monsieurtanuki Good, right now you have to know your mapping range in advance.

I think there was an invalidateMapping() or similiar function in the initial PR last year. It was meant for recording speed and invalidate the mapping for new top speed (I wanted to use it for that). It was dropped during the refactoring and so on.

In the current code this invalidation is not possible because the scalars are not saved. The mapping is calculated once if I remember correctly.

**Comment by tvaknin** [comment]
Hi @mat8854 

I saved all records, then, "repaint"
Please see the attached example code.

[repaint.txt](https://github.com/osmdroid/osmdroid/files/4524623/repaint.txt)

**Comment by monsieurtanuki** [comment]
@tvaknin @mat8854 So it's a typical use case to compute on the fly the start and end values of the scalar range (e.g. the min and max values of the added scalars), am I right? If so there may be little evolutions needed for `ColorMappingForScalar`.

**Comment by tvaknin** [comment]
@monsieurtanuki 
Yes, the best will be if ColorMappingForScalar will be able to get new start and end values.

**Comment by monsieurtanuki** [comment]
Working on it...

**Comment by monsieurtanuki** [comment]
I coded something that works, at least in the way I understand things.
Basically I created a new class called `ColorMappingForScalarContainer`.
Following is a little demo:
````java
private void demo() {
  final float scalarStart = 0; // first start value, very large, we don't know where we're going
  final float scalarEnd = 1000; // first end value, very large, we don't know where we're going
  final float hueStart = 0;
  final float hueEnd = 100; // in order to mock up a percentage
  final float saturation = 1; // in the context of the demo we don't really use it
  final float luminance = .5f; // in the context of the demo we don't really use it
  final ColorMappingVariationHue mapping = new ColorMappingVariationHue(
      scalarStart, scalarEnd, hueStart, hueEnd, saturation, luminance);
  final ColorMappingForScalarContainer container = new ColorMappingForScalarContainer(mapping);

  final float[] demoValues = { // obviously from 400 to 500, step by step
      412, 405, 400, 420, 440, 460, 455, 500,
  };
  int step = 0;
  for (final float demoValue : demoValues) { // once in a while we get new values (like a new GeoPoint)
    step ++;
    container.add(demoValue);
    final float min = container.getScalarMin();
    final float max = container.getScalarMax();
    if (min != max) { // if we have at least 2 different scalars we can compute a more relevant range
      mapping.init(min, max, hueStart, hueEnd);
      container.refresh();
    }
    for (int i = 0; i < container.size(); i++) {
      Log.e("step#" + step, "color#" + i + "=" + container.getColorForIndex(i));
    }
  }
}
````

And here are the results (as a percentage of the min/max values instead of a color):
```
step#1: color#0=41

step#2: color#0=100
step#2: color#1=0

step#3: color#0=100
step#3: color#1=42
step#3: color#2=0

step#4: color#0=60
step#4: color#1=25
step#4: color#2=0
step#4: color#3=100

step#5: color#0=30
step#5: color#1=13
step#5: color#2=0
step#5: color#3=50
step#5: color#4=100

step#6: color#0=20
step#6: color#1=8
step#6: color#2=0
step#6: color#3=33
step#6: color#4=67
step#6: color#5=100

step#7: color#0=20
step#7: color#1=8
step#7: color#2=0
step#7: color#3=33
step#7: color#4=67
step#7: color#5=100
step#7: color#6=92

step#8: color#0=12
step#8: color#1=5
step#8: color#2=0
step#8: color#3=20
step#8: color#4=40
step#8: color#5=60
step#8: color#6=55
step#8: color#7=100
```

@mat8854 @tvaknin Would this work as you want it to?

**Comment by tvaknin** [comment]
@monsieurtanuki 

It's looks good. 
As I understand, we should call the following code every time we want update the color lines?: 

  final float[] demoValues = { // obviously from 400 to 500, step by step
      412, 405, 400, 420, 440, 460, 455, 500,
  };
  int step = 0;
  for (final float demoValue : demoValues) { // once in a while we get new values (like a new GeoPoint)
    step ++;
    container.add(demoValue);
    final float min = container.getScalarMin();
    final float max = container.getScalarMax();
    if (min != max) { // if we have at least 2 different scalars we can compute a more relevant range
      mapping.init(min, max, hueStart, hueEnd);
      container.refresh();
    }
    for (int i = 0; i < container.size(); i++) {
      Log.e("step#" + step, "color#" + i + "=" + container.getColorForIndex(i));
    }

In addition, you added new method for ColorMappingVariationHue - init()?

**Comment by monsieurtanuki** [comment]
> It's looks good.

Perfect!

> As I understand, we should call the following code every time we want update the color lines?

* each time you want to add a scalar, you - erm - add a scalar (to the "container")
* each time you feel it's appropriate to refresh the scalar range x the hue range, you call `init` (that recomputes the conversion parameters) and `refresh` (that recomputes all the colors from all the scalars according to the new conversion parameters)

> In addition, you added new method for ColorMappingVariationHue - init()?

`init` already exists.

**Comment by mat8854** [comment]
@monsieurtanuki If you push your code on a PR I will try it myself next week.

**Comment by monsieurtanuki** [comment]
@mat8854 @tvaknin I've just PR'ed #1563

For the record:
* I could not test my code on osmdroid because of #1560
* there are slight changes from what I wrote this morning
  * `ColorMappingForScalarContainer` does not implement `ColorMapping` anymore
  * therefore there is not `getColorForIndex(int)` method
  * if you want to get the colors - and I assume you do - you need to use `getColorForIndex(int)` of the inner color mapping class (in the context of the demo, our `ColorMappingVariationHue`), either by keeping the created object or by calling `ColorMappingForScalarContainer.getMappingForScalar()`

**Comment by monsieurtanuki** [comment]
@tvaknin Is it ok for you to close the issue now?

**Comment by tvaknin** [comment]
For some reason I didn't see notifications on github, I didn't see you reply.
Yes, the solution is great.
Thanks.
