### ISSUE TITLE
Map stuck when drawing 1000 polygone in the map.

### ISSUE THREAD

**Issue by GohelAshok701** [osmdroid/osmdroid#1557]
Please note: issues related to or caused by osmbonuspack will be closed with a
suggestion to open an issue at https://github.com/MKergall/osmbonuspack

(feel free to delete whatever doesn't apply)

## Issue Type

[ ] Question
[ ] Bug
[ ] Improvement
[ ] Build system related
[ ] Performance
[ ] Documentation

### If it's a bug, version(s) of android this affects:

All

### Version of osmdroid the issue relates to:

6.1.2

**Comment by monsieurtanuki** [comment]
@GohelAshok701 I suggest you switch to the latest version of osmdroid (6.1.6) which includes tremendous improvements regarding polygon display performances.

**Comment by GohelAshok701** [comment]
Thanks for your replay.

I'm facing the tile loading issue.

can you please help me?

**Comment by GohelAshok701** [comment]
I have many modifications to the library.

can you please tell me the major changed file?

Thanks

**Comment by monsieurtanuki** [comment]
@GohelAshok701 If you have developed modifications to the library that you think would be useful for other developers, don't be shy, create pull requests for each improvement or bug fix.

The main class for polygons is [`PolyOverlayWithIW`](https://github.com/osmdroid/osmdroid/blob/master/osmdroid-android/src/main/java/org/osmdroid/views/overlay/PolyOverlayWithIW.java), but it's probably going to be painful to reconciliate your code and the latest osmdroid code. Nobody can help you with that. Good luck!

**Comment by GohelAshok701** [comment]
@monsieurtanuki 

Thanks for your response.
