### ISSUE TITLE
null pointer exception on scroll

### ISSUE THREAD

**Issue by fokin33** [osmdroid/osmdroid#1558]
I used on old versions:
public void onResume(){
  wrappedListener = new MapListener()
                    {
                        @Override
                        public boolean onScroll(ScrollEvent scrollEvent)
....
mMapView.setMapListener(wrappedListener);

public void onPause(){
mMapView.setMapListener(null);

But after update to last version, get :
Version: 2.6.4 (610)
Thread[main,5,main]
Exception: java.lang.NullPointerException
Message: Attempt to invoke interface method 'boolean org.osmdroid.events.MapListener.onScroll(org.osmdroid.events.ScrollEvent)' on a null object reference
Stacktrace:
	org.osmdroid.views.MapView.setExpectedCenter(MapView.java:1822)
	org.osmdroid.views.MapView.setExpectedCenter(MapView.java:1832)
	org.osmdroid.views.MapController$MapAnimatorListener.onAnimationUpdate(MapController.java:536)
	android.animation.ValueAnimator.animateValue(ValueAnimator.java:1558)
	android.animation.ValueAnimator.animateBasedOnTime(ValueAnimator.java:1349)
	android.animation.ValueAnimator.doAnimationFrame(ValueAnimator.java:1481)
	android.animation.AnimationHandler.doAnimationFrame(AnimationHandler.java:146)
	android.animation.AnimationHandler.access$100(AnimationHandler.java:37)
	android.animation.AnimationHandler$1.doFrame(AnimationHandler.java:54)
	android.view.Choreographer$CallbackRecord.run(Choreographer.java:1055)
	android.view.Choreographer.doCallbacks(Choreographer.java:875)
	android.view.Choreographer.doFrame(Choreographer.java:772)
	android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1042)
	android.os.Handler.handleCallback(Handler.java:888)
	android.os.Handler.dispatchMessage(Handler.java:100)
	android.os.Looper.loop(Looper.java:213)
	android.app.ActivityThread.main(ActivityThread.java:8147)
	java.lang.reflect.Method.invoke(Native Method)
	com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
	com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)

Whats i doing wrong ?
Sorry for my english

**Comment by monsieurtanuki** [comment]
@fokin33 Obviously the problem comes from your `mMapView.setMapListener(null)` (deprecated 2 years ago).
If you really want to remove the listener in `onPause`, use `mMapView.removeMapListener` instead.
Tell me if it works.

**Comment by fokin33** [comment]
Thank you? it is ok now!
