### ISSUE TITLE
unable to resolve class org.gradle.api.internal.ClosureBackedAction

### ISSUE THREAD

**Issue by aamir-github** [osmdroid/osmdroid#1559]
While following the "Advance tutorial section" of osmdroid there is a line "The best example of how to use the osmdroid library is our OpenStreetMapViewer sample project, 
https://github.com/osmdroid/osmdroid/tree/master/OpenStreetMapViewer
but unable to open the "OpenStreetMapViewer" sample project in the android studio. Error faced during opening the project in the android studio is 
"unable to resolve class org.gradle.api.internal.ClosureBackedAction".
Same is the case with the parent library osmdroid-master. 

## Issue Type
[ ] Bug

**Comment by monsieurtanuki** [comment]
@aamir-github I know that I have (perhaps) related problems with osmdroid sample app on Android Studio 3.6.3.
It works OK on 3.5.3 though.
I've just retried on 3.6.3 and got the following error when trying to run (Shift-F10):
````
Unable to determine application id: com.android.tools.idea.run.ApkProvisionException: No outputs for the main artifact of variant: debug
````

Maybe it's not 100% related to your issue, but I think there's something around the build process that doesn't go well with the new Android Studio 3.6.x. And I have no idea on how to fix that, as I don't understand anything about the build process.

**Comment by aamir-github** [comment]
@monsieurtanuki the Android Studio currently I am using is "3.5.2"

**Comment by monsieurtanuki** [comment]
@aamir-github Then it's something else... Or an issue with the version of gradle? As I said, I don't know much about builds. But I know that I had no problem with AS 3.5.2 - except that I was maybe cautious with the gradle upgrades suggested by AS.

**Comment by spyhunter99** [comment]
should be fixed now
