### ISSUE TITLE
Cannot run demo app with Android Studio 3.6.3

### ISSUE THREAD

**Issue by monsieurtanuki** [osmdroid/osmdroid#1560]
## Issue Type

- [x] Bug
- [x] Build system related

## Description and/or steps/code to reproduce the problem

I had no problem with Android Studio 3.5.3.
When I upgraded to AS 3.6.3, I could not run the demo app anymore.
(same problem with other 3.6.x versions)
I have the following message in the Run tab:
````
04/24 08:56:17: Launching 'OpenStreetMapViewer' on samsung SM-G360F.
Unable to determine application id: com.android.tools.idea.run.ApkProvisionException: No outputs for the main artifact of variant: debug
````

I tried to upgrade the gradle version as suggested by AS:

> To take advantage of the latest features, improvements, and security fixes, we strongly recommend that you update the Android Gradle plugin from the current version 2.2.0 to version 3.6.3 and Gradle to version 5.6.4. Release notes  Android plugin 3.2.0 and higher now support building the Android App Bundle—a new upload format that defers APK generation and signing to compatible app stores, such as Google Play. With app bundles, you no longer have to build, sign, and manage multiple APKs, and users get smaller, more optimized downloads. [Learn more](http://d.android.com/r/studio-ui/dynamic-delivery/overview)

But then I had other problems.

**Comment by spyhunter99** [comment]
So more specifically, you can no longer build the demo app using android studio because of an update you chose to install and/or changes you made. The demo app, downloaded off the play store probably works just fine.

Assuming you are trying to build osmdroid from source....first off, you should probably reset the repo if you did make changes.

    git reset --hard

    gradlew clean install

And if you "imported" osmdroid source into your android studio project, that's on you. I'm not sure who keeps promoting this practice but it should stop. 

I hate everything related to android development.  Build reproducibility is poor at best

**Comment by monsieurtanuki** [comment]
Unfortunately I still have the same error message after the git&gradle commands.
````
04/25 18:12:16: Launching 'OpenStreetMapViewer' on samsung SM-G360F.
Unable to determine application id: com.android.tools.idea.run.ApkProvisionException: No outputs for the main artifact of variant: debug
Timed out waiting for process (org.osmdroid) to appear on samsung-sm_g360f-5545b037.
````

Obviously I'm not the only one with an issue switching from AS 3.5.x to 3.6.x. (not specifically for osmdroid):
* https://stackoverflow.com/questions/60484690/android-studio-3-6-issue-apkprovisionexception-no-outputs-for-the-main-artifa
* https://stackoverflow.com/questions/60417572/apkprovisionexception-after-upgrading-to-android-studio-3-6
* https://stackoverflow.com/questions/60493101/unable-to-determine-application-id-com-android-tools-idea-run-apkprovisionexcep
* https://stackoverflow.com/questions/60411205/project-with-external-module-issue-in-android-studio-3-6

But with my very limited understanding of the build process, that doesn't help.

**Comment by spyhunter99** [comment]
does this work for you?

compile via command line `gradle build`
install app via command line `adb install adb install OpenStreetMapViewer\build\outputs\apk\OpenStreetMapViewer-6.1.7-SNAPSHOT-debug.apk`
launch app on device
attach debugger via android studio. It's run > Attach debugger to android process

**Comment by spyhunter99** [comment]
by the way, what problem are you trying to solve?

**Comment by spyhunter99** [comment]
OK so i just upgraded. Pro tip, don't upgrade AS until this is resolved.

**Comment by spyhunter99** [comment]
https://developer.android.com/studio/archive
3.5.3 works, i'd recommend getting that version to solve whatever problem is it you are trying to do.

i'm willing to bet AS is doing something funky and trying to detect something from our build script, which is out of the ordinary and it's screwing up somewhere which causes the process automation to fail.

**Comment by monsieurtanuki** [comment]
I had to switch to MacBook Pro and AS 4.
Doesn't work either, with this message:
```
Server returned HTTP response code: 403 for URL: http://services.gradle.org/distributions/gradle-2.14-bin.zip
```

**Comment by spyhunter99** [comment]
Try https

**Comment by monsieurtanuki** [comment]
@spyhunter99 Thanks, https was indeed useful, but now I'm stuck with
```
failed to find target with hash string 'Google Inc.:Google APIs:23' in: /Users/zzzz/Library/Android/sdk
```

**Comment by spyhunter99** [comment]
should be fixed now
