### ISSUE TITLE
NullPointerException with Bing

### ISSUE THREAD

**Issue by fokin33** [osmdroid/osmdroid#1567]
## Issue Type
[ ] Bug

## Description and/or steps/code to reproduce the problem
With 6.1.7-SNAPSHOT i get exception after resuming activity with MapFragment
Thread[GarbageCollector,1,main]
Exception: java.lang.NullPointerException
Message: format == null
Stacktrace:
	java.lang.String.format(String.java:1550)
	java.lang.String.format(String.java:1528)
org.osmdroid.tileprovider.tilesource.bing.BingMapTileSource.getTileURLString(BingMapTileSource.java:124)
org.osmdroid.tileprovider.modules.MapTileDownloader$TileLoader.loadTile(MapTileDownloader.java:223)
org.osmdroid.tileprovider.modules.MapTileModuleProviderBase$TileLoader.loadTileIfReachable(MapTileModuleProviderBase.java:214)
	org.osmdroid.tileprovider.MapTilePreCache.search(MapTilePreCache.java:125)
	org.osmdroid.tileprovider.MapTilePreCache.access$100(MapTilePreCache.java:30)
	org.osmdroid.tileprovider.MapTilePreCache$1.run(MapTilePreCache.java:41)
	org.osmdroid.util.GarbageCollector$1.run(GarbageCollector.java:31)
	java.lang.Thread.run(Thread.java:818)

### Version of osmdroid the issue relates to:
6.1.7-SNAPSHOT

**Comment by monsieurtanuki** [comment]
@fokin33 Looking at the code that shouldn't be related specifically to 6.1.7.
Do you use `BingMapTileSource.setStyle(String)`?

**Comment by fokin33** [comment]
Yes.
Using 
 bingTileSource.setStyle(BingMapTileSource.IMAGERYSET_AERIAL);
and 
 bingTileSource.setStyle(BingMapTileSource.IMAGERYSET_AERIALWITHLABELS);
in my code

**Comment by monsieurtanuki** [comment]
@fokin33 
* Does it crash for all styles?
* Does it ring any bell to you if I say that the "styles" that crash don't have "subdomains"?
* I found something fishy in the [code](https://github.com/osmdroid/osmdroid/blob/master/osmdroid-android/src/main/java/org/osmdroid/tileprovider/tilesource/bing/BingMapTileSource.java#L305) - if the current style does not have subdomains, the URL is not refreshed (and remains `null`)
* you should see in the logs (level `d`) two message lines for `OsmDroid`
  * `updated url = ` (something, or surely `null` in your case)
  * `end updateBaseUrl`

Disclaimer: I don't know anything about Bing.

**Comment by fokin33** [comment]
As I understand it, the situation was caused by the fact that dev.virtualearth.net for some reason sometimes does not return "imageUrlSubdomains": ["t0", "t1", "t2", "t3"]
 in the request to client = (HttpURLConnection) (new URL (String.format (BASE_URL_PATTERN, mStyle, mBingMapKey)). openConnection ()) ;. It is better of course to secure itself from this in any way.

**Comment by monsieurtanuki** [comment]
@fokin33 But without the available subdomains being provided, how can we deduce the correct URL?

**Comment by fokin33** [comment]
I meant that this situation should not cause the application to crash. Or is it better to try to handle an exception in the app ? Actually, I'm not sure which is better.

**Comment by monsieurtanuki** [comment]
@fokin33 Maybe it should not crash (or with a better error message). If so, what shall we do when the subdomains are not provided: how do we compute the URL without the subdomains? On this virtualearth server, what do they say we can do if no subdomains are provided? Is there a "www"-like subdomain that always works?

**Comment by fokin33** [comment]
This was because the BingMapTileSource.retrieveBingKey(global Activity) method was not always called before displaying the map on the screen.
