### ISSUE TITLE
Proguard warnings because of FloatMath class.

### ISSUE THREAD

**Issue by rsavin** [osmdroid/osmdroid#158]
Hi. You use FloatMath class in CompassOverlay and MyLocationNewOverlay classes. FloatMath  was deprecated in API level 22. Everything was ok with compileSdkVersion 22. But with version 23 I get the following proguard warnings:
```
Warning: org.osmdroid.views.overlay.compass.CompassOverlay: can't find referenced method 'float ceil(float)' in library class android.util.FloatMath
Warning: org.osmdroid.views.overlay.mylocation.MyLocationNewOverlay: can't find referenced method 'float ceil(float)' in library class android.util.FloatMath
```

**Comment by DShamaev** [comment]
Someone please merge these urgent changes, because projects for android 6 won't compile at all. I don't want to suppress these warning from compiler

**Comment by neilboyd** [comment]
I would be keener to merge it if there was only one commit and there were tests that ensure there are no rounding errors. Otherwise I have to do that myself.

**Comment by spyhunter99** [comment]
Compass and MyLocation overlays are hardly show stoppers if it's off, even by a litttle

**Comment by spyhunter99** [comment]
still present for CompassOverlay and MyLocationNewOverlay classes

**Comment by spyhunter99** [comment]
this isn't the only issue, apache http client was removed from android 6, requiring an additional "legacy" library

**Comment by neilboyd** [comment]
See also:
[issue 200](https://code.google.com/p/osmdroid/issues/detail?id=200)
[issue 212](https://code.google.com/p/osmdroid/issues/detail?id=212)
[issue 273](https://code.google.com/p/osmdroid/issues/detail?id=273)
[revision 960](https://code.google.com/p/osmdroid/source/detail?r=960)
commit 405fd87
