### ISSUE TITLE
How to download tiles permanentely inside osm android ?? 

### ISSUE THREAD

**Issue by jesuvijay** [osmdroid/osmdroid#1582]
Please note: issues related to or caused by osmbonuspack will be closed with a
suggestion to open an issue at https://github.com/MKergall/osmbonuspack

(feel free to delete whatever doesn't apply)

## Issue Type

[ ] Question
[ ] Bug
[ ] Improvement
[ ] Build system related
[ ] Performance
[ ] Documentation

[Style edited]
I am using bing maps in osmdroid for satellite view. I need to download tiles for offline use but by using cache manager i am able to download tiles . cache tiles are expiring . so how to overcome and how to use tiles writer for permanent cache data. sample code plz

### If it's a bug, version(s) of android this affects:

All

### Version of osmdroid the issue relates to:

6.1.2

**Comment by monsieurtanuki** [comment]
@jesuvijay A possible idea would be to override each tile cache expiration date. I think there's something like that in `DefaultConfigurationManager`, like `setExpirationBlablabla`.
If you add 10 years to the actual tile cache expiration datetime, you should be OK for the next 10 years.
In that case you would have to re-download the tiles once (where they'll have their expiration date overridden).

**Comment by jesuvijay** [comment]
Thank u  tanuki...:)

**Comment by jesuvijay** [comment]
let me check and get back to u

**Comment by spyhunter99** [comment]
Use the cache manager, it can produce non expiring archives

**Comment by jesuvijay** [comment]
how to create non expiring archives. example plz and also how to sync this archive with online in BIng map tiles source??

I tried sqltilewriter to cache data as archive. but by using offline tile source i can show the archive data on mapview.. how to combine it with bing tiles source ??

**Comment by jesuvijay** [comment]
how to use tile writer? no example in github .. can  u provide ideas??

**Comment by spyhunter99** [comment]
https://github.com/osmdroid/osmdroid/wiki/Cache-Manager
that's the wiki article describing how it works.

example usage
https://github.com/osmdroid/osmdroid/blob/master/OpenStreetMapViewer/src/main/java/org/osmdroid/samplefragments/cache/SampleCacheDownloader.java#L214

**Comment by jesuvijay** [comment]
so, by using cache manager,downloaded data cannot be expired . But the document says 30 days default. How to change to get permanaent?. how to add multiple cache files load from sd card ??

**Comment by jesuvijay** [comment]
Hi by using cache manager i created archive.sqlite file is it expired after 30 days ??? or is it permanent.

**Comment by spyhunter99** [comment]
i guess you found the other example here:
https://github.com/osmdroid/osmdroid/blob/master/OpenStreetMapViewer/src/main/java/org/osmdroid/samplefragments/cache/SampleCacheDownloaderArchive.java

You can view a demo on the sample app on the play store. good luck and don't get banned
