### ISSUE TITLE
Gradle issue

### ISSUE THREAD

**Issue by GohelAshok701** [osmdroid/osmdroid#1584]
Configuration on demand is an incubating feature.

FAILURE: Build failed with an exception.

* Where:
Script 'https://raw.githubusercontent.com/gradle-fury/gradle-fury/v1.1.4/gradle/maven-support.gradle' line: 1453

* What went wrong:
Could not compile script 'https://raw.githubusercontent.com/gradle-fury/gradle-fury/v1.1.4/gradle/maven-support.gradle'.
> startup failed:
  script 'https://raw.githubusercontent.com/gradle-fury/gradle-fury/v1.1.4/gradle/maven-support.gradle': 1453: unable to resolve class org.gradle.api.internal.ClosureBackedAction 
   @ line 1453, column 13.
                 new org.gradle.api.internal.ClosureBackedAction({
                 ^
  
  1 error

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s

**Comment by GohelAshok701** [comment]
Can you please help me?

**Comment by GohelAshok701** [comment]
![build verient](https://user-images.githubusercontent.com/30015482/81805222-10c0cf00-9538-11ea-8709-14073e2548a1.PNG)

Unable to determine application id: com.android.tools.idea.run.ApkProvisionException: No outputs for the main artifact of variant: debug

**Comment by GohelAshok701** [comment]
@monsieurtanuki 

Any update??

**Comment by monsieurtanuki** [comment]
maybe same as #1560.
try with Android Studio 3.5.3.

**Comment by GohelAshok701** [comment]
Thank you so much :)
