### ISSUE TITLE
Marker icons disappear on zoom out and pan 

### ISSUE THREAD

**Issue by frank702** [osmdroid/osmdroid#1585]
## Issue Type
[ -] Bug

## Description and/or steps/code to reproduce the problem
After adding a few markers with icon drawable, some of the icons disappear on zooming out or panning.
May also happen that the icon keeps visible at any zoom level, but its InfoWindow stays hidden until zoomed in.

This seems very similar to issue #1544, which seems having been closed with version 6.1.6, but nonetheless I'm experiencing it on 6.1.6. May be relevant: here the map is contained into a Fragment.

Code for drawing markers:
```
        Marker m = new Marker(map);
        m.setId(_place._id.toString());
        m.setIcon(new BitmapDrawable(map.getContext().getResources(), placeIcons.get(_place.icon)));
        m.setPosition(new GeoPoint(_place._lat, _place._long));
        m.setVisible(true);
        map.getOverlays().add(m);
```
A sample video:
https://drive.google.com/open?id=1fveyMPjRWXhsHVGuS6kKJd9rZ7oJTCzM

### Version of osmdroid the issue relates to:

6.1.6

**Comment by monsieurtanuki** [comment]
@frank702 You're right, it looks similar to #1544.

For performance reasons, for each draw, we assess if each Overlay should be displayed, by comparing its geo position (and therefore its pixel position) and its size versus the position of the map and its size. If those positions+size don't match, we don't display the Overlay (cf. [code](https://github.com/osmdroid/osmdroid/blob/master/osmdroid-android/src/main/java/org/osmdroid/views/overlay/Marker.java#L520)).

And obviously something's going wrong for you.
I suggest that you extend Marker, play with method `drawAt` (remove the `mDisplayed` test, add some `Log`, ...) , to understand what's going on: I believe that that's where the problem is (but I don't know what it is).

PS: I never understood the point of `Fragment`s, but that's another story.

**Comment by spyhunter99** [comment]
Thanks for the video. This is pretty strange but it may be related to some work i did on the overlay manager which checks to see if the bounds of the overlay overlap with the current map view. hmmm

**Comment by frank702** [comment]
Thank you for both feedbacks.
I'm actually trying debugging along suggestions of @monsieurtanuki, but "unfortunately" the issue is not stable and it's not been showing up in the last couple of days. I'm going to work out the circumstances triggering it, and will provide updates to this thread as soon as possible!

**Comment by monsieurtanuki** [comment]
@frank702 Too bad the issue is not stable!
An additional suggestion: are there places in your code where you redraw only a "dirty" rectangle of the canvas, but not the full canvas?

**Comment by frank702** [comment]
A-ha, got it!
The issue was actually stable, but engaged now and then, according to circumstances in the app logic layer that were hardly visible.
So, this is the point: some markers added to the map were sometimes accidentally mapped to not-existing icon drawables.
Being the icons set into the markers as follows:

`mk.setIcon(new BitmapDrawable(map.getContext().getResources(), faulty_icon));
`

the affected markers showed a not null icon with

`mBitmapWidth = mBitmapHeight = -1
`

The strangely-behaving map areas had one of these faulty markers in proximity, just brought in the scene by a slight zoom-out or pan action.
As soon as those markers got into the canvas, maybe a null-pointer exception prevented drawing them and any further object... et voilà, the reported behaviour!

A quick and dirty fix may consist in checking one of the icon dimensions before accepting it, in the setIcon method.

```
    public void setIcon(final Drawable icon){
        if (icon!=null && icon.getIntrinsicWidth()>-1) {
            mIcon=icon;
        } else {
            setDefaultIcon();
        }
    }

```

Thank you all for your assistance!
frank

**Comment by monsieurtanuki** [comment]
@frank702 I'm glad you solved the issue.
I don't think we should alter anything in osmdroid code, that seems to work OK for `Marker`s created with regular `Drawable`s as icons. Which is the target, isn't it?

Feel free to close the issue.

**Comment by frank702** [comment]
I see your point and agree, @monsieurtanuki!
