### ISSUE TITLE
Fail to Sync Graddle Project

### ISSUE THREAD

**Issue by caBBAlainB** [osmdroid/osmdroid#159]
Hello,
Sorry, but tha's the first time I encounter such error.
Could you please help me to solve this:

    Error:Unable to load class 'org.codehaus.groovy.runtime.StringGroovyMethods'.
	Possible causes for this unexpected error include:<ul><li>You are using JDK version 'java version "1.7.0_79"'. Some versions of JDK 1.7 (e.g. 1.7.0_10) may cause class loading errors in Gradle.
	Please update to a newer version (e.g. 1.7.0_67).
	<a href="open.project.structure">Open JDK Settings</a></li><li>Gradle's dependency cache may be corrupt (this sometimes occurs after a network connection timeout.)
	<a href="syncProject">Re-download dependencies and sync project (requires network)</a></li><li>The state of a Gradle build process (daemon) may be corrupt. Stopping all Gradle daemons may solve this problem.
	<a href="stopGradleDaemons">Stop Gradle build processes (requires restart)</a></li><li>Your project may be using a third-party plugin which is not compatible with the other plugins in the project or the version of Gradle requested by the project.</li></ul>In the case of corrupt Gradle processes, you can also try closing the IDE and then killing all Java processes.

I cannot find org.codehaus anywhere in OpenStreetMapViewer project. Where does it come from??

Thanks a lot.

**Comment by spyhunter99** [comment]
osmdroid uses maven to build. the gradle bits are there to make our lives easier when running with android studio. try building it with maven

**Comment by spyhunter99** [comment]
found the issue, will push a change set to fix in a minute

**Comment by spyhunter99** [comment]
fixed

**Comment by nitinarv** [comment]
Hi Spyhunter99. I am facing the same issue in a project I had imported from github. I would like to know what had you done to resolve this issue.

**Comment by spyhunter99** [comment]
no idea, i didn't tag this issue in a commit nor do i see anything specific in the commit history. try making a new project with android studio, then copying all the imported stuff over

**Comment by nitinarv** [comment]
Oh, That's unfortunate. Thanks anyways.
