### ISSUE TITLE
Labels overlap with Polygone

### ISSUE THREAD

**Issue by GohelAshok701** [osmdroid/osmdroid#1590]
Hello @monsieurtanuki 

I hope you are doing great!.

I wont to display the Labels above the polygon, see attached image.

Is this possible with OSM?

![overlap with polygone](https://user-images.githubusercontent.com/30015482/82179397-dff7e580-98fb-11ea-91fd-779101494a94.PNG)

Thanks for your support.

**Comment by monsieurtanuki** [comment]
@GohelAshok701 The labels you're talking about are part of the map tiles, in the background.
Whatever you draw on top of it is potentially hidden, as in your case.
A solution would be to use an additional tile overlay on top of it, with only the labels. I don't know if such a tile source provider exists.

**Comment by pasniak** [comment]
There are "basemaps without labels" (the keywords I used to find them) in the wild. For example https://help.openstreetmap.org/questions/40664/how-to-hide-all-labels-of-osm. But the TOS might not fit your the use case....

**Comment by GohelAshok701** [comment]
Thanks for your response
