### ISSUE TITLE
Android build tools outdated

### ISSUE THREAD

**Issue by hannesa2** [osmdroid/osmdroid#1593]
I see Android build tools are outdated, currently here it's `2.2.0`, but the world is on `3.6.3`.

so I updated it locally and run into this [gradle-fury](https://github.com/gradle-fury/gradle-fury) which is 4 years old on only support 
![image](https://user-images.githubusercontent.com/3314607/82862412-d97ef480-9f1f-11ea-9d11-12aa3a6d2170.png)

Using such a _helper_ tools is a future blocker to modernize. **Now this repo is in this situation.**

Ok, want to  modernize, remove at least this helper, probable more and simplify build and setup.
Which means it will **change a lot**

But I want to save my time and I'm afraid about a lot of doubt on maintainer side and the pull request will never merged.

So I ask you, what are you thinking about this ?

**Comment by monsieurtanuki** [comment]
@hannesa2 Does it solve #1560 ?

**Comment by hannesa2** [comment]
I made a pull request for it https://github.com/osmdroid/osmdroid/pull/1594

**Comment by hannesa2** [comment]
> @hannesa2 Does it solve #1560 ?

CI builds 
<img width="672" alt="image" src="https://user-images.githubusercontent.com/3314607/82867148-a0984d00-9f2a-11ea-8815-e0883b2df8ec.png">

But this test a questionable (crap) because locally I run currently into 
<img width="1345" alt="image" src="https://user-images.githubusercontent.com/3314607/82867221-bc9bee80-9f2a-11ea-83eb-ccf3faf014ea.png">

**Comment by hannesa2** [comment]
Lint is also in a bad condition

<img width="1100" alt="image" src="https://user-images.githubusercontent.com/3314607/82867358-01c02080-9f2b-11ea-9b5a-e85fe85b3a48.png">

**Comment by hannesa2** [comment]
@monsieurtanuki I guess you are a maintainer. Please allow Github actions to run Gradle verification

<img width="866" alt="image" src="https://user-images.githubusercontent.com/3314607/82867540-58c5f580-9f2b-11ea-8a4b-671d01bd1d97.png">

**Comment by monsieurtanuki** [comment]
@hannesa2 My part in the project is about developing in Java and reviewing code. I have not the slightest idea about anything around gradle and I cannot validate or change parameters I do not understand at all.

I know @spyhunter99 has much clearer ideas about the whole process. If you guys could manage to upgrade and improve the build process, that would be awesome!

**Comment by hannesa2** [comment]
@spyhunter99 
Now I need you review https://github.com/osmdroid/osmdroid/pull/1594 and please enable Github actions

**Comment by spyhunter99** [comment]
i'll look at it tonight.

**Comment by spyhunter99** [comment]
fixed
