### ISSUE TITLE
jitpack.io don't deliver all libraries 

### ISSUE THREAD

**Issue by hannesa2** [osmdroid/osmdroid#1601]
Having a look at osmandorid output at https://jitpack.io/#hannesa2/osmdroid/6.1.6.0

<img width="810" alt="image" src="https://user-images.githubusercontent.com/3314607/85220903-99405400-b3af-11ea-84ba-fce1508c1d09.png">

I see only two libraries are delivered.
But I'm not sure which one are necessary. I guess to use it in https://github.com/MKergall/osmbonuspack will show me the minimum required libs

**Comment by hannesa2** [comment]
I made a pull request for it https://github.com/osmdroid/osmdroid/pull/1602

**Comment by spyhunter99** [comment]
i think we can close this. all the build tech was updated recently. we're still publishing to maven central
