### ISSUE TITLE
FolderOverlay recalculateBounds crashes if empty folder

### ISSUE THREAD

**Issue by MKergall** [osmdroid/osmdroid#1615]
# Issue Type

[X] Bug

## Description and/or steps/code to reproduce the problem
if you remove the latest element from a FolderOverlay: folder.remove(myItem);
you get a crash, because recalculateBounds() tries to build an invalid bounding box. 
Faulty code here: 
mBounds= new BoundingBox(maxLat, maxLon, minLat, minLon);

Since osmdroid 6.1.6

Fix: first of all, test: 

if (mOverlayManager.size() == 0)
  mBounds=null;
else
 ....

**Comment by monsieurtanuki** [comment]
@MKergall It's not that obvious: should it be `null`or the largest bounding box? cf. #1521
Probably with 6.1.6 you don't have #1521's PR merged (#1524), do you?

**Comment by MKergall** [comment]
Effectively: I didn't notice this bug was already raised as 1521. And 1524 is not in 6.1.6. 
I have no workaround for this one. I will wait for 6.1.7 (arriving soon?).

**Comment by MKergall** [comment]
Duplicate with #1521
