### ISSUE TITLE
Android 4.x.x not downloading Titles

### ISSUE THREAD

**Issue by victordiaz** [osmdroid/osmdroid#1617]
## Issue Type
[x] Bug

## Description and/or steps/code to reproduce the problem
Titles are set to MAPNIK.
When trying to render the map I get the following error 

```java.net.ConnectException: failed to connect to b.tile.openstreetmap.org/2a01:4f8:1c1c:bc54::1 (port 443): connect failed: ENETUNREACH (Network is unreachable)```

According to this [https://stackoverflow.com/questions/29916962/javax-net-ssl-sslhandshakeexception-javax-net-ssl-sslprotocolexception-ssl-han/50640113#50640113](https://stackoverflow.com/questions/29916962/javax-net-ssl-sslhandshakeexception-javax-net-ssl-sslprotocolexception-ssl-han/50640113#50640113) is a problem with TSL and Android 4.x.x but I'm not so sure if that's the answer.

## Environment
Device with 4.2 and any emulator using 4.x.x

### If it's a bug, version(s) of android this affects:
4.x.x

### Version of osmdroid the issue relates to:
6.1.6

**Comment by cbalster** [comment]
This was already reported in #1554 and fixed in #1555.
Unfortunately there has been no release since.

**Comment by spyhunter99** [comment]
i can cut a release tonight if you all want

**Comment by cbalster** [comment]
I just revisited this and for some reason it seems to fall back to TLS1 in some cases. I will PR a fix in a second.
@spyhunter99 If you could merge the PR and cut a release that would be great!

**Comment by monsieurtanuki** [comment]
I'm ok with the idea of a new release.

**Comment by victordiaz** [comment]
I just want to confirm that the new release fixed problems with 4.x.x devices in my app [https://phonk.app/](https://phonk.app/)

Thanks!
