### ISSUE TITLE
How to override the http headers sent when requesting a tile

### ISSUE THREAD

**Issue by vvavepacket** [osmdroid/osmdroid#1627]
## Issue Type

[X ] Question
[ ] Bug
[ ] Improvement
[ ] Build system related
[ ] Performance
[ ] Documentation

## Description and/or steps/code to reproduce the problem
Recently I placed the tile server behind a gateway that requires Http Authorization header to be sent always. How do we tell OSM Droid to add the auth header at every request going forward?

### If it's a bug, version(s) of android this affects:

All

### Version of osmdroid the issue relates to:

6.1.2

**Comment by monsieurtanuki** [comment]
@vvavepacket Something like that: https://github.com/osmdroid/osmdroid/blob/master/osmdroid-android/src/main/java/org/osmdroid/tileprovider/modules/TileDownloader.java#L107?

**Comment by vvavepacket** [comment]
How does one override these other than modifying the source files and
recompiling them? Can these be extended without doing the above?

**Comment by monsieurtanuki** [comment]
@vvavepacket If it's only a matter of additional http request properties, then you can implement `IConfigurationProvider` or override `DefaultConfigurationProvider`, and more specifically method `Map<String, String> getAdditionalHttpRequestProperties()`.
You may even not have to override this method, but just add your properties directly using the method.
