### ISSUE TITLE
Crash at app startup

### ISSUE THREAD

**Issue by panovvitalik** [osmdroid/osmdroid#1628]
## Issue Type

[ ] Question
[x] Bug
[ ] Improvement
[ ] Build system related
[ ] Performance
[ ] Documentation

## Description and/or steps/code to reproduce the problem
Yesterday, 7:49 PM on app version 229
Vivo vivo 1920 (1920), 7680MB RAM, Android 9
Report 1 of 1
51 minutes ago on app version 230
Samsung Galaxy A10s (a10s), 1792MB RAM, Android 10
Report 1 of 2

```
java.lang.NullPointerException: 
  at org.osmdroid.config.DefaultConfigurationProvider.load (DefaultConfigurationProvider.java:337)
  at vitalypanov.phototracker.fragment.MapOpenStreetSupportFragment.onCreateView (MapOpenStreetSupportFragment.java:333)
```
Crash occure at starting fragment when I call:
Configuration.getInstance().load(ctx, PreferenceManager.getDefaultSharedPreferences(ctx));

### If it's a bug, version(s) of android this affects:
Android 10.0

### Version of osmdroid the issue relates to:

6.1.8

**Comment by tvaknin** [comment]
@panovvitalik  Every call to Configuration.getInstance() causes a crash on release 6.1.8, for now, I just downgrade to 6.1.6.
Is there any fix?

**Comment by spyhunter99** [comment]
try an older version. there were changes made to the last version related to this that is probably causing this. The initial config setup is a pain to get right for all devices and versions of android

**Comment by spyhunter99** [comment]
well over a year old, not sure if this is still an issue. reopen if needed
