### ISSUE TITLE
Does support 3d map?

### ISSUE THREAD

**Issue by lbb1993** [osmdroid/osmdroid#1629]
Please note: issues related to or caused by osmbonuspack will be closed with a
suggestion to open an issue at https://github.com/MKergall/osmbonuspack

(feel free to delete whatever doesn't apply)

## Issue Type

[ x] Question
[ ] Bug
[ ] Improvement
[ ] Build system related
[ ] Performance
[ ] Documentation

### If it's a bug, version(s) of android this affects:

All

### Version of osmdroid the issue relates to:

6.1.2
Hello,I am a newer to this great library.I want to load some 3d map like Google Earth,Does this libs can support?I will be very happy if someone can answer me .Thank you~

**Comment by monsieurtanuki** [comment]
@lbb1993 I don't think osmdroid supports 3D maps. Basically osmdroid stitches together same sized raster files that have no meta data.

**Comment by lbb1993** [comment]
> @lbb1993 I don't think osmdroid supports 3D maps. Basically osmdroid stitches together same sized raster files that have no meta data.
Thank you sir for your kindful replay.Do you know some other open source libs that can display 3d maps like Google Earth?

**Comment by monsieurtanuki** [comment]
I don't know; I'm not into 3D maps.

**Comment by spyhunter99** [comment]
it does not
