### ISSUE TITLE
Tiles with the same coordinates overwrite each other when using different tileservers

### ISSUE THREAD

**Issue by idaspin** [osmdroid/osmdroid#1630]
## Issue Type

[X] Question

## Description and/or steps/code to reproduce the problem

I use ViewPager where each fragment load tiles from different servers depending on position in the pager.
Final URL looks like "http://tileserver.custommap.online/"+mapname+"/"+mapname+"/{z}/{x}/{y}.png"
As I think MapView download tile 0/0/0.png for Map#1 and when Im trying to open Map#2 it show me preloaded picture for Map#1. 
There is any solution to split tiles from different tileservers?

### Version of osmdroid the issue relates to:

6.1.2

**Comment by idaspin** [comment]
I just tried to configure file name ending from ".png" to "_map"+currentMapID+".png" (pictures name updated on the server) but it doesnot help

**Comment by monsieurtanuki** [comment]
@idaspin If I remember well the tile source name is part of the key, as well as z, x and y (cf. https://github.com/osmdroid/osmdroid/blob/master/osmdroid-android/src/main/java/org/osmdroid/tileprovider/tilesource/TileSourceFactory.java)
If all your tileservers use the same tile source name, overwriting is normal.

**Comment by idaspin** [comment]
@monsieurtanuki 
I use this code
`map.setTileSource(new OnlineTileSourceBase("", 0, 5, 256, ".png",
      new String[] { "http://tileserver.custommap.online/" }) {
      ...
});`
I already tired to replace `ImageFilenameEnding` from `".png"` to `"_map"+id+".png"`. Files names looks like `["0_map1.png", "1_map1.png", "0_map2.png", "1_map2.png"]` on the server. But tiles still overwrites another ones

**Comment by monsieurtanuki** [comment]
I think the tile source name is the first parameter, that you currently set to `""`.
If you use several tile sources, you should use `"tileserver1"`, `"tileserver2"`, ... instead.
We use the actual filename only to match the zoom,x,y parameters, but then we store the file content, not the filename.

**Comment by idaspin** [comment]
Nope. Now I have two subdomains "tileserver.custommap.online" and "tileserver1.custommap.online"
Code looks like: 
`map.setTileSource(new OnlineTileSourceBase("", 0, 5, 256, ".png", new String[] { "http://tileserver.custommap.online/map1/map1/" }) { 
            @Override
            public String getTileURLString(long pMapTileIndex) {
                return getBaseUrl()
                        + MapTileIndex.getZoom(pMapTileIndex)
                        + "/" + MapTileIndex.getX(pMapTileIndex)
                        + "/" + MapTileIndex.getY(pMapTileIndex)
                        + mImageFilenameEnding;
            } });`

`map2.setTileSource(new OnlineTileSourceBase("", 0, 5, 256, ".png", new String[] { "http://tileserver1.custommap.online/map2/map2" }) { 
@Override
            public String getTileURLString(long pMapTileIndex) {
                return getBaseUrl()
                        + MapTileIndex.getZoom(pMapTileIndex)
                        + "/" + MapTileIndex.getX(pMapTileIndex)
                        + "/" + MapTileIndex.getY(pMapTileIndex)
                        + mImageFilenameEnding;
            } });`

Log shows me loading images with correct URL's `http://tileserver.custommap.online/map1/map1/0/0/0.png` and `http://tileserver1.custommap.online/map2/map2/0/0/0.png` at the same time. But tiles still overwrites each other

**Comment by monsieurtanuki** [comment]
@idaspin I meant something like
````
map.setTileSource(new OnlineTileSourceBase("mysource1", 0, 5, 256, ".png", new String[] { "http://tileserver.custommap.online/" }) { ... });
map.setTileSource(new OnlineTileSourceBase("mysource2", 0, 5, 256, ".png", new String[] { "http://tileserver1.custommap.online/" }) { ... });
````

**Comment by idaspin** [comment]
> @idaspin I meant something like
> 
> ```
> map.setTileSource(new OnlineTileSourceBase("mysource1", 0, 5, 256, ".png", new String[] { "http://tileserver.custommap.online/" }) { ... });
> map.setTileSource(new OnlineTileSourceBase("mysource2", 0, 5, 256, ".png", new String[] { "http://tileserver1.custommap.online/" }) { ... });
> ```

Thanks, It works
