### ISSUE TITLE
Mbtiles not working

### ISSUE THREAD

**Issue by AlirezaAsadi96** [osmdroid/osmdroid#1631]
Hi. I'm using osmdroid for display local mbtiles on map. But the result is an empty map!

Here is the mbtiles that I copy to sdcard/osmdroid/Countries.mbtiles:
[Countries.zip](https://github.com/osmdroid/osmdroid/files/5128312/Countries.zip)

And the code is:
` map = (MapView) findViewById(R.id.mapview);`
       ` map.getController().setZoom(5);`
       ` map.setTileSource(new XYTileSource(
                "Countries",
                0,
                6,
                256,
                ".png",
                new String[]{""}
        ));`
The result is:
![osmdroid](https://user-images.githubusercontent.com/29544471/91276409-5fd0ef80-e736-11ea-8359-2818486711df.png)

Please help me

### Version of osmdroid the issue relates to:

6.1.8

**Comment by spyhunter99** [comment]
get the configuration provider getOsmdroidBasePath. the mbtiles database needs to be a folder that osmdroid can find it and read it. the default is /sdcard/osmdroid/.

**Comment by spyhunter99** [comment]
well over a year old, not sure if this is still an issue. reopen if needed

**Comment by CodeK1988** [comment]
@AlirezaAsadi96 @spyhunter99 hi mate, I encountered the same error. Did you solve it?
