### ISSUE TITLE
org.osmdroid.OsmdroidBuildInfo.VERSION returns old version

### ISSUE THREAD

**Issue by mikebravoyes** [osmdroid/osmdroid#1633]
## Issue Type

[x] Bug

## Description and/or steps/code to reproduce the problem

@spyhunter99 
I refer to issue #1500. When I build a new release of my app with the current osmdroid version (6.1.8), the public String variable `org.osmdroid.OsmdroidBuildInfo.VERSION` returns "6.1.7-SNAPSHOT" instead of "6.1.8", as expected.

build.gradle:
```
dependencies {
    ...
    implementation group: 'org.osmdroid', name: 'osmdroid-android', version: '6.1.8'
}

```

java file:
`    String versionName = org.osmdroid.OsmdroidBuildInfo.VERSION;
`

Probably, the class OsmdroidBuildInfo is not generated automatically during the build. The related BUILD_DATE is "Tue Jul 21 20:13:02 EDT 2020", which was one day before the release of version 6.1.7.

### If it's a bug, version(s) of android this affects:

All

### Version of osmdroid the issue relates to:

6.1.8

**Comment by spyhunter99** [comment]
thanks i'll take a look at it

**Comment by spyhunter99** [comment]
gradle was skipping the task since it thought it was up to date. i altered the release procedure to ensure this doesn't happen again.

**Comment by mikebravoyes** [comment]
@spyhunter99 
When will the version 6.19 be released?

**Comment by spyhunter99** [comment]
whenever you all want. this week is possible. i honestly haven't been tracking any osmdroid related issues.

**Comment by monsieurtanuki** [comment]
@spyhunter99 Long time no see
To be honest I didn't track issues, I just replied to the easy ones.
How can I be helpful?
