### ISSUE TITLE
Map freezes when zoomed out extremely

### ISSUE THREAD

**Issue by mikebravoyes** [osmdroid/osmdroid#1634]
## Issue Type

[x] Bug

## Description and/or steps/code to reproduce the problem

@monsieurtanuki 
I refer to issue #1514. Until osmdroid 6.1.6 there was this issue with the lat/lon grid. This problem has gone. But now (6.1.8), the map freezes, when zoomed out extremely.

Old behaviour (version 6.1.6): The map can be zoomed out extremely, showing more than one world - without lat/lon grid.
![Screenshot_20200831-120736](https://user-images.githubusercontent.com/6436590/91711122-a5057f00-eb85-11ea-9edd-3a1d44333efa.jpg)

New behaviour (version 6.1.8): When zooming out, it stops at a certain level. There is only one world (or two?) - with lat/lon grid. But the map freezes, it can't be zoomed in or out any more. Instead of that, the whole app crashes after a few seconds.
![Screenshot_20200831-121028](https://user-images.githubusercontent.com/6436590/91711127-a9319c80-eb85-11ea-972d-d80f28626a81.jpg)

### If it's a bug, version(s) of android this affects:

All

### Version of osmdroid the issue relates to:

6.1.8

**Comment by monsieurtanuki** [comment]
@mikebravoyes Two questions:
* what do the logs say?
* can you display a simple piece of code in order to reproduce that?

**Comment by mikebravoyes** [comment]
@monsieurtanuki 

Concerning the logs: I don't know how to activate log outputs in osmdroid. The hints in [https://github.com/osmdroid/osmdroid/wiki/Debugging-osmdroid](https://github.com/osmdroid/osmdroid/wiki/Debugging-osmdroid) didn't work for me. Anyway, here is an extract of the LogCat output in Android Studio 4.0:
[LogCat.txt](https://github.com/osmdroid/osmdroid/files/5155683/LogCat.txt)
The crash happens after this line (debug output by my app):
`2020-09-01 12:31:20.504 24641-24641/net.braun_home.sensorrecording.pro D/logEntry: text 1;A06;zoomLevel;1.9985590809530827`



And here are the code snippets (simplified) of how I use the osmdroid MapView:

The layout.xml file:
```
<LinearLayout
    android:orientation="vertical"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:id="@+id/linearlayout5a" >

    <org.osmdroid.views.MapView
        android:id="@+id/mapview"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        tilesource="Mapnik"/>	<!-- may be overwritten programmatically in initMap() -->

</LinearLayout>

```

and the activity.java (in onFirstLayout, invoked by onResume):

```
// init map
mapView = (MapView) findViewById(R.id.mapview);
ITileSource iTileSource1 = TileSourceFactory.MAPNIK;
mapView.setTileSource(iTileSource1);

// some settings
mapView.setClickable(true);
mapView.setBuiltInZoomControls(false);  // "true" steals the onTouch event for the listener
mapView.setMultiTouchControls(true);
mapView.setTilesScaledToDpi(true);      //   3.0
mapView.setTilesScaleFactor(0.5f);      // * 0.5 = 1.5

// initialise position, zoomlevel + orientation
IMapController mapController = mapView.getController();
if (mapCenter != null) mapController.setCenter(mapCenter);
mapController.setZoom(zoomLevel);
mapView.setMapOrientation(mapOrientation);
mapView.setVisibility(View.VISIBLE);


// set static overlays

// Copyright notice
CopyrightOverlay copyrightOverlay1 = new CopyrightOverlay(this);
mapView.getOverlays().add(copyrightOverlay1);

// Compass
myCompassOverlay = new CompassOverlay(this, new InternalCompassOrientationProvider(this), mapView);
myCompassOverlay.enableCompass();
myCompassOverlay.setPointerMode(false);  // false = true north, true = chart north (??)
myCompassOverlay.setCompassInCenter(false);
mapView.getOverlays().add(myCompassOverlay);

// Map Scale Bar
ScaleBarOverlay mScaleBarOverlay;
mScaleBarOverlay = new ScaleBarOverlay(mapView);
mScaleBarOverlay.setCentred(true);
mScaleBarOverlay.setScaleBarOffset(metrics.widthPixels / 2, 10);
mapView.getOverlays().add(mScaleBarOverlay);

// Grid
LatLonGridlineOverlay2 gridOverlay = new LatLonGridlineOverlay2();
gridOverlay.setMultiplier(4);
gridOverlay.setFontColor(Color.BLACK);
gridOverlay.setBackgroundColor(Color.WHITE);
short tSize = 32; // text size
tSize = (short) ((tSize * density / 3.0) + 0.5);
gridOverlay.setFontSizeDp(tSize);
DecimalFormatSymbols dfs = new DecimalFormatSymbols();
dfs.setDecimalSeparator('.');
gridOverlay.setDecimalFormatter(new DecimalFormat("#.#####", dfs));
mapView.getOverlays().add(gridOverlay);

```

If I leave out the "grid" section, everything works fine. I can zoom in and out until I get the "multiple worlds picture" (1st screenshot above). 

But as soon as I activate the grid, the freeze occurs after zooming out to a certain zoom level (I guess < 2.0).

**Comment by monsieurtanuki** [comment]
@mikebravoyes Probably related to #1514, as it looks like a problem with `LatLonGridlineOverlay2` only.
I did test with zoom level 0, though, [as seen on one of the screenshots](https://github.com/osmdroid/osmdroid/issues/1514#issuecomment-600138706).

Could it be because you use `gridOverlay.setMultiplier(4)`, which does not seem reasonable with zoom levels 0 and 1, because it would mean [120° of latitude](https://github.com/osmdroid/osmdroid/blame/master/osmdroid-android/src/main/java/org/osmdroid/views/overlay/gridlines/LatLonGridlineOverlay2.java#L210).
Could you check if everything's fine with `gridOverlay.setMultiplier(1)`,  `gridOverlay.setMultiplier(2)` and  `gridOverlay.setMultiplier(2.5f)`?

**Comment by mikebravoyes** [comment]
@monsieurtanuki 
You are right, this is exactly the problem. The limit for gridOverlay.setMultiplier() seems to be somewhere between 2.83f (latitude=84.9°) and 2.84f (latitude=85.2°). I will use 2.0f and everything is OK. Thanks a lot!

**Comment by monsieurtanuki** [comment]
@mikebravoyes Good news!

If needed, feel free to create
* a "new feature" issue where the end-user can have more control about the grid lines quanta than with the current multiplier, and even different values for longitudes and latitudes
* a "bug fix" issue where you can use `gridOverlay.setMultiplier(4)` and it does not freeze - you just don't see lines for latitudes

**Comment by mikebravoyes** [comment]
@monsieurtanuki 
Btw: The [Docu ](https://osmdroid.github.io/osmdroid/javadocAll/org/osmdroid/views/overlay/gridlines/LatLonGridlineOverlay2.html)for `LatLonGridlineOverlay2.setMultiplier(float multiplier)` is wrong. It says: _"default is 1, larger number = more lines on screen."_ But it is exactly the opposite.
