### ISSUE TITLE
HttpsURLConnection to trust a specific set of CAs

### ISSUE THREAD

**Issue by Rafal-Okuniewski** [osmdroid/osmdroid#1640]
## Issue Type

[ X ] Question
[ ] Bug
[ ] Improvement
[ ] Build system related
[ ] Performance
[ ] Documentation

## Question
Hello.

I need to connect to the map server, use Https and add my own certificate as indicated in the Android documentation:
https://developer.android.com/training/articles/security-ssl#UnknownCa

Is it perhaps planned to implement support for this type of action?

### Version of osmdroid the issue relates to:

6.1.8

**Comment by monsieurtanuki** [comment]
@Rafal-Okuniewski AFAIK no plans to implement that, but I guess that should be (relatively) easy:
1. implement your own [`TileDownloader`](https://github.com/osmdroid/osmdroid/blob/master/osmdroid-android/src/main/java/org/osmdroid/tileprovider/modules/TileDownloader.java) according to the android documentation
1. use [`MapTileDownloader.setTileDownloader(TileDownloader)`](https://github.com/osmdroid/osmdroid/blob/master/osmdroid-android/src/main/java/org/osmdroid/tileprovider/modules/MapTileDownloader.java#L224)

**Comment by Rafal-Okuniewski** [comment]
@monsieurtanuki Thank you for your answer.
That is what I did. I also had to write my own MapTileProviderBasic where I could set up MapTileDownloader. I understand that there is no other way to set up your own TileDownloader for MapTileProviderBasic?

**Comment by monsieurtanuki** [comment]
@Rafal-Okuniewski Correct, there's no such method in `MapTileProviderBasic`.
I don't know, perhaps `MapTileDownloader MapTileProviderBasic.getMapTileDownloader()` would make more sense? Provided that we don't allow `MapTileDownloader.setTileSource(ITileSource)` to be called when the `MapTileDownloader` was created inside a `MapTileProviderBasic`...

I'm glad it solved your issue anyway, and `MapTileProviderBasic` is not such a huge code to copy (and it's supposed to be only a basic example).

Feel free to close the issue, and/or to create a new one about how flexible the basic tile provider should be.

**Comment by Rafal-Okuniewski** [comment]
Thank you for your time and help.
