### ISSUE TITLE
How to show map in a fragment.

### ISSUE THREAD

**Issue by KavinduZoysa** [osmdroid/osmdroid#1641]
## Issue Type

[* ] Question
[ ] Bug
[ ] Improvement
[ ] Build system related
[ ] Performance
[* ] Documentation

## Description and/or steps/code to reproduce the problem

This is my code. 

```
public class FirstFragment extends Fragment {

    MapView mMapView;

    @Override
    public View onCreateView(
            LayoutInflater inflater, ViewGroup container,
            Bundle savedInstanceState
    ) {
        mMapView = new MapView(inflater.getContext());
        return mMapView;
    }

    @Override
    public void onResume() {
        super.onResume();
        mMapView.onResume();
    }
}
```
This is my output. 

![osmmap](https://user-images.githubusercontent.com/28332708/93627217-38ea9e00-fa02-11ea-9d22-b7b2e1745fb2.png)

How do I set the map to this fragment? Kindly requesting an example code.

### Version of osmdroid the issue relates to:

6.1.2

**Comment by spyhunter99** [comment]
Check out the sample app on the playstore, then find an example you like, then dig up the source for it and poke around. Adding it in a fragment is no different than in an activity layout, only the lifecycle is a bit different.

**Comment by wt0816k** [comment]
`mMapView.setDestroyMode(false);`
This appears to be the most effective solution at present.
from: #1848
