### ISSUE TITLE
Crash in Marker constructor

### ISSUE THREAD

**Issue by panovvitalik** [osmdroid/osmdroid#1650]
## Issue Type

[ ] Question
[ X ] Bug
[ ] Improvement
[ ] Build system related
[ ] Performance
[ ] Documentation

## Description and/or steps/code to reproduce the problem
The issue occure in play console. I can't reproduce it in developer machine.

Yesterday, 3:05 PM on app version 240
Google Pixel 3 XL (crosshatch), 3584MB RAM, Android 10
Report 6

```
android.content.res.Resources$NotFoundException: 
  at android.content.res.ResourcesImpl.getValueForDensity (ResourcesImpl.java:246)
  at android.content.res.Resources.getDrawableForDensity (Resources.java:905)
  at android.content.res.Resources.getDrawable (Resources.java:845)
  at android.content.res.Resources.getDrawable (Resources.java:820)
  at org.osmdroid.views.MapViewRepository.getDefaultMarkerIcon (MapViewRepository.java:83)
  at org.osmdroid.views.overlay.Marker.setDefaultIcon (Marker.java:140)
  at org.osmdroid.views.overlay.Marker.<init> (Marker.java:115)
  at org.osmdroid.views.overlay.Marker.<init> (Marker.java:93)
  at vitalypanov.phototracker.maps.openstreet.BaseMarker.<init> (BaseMarker.java:13)
```

## Environment

Nexus 5X (bullhead) | 6 | 40.0%
Pixel 3a (sargo) | 5 | 33.3%
Pixel 3 XL (crosshatch) | 4 | 26.7%

### If it's a bug, version(s) of android this affects:

Android 10 | 9 | 60.0%
Android 8.1 | 6 | 40.0%

### Version of osmdroid the issue relates to:

implementation 'org.osmdroid:osmdroid-android:6.1.8'

**Comment by monsieurtanuki** [comment]
@panovvitalik Isn't that similar to your own #1223?
For some reason it looks like in your case the default Marker icon (`R.drawable.marker_default`) cannot be found.
As it's an ugly icon anyway, my fast track suggestion: create a new class that extends `Marker`, and override `setDefaultIcon()`.

**Comment by panovvitalik** [comment]
@monsieurtanuki
No. It's not the similar! There was null pointer exception at mMapViewRepository private variable.
Now it' the crash due to "not found resource" message. I don't understand completely why.... but

Thank you for the idea of overriding setDefaultIcon procedure. 
But anyway I hope this NPE info will be usefull for improving quality of the lib.

**Comment by spyhunter99** [comment]
are you adding the aar as a dependency for your project or are you one of the crazies that that extracts a jar from the aar and somehow uses that?

**Comment by panovvitalik** [comment]
> are you adding the aar as a dependency for your project or are you one of the crazies that that extracts a jar from the aar and somehow uses that?

I'm the crazy who use: implementation 'org.osmdroid:osmdroid-android:6.1.8'

**Comment by spyhunter99** [comment]
that sounds normal. Every now and then we get someone that opens an issue like this that is an eclipse user that adds just the osmdroid classes to their app and not the resource files, which causes this issue. Are you using proguard or something like it? Maybe the resources files are getting removed by something else

**Comment by spyhunter99** [comment]
well over a year old, not sure if this is still an issue. reopen if needed
