### ISSUE TITLE
Marker icon position gets changes on map zoom in and zoom out.

### ISSUE THREAD

**Issue by UrbanSide** [osmdroid/osmdroid#1651]
[*] Question
[*] Bug
[ ] Improvement
[ ] Build system related
[ ] Performance
[ ] Documentation

## Description and/or steps/code to reproduce the problem

Hello everyone, I am using this lib to draw the map. The markers change their position when zooming in. The true position is achieved only at the maximum zoom. How to solve this *?
Sorry for my english,my lang is russian.
Video:
https://drive.google.com/file/d/1-0HbPzmAygX26lP4hsOPH2rzvJ8N6nT5/view

### If it's a bug, version(s) of android this affects:

Android 9/10

### Version of osmdroid the issue relates to:

6.1.8

**Comment by monsieurtanuki** [comment]
@UrbanSide Looks similar to #1430 and #1349.
Please have a look at the solution successfully implemented by @mminelli in #1349:
> Problem confirmed as solved: creating the folders
drawable-xhdpi
drawable-xxhdpi
drawable-xxxhdpi
drawable-mdpi
drawable-ldpi
drawable-hdpi
and populating them with my icon (which is also placed in drawable) makes it stay correctly in place even when I zoom in/out.

Feel free to close the issue if it worked.

**Comment by UrbanSide** [comment]
I fix it by change Anchor : `mr.setAnchor(0.2f, 0.4f);`

> @UrbanSide Looks similar to #1430 and #1349.
> Please have a look at the solution successfully implemented by @mminelli in #1349:
> 
> > Problem confirmed as solved: creating the folders
> > drawable-xhdpi
> > drawable-xxhdpi
> > drawable-xxxhdpi
> > drawable-mdpi
> > drawable-ldpi
> > drawable-hdpi
> > and populating them with my icon (which is also placed in drawable) makes it stay correctly in place even when I zoom in/out.
> 
> Feel free to close the issue if it worked.
