### ISSUE TITLE
error CS0426: The type name 'CallbackTask' does not exist in the type 'DelayedMapListener'

### ISSUE THREAD

**Issue by panushjain** [osmdroid/osmdroid#1655]
The build is failing with an error due to osm generated class, attaching the file content below.

(feel free to delete whatever doesn't apply)

## Issue Type

[ ] Question
[ ] Bug
[ ] Improvement
[x] Build system related
[ ] Performance
[ ] Documentation

## Description and/or steps/code to reproduce the problem
Build error :

**CS0426: obj\Release\generated\src\Org.Osmdroid.Events.DelayedMapListener.cs(20,60): The type name 'CallbackTask' does not exist in the type 'DelayedMapListener'**

## Environment
Windows Server 2016
Visual Studio Enterprise 2019 version 16.7.7

### If it's a bug, version(s) of android this affects:

All

### Version of osmdroid the issue relates to:

5.2

**DelayedMapListener.cs**

`using System;
using System.Collections.Generic;
using Android.Runtime;
using Java.Interop;

namespace Osmdroid.Events {

	// Metadata.xml XPath class reference: path="/api/package[@name='org.osmdroid.events']/class[@name='DelayedMapListener']"
	[global::Android.Runtime.Register ("org/osmdroid/events/DelayedMapListener", DoNotGenerateAcw=true)]
	public partial class DelayedMapListener : global::Java.Lang.Object, global::Osmdroid.Events.IMapListener {

		// Metadata.xml XPath field reference: path="/api/package[@name='org.osmdroid.events']/class[@name='DelayedMapListener']/field[@name='DEFAULT_DELAY']"
		[Register ("DEFAULT_DELAY")]
		protected const int DefaultDelay = (int) 100;

		// Metadata.xml XPath field reference: path="/api/package[@name='org.osmdroid.events']/class[@name='DelayedMapListener']/field[@name='callback']"
		[Register ("callback")]
		protected global::Osmdroid.Events.DelayedMapListener.CallbackTask Callback {
			get {
				const string __id = "callback.Lorg/osmdroid/events/DelayedMapListener$CallbackTask;";

				var __v = _members.InstanceFields.GetObjectValue (__id, this);
				return global::Java.Lang.Object.GetObject<global::Osmdroid.Events.DelayedMapListener.CallbackTask> (__v.Handle, JniHandleOwnership.TransferLocalRef);
			}
			set {
				const string __id = "callback.Lorg/osmdroid/events/DelayedMapListener$CallbackTask;";

				IntPtr native_value = global::Android.Runtime.JNIEnv.ToLocalJniHandle (value);
				try {
					_members.InstanceFields.SetValue (__id, this, new JniObjectReference (native_value));
				} finally {
					global::Android.Runtime.JNIEnv.DeleteLocalRef (native_value);
				}
			}
		}

		// Metadata.xml XPath field reference: path="/api/package[@name='org.osmdroid.events']/class[@name='DelayedMapListener']/field[@name='delay']"
		[Register ("delay")]
		protected long Delay {
			get {
				const string __id = "delay.J";

				var __v = _members.InstanceFields.GetInt64Value (__id, this);
				return __v;
			}
			set {
				const string __id = "delay.J";

				try {
					_members.InstanceFields.SetValue (__id, this, value);
				} finally {
				}
			}
		}

		// Metadata.xml XPath field reference: path="/api/package[@name='org.osmdroid.events']/class[@name='DelayedMapListener']/field[@name='handler']"
		[Register ("handler")]
		protected global::Android.OS.Handler Handler {
			get {
				const string __id = "handler.Landroid/os/Handler;";

				var __v = _members.InstanceFields.GetObjectValue (__id, this);
				return global::Java.Lang.Object.GetObject<global::Android.OS.Handler> (__v.Handle, JniHandleOwnership.TransferLocalRef);
			}
			set {
				const string __id = "handler.Landroid/os/Handler;";

				IntPtr native_value = global::Android.Runtime.JNIEnv.ToLocalJniHandle (value);
				try {
					_members.InstanceFields.SetValue (__id, this, new JniObjectReference (native_value));
				} finally {
					global::Android.Runtime.JNIEnv.DeleteLocalRef (native_value);
				}
			}
		}
		// Metadata.xml XPath class reference: path="/api/package[@name='org.osmdroid.events']/class[@name='DelayedMapListener.CallbackTask']"
		[global::Android.Runtime.Register ("org/osmdroid/events/DelayedMapListener$CallbackTask", DoNotGenerateAcw=true)]
		public partial class CallbackTask : global::Java.Lang.Object, global::Java.Lang.IRunnable {

			internal    new     static  readonly    JniPeerMembers  _members    = new XAPeerMembers ("org/osmdroid/events/DelayedMapListener$CallbackTask", typeof (CallbackTask));
			internal static new IntPtr class_ref {
				get {
					return _members.JniPeerType.PeerReference.Handle;
				}
			}

			public override global::Java.Interop.JniPeerMembers JniPeerMembers {
				get { return _members; }
			}

			protected override IntPtr ThresholdClass {
				get { return _members.JniPeerType.PeerReference.Handle; }
			}

			protected override global::System.Type ThresholdType {
				get { return _members.ManagedPeerType; }
			}

			protected CallbackTask (IntPtr javaReference, JniHandleOwnership transfer) : base (javaReference, transfer) {}

			// Metadata.xml XPath constructor reference: path="/api/package[@name='org.osmdroid.events']/class[@name='DelayedMapListener.CallbackTask']/constructor[@name='DelayedMapListener.CallbackTask' and count(parameter)=2 and parameter[1][@type='org.osmdroid.events.DelayedMapListener'] and parameter[2][@type='org.osmdroid.events.MapEvent']]"
			[Register (".ctor", "(Lorg/osmdroid/events/DelayedMapListener;Lorg/osmdroid/events/MapEvent;)V", "")]
			public unsafe CallbackTask (global::Osmdroid.Events.DelayedMapListener __self, global::Osmdroid.Events.IMapEvent p1)
				: base (IntPtr.Zero, JniHandleOwnership.DoNotTransfer)
			{
				string __id = "(L" + global::Android.Runtime.JNIEnv.GetJniName (GetType ().DeclaringType) + ";Lorg/osmdroid/events/MapEvent;)V";

				if (((global::Java.Lang.Object) this).Handle != IntPtr.Zero)
					return;

				try {
					JniArgumentValue* __args = stackalloc JniArgumentValue [2];
					__args [0] = new JniArgumentValue ((__self == null) ? IntPtr.Zero : ((global::Java.Lang.Object) __self).Handle);
					__args [1] = new JniArgumentValue ((p1 == null) ? IntPtr.Zero : ((global::Java.Lang.Object) p1).Handle);
					var __r = _members.InstanceMethods.StartCreateInstance (__id, ((object) this).GetType (), __args);
					SetHandle (__r.Handle, JniHandleOwnership.TransferLocalRef);
					_members.InstanceMethods.FinishCreateInstance (__id, this, __args);
				} finally {
				}
			}

			static Delegate cb_run;
#pragma warning disable 0169
			static Delegate GetRunHandler ()
			{
				if (cb_run == null)
					cb_run = JNINativeWrapper.CreateDelegate ((Action<IntPtr, IntPtr>) n_Run);
				return cb_run;
			}

			static void n_Run (IntPtr jnienv, IntPtr native__this)
			{
				global::Osmdroid.Events.DelayedMapListener.CallbackTask __this = global::Java.Lang.Object.GetObject<global::Osmdroid.Events.DelayedMapListener.CallbackTask> (jnienv, native__this, JniHandleOwnership.DoNotTransfer);
				__this.Run ();
			}
#pragma warning restore 0169

			// Metadata.xml XPath method reference: path="/api/package[@name='org.osmdroid.events']/class[@name='DelayedMapListener.CallbackTask']/method[@name='run' and count(parameter)=0]"
			[Register ("run", "()V", "GetRunHandler")]
			public virtual unsafe void Run ()
			{
				const string __id = "run.()V";
				try {
					_members.InstanceMethods.InvokeVirtualVoidMethod (__id, this, null);
				} finally {
				}
			}

		}

		internal    new     static  readonly    JniPeerMembers  _members    = new XAPeerMembers ("org/osmdroid/events/DelayedMapListener", typeof (DelayedMapListener));
		internal static new IntPtr class_ref {
			get {
				return _members.JniPeerType.PeerReference.Handle;
			}
		}

		public override global::Java.Interop.JniPeerMembers JniPeerMembers {
			get { return _members; }
		}

		protected override IntPtr ThresholdClass {
			get { return _members.JniPeerType.PeerReference.Handle; }
		}

		protected override global::System.Type ThresholdType {
			get { return _members.ManagedPeerType; }
		}

		protected DelayedMapListener (IntPtr javaReference, JniHandleOwnership transfer) : base (javaReference, transfer) {}

		// Metadata.xml XPath constructor reference: path="/api/package[@name='org.osmdroid.events']/class[@name='DelayedMapListener']/constructor[@name='DelayedMapListener' and count(parameter)=2 and parameter[1][@type='org.osmdroid.events.MapListener'] and parameter[2][@type='long']]"
		[Register (".ctor", "(Lorg/osmdroid/events/MapListener;J)V", "")]
		public unsafe DelayedMapListener (global::Osmdroid.Events.IMapListener p0, long p1)
			: base (IntPtr.Zero, JniHandleOwnership.DoNotTransfer)
		{
			const string __id = "(Lorg/osmdroid/events/MapListener;J)V";

			if (((global::Java.Lang.Object) this).Handle != IntPtr.Zero)
				return;

			try {
				JniArgumentValue* __args = stackalloc JniArgumentValue [2];
				__args [0] = new JniArgumentValue ((p0 == null) ? IntPtr.Zero : ((global::Java.Lang.Object) p0).Handle);
				__args [1] = new JniArgumentValue (p1);
				var __r = _members.InstanceMethods.StartCreateInstance (__id, ((object) this).GetType (), __args);
				SetHandle (__r.Handle, JniHandleOwnership.TransferLocalRef);
				_members.InstanceMethods.FinishCreateInstance (__id, this, __args);
			} finally {
			}
		}

		// Metadata.xml XPath constructor reference: path="/api/package[@name='org.osmdroid.events']/class[@name='DelayedMapListener']/constructor[@name='DelayedMapListener' and count(parameter)=1 and parameter[1][@type='org.osmdroid.events.MapListener']]"
		[Register (".ctor", "(Lorg/osmdroid/events/MapListener;)V", "")]
		public unsafe DelayedMapListener (global::Osmdroid.Events.IMapListener p0)
			: base (IntPtr.Zero, JniHandleOwnership.DoNotTransfer)
		{
			const string __id = "(Lorg/osmdroid/events/MapListener;)V";

			if (((global::Java.Lang.Object) this).Handle != IntPtr.Zero)
				return;

			try {
				JniArgumentValue* __args = stackalloc JniArgumentValue [1];
				__args [0] = new JniArgumentValue ((p0 == null) ? IntPtr.Zero : ((global::Java.Lang.Object) p0).Handle);
				var __r = _members.InstanceMethods.StartCreateInstance (__id, ((object) this).GetType (), __args);
				SetHandle (__r.Handle, JniHandleOwnership.TransferLocalRef);
				_members.InstanceMethods.FinishCreateInstance (__id, this, __args);
			} finally {
			}
		}

		static Delegate cb_dispatch_Lorg_osmdroid_events_MapEvent_;
#pragma warning disable 0169
		static Delegate GetDispatch_Lorg_osmdroid_events_MapEvent_Handler ()
		{
			if (cb_dispatch_Lorg_osmdroid_events_MapEvent_ == null)
				cb_dispatch_Lorg_osmdroid_events_MapEvent_ = JNINativeWrapper.CreateDelegate ((Action<IntPtr, IntPtr, IntPtr>) n_Dispatch_Lorg_osmdroid_events_MapEvent_);
			return cb_dispatch_Lorg_osmdroid_events_MapEvent_;
		}

		static void n_Dispatch_Lorg_osmdroid_events_MapEvent_ (IntPtr jnienv, IntPtr native__this, IntPtr native_p0)
		{
			global::Osmdroid.Events.DelayedMapListener __this = global::Java.Lang.Object.GetObject<global::Osmdroid.Events.DelayedMapListener> (jnienv, native__this, JniHandleOwnership.DoNotTransfer);
			global::Osmdroid.Events.IMapEvent p0 = (global::Osmdroid.Events.IMapEvent)global::Java.Lang.Object.GetObject<global::Osmdroid.Events.IMapEvent> (native_p0, JniHandleOwnership.DoNotTransfer);
			__this.Dispatch (p0);
		}
#pragma warning restore 0169

		// Metadata.xml XPath method reference: path="/api/package[@name='org.osmdroid.events']/class[@name='DelayedMapListener']/method[@name='dispatch' and count(parameter)=1 and parameter[1][@type='org.osmdroid.events.MapEvent']]"
		[Register ("dispatch", "(Lorg/osmdroid/events/MapEvent;)V", "GetDispatch_Lorg_osmdroid_events_MapEvent_Handler")]
		protected virtual unsafe void Dispatch (global::Osmdroid.Events.IMapEvent p0)
		{
			const string __id = "dispatch.(Lorg/osmdroid/events/MapEvent;)V";
			try {
				JniArgumentValue* __args = stackalloc JniArgumentValue [1];
				__args [0] = new JniArgumentValue ((p0 == null) ? IntPtr.Zero : ((global::Java.Lang.Object) p0).Handle);
				_members.InstanceMethods.InvokeVirtualVoidMethod (__id, this, __args);
			} finally {
			}
		}

		static Delegate cb_onScroll_Lorg_osmdroid_events_ScrollEvent_;
#pragma warning disable 0169
		static Delegate GetOnScroll_Lorg_osmdroid_events_ScrollEvent_Handler ()
		{
			if (cb_onScroll_Lorg_osmdroid_events_ScrollEvent_ == null)
				cb_onScroll_Lorg_osmdroid_events_ScrollEvent_ = JNINativeWrapper.CreateDelegate ((Func<IntPtr, IntPtr, IntPtr, bool>) n_OnScroll_Lorg_osmdroid_events_ScrollEvent_);
			return cb_onScroll_Lorg_osmdroid_events_ScrollEvent_;
		}

		static bool n_OnScroll_Lorg_osmdroid_events_ScrollEvent_ (IntPtr jnienv, IntPtr native__this, IntPtr native_p0)
		{
			global::Osmdroid.Events.DelayedMapListener __this = global::Java.Lang.Object.GetObject<global::Osmdroid.Events.DelayedMapListener> (jnienv, native__this, JniHandleOwnership.DoNotTransfer);
			global::Osmdroid.Events.ScrollEvent p0 = global::Java.Lang.Object.GetObject<global::Osmdroid.Events.ScrollEvent> (native_p0, JniHandleOwnership.DoNotTransfer);
			bool __ret = __this.OnScroll (p0);
			return __ret;
		}
#pragma warning restore 0169

		// Metadata.xml XPath method reference: path="/api/package[@name='org.osmdroid.events']/class[@name='DelayedMapListener']/method[@name='onScroll' and count(parameter)=1 and parameter[1][@type='org.osmdroid.events.ScrollEvent']]"
		[Register ("onScroll", "(Lorg/osmdroid/events/ScrollEvent;)Z", "GetOnScroll_Lorg_osmdroid_events_ScrollEvent_Handler")]
		public virtual unsafe bool OnScroll (global::Osmdroid.Events.ScrollEvent p0)
		{
			const string __id = "onScroll.(Lorg/osmdroid/events/ScrollEvent;)Z";
			try {
				JniArgumentValue* __args = stackalloc JniArgumentValue [1];
				__args [0] = new JniArgumentValue ((p0 == null) ? IntPtr.Zero : ((global::Java.Lang.Object) p0).Handle);
				var __rm = _members.InstanceMethods.InvokeVirtualBooleanMethod (__id, this, __args);
				return __rm;
			} finally {
			}
		}

		static Delegate cb_onZoom_Lorg_osmdroid_events_ZoomEvent_;
#pragma warning disable 0169
		static Delegate GetOnZoom_Lorg_osmdroid_events_ZoomEvent_Handler ()
		{
			if (cb_onZoom_Lorg_osmdroid_events_ZoomEvent_ == null)
				cb_onZoom_Lorg_osmdroid_events_ZoomEvent_ = JNINativeWrapper.CreateDelegate ((Func<IntPtr, IntPtr, IntPtr, bool>) n_OnZoom_Lorg_osmdroid_events_ZoomEvent_);
			return cb_onZoom_Lorg_osmdroid_events_ZoomEvent_;
		}

		static bool n_OnZoom_Lorg_osmdroid_events_ZoomEvent_ (IntPtr jnienv, IntPtr native__this, IntPtr native_p0)
		{
			global::Osmdroid.Events.DelayedMapListener __this = global::Java.Lang.Object.GetObject<global::Osmdroid.Events.DelayedMapListener> (jnienv, native__this, JniHandleOwnership.DoNotTransfer);
			global::Osmdroid.Events.ZoomEvent p0 = global::Java.Lang.Object.GetObject<global::Osmdroid.Events.ZoomEvent> (native_p0, JniHandleOwnership.DoNotTransfer);
			bool __ret = __this.OnZoom (p0);
			return __ret;
		}
#pragma warning restore 0169

		// Metadata.xml XPath method reference: path="/api/package[@name='org.osmdroid.events']/class[@name='DelayedMapListener']/method[@name='onZoom' and count(parameter)=1 and parameter[1][@type='org.osmdroid.events.ZoomEvent']]"
		[Register ("onZoom", "(Lorg/osmdroid/events/ZoomEvent;)Z", "GetOnZoom_Lorg_osmdroid_events_ZoomEvent_Handler")]
		public virtual unsafe bool OnZoom (global::Osmdroid.Events.ZoomEvent p0)
		{
			const string __id = "onZoom.(Lorg/osmdroid/events/ZoomEvent;)Z";
			try {
				JniArgumentValue* __args = stackalloc JniArgumentValue [1];
				__args [0] = new JniArgumentValue ((p0 == null) ? IntPtr.Zero : ((global::Java.Lang.Object) p0).Handle);
				var __rm = _members.InstanceMethods.InvokeVirtualBooleanMethod (__id, this, __args);
				return __rm;
			} finally {
			}
		}

	}
}
`

**Comment by skb50bd** [comment]
Hi, @panushjain! 
I am facing the same issue. Have you solved it? If yes, can you please share the solution?
