### ISSUE TITLE
Gray tile when zooming out

### ISSUE THREAD

**Issue by Saursinet** [osmdroid/osmdroid#1657]
## Issue Type

[X] Bug

## Description and/or steps/code to reproduce the problem

When user zoom out and that new tiles appear some of them take default color indicated by 
```
tilesOverlay.loadingBackgroundColor = context.getColor(R.color.loading_tile)
tilesOverlay.loadingLineColor = context.getColor(R.color.loading_tile)
```
But I have some others which appear gray and I cannot find a way to fix this. (cf: photo)
![Screenshot_20201029-155156](https://user-images.githubusercontent.com/10145464/98557062-06438000-22a4-11eb-984b-0d2258be5678.jpg)
On this photo we can see 2 colors. The yellowish is the default tile color while the gray is not set anywhere. 
Also after loading the tiles appear correctly but it's just in the meantime that we see this Gray color.

### If it's a bug, version(s) of android this affects:

All

### Version of osmdroid the issue relates to:

6.1.6

**Comment by monsieurtanuki** [comment]
@Saursinet I guess it's when the tile is not available for the moment and is being "approximated" from relevant tiles on other zoom levels, cf. [MapTileProviderBase](https://github.com/osmdroid/osmdroid/blob/master/osmdroid-android/src/main/java/org/osmdroid/tileprovider/MapTileProviderBase.java#L473)
Does that make sense? Would you like to have control on the "approximation" background color?

**Comment by Saursinet** [comment]
Ah indeed! It does make sense! And yes I would like to be able to set this "approximation" background color so that it would almost match empty land color!

**Comment by monsieurtanuki** [comment]
Well, I guess a `static` setter would do the trick.
I've coded that, and then I got trapped into a git issue that could easily turn into a time-consuming nightmare. That would last much more than the 5 minutes I was able to allocate to this issue.
Feel free to send a PR.

**Comment by Saursinet** [comment]
Thank you for checking and look into it!

**Comment by monsieurtanuki** [comment]
@Saursinet Strange behavior...
If I sum up, if you chose color A, color B will be displayed wherever you expected color A as the default approximation color. Your only problem is that this is not the color you chose - but at least there's consistency as the same color B is displayed every time you expected color A. Is that a good description?

**Comment by Saursinet** [comment]
So yes the summary is good there is only one nuance in that description. We seem to have the colour deeper in some places (cf: photo). This is the app with the color #EEF1E0 used [
<img width="489" alt="Screenshot 2021-04-06 at 12 04 56" src="https://user-images.githubusercontent.com/10145464/113694867-8f82a580-96d0-11eb-807f-2b6817b44ccd.png">
](url)

**Comment by monsieurtanuki** [comment]
@Saursinet I can see different colors, but I don't know where you say the color is deeper (darker?) than #EEF1E0.
What happens if you don't put your own color and leave the default color: do you still see unexpected results?
Could it be an issue with the alpha channel: what happens with `#FFEEF1E0`?
What if you use a predefined color, like `Color.YELLOW`?

**Comment by Saursinet** [comment]
Sorry yes by deeper i meant darker. We see a light purple and dark purple on the above image what i mean is they are both "approximate tiles".
If I leave the default colour then we return to why I created this ticket in the first place and we have Gray tiles.
I did try the Alpha channel but no it doesn't make any difference in the colour. But R.color.Yellow does show a yellow colour.

**Comment by monsieurtanuki** [comment]
I don't see how #EEF1E0 should turn purple when darker, the main color being (slightly) green, for a light gray.
If everything looks perfect with R.color.Yellow, it looks like the issue is with your creation of a color.
Please use R.color.Yellow as a starting point and try with other R.color colors.

**Comment by Saursinet** [comment]
Alright I found out that by using `context.getColor(R.color.loading_tile)` a weird filter appears on top (we sse purple instead of yellowish).
But when I declare the colour as follow `@ColorInt private val LOADING_TILE_COLOR = -0x110e20` then I have no problem in my code. 
Thanks for your support! I'll now close the topic!
