### ISSUE TITLE
How to get involved into the osmdroid community for support, discussion and exchange?

### ISSUE THREAD

**Issue by derMitDemRadTanzt** [osmdroid/osmdroid#1658]
## Issue Type

[x] Question

## Description and/or steps/code to reproduce the problem

Hi folks,
I started a project with osmdroid as crucial part on the front and user end site in the Android app. That is why I want to become part of the osmdroid project community for development, discussion, exchange and support reasons. I tried to find some sort of community by looking for irc chats, mailing lists or forums but found nothing so far. That is why this question appeared: Is there some sort of community and how is it interacting? I thank you folks very much for your time and effort and remain with

Best regards

**Comment by monsieurtanuki** [comment]
[Willkommen, bienvenue, welcome](https://www.youtube.com/watch?v=hBlB8RAJEEc) @derMitDemRadTanzt!
I guess we just create issues, comment them and send PRs.
The core of the reflexion is a ping-pong match commenting issues. Then, when we agree, PR and merge.
I don't think there's anything beyond that for osmdroid.

**Comment by derMitDemRadTanzt** [comment]
Hi @monsieurtanuki ,
thank you very much for the prompt reply. I am a software engineer with a strong embedded systems background. Android, Java and Kotlin is all new to me but I started a project where the front end is heavily relying on those thechnologies.

Now and than I have question and I do not find many or satisfying answers. To my mind, osmdroid has the potential for a more elaborate documentation. I could do that if you are interested. However, first of all I need to find a way to address my questions. What do you think? What do you suggest?

**Comment by monsieurtanuki** [comment]
@derMitDemRadTanzt
* To be honest, I would NOT advise anybody to start learning Android/Java, because it's a real pain in the neck (I don't know much about Kotlin, but the painful part in Android/Java is more Android than Java)
* I would recommend `flutter` instead for so many reasons
* Regarding osmdroid, a very good start is to play with the osmdroid demo app available on Google Play, and even to download the demo code to understand it and edit it
* I don't believe in elaborate documentation anymore, and I would not waste energy on that. Rather something like reading the code, fixing possible bugs, creating/commenting issues and writing sporadically wiki pages.
* If you have specific questions that you cannot find old answers about, just create a new issue

**Comment by derMitDemRadTanzt** [comment]
@monsieurtanuki 

- You are more than right. I spend hour after hour on Android without getting far.

- Thank you very much for the flutter recommendation. I'll definitely give it a thought.

- I came across Android and Java because of the osmdroid app. To study it, I am kind of bound to those technologies, aren't I? Or, does this example or even the project also exist in flutter?

**Comment by monsieurtanuki** [comment]
@derMitDemRadTanzt I don't know what you try to achieve and more specifically which aspects interest you in osmdroid.
There are other librairies in other languages that use the same kind of map tiles created using the same Open Street Map meta data, like [Leaflet](https://leafletjs.com) or [flutter_map](https://pub.dev/packages/flutter_map), for instance. I don't especially endorse those librairies; I just say that there are plenty of them.
Have a look at different libraries on different languages, test them, and tell me what is your favorite ;)

**Comment by derMitDemRadTanzt** [comment]
@monsieurtanuki Thank you very much for your help. I'll do so and touch base when I have a favorite. Cheers!

**Comment by spyhunter99** [comment]
i'll add that i'm currently only involved for doing release management. if someone wants to take over, let me know. i honestly don't have much time to support this project anymore
