### ISSUE TITLE
google maps wrapper example app crashes on start up

### ISSUE THREAD

**Issue by spyhunter99** [osmdroid/osmdroid#166]
looks like removing the slf4j dependency had some unintended consequences

**Comment by neilboyd** [comment]
What was the problem?  I removed slf4j and it works okay, as expected.

**Comment by spyhunter99** [comment]
it was crashing with a classdef not found. even with manually unistall and deploy

**Comment by neilboyd** [comment]
I see the problem. If you build with Maven and then deploy the apk that's generated. I was doing it in Android Studio which was working fine.

I changed the dependency from GoogleWrapperSample on osmdroid-android to be type aar.  Plus some other dependency tidying up that I hope doesn't break anything.

I can now run `mvn clean install` on the root which cleans and builds everything, including running all the tests.
