### ISSUE TITLE
Does the CleanAreaAsync have a callback function?

### ISSUE THREAD

**Issue by ivanhjel** [osmdroid/osmdroid#1665]
Please note: issues related to or caused by osmbonuspack will be closed with a
suggestion to open an issue at https://github.com/MKergall/osmbonuspack

(feel free to delete whatever doesn't apply)

## Issue Type

[x] Question
[ ] Bug
[ ] Improvement
[ ] Build system related
[ ] Performance
[ ] Documentation
## Description and/or steps/code to reproduce the problem
Hi, I am trying to add a callback to the cleanAreaAsync functionality for the CacheManager. It doesn't seem to me that there is a callback for the function, but the example I've seen tries to use the callback from the download task. Is there any way to get a callback from the cleanAction? Or is it a way to override the cleaningdialog? I've used this example: 
https://github.com/osmdroid/osmdroid/blob/master/OpenStreetMapViewer/src/main/java/org/osmdroid/samplefragments/cache/SampleCacheDelete.java

### Version of osmdroid the issue relates to:

6.1.2

**Comment by monsieurtanuki** [comment]
@ivanhjel I guess you can find inspiration in the code you mentioned, and do something like that:
```java
CacheManager.CacheManagerTask cacheManagerTask = mgr.cleanAreaAsync(getActivity(), bb, zoommin, zoommax);
cacheManagerTask.addCallback(new CacheManager.CacheManagerCallback() {
   @Override
   public void onTaskComplete() {
    // put something here...
   }

   @Override
   public void updateProgress(int progress, int currentZoomLevel, int zoomMin, int zoomMax) {
    // ... or there
   }

   @Override
   public void downloadStarted() {}

   @Override
   public void setPossibleTilesInArea(int total) {}

   @Override
   public void onTaskFailed(int errors) {}
});
mgr.execute(cacheManagerTask);
```

**Comment by ivanhjel** [comment]
@monsieurtanuki Yeah, I've used the same way of callback when downloading tiles, but it doesn't seem to work for the cleanAreaAsync action. I've set it up the same way as mentioned above, but the "default" dialog gets shown instead of triggering the callback above :/

**Comment by monsieurtanuki** [comment]
@ivanhjel Oops, actually I meant more something like that:
```java
task = new CacheManagerTask(mgr, mgr.getCleaningAction(), bb, zoomMin, zoomMax);
```

If it's not exactly that, I'm sure you'll find the right combination in [CacheManager.java](https://github.com/osmdroid/osmdroid/blob/master/osmdroid-android/src/main/java/org/osmdroid/tileprovider/cachemanager/CacheManager.java)

**Comment by ivanhjel** [comment]
Yay! Thank you, @monsieurtanuki ! I'll close this issue as this solves my challenge :) 

In case anyone else is looking for the same thing, here is an example in Kotlin: 

```
val task = CacheManagerTask(cacheManager, cacheManager.cleaningAction, boundingBox, 9, 14)
task.addCallback(object : CacheManager.CacheManagerCallback {
    override fun onTaskComplete() {}
    override fun updateProgress(
        progress: Int,
        currentZoomLevel: Int,
        zoomMin: Int,
        zoomMax: Int
    ) {}
    override fun downloadStarted() {}
    override fun setPossibleTilesInArea(total: Int) {}
    override fun onTaskFailed(errors: Int) {}

})
task.execute()
```
