### ISSUE TITLE
Dialogs in CacheManager contain hardcoded English strings

### ISSUE THREAD

**Issue by grishka** [osmdroid/osmdroid#1668]
## Issue Type

[ ] Question
[ ] Bug
[x] Improvement
[ ] Build system related
[ ] Performance
[ ] Documentation

## Description and/or steps/code to reproduce the problem

CacheManager shows dialogs, and all the user-visible strings are hardcoded and not translatable. For example:
https://github.com/osmdroid/osmdroid/blob/98085a50bf6b1b78cc9e952af7e0990a9b24934d/osmdroid-android/src/main/java/org/osmdroid/tileprovider/cachemanager/CacheManager.java#L766-L779

I was able to substitute this particular one for a localized string like this, but still...

```java
CacheManager mgr=new CacheManager(OSM.OPENTOPOMAP, new SqliteArchiveTileWriter(tilesDb.getAbsolutePath()), minZoom, maxZoom){
	@Override
	public CacheManagerDialog getDownloadingDialog(Context pCtx, CacheManagerTask pTask){
		return new CacheManagerDialog(pCtx, pTask) {
			@Override
			protected String getUITitle() {
				return getString(R.string.downloading_map);
			}

			@Override
			public void onTaskFailed(int errors) {
				super.onTaskFailed(errors);
				Toast.makeText(pCtx, "Loading completed with " + errors + " errors.", Toast.LENGTH_SHORT).show();
			}
		};
	}
};
```
It would be nice to move the strings to a `strings.xml` file so that apps could provide their own translated versions by overriding them in other locales.
### If it's a bug, version(s) of android this affects:

All

### Version of osmdroid the issue relates to:

6.1.2

**Comment by monsieurtanuki** [comment]
@grishka The good thing is that as you see it's very easy to put your own translation even with the current implementation.

What if someone else would like to put the name of the set of tiles being currently downloaded, like "Downloading map of Italy"? Your improvement suggestion wouldn't work; in that case again you would have to override `getUITitle`.

My point of view: the current system is flexible enough for all developers' needs. Btw I'm not an expert on `strings.xml` files - I mean, yes of course I use one per language, but not several files for the same language, with the possible tag collision issues. And as a developer I don't like the idea of retrieving unnecessary data (including translations) from a lib for languages or use-cases I don't need.

That being said, feel free to create a PR for the translation of "Downloading tiles" through `strings.xml`.
