### ISSUE TITLE
Conversion from WKT

### ISSUE THREAD

**Issue by Josue10599** [osmdroid/osmdroid#1676]
Please note: issues related to or caused by osmbonuspack will be closed with a
suggestion to open an issue at https://github.com/MKergall/osmbonuspack

(feel free to delete whatever doesn't apply)

## Issue Type

[X] Question
[ ] Bug
[X] Improvement
[ ] Build system related
[ ] Performance
[ ] Documentation

## Question

I want to know if the osmdroid library has any function to convert WKT to Polygons?

If we cannot use this Issue to add this function, I have not yet worked on the development of the osmdroid library, but I would love to be able to contribute to this project.

**Comment by monsieurtanuki** [comment]
Hi @Josue10599 
I don't think there's something like that in osmdroid, but I suggest you have a look at https://github.com/MKergall/osmbonuspack where you can find similar things around KML and GeoJSON. And that would be the appropriate project for your generous contribution offer :)

**Comment by Josue10599** [comment]
Right, i am go verify on the [OSMBonusPack](https://github.com/MKergall/osmbonuspack)
Thanks, you respond very fast my question :satisfied:
