### ISSUE TITLE
How to get the TileStates separately for basic map and overlay?

### ISSUE THREAD

**Issue by mikebravoyes** [osmdroid/osmdroid#1683]
## Issue Type

[x] Question
[x] Bug (?)

## Description and/or steps/code to reproduce the problem

@monsieurtanuki 
In my app, I can select either just a basic map (e.g. MAPNIK) or a basic map plus one overlay (e.g. PUBLIC_TRANSPORT). See screenshot below:

![MAPNIK+PUBLIC_TRANSPORT](https://user-images.githubusercontent.com/6436590/105514396-b9cce580-5cd3-11eb-9d79-c37dcb2fbfcb.png)

Now I want to figure out the completeness of the tiles' download.

```
// check completeness of map tiles
TileStates tileStates = mapView.getOverlayManager().getTilesOverlay().getTileStates();

// evaluate the tile states
int totalTiles = tileStates.getTotal();
int goodTiles = tileStates.getUpToDate();

```
If the values for totalTiles and goodTiles are identical, the download of the map is complete. But I get only one "tileStates", regardless of whether I have selected 1 map (basic) or 2 maps (basic + overlay). In the case of 2 maps, I want to be sure, that all tiles for both maps are downloaded completely. How can I distinguish, which is which? 

### If it's a bug, version(s) of android this affects:

All

### Version of osmdroid the issue relates to:

6.1.8

**Comment by monsieurtanuki** [comment]
@mikebravoyes My educated guess is that `mapView.getOverlayManager().getTilesOverlay()` will only point you to the "main" tiles overlay.
If you want the same states for your secondary tiles overlay, you have to use `getTileStates()` on your secondary tiles overlay.
I'm getting a bit rusty on that topic...

**Comment by mikebravoyes** [comment]
@monsieurtanuki 
OK, I amended the code as follows:

```
// primary map
TileStates tileStates1 = mapView.getOverlayManager().getTilesOverlay().getTileStates();
int totalTiles1 = tileStates1.getTotal();
int goodTiles1  = tileStates1.getUpToDate();

// secondary map
Overlay overlay = mapOverlays.getOverlay(mapView, "TilesOverlay");
if (overlay != null)
{
    TilesOverlay tilesOverlay = (TilesOverlay) overlay;
    TileStates tileStates2 = tilesOverlay.getTileStates();
    totalTiles2 = tileStates2.getTotal();
    goodTiles2  = tileStates2.getUpToDate();
}

```
The rest is straight forward...

**Comment by monsieurtanuki** [comment]
@mikebravoyes Looks like it's fixed then, isn't it? Feel free to close the issue.

**Comment by mikebravoyes** [comment]
Thanks for your help!
