### ISSUE TITLE
Marker position is inaccurate when zoomed out

### ISSUE THREAD

**Issue by IpswichMapper** [osmdroid/osmdroid#1688]
## Issue Type

- [x] Question
- [x] Bug
- [x] Improvement

## Description and/or steps/code to reproduce the problem

Hello. I recently created an app to [add housenumbers to OSM quickly](https://github.com/IpswichMapper/SwiftAddress). To place housenumbers, you add the housenumber and it displayed as a marker on the OSMdroid map.

Here is an example of what I mean: 

![housenumber when zoomed in](https://user-images.githubusercontent.com/73911790/105643891-eaa74900-5e92-11eb-92fb-9b46d60b0f08.jpg)

![housenumber when zoomed out](https://user-images.githubusercontent.com/73911790/105643929-1c201480-5e93-11eb-9d42-7cc084dbad47.jpg)

As you can see, when zoomed in the housenumber is below the road. But when zoomed out the housenumber is above the road.

Is this a problem with OSMdroid or is it my code?

Here is the code to add a marker that I have used:

```kotlin

        markerList.add(Marker(map))

        markerList.last().position = GeoPoint(address.latitude, address.longitude)
        markerList.last().icon = ContextCompat.getDrawable(this, R.drawable.address)
        markerList.last().setAnchor(Marker.ANCHOR_CENTER, Marker.ANCHOR_BOTTOM)
        markerList.last().title = address.housenumber

        map.overlays.add(markerList.last())
        Log.i("map", "housenumber marker added")
```

## Environment

Android Studio, built using gradle.

### If it's a bug, version(s) of android this affects:

All

### Version of osmdroid the issue relates to:

6.1.8

**Comment by IpswichMapper** [comment]
EDIT: ANCHOR_CENTER instead of ANCHOR_BOTTOM fixes the issue

**Comment by monsieurtanuki** [comment]
@IpswichMapper I have the weird feeling that it was exactly what I suggested, but I cannot find my reply anymore...
Feel free to close the issue if solved.

**Comment by IpswichMapper** [comment]
But the documentation suggests ANCHOR_BOTTOM

**Comment by monsieurtanuki** [comment]
Then the documentation is wrong or misleading.
If your icon is a circle, then the anchor should be something like HCENTER | VCENTER.
If your icon is a pin, then it makes sense to use something like HCENTER | BOTTOM.
And I still haven't found my message :(

**Comment by spyhunter99** [comment]
where in the documentation was it listed to use bottom? The javadocs don't seem to specify this. The sample applications do use a lot, but that's because most of the icons are pushpin style points in which the location represented by the icon is the tip of the point, not the center point of the icon.

**Comment by IpswichMapper** [comment]
Sorry, when I said documentation, I meant this:

https://github.com/osmdroid/osmdroid/wiki/Markers,-Lines-and-Polygons

However, I changed this to ANCHOR_CENTER. I have a few questions:

* How should this markers guide indicate when to use ANCHOR_CENTER verses ANCHOR_BOTTOM
* If ANCHOR_BOTTOM works for pins, then for the example I showed, why is the bottom of the icon not in the correct position? The icon is just completely out of position, not even the bottom is in the right position. Is it because the icon is 24dpx24dp, and therefore I section of the bottom of the icon is transparent?

**Comment by monsieurtanuki** [comment]
@IpswichMapper `ANCHOR_CENTER` and `ANCHOR_BOTTOM` are no `enum`s, they are `float`s (`.5f` and `1f`).
If you imagine that your picture is a 24x24 square filled with a color, `setAnchor(1f, 1f)` should position the bottom right corner of that square in the correct geo position on the map (versus `setAnchor(0f, 0f)` and top left)
If there are hidden transparent zones in your icon, that can produce a little offset on the screen.
But if you know that on your 24x24 icon the reference anchor is pixel (5, 20), you should use something like `setAnchor(5f / 24, 20f / 24)`.

**Comment by pasniak** [comment]
I also created MyMarker which only feature was to set anchor to the center. Maybe center would be more sensible default...

**Comment by monsieurtanuki** [comment]
@IpswichMapper I'm not sure it's the case but if your problem is fixed now, please close the issue.
@pasniak "Maybe center would be more sensible default" - I guess you're right, but now it's a bit too late, with all the apps that already use osmdroid...

**Comment by IpswichMapper** [comment]
"Maybe center would be more sensible default" - I guess you're right, but now it's a bit too late, with all the apps that already use osmdroid."

??? Is ANCHOR_BOTTOM the default option? I ddin't even realise that, and I don't think it matters. When I first made my app, according the osmdroid wiki you should declare the anchor anyway. What I am talking about here is how to make the wiki clearer so that other users do not face the same issues I did.
