### ISSUE TITLE
MarkerInfoWindow from View

### ISSUE THREAD

**Issue by wharnisch** [osmdroid/osmdroid#1690]
## Issue Type

[x] Question
[ ] Bug
[ ] Improvement
[ ] Build system related
[ ] Performance
[ ] Documentation

## Description and/or steps/code to reproduce the problem

Is there any way to create an InfoWindow for a marker NOT from the "bubble"-ressource, not even on top of any ressource, but from a programmatically created View? As far as I see, a MarkerInfoWindow and even a BasicInfoWindow can only be constructed using a bitmap-ressource.

**Comment by monsieurtanuki** [comment]
@wharnisch What about `extend`ing an `InfoWindow`, and using its resource-less constructor `public InfoWindow(View v, MapView mapView)`?

**Comment by wharnisch** [comment]
Ok, thanks for the info, I will try that.
Regards from Austria

**Comment by wharnisch** [comment]
Thank you, it worked as you suggested! Did not realize that also an InfoWindow, not only a MarkerInfoWindow can be used with a marker.

**Comment by monsieurtanuki** [comment]
You're welcome @wharnisch
