### ISSUE TITLE
OSMMapTilePackager Downloading Error 403 for URL

### ISSUE THREAD

**Issue by tsvetkovivan** [osmdroid/osmdroid#1692]
I need to download tiles for offline use. I have built OSMMapTIlePackaher using Android Studio and Gradle. I read license of use, so first I tried to use their examples in the file [README,](https://github.com/osmdroid/osmdroid/blob/master/OSMMapTilePackager/readme.md) and then my own simple ones (no more than 40 tiles). But nothing works. 

In the console, I enter :
(their example)

- ./OSMMapTilePackager -u http://b.tile.openstreetmap.org/%d/%d/%d.png -t Mapnik -d at_mapnik_13.zip -zmax 13 -n 49.03942 -s 46.40162 -e 17.14736 -w 9.44595

(my example)

- ./OSMMapTilePackager -u https://b.tile.openstreetmap.org/%d/%d/%d.png -t /home/user/Mapnik -d /home/user/tiles.zip -zmin 10 -zmax 10 -n 1.0 -e 1.0 -s -1.0 -w -1.0

But I always get endless error :

.Error downloading: 'z=10 x=509 y=509' from URL: https://b.tile.openstreetmap.org/10/509/509.png : java.io.IOException: Server returned HTTP response code: 403 for URL: https://b.tile.openstreetmap.org/10/509/509.png

Using the same commands through the GUI I get the same errors.

Apparently I really do not understand something obvious. I am newbie with OSM, please help. If it helps, then I use Ubuntu 20.04.2 LTS

## Issue Type

[x ] Question
[ ] Bug
[ ] Improvement
[ ] Build system related
[ ] Performance
[ ] Documentation

### If it's a bug, version(s) of android this affects:

All

### Version of osmdroid the issue relates to:

6.1.11

**Comment by monsieurtanuki** [comment]
@tsvetkovivan If I remember well, last year the guys at MAPNIK reminded us that their tile server was there (for us) just as test/courtesy and that no bulk download was to be allowed. In addition to that, some http parameters need now to be set - that would explain the `403` ("forbidden") (cf. [wiki and http user agent](https://github.com/osmdroid/osmdroid/wiki/How-to-use-the-osmdroid-library#main-activity))
I guess the README you're referring to is a bit old.

My suggestions
* try with `-t OSMPublicTransport` - I don't think they enforce strong policies
* if it's only 40 tiles that are needed, I would download them one by one with a browser - in less than 30 minutes it's done

**Comment by tsvetkovivan** [comment]
@monsieurtanuki Thanks for your quick answer. I think it's the user agent, so I'll try to figure it out. Then I will report back.

**Comment by monsieurtanuki** [comment]
That doesn't change the "no bulk" policy :(

**Comment by tsvetkovivan** [comment]
@monsieurtanuki So now there are no other alternatives for offline maps, except for OSMPublicTransport?

**Comment by monsieurtanuki** [comment]
@tsvetkovivan I guess there are tons of other available tile servers, like [here](https://wiki.openstreetmap.org/wiki/Tile_servers).
The fact is that we only suggest some tile servers in [`TileSourceFactory`](https://github.com/osmdroid/osmdroid/blob/master/osmdroid-android/src/main/java/org/osmdroid/tileprovider/tilesource/TileSourceFactory.java), but it's easy to configure others.
We're only talking about 40 tiles anyway: either 40 manual downloads, or a minor breach of rules that won't hurt anybody.

**Comment by tsvetkovivan** [comment]
@monsieurtanuki I got it. Thank you very much.
