### ISSUE TITLE
How to show untiled world map

### ISSUE THREAD

**Issue by Choongkyu** [osmdroid/osmdroid#1694]
Please note: issues related to or caused by osmbonuspack will be closed with a
suggestion to open an issue at https://github.com/MKergall/osmbonuspack

(feel free to delete whatever doesn't apply)

## Issue Type

[ X] Question
[ ] Bug
[ ] Improvement
[ ] Build system related
[ ] Performance
[ ] Documentation

## Description and/or steps/code to reproduce the problem

I followed the [wiki here](https://github.com/osmdroid/osmdroid/wiki/How-to-use-the-osmdroid-library) and saw this come out. I was wondering how I can have an un-tiled version of this.

![Screenshot_20210220-153138](https://user-images.githubusercontent.com/1592194/108611452-7a0d2280-7393-11eb-9d4b-7fc04b8ee028.jpg)

## Environment
macos big sur

### If it's a bug, version(s) of android this affects:

All

### Version of osmdroid the issue relates to:

6.1.10

**Comment by monsieurtanuki** [comment]
Hi @Choongkyu!
My suggestions:
* `mapView.setHorizontalMapRepetitionEnabled(false)`
* `mapView.setVerticalMapRepetitionEnabled(false)`
* `mapView.setTilesScaledToDpi(true)`

**Comment by Choongkyu** [comment]
> Hi @Choongkyu!
> My suggestions:
> 
> * `mapView.setHorizontalMapRepetitionEnabled(false)`
> * `mapView.setVerticalMapRepetitionEnabled(false)`
> * `mapView.setTilesScaledToDpi(true)`

thank you! that fixed it. I have an unrelated question: I noticed that osmdroid defaults to using Mapnik as the tile provider and I was wondering if there are any traffic-related usage policies/limitations when using osmdroid with Mapnik.
