### ISSUE TITLE
Yandex tiles in osmdroid

### ISSUE THREAD

**Issue by s-ilnar** [osmdroid/osmdroid#1699]
## Issue Type

[ x] Question
[ ] Bug
[ ] Improvement
[ ] Build system related
[ ] Performance
[ ] Documentation

## Description and/or steps/code to reproduce the problem

Similar question on the stackoverflow -> https://stackoverflow.com/questions/26742738/yandex-tiles-wrong/27807769

This is my tile provider (yandex)

```
class YandexTileProvider(
        private val width: Int = 256,
        private val height: Int = 256
) : UrlTileProvider(width, height) {

    private val baseUrl = "http://vec0{s}.maps.yandex.net/tiles?l=map&v=2.28.0&x={x}&y={y}&z={z}&lang=ru-RU"

    override fun getTileUrl(x: Int, y: Int, zoom: Int): URL {
        val url = baseUrl.replace("{s}", "${(0..4).random()}").replace("{z}", "$zoom")
                .replace("{x}", "$x").replace("{y}", "$y")
        return URL(url)
    }

    fun toOsmTile(): OnlineTileSourceBase {
        return object : OnlineTileSourceBase("Yandex", 1, 17, width.coerceAtMost(height), "", arrayOf(baseUrl), "© Yandex") {
            override fun getTileURLString(pMapTileIndex: Long): String {
                val x = MapTileIndex.getX(pMapTileIndex)
                val y = MapTileIndex.getY(pMapTileIndex)
                val zoom = MapTileIndex.getZoom(pMapTileIndex)

                return baseUrl.replace("{s}", "${(1..4).random()}").replace("{z}", "$zoom")
                        .replace("{x}", "$x").replace("{y}", "$y")
            }
        }
    }
}
```

Change tile code:

```
if (isYandex) {
                mapView.setTileSource(new YandexTileProvider().toOsmTile());
            } else {
                mapView.setTileSource(TileSourceFactory.MAPNIK);
            }
```

## Environment

When using Yandex tiles, the position is displayed incorrectly. Are there any thoughts on how to fix this?

Screenshots
<a href="https://ibb.co/BKwmJjJ"><img src="https://i.ibb.co/BKwmJjJ/2021-03-03-09-06-59.png" alt="2021-03-03-09-06-59" border="0"></a> <a href="https://ibb.co/5RskjyB"><img src="https://i.ibb.co/5RskjyB/2021-03-03-09-08-11.png" alt="2021-03-03-09-08-11" border="0"></a>

### If it's a bug, version(s) of android this affects:

All

### Version of osmdroid the issue relates to:

6.0.1

**Comment by monsieurtanuki** [comment]
Hi @s-ilnar!
I don't know anything about Yandex, but in the stackoverflow you mentioned they say the projection is a bit different.
My suggestion would be to create a new class that implements `TileSystem`, a bit like [`TileSystemWebMercator`](https://github.com/osmdroid/osmdroid/blob/master/osmdroid-android/src/main/java/org/osmdroid/util/TileSystemWebMercator.java).
Then something like `MapView.setTileSystem(new TileSystemYandex())`.
cf. #971.
I hope this helps...

**Comment by s-ilnar** [comment]
@monsieurtanuki Hi! Thanks for the help!

**Comment by monsieurtanuki** [comment]
@s-ilnar You're welcome!
If you managed to code a new `TileSystemYandex` class, please create a PR about it.
