### ISSUE TITLE
Map operations is not smooth under a large zoom level (about 21+)

### ISSUE THREAD

**Issue by zzhall** [osmdroid/osmdroid#1701]
Map operations is not smooth under a large zoom level (about 21+), with only a few geo markers and polygons.  But it becomes smooth when i zoom out the mapview to a level below 18. 

I found that onScroll method in MapViewGestureDetectorListener was called in a much smaller frequency under larger zoom level. But I don't know how I can optimize it. 

So, is there any solution to fix this?

**Comment by zzhall** [comment]
I find that it has nothing to do with zoom level. If a polygon covers the most of screen at a zoom level, mapview will always get low performance,  no matter how big the polygon is.

**Comment by monsieurtanuki** [comment]
Hi @zzhall!
I'm surprised by your comments, given what's been done in #1409, #1458 and more specifically #1467 (where we managed to smoothly display a Polygon with 14K points). Could you please have a look at these issues?

**Comment by zzhall** [comment]
Thanks for your reply. I will take a close look at  those  issues later.

**Comment by zzhall** [comment]
Thanks for your reply. I will take a close look at  those  issues later.

**Comment by zzhall** [comment]
I'm using an Android device base on RK3288 development board, which provides poor hardware environment. And that's why I still got this problem discribed in #1467 . _The display of this polygon is very slow if the zoom is much too close. But it's not that slow if the polygon fits the screen._

**Comment by monsieurtanuki** [comment]
@zzhall May be useful to play with hardware acceleration on/off: https://developer.android.com/guide/topics/graphics/hardware-accel
