### ISSUE TITLE
How to Use Google historical images ?

### ISSUE THREAD

**Issue by jinyujie** [osmdroid/osmdroid#1713]
Hello, osmdroid is a very good project. I would like to ask a question, how to use osmdroid to load Google historical images?
tile url like this:"https://khmdb.google.com/flatfile?db=tm&f1-02000123-i.19-f859f"

**Comment by Malvineous** [comment]
I found [this repo](https://github.com/ConorPai/GEDownload/tree/master) that can download the historical images.  Perhaps it can be used as a starting point, as in its current state you have to figure out how to assemble the downloaded .jpg images yourself.
