### ISSUE TITLE
how to adjust detail level of mapnik tiles

### ISSUE THREAD

**Issue by Choongkyu** [osmdroid/osmdroid#1716]
## Issue Type

[x ] Question
[ ] Bug
[ ] Improvement
[ ] Build system related
[ ] Performance
[ ] Documentation

## Description and/or steps/code to reproduce the problem
Hello. I was wondering how I might be able to reduce the level of detail on this mapnik tile-based map, ideally with no buildings. Thank you.
<img width="379" alt="Screen Shot 2021-04-24 at 10 11 55 AM" src="https://user-images.githubusercontent.com/1592194/115972329-8b44ed80-a502-11eb-9834-11d2aec3deec.png">

### Version of osmdroid the issue relates to:

6.1.10

**Comment by monsieurtanuki** [comment]
Hi @Choongkyu!
Technically you cannot remove buildings from the "mapnik" tiles: in osmdroid we display what the tile providers give as JPEG/PNG files.
What you can do is use another tile provider, that chose not to display buildings.

Some links about that:
* https://github.com/osmdroid/osmdroid/wiki/Map-Sources
* https://wiki.openstreetmap.org/wiki/Tile_servers

**Comment by Choongkyu** [comment]
> Hi @Choongkyu!
> Technically you cannot remove buildings from the "mapnik" tiles: in osmdroid we display what the tile providers give as JPEG/PNG files.
> What you can do is use another tile provider, that chose not to display buildings.
> 
> Some links about that:
> 
> * https://github.com/osmdroid/osmdroid/wiki/Map-Sources
> * https://wiki.openstreetmap.org/wiki/Tile_servers

thank you very much!
