### ISSUE TITLE
Text Style in LatLonGridlineOverlay2

### ISSUE THREAD

**Issue by mikebravoyes** [osmdroid/osmdroid#1723]
## Issue Type

[x] Question
[x] Improvement

## Description and/or steps/code to reproduce the problem

@spyhunter99 @monsieurtanuki 

In my opinion, the degree number at the grid lines is hard to read - depending upon the display density (in the screenshot below: 440 dpi). I',m using `setFontColor(Color.BLACK);` and `setBackgroundColor(Color.WHITE);
`

![Screenshot_20210610-153053](https://user-images.githubusercontent.com/6436590/121534731-c55e4600-ca01-11eb-84db-45262f6f9b50.png)

In the code I have seen, that it is initialized with `mTextPaint.setStyle(Paint.Style.STROKE);` I would prefer `FILL_AND_STROKE`. However it's not possible to modify this, because it is defined like this
`private final Paint mTextPaint = new Paint();`

Could you 
a) either change it to `protected` so that I can extend the class or 
b) introduce a new method? 
`public void setTextStyle(Paint paint) { mTextPaint.setStyle(paint); }`

That would be great!

### Version of osmdroid the issue relates to:

6.1.10

**Comment by monsieurtanuki** [comment]
@mikebravoyes Rather than a setter or an "upgrade" to `protected` I would suggest a getter, like in [`PolyOverlayWithIW`](https://github.com/osmdroid/osmdroid/blob/master/osmdroid-android/src/main/java/org/osmdroid/views/overlay/PolyOverlayWithIW.java#L132-L137).
