### ISSUE TITLE
Check if a GeoPoint laid inside Tile X/Y/Z

### ISSUE THREAD

**Issue by yorkw** [osmdroid/osmdroid#1725]
## Issue Type

[x ] Question

## Description and/or steps/code to reproduce the problem

I went through the docs and couldn't find any clues, I wonder if there is a simple way to achieve something like this:

boolean laid = TileSystem.inside(lat, lon, x, y, z);

### Version of osmdroid the issue relates to:

6.1.10

Thanks

**Comment by monsieurtanuki** [comment]
Hi @yorkw!
I guess you could use `tileSystem.getTileXFromLongitude(double longitude, int zoom)` and `tileSystem.getTileYFromLatitude(double latitude, int zoom)`.
Would that work in your use-case?

**Comment by yorkw** [comment]
@monsieurtanuki , thanks for your reply, I think that would be the only way to go at the moment
