### ISSUE TITLE
Additional http request properties get padded when restored from preferences 

### ISSUE THREAD

**Issue by xxfast** [osmdroid/osmdroid#1727]
## Issue Type

[x] Bug

## Description and/or steps/code to reproduce the problem

Setting `Configuration.getInstance().additionalHttpRequestProperties` works for the first initial run. 
```kotlin
@Override
public void onCreate(Bundle savedInstance) {
    ...
    Configuration.getInstance().additionalHttpRequestProperties["Authorization"] = "Basic $TOKEN"
    Configuration.getInstance().load(getApplicationContext(),
            PreferenceManager.getDefaultSharedPreferences(getApplicationContext()));
    Configuration.getInstance().additionalHttpRequestProperties["Authorization"] // prints `Basic $TOKEN`
    ...
}
```
Reopening the app, this no longer works as
```kotlin
@Override
public void onCreate(Bundle savedInstance) {
    ...
    Configuration.getInstance().additionalHttpRequestProperties["Authorization"] = "Basic $TOKEN"
    Configuration.getInstance().load(getApplicationContext(),
            PreferenceManager.getDefaultSharedPreferences(getApplicationContext()));
    Configuration.getInstance().additionalHttpRequestProperties["Authorization"] // prints `Basic $TOKEN    `
    ...
}
```
Note the additional padding at the end of string.

## Possible workaround for now

to always reset the request properties after loading
```kotlin
@Override
public void onCreate(Bundle savedInstance) {
    ...
    Configuration.getInstance().load(getApplicationContext(),
            PreferenceManager.getDefaultSharedPreferences(getApplicationContext()));
    Configuration.getInstance().additionalHttpRequestProperties["Authorization"] = "Basic $TOKEN"
    Configuration.getInstance().additionalHttpRequestProperties["Authorization"] // prints `Basic $TOKEN`
    ...
}
```

## Environment

Android 10

### Version of osmdroid the issue relates to:

6.1.2

**Comment by monsieurtanuki** [comment]
@xxfast Interesting...
If needed, I suggest that you copy `DefaultConfigurationProvider` into your own custom class and debug on it by setting it as the class to use with `Configuration.setConfigurationProvider(myOwnConfigurationProvider)`.

That being said, I don't understand your code: it makes no sense to set a field AND THEN to load the preferences (which may crash your field value).
I would:
1. load the preferences
1. set my field
1. save the preferences

**Comment by xxfast** [comment]
Where in the app lifecycle should these additional headers be set? 🤔

**Comment by monsieurtanuki** [comment]
I think `onCreate` is appropriate, isn't it?

**Comment by spyhunter99** [comment]
onResume might better but it probably depends on your use case. feel free to open a pr if you feel the rest of the community can make use of your changes. reopen this issue if needed
