### ISSUE TITLE
Zoom buttons zoom twice when tapped slowly

### ISSUE THREAD

**Issue by hauke96** [osmdroid/osmdroid#1733]
## Issue Type

[ ] Question
[x] Bug
[ ] Improvement
[ ] Build system related
[ ] Performance
[ ] Documentation

## Description and/or steps/code to reproduce the problem

When tapping a zoom button very slowly, there is a zoom in/out happening on the `ACTION_DOWN` and also on the `ACTION_UP` event, so there are two zooms happening. This doesn't feel right and also [confused an user](https://github.com/hauke96/GeoNotes/issues/47) of an app of mine.

As far as my research goes this is caused by pull request #1471 in the `CustomZoomButtonsDisplay` by [this line](https://github.com/osmdroid/osmdroid/blob/dbb20901cac30b28a6a9349da097c22d9a962311/osmdroid-android/src/main/java/org/osmdroid/views/CustomZoomButtonsDisplay.java#L232). Here both `UP` and `DOWN` events are considered a touch which causes the `CustomZoomButtonsController` to trigger two `onZoom()` calls on the map controller (see e.g. [here](https://github.com/osmdroid/osmdroid/blob/dbb20901cac30b28a6a9349da097c22d9a962311/osmdroid-android/src/main/java/org/osmdroid/views/CustomZoomButtonsController.java#L194)).
If this is not a bug, maybe it's better to somehow configure the behavior on the `CustomZoomButtonsController` class?

### Steps to reproduce

1. Tap and hold on the zoom in/out button
  * Now the map zooms in/out
2. Wait a second until the animation completed
3. Release your finger
  * Another zoom happens

### If it's a bug, version(s) of android this affects:

As far as I know all versions of android are affected.

### Version of osmdroid the issue relates to:

6.1.8

**Comment by monsieurtanuki** [comment]
Hi @hauke96!
It does look like a bug to me.
Feel free to create a PR - I guess `ACTION_DOWN` would be enough, what do you think?

**Comment by hauke96** [comment]
Hi, I think `ACTION_UP` is better suited as it's the default behavior on normal buttons (on desktop systems as well as on android). I currently have little time so it will take a while until I work on this, but it's on my bucket list.

**Comment by monsieurtanuki** [comment]
Fixed by #1775.
