### ISSUE TITLE
MapView fully loaded callback / MapView Screenshot Functionality

### ISSUE THREAD

**Issue by abinpaul1** [osmdroid/osmdroid#1737]
Please note: issues related to or caused by osmbonuspack will be closed with a
suggestion to open an issue at https://github.com/MKergall/osmbonuspack

(feel free to delete whatever doesn't apply)

## Issue Type

[ ] Question
[ ] Bug
[ X] Improvement
[ ] Build system related
[ ] Performance
[ ] Documentation

## Description

Currently there is no option to know when a Mapview is fully loaded with all the tiles. This could be helpful to create a static screenshot of MapView instead of relying on a server-side Static Map API. 
A functionality similar to [snapshot](https://developers.google.com/android/reference/com/google/android/gms/maps/GoogleMap#public-final-void-snapshot-googlemap.snapshotreadycallback-callback,-bitmap-bitmap)  method in Google's MapView would also be useful.

**Comment by monsieurtanuki** [comment]
Hi @abinpaul1!
Actually there's something similar, but maybe not deeply embedded in `MapView`.
It's called `MapSnapshot`.
I think you'll find a couple of demos in the sample app: one that creates bitmaps with up-to-date tiles for USA States, and the other that displays on top of the `MapView` the number of up-to-date and approximated tiles.
Tell me if you do find something close to your needs.

**Comment by abinpaul1** [comment]
Yes. That was exactly what was required. Thanks a lot. 
I wasnt able to find this functionality easily. I would be happy to add documentation or wiki for this option , if you could point me to where I should.

Just adding the snippet to take snapshot of a Mapview hear incase anyone wants a quick sample
```java
final MapSnapshot mapSnapshot = new MapSnapshot(new MapSnapshot.MapSnapshotable() {
            @Override
            public void callback(final MapSnapshot pMapSnapshot) {
                if (pMapSnapshot.getStatus() != MapSnapshot.Status.CANVAS_OK) {
                    return;
                }
                final Bitmap bitmap = Bitmap.createBitmap(pMapSnapshot.getBitmap());
                // Do something with the bitmap like save to file
            }
        }, MapSnapshot.INCLUDE_FLAG_UPTODATE, pMapView);
new Thread(mapSnapshot).start();
```

**Comment by monsieurtanuki** [comment]
@abinpaul1 Cool! Feel free to create a new page in the [wiki](https://github.com/osmdroid/osmdroid/wiki).

**Comment by abinpaul1** [comment]
I have added it here : https://github.com/osmdroid/osmdroid/wiki/Taking-Snapshot-of-Maps

**Comment by monsieurtanuki** [comment]
@abinpaul1 Well done!

There's another demo that could be interesting for you called ["Tile States"](https://github.com/osmdroid/osmdroid/blob/master/OpenStreetMapViewer/src/main/java/org/osmdroid/samplefragments/tileproviders/SampleTileStates.java), based on [`TileStates`](https://github.com/osmdroid/osmdroid/blob/master/osmdroid-android/src/main/java/org/osmdroid/tileprovider/TileStates.java). Each time the map is refreshed, the number of up-to-date/expired/scaled/not-found tiles is computed. Less "callback-style" than `MapSnapshot`, but can be useful too.

Feel free to close this issue.
