### ISSUE TITLE
Enhance save method of MapSnapshot to specify compression type and quality

### ISSUE THREAD

**Issue by abinpaul1** [osmdroid/osmdroid#1741]
## Issue Type

[ ] Question
[ ] Bug
[ X] Improvement
[ ] Build system related
[ ] Performance
[ ] Documentation

## Description and/or steps/code to reproduce the problem

`MapSnapshot` has a method `save` which takes a `File` object to save the bitmap to. By default it is saved as `Bitmap.CompressFormat.PNG` with quality set to `100`.  The save method could take these as arguments as well to provide better customization thereby allowing the user to decide the compression type and quality needed.

**Comment by monsieurtanuki** [comment]
The current implementations in `MapSnapshot` are something like that:
```java
public Bitmap getBitmap() {
    return mBitmap;
}
public boolean save(final File pFile) {
    return save(mBitmap, pFile);
}
private static boolean save(Bitmap pBitmap, File pFile) {
    FileOutputStream out = null;
    try {
        out = new FileOutputStream(pFile.getAbsolutePath());
        pBitmap.compress(Bitmap.CompressFormat.PNG, 100, out);
        return true;
    } catch (Exception e) {
        e.printStackTrace();
    } finally {
        try {
            if (out != null) {
                out.close();
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
    return false;
}
```
I'm not sure osmdroid has the goal to implement all the possible configurations. Rather, we provide a simple example with `save(final File pFile)`, that can be easily duplicated for different needs (add a label, different compression, ...), as long as there's an access to `getBitmap()`.
Especially in Java where optional parameters means additional methods.
@abinpaul1 What's your opinion?

**Comment by abinpaul1** [comment]
Oh okay, that makes sense 👍.  If the goal was to provide a simple example of saving,  this does the job really well.
