### ISSUE TITLE
Use HttpURLConnection instead of HttpClient

### ISSUE THREAD

**Issue by shiroyagi** [osmdroid/osmdroid#175]
Further to https://code.google.com/p/osmdroid/issues/detail?id=273, the HttpClient is being removed from Android 6:
https://developer.android.com/about/versions/marshmallow/android-6.0-changes.html#behavior-apache-http-client

Given the Apache client is so old, HttpURLConnection may also give some performance benefits.
However it is probably worth turning off gzip requests, since image tiles can't be compressed further:
urlConnection.setRequestProperty("Accept-Encoding", "identity");

I'm not sure if it necessary to provide an equivalent of HttpClientFactory, but it would be useful to provide a mechanism for setting other options on the HttpURLConnection (eg. an app specific user-agent string)

**Comment by shiroyagi** [comment]
I am seeing slow tile downloading and related errors which this may improve:
```
10-21 05:21:38.948 E/org.osmdroid.tileprovider.modules.MapTileDownloader( 1123): Error downloading MapTile: /9/253/164
10-21 05:21:38.948 E/org.osmdroid.tileprovider.modules.MapTileDownloader( 1123): java.lang.IllegalStateException: No wrapped connection.
10-21 05:21:38.948 E/org.osmdroid.tileprovider.modules.MapTileDownloader( 1123): 	at org.apache.http.impl.conn.AbstractClientConnAdapter.assertValid(AbstractClientConnAdapter.java:163)

10-21 05:21:41.548 E/org.osmdroid.tileprovider.modules.MapTileDownloader( 1123): Error downloading MapTile: /9/257/169
10-21 05:21:41.548 E/org.osmdroid.tileprovider.modules.MapTileDownloader( 1123): java.lang.ArrayIndexOutOfBoundsException: length=8192; regionStart=-2364; regionLength=10556
10-21 05:21:41.548 E/org.osmdroid.tileprovider.modules.MapTileDownloader( 1123): 	at java.util.Arrays.checkOffsetAndCount(Arrays.java:1732)
10-21 05:21:41.548 E/org.osmdroid.tileprovider.modules.MapTileDownloader( 1123): 	at java.net.PlainSocketImpl.read(PlainSocketImpl.java:484)
10-21 05:21:41.548 E/org.osmdroid.tileprovider.modules.MapTileDownloader( 1123): 	at java.net.PlainSocketImpl.access$000(PlainSocketImpl.java:46)
10-21 05:21:41.548 E/org.osmdroid.tileprovider.modules.MapTileDownloader( 1123): 	at java.net.PlainSocketImpl$PlainSocketInputStream.read(PlainSocketImpl.java:240)
10-21 05:21:41.548 E/org.osmdroid.tileprovider.modules.MapTileDownloader( 1123): 	at org.apache.http.impl.io.AbstractSessionInputBuffer.fillBuffer(AbstractSessionInputBuffer.java:103)
```

**Comment by spyhunter99** [comment]
#158 related issue and already known. If you open a pull request, I can merge

**Comment by MKergall** [comment]
When MapBox made their own fork of osmdroid (https://github.com/mapbox/mapbox-android-sdk-legacy), they replaced HttpClient by OkHttp lib. This is mainly in util/NetworkUtils.java. 
You could get their changes back.

**Comment by shiroyagi** [comment]
Why would you use OkHttp instead of HttpURLConnection?

**Comment by MKergall** [comment]
I'm not specialist, but MapBox guys are. So I imagine it could solves this issue, some others, and may improve downloading speed.

**Comment by shiroyagi** [comment]
Great.  However it does seem to be missing the user-agent string:
c.setRequestProperty("User-Agent","osmdroid");
Although I really think apps should use their own string eg. "MyApp/1.0 osmdroid/4.3" (see terms & conditions of tile providers).

**Comment by spyhunter99** [comment]
ok, i'll add it in momentarily

**Comment by spyhunter99** [comment]
missing client.close, whoops
