### ISSUE TITLE
Indication for “graphics complete”

### ISSUE THREAD

**Issue by mikebravoyes** [osmdroid/osmdroid#1755]
## Issue Type

[X] Question

## Description and/or steps/code to reproduce the problem

@monsieurtanuki 

Is there some way to know for sure if the graphics engine in osmdroid is completely done? If there are numerous overlays, the update may take a while. And I am not allowed to change the underlying data in between, as this could lead to an Exception.

The drawing process is triggered with `mapView.invalidate()` but when does it finish?

### If it's a bug, version(s) of android this affects:

All

### Version of osmdroid the issue relates to:

6.1.11

**Comment by monsieurtanuki** [comment]
Hi @mikebravoyes!
For the record the drawing process is triggered with `mapView.invalidate()` but does not start immediately.
If you want to know when the map and its numerous overlays are all drawn, I would suggest to create a virtual Overlay that does nothing but just runs a callback. If you put it at the end of your Overlay list, when it's "displayed" it's the end of the list: your callback is run when everything else is displayed.
Does that make sense?

**Comment by monsieurtanuki** [comment]
As far as I understand graphics on Android, there's only thread that draws. You can call `invalidate` as often as you want, it's not going to actually start an _immediate_ display refresh. Android will decide when to refresh the display, and will do it in an atomic way.
That's the way things work more specifically in osmdroid, where we spend our time downloading new tiles and asking for a display refresh (with `invalidate`) after each tile is downloaded. And the fact that the display refresh is unique and atomic is essential for some osmdroid features to work: for instance when we display a `Polygon` there's an init phase where we pre-compute data and store them in class fields - that wouldn't be possible if parallel threads were allowed to display at the same time (some pre-computed fields would be overwritten by the other thread).

**Comment by mikebravoyes** [comment]
@monsieurtanuki 
OK, I will make some tests accordingly and let you know...

**Comment by mikebravoyes** [comment]
@monsieurtanuki 
You were right: It had nothing to do with the display refresh. The problem was the following: There is a data set of geographical coordinates, which are translated into one or more `Polyline`s for the map. This data set can be manipulated by two asynchronous threads, which may interfere with each other. To avoid that, I introduced a Semaphore, which is initialized at the start of the app.

`public static Semaphore mutex = new Semaphore(1);`

Then, in the two competing threads, they block each other with:
```
try {
	mutex.acquire();
	// prepare the data set with geographical coordinates
	...
	// generate Polylines from data set
	...
	mapView.invalidate();
} catch (InterruptedException e) {
	e.printStackTrace();
} finally {
	mutex.release();
}
```
And everything works without any problems.
Thanks for your support!

**Comment by monsieurtanuki** [comment]
Async processes are often a source of bug.
I'm glad I was helpful!
Take care @mikebravoyes
