### ISSUE TITLE
Markers disappear inside a MapView in a fragment

### ISSUE THREAD

**Issue by pierluigisupino** [osmdroid/osmdroid#1758]
The markers are no longer visible when changing fragment and then returning to the mapview fragment

Adding markers and geopoints
![Screenshot_1640712150](https://user-images.githubusercontent.com/58226371/147591278-370bf8d2-343a-41a0-852c-531937623cde.png)

After changing fragment and returning
![Screenshot_1640712238](https://user-images.githubusercontent.com/58226371/147591367-1e3fee07-a4ca-4c6d-90bc-a45c5ce35fe3.png)

Affter adding a new marker and geopoint
![Screenshot_1640712283](https://user-images.githubusercontent.com/58226371/147591433-135f8095-4857-42ff-99ff-d597031c2afd.png)

**Comment by monsieurtanuki** [comment]
Hi @pierluigisupino!
It looks like a very nice trip you're planning ;)
Regarding the issue, when do you store and retrieve your markers?

**Comment by pierluigisupino** [comment]
Hi @monsieurtanuki!
Every time I add a new marker (onMapClick) I add its geopoint and if i have more than 1 geopoint i get the road between the geopoints. Should i do something when onResume() is called?

**Comment by monsieurtanuki** [comment]
Unfortunately it's the Android world: every time you go out of your activity or your fragment, you have to store whatever data you were working on. And when you go back to the activity or the fragment, you have to reload everything.
Like when you tilt your smartphone from portrait to landscape.
Here at osmdroid we just display markers on maps. It's your job to store/reload your data.
Does that make sense?

**Comment by pierluigisupino** [comment]
Yes make sense, but when i return to the fragment and place a new geopoint and get the road between the points the road is rendered using also the "invisibles" geopoints like in the 3th image, if a replace all the markes on the map when onResume() is called won't i duplicate all markers and related geopoints?

**Comment by monsieurtanuki** [comment]
I don't know where (and if) you store your markers. If you just create a Marker and put it on the map and think that's enough, that's not good.
I don't know how you compute the road: perhaps the tool you're using stores previous geo points.
I suggest that you add logs to your program, counting for instance the number of overlays and markers of your mapview in the onStop, onPause, onResume, onStart and onCreate events.

**Comment by pierluigisupino** [comment]
Solved, strangely even if I saved my markers in an ArrayList to add them back to the map when onResume is called i had to reset their icon otherwise this was null making the marker be invisible
