### ISSUE TITLE
Request for a Longer Description/Wiki Entry on Retrieving the Location (using Kotlin) Within an OSMDroid-based App

### ISSUE THREAD

**Issue by kwesiRutledge** [osmdroid/osmdroid#1759]
## Issue Type

[ ] Question
[ ] Documentation

## Description and/or steps/code to reproduce the problem

I was interested in retrieving the device's location while running an app that uses OSMDroid and had a very difficult time doing so (I think this is somewhat because I'm new to Android App development and the fact that I've been using Kotlin instead of Java). My proposition is that a new entry to the OSMDroid Wiki be added that teaches how how to get location updates in a manner similar to [Mir1001's repository](https://github.com/Mir1001/MapOsmdroidKotlinExample) of Kotlin code.

I’ve seen 4+ posts on how to get the device’s current location using OSMDroid and Kotlin, but was unable to stitch together their clues to form a working demo in Kotlin. The posts that I considered were:

- [How to add my current location with osmdroid?](https://stackoverflow.com/questions/53651627/how-to-add-my-current-location-with-osmdroid)
- [https://github.com/osmdroid/osmdroid/issues/783](https://github.com/osmdroid/osmdroid/issues/783)
- [https://github.com/osmdroid/osmdroid/issues/917](https://github.com/osmdroid/osmdroid/issues/917)
- [How to Add My Location Overlay (OSMDroid Wiki)](https://github.com/osmdroid/osmdroid/wiki/How-to-use-the-osmdroid-library-(Kotlin)#how-to-add-the-my-location-overlay)

The one demo that seemed to show this functionality in Kotlin was actually this project that I stumbled upon on Github: [https://github.com/Mir1001/MapOsmdroidKotlinExample](https://github.com/Mir1001/MapOsmdroidKotlinExample)

I'd be willing to write the post and would try to decompose it in such a way that future Kotlin users can better understand what elements they need in their app to achieve similar behaviors.

### Version of osmdroid the issue relates to:

6.1.2

**Comment by monsieurtanuki** [comment]
Happy new year @kwesiRutledge!
I believe the wiki is not restricted: thank you in advance for writing that nice doc!

**Comment by kwesiRutledge** [comment]
Sorry for the lack of updates, @monsieurtanuki .

I've placed a draft into the Wiki [here](https://github.com/osmdroid/osmdroid/wiki/Incorporating-Location-Updates-Into-an-OSMDroid-Application-(Kotlin)) and added a link to it at the Wiki's home page. I'll review the entry once more to look for typos, but think that my first pass is done.

I will close the issue for now, but if anyone has questions about the entry or wants to edit then feel free to send the questions to me or just edit it to make it better!

**Comment by monsieurtanuki** [comment]
Thank you @kwesiRutledge!
