### ISSUE TITLE
Set style polylines from shapefile

### ISSUE THREAD

**Issue by samuelBarbarin** [osmdroid/osmdroid#1760]
I am loading polylines in a map from a shapefile with this code
```
folder: List<Overlay> = ShapeConverter.convert(mapView, File(myshape))
mapView.overlayManager.addAll(folder)
mapView.invalidate()
```

From [How to use the osmdroid library (Kotlin)](https://github.com/osmdroid/osmdroid/wiki/How-to-use-the-osmdroid-library-%28Kotlin%29)
Is someone can tell me, how to style these polylines ?

**Comment by monsieurtanuki** [comment]
Hi @samuelBarbarin!
I'm sure you can find advanced examples, for instance in https://github.com/osmdroid/osmdroid/issues/1378 and https://github.com/osmdroid/osmdroid/issues/1551.
My suggestion: download the osmdroid example app, find the example that matches your needs, and have a look at the corresponding code.

**Comment by monsieurtanuki** [comment]
If I remember well `Overlay` is an abstract class, or let's say a generic displayable object.
And if I have a look at the link you provided, I see that `ShapeConverter.convert` outputs items of 3 different classes: `Marker`, `Polyline` and `Polygon`.
I guess you should loop your items and check which are `Polyline`s, and apply the desired style only to them.

**Comment by monsieurtanuki** [comment]
I don't read kotlin, but except the fact that the loop could probably be more elegant (something like `for (myfolder in folder)` if this syntax exists), that's the general idea: you bulk-load data of different types, you want to impact only Polylines so you have to check first.
It looks like you're also dismissing the overlays that are not polylines, is that what you wanted to do?

For the record you can display a more readable source code with 3 back-quotes then the language:
```kotlin
val folder: List<Overlay> = ShapeConverter.convert(map, shp)
        for (i in folder.indices) {
            var ov = folder[i]
            if (folder[i] is Polyline) {
                var pl = folder[i] as Polyline
                pl.setColor(Color.LTGRAY)
                pl.setWidth(2.0f)
                map.overlayManager.add(folder[i])
            }
        }
```

Feel free to close the issue if relevant.

**Comment by monsieurtanuki** [comment]
@samuelBarbarin Don't forget the language for nice colors:
> \`\`\`kotlin

**Comment by samuelBarbarin** [comment]
Learn a lot today, I will glad to show you my project some time
