### ISSUE TITLE
Draw text near the marker

### ISSUE THREAD

**Issue by bkekelic2** [osmdroid/osmdroid#1763]
## Issue Type
[x] Bug

## Description and/or steps/code to reproduce the problem

Hi,
I'm trying to show a marker and text which will be aligned to the left side of the marker and moved along with it. 
I found [this approach](https://stackoverflow.com/a/22428509) which seems working but the issue is that sometimes when the canvas is redrawn (moving the map, updating marker location, etc..) it seems that the old text is **not removed** and the new gets on top of the old one. The result is text which is bolder then the original one. And every few moments it seems to getting bolder and bolder.
I also tested with changing of a text (text + counter) on each redraw and the leftovers can be seen below text. 

I'm wondering why it is happening and how to prevent it. Also, I will appreciate any other ways to do this.
Note: I do need to have also IW functionality.

### If it's a bug, version(s) of android this affects:

Tested on Android 10

### Version of osmdroid the issue relates to:

I'm using osmdroid along with mapsforge.

osmdroid - 6.1.11
mapsforge - 0.10.0

**Comment by eclectice** [comment]
Instead of 

```java
    Point p = this.mPositionPixels;  // already provisioned by Marker
    c.drawText( mLabel, p.x, p.y+20, textPaint); 
```

use `Canvas.save()` and `Canvas.restore()` when drawing and translating a text relative to the symbol's coordinates like this:

```java
    Point p = this.mPositionPixels;  // already provisioned by Marker
    canvas.save();
    canvas.translate(p.x, p.y+20);
    canvas.drawText(mLabel, 0, 0, textPaint);
    canvas.restore();
```

**Comment by bkekelic2** [comment]
Hi @eclectice first of all thanks for the idea.
I tested it and it seems that the issue is still the present (same behavior) - text is drawn on top of the old one every few moments (ca. every 100 drawn)

**Comment by eclectice** [comment]
Hmm, while creating graphical elements for my extended overlay class, I utilize a lot of canvas saves and restores, and all of the overlay's graphical elements are properly displayed when the overlay moves.

Perhaps it necessitates calls to `MapView.invalidate()` or `MapView.postInvalidate()`?

Would you mind sharing the source code for the marker class that uses the method?

**Comment by bkekelic2** [comment]
Finally figured it out. Thanks @eclectice for your indirect help, I was creating simplified version of the app for this post and eventually figured it out. 
The issue was happening because in some cases when the marker was moving I was unnecessary calling `mapView.getOverlays().add(mapMarker);` even if the marker was already there, in overlays, so it was putting both marker and the text on top of each other.

So I just added one check to prevent this to happen:
 `if(!mapView.getOverlays().contains(mapMarker)) mapView.getOverlays().add(mapMarker);`
 
 Thanks again. for your time ;)
