### ISSUE TITLE
Add or remove maps in real-time

### ISSUE THREAD

**Issue by bkekelic2** [osmdroid/osmdroid#1772]
## Issue Type

[x] Question

Hi, 
I'm wondering if there is possibility to add or remove maps in the real-time while the map is still visible (after initial constructor invocation and load of the maps) without reinitialization of complete map and redrawing whole content. 

I can see that there is `private MultiMapDataStore mapDatabase;` variable in `MapsForgeTileSource.java` class but it is not accessible out of the class. 

I'm currently using osmdorid with mapsforge provider with offline maps.

Any idea? Thanks.

### Version of osmdroid the issue relates to:

osmdroid - 6.1.11
mapsforge - 0.10.0

**Comment by monsieurtanuki** [comment]
Hi @bkekelic2!
I don't know that much about MapsForge, and my suggestion is that you copy `MapsForgeTileSource` into your own project and try to achieve what you want - for instance making field `mapDatabase` `public` or `protected`. Maybe you'll also need `MapsForgeTileModuleProvider` and `MapsForgeTileProvider`, but there are not that many MapsForge classes in osmdroid.
I hope you'll achieve what you want, and if you manage to do it please send a PR. Good luck!

**Comment by bkekelic2** [comment]
Hi @monsieurtanuki, 
Thanks for the idea but I eventually ended up with a workaround. 

At first map initialization, I save loaded files into private variable `private List<File> loadedFiles;` and on each `onResume()` event I check if there are some differences (new file added or old one removed) between `loadedFiles` and actual files from the storage. If yes, I just reinit map with new files, update `loadedFiles` and redraw each marker on its last known position. 

Thanks.
