### ISSUE TITLE
Offline satellite view

### ISSUE THREAD

**Issue by bkekelic2** [osmdroid/osmdroid#1774]
## Issue Type

[x ] Question

Hi, I'm using osmdroid + mapsforge for offline maps and it works great for showing "street" view with all customizable details through themes. 
I'm wondering if there is any support for osmdroid to use offline maps with satellite view?
I can see that there is MapBoxTileSource but does it only provide online maps (sth like wrapper for Mapbox SDK for online maps)? 

Thanks in advance.

**Comment by monsieurtanuki** [comment]
Hi @bkekelic2!
Satellite views are just different picture files than street view pictures. And in osmdroid we just say: for this zoom level, x and y, this is the 256x256 bitmap we should download/display/refresh. Satellite or street view, whatever.
That said, I don't know if offline use complies with MapBox's licence. Beyond that, from what I saw in [`MapBoxTileSource`](https://github.com/osmdroid/osmdroid/blob/master/osmdroid-android/src/main/java/org/osmdroid/tileprovider/tilesource/MapBoxTileSource.java) MapBox is not very different from the more open tile sources, therefore accessing offline data shouldn't be a technical issue.

**Comment by bkekelic2** [comment]
Hi @monsieurtanuki, thanks for the feedback. I think it is clear what the obstacle here is, so okay. I will close this issue for now, and if I came back with some questions when I get back to this topic I will reopen this issue or open the new one. 

Thanks again.
