### ISSUE TITLE
Build setup

### ISSUE THREAD

**Issue by spyhunter99** [osmdroid/osmdroid#1776]
## Issue Type

[ ] Build system related

## Description and/or steps/code to reproduce the problem

Per https://developer.android.google.cn/studio/build/maven-publish-plugin
it might be time to revisit the build system setup. I know everyone has various issues with the current outdated build tech. It would be nice if we can prototype a new setup, attempt to publish to maven central and if successful, merge and carry on

**Comment by spyhunter99** [comment]
well i made an attempt starting with this branch https://github.com/osmdroid/osmdroid/pull/1705
ended up on jdk 11, gradle 7.0, android-plugin version 7.0.0

long story short, i got to the point where i could compile and test osmdroid-android and i have a maven publish setup...only thing is `gradlew publish` does absolutely nothing. i'm giving up for now. if someone else wants to tackle this, i'll get them setup with osmdroid's signing keys and a sonatype oss account. 

alternatively, one can download sonatype oss and run it locally for testing, however be warned that the default setup is not the same as the central's publishing rules.

**Comment by monsieurtanuki** [comment]
Good luck!

**Comment by spyhunter99** [comment]
@monsieurtanuki i had a thought on how to satisfy both the requirements of being able to publish to central and using a more modern build stack. It's super hacky but i think it would work.

- remove gradle fury (most of it)
- use the newer build stack, javadocs and source jars included
- have a standalone module or simply a bash script or something that updates a static pom file to have the right version, does the signatures, etc and then uploads, using the artifacts already generated from the previous build steps

down sides

- the pom's dependencies may get out of sync vs what gradle is using

other options

- write a parse for the gradle build file, then dynamically generate the pom file


any thoughts on this?

**Comment by monsieurtanuki** [comment]
Hi @spyhunter99! Unfortunately I have no idea what you're talking about: I'm good at coding (sometimes) but I'm absolutely clueless regarding compilation (not even sure that "compilation" is the correct word here).

Very puzzled about how complicated it looks to generate code. As osmdroid is very old now, and assuming that improvements arrived in the last years regarding "compilation" on Android, I would start from scratch the compilation part. The simplest possible, whatever works, removing all the "just in case" parts that used to seem relevant in some rare cases that we know now will not happen.

**Comment by spyhunter99** [comment]
making progress. soon, we'll be at the latest of the latest and we'll still be able to publish to central, ironically, not using gradle

**Comment by monsieurtanuki** [comment]
Awesome!
