### ISSUE TITLE
Could not rad script  'https://raw.githubusercontent.com/gradle-fury/gradle-fury/v1.1.4/gradle/maven-suppoirt.gradle

### ISSUE THREAD

**Issue by xuzhanya** [osmdroid/osmdroid#1777]
FAILURE: Build failed with an exception.

* Where:
Build file 'D:\WorkCodesDir\MpxMobile\OsmDroidMap\osmdroid\build.gradle' line: 29

* What went wrong:
A problem occurred evaluating root project 'osmdroid-parent'.
> Could not read script 'https://raw.githubusercontent.com/gradle-fury/gradle-fury/v1.1.4/gradle/maven-support.gradle'.
   > Connection timed out: connect

## Environment
Android Studio BunbleBee 2021.1.1 Patch 2

### If it's a bug, version(s) of android this affects:

All

### Version of osmdroid the issue relates to:

6.1.2

**Comment by eclectice** [comment]
You can refer to my guide on how to successfully build OSMDroid without the Gradle Fury scripts

https://github.com/osmdroid/osmdroid/issues/1756#issue-1084559601

**Comment by spyhunter99** [comment]
are you connected to the internet?

**Comment by spyhunter99** [comment]
fixed via #1776
