### ISSUE TITLE
Can not change tile to USGS_SAT or USGS_TOPO

### ISSUE THREAD

**Issue by Saschawho** [osmdroid/osmdroid#1778]
In my Kotlin study I got the assessment to change the map to a satellite view and in another version to a topographic view.

This is the part of my code:

"val osmConfig = Configuration.getInstance()  
osmConfig.userAgentValue = packageName
val basePath = File(cacheDir.absolutePath, "osmdroid")  
osmConfig.osmdroidBasePath = basePath  
val tileCache = File(osmConfig.osmdroidBasePath, "tile")  
osmConfig.osmdroidTileCache = tileCache  
val map = findViewById<MapView>(R.id.mapview)  
map.setTileSource(TileSourceFactory.DEFAULT_TILE_SOURCE)"

I checked, which Tilesources are out there and I guess, USGS_SAT and USGS_TOPO could be the right sources for the desired views. Unforunately, when I just change the "DEFAULT_TILE_SOURCE" of the last line to USGS_SAT or USGS_TOPO, I do not get any map graphics when running my app - anchor is there, but the map is blank. Others from the list of the OSMDroid site are working. So I expect my "solution" to be right. Are USGS_SAT and USGS_TOPO broken? Or is my solution wrong?

Thanks a lot!

**Comment by monsieurtanuki** [comment]
Hi @Saschawho!

First thing, please consider [learning how to write code on github comment](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code):
```kotlin
val osmConfig = Configuration.getInstance()
osmConfig.userAgentValue = packageName
val basePath = File(cacheDir.absolutePath, "osmdroid")
osmConfig.osmdroidBasePath = basePath
val tileCache = File(osmConfig.osmdroidBasePath, "tile")
osmConfig.osmdroidTileCache = tileCache
val map = findViewById(R.id.mapview)
map.setTileSource(TileSourceFactory.DEFAULT_TILE_SOURCE)
```
Easier to read, right?

Then, if you have a look at the code for USGS_SAT in [`TileSourceFactory`](https://github.com/osmdroid/osmdroid/blob/master/osmdroid-android/src/main/java/org/osmdroid/tileprovider/tilesource/TileSourceFactory.java#L188-L194), you'll see the pattern of the tile URL:
```java
public static final OnlineTileSourceBase USGS_SAT = new OnlineTileSourceBase("USGS National Map Sat", 0, 15, 256, "",
            new String[]{"https://basemap.nationalmap.gov/arcgis/rest/services/USGSImageryTopo/MapServer/tile/"}, "USGS") {
        @Override
        public String getTileURLString(final long pMapTileIndex) {
            return getBaseUrl() + MapTileIndex.getZoom(pMapTileIndex) + "/" + MapTileIndex.getY(pMapTileIndex) + "/" + MapTileIndex.getX(pMapTileIndex);
        }
    };
```
That means that the tile of the world (zoom = 0, X = 0, Y = 0) can be found at https://basemap.nationalmap.gov/arcgis/rest/services/USGSImageryTopo/MapServer/tile/0/0/0 (and it works, at least from my web browser).

Perhaps they need the [user agent to be properly populated](https://github.com/osmdroid/osmdroid/wiki/How-to-use-the-osmdroid-library-(Java)#main-activity), I don't know.

My suggestion: download the osmdroid sample app, and try to display maps with satellite as tile source. If it works with the osmdroid sample app, there is probably an error in your code.

Good luck!

**Comment by Saschawho** [comment]
Thank you very much!

It works in the sample app. Need to work on my code maybe. For me it is still some kind of hard to read Java code and doctor right things in Kotlin. But I will take a look.

Thank you as well for pointing out, how to format code correctly here on GitHub. :)
