### ISSUE TITLE
No direct method <init>(Ljava/lang/String;Ljava/lang/String;Lorg/osmdroid/util/GeoPoint;)V in class Lorg/osmdroid/views/overlay/OverlayItem; or its super classes (declaration of 'org.osmdroid.views.overlay.OverlayItem'

### ISSUE THREAD

**Issue by bhadra272727** [osmdroid/osmdroid#1779]
Please note: issues related to or caused by osmbonuspack will be closed with a
suggestion to open an issue at https://github.com/MKergall/osmbonuspack

(feel free to delete whatever doesn't apply)

## Issue Type

[ ] Question
[ ] Bug
[ ] Improvement
[ ] Build system related
[ ] Performance
[ ] Documentation

### If it's a bug, version(s) of android this affects:

All

### Version of osmdroid the issue relates to:

6.1.2

**Comment by spyhunter99** [comment]
i went through the version history of this class and did not see a constructor matching those parameters. How did you get this error message? Currently it's a title (string), description (string) and a geopoint. There's also additional constructors. 
I'd suggest updating your code
