### ISSUE TITLE
How to use sqlite database with Osmdroid?

### ISSUE THREAD

**Issue by KotofeyKotofeevich** [osmdroid/osmdroid#1780]
How to use sqlite database with Osmdroid?
to view online?

now i have:
cache.db-journal
cache.db

I need it to be like this:

map1.db-journal
map1.db

GoogleHybrid.db-journal
GoogleHybrid.db

GoogleSatellite..db-journal
Google Satellite.db

**Comment by spyhunter99** [comment]
view online? like in a browser?

**Comment by spyhunter99** [comment]
you can browse the database using the sqlite command line utility or the firefox plugin. The database can also be used by osmdroid, there's a few examples in the sample app. The database can also be used by an offline tile server. This can wired up to open layers or a number of other gis javascript libraries or pulled from osmdroid using a custom online tile provider to the tile server. hope this helps

**Comment by KotofeyKotofeevich** [comment]
> view online? like in a browser?

When I view the online map in MapView, everything is put together in this database:

/osmdroid/tiles/
cache.db-journal
cache.db
osmdroid out of the box support...

I wanted everything to be separate.

**Comment by KotofeyKotofeevich** [comment]
Test

**Comment by spyhunter99** [comment]
https://github.com/osmdroid/osmdroid/blob/master/OpenStreetMapViewer/src/main/java/org/osmdroid/samplefragments/tileproviders/OfflinePickerSample.java

**Comment by spyhunter99** [comment]
normally, it will load it up, but since the newer versions of android, lots of permissions related issues

**Comment by spyhunter99** [comment]
reopen or comment if there are further questions
