### ISSUE TITLE
TileSource response Forbidden

### ISSUE THREAD

**Issue by JaizPal** [osmdroid/osmdroid#1786]
[ ] Question
[ *] Bug
[ ] Improvement
[ ] Build system related
[ ] Performance
[ ] Documentation

## Description and/or steps/code to reproduce the problem
Hi. I'm trying to change TileSource and i have this log and the map not show:

> W/OsmDroid: Problem downloading MapTile: /15/16048/12121 HTTP response: Forbidden

I have read a lot about this bug, like: #366 

I include in my code this:
`Configuration.getInstance().userAgentValue = BuildConfig.APPLICATION_ID`

` val provider: Array<String> =
            arrayOf("https://tile.thunderforest.com/spinal-map/{z}/{x}/{y}.png?apikey=" + apiKey) `
`val tileSource = XYTileSource(
            "cycle",
            0,
            18,
            256,
            ".png",
            provider,
            "© Colaboradores de OpenStreetMap",
            TileSourcePolicy(2, TileSourcePolicy.FLAG_USER_AGENT_MEANINGFUL)
        )`

I don´t understand what is happening. 
Can someone help me?
Thanks.

**Comment by monsieurtanuki** [comment]
Hi @JaizPal!
Simple questions:
* does it work if you open a web browser and go to "https://tile.thunderforest.com/spinal-map/{z}/{x}/{y}.png?apikey=" + apiKey ?
* are there explicit limitations by your tile provider that you don't know?

**Comment by JaizPal** [comment]
> /15/16048/12121

- Yes, it's working
![image](https://user-images.githubusercontent.com/92947225/161926421-29d98343-695a-41e2-8da4-0d3aa172cc5a.png)

- Maybe, but I think I'm within those limitations although I don't understand much OSMdroid

I'm working in a final school project and i want to change map style/theme but i think all tile server have restrictions and i can´t use.

Thanks for reply.

**Comment by monsieurtanuki** [comment]
@JaizPal I'm sure you can find decent tile sources in [`TileSourceFactory`](https://github.com/osmdroid/osmdroid/blob/master/osmdroid-android/src/main/java/org/osmdroid/tileprovider/tilesource/TileSourceFactory.java). Or find inspiration there for good parameters. Good luck!

**Comment by JaizPal** [comment]
> @JaizPal I'm sure you can find decent tile sources in [`TileSourceFactory`](https://github.com/osmdroid/osmdroid/blob/master/osmdroid-android/src/main/java/org/osmdroid/tileprovider/tilesource/TileSourceFactory.java). Or find inspiration there for good parameters. Good luck!

Okay, thank you very much.
WIKIMEDIA is lovely :)
