### ISSUE TITLE
Config broken after Micro SD card change

### ISSUE THREAD

**Issue by PHolzwarth** [osmdroid/osmdroid#1787]
## Issue Type

[ ] Question
[x] Bug
[ ] Improvement
[ ] Build system related
[ ] Performance
[ ] Documentation

## Description and/or steps/code to reproduce the problem

1) have a micro SD card in your device that has more free memory than the main storage.
2) use OsmDroid
3) exchange or remove the micro SD card
4) use OsmDroid again

-> Configuration will still try to use the previous path.

## Suggested fix
In DefaultConfigurationProvider, exchange line 328
```
        if (!prefs.contains("osmdroid.basePath")) {
```
with these two lines:
```
        String basePathStr= prefs.getString("osmdroid.basePath", null);
        if (basePathStr==null || !new File(basePathStr).exists()) {
```

### If it's a bug, version(s) of android this affects:

All

### Version of osmdroid the issue relates to:

6.1.2

**Comment by spyhunter99** [comment]
Can you do a pr for this?
