### ISSUE TITLE
ViewPager MapVIew in fragment

### ISSUE THREAD

**Issue by moctavianro** [osmdroid/osmdroid#1789]
[ ] Question
[ ] Bug

When add a fragment with a maview in a viewpager, it show the map only the fisrt time, after navigating trough viewpager fragments, when got back to mapview fragment, the tiles wont show and get this message: TileLoader failed to load tile due to mWriter being null (map shutdown?)

Thanks!

**Comment by moctavianro** [comment]
nobody?... no one?...

**Comment by spyhunter99** [comment]
i think we have a sample in the sample app that does what you described. You may want to take a look at it. Sounds like a lifecycle issue

**Comment by moctavianro** [comment]
> i think we have a sample in the sample app that does what you described. You may want to take a look at it. Sounds like a lifecycle issue

Thanks! Do you have a link? Thanks again.

**Comment by spyhunter99** [comment]
https://github.com/osmdroid/osmdroid/blob/master/OpenStreetMapViewer/src/main/java/org/osmdroid/samplefragments/layouts/MapInAViewPagerFragment.java

**Comment by spyhunter99** [comment]
reopen if needed
