### ISSUE TITLE
Higher zoom than TileSource supports shows blank tile

### ISSUE THREAD

**Issue by anox1337** [osmdroid/osmdroid#1790]
## Issue Type

[ X] Question
[ ] Bug
[ ] Improvement
[ ] Build system related
[ ] Performance
[ ] Documentation

## Description and/or steps/code to reproduce the problem
I am using the tile source of https://a.tile.openstreetmap.de/ which has a maximum zoom level of 19. If I load the map using zoomlevel 19 or lower then the map loads as expected. When I then zoom into the map osmdroid scales the loaded tiles correctly.
The problem arises if the map zoom is set to something higher (like 23) before the tiles have been loaded. The Tile source then cannot find the tiles because of the out-of-scope zoom level and thus osmdroid can't scale them.

I don't really know if this is a issue or if I am missing something. My workaround currently is setting the zoom of the map to a value the tilesource can support and then after 1 second I zoom in. But this is really messy. Another idea would be to have the tilesource zoom "max-out" at 19 and keep requesting those tiles instead of the real zoom (e.g. 23) 

Any hints?

### Version of osmdroid the issue relates to:

6.1.11

**Comment by monsieurtanuki** [comment]
Hi @anox1337!
Interesting question. I have a suggestion:
* in `MapTileProviderBasic`
* we sort of pre-compute other tiles than the displayed tiles
* I can't remember if we _download_ those tiles or if we give them a higher priority in the cache pool
* but if we do download them there, you would just have to say "please download zoom level - 4" (4 = 23 - 19)
* the current code is `getTileCache().getProtectedTileComputers().add(new MapTileAreaZoomComputer(-1));`
* I suggest that you copy/paste `MapTileProviderBasic` and try with zooms -1, -2, -3 and -4

Tell me if it worked!

**Comment by anox1337** [comment]
Hello @monsieurtanuki ,

at a first glance, your idea seems to work. Thank you!
Since I don't know beforehand what zoomlevel I will be using ( I zoom in on user-created polygons so really tiny ones will have a higher zoom ) I have to find a way to dynamically set the correct `ZoomDelta`. Depending on the current zoom.
I tried -5 ( for even the most extreme cases ) but then even the "casual" zoomlevels get pixelated. 
I tried adding more `MapTileAreaZoomComputers` ( -1, -2, -3, -4, -5 ) and that seems to be okay. But I don't know yet if having 5 `zoomcomputers` will have a big impact on performance.

But I guess I have everything to work it out. Thanks again for helping!

**Comment by monsieurtanuki** [comment]
@anox1337 You're welcome!
I suggest that you limit your map zoom level to some decent value - e.g. 24 - even if the polygon area is smaller.
-1, -2, -3, -4, -5 should keep you ok up to zoom level 24 (from a zoom 19 source).
That should have minimum impact on the performances, as each time you go one level up (-1) there are 4 times less tiles. 1 tile of zoom 19 becomes 4^5 = 1024 tiles of zoom level 24 - on the other direction it means that 1024 tiles of zoom level 24 have the same zoom 19 tile. What I mean is that you won't download that much tiles as you're downloading tiles of smaller zoom levels.
Feel free to close the issue if relevant.
