### ISSUE TITLE
Get location in polygon and polyline 

### ISSUE THREAD

**Issue by radosimarmata** [osmdroid/osmdroid#1792]
Please note: issues related to or caused by osmbonuspack will be closed with a
suggestion to open an issue at https://github.com/MKergall/osmbonuspack

(feel free to delete whatever doesn't apply)

## Issue Type

[x ] Question
[ ] Bug
[ ] Improvement
[ ] Build system related
[ ] Performance
[ ] Documentation

## Description and/or steps/code to reproduce the problem

How to read polygon and polyline if my location inside that?

### If it's a bug, version(s) of android this affects:

All

### Version of osmdroid the issue relates to:

6.1.2

**Comment by spyhunter99** [comment]
What?

**Comment by spyhunter99** [comment]
this is more of a geometry problem than an osmdroid issue. Open a pr if you come up with a solution. Also, keep in mind the date line may be an issue
