### ISSUE TITLE
removing range checks on geopoint

### ISSUE THREAD

**Issue by spyhunter99** [osmdroid/osmdroid#1794]
Please note: issues related to or caused by osmbonuspack will be closed with a
suggestion to open an issue at https://github.com/MKergall/osmbonuspack

(feel free to delete whatever doesn't apply)

## Issue Type

[ ] Question
[ ] Bug
[ ] Improvement
[ ] Build system related
[ ] Performance
[ ] Documentation

## Description and/or steps/code to reproduce the problem

Currently we have range checks in geopoint that matches the bounds of the web mercator projection which is +-85 lat. This has causes a lot of undue problems with apps not validating this,causing a npe and crashing. I think we should drop that range check or at lease move to 90 degree threshold

Any thoughts in this?

### If it's a bug, version(s) of android this affects:

All

### Version of osmdroid the issue relates to:

6.1.2

**Comment by monsieurtanuki** [comment]
Hi @spyhunter99!

I know that in many cases developers opened issues about bounding box exceptions.
Actually the problem is not the exception, but the given value that is beyond the limits.

Here my suggestions:
* a more verbose message that include the "wrong" value, like `"north (" + north + ") must be in " + tileSystem.toStringLatitudeSpan()` (right now we don't print the off-limit value)
* a bounding box leniency mode in the preferences, with
  * a STRICT mode (like now) (default)
  * a WARNING mode (no exception, just `Log.w` when off limits)
  * a TRUNC mode (when off limit, put the exceeded limit value instead)

What do you think of that?

**Comment by spyhunter99** [comment]
i think changing it back to just a warning is more appropriate. rendering near the poles with web mercator is and always will be a bit funky

**Comment by spyhunter99** [comment]
after thinking about this some more, i think  > tile system bounds but <= lat/lon maxs should be allowed, but beyond the min/max of the lat/lon coordinates should not be allowed.

**Comment by monsieurtanuki** [comment]
The initial point of the exception was not "thy data is evil therefore thou shall crash", but the mere fact that we cannot compute data beyond the limits (e.g. `tan(pi/2)`). If "our" exception does not crash first (with a verbose message), then it's going to crash later (without a verbose message).

If you really want to be lenient, the "trunc" mode would make sense: if the value is beyond the limit, we put the limit instead.
That could also mean creating a sibling to `TileSystemWebMercator`, where we never crash and apply this "trunc" fix. Of course there might be side-effects (there already are) if you expect some bijection between geopoint and X01/Y01.

**Comment by spyhunter99** [comment]
hmm what if we "correct" the points above the tile system limit?

if lat > tileSystemLimit then lat = titleSystemLimit

**Comment by monsieurtanuki** [comment]
That's what I meant with "trunc mode": "if the value is beyond the limit, we put the limit instead".

That would look a bit like that:
```java
package org.osmdroid.util;

public class TileSystemWebLenientMercator extends TileSystemWebMercator {

    @Override
    public double getX01FromLongitude(final double pLongitude) {
        return super.getX01FromLongitude(cleanLongitude(pLongitude));
    }

    @Override
    public double getY01FromLatitude(final double pLatitude) {
        return super.getY01FromLatitude(cleanLatitude(pLatitude));
    }

    @Override
    public boolean isValidLongitude(final double pLongitude) {
        return true;
    }

    public boolean isValidLatitude(final double pLatitude) {
        return true;
    }
}
```
