### ISSUE TITLE
Map source HTTP not found

### ISSUE THREAD

**Issue by ser-gent** [osmdroid/osmdroid#1796]
Please note: issues related to or caused by osmbonuspack will be closed with a
suggestion to open an issue at https://github.com/MKergall/osmbonuspack

(feel free to delete whatever doesn't apply)

## Issue Type

[x] Question
[x] Bug
[ ] Improvement
[ ] Build system related
[ ] Performance
[ ] Documentation

## Description and/or steps/code to reproduce the problem
In my project, I would use `USGS_SAT` tile source

```
map.setTileSource(TileSourceFactory.USGS_SAT);
```

The map is not displayed and the following error appears:
```
W/OsmDroid: Problem downloading MapTile: /15/17216/12125 HTTP response: Not Found
W/OsmDroid: Problem downloading MapTile: /15/17215/12126 HTTP response: Not Found
W/OsmDroid: Problem downloading MapTile: /15/17217/12124 HTTP response: Not Found
```

When I use `MAPNIK` tile source it's working fine. 
What is the solution to this?

### If it's a bug, version(s) of android this affects:

API 29 / 30

### Version of osmdroid the issue relates to:

6.1.2

**Comment by monsieurtanuki** [comment]
Hi @ser-gent!
Probably duplicate with #1778
Please close the issue if relevant.

**Comment by ser-gent** [comment]
Hi !
I have identified the problem: the online source base return HTTP 404 when the zoom level is higher than 8.0. On the official website, I can't access to a layer higher than 8. 
[https://basemap.nationalmap.gov/arcgis/rest/services/USGSImageryOnly/MapServer](https://basemap.nationalmap.gov/arcgis/rest/services/USGSImageryOnly/MapServer)
Internet pages are inaccessible.

Is it the same for you?

**Comment by monsieurtanuki** [comment]
Maybe they changed their policy and restricted to zoom level 8.
On the website I can reach zoom levels higher than 8:
![Capture d’écran 2022-05-03 à 10 07 49](https://user-images.githubusercontent.com/11576431/166421880-f3122d65-5f34-49fb-913a-00b74d0e6217.png)
You can try to find another satellite tile source if needed.

**Comment by ser-gent** [comment]
Ok fine i will try with an another satellite tile source thanks
