### ISSUE TITLE
How to retrieve ICAO airport code from geo location

### ISSUE THREAD

**Issue by mikebravoyes** [osmdroid/osmdroid#1797]
Please note: issues related to or caused by osmbonuspack will be closed with a
suggestion to open an issue at https://github.com/MKergall/osmbonuspack

(feel free to delete whatever doesn't apply)

## Issue Type

[x] Question
[x] Improvement

## Description and/or steps/code to reproduce the problem

@monsieurtanuki @spyhunter99 

With the class `GeoCoder` (method `getFromLocation`) it is possible to translate a geographic location (lat/lon) into an address: country, city, zip code, street, number, etc. The method `getFromLocationName` handles the opposite direction.

In my app "SensorRecording" I am using the tile source "open AIP map" as overlay. It contains information about airports worldwide, such as ICAO code, radio frequency, length of runway, altitude above MSL (mean sea level). See screenshot below:

![Screenshot_20220507-113419](https://user-images.githubusercontent.com/6436590/167248870-431254bd-d589-46bc-85fd-8ae54c6a5030.png)

The information can be seen on the graphic, but is it also possible, to retrieve the ICAO code programmatically as a function of the location?

### If it's a bug, version(s) of android this affects:

All

### Version of osmdroid the issue relates to:

6.1.11

**Comment by spyhunter99** [comment]
outside the scope of this project. osmdroid provides screen coordinates to lat/lon but that's about it. you'll need an external data source, database, rest service, etc to get an airport code. We don't provide anything like that. The data you're looking for may be in open street map's databases, but osmdroid is just a presentation mechanism for raster map tiles

**Comment by mikebravoyes** [comment]
Anyway, thanks for your advice!
