### ISSUE TITLE
osmdroid repeatedly download map when zoom in

### ISSUE THREAD

**Issue by bigmisspanda** [osmdroid/osmdroid#1799]
Hello. Thanks for your work!
## Issue Type
[ x] Question
[ ] Bug
[ ] Improvement
[ ] Build system related
[ ] Performance
[ ] Documentation
## Description and/or steps/code to reproduce the problem
**when using geoserver wms service offline map,osmdroid repeatedly download map when zoom in**
![d9210062d8cce9cb827b667c1442d57](https://user-images.githubusercontent.com/12532421/167333992-84592895-4ede-4668-b1d3-6ba8e036d007.jpg)
```

`HttpURLConnection c = null;
            InputStream is = null;
            WMSEndpoint wmsEndpoint = null;
            try {
                c = (HttpURLConnection) new URL("http://192.168.0.125:8080/geoserver/topp/wms?service=WMS&version=1.1.1&request=GetCapabilities").openConnection();
            } catch (IOException e) {
                e.printStackTrace();
            }
            try {
                is = c.getInputStream();
            } catch (IOException e) {
                e.printStackTrace();
            }
            try {
                wmsEndpoint = WMSParser.parse(is);
            } catch (Exception e) {
                e.printStackTrace();
            }
           WMSLayer layer = wmsEndpoint.getLayers().get(3);
           WMSTileSourceSelf tileSource =WMSTileSourceSelf.createFrom(wmsEndpoint, layer);
            map.setVerticalMapRepetitionEnabled(false);
            map.setHorizontalMapRepetitionEnabled(false);
           if (layer.getBbox() != null) {
               map.zoomToBoundingBox(layer.getBbox(),true);
           }
            map.setTileSource(tileSource);
        }`
```

**here is my snippet of OnlineTileSourceBase implemention which I hardcode getTileURLString for simple purpose**
```
`  @Override
    public String getTileURLString(final long pMapTileIndex) {
        return "http://192.168.0.125:8080/geoserver/topp/wms?service=WMS&version=1.1.0&request=GetMap&layers=topp:states&bbox=-124.73142200000001,24.955967,-66.969849,49.371735&width=768&height=330&srs=EPSG:4326&styles=&format=image/png&transparent=true";
    }
`
```

### Version of osmdroid the issue relates to:

6.1.2

**Comment by monsieurtanuki** [comment]
Hi @bigmisspanda!

It looks like your problem is not that the map is being _downloaded_ several times, it's that the map is being _displayed_ several times.
I suggest the following methods in `MapView`:
* `setHorizontalMapRepetitionEnabled(false)`
* `setVerticalMapRepetitionEnabled(false)`
* `setMinZoomLevel(double)`

**Comment by bigmisspanda** [comment]
> 

@monsieurtanuki 
thanks for you advise,but I set repetition to false ,your can check my snippet code above and  I debug to the MapViewZoomListener  **show that when zoom in event occur,a MapTileDownloader$TileLoader thread was invoked to download the same map**.below was the stack 
![1652082196(1)](https://user-images.githubusercontent.com/12532421/167363469-f6aecd7f-153a-4623-a750-4d528e7eeab4.png)
I'm new to this map engine and Android development any advice was helpful.
thanks.

**Comment by monsieurtanuki** [comment]
If you're new to Android development, my suggestion is to run away! Use `flutter` instead.
Besides, I was just commenting regarding maps in general, but I have no previous experience with WMS.
Still strange to see the map replicated. Try to put `setTileSource` as early as possible, e.g. before `map.setVerticalMapRepetitionEnabled(false);map.setHorizontalMapRepetitionEnabled(false);`.

**Comment by bigmisspanda** [comment]
@monsieurtanuki 
thanks for your help ^_^. I will go deep into the code to see what will find before try other solutions.
