### ISSUE TITLE
GEMF files not shown

### ISSUE THREAD

**Issue by MKergall** [osmdroid/osmdroid#18]
What has been done : 
Create an atlas with MOBAC 1.9.16, using "Osmdroid GEMF" format and "OpenStreetMap MapQuest" as source, and selecting (at least) zoom level 0. 
File "Layer.gemf" transfered on the device in the existing /sdcard/osmdroid path. 

Then, in a basic app based on osmdroid 4.1 (app which works fine with the default Mapnik Tile Source), change to this tile source: 

map.setTileSource(new XYTileSource("MapQuest",
	ResourceProxy.string.mapquest_osm, 0, 18, 256, ".jpg", new String[] {
		"http://otile1.mqcdn.com/tiles/1.0.0/map/",
		"http://otile2.mqcdn.com/tiles/1.0.0/map/",
		"http://otile3.mqcdn.com/tiles/1.0.0/map/",
		"http://otile4.mqcdn.com/tiles/1.0.0/map/" }));
map.setUseDataConnection(false);
mapController.setZoom(0);

Result: only the "grey grid" is shown. 

More info (tracing with the debugger): 

The file is properly detected and loaded as an archive file (in GEMFFile#openFiles). 
At display, proper range (x=0,y=0,z=0) is detected (in GEMFFile#getInputStream, line "range = rs;" is reached)

The big issue occurs in BitmapTileSourceBase#getDrawable, at line: 
  final Bitmap bitmap = BitmapFactory.decodeStream(aFileInputStream, null, bitmapOptions);
=> this call never exit!

**Comment by spyhunter99** [comment]
old issue, but i just merged some code to remove slf4j. all log output now goes to android's logcat

**Comment by spyhunter99** [comment]
i had some time to look at this, same scenario with jpegs.

Confirming same behavior as detailed above.
final Bitmap bitmap = BitmapFactory.decodeStream(aFileInputStream, null, bitmapOptions);

Just guessing, but this looks like a google problem, not ours.
See https://code.google.com/p/android/issues/detail?id=6066

I tried their work around but it didn't work :(

**Comment by MKergall** [comment]
I don't think it's similar to https://code.google.com/p/android/issues/detail?id=6066
- They report that BitmapFactory.decodeStream() returns null, I think that in our case, it never returns. 
- We have this issue when using GEMF format. Not with MapQuest online tiles (which are jpeg), or with jpg in a ZIP. 
- Apparently, the same issue occurs with the same GEMF files on a QT viewer. 

So I really suspect MOBAC GEMF encoding.

**Comment by spyhunter99** [comment]
@MKergall want to open a mobac bug report?

**Comment by spyhunter99** [comment]
#615 fix
