### ISSUE TITLE
Geopackage support

### ISSUE THREAD

**Issue by spyhunter99** [osmdroid/osmdroid#180]
add support for geopackage storage formats
http://www.geopackage.org/spec/

**Comment by spyhunter99** [comment]
found an android friendly provider that provides tiles via google maps tile provider
https://github.com/ngageoint/geopackage-android

**Comment by spyhunter99** [comment]
quick update, i was able to get this to work, however the performance was terrible when using it synchronously. when loading the tiles asynchronously, tiles just don't show up and i'm not entirely sure why.

**Comment by spyhunter99** [comment]
I wrote a tool which enables you to preconvert geopack files into osmdroid sqlite databases. This more or less meets the objective. It can be found here: https://github.com/spyhunter99/geopkg4osmdroid

**Comment by legrostdg** [comment]
It would be cool to support geopackage directly in osmdroid: it is a standard and is supported by gdal, which permits conversion from a lot of formats. Maybe the performance of geopackage-android has improved during the last year?

**Comment by spyhunter99** [comment]
Looking back, I think the issue was related to database indexing. There is
a project which converts raster tiles in geopackage into osmdroid format
(see the wiki/related projects). Including the GRL package with an example
in osmdroid is feasible, however vector data probably wont' be supportable
(at least easily)

**Comment by spyhunter99** [comment]
@legrostdg you sir, are in luck. I still have the on device code. I'll see if it can be updated and the performance issues fixed. Unless you want to give it a whirl? I'm a bit busy at the moment on other tasks

**Comment by spyhunter99** [comment]
i think the reason why it wasn't originally merged has the version at the time had a lot of dependencies on google libraries, which i don't like and it sort makes understanding the licensing, complicated.

i also wanted to just included it with the samples osmdroid app, however the minsdk is 8 for osmdroid. the NGA stuff enforces a minsdk of 14. Enforcing that for the sample app would significantly reduce our test coverage unfortunately but it may be worth it. Maybe we can split up the sample app somehow to have a version for travis with a low minsdk but publish to the play store a version with everything in it.

https://github.com/ngageoint/geopackage-android/issues/18

**Comment by legrostdg** [comment]
@spyhunter99 unfortunately I reported this as the user, not as a coder, as I don't speak java... I would be happy to assist if it could be coded in haskell or python!

I think this worth increasing the minsdk but you are the one who decides :-).

Thanks a lot for taking time on this issue!
