### ISSUE TITLE
Get rid of deprecated android.preference.PreferenceManager API

### ISSUE THREAD

**Issue by bubelov** [osmdroid/osmdroid#1803]
```bash
./gradlew clean check
```

```bash
w: ClassName.kt: (8, 27): 'PreferenceManager' is deprecated. Deprecated in Java
w: ClassNamet.kt: (83, 13): 'PreferenceManager' is deprecated. Deprecated in Java
w: ClassName.kt: (83, 31): 'getDefaultSharedPreferences(Context!): SharedPreferences!' is deprecated. Deprecated in Java
```

If no one opposes this fix, I can submit a pull request. Those deprecation warnings are really annoying =)

**Comment by spyhunter99** [comment]
please do so. what is the replacement?

**Comment by bubelov** [comment]
Never mind, I misunderstood the doc. The new preference dependency uses the same `SharedPreferences` class, it just re-implements `PreferenceManager`, so the client apps can just switch to the new `PreferenceManager` without any changes to the library API since it only deals with `SharedPreferences`
