### ISSUE TITLE
mbtiles vs. geopackage EPSG 3857 north must be in [-85.05112877980658,85.05112877980658]

### ISSUE THREAD

**Issue by TFreudi1** [osmdroid/osmdroid#1806]
OsmDroid 6.1.2, Geopackage 6.1.3.
I have a simple mbtiles map which loaded fine in Osmdroid, when I converted it to a geopackage and try to load that , I get an error about the bounding box:
north must be in [-85.05112877980658,85.05112877980658]
which is clear because the max-bounding box in all EPSG 3857 files is  -20037508.3427892,-20037508.3427892,20037508.3427892,
20037508.3427892. I can patch the table gpkg_tile_matrix_set from the correct EPSG 3857 bounding to -180,-85,180,85 than I don't have the error, but I never see a map. Here is a sample file from the geopackage web site:
[river.zip](https://github.com/osmdroid/osmdroid/files/8730526/river.zip)

So the problem is that I can't use any raster map with EPSG 3857 in a geopackage.

**Comment by spyhunter99** [comment]
should be fixed in the next release
