### ISSUE TITLE
How to create a MapSnapshot of a certain size

### ISSUE THREAD

**Issue by MTgdev** [osmdroid/osmdroid#1813]
## Issue Type

[x ] Question
[ ] Bug
[ ] Improvement
[ ] Build system related
[ ] Performance
[ ] Documentation

## Description and/or steps/code to reproduce the problem

I am trying to create a MapSnapshot of a certain size but with no success. The documentation on it has no example for it, and the ones that are there assume that you have some level of knowledge about projections (I think?) but I don't understand much about them.

Currently, the bitmaps look like this (they don't fill the width that I want).
![immagine](https://user-images.githubusercontent.com/76953695/172052293-dc3b3f80-8b7e-4bc5-a630-cad5e91ffdf2.png)

Here's the method I am using to generate the bitmaps:

```java
    public static void takeMapSnapshot(Context context, GeoPoint geoPoint, MapSnapshot.MapSnapshotable callback, int width, int height){

        Marker marker = new Marker(new MapView(context));
        marker.setPosition(geoPoint);
        marker.setAnchor(Marker.ANCHOR_CENTER, Marker.ANCHOR_BOTTOM);

        List<Overlay> mOverlay = new ArrayList<>();
        mOverlay.add(marker);

        MapTileProviderBase mapTileProviderBase = new MapTileProviderBasic(context);
        Projection mProjection = new Projection(9.00, width, height, geoPoint, 0, true, true, 0, 0);

        final MapSnapshot mapSnapshot = new MapSnapshot(callback,
                MapSnapshot.INCLUDE_FLAG_UPTODATE, mapTileProviderBase, mOverlay, mProjection);
        executorService.submit(mapSnapshot);
    }
```

### Version of osmdroid the issue relates to:

6.1.2

**Comment by monsieurtanuki** [comment]
Hi @MTgdev!
Please have a look at [`SampleMapSnapshot.java`](https://github.com/osmdroid/osmdroid/blob/master/OpenStreetMapViewer/src/main/java/org/osmdroid/samplefragments/data/SampleMapSnapshot.java), and possibly use the osmdroid test app to see how it works concretely.
From what I can see, in your code the problem may come from what you do in `callback`; here maybe you should do nothing until `pMapSnapshot.getStatus() != MapSnapshot.Status.CANVAS_OK`.

**Comment by UNILucaM** [comment]
It actually turns out that the code itself was absolutely fine, and how I called the method was the problem. What I was doing wrong was that I would run `takeMapSnapShot` with the cardView's `post()` method and not the progressBar's (because, before the MapSnapshot is taken, a progressbar circles until it is ready). Sorry for the waste of time, and thank you for the steady response!

**Comment by monsieurtanuki** [comment]
@MTgdev @UNILucaM You're welcome!
