### ISSUE TITLE
Wrong version string in BuildInfo

### ISSUE THREAD

**Issue by mikebravoyes** [osmdroid/osmdroid#1815]
## Issue Type

[X] Bug
[X] Improvement

## Description and/or steps/code to reproduce the problem

@spyhunter99 
I just updated the osmdroid version in my build.gradle
```
dependencies {
    implementation group: 'org.osmdroid', name: 'osmdroid-android', version: '6.1.13'
```
After a new build, I was surprised to find `OsmdroidBuildInfo.VERSION = '6.1.12'`.

I thought the version string is generated automatically, but obviously it is not.

### If it's a bug, version(s) of android this affects:

All

### Version of osmdroid the issue relates to:

6.1.13

**Comment by spyhunter99** [comment]
i can explain this. i went through the release process for 6.1.12, then found a snag in the release which only required build script updates only. I think gradle skipped unchanged files during the compile which probably caused this. A clean step would have prevented this.

**Comment by mikebravoyes** [comment]
@spyhunter99 
When I compile with version 6.1.14, I still get this `OsmdroidBuildInfo.java`:

```
package org.osmdroid;

//this file is automatically generated during the build
//when making changes, only edit ./src/main/filtered/...
//https://github.com/osmdroid/osmdroid/issues/1500
public class OsmdroidBuildInfo {

    private OsmdroidBuildInfo() {
    }

    public static final String VERSION = "6.1.12";
    public static final String BUILD_DATE = "Sat May 14 10:16:32 EDT 2022";
}
```

**Comment by mikebravoyes** [comment]
@spyhunter99 
And the releases in [https://github.com/osmdroid/osmdroid/releases](https://github.com/osmdroid/osmdroid/releases) still show version **6.1.13**
