### ISSUE TITLE
ItemizedIconOverlay removed markers that has almost same location

### ISSUE THREAD

**Issue by mojtabashirkhani** [osmdroid/osmdroid#1816]
## Issue Type

[ ] Question
[ ] Bug
[ ] Improvement

## Description and/or steps/code to reproduce the problem
here is my code

ItemizedIconOverlay<OverlayItem> defaultItemizedIconOverlay = new ItemizedIconOverlay<>(defaultItems, getResources().getDrawable(R.drawable.ic_default_star), new ItemizedIconOverlay.OnItemGestureListener<OverlayItem>() {
                @Override
                public boolean onItemSingleTapUp(int index, OverlayItem item) {
                  
                    return false;
                }

                @Override
                public boolean onItemLongPress(int index, OverlayItem item) {
                    return false;
                }
            }, TreasuryListMapActivity.this);
            map.getOverlays().add(defaultItemizedIconOverlay);

35.73967-51.375336   35.739754-51.37562
and when i have this locations, just show one of them and i want to show both of them (that's 1 unit location actually)

## Environment
android studio
### If it's a bug, version(s) of android this affects:
Latest version
All

### Version of osmdroid the issue relates to:
i used 6.1.10 i had same issue, also i update it to latest version but nothing has change
6.1.2

**Comment by mojtabashirkhani** [comment]
Thank you bro, I solve this problem with another way, I passed that list to recyclerview and show to user if that was duplicate or more

**Comment by monsieurtanuki** [comment]
@mojtabashirkhani Perfect!
