### ISSUE TITLE
Performance Issue with a lot of Overlays

### ISSUE THREAD

**Issue by Maradox** [osmdroid/osmdroid#182]
When using ItemizedIconOverlays with a lot of points (altogether ~1500) the performance decreases significantly (below 60fps on a Nexus 5). Via the profiler I can see that most of the time is required for drawing onto the canvas.

Is that behavior to be expected with that amount of points? Is there something that could be done to increase performance (beside using an extra TileOverlay instead where the points are drawn on)? Skipping items which are currently not visible is not a real solution in my case, since sometimes all Points are visible.

**Comment by spyhunter99** [comment]
have you tried the clustering mechanism osmbonus pack has?

**Comment by Maradox** [comment]
I wanted to avoid clustering. My plan is to rescale the drawables of the OverlayItems according to the zoom-Level where a higher zoom-level increases the size of the OverlayItems. This approach already looks and works very well and has no performance penalty during scrolling on its own.

If there is no solution for the performance problem I may implement a custom TilesOverlay which draws the items on tiles which can be cached (in this case creating the Tiles may be a performance-problem, but I will have to check). Or would something speak against this approach?

Otherwise I may reconsider clustering.

**Comment by spyhunter99** [comment]
I just added an example that lets you add points 500 at a time. on my s5, it runs pretty good up until 3k icons. at 6k icons it's noticeably slow. what kind of device are you running on?

**Comment by Maradox** [comment]
I'm using a Nexus 5. 
I tried your example. With 500 icons it 's still smooth. 1500 is already a bit laggy. 3000 is very laggy.

**Comment by spyhunter99** [comment]
Sounds like your use case uses data that doesn't change very frequently or not at all. In this case, painting the icons right on to the tiles overlay could be a feasible solution. You may also want to look at MapForge, which renders tiles on the fly using OSM vector data. There's a plugin in OSMBonus pack for it.

do you by chance have hardware acceleration turned off?

**Comment by spyhunter99** [comment]
Also, are your icon all the same or are they unique? you can probably save memory usage by using a single icon and reusing it. Using a smaller icon should help reduce the lag too. Another strategy is to remove icons from the overlay when they are off screen and re-add when they become on screen. One can accomplish this by attaching a map listener for zoom and movement events and then handle accordingly. Reducing the amount of stuff in the osmdroid overlays will reduce draw times, even if the item is currently off screen

**Comment by Maradox** [comment]
The overlays don't change frequently but can be changed in the settings. I use about 35 different icons.

I created a custom TileProvider for drawing the icons onto tiles and the performance is amazing, until you scroll far enough so that new tiles need to be created - then it will stutter a bit. Also the memory usage is higher.

**Comment by k3b** [comment]
I have 15 000 items in a database and read only those items that are currenly visible into a folderOverlay in a background task (AsyncTask) . When background loading is finished the folderOverlay is added to the map (and the previous-folder-overlay is removed)

This works until osmdroid-5.1; does not work with osmdroid-5.2; and will work again on osmdroid-5.3

**Comment by spyhunter99** [comment]
You could just use a thread and pass in context. AsyncTask not a mandatory
thing

**Comment by ultimate-tester** [comment]
Could @k3b  or anyone else show an example of how this is achieved? I am loading roughly 3500 overlays onto the map and even with clustering I get ANR messages all the time. It takes about 30 seconds before it's finished redrawing the map and moving the map induces the lag again.

**Comment by spyhunter99** [comment]
I've answered a similar question before.  If the data is static, you can
paint right on to the tiles and cache them.  You ll have to handle click
events differently.

Another option is to only add the layers of its in view.

You can also increase the clustering threshold or simply limit the on
screen icon count until you zoom in more

**Comment by k3b** [comment]
you get ANR because you are doing to much in the main thread.

you can view the sources of my current background-cluster load at 

* https://github.com/k3b/APhotoManager/

**Comment by k3b** [comment]
@ultimate-tester i will create a demo. See #394

**Comment by spyhunter99** [comment]
now that we have a function example for on device tile rendering, perhaps the ultimate solution for many overlays that do not update frequently would be to render tiles on device for those overlays

**Comment by spyhunter99** [comment]
relooking at this... mapview.getBoundingBox() has a contains method. If we stick this check in the on draw method of itemized icon overlay, it should significantly improve things when the view bounds does not include all icons

**Comment by spyhunter99** [comment]
#890 related issue

**Comment by monsieurtanuki** [comment]
Reopened as the correction of this issue has side effects - including #954.

The focus is on `ItemizedOverlay.onDrawItem`.
My assumption is that all the `canvas.save` / `canvas.restore` steps are costly.
First good news: we can skip the `canvas.scale` step, as we don't use matrix scales anymore - we handle the double zoom level instead and use `Drawable.setBounds` in order to stretch the tile bitmap.

**Comment by monsieurtanuki** [comment]
I think I found an elegant (and fast) solution.
I should be able to PR tomorrow.

**Comment by monsieurtanuki** [comment]
Fixed by #984.
