### ISSUE TITLE
With 6.1.12 pressing on MapView Zoom controller +/- buttons generates LongPress events

### ISSUE THREAD

**Issue by wuan** [osmdroid/osmdroid#1822]
Please note: issues related to or caused by osmbonuspack will be closed with a
suggestion to open an issue at https://github.com/MKergall/osmbonuspack

(feel free to delete whatever doesn't apply)

## Issue Type

[ ] Question
[x] Bug
[ ] Improvement
[ ] Build system related
[ ] Performance
[ ] Documentation

## Description and/or steps/code to reproduce the problem

After upgrading to 6.1.12 using the Zoom controller buttons creates LongPress events after a zoom action is triggered, even when only clicking the zoom buttons.

Before 6.1.12 the Map view works as expected.

### If it's a bug, version(s) of android this affects:

Currently tested on API 30 only

### Version of osmdroid the issue relates to:

6.1.12

**Comment by nienienienie** [comment]
isn't it related to https://github.com/osmdroid/osmdroid/issues/1572?

**Comment by InI4** [comment]
I'd like to confirm, that this issue persists with 6.1.13. Very annoying, when your application uses LongPress events.

**Comment by wuan** [comment]
The issue is also there when using 6.1.13.

**Comment by monsieurtanuki** [comment]
I've lost the track of what was in 6.1.12 and 6.1.13.
The good news is that you can copy and override custom zoom classes (and other classes too) to find the bug and fix it.
Feel free to send a PR then :)

**Comment by InI4** [comment]
I can help with that, I still see that behaviour in 6.1.14. Nastym being totally out of time. From the timeline and some superficial tests I'd say, it is the commit #1733. Can't you revert it?

**Comment by tvaknin** [comment]
I found a workaround for now... 
1. Take time onZoom event 
2. on longPressHelper check if timediff>400ms -> do stuff

**Comment by gokar96** [comment]
Any news here, issue is still in 6.1.18 and it is annoying because the workaround by tvaknin does not work when your are on the max or min zoomlevel (You get no OnZoom event in that case)

**Comment by gokar96** [comment]
The best workaround for this problem is to create your own zoom buttons on the map :)
