### ISSUE TITLE
Prevent scroll wrapping

### ISSUE THREAD

**Issue by Maradox** [osmdroid/osmdroid#183]
When using a custom tile-source (which may not be the complete world), it would be nice to be able to scroll e.g.: half-screen beyond the map-bounds. Unfortunately currently due to the scroll-wrapping the map will re-appear in every direction.

One possible solution may be to change the TilesLooper and make it optional to only draw Tiles inside the bounds. But I guess that would only work for the TilesOverlay and not for other Overlays? Also it may not be sufficient if someone wishes to scroll even further away from the map than half-screen, since the ViewPort in the TilesLooper seems to reset when scrolling far enough.

**Comment by spyhunter99** [comment]
you can set the scrollable bounds and min zoom levels with mapview

**Comment by Maradox** [comment]
This is what I'm currently doing (bounds and min-zoom), but I'm looking for a solution where it is possible to see the whole map (only once) and to scroll a bit beyond the map.

If someone could hint me in the direction on how to implement that in the correct way I may create a PR for it.

**Comment by spyhunter99** [comment]
go head and open a PR. i have no idea where to start. It would probably be in the following class
org.osmdroid.views.overlay.TilesOverlay

If do you resolve this, please make it an optional setting where the default setting is for the current behavior. Personally, I'd like to see this happen too

**Comment by spyhunter99** [comment]
@MKergall can you test this out on your device? It only works in one direction on my device but i think it's from the infamous samsung issue whereby screen height is incorrectly reported by the os.
