### ISSUE TITLE
Osmdroid for Android Automotive OS?

### ISSUE THREAD

**Issue by gogamid** [osmdroid/osmdroid#1836]
## Issue Type

[ x] Question
[ ] Bug
[ x] Improvement
[ ] Build system related
[ ] Performance
[ ] Documentation

## Question

I have been developing an app for AOSP Automotive OS, where Google Maps is not available. Has anyone could integrate osmdroid into Templated Apps, specifically PlaceListMapTemplate? I want to display osmdroid map instead of Google Maps.

**Comment by eclectice** [comment]
#1670

**Comment by gogamid** [comment]
I have integrated Mapbox to Automotive or Android Auto application minimalistically, you can check it out:
https://github.com/gogamid/mapbox-automotive-integration/tree/main
![Screenshot_1667862474](https://user-images.githubusercontent.com/36050790/200436137-d727ceae-70b3-4dc3-a571-0de60aa543c3.png)
