### ISSUE TITLE
Border around tiles

### ISSUE THREAD

**Issue by MichHighlander** [osmdroid/osmdroid#1841]
Please note: issues related to or caused by osmbonuspack will be closed with a
suggestion to open an issue at https://github.com/MKergall/osmbonuspack

(feel free to delete whatever doesn't apply)

## Issue Type

[ X] Question
[ ] Bug
[ ] Improvement
[ ] Build system related
[ ] Performance
[ ] Documentation

## Description and/or steps/code to reproduce the problem

Hello,
When i load a custom tile to my MapView i get a black border around the tile with the word scaled and the ZXY of the tile.
How do i remove that?

## Environment
Android
### If it's a bug, version(s) of android this affects:

All

### Version of osmdroid the issue relates to:

6.1.2

**Comment by spyhunter99** [comment]
turn off the tile debugging.

**Comment by MichHighlander** [comment]
@spyhunter99 
Thanks!
