### ISSUE TITLE
Marker z-index

### ISSUE THREAD

**Issue by MichHighlander** [osmdroid/osmdroid#1842]
Please note: issues related to or caused by osmbonuspack will be closed with a
suggestion to open an issue at https://github.com/MKergall/osmbonuspack

(feel free to delete whatever doesn't apply)

## Issue Type

[ X] Question
[ ] Bug
[ ] Improvement
[ ] Build system related
[ ] Performance
[ ] Documentation

## Description and/or steps/code to reproduce the problem
I want to alter my Markers Z-Index, i don't see a function on how to do that.
Is that possible?

### If it's a bug, version(s) of android this affects:

All

### Version of osmdroid the issue relates to:

6.1.2

**Comment by monsieurtanuki** [comment]
Hi @MichHighlander!
No we don't support z-index.
But if you order correctly your markers, you can emulate z-index effect.

**Comment by MichHighlander** [comment]
@monsieurtanuki i see, thank you.
So if i have a marker already present and i want it to be on top i need to remove it, add the marker i want to be under and then add the removed marker again?

**Comment by monsieurtanuki** [comment]
If you want marker A to be on top, you have to remove marker A from wherever it was, and to put marker A at the end of the list. All the other markers will be below marker A.

**Comment by MichHighlander** [comment]
@monsieurtanuki Thanks it worked.
Another question because i don't want to open another ticket.
How can i set a callback that when i touch the map i will get to coordinates of where i touched?

**Comment by spyhunter99** [comment]
One technique is to add a transparent view on top of the map, get the touch
coordinates then there's a osmroid rop api for pixels to lat lon. I think
it's in tilesystem

**Comment by MichHighlander** [comment]
@spyhunter99 Thanks, you got a great library!

**Comment by monsieurtanuki** [comment]
Can't remember precisely but there must be an `onTouched` event for the map that returns the pixel coordinates, that you have to change into geo coordinates with the `MapView`'s `Projection`.
I suggest that you download the sample app of Osmdroid, or that you have a look at the samples directly in the code.
You'll find answers and inspiration there.

PS: don't be shy with opening new issues, that helps other developers when they see relevant titles.

**Comment by MKergall** [comment]
Have a look here: https://github.com/MKergall/osmbonuspack/wiki/Tutorial_5
