### ISSUE TITLE
osmdroid osm looks more "zoom out" than Google Maps v2 with the same zoom level

### ISSUE THREAD

**Issue by meor9zcu12** [osmdroid/osmdroid#1844]
## Issue Type
[X] Question

## Description and/or steps/code to reproduce the problem

I am trying migrate my project from Google Maps v2 to osmdroid, I knew osmdroid is a replacement of v1.
And my goal is to reuse the same map config, e.g. zoom level, when replacing Google Maps v2 by osmdroid.

My question is that, in my testing, the zoom level of Google Maps v2 and osmdroid is the same, let's say zoom level = 13, the Google Maps always look like more "zoom in" than osm in osmdroid, and I don't know why.

I don't know too much about coordinate system, I thought both OSM and Google Maps use WGS84, then the zoom level config should be the same or very similar. 
Is it intended or something I missed? What should I do to reuse the same zoom level from Google Maps v2 to osmdroid?

<img src="https://user-images.githubusercontent.com/82598626/188782066-98372576-0490-4014-b41a-5a3fb895fad9.png" width="500">
The maps, both are in zoom level 13.
  
MapTestActivity.java
```
public class MapTestActivity extends AppCompatActivity {
    @Override
    protected void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setTitle("Map Test");
        setContentView(R.layout.map_layout);

        // Google Maps v2
        SupportMapFragment supportMapFragment = SupportMapFragment.newInstance();
        getSupportFragmentManager().beginTransaction().add(R.id.container, supportMapFragment).commit();

        supportMapFragment.getMapAsync(googleMap -> {
            googleMap.setMaxZoomPreference(13f);
            googleMap.setMinZoomPreference(9f);
            googleMap.moveCamera(CameraUpdateFactory.newLatLngZoom(new LatLng(40.730610, -73.935242), 10f));
            googleMap.addMarker(new MarkerOptions()
                    .position(new LatLng(40.730610, -73.935242)));
        });

        // osmdroid
        MapView mapView = findViewById(R.id.map_view);

        Context ctx = getApplicationContext();
        Configuration.getInstance().load(ctx, PreferenceManager.getDefaultSharedPreferences(ctx));

        mapView.setTileSource(TileSourceFactory.MAPNIK);
        mapView.setMultiTouchControls(true);

        mapView.getController().setZoom(10d);
        mapView.setMaxZoomLevel(13d);
        mapView.setMinZoomLevel(9d);
        mapView.setExpectedCenter(new GeoPoint(40.730610, -73.935242));

        Marker marker = new Marker(mapView);
        marker.setPosition(new GeoPoint(40.730610, -73.935242));
        mapView.getOverlays().add(marker);

        CopyrightOverlay copyrightOverlay = new CopyrightOverlay(ctx);
        mapView.getOverlays().add(copyrightOverlay);
    }
}
```

map_layout.xml
```
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical">

    <androidx.fragment.app.FragmentContainerView
        android:id="@+id/container"
        android:layout_width="match_parent"
        android:layout_height="0dp"
        android:layout_weight="1" />

    <org.osmdroid.views.MapView
        android:id="@+id/map_view"
        android:layout_width="match_parent"
        android:layout_height="0dp"
        android:layout_weight="1" />
</LinearLayout>
```

## Environment
All

### Version of osmdroid the issue relates to:
6.1.14

**Comment by monsieurtanuki** [comment]
Beyond the fact that the zoom level looks different, the display is harder to read with osmdroid.
I think there's a method like `setTileDpi` in `MapView` to correct the display of tiles according to the device dpi settings: bigger tiles, which look like a more relevant zoom.
________________________________
De : meor9zcu12 ***@***.***>
Envoyé : mercredi 7 septembre 2022 05:52
À : osmdroid/osmdroid ***@***.***>
Cc : Subscribed ***@***.***>
Objet : [osmdroid/osmdroid] osmdroid osm looks more "zoom out" than Google Maps v2 with the same zoom level (Issue #1844)


Issue Type

[X] Question

Description and/or steps/code to reproduce the problem

I am trying migrate my project from Google Maps v2 to osmdroid, I knew osmdroid is a replacement of v1.
And my goal is to reuse the same map config, e.g. zoom level, when replacing Google Maps v2 by osmdroid.

My question is that, in my testing, the zoom level of Google Maps v2 and osmdroid is the same, let's say zoom level = 13, the Google Maps always look like more "zoom in" than osm in osmdroid, and I don't know why.

I don't know too much about coordinate system, I thought both OSM and Google Maps use WGS84, then the zoom level config should be the same or very similar.
Is it intended or something I missed? What should I do to reuse the same zoom level from Google Maps v2 to osmdroid?

[https://user-images.githubusercontent.com/82598626/188782066-98372576-0490-4014-b41a-5a3fb895fad9.png]<https://user-images.githubusercontent.com/82598626/188782066-98372576-0490-4014-b41a-5a3fb895fad9.png>

The maps, both are in zoom level 13.

MapTestActivity.java

public class MapTestActivity extends AppCompatActivity {
    @Override
    protected void ***@***.*** Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setTitle("Map Test");
        setContentView(R.layout.map_layout);

        // Google Maps v2
        SupportMapFragment supportMapFragment = SupportMapFragment.newInstance();
        getSupportFragmentManager().beginTransaction().add(R.id.container, supportMapFragment).commit();

        supportMapFragment.getMapAsync(googleMap -> {
            googleMap.setMaxZoomPreference(13f);
            googleMap.setMinZoomPreference(9f);
            googleMap.moveCamera(CameraUpdateFactory.newLatLngZoom(new LatLng(40.730610, -73.935242), 10f));
            googleMap.addMarker(new MarkerOptions()
                    .position(new LatLng(40.730610, -73.935242)));
        });

        // osmdroid
        MapView mapView = findViewById(R.id.map_view);

        Context ctx = getApplicationContext();
        Configuration.getInstance().load(ctx, PreferenceManager.getDefaultSharedPreferences(ctx));

        mapView.setTileSource(TileSourceFactory.MAPNIK);
        mapView.setMultiTouchControls(true);

        mapView.getController().setZoom(10d);
        mapView.setMaxZoomLevel(13d);
        mapView.setMinZoomLevel(9d);
        mapView.setExpectedCenter(new GeoPoint(40.730610, -73.935242));

        Marker marker = new Marker(mapView);
        marker.setPosition(new GeoPoint(40.730610, -73.935242));
        mapView.getOverlays().add(marker);

        CopyrightOverlay copyrightOverlay = new CopyrightOverlay(ctx);
        mapView.getOverlays().add(copyrightOverlay);
    }
}


map_layout.xml

<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical">

    <androidx.fragment.app.FragmentContainerView
        android:id="@+id/container"
        android:layout_width="match_parent"
        android:layout_height="0dp"
        android:layout_weight="1" />

    <org.osmdroid.views.MapView
        android:id="@+id/map_view"
        android:layout_width="match_parent"
        android:layout_height="0dp"
        android:layout_weight="1" />
</LinearLayout>


Environment

All

Version of osmdroid the issue relates to:

6.1.14

**Comment by MKergall** [comment]
probably this one: MapView.setTilesScaledToDpi(boolean tilesScaledToDpi)

**Comment by meor9zcu12** [comment]
Thanks a lot!
I used `MapView.setTilesScaledToDpi` and now works as expected.

**Comment by MKergall** [comment]
BTW, most devices now have high density, requiring this setting => I think we should set this tilesScaledToDpi setting to true by default. 

@monsieurtanuki @spyhunter99 your view?

**Comment by monsieurtanuki** [comment]
Indeed `true` should be the default.
Is that a breaking change? How smoothly can we do that?
Well, just editing `private boolean mTilesScaledToDpi = false;` and adding an explicit release note would do the trick I guess.
