### ISSUE TITLE
tileWriter null when map used in viewPager2

### ISSUE THREAD

**Issue by CW12** [osmdroid/osmdroid#1848]
## Issue Type

[ ] Question
[x ] Bug
[ ] Improvement
[ ] Build system related
[ ] Performance
[ ] Documentation

## Description and/or steps/code to reproduce the problem
When used in a viewPager2, the map loads correctly initially, but after navigating to a new view and back to the view holding the map, the map doesn't work correctly (tiles won't load, markers are gone)

The following line gets printed to the console repeatedly if I try to move the map:
D/OsmDroid: TileLoader failed to load tile due to mWriter being null (map shutdown?)

Setting a breakpoint in the onResume() method for the child fragment holding the map, the tileWriter on the map's tileProvider is null when I navigate back to that fragment - it is non null the first time that fragment is shown.

### If it's a bug, version(s) of android this affects:

All

### Version of osmdroid the issue relates to:

6.1.14

**Comment by eclectice** [comment]
I use **ViewPager2** and **FragmentStateAdapter** to manage tabs in a tab layout. However, I've had no issues running OsmDroid **MapView** inside an OsmMapFragment in one of the tabs. The **MapView** rendering update is unaffected by switching between tabs. The marker I set by default to mark the current position is always updated by the Location service.

It works well on Android 7.0, Android 11.0, and Android 12.0. It works with Android SDK API 33.

<details><summary>A class that extends FragmentStateAdapter</summary>
<p>

```java

    private androidx.viewpager2.widget.ViewPager2 mViewPager2;

    private SectionsPagerAdapter2 mSectionsPagerAdapter2;

    /**
     * A {@link FragmentStateAdapter} that returns a fragment corresponding to
     * one of the sections/tabs/pages.
     */
    public class SectionsPagerAdapter2 extends FragmentStateAdapter {
        RemoteControlFragment radio;
        OsmMapFragment osmMap;
        MainChatFragment chat;

        public SectionsPagerAdapter2(@NonNull Fragment fragment) {
            super(fragment);
            radio = AltRadioRemoteControlFragment.newInstance();
            osmMap = OsmMapFragment.newInstance();
            chat = MainChatFragment.newInstance();
        }

        public SectionsPagerAdapter2(@NonNull FragmentActivity fragmentActivity) {
            super(fragmentActivity);
            radio = AltRadioRemoteControlFragment.newInstance();
            osmMap = OsmMapFragment.newInstance();
            chat = MainChatFragment.newInstance();
        }

        public SectionsPagerAdapter2(@NonNull FragmentManager fragmentManager, @NonNull Lifecycle lifecycle) {
            super(fragmentManager, lifecycle);
            radio = AltRadioRemoteControlFragment.newInstance();
            osmMap = OsmMapFragment.newInstance();
            chat = MainChatFragment.newInstance();
        }

        @NonNull
        public Fragment getItem(int position) {
            switch (position)
            {
                case MAP_PAGE:
                    return osmMap;
                case CHAT_PAGE:
                    return chat;
                default:
                    return radio;
            }
        }

        private int getCount() {
            return 3;
        }

        @Override
        public int getItemCount() {
            return getCount();
        }

        @NonNull
        @Override
        public Fragment createFragment(int position) { return getItem(position); }
    }
```

</p>
</details>

<details><summary>the codes that links FragmentStateAdapter to ViewPager2 via a mediator</summary>
<p>

```java
protected void registerTabsListener2(Bundle savedInstanceState) {
	Resources res = getResources();
	// Create the adapter that will return a fragment for each of the three
	// primary sections of the activity.
	mSectionsPagerAdapter2 = new SectionsPagerAdapter2(getSupportFragmentManager(), getActivity().getLifecycle());

	// Set up the ViewPager with the sections adapter.
	mViewPager2 = findViewById(R.id.container2);
	mViewPager2.setAdapter(mSectionsPagerAdapter2);
	mViewPager2.setOffscreenPageLimit(2);
	mViewPager2.setUserInputEnabled(false);

	tabLayout = findViewById(R.id.tabanim_tabs);
	tabLayout.addTab(tabLayout.newTab().setText(R.string.remote));
	tabLayout.addTab(tabLayout.newTab().setText(R.string.map));
	tabLayout.addTab(tabLayout.newTab().setText(R.string.chat));
	new TabLayoutMediator(tabLayout, mViewPager2,
			(tab, position) -> {
				switch (position) {
					case REMOTE_PAGE: tab.setText(R.string.remote); break;
					case MAP_PAGE: tab.setText(R.string.map); break;
					case CHAT_PAGE: tab.setText(R.string.chat); break;
				}
			}
	).attach();
	tabLayout.addOnTabSelectedListener(new TabLayout.OnTabSelectedListener() {
		@Override
		public void onTabSelected(TabLayout.Tab tab) {
			mViewPager2.setCurrentItem(tab.getPosition());
		}

		@Override
		public void onTabUnselected(TabLayout.Tab tab) {

		}

		@Override
		public void onTabReselected(TabLayout.Tab tab) {

		}
	});
}
```

</p>
</details>

Could you show your code for configuring the MapView?

**Comment by eclectice** [comment]
When ***mWriter*** is null, the error occurs. It appears that it fails during initialization in the first code, generating a problem in the second code.

https://github.com/osmdroid/osmdroid/blob/dbb20901cac30b28a6a9349da097c22d9a962311/osmdroid-android/src/main/java/org/osmdroid/tileprovider/modules/MapTileSqlCacheProvider.java#L60

https://github.com/osmdroid/osmdroid/blob/dbb20901cac30b28a6a9349da097c22d9a962311/osmdroid-android/src/main/java/org/osmdroid/tileprovider/modules/MapTileSqlCacheProvider.java#L180

The ***getDB()*** call is failing

https://github.com/osmdroid/osmdroid/blob/dbb20901cac30b28a6a9349da097c22d9a962311/osmdroid-android/src/main/java/org/osmdroid/tileprovider/modules/SqlTileWriter.java#L736

It is called from this code:

https://github.com/osmdroid/osmdroid/blob/dbb20901cac30b28a6a9349da097c22d9a962311/osmdroid-android/src/main/java/org/osmdroid/tileprovider/modules/SqlTileWriter.java#L83

How did you store your OsmDroid cache database: inside (app's private folder) or externally (outside of app's private folder)? Indicate which Android versions you've tested.  Can you look for **SQLiteLog** and **SQLiteQuery** tags in your logcat?

**Comment by eclectice** [comment]
@CW12 Should this be deemed closed based on your most recent post?

**Comment by CW12** [comment]
Sorry for the delay, I've been out of the office.

I'm not getting any SQlite entries in the logcat.

This is how the tilecache is being set:
`       
        IConfigurationProvider osmConfig = Configuration.getInstance();
        File basePath = new File(this.getCacheDir().getAbsolutePath(), "osmdroid");
        osmConfig.setOsmdroidBasePath(basePath);
        File titleCache = new File(osmConfig.getOsmdroidBasePath().getAbsolutePath(), "title");
        osmConfig.setOsmdroidTileCache(titleCache);
`

I have inherited this project and am not very familiar with OSMDroid, so there is every chance that something isn't configured correctly, and has only come to light now that I'm trying to use maps inside a viewpager (there are maps used in many other places that all work fine)

**Comment by eclectice** [comment]
If I'm not mistaken, the default ***getOsmdroidBasePath()*** utilizes ***Environment. getExternalStorageDirectory()***, which is in the shared storage. It no longer works with a ***File*** object since Android 10+. You must utilize an app-specific directory to access files with a ***File*** object. But, since you have changed it to ***Context.getCacheDir()*** which resides in the internal storage, you need to check for the existence of the files in that directory. If the internal storage is low, Android gives a significant likelihood of deletion.

**Comment by eclectice** [comment]
#1743

**Comment by CW12** [comment]
I don't believe this is an issue related to storage - the maps work exactly as expected the first time a fragment in the viewpager is loaded, but it's only when I then go to a different fragment in the viewpager and back to the fragment containing the map that it's an issue.

Storage space definitely isn't the issue.

The cache appears to be working correctly - places that I've recently viewed in a map load instantly without network calls when I reload a map.

The app uses OSMDroid maps in about a dozen places, and every single one works fine, except those placed inside a viewpager. 

At the moment, I have it working, but am having to hack around it and remove and readd the map in the viewpager child fragment's onResume:

```
 @Override
    public void onResume() {
        super.onResume();
        binding.map.onResume();
        //This is a hack! The mapview looses it's reference to the tile writer when changing tabs
        //The only way I could find to work around this was to completely remove the view and
        //programtically re add it.
        ConstraintLayout layout = (ConstraintLayout) binding.getRoot();
        ConstraintSet set = new ConstraintSet();
        CustomOSM temp = binding.getRoot().findViewById(R.id.map);
        binding.getRoot().removeView(temp);
        CustomOSM map = new CustomOSM(mContext, (AttributeSet) null);
        map.setId(R.id.map);
        layout.addView(map, 0);
        set.clone(layout);

        set.connect(R.id.map, ConstraintSet.START, ConstraintSet.PARENT_ID, ConstraintSet.START, 0);
        set.connect(R.id.map, ConstraintSet.END, ConstraintSet.PARENT_ID, ConstraintSet.END, 0);
        set.connect(R.id.map, ConstraintSet.BOTTOM, ConstraintSet.PARENT_ID, ConstraintSet.BOTTOM, 0);
        set.connect(R.id.map, ConstraintSet.TOP, binding.tvAddress.getId(), ConstraintSet.BOTTOM, Global.dpToPx(16, mContext));
        set.constrainHeight(R.id.map, 0);
        set.applyTo(layout);
        binding.getRoot().requestLayout();

        setUpMap(map);

    }
```

Yes, CustomOSM extends MapView and only overrides dispatchTouchEvent (I believe because there were issues using the maps inside a scrollview, but this was before I took over the project).

```
public class CustomOSM extends MapView {

    public CustomOSM(Context context, AttributeSet attrs) {
        super(context, attrs);
    }


    @Override
    public boolean dispatchTouchEvent(MotionEvent event) {
        switch (event.getAction()) {
            case MotionEvent.ACTION_UP:
                this.getParent().requestDisallowInterceptTouchEvent(false);
                break;
            case MotionEvent.ACTION_DOWN:
                this.getParent().requestDisallowInterceptTouchEvent(true);
                break;
        }
        return super.dispatchTouchEvent(event);
    }


}
```

**Comment by eclectice** [comment]
I'm still writing Android code in Java.

Perhaps something is necessary for Kotlin code to work properly with ViewPager2 because you stated fragments losing references due to Android lifecycle events?

You might want to look at this Google guide on ViewPager2 (codes in Kotlin) https://github.com/android/views-widgets-samples/tree/master/ViewPager2

**Comment by CW12** [comment]
I too am writing in Java

I tried calling map.onResume() and map.onPause() in the respective lifecycle calls, but that didn't help.

I have followed the google docs on setting up my viewPager, and am reasonably confident that's all set up correctly - it's working correctly in every respect except with the OSMDroid map views.

I tried upping the setOffscreePageLimit but that didn't help - I'm having this problem with only 2 tabs, and I don't believe this can be set to less than 1, so the tab containing the map is always maintained in this scenario.

Having done a bit more investigating, I believe this is because MapView.onDetach() is being called as soon as I navigate away from the tab containing the map. This destroys a whole bunch of references, that cannot be recreated - the only option is to fully recreate the whole map.

If I override onDetach() in my customOSM to do nothing (i.e. not call it's super) then the navigating between tabs works as expected, but that's probably not the route I want to go down!

The fragment's (containing the mapView) onDestroy() and onDetach() methods aren't being called when navigating between tabs, so the fragment is retained and not recreated, but the mapView.onDetach() is called, destroying the mapview, which isn't being automatically recreated because the fragment doesn't get recreated.

I think this is related to https://github.com/osmdroid/osmdroid/issues/1077

**Comment by CW12** [comment]
You mentioned previously that you have maps working inside a viewPager2 - is your mapView.onDetach() not being called when you navigate between tabs, or are you doing something to handle this?

**Comment by eclectice** [comment]
Here is my logcat for Android lifecycle events for the main app (**MainController**). 

Note that I have ***ViewPager2*** (**SectionsPagerAdapter2**) managing three tab fragments (**AltRadioRemoteControlFragment**, **OsmMapFragment**, **MainChatFragment**). **OsmMapFragment** contains OsmDroid ***MapView***.

For **MainChatFragment**, it has a ***ViewPager2*** managing three child fragments (**UserListSlideFragment**, **ChatSlideFragment**, **SmsListSlideFragment**).

I could not find a way to put a log for ***MapView.onDetach()*** since I didn't extend it. Hence, I am just using the standard OsmDroid ***MapView*** where ***MapView.onDetach()*** is called inside ***MapView.onDetachedFromWindow()***. I assume it should be called when detaching **OsmMapFragment** from a window. It is tied to the main app's ***onDestroy()*** lifecycle event.

https://github.com/osmdroid/osmdroid/blob/dbb20901cac30b28a6a9349da097c22d9a962311/osmdroid-android/src/main/java/org/osmdroid/views/MapView.java#L1271

I put some comments in the logcat for you to understand the events and actions performed.

<details><summary>logcat</summary>
<p>

```log
//starting main app
MAIN_LIFECYCLE           E  MainController.onCreate()
MAIN_LIFECYCLE           E  MainController.onResume()

//starting main app - viewpager2 prepares three tab fragments
//preparing fragment f1
MAIN_VIEWPAGER2          E  SectionsPagerAdapter2.createFragment()
MAIN_FRAGMENT            E  AltRadioRemoteControlFragment.onAttach() isAdded() = true
MAIN_FRAGMENT            E  AltRadioRemoteControlFragment.onCreate() isAdded() = true
MAIN_FRAGMENT            E  AltRadioRemoteControlFragment.onCreateView() isAdded() = true
MAIN_FRAGMENT            E  AltRadioRemoteControlFragment.onViewCreated() isAdded() = true
MAIN_FRAGMENT            E  AltRadioRemoteControlFragment.onViewStateRestored() isAdded() = true
MAIN_FRAGMENT            E  AltRadioRemoteControlFragment.onStart() isAdded() = true
MAIN_FRAGMENT            E  AltRadioRemoteControlFragment.onResume() isAdded() = true

//preparing fragment f2
MAIN_VIEWPAGER2          E  SectionsPagerAdapter2.createFragment()
MAIN_FRAGMENT            E  OsmMapFragment.onAttach() isAdded() = true
MAIN_FRAGMENT            E  OsmMapFragment.onCreate() isAdded() = true
MAIN_FRAGMENT            E  OsmMapFragment.onCreateView() isAdded() = true
MAIN_FRAGMENT            E  OsmMapFragment.onViewCreated() isAdded() = true
MAIN_FRAGMENT            E  OsmMapFragment.onViewStateRestored() isAdded() = true
MAIN_FRAGMENT            E  OsmMapFragment.onStart() isAdded() = true

//preparing fragment f3
MAIN_VIEWPAGER2          E  SectionsPagerAdapter2.createFragment()
MAIN_FRAGMENT            E  MainChatFragment.onAttach() isAdded() = true
MAIN_FRAGMENT            E  MainChatFragment.onCreate() isAdded() = true
MAIN_FRAGMENT            E  MainChatFragment.onCreateView() isAdded() = true
MAIN_FRAGMENT            E  MainChatFragment.onViewCreated() isAdded() = true
MAIN_FRAGMENT            E  MainChatFragment.onViewStateRestored() isAdded() = true
MAIN_FRAGMENT            E  MainChatFragment.onStart() isAdded() = true

//preparing fragment f3's child f1
MAIN_FRAGM...VIEWPAGER2  E  ScreenSlidePagerAdapter2.createFragment()
MAIN_CHILD_FRAGMENT      E  UserListSlideFragment.onAttach() isAdded() = true
MAIN_CHILD_FRAGMENT      E  UserListSlideFragment.onCreateView() isAdded() = true
MAIN_CHILD_FRAGMENT      E  UserListSlideFragment.onViewCreated() isAdded() = true

//preparing fragment f3's child f2
MAIN_FRAGM...VIEWPAGER2  E  ScreenSlidePagerAdapter2.createFragment()
MAIN_CHILD_FRAGMENT      E  ChatSlideFragment.onAttach() isAdded() = true
MAIN_CHILD_FRAGMENT      E  ChatSlideFragment.onCreateView() isAdded() = true
MAIN_CHILD_FRAGMENT      E  ChatSlideFragment.onViewCreated() isAdded() = true

//preparing fragment f3's child f3
MAIN_FRAGM...VIEWPAGER2  E  ScreenSlidePagerAdapter2.createFragment()
MAIN_CHILD_FRAGMENT      E  SmsListSlideFragment.onAttach() isAdded() = true
MAIN_CHILD_FRAGMENT      E  SmsListSlideFragment.onCreateView() isAdded() = true
MAIN_CHILD_FRAGMENT      E  SmsListSlideFragment.onViewCreated() isAdded() = true

MAIN_LIFECYCLE           E  MainController.onPause()
MAIN_FRAGMENT            E  AltRadioRemoteControlFragment.onPause() isAdded() = true

//main app resumes
MAIN_LIFECYCLE           E  MainController.onResume()

//switching between tab fragments in order f1 -> f2 -> f3 -> f1
MAIN_FRAGMENT            E  AltRadioRemoteControlFragment.onResume() isAdded() = true //f1 resume
MAIN_FRAGMENT            E  AltRadioRemoteControlFragment.onPause() isAdded() = true //f1 pause (switch to f2)
MAIN_FRAGMENT            E  OsmMapFragment.onResume() isAdded() = true //f2 resume
MAIN_FRAGMENT            E  OsmMapFragment.onPause() isAdded() = true //f2 pause (switch to f3)
MAIN_FRAGMENT            E  MainChatFragment.onResume() isAdded() = true //f3 resume
MAIN_CHILD_FRAGMENT      E  ChatSlideFragment.onResume() isAdded() = true //f3's child f1 resume
MAIN_FRAGMENT            E  MainChatFragment.onPause() isAdded() = true //f3 pause (switch to f1)
MAIN_FRAGMENT            E  AltRadioRemoteControlFragment.onResume() isAdded() = true //f1 resume

//quiting main app
MAIN_LIFECYCLE           E  MainController.onPause()
MAIN_FRAGMENT            E  AltRadioRemoteControlFragment.onPause() isAdded() = true
MAIN_FRAGMENT            E  AltRadioRemoteControlFragment.onStop() isAdded() = true
MAIN_FRAGMENT            E  OsmMapFragment.onStop() isAdded() = true
MAIN_FRAGMENT            E  MainChatFragment.onStop() isAdded() = true

MAIN_LIFECYCLE           E  MainController.onDestroy()
MAIN_FRAGMENT            E  AltRadioRemoteControlFragment.onDestroyView() isAdded() = true
MAIN_FRAGMENT            E  AltRadioRemoteControlFragment.onDetach() isAdded() = true
MAIN_FRAGMENT            E  OsmMapFragment.onDestroyView() isAdded() = true
MAIN_FRAGMENT            E  OsmMapFragment.onDetach() isAdded() = true
MAIN_CHILD_FRAGMENT      E  UserListSlideFragment.onDestroyView() isAdded() = true
MAIN_CHILD_FRAGMENT      E  ChatSlideFragment.onDestroyView() isAdded() = true
MAIN_CHILD_FRAGMENT      E  SmsListSlideFragment.onDestroyView() isAdded() = true
MAIN_FRAGMENT            E  MainChatFragment.onDestroyView() isAdded() = true
MAIN_CHILD_FRAGMENT      E  UserListSlideFragment.onDetach() isAdded() = true
MAIN_CHILD_FRAGMENT      E  ChatSlideFragment.onDetach() isAdded() = true
MAIN_CHILD_FRAGMENT      E  SmsListSlideFragment.onDetach() isAdded() = true
MAIN_FRAGMENT            E  MainChatFragment.onDetach() isAdded() = true

```

</p>
</details>

**Comment by CW12** [comment]
Sorry for my delay in getting back to you on this.

I have finally found the very simple solution...

        binding.mapView.setDestroyMode(false);
        
I feel the documentation on this could be improved

**Comment by monsieurtanuki** [comment]
Thank you @CW12!
Actually you can change the documentation: feel free to improve it.

**Comment by Tgarfr** [comment]
Thanks CW12,
`binding.mapView.setDestroyMode(false);`
it works.
What does destroy mode do, why does it solve the problem?
