### ISSUE TITLE
Is GeoPoint Serializable? [Strange Error in Android Studio]

### ISSUE THREAD

**Issue by kwesiRutledge** [osmdroid/osmdroid#1850]
## Issue Type

[x] Question
[ ] Bug
[ ] Improvement
[ ] Build system related
[ ] Performance
[ ] Documentation

## Description and/or steps/code to reproduce the problem

I've created an API that returns GPS data and want to connect my OSMDroid-based application to it. The application contains a function which should convert the API data into GeoPoint objects using the Serialize command. This is done via a class very similar to this (names have been changed for privacy concerns):

```
@Serializable
data class someAPIResponse (
    val Duration: Float,
    val Points: List<GeoPoint>,
    val Error: String
)
```
But Android Studio does not like this definition by itself. When I try to run the app, I get the error: `Serializer has not been found for type 'GeoPoint'. To use context serializer as fallback, explicitly annotate type or property with @Contextual`.

The documentation for GeoPoint made me think that a Serializer existed. Does it not? If the Serializer does exist, is there a known reason for why Android Studio doesn't recognize it?

This problem seems to be related to the issue here:
[https://github.com/GitLiveApp/firebase-kotlin-sdk/issues/324](https://github.com/GitLiveApp/firebase-kotlin-sdk/issues/324)

### If it's a bug, version(s) of android this affects:

All

### Version of osmdroid the issue relates to:

6.1.14

**Comment by eclectice** [comment]
New knowledge here: It is stated in the comment that Kotlin serialization cannot use Java serialization.
https://stackoverflow.com/questions/65398284/kotlin-serialization-serializer-has-not-been-found-for-type-uuid

**Comment by kwesiRutledge** [comment]
Interesting! Thank you for your response! It is really helpful to learn that the serialization mentioned in the comment I was reading is not Kotlin serialization. I will try to do a deep dive on this serialization concept in parallel with a work around for my problem.

Thanks, @eclectice !
