### ISSUE TITLE
Free use of sdk

### ISSUE THREAD

**Issue by BLoeT** [osmdroid/osmdroid#1861]
Issue Type
[ x ] Question

I'm a little confused because of the free use of the SDK. The first Sentence on the Repo "osmdroid is a (almost) full/free replacement" confused me. 
I have read the license file.

Could someone please tell me if I can use this SDK in my App (i want to upload this app also in AppStore) for free and without to publish source code?

I will use my own tile-server and just want to use the map and markers.

**Comment by spyhunter99** [comment]
It's free to use under the terms of ASL 2.0 license. There are a few
exceptions due to GPL dependencies on specific optional sub modules

It's an almost full replacement for Google maps

**Comment by BLoeT** [comment]
@spyhunter99 

Thank you very much :)
