### ISSUE TITLE
Current position at the bottom of the screen (setExpectedCenter) when bearing is not zero

### ISSUE THREAD

**Issue by mminelli** [osmdroid/osmdroid#1862]
Please note: issues related to or caused by osmbonuspack will be closed with a
suggestion to open an issue at https://github.com/MKergall/osmbonuspack

(feel free to delete whatever doesn't apply)

## Issue Type

[X] Question
[X] Bug
[ ] Improvement
[ ] Build system related
[ ] Performance
[ ] Documentation

## Description and/or steps/code to reproduce the problem

I want to keep the current position not in the center of the screen but at the bottom, like most applications do.
The problem is when the bearing is not 0, and I see the exact same behavior described in the (solved) issue #1348.

Specifically, my code is like

        if (followMe) {
            float bearing = 20;  // just to test with a bearing != 0, in reality this is "correct"
            mapView.setMapOrientation(bearing);
            mapView.setExpectedCenter(currentLocation, 0, (long) (mapView.getHeight() / 2 * 0.7));
        }

Somehow, it seems like the entire map, including the direction arrow at the bottom of the screen are rotating around the center of the screen, although I am not sure this is really what is happening.

Am I missing something?

### If it's a bug, version(s) of android this affects:

Tested on Android 10. All versions affected?

### Version of osmdroid the issue relates to:

6.1.13

**Comment by eclectice** [comment]
Is this your StackOverflow post? https://stackoverflow.com/questions/74046688/osmdroid-animate-to-current-location-with-pixel-offset?noredirect=1#comment130806285_74046688

**Comment by mminelli** [comment]
Yes, that's me :)

**Comment by eclectice** [comment]
OK, instead of ***MapView.setExpectedCenter***; I test this code:

```java
GeoPoint pos = new GeoPoint(me.getLatitude(), me.getLongitude());
mapView.setMapOrientation((float)me.getBearing());
mapView.setMapCenterOffset(0, (int) (mapView.getHeight()/ 2* 0.7));
mapController.setCenter(pos);
```

It accomplishes the desired design, with the device location's marker now a quarter below the original mapView center. 

Take note that the device location's marker is actually an extended **OverlayItem** object with some labels that change orientation depending on the bearing value. Its labels are now correctly oriented in accordance with the map's orientation, as determined by the ***mapView.setMapOrientation((float)me.getBearing())*** call (as evident in the screenshot below).

Only the markers for which no bearing is set will remain at zero degrees. Other colored Geopackages polygons and polylines behave similarly.


![image](https://user-images.githubusercontent.com/1452656/198196288-0b2f24f9-f2e7-4d50-8358-47b0246c8dd7.png)

**Comment by eclectice** [comment]
@mminelli Can we close this ticket now if it has already been adequately addressed?

**Comment by mminelli** [comment]
@eclectice Sorry for the late reply, it was a busy week and I had no time to try this out.
Thank you very much for your help, I think this does the trick.

So what I had missed is that I could set the map's offset and then just center the map on my position, and the offset would be taken into account. I will test this better the first time I bike around, but I think your code is working as expected.

Just out of curiosity, does it mean that the `setExpectedCenter` method I was originally using has a bug? Or was I using it incorrectly?

**Comment by eclectice** [comment]
***MapView.setExpectedCenter()*** simply calls ***MapController.animateTo()***, which performs a fling animation when translating to a given MapView position. The graphics performance of the device on which the app is running may have an effect on this animation. From my understanding of its code, ***MapController.animateTo()***, on the other hand, will not accept a single-touch gesture while the animation is still running, but it will accept it intermittently in between animation frame calls, which the user may interpret as a "lag" or "stutter". However, its code allows a pinch zoom or two-finger touch gesture to bypass this.

**Comment by mminelli** [comment]
OK thanks for the extra explanation.

I am not familiar with the internals of the library, so I cannot really have an opinion as to what it should do, but I will use the code you provided above with `setMapCenterOffset`, which seems to work fine.

Thanks again, closing.

**Comment by alina26** [comment]
> OK, instead of _**MapView.setExpectedCenter()**_ method; I test this code:
> 
> ```java
> GeoPoint pos = new GeoPoint(me.getLatitude(), me.getLongitude());
> mapView.setMapOrientation((float)me.getBearing());
> mapView.setMapCenterOffset(0, (int) (mapView.getHeight()/ 2* 0.7));
> mapController.setCenter(pos);
> ```
> 
> It accomplishes the desired design, with the device location's marker now a quarter below the original mapView center every time its device location changes, as in Google Maps and, to a lesser extent, Waze's similar navigation marker design.
> 
> Take note that the device location's marker (big cyan circle with a dark blue outline) in my app is actually an extended **ItemizedIconOverlay** object with some labels (id "1004", callsign "BRAVO", and speed info "0.00 km/h") that change orientation depending on the MapView projection. Its labels are now correctly oriented in accordance with the map's orientation, as determined by the _**mapView.setMapOrientation((float)me.getBearing())**_ call (as evident in the screenshot below). Colored Geopackages polygons and polylines also change orientation with respect to the MapView projection.
> 
> Only the markers from the **Marker** class for which no bearing is set will remain at zero degrees with no respect to the MapView projection.
> 
> ![image](https://user-images.githubusercontent.com/1452656/198196288-0b2f24f9-f2e7-4d50-8358-47b0246c8dd7.png)
> 
> Another way to do it is to use the _**MapController.animateTo()**_ method:
> 
> ```java
> GeoPoint pos = new GeoPoint(me.getLatitude(), me.getLongitude());
> mapView.setMapCenterOffset(0, (int) (mapView.getHeight()/ 2* 0.7));
> mapController.animateTo(pos, null, null, (float) me.getBearing(), Boolean.TRUE);
> ```
> 
> However, this version includes a fling animation effect that you may not like because it makes it difficult to pan/drag the map during its animation with a single-finger touch (you can only bypass it with a two-finger touch or a pinch zoom).

@eclectice Hi) I see that this issues is closed but maybe you can help me - it seems that yours solution works only when user doesn't scroll or zoom map(because there is mapController.setCenter(pos) - so scroll is blocked). So the question is - is it possible to make map rotate around arbitrary point on map(not center) and have ability to scroll or zoom map at the same time?
