### ISSUE TITLE
Attempted to finish an input event but the input event receiver has already been disposed.

### ISSUE THREAD

**Issue by xero88** [osmdroid/osmdroid#187]
Hi,

I got this error trying to implement osmdroid : 

Attempted to finish an input event but the input event receiver has already been disposed.

This error append when I try to move in the map. The map refuse to move.

Any idea ?
Cheers!

Anthony

**Comment by spyhunter99** [comment]
can you provide some sample code to reproduce?

**Comment by xero88** [comment]
Hi,

It was not a issue with osmdroid. 
A layout was under the mapView.

Cheers!
