### ISSUE TITLE
403 using OSMMapTilePackager-6.1.15

### ISSUE THREAD

**Issue by geek0075** [osmdroid/osmdroid#1872]
Please note: issues related to or caused by osmbonuspack will be closed with a
suggestion to open an issue at https://github.com/MKergall/osmbonuspack

(feel free to delete whatever doesn't apply)

## Issue Type

[x ] Question
[ ] Bug
[ ] Improvement
[ ] Build system related
[ ] Performance
[ ] Documentation

## Description and/or steps/code to reproduce the problem

Hi. I am running:

$ ./OSMMapTilePackager -gui

on my MacOS. After filling in the GUI as follows - as given by one of the examples on

https://github.com/osmdroid/osmdroid/tree/master/OSMMapTilePackager

-u http://b.tile.openstreetmap.org/%d/%d/%d.png -t Mapnik -d at_mapnik_13.zip -zmax 13 -n 49.03942 -s 46.40162 -e 17.14736 -w 9.44595

I keep getting back the following:

.Error downloading: 'z=2 x=2 y=1' from URL: https://b.tile.openstreetmap.org/2/2/1.png : java.io.IOException: Server returned HTTP response code: 403 for URL: https://b.tile.openstreetmap.org/2/2/1.png
.Error downloading: 'z=4 x=8 y=5' from URL: https://b.tile.openstreetmap.org/4/8/5.png : java.io.IOException: Server returned HTTP response code: 403 for URL: https://b.tile.openstreetmap.org/4/8/5.png
.Error downloading: 'z=2 x=2 y=1' from URL: https://b.tile.openstreetmap.org/2/2/1.png : java.io.IOException: Server returned HTTP response code: 403 for URL: https://b.tile.openstreetmap.org/2/2/1.png
...

When I open the same url on my chrome or safari browser the tile is right there! It shows up fine. I can view and download each of the above urls from chrome or safari web browser:

https://b.tile.openstreetmap.org/2/2/1.png
https://b.tile.openstreetmap.org/4/8/5.png
etc

But when I run:

$ ./OSMMapTilePackager -gui

fill in the parameters and execute, I get 403 in my command terminal. What is the solution to this? I suspect something simple is the solution...

## Environment

MacOS Catalina

### If it's a bug, version(s) of android this affects:

All

### Version of osmdroid the issue relates to:

6.1.15

**Comment by monsieurtanuki** [comment]
Hi @geek0075!
A look at [TileSourceFactory](https://github.com/osmdroid/osmdroid/blob/master/osmdroid-android/src/main/java/org/osmdroid/tileprovider/tilesource/TileSourceFactory.java):
```java
public static final OnlineTileSourceBase MAPNIK = new XYTileSource("Mapnik",
            0, 19, 256, ".png", new String[]{
            "https://a.tile.openstreetmap.org/",
            "https://b.tile.openstreetmap.org/",
            "https://c.tile.openstreetmap.org/"}, "© OpenStreetMap contributors",
            new TileSourcePolicy(2,
                    TileSourcePolicy.FLAG_NO_BULK
                            | TileSourcePolicy.FLAG_NO_PREVENTIVE
                            | TileSourcePolicy.FLAG_USER_AGENT_MEANINGFUL
                            | TileSourcePolicy.FLAG_USER_AGENT_NORMALIZED
            ));
```
I think a decent user agent is needed. How to implement that using OSMMapTilePackager is another story.

Other possible fix: I know that now OSM do not need the a,b,c prefix anymore. E.g. https://tile.openstreetmap.org/2/2/1.png
Perhaps that would help too:
```java
public static final OnlineTileSourceBase MAPNIK = new XYTileSource("Mapnik",
            0, 19, 256, ".png", new String[]{
            "https://tile.openstreetmap.org/"}, "© OpenStreetMap contributors",
            new TileSourcePolicy(2,
                    TileSourcePolicy.FLAG_NO_BULK
                            | TileSourcePolicy.FLAG_NO_PREVENTIVE
                            | TileSourcePolicy.FLAG_USER_AGENT_MEANINGFUL
                            | TileSourcePolicy.FLAG_USER_AGENT_NORMALIZED
            ));
```

**Comment by geek0075** [comment]
Hi @monsieurtanuki 

The source code for OSMMapTilePackager-6.1.15 is available:

[DownloadManager](https://github.com/osmdroid/osmdroid/blob/master/OSMMapTilePackager/src/main/java/org/osmdroid/mtp/download/DownloadManager.java)

The issue I see occurs in this segment of code:

`            try {
                in = new BufferedInputStream(new URL(finalURL).openStream(), StreamUtils.IO_BUFFER_SIZE);

                final FileOutputStream fileOut = new FileOutputStream(this.mDestinationFile);
                out = new BufferedOutputStream(fileOut, StreamUtils.IO_BUFFER_SIZE);

                StreamUtils.copy(in, out);

                out.flush();
            } catch (final Exception e) {
                System.err.println("Error downloading: '" + this.mTileInfo + "' from URL: " + finalURL + " : " + e);
                DownloadManager.this.add(this.mTileInfo); // try again later
            } finally {
                StreamUtils.closeStream(in);
                StreamUtils.closeStream(out);
            }
`
You can see the:

`System.err.println("Error downloading: '" + this.mTileInfo + "' from URL: " + finalURL + " : " + e);`

corresponds closely to the response I get:

Error downloading: 'z=2 x=2 y=1' from URL: https://b.tile.openstreetmap.org/2/2/1.png : java.io.IOException: Server returned HTTP response code: 403 for URL: https://b.tile.openstreetmap.org/2/2/1.png

So somewhere here:

`                in = new BufferedInputStream(new URL(finalURL).openStream(), StreamUtils.IO_BUFFER_SIZE);

                final FileOutputStream fileOut = new FileOutputStream(this.mDestinationFile);
                out = new BufferedOutputStream(fileOut, StreamUtils.IO_BUFFER_SIZE);

                StreamUtils.copy(in, out);

                out.flush();
` 
I have to add User Agent info and perhaps I will be good to go. How to do that is a research topic right now BUT I am researching...

**Comment by geek0075** [comment]
For the Android Mobile App Integration they provided a Configuration object used for setting the User Agent:
```
org.osmdroid.config.Configuration
```
One just calls the following:
```
Configuration.getInstance().setUserAgentValue("UserAgent")
```
Then the Android client starts to work. Perhaps someone on the development team @spyhunter99 for example can tell us how to do this for OSMMapTilePackager...

It should be simple enough....when you are on the team.

**Comment by geek0075** [comment]
OK. Solved this. I just changed the code in Download Manager as follows:

```
                URL tileServer = new URL(finalURL);
                URLConnection yc = tileServer.openConnection();
                yc.setRequestProperty("User-Agent", "<Enter Your User Agent Here!>");
                
                in = new BufferedInputStream(yc.getInputStream(), StreamUtils.IO_BUFFER_SIZE);

                final FileOutputStream fileOut = new FileOutputStream(this.mDestinationFile);
                out = new BufferedOutputStream(fileOut, StreamUtils.IO_BUFFER_SIZE);

                StreamUtils.copy(in, out);

                out.flush();
```

I picked some user agent text from here: 

[Common User Agents](https://techblog.willshouse.com/2012/01/03/most-common-user-agents/)

I rebuilt, and boom shakalaka - I am good to go ;-). Thanks for your pointer into source code. That led me to a solution...I hope this can help someone down the line.

Cheers.
