### ISSUE TITLE
Using least version osmdroid with examples

### ISSUE THREAD

**Issue by red0bear** [osmdroid/osmdroid#1881]
## Issue Type

[ ] Question
[ ] Bug
[ ] Improvement
[ ] Build system related
[ ] Performance
[ X ] Documentation

## Description and/or steps/code to reproduce the problem
well i try upgrade org.osmdroid:osmdroid-android:6.1.10 to org.osmdroid:osmdroid-android:6.1.14 but seems things changed a lot of. 
i would like to know if someone can point me to good examples with mapsforge local map using this new version.

**Comment by spyhunter99** [comment]
the wiki articles is all we have + the sample code for the sample app...which has a mapsforge sample in it. i'd start there

**Comment by red0bear** [comment]
response took too long ... decided make it my self https://github.com/red0bear/androidmapsexample
