### ISSUE TITLE
rendertheme gives exception

### ISSUE THREAD

**Issue by red0bear** [osmdroid/osmdroid#1883]
OSMDROID VERSION --> 6.1.10

min sdk version 21 / max 33 

    implementation 'org.mapsforge:mapsforge-map-android:0.18.0'
    // https://mvnrepository.com/artifact/org.mapsforge/mapsforge-core
    implementation 'org.mapsforge:mapsforge-core:0.18.0'
    implementation 'org.mapsforge:mapsforge-map:0.18.0'
    implementation 'org.mapsforge:mapsforge-themes:0.18.0'
    implementation 'org.mapsforge:sqlite-android:0.18.0'
    implementation 'com.caverock:androidsvg:1.4'

    implementation 'org.osmdroid:osmdroid-android:6.1.10'
    implementation 'org.osmdroid:osmdroid-mapsforge:6.1.10'
    // https://mvnrepository.com/artifact/org.osmdroid/OpenStreetMapViewer
    //implementation 'org.osmdroid:OpenStreetMapViewer:6.1.10'
    implementation files('libs/OpenStreetMapViewer-release-unsigned.apk')

While try uses OpenStreetMapViewer he gives W/DirectRenderer: Exception: java.lang.IllegalArgumentException: File error for XML rendertheme on rendertheme-v4.xml for local maps 

http://mapsforge.org/renderTheme site show not found/ forbbiden 
https://raw.githubusercontent.com/mapsforge/mapsforge/dev/resources/renderTheme-v4.xsd site show not found 404

**Comment by red0bear** [comment]
i did some examples trying make thing works https://github.com/red0bear/androidmapsexample

**Comment by spyhunter99** [comment]
we still target 0.11.0 of mapsforge. that's probably why you have an issue. either downgrade your dependency or open a PR for osmdroid to fix it
