### ISSUE TITLE
api key required

### ISSUE THREAD

**Issue by WislieZhu** [osmdroid/osmdroid#1892]
Please note: issues related to or caused by osmbonuspack will be closed with a
suggestion to open an issue at https://github.com/MKergall/osmbonuspack

(feel free to delete whatever doesn't apply)

## Issue Type

[ ] Question hint api key required,but I can't find it
[ ] Bug
[ ] Improvement
[ ] Build system related
[ ] Performance
[ ] Documentation

### If it's a bug, version(s) of android this affects:

All

### Version of osmdroid the issue relates to:

6.1.2

**Comment by monsieurtanuki** [comment]
Hi @WislieZhu!
Please create a new issue with details, if needed.
