### ISSUE TITLE
Multiple Maps are shown on screen in Android App Development using Android Studio

### ISSUE THREAD

**Issue by HMSafiullah** [osmdroid/osmdroid#1894]
Please note: issues related to or caused by osmbonuspack will be closed with a
suggestion to open an issue at https://github.com/MKergall/osmbonuspack

(feel free to delete whatever doesn't apply)

## Issue Type

[ ] Question
[ ] Bug
[ ] Improvement
[ ] Build system related

### If it's a bug, version(s) of android this affects:

All

### Version of osmdroid the issue relates to:

6.1.16

**Comment by spyhunter99** [comment]
https://github.com/osmdroid/osmdroid/blob/master/osmdroid-android/src/main/java/org/osmdroid/views/MapView.java#L1461  try that
