### ISSUE TITLE
How to calculate the length (distance) of a route?

### ISSUE THREAD

**Issue by Child0fTheSun** [osmdroid/osmdroid#1896]
Is there any way to calculate the route length in kilometers?

[ *] Question

6.1.13

**Comment by LostRat** [comment]
Loop through your points. The Location.distanceBetween function seems to be most convenient for me. I keep points in a unique class.  Divide total by 1000. (Smoothing out wild zig zags is a magic art that I cannot master.)
```
public float distanceBetween(myPointClass that) {
    float[] results = new float[5];
    Location.distanceBetween(this.getLatitude(), this.getLongitude(), that.getLatitude(), that.getLongitude(), results);
    // in meters
    return results[0];
}
```

**Comment by Child0fTheSun** [comment]
> Прокрутите свои точки. Функция Location.distanceBetween мне кажется наиболее удобной. Я держу очки в уникальном классе. Разделите сумму на 1000. (Сглаживание диких зигзагов — магическое искусство, которым я не могу овладеть.)
> 
> ```
> public float distanceBetween(myPointClass that) {
>     float[] results = new float[5];
>     Location.distanceBetween(this.getLatitude(), this.getLongitude(), that.getLatitude(), that.getLongitude(), results);
>     // in meters
>     return results[0];
> }
> ```

I understand correctly that this method returns the distance between two points?

Then I can calculate the distance between neighboring points in a loop and add the resulting results?

Thanks, you helped a lot!
