### ISSUE TITLE
Question: How to create a custom overlay

### ISSUE THREAD

**Issue by mslalith** [osmdroid/osmdroid#1897]
## Issue Type

[ ] Question

## Description and/or steps/code to reproduce the problem
How to add a custom overlay which shows custom buttons (which also can fade away after a while)

### Version of osmdroid the issue relates to:

6.1.2

**Comment by spyhunter99** [comment]
hmm you could do this with an osmdroid overlay, but it would probably be best if you did this with an android view that sits on top of the map view. then you can do whatever you want as long as you pass touch events, etc down to the map. there's a few examples of this in the sample app for drawing content on screen. This is done in an android view.

if you go the osmdroid overlay route, you'll have to deal with issues like map rotation. not sure if you want buttons to rotate with the map. that would be...out of the ordinary. hope this helps
