### ISSUE TITLE
Question: How to use this library in Xamarin

### ISSUE THREAD

**Issue by Spe1993** [osmdroid/osmdroid#1898]
## Issue Type 
[ ] Question

## Description and/or steps/code to reproduce the problem
i want ro know how to use this  library in Xamarin.when i want convert this to c# ,vs tell me many problems

### Version of osmdroid the issue relates to:

6.1.16

**Comment by spyhunter99** [comment]
i don't think you'll get much help here. osmdroid is a java android library. might want to google around for solutions to whatever problem you have.
