### ISSUE TITLE
marker.infoWindow not shown by click marker when markers loaded from the database

### ISSUE THREAD

**Issue by HosseinKurd** [osmdroid/osmdroid#1910]
## Issue Type

[ ] Bug

## Description and/or steps/code to reproduce the problem

marker.infoWindow is not shown by click marker when markers loaded from the database
Markers are called from the database and shown on the map, But _**setOnMarkerClickListener**_ doesn't work
but it works for markers added by **_mapEventsReceiver.singleTapConfirmedHelper_**

### If it's a bug, version(s) of android this affects:

All

### Version of osmdroid the issue relates to:

6.1.16

**Comment by spyhunter99** [comment]
uhhh osmdroid the library doesn't do anything with a database for markers. whatever problem you are seeing is an integration with your app and the library. i can't really help you without a fair about of sample code on this... even at that, it's probably not an issue with osmdroid
