### ISSUE TITLE
6.1.16 release plan

### ISSUE THREAD

**Issue by Lastoneee** [osmdroid/osmdroid#1912]
## Issue Type
[ ] Question

## Description and/or steps/code to reproduce the problem
The last LTS version (v6.1.13) of the osmdroid has been released in 2022. Is there any plan to release the new LTS version (6.1.16)? If so, when will it be released? 

### Version of osmdroid the issue relates to:
6.1.16

**Comment by spyhunter99** [comment]
whenever there is a need. i don't think there's been too many code changes
since then

**Comment by spyhunter99** [comment]
the last release was v6.1.16 Mar 31, 2023
