### ISSUE TITLE
i can't use this Mapbox Url in osmdroid

### ISSUE THREAD

**Issue by VishlDeveloper** [osmdroid/osmdroid#1915]
Please note: issues related to or caused by osmbonuspack will be closed with a
suggestion to open an issue at https://github.com/MKergall/osmbonuspack

(feel free to delete whatever doesn't apply)

## Can't use maptile from this mapbox url http://52.59.214.0/maanmittauslaitos/avoin/wmts/1.0.0/kiinteistojaotus/default/WGS84_Pseudo-Mercator/{z}/{y}/{x}.jpg

While using this url nothing shows up.

**please provide solution how to use mapbox url in the Osmdroid**

## Description and/or steps/code to reproduce the problem
While using this url in Mapbox this map tile render but not in osmdroid.
Is there a way to workout this issue .

i have used two types of code to showing map from url of Mapbox but both of showing only white screen.
1. mapbox code that i used.
`    private void setmapff() {
        MapBoxTileSource MAPBOXSATELLITELABELLED = new MapBoxTileSourceFixed("MapBoxSatelliteLabelled", 1, 19, 256);
        MAPBOXSATELLITELABELLED.retrieveAccessToken(FragmentMap.this);
        MAPBOXSATELLITELABELLED.retrieveMapBoxMapId(FragmentMap.this);
        TileSourceFactory.addTileSource(MAPBOXSATELLITELABELLED);
        map.setTileSource(MAPBOXSATELLITELABELLED);
        map.getOverlayManager().getTilesOverlay().setColorFilter(null);
        map.invalidate();
    }

    static class MapBoxTileSourceFixed extends MapBoxTileSource {
        MapBoxTileSourceFixed(String name, int zoomMinLevel, int zoomMaxLevel, int tileSizePixels) {
            super(name, zoomMinLevel, zoomMaxLevel, tileSizePixels, "");
        }

        @Override
        public String getTileURLString(final long pMapTileIndex) {
            //  StringBuilder url = new StringBuilder("https://api.mapbox.com/styles/v1/mapbox/");
            Log.d(TAG, "getTileURLStringofdata: " + pMapTileIndex);
            String DefaultToken = "pk.eyJ1IjoibWF0cmlkdGVjaDEyMyIsImEiOiJjbGxjNzJzamcwODRuM25xNWxvZWNyYXp1In0.6zD1jq8bf_cVV0pFLj1ibQ";
            StringBuilder url = new StringBuilder("http://52.59.214.0/maanmittauslaitos/avoin/wmts/1.0.0/kiinteistojaotus/default/WGS84_Pseudo-Mercator");
           /* url.append(getMapBoxMapId());*/
           /* url.append("/tiles/");*/
            url.append(MapTileIndex.getZoom(pMapTileIndex));
            url.append("/");
            url.append(MapTileIndex.getX(pMapTileIndex));
            url.append("/");
            url.append(MapTileIndex.getY(pMapTileIndex));
            //url.append("@2x"); //for high-res
            url.append("?access_token=").append(DefaultToken);
            String res = url.toString();
            Log.d(TAG, "getTileURLStringofdata: " + res);
            return res;
        }
    }
`

2.Osmdroid code

    public static final OnlineTileSourceBase TERRAIN =  new OnlineTileSourceBase("lantmateriet", 1, 18, 256, "pk.eyJ1IjoibWF0cmlkdGVjaDEyMyIsImEiOiJjbGxjNzJzamcwODRuM25xNWxvZWNyYXp1In0.6zD1jq8bf_cVV0pFLj1ibQ", new String[]{"http://52.59.214.0/lantmateriet/topowebb/default/3857/"}) {
        @Override
        public String getTileURLString ( long pMapTileIndex){
            String mImageFilenameEnding = ".png";
            String baseuser="http://52.59.214.0/maanmittauslaitos/avoin/wmts/1.0.0/kiinteistojaotus/default/WGS84_Pseudo-Mercator/";
            Log.e("terrain", " " + getBaseUrl() + MapTileIndex.getZoom(pMapTileIndex) + "/"
                    + MapTileIndex.getX(pMapTileIndex) + "/" + MapTileIndex.getY(pMapTileIndex)
                    + mImageFilenameEnding);
            return getBaseUrl() + MapTileIndex.getZoom(pMapTileIndex) + "/"
                    + MapTileIndex.getX(pMapTileIndex) + "/" + MapTileIndex.getY(pMapTileIndex);
            //+ mImageFilenameEnding;

      
        }
    };

[
map is showing white screen
![osmdroid image 1](https://github.com/osmdroid/osmdroid/assets/96579379/ea6bac85-3bdd-4c35-9ecb-633ebd95eae7)

Need to showing map like this screenshot
<img width="194" alt="Screenshotc" src="https://github.com/osmdroid/osmdroid/assets/96579379/52700bb0-9794-44f2-ad48-bdd175e5480e">
](url)

[](url)
### If it's a bug, version(s) of android this affects:

All

### Version of osmdroid the issue relates to:

6.1.2

**Comment by spyhunter99** [comment]
well that url gives me a 404. I'm guessing mapbox needs some kind of api key to access it. Did you provide the key to the map box source? There should be an example in the sample app
