### ISSUE TITLE
The project is dead?

### ISSUE THREAD

**Issue by panovvitalik** [osmdroid/osmdroid#1920]
Please note: issues related to or caused by osmbonuspack will be closed with a
suggestion to open an issue at https://github.com/MKergall/osmbonuspack

(feel free to delete whatever doesn't apply)

## Issue Type

[ ] Question
[ ] Bug
[ ] Improvement
[ ] Build system related
[ ] Performance
[ ] Documentation

### If it's a bug, version(s) of android this affects:

All

### Version of osmdroid the issue relates to:

6.1.2

**Comment by spyhunter99** [comment]
Hi, I do the release management for this project. I no longer have time to actively work on this project but I will push the button when required to cut a new release. I'm relying the community to open pull requests to fix issues or add features. Does that answer your question?

**Comment by panovvitalik** [comment]
> Hi, I do the release management for this project. I no longer have time to actively work on this project but I will push the button when required to cut a new release. I'm relying the community to open pull requests to fix issues or add features. Does that answer your question?

"push the button" I think is not enough to keep the project living.... :-(  It's sad
Anywat thank you for your answer

**Comment by panovvitalik** [comment]
NIce job

**Comment by panovvitalik** [comment]
Closed the bug - and thats all, no problems

**Comment by eclectice** [comment]
I found something odd with your app after looking at the image proof, but there are no issues with the OpenStreetMap map, the MAPNIK tile source, or the OsmDroid library. Please read my response: https://github.com/osmdroid/osmdroid/issues/1918
