### ISSUE TITLE
Maps broken

### ISSUE THREAD

**Issue by panovvitalik** [osmdroid/osmdroid#1921]
https://community.openstreetmap.org/t/topic/102894

https://community.openstreetmap.org/t/vandalism-report/102714

## Issue Type

[ ] Question
[ ] Bug
[ ] Improvement
[ ] Build system related
[ ] Performance
[ ] Documentation

### If it's a bug, version(s) of android this affects:

All

### Version of osmdroid the issue relates to:

6.1.2

**Comment by spyhunter99** [comment]
osmdroid is a library to rendering tiles from multiple map sources. if openstreetmaps doesn't work for you, use a different tile source.

**Comment by eclectice** [comment]
I found something odd with your app after looking at the image proof, but there are no issues with the OpenStreetMap map, the MAPNIK tile source, or the OsmDroid library. Please read my response: https://github.com/osmdroid/osmdroid/issues/1918
