### ISSUE TITLE
Could you please explain the source of your map data?

### ISSUE THREAD

**Issue by panovvitalik** [osmdroid/osmdroid#1922]
It's very important.
Because in browser it looks like the issue is solved, but osdmdroid show wrong broken data.
For details info please review my other bugs reports and my replies for the same issues - which you have "succesfuley" resolved.

First screen - osmdroid control
The second screen is an OpenStreetMap map from the browser.
![screen_osmdroid](https://github.com/osmdroid/osmdroid/assets/29057366/07ac0959-4ae9-4046-8142-c81b50d16e0c)
![screen_browser](https://github.com/osmdroid/osmdroid/assets/29057366/21a87e71-2fe7-480e-84cd-f40e315585ad)

## Issue Type

[ ] Question
[ X ] Bug
[ ] Improvement
[ ] Build system related
[ ] Performance
[ ] Documentation

### If it's a bug, version(s) of android this affects:

All

### Version of osmdroid the issue relates to:

6.1.2

**Comment by spyhunter99** [comment]
OK this is enough. You are now blocked. Not my problem, not the library

**Comment by eclectice** [comment]
I found something odd with your app after looking at the image proof, but there are no issues with the OpenStreetMap map, the MAPNIK tile source, or the OsmDroid library. Please read my response: https://github.com/osmdroid/osmdroid/issues/1918
