### ISSUE TITLE
Missing release information - not updated release page

### ISSUE THREAD

**Issue by michael-winkler** [osmdroid/osmdroid#1928]
## Issue Type

[ ] Question
[ ] Bug
[x ] Improvement
[ ] Build system related
[ ] Performance
[ ] Documentation

## Description and/or steps/code to reproduce the problem
It would be really great if the page of releases https://github.com/osmdroid/osmdroid/releases would get updates again.
Else it is really hard to notice that a new release was done.

As example I dont know whats changed in the last release.

**Comment by spyhunter99** [comment]
apologies. fixed
