### ISSUE TITLE
build faild~~ no support:compatibility

### ISSUE THREAD

**Issue by ikkyu0319** [osmdroid/osmdroid#194]
Error:(32, 13) Failed to resolve: android.support:compatibility-v4:23+

**Comment by neilboyd** [comment]
Please read the relevant [wiki](https://github.com/osmdroid/osmdroid/wiki) for your build method

**Comment by spyhunter99** [comment]
you may need to update your android sdk

**Comment by spyhunter99** [comment]
I'm going to go ahead a close this. Please reopen if this is still a problem for you @ikkyu0319. No one else appears to be having the problem and most likely the issue is that you need to run the android sdk updater tool

**Comment by rastikw** [comment]
What helped me was to change the dependencies line to:
```
compile 'com.android.support:support-v4:23+'
```

**Comment by ZKjellberg** [comment]
When building using **gradle**, the **OpenStreetMapViewer\build.gradle** will fail as it cannot discover
>compile 'android.support:compatibility-v4:23+'

As @rastikw suggested, replacing this with the below value will resolve the issue.
>compile 'com.android.support:support-v4:23+'
