### ISSUE TITLE
GitHub Pages site is outdated

### ISSUE THREAD

**Issue by EdricChan03** [osmdroid/osmdroid#1945]
Please note: issues related to or caused by osmbonuspack will be closed with a
suggestion to open an issue at https://github.com/MKergall/osmbonuspack

(feel free to delete whatever doesn't apply)

## Issue Type

[ ] Question
[ ] Bug
[ ] Improvement
[ ] Build system related
[ ] Performance
[x] Documentation

## Description and/or steps/code to reproduce the problem

The [GitHub Pages documentation site](https://osmdroid.github.io/osmdroid/) appears to be last updated 4 years ago according to the [deployments log](https://github.com/osmdroid/osmdroid/deployments/github-pages). The "latest" version also appears to be of a version that was [published in 2019 (v6.1.1)](https://github.com/osmdroid/osmdroid/releases/tag/osmdroid-parent-6.1.1).

**Comment by spyhunter99** [comment]
thanks for bringing this up. some people disliked the unmaintained gradle scripts we were using that generated the site. as such, it is no longer possible to generate it. we can delete the site if that makes sense. the content was build generated artifacts + the wiki converted to html. 

any opinions on this?

**Comment by spyhunter99** [comment]
only option is to deleted it or find another way to produce it. any suggestions?

**Comment by monsieurtanuki** [comment]
If it's just about code docs I never use them in any project. As it's open source I prefer to have a look at the code if needed.
Along with a good `README.md` and a wiki.
I would remove the documentation site: it's useless, outdated and nobody has time to maintain it one way or the other.

**Comment by spyhunter99** [comment]
it's been deactivated. all content is available on the wiki

**Comment by YewoMhango** [comment]
@spyhunter99 The repository's About sidebar still has a link to the old site. It got me confused initially about where to find the docs

**Comment by spyhunter99** [comment]
fixed, sorry about that
