### ISSUE TITLE
One-finger zoom in and out

### ISSUE THREAD

**Issue by tegorov** [osmdroid/osmdroid#1951]
## Issue Type

[ ] Question
[ ] Bug
[x] Improvement
[ ] Build system related
[ ] Performance
[ ] Documentation

## Description and/or steps/code to reproduce the problem

Hi, folks!
I want to zoom like on Google Maps:
https://github.com/osmdroid/osmdroid/assets/42921436/e60ba55b-f2a0-41b9-a43a-fdd7635f3610

This is the current behavior:
https://github.com/osmdroid/osmdroid/assets/42921436/d84c6fce-e051-4376-8ac9-25c4aa92284c

**Comment by spyhunter99** [comment]
this is really neat

**Comment by tegorov** [comment]
@spyhunter99 thanks! Can you review my pr please?
