### ISSUE TITLE
GeoPoint didn't work

### ISSUE THREAD

**Issue by joelurtubia** [osmdroid/osmdroid#196]
Hi, I'm Joel Urtubia,  I have a problem with "GeoPoint"  library...all is working as I expect, but when I try to use a Geopoint module, didn't worked, can you help me please to find that problem, I've followed all step of official manual , but always is the same only show me a "world map"  but never show me a GeoPoint  that I've configured,  attached all files "MainActivity.java", "activity_main.xml","AndroidManifiest.xml" and screenshoot of emulator

also I use "Android Studio" version 1.5

[AndroidManifest.xml.txt](https://github.com/osmdroid/osmdroid/files/44030/AndroidManifest.xml.txt)
[MainActivity.java.txt](https://github.com/osmdroid/osmdroid/files/44031/MainActivity.java.txt)
![gps](https://cloud.githubusercontent.com/assets/10262664/11401409/3a74741e-9371-11e5-88f2-45cab25affd9.png)

[build.gradle.txt](https://github.com/osmdroid/osmdroid/files/44029/build.gradle.txt)

**Comment by joelurtubia** [comment]
sorry ,I've used this version of osmdroid "org.osmdroid:osmdroid-android:5.0.1@aar"

**Comment by spyhunter99** [comment]
I'm not sure what your goal is. It sounds like you want an icon at a given lat/lon. Your code set's the center of the map at that lat/lon. It won't plot any points. If I'm understanding your correctly, you need an ItemizedIconOverlay. See the sample project for additional details.

**Comment by joelurtubia** [comment]
Thanks for your reply ,but i would like that in my map only appears Chile,not all world...how can i do that?...i thought this could be with Geopoint library....also Very sorry for my english 
Thanks for all!!!

**Comment by spyhunter99** [comment]
If you want to prevent the user from scrolling away from a specific bounds, use MapView.setScrollableArea

https://github.com/osmdroid/osmdroid/blob/master/osmdroid-android/src/main/java/org/osmdroid/views/MapView.java#L570

**Comment by joelurtubia** [comment]
thanks for your reply again, but as well I've followed your comments and this is my new code

[MainActivity.java.txt](https://github.com/osmdroid/osmdroid/files/44979/MainActivity.java.txt)

I've launched the emulator without any error, I've thought that should be ok, but still didn't work, show me the same screen, only working with manually scroll,attached a log of emulator

[LogSetScrollArea.txt](https://github.com/osmdroid/osmdroid/files/44982/LogSetScrollArea.txt)

can you help me please to find what should be my problem?..appreciate your help..

**Comment by spyhunter99** [comment]
try setting the min/max zoom levels. when you're zoomed out (lower numbers, higher altitude), the bounding box has little effect.

**Comment by joelurtubia** [comment]
Hi...
very sorry for delay but  I found my problem, ....into the file MainActivity.java didn't work if i use this library

android.support.v7.app.AppCompatActivity

but if i use this library

android.support.v7.app.ActionBarActivity

all was solved, this is the line that I've change

public class MainActivity extends ActionBarActivity {

attached java file and build.gradle file
[MainActivity.java.txt](https://github.com/osmdroid/osmdroid/files/49847/MainActivity.java.txt)

[build.gradle.txt](https://github.com/osmdroid/osmdroid/files/49849/build.gradle.txt)

but this library will be remplace for  "android.support.v7.app.AppCompatActivity", do you know why send me an error when I've used this library?

PD: very sorry , I'm very new in android

thanks...

**Comment by spyhunter99** [comment]
Try just plain old "Activity"

**Comment by joelurtubia** [comment]
Thanks is working!!, But I still don't know what is the main difference, "android studio" software  by default always use this library "AppCompatActivity"
