### ISSUE TITLE
Poposal for modification of adjustForDateLine for low zoom levels

### ISSUE THREAD

**Issue by stellardeveloper** [osmdroid/osmdroid#197]
When fixing a bug of the osmbonuspack.Polyline (see issue   https://github.com/MKergall/osmbonuspack/issues/170) I noticed, that at low zoom levels, when two or more entire maps are displayed on the screen, objects like markers or lines are distributed on two maps, even if there is enough space on the screen to draw then in the same map. 

In order to keep things together I would  like to suggest a modification which keeps points and lines together at lower zoomLevels if the screen size is exceeding the mapSize:

	protected Point adjustForDateLine (int x, int y, Point reuse) {
		final Point out = reuse != null ? reuse : new Point();
		out.set(x, y);
		out.offset(-mMapViewWidth / 2, -mMapViewHeight / 2);     //
		final int mapSize = TileSystem.MapSize(getZoomLevel());
		final int absX = Math.abs(out.x);
		final int absY = Math.abs(out.y);
		final int yCompare = mapSize > mMapViewHeight ? mapSize : mMapViewHeight;  // avoid too early vertical adjusting
		if (absX > Math.abs(out.x - mapSize)) {
			out.x -= mapSize;
		}
		if (absX > Math.abs(out.x + mapSize)) {
			out.x += mapSize;
		}

		if (absY > Math.abs(out.y - yCompare) && mMapViewHeight < 2* mapSize) {  // use yCorrection instead of mapSize
			out.y -= mapSize;
		}
		if (absY > Math.abs(out.y + yCompare) || mMapViewHeight >= 2* mapSize) {  // use yCorrection instead of mapSize
			out.y += mapSize;
		}
		out.offset(mMapViewWidth / 2, mMapViewHeight / 2);
		return out;
	}

However, this should be checked carefully for rotated screens and modified, if necessary, as mMapViewHeight is not the relevant screen height in rotated maps.

**Comment by spyhunter99** [comment]
I made the change, but noticed nothing different for single point icons. Is the problem area related to multipoint stuff, like lines and polygons?

**Comment by stellardeveloper** [comment]
> Is the problem area related to multipoint stuff, like lines and polygons?

No, all items using the adjustForDateLine method are affected. 
Example: Set a marker and scroll the map at zoom level 1 upward. 
Without the modification the marker will jump into the next replicated map below before it is reaching the top map border.
With the modification the markerwill jump down just before it will scroll outside the map view area.

**Comment by spyhunter99** [comment]
I took a screencast of the before and after and definitely see the difference now. Good find!

**Comment by spyhunter99** [comment]
merged
