### ISSUE TITLE
Custom ZoomIn and ZoomOut buttons. How to implement custom zoomOut/zoomIn buttons?

### ISSUE THREAD

**Issue by invweb** [osmdroid/osmdroid#1972]
## Issue Type
[x] Question
[x] Bug
[ ] Improvement
[ ] Build system related
[ ] Performance
[ ] Documentation

## Description and/or steps/code to reproduce the problem
Hello, I tried to implement custom zoomIn/zoomOut buttons. There are no zoomIn() or zoomOut() methods in the CustomZoomButtonsController. How to implement custom zoomOut/zoom In buttons

### Version of osmdroid the issue relates to:

**6.1.18**

![Screenshot 2024-01-20 at 08 21 10](https://github.com/osmdroid/osmdroid/assets/2270351/412bd06a-7cf5-4dd1-9eb0-65c8347adde6)
![Screenshot 2024-01-20 at 08 25 03](https://github.com/osmdroid/osmdroid/assets/2270351/9ea72779-372c-43a6-b393-ff7138e01e6a)

Why are these methods not available in the latest version?

**Comment by invweb** [comment]
![Screenshot 2024-01-20 at 08 21 10](https://github.com/osmdroid/osmdroid/assets/2270351/412bd06a-7cf5-4dd1-9eb0-65c8347adde6)
![Screenshot 2024-01-20 at 08 25 03](https://github.com/osmdroid/osmdroid/assets/2270351/9ea72779-372c-43a6-b393-ff7138e01e6a)

**Comment by invweb** [comment]
Why are these methods not available in the latest version?

**Comment by spyhunter99** [comment]
uhh not sure what you're quoting. might want to look at the example app. there should be one for custom zoom buttons

**Comment by invweb** [comment]
```
 binding.fabMapZoomIn.setOnClickListener {
            val myMapController = mapView?.controller
            mapView?.let {
                myMapController?.setZoom(it.zoomLevelDouble * Constants.DEFAULT_ZOOM_LEVEL)
            }
        }

        binding.fabMapZoomOut.setOnClickListener {
            val myMapController = mapView?.controller
            mapView?.let {
                myMapController?.setZoom(it.zoomLevelDouble / Constants.DEFAULT_ZOOM_LEVEL)
            }
        }
```
