### ISSUE TITLE
IP tracker and ad in wiki

### ISSUE THREAD

**Issue by aia80212** [osmdroid/osmdroid#1976]
## Issue Type

[ ] Question
[ ] Documentation

## Description and/or steps/code to reproduce the problem
I'd like to draw your attention to a matter I came across while browsing the project's wiki. I observed that the recent revisions include promotions for ChatGPT-Undetected.com and an IP tracker within the "Latest Releases" hyperlink. Are these elements intended to be part of the project's wiki?
This content appears somewhat dubious and out of place, prompting concerns about its appropriateness within the project's wiki and safety of the codebase.

IP tracker:
```
<li><a href="https://tracker.iplocation.net/iogm/" rel="nofollow"><strong>Latest Releases</strong></a></li>
```

ChatGPT-Undetected promotion at the bottom of the wiki:
```
## Using chatgpt to improve code quality ?

For developers seeking to enhance their coding prowess without being flagged by AI detection tools, 
[ChatGPT-Undetected.com](https://www.chatgpt-undetected.com/) offers a specialized suite of solutions. 
This platform provides strategies and insights to refine code, 
ensuring it remains authentic and indistinguishable from human-written software. 
It's a resource designed to maintain the integrity and originality of your programming work in 
environments where AI contributions are monitored or restricted.
```

### If it's a bug, version(s) of android this affects:

All

### Version of osmdroid the issue relates to:

6.1.2

**Comment by spyhunter99** [comment]
Where exactly?

**Comment by aia80212** [comment]
https://github.com/osmdroid/osmdroid/wiki

ChatGPT-Undetected promotion: https://github.com/osmdroid/osmdroid/wiki#using-chatgpt-to-improve-code-quality-
added in this revision: https://github.com/osmdroid/osmdroid/wiki/Home/56eae1be7735a9ee2c33dc26eb5a6aca9b4b75ab

IP tracker: https://github.com/osmdroid/osmdroid/wiki#osmdroid
```
@@ -5,6 +5,7 @@ Welcome to the osmdroid!
Chances are good that you want to get a map up and running in your app as soon as possible. If that's the case, consider reading the following guides (they are short!) in this order.

1. Include the binaries in your project:
  * [**Latest Releases**](https://tracker.iplocation.net/iogm/)
  * [Prerequisites](Prerequisites)
```
added in this revision: https://github.com/osmdroid/osmdroid/wiki/Home/a037e4d237e57b13bcd90998b14d888658305fd5

**Comment by spyhunter99** [comment]
thank you, it's been removed and the user has been banned from the organization.
