### ISSUE TITLE
BingMapTileSource　always crash 

### ISSUE THREAD

**Issue by sby5388** [osmdroid/osmdroid#1986]
Please note: issues related to or caused by osmbonuspack will be closed with a
suggestion to open an issue at https://github.com/MKergall/osmbonuspack

(feel free to delete whatever doesn't apply)

## Issue Type
[ ] Bug

## Description and/or steps/code to reproduce the problem
as you know ,in China ,I can't use bingMap direct, so i use vpn
if the network is unavailable (like i don't open vpn-app), the osmdroid with bingmap work  even it could not show bing-map-tile well ,just display  old cached;
but when I enable vpn-app, it work well just 20-seconds and crash,this not happened in all devices;
these are crash log
```
java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
 at java.util.Formatter.parse(Formatter.java:2546)
 at java.util.Formatter.format(Formatter.java:2505)
 at java.util.Formatter.format(Formatter.java:2459)
 at java.lang.String.format(String.java:2870) 
at org.osmdroid.tileprovider.tilesource.bing.BingMapTileSource.getTileURLString(BingMapTileSource.java:124)
at org.osmdroid.tileprovider.modules.MapTileDownloader$TileLoader.loadTile(MapTileDownloader.java:188)
at org.osmdroid.tileprovider.modules.MapTileModuleProviderBase$TileLoader.loadTileIfReachable(MapTileModuleProviderBase.java:213)
at org.osmdroid.tileprovider.MapTilePreCache.search(MapTilePreCache.java:127)
at org.osmdroid.tileprovider.MapTilePreCache.access$100(MapTilePreCache.java:31)
at org.osmdroid.tileprovider.MapTilePreCache$1.run(MapTilePreCache.java:42)
at org.osmdroid.util.GarbageCollector$1.run(GarbageCollector.java:32)
                                                            
```

    @Override
    public String getTileURLString(final long pMapTileIndex) {
        if (!mImageryData.m_isInitialised) {
            initMetaData();
        }
        return String.format(mUrl, quadTree(pMapTileIndex));
    }

the NPE happened at 3rd-lib && java-framework in thread ，so I can't caught it;
 so why and what should i do to  handle it or avoid app-crash ?
 
## Environment
android 11
org.osmdroid:osmdroid-android:6.1.11@aar
### If it's a bug, version(s) of android this affects:

android-api-30
abdroid-version:11

### Version of osmdroid the issue relates to:

6.1.11

**Comment by spyhunter99** [comment]
it calls the function BingMapTileSource#initMetaData which attempts to fetch data from 
https://dev.virtualearth.net/REST/V1/Imagery/Metadata/%s?mapVersion=v1&output=json&uriScheme=https&key=%s
defaulting to the road imagery set using your bing map key.

The bing map key can set via a variety of mechanisms.
- BindMapTileSource#setBingKey
- BindMapTileSource#retrieveBingKey(context) if you store the key in your app's manifest using BING_KEY
see https://github.com/osmdroid/osmdroid/blob/master/OpenStreetMapViewer/src/main/AndroidManifest.xml#L195 for an example

it's also entirely possible that bind has updated how map tiles work and that none of this works anymore. may need to consult their documentation on map tile access.

**Comment by sby5388** [comment]
> 它调用函数 BingMapTileSource#initMetaData 尝试从 https://dev.virtualearth.net/REST/V1/Imagery/Metadata/%s?mapVersion=v1&output=json&uriScheme=https&key=%s获取数据 ，默认为道路图像集使用您的 bing 地图密钥。
> 
> bing 地图密钥可以通过多种机制进行设置。
> 
> * BindMapTileSource#setBingKey
> * BindMapTileSource#retrieveBingKey(context) 如果您使用 BING_KEY 将密钥存储在应用程序的清单中，
>   请参阅https://github.com/osmdroid/osmdroid/blob/master/OpenStreetMapViewer/src/main/AndroidManifest.xml#L195获取示例
> 
> 也完全有可能，bind 更新了地图图块的工作方式，而这些都不再起作用了。可能需要查阅有关地图图块访问的文档。

---
thanks.it wotk
