### ISSUE TITLE
wiki: to figure out how to load tiles

### ISSUE THREAD

**Issue by emnrd-ito** [osmdroid/osmdroid#199]
This statement in the [wiki](https://github.com/osmdroid/osmdroid/wiki/How-to-use-the-osmdroid-library) doesn't make sense ("to figure out how to load tiles" appears twice):

OsmDroid uses a Tile Provider *to figure out how to load tiles* (online, offline, assets folders, etc) and a Tile Source (Bing, Mapquest, Mapnik, etc) *to figure out how to load tiles*.

**Comment by spyhunter99** [comment]
just updated it. does it make more sense now?

**Comment by emnrd-ito** [comment]
Looks good, thanks.
