### ISSUE TITLE
Can not launch app with version 5.0.1

### ISSUE THREAD

**Issue by hamzux** [osmdroid/osmdroid#200]
Hello, 
I'm having a strange problem when using osmdroid 5.0.1@aar : 
* What went wrong:
Execution failed for task ':app:dexDebug'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'C:\Program Files\Java\jdk1.7.0_03\bin\java.exe'' finished with non-zero exit value 2

when enabling multiDex I get : 
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:packageAllDebugClassesForMultiDex'.
> java.util.zip.ZipException: duplicate entry: microsoft/mappoint/TileSystem.class

Thanks

**Comment by spyhunter99** [comment]
what's in your dependency list?

**Comment by spyhunter99** [comment]
ping

**Comment by spyhunter99** [comment]
in about 2 seconds worth a googling, the problem is most likely a dependency issue where you have two different versions of osmdroid and osmdroid thirdparty or something to that effect.

**Comment by spyhunter99** [comment]
ping time out. From what little info you provided, it looks like it's not an osmdroid issue. Feel free to reopen or post back what your solution was
