### ISSUE TITLE
Vertical replication of the map

### ISSUE THREAD

**Issue by MKergall** [osmdroid/osmdroid#201]
osmdroid map is replicated vertically: just below the south pole, the north pole area is displayed. And just above the north pole, the south pole area is displayed. 
This is particularly noticeable at very low zoom levels, when the whole map is shown, and replicated above and below. 

In fact, this vertical replication doesn't make sense. The north pole is not "just below" the south pole. 
Google Maps, OSM web site, Bing Maps, MapQuest, Mappy: nobody else is doing that. They just put a grey filling. 
In addition, it causes issues on overlays drawing... 

So I strongly suggest to remove this vertical replication of the map, and fill in grey when "outside the map".

**Comment by spyhunter99** [comment]
+1. I wish I had time to work on it. Feel free to open a PR if you're inclined

**Comment by spyhunter99** [comment]
if i were a betting man, i'd guess and say that the fix would probably lay within the Projection class.

**Comment by spyhunter99** [comment]
related to #197

**Comment by MKergall** [comment]
Fix for stopping vertical replication of the map
Chapter 1 - Results of first investigations

In TileLooper.loop, we have this: 

		TileSystem.PixelXYToTileXY(pViewPort.left, pViewPort.top, mUpperLeft);
		mUpperLeft.offset(-1, -1);
		TileSystem.PixelXYToTileXY(pViewPort.right, pViewPort.bottom, mLowerRight);

Those mUpperLeft and mLowerRight define the bounding box to fill with tiles. 
The y loop below fills the whole view vertically with tiles: 

		/* Draw all the MapTiles (from the upper left to the lower right). */
		for (int y = mUpperLeft.y; y <= mLowerRight.y; y++) {
			for (int x = mUpperLeft.x; x <= mLowerRight.x; x++) {
				// Construct a MapTile to request from the tile provider.
				final int tileY = MyMath.mod(y, mapTileUpperBound);
				final int tileX = MyMath.mod(x, mapTileUpperBound);
				final MapTile tile = new MapTile(pZoomLevel, tileX, tileY);
				handleTile(pCanvas, pTileSizePx, tile, x, y);
			}
		}

Solution: limit mUpperLeft.y and mLowerRight.y to the "appropriate" values... 

Next chapter to come: find those appropriate limits...

**Comment by spyhunter99** [comment]
Nice work

**Comment by oliverlockwood** [comment]
@spyhunter99 can you please clarify - am I to understand that this was fixed in `v6.0.0`? Is there a corresponding PR that went in?

**Comment by oliverlockwood** [comment]
Never mind, I found the answer myself.  For future reference of others:

-  https://github.com/osmdroid/osmdroid/releases/tag/osmdroid-parent-6.0.0 mentions:
    >Map View repetition can now be disabled

-  https://github.com/osmdroid/osmdroid/blob/master/osmdroid-android/src/main/java/org/osmdroid/views/MapView.java#L741-L759 shows the relevant function `setScrollableAreaLimitLatitude()` that can be used  to solve this issue.

**Comment by monsieurtanuki** [comment]
@oliverlockwood Please consider also `MapView.setVerticalMapRepetitionEnabled`.

**Comment by vincent-paing** [comment]
What's the exact method do we have to call to prevent repetition both horizontally and vertically?

**Comment by spyhunter99** [comment]
`MapView#setHorizontalMapRepetitionEnabled`
