### ISSUE TITLE
load 4326 coordinate system wmts map service

### ISSUE THREAD

**Issue by swzjzz1314** [osmdroid/osmdroid#2014]
In version 6.1.18, load 4326 coordinate system wmts map service, how should it be implemented?

This is my code, but TileCol and TileRow keep pulling out incorrect values

 private OnlineTileSourceBase tianDiTuImgTileSource = new XYTileSource("wx", 16, 18, 256, "png",
            new String[]{url}) {
        @Override
        public String getTileURLString(final long pMapTileIndex) {
            String url = getBaseUrl() + "&TileRow=" + MapTileIndex.getY(pMapTileIndex) + "&TileCol=" + MapTileIndex.getX(pMapTileIndex)
                    + "&TileMatrix=" + "EPSG:4326:" + MapTileIndex.getZoom(pMapTileIndex);
            ALogUtils.d(url);
            return url;
        }
    };

**Comment by wanjixin133yx** [comment]
Have you solved your problem? I am also using osmroid to load WMTS layers and have encountered a similar issue as you, where layer tiles cannot be displayed properly
