### ISSUE TITLE
is MapBoxTileSource still working?

### ISSUE THREAD

**Issue by MKergall** [osmdroid/osmdroid#202]
I'm fighting to get my MapBox map working under osmdroid 5.0.1. 
I get the grey grid, and numerous logs like: 
"IOException downloading MapTile: /2/3/3 : java.io.IOException: Received authentication challenge is null"

Something strange: 

MapBox is documenting its static map api this way: 
https://api.mapbox.com/v4/{mapid}/{lon},{lat},{z}/{width}x{height}.{format}?access_token=<your access token>
(see https://www.mapbox.com/developers/api/static/)

But osmdroid 5.0.1 MapBoxTileSource is building a url like this: 
https://api.mapbox.com/v4/{mapid}/{zoom}/{x}/{y}.png?access_token=<your access token>

**Comment by spyhunter99** [comment]
i tested after the last set of changes and it was working. I used the following guide for url patterns...

https://www.mapbox.com/developers/api/maps/#mapids

https://api.mapbox.com/v4/{mapid}/{z}/{x}/{y}.{format}?access_token=<your access token>

**Comment by MKergall** [comment]
Oh, I missed to add this new call: MapBoxTileSource.retrieveAccessToken(context);
Now it works!

BTW, this MapBoxTileSource API is really weird: it's mandatory to set these 2 params in the manifest, AND it's mandatory to do these 2 calls. 
And we still cannot set for instance 2 different MapBoxTileSources in the same app, because those params are static.

**Comment by spyhunter99** [comment]
I think the idea is that you can either define the params in the manifest
OR provide them programmatically. Not too much of a stretch to have a per
tile source settings.

**Comment by MKergall** [comment]
Unfortunately, we cannot provide them programmatically. The 2 mandatory calls are just here to launch manifest params loading. Have a look in the code, you will see what I mean...

**Comment by spyhunter99** [comment]
there is a setMapboxId and a setAccessToken methods.

**Comment by spyhunter99** [comment]
oh. it's not static. fix coming soon. i'll change it so that there's an additional constructor for the mapbox id and access token. stuff that accesses the manifest will still be present.

**Comment by spyhunter99** [comment]
should be fixed now, feel free to test it out.

**Comment by spyhunter99** [comment]
operation time out.

and i just tested it on the sample app which now prompts for the api key and map id.  see #231
