### ISSUE TITLE
Need to update target API level before Aug 31, 2024

### ISSUE THREAD

**Issue by neilboyd** [osmdroid/osmdroid#2029]
I'm still the admin of the app in the Google Play Store. I received this email from Google:

![image](https://github.com/user-attachments/assets/b7479cd2-4faa-4b3c-a380-a341fa115835)

Someone needs to fix this and publish a new version.

@osmdroid/admins

**Comment by spyhunter99** [comment]
tracking. i'll cut to cut a release this weekend if i have time

**Comment by neilboyd** [comment]
@spyhunter99 did you see the email I sent you?
