### ISSUE TITLE
Use a .media file to tell gallery to ignore tiles instead of adding a .tile extension

### ISSUE THREAD

**Issue by neilboyd** [osmdroid/osmdroid#207]
The reason the map tiles have a ".tile" extension is a misinformed decision way back in the [old issue 79](https://code.google.com/p/osmdroid/issues/detail?id=79).

We add a [".tile" extension](https://github.com/osmdroid/osmdroid/blob/master/osmdroid-android/src/main/java/org/osmdroid/tileprovider/constants/OpenStreetMapTileProviderConstants.java#L57) to the map tiles so that the gallery doesn't index the map tiles.

However there are [two other ways](http://www.addictivetips.com/mobile/how-to-prevent-a-directory-from-being-scanned-by-android-gallery/) of achieving this:

1. Create a ".nomedia" file in the folder
2. Add a dot prefix to the folder

Either of these seems like a better idea than adding the ".tile" extension.

**Comment by oseiler2** [comment]
FYI, Be aware that some apps don't seem to care about .nomedia. I came across a Samsung Galaxy that crawled all folders and parsed all .png/.gif/.jpgs even with the .nomedia file present and in a .[xyz] folder. On every reboot the device became unusable for minutes and chewed through a lot of battery. Chenging the file extensions back to .tile prevented this.

**Comment by spyhunter99** [comment]
we could also use the calling applications private data directory or make the tiles folder hidden. Maybe a combination of all these

**Comment by neilboyd** [comment]
It's nice to have a discussion about this. That was the purpose of the issue :)
I can easily believe that some devices have different levels of support for these features.
Of course it's easier to keep it as it is, but it seems like there should be a better way.

**Comment by spyhunter99** [comment]
I think adding a .nomedia file should cover most cases. For edge cases, leaving the .tile extension should probably be left in place.  i'll see if can i jam it into a static initializer so it loads only at start up

**Comment by spyhunter99** [comment]
fixed. works as expected on a samsung s5. feel free to reopen if my patch needs work or if this reoccurs on another device/os combo

**Comment by spyhunter99** [comment]
here's a related thread on SO http://stackoverflow.com/questions/10697276/android-nomedia-not-working-for-images
