### ISSUE TITLE
ScaleBar aligned bottom or right

### ISSUE THREAD

**Issue by stellardeveloper** [osmdroid/osmdroid#212]
I want to include a scale bar, but bottom aligned. As it is still on the ScaleBarOverlay'sTODO list, I did it.
My solution:
modifying/adding a few variables and methods:

	private final MapView mMapView;

	protected boolean alignBottom = false;
	protected boolean alignRight  = false;

	public void setCentred(final boolean centred) {
		this.centred = centred;
		alignBottom  = !centred;
		alignRight   = !centred;
		lastZoomLevel = -1; // Force redraw of scalebar
	}
	
	public void setAlignBottom(final boolean alignBottom) {
		this.centred = false;
		this.alignBottom  = alignBottom;
		lastZoomLevel = -1; // Force redraw of scalebar
	}

	public void setAlignRight(final boolean alignRight) {
		this.centred = false;
		this.alignRight  = alignRight;
		lastZoomLevel = -1; // Force redraw of scalebar
	}

For further operations we need the size of the mapView. I changed the constructor like this:

	public ScaleBarOverlay(final MapView mapView) {
		this(mapView, new DefaultResourceProxyImpl(mapView.getContext()));
	}

	public ScaleBarOverlay(final MapView mapView, final ResourceProxy pResourceProxy) {
		super(pResourceProxy);
		this.mMapView = mapView;
		this.resourceProxy = pResourceProxy;
		this.context = mapView.getContext();
               // the rest of constructor is not  changed

Unfortunately, when creating the scaleBar in onCreate or similar mthods, the mapView dimensions are still set to zero, but they are visible at onDraw. So Initialization of screenWidth and height is useless in the constructor. Of  course you have  to call the constructor now with your current mapView as the parameter.

Add to the draw method

			screenWidth	   = mMapView.getWidth();
			screenHeight   = mMapView.getHeight();

BEFORE calling  
  final IGeoPoint center = projection.fromPixels(screenWidth / 2, screenHeight / 2, null)!

BTW: until now, the center was not exactly the center, as you usually have appr. 100 pixels of window borders on top of your screen.

Also add to draw method

			if (alignBottom) offsetY *=-1;
			if (alignRight ) offsetX *=-1;

after offsetX and offsetY initialization. This will keep the offset effect independent of the alignment.

The largest modification is required in rebuildBarPath:

                // .... parts before comment "create text" are not changed

		// create text
		final String xMsg = scaleBarLengthText((int) xMetersAdjusted);
		final Rect xTextRect = new Rect();
		textPaint.getTextBounds(xMsg, 0, xMsg.length(), xTextRect);
		int xTextSpacing = (int) (xTextRect.height() / 5.0);           

		// create text
		final String yMsg = scaleBarLengthText((int) yMetersAdjusted);
		final Rect yTextRect = new Rect();
		textPaint.getTextBounds(yMsg, 0, yMsg.length(), yTextRect);
		int yTextSpacing = (int) (yTextRect.height() / 5.0);
		int xTextHeight  = xTextRect.height();
		int yTextHeight  = yTextRect.height();

		barPath.rewind();
		
		// ** alignBottom ad-ons, initilize with their former values  
		int barOriginX = 0;
		int barOriginY = 0;
		int barToX     = xBarLengthPixels;
		int barToY	   = yBarLengthPixels;
		if (alignBottom) {
			xTextSpacing *= -1;
			xTextHeight  *= -1;
			barOriginY   = mMapView.getHeight();
			barToY       = barOriginY -yBarLengthPixels;
		}
				
		if (alignRight) {
			yTextSpacing *= -1;
			yTextHeight  *= -1;		
			barOriginX   = mMapView.getWidth();
			barToX       = barOriginX -xBarLengthPixels;    
		}
		
		if (latitudeBar) {
			// draw latitude bar
			barPath.moveTo(barToX, barOriginY +xTextHeight + xTextSpacing * 2);
			barPath.lineTo(barToX, barOriginY);
			barPath.lineTo(barOriginX, barOriginY);

			if (!longitudeBar) {
				barPath.lineTo(barOriginX,  barOriginY +xTextHeight + xTextSpacing * 2);
			}
			latitudeBarRect.set(barOriginX, barOriginY, barToX, barOriginY +xTextHeight + xTextSpacing * 2);
		}

		if (longitudeBar) {
			// draw longitude bar
			if (!latitudeBar) {
				barPath.moveTo(barOriginX +yTextHeight + yTextSpacing * 2, barOriginY);
				barPath.lineTo(barOriginX, barOriginY);
			}

			barPath.lineTo(barOriginX, barToY);
			barPath.lineTo(barOriginX +yTextHeight + yTextSpacing * 2, barToY);

			longitudeBarRect.set(barOriginX, barOriginY, barOriginX +yTextHeight + yTextSpacing * 2, barToY);
		}
	}

Now change/add in the drawLatitudeText bevore calling canvas.drawText:

		float x = xBarLengthPixels / 2 - sTextBoundsRect.width() / 2;
		if (alignRight)  x+= screenWidth -xBarLengthPixels;
		float y; 
		if (alignBottom) { y = screenHeight   -xTextSpacing*2; }
		else y = sTextBoundsRect.height() + xTextSpacing;

and do similar in  drawLongitudeText before calling canvas.save():

		float x; 
		if (alignRight)  {x = screenWidth  -yTextSpacing*2;}
		else x = sTextBoundsRect.height() + yTextSpacing;
		float y = yBarLengthPixels / 2 + sTextBoundsRect.width() / 2;
		if (alignBottom) y+= screenHeight -yBarLengthPixels;

**Comment by spyhunter99** [comment]
The bottom scale bar is a tricky one. Have you tried it on a samsung device or a device with and without hardware buttons? It's a fun one. Please open this as a PR and we'll get it merged

**Comment by stellardeveloper** [comment]
I tried it on a Samsung SGS2, emulators and BlueStacks. It is working as expected. Will try it on a HTC Desire, too.

**Comment by spyhunter99** [comment]
There's a related issue for scale bars. Adjustable font size, color, and screen render size. I think right now its rendered as one inch wide, which on a big display, wraps the text, which is ugly. Bottom line, it could use some work

**Comment by spyhunter99** [comment]
please open a pull request and we'll get it merged

**Comment by stellardeveloper** [comment]
I tried to do so 8 days ago, obviously without success. Tried new PR, hope it is working now.

Please respect that the constructors of the ScaleBarOverlay have changed! A MapView as a parameter is neeeded now.

**Comment by spyhunter99** [comment]
see the pr, doesn't build

**Comment by spyhunter99** [comment]
merged
