### ISSUE TITLE
Change tile caching to a database backed mechanism 

### ISSUE THREAD

**Issue by spyhunter99** [osmdroid/osmdroid#213]
Recently, @johnnynotsolucky was nice enough to offer a better solution for managing and maintain the 'tile expired' time stamps, which is used for online map sources. The expired timestamp could be tile source and perhaps even tile specific. Before the PR, osmdroid uses one setting for everything that aligns with the OSM settings. Currently, cached tiles from online sources are stored on the file system using the following pattern /sdcard/osmdroid/tiles/{tilesource}/z/x/y.{png,jpg,etc}

In my experience, operating systems often struggle with large quantities of files within a given folder. Most seem to have serious perofrmance issues around 100k files in a given folder. @johnnynotsolucky's PR may actually make this worse by adding a properties file for each tile.

Considering the need for a storage medium along with additional metadata and performance related issues, I'd like to propose that we switch to a sqlite backed database for the cache. We already consume sqlite for offline tiles and would essentially just be reusing that mechanism and adding inserts from the tile downloader.

I'll open this up for discussion and any hidden issues before doing anything

**Comment by johnnynotsolucky** [comment]
I think this would be the best solution too, and more extensible

**Comment by cfsbhawkins** [comment]
I agree that a sql approach is best, extending the osmdroid format might be best as it contains a provider field, we might just want to add a last modified date.

**Comment by spyhunter99** [comment]
I think the solution would be to alter both TileWriter and the MapTileFilesystemProvider. This should actually be a pretty simple fix

**Comment by neilboyd** [comment]
There already seem to be some SQLite [Mobac formats](http://mobac.sourceforge.net/wiki/index.php/Atlas_formats). Perhaps we can find one that works.

**Comment by MKergall** [comment]
That seems a good idea. Deleting the files cache folder for instance can take a while. 
Both Osmdroid SQLite and MBTiles SQLite are working. 

But carefully check the displaying perfs. Offline maps in ZIP format, for instance, are really slow.

**Comment by spyhunter99** [comment]
pushed to branch 213 for review

**Comment by cfsbhawkins** [comment]
Looks good here, Is there a way to override the default from the static variable if the server did not return it in the header? Another option would be to make the expires scale depending on zoom level, as 1 - 7 zooms rarely change if ever.

**Comment by spyhunter99** [comment]
@cfsbhawkins  good call.

**Comment by spyhunter99** [comment]
@neilboyd are we good to merge this?

**Comment by spyhunter99** [comment]
this still has a few issues with it, namely osmdroid crashing on startup. looking into it now

**Comment by spyhunter99** [comment]
needs checks for sdcard mounted to prevent barfing

**Comment by spyhunter99** [comment]
all those that are interested in this ticket, please check out the branch and run locally. There's a few decision points to be made here.

1) when running the branch version, or when you upgrade your apps with a newer version of osmdroid, what do we want to do with the image files in /sdcard/osmdroid/tiles/
we could import them into the sqlite database, delete them and force another download or do nothing and leave the responsibility up to the app developers to figure out. In either case, a utility method could be written to support the import and delete scenario.

2) I'm not entirely sure where the logic needs to be to force a deletion from the database when we run across an expired tile. Right now, it's deleted from the database right before we insert the updated one after it's downloaded. This seems right, but I'm just a guy with a keyboard. I'd appreciate other opinions. There's also potential concurrency issues when the way the database is structured. Again, looking for opinions.

Lastly, this will probably have to be pushed to the next release as a precaution. It's a big change and I'd like more testing

**Comment by spyhunter99** [comment]
and we have a unit test that fails, i think it's failing because it's looking for a specific file on the sdcard.

**Comment by cfsbhawkins** [comment]
I will give it a good testing on our application and let you know how it goes. As far as old tiles, I would leave it up to the developer to remove them, as well as redownload them instead of importing them. They would expire in within a week or two anyways. 

We could add the following method I use to remove expired tiles so we don't have issues with a CPU spike. Just removing the file age check.

 public static void deleteRecursive(File fileOrDirectory) {
        try {
            if (fileOrDirectory.isDirectory()) {
                for (File child : fileOrDirectory.listFiles()) {
                    deleteRecursive(child);
                }
            }

            long lastModified = fileOrDirectory.lastModified();
            boolean fileExpired = lastModified < System.currentTimeMillis() - (OpenStreetMapTileProviderConstants.ONE_WEEK - OpenStreetMapTileProviderConstants.ONE_DAY);

            if (fileExpired) {
                fileOrDirectory.delete();
            }

        } catch (Exception e) {

            Log.e("MapUtility", "Exception deleting map directory");
        }
    }

**Comment by spyhunter99** [comment]
I'm wondering if it should be an option for applications to specify a) use sqlite based cache or b) use file based cache

**Comment by cfsbhawkins** [comment]
I'm up in the air on this one, to maintain backwards compatibility it would be nice, but the features of having it all in one database might be worth it.

**Comment by spyhunter99** [comment]
Unfortunately, we have a crash condition on API8 devices. Apparently there were some significant delta's with sqlite between 8 and 10. API >= 10 is how it is today, prior to that and the sql syntax is different

**Comment by cfsbhawkins** [comment]
Well I guess we could default file system, and allow devs to enable SQL caching, I know in my case, I set my min API to JB MR2.

**Comment by spyhunter99** [comment]
@cfsbhawkins i think that's a good idea. I put some hooks in this branch to (by default) use sqlite if the API level is >=10 otherwise default to the file system. This can be overwritten at map construction time or on map tile provider construction time with whatever you want.

**Comment by cfsbhawkins** [comment]
@spyhunter99 Looks good here, I will pull in this branch and give it a test and let you know how it goes.

**Comment by spyhunter99** [comment]
Thanks, appreciate the help

**Comment by cfsbhawkins** [comment]
@spyhunter99 Took a look at it in a few different scenarios, one with a set of offline tiles in SQL db's and then in an online mode. All looks good, sorry it took me a few days to get back to you, had to do a little rework in my app since the ResourceProxy was removed.  

One thing I'm thinking of and want your opinion, whats your thoughts on a helper that could be called to import the current tiles cached on disk to the database? I could see it being helpful for a transition to the new db method, as well as a cleanup utility. 

I tested this on a Samsung Tab S running 5.0.2. When I get into work in the AM I will test on some newer devices, as well as an older KitKat device.

**Comment by spyhunter99** [comment]
> helper that could be called to import the current tiles cached on disk to the database

There was some discussion of this at one point. The conclusion was that since it's an expiring caching, the recommendation was to just to delete the load tile cache and download the tiles again and that it should be apps using osmdroid's responsibility to do so. Speaking of which, we really need a wiki page on this topic

**Comment by cfsbhawkins** [comment]
@spyhunter99 Only issue we have seen here in testing is this error and a close and reopen of the application fixed it. Not sure how to reproduce it we just saw it on one device. Im not sure if it was a race condition on an expired tile and it trying to load at the same time. Other than this one it all looks good here.

E/OsmDroid: Error loading tile
                                                                               java.lang.NullPointerException: Attempt to invoke virtual method 'android.database.Cursor android.database.sqlite.SQLiteDatabase.query(java.lang.String, java.lang.String[], java.lang.String, java.lang.String[], java.lang.String, java.lang.String, java.lang.String)' on a null object reference
                                                                                   at org.osmdroid.tileprovider.modules.MapTileSqlCacheProvider$TileLoader.loadTile(MapTileSqlCacheProvider.java:200)
                                                                                   at org.osmdroid.tileprovider.modules.MapTileModuleProviderBase$TileLoader.run(MapTileModuleProviderBase.java:291)
                                                                                   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                                   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                                   at java.lang.Thread.run(Thread.java:81

**Comment by cfsbhawkins** [comment]
@spyhunter99 Got some more info on that above crash, I am able to reproduce it by relaunching an activity, it appears its not closing the database on close, and on resume of activity it can't lock the database for write. Do we have a command on destroy that we should call? To make sure that database is released.

Let me know if you want me to test anything out.

Unable to store cached tile from (OurTileServer) /14/6402/3151, database not available.

**Comment by spyhunter99** [comment]
I'll look into it

**Comment by spyhunter99** [comment]
I think i have a solution, really need to wait for #335 to be merged since it touches a lot of the same files. Basically, I added a "close" method on the IFileSystemCache interface and then it's invoked on MapTileProviderBasic.onDetach.

**Comment by spyhunter99** [comment]
update, #335 is merged to master, master merged into this branch and we're passing on travis. @cfsbhawkins would you mind running through your tests again? When you said, close and reopen the app, what did you mean exactly?

hardware/software home button, then relaunch the app from the launcher?
hardware/software home button, then relaunch the app from the recent apps list?
app was interrupted by another intent, then return?
is the map by chance in an activity for result and the error is after the result?

**Comment by cfsbhawkins** [comment]
@spyhunter99 Sure I will test this evening what I meant to say was we were relaunching the activity, we have a change location button that changes the dataset that is shown from our API's so to make sure everything is cleared out we just close and relaunch the activity with the map fragment on it. I will also check to make sure someone isn't referencing the map in a static context so we are not leaking there.

**Comment by spyhunter99** [comment]
@cfsbhawkins awesome, thanks!, just merged in the changes. i'll start lobbying for a version cut
