### ISSUE TITLE
ItemizedOverlayWithFocus is not scaled for screen resolution

### ISSUE THREAD

**Issue by neilboyd** [osmdroid/osmdroid#214]
As noted in PR #209 the description of the itemized overlay is very small on a large screen.

This is presumably due to all the hard-coded calculations in [`ItemizedOverlayWithFocus`](https://github.com/osmdroid/osmdroid/blob/master/osmdroid-android/src/main/java/org/osmdroid/views/overlay/ItemizedOverlayWithFocus.java).  These calculations should account for screen resolution, or use a layout file.

![itemized overlay with small description](https://cloud.githubusercontent.com/assets/143709/11685350/a4e84c64-9e78-11e5-9715-a8504363f566.png)

**Comment by spyhunter99** [comment]
@neilboyd i pushed a change set that fixes this. Although it's fixed, i'm not exactly sure what "right" looks like here. This also required an API change for ItemizedOverlayWithFocus and everything else that uses it. I've made the font sizes and whatnot adjustable by classes that extend this but this could potential be simplified or done in a better way. I'll defer to you on that one

**Comment by neilboyd** [comment]
It would be better to add the two properties that are needed as properties on ResourceProxy instead of passing Context through a load of methods.  ResourceProxy already has one property getDisplayMetricsDensity().

**Comment by spyhunter99** [comment]
i added a new method to the default resource proxy and the interface. it'll be a potentially breaking change, but the impact should be minimal

**Comment by neilboyd** [comment]
You added getDisplayMetrics() so you could remove getDisplayMetricsDensity().

**Comment by spyhunter99** [comment]
I thought about it, but maybe we could leave it and flag as deprecated. No
idea who else may be relying on it

**Comment by neilboyd** [comment]
Deprecated is good.

**Comment by spyhunter99** [comment]
@neilboyd is this good to merge then?

**Comment by neilboyd** [comment]
I guess so
