### ISSUE TITLE
Stale Branches Cleanup

### ISSUE THREAD

**Issue by ZKjellberg** [osmdroid/osmdroid#216]
There are currently [17 stale branches](https://github.com/osmdroid/osmdroid/branches/stale) which are incredible old. Would it be possible to cleanup and purge some of these branches?

When the project is downloaded, it is quite noisy when navigating for active branches due to these.

**Comment by spyhunter99** [comment]
i removed everything that looked safe to delete, other branches i'm hesitant to touch

**Comment by neilboyd** [comment]
I deleted all the ones with my name on them

**Comment by kurtzmarc** [comment]
I removed two of my old branches. I also looked at rotation (implemented later) and osm-contributor (a branch close to the root of the repo and no longer relevant) and can say that they are outdated so I deleted them as well. I think this ticket can be closed!

**Comment by spyhunter99** [comment]
i think that just about does it. thank you, next window please
