### ISSUE TITLE
Doesn't work on API 8 device

### ISSUE THREAD

**Issue by neilboyd** [osmdroid/osmdroid#218]
minSdkVersion is 8 but the app doesn't run on an API 8 device. I think we should continue to support 8. The alternative is to increase to 10, but that doesn't help much, and the [stats](http://developer.android.com/about/dashboards/index.html) on 11 are a bit vague.

**Comment by neilboyd** [comment]
Below is the error log when running the first sample.  A more extensive test may find other issues.

<pre>12-15 23:51:15.186 I/ActivityManager(   63): Starting activity: Intent { cmp=org.osmdroid/.MapActivity }
12-15 23:51:15.326 I/dalvikvm(  327): Could not find method android.support.v4.app.BaseFragmentActivityDonut.onCreateView, referenced from method android.support.v4.app.BaseFragmentActivityHoneycomb.onCreateView
12-15 23:51:15.326 W/dalvikvm(  327): VFY: unable to resolve virtual method 1452: Landroid/support/v4/app/BaseFragmentActivityDonut;.onCreateView (Landroid/view/View;Ljava/lang/String;Landroid/content/Context;Landroid/util/AttributeSet;)Landroid/view/View;
12-15 23:51:15.326 D/dalvikvm(  327): VFY: replacing opcode 0x6f at 0x000c
12-15 23:51:15.326 D/dalvikvm(  327): VFY: dead code 0x000f-000f in Landroid/support/v4/app/BaseFragmentActivityHoneycomb;.onCreateView (Landroid/view/View;Ljava/lang/String;Landroid/content/Context;Landroid/util/AttributeSet;)Landroid/view/View;
12-15 23:51:15.745 I/dalvikvm(  327): Could not find method org.osmdroid.views.MapView.setLayerType, referenced from method org.osmdroid.MapFragment.setHardwareAccelerationOff
12-15 23:51:15.745 W/dalvikvm(  327): VFY: unable to resolve virtual method 12435: Lorg/osmdroid/views/MapView;.setLayerType (ILandroid/graphics/Paint;)V
12-15 23:51:15.745 D/dalvikvm(  327): VFY: replacing opcode 0x6e at 0x000a
12-15 23:51:16.225 I/dalvikvm(  327): Failed resolving Lorg/osmdroid/views/MapController$ZoomAnimatorListener; interface 7 'Landroid/animation/Animator$AnimatorListener;'
12-15 23:51:16.236 W/dalvikvm(  327): Link of class 'Lorg/osmdroid/views/MapController$ZoomAnimatorListener;' failed
12-15 23:51:16.246 E/dalvikvm(  327): Could not find class 'org.osmdroid.views.MapController$ZoomAnimatorListener', referenced from method org.osmdroid.views.MapController.<init>
12-15 23:51:16.256 W/dalvikvm(  327): VFY: unable to resolve new-instance 1769 (Lorg/osmdroid/views/MapController$ZoomAnimatorListener;) inLorg/osmdroid/views/MapController;
12-15 23:51:16.256 D/dalvikvm(  327): VFY: replacing opcode 0x22 at 0x002c
12-15 23:51:16.266 D/dalvikvm(  327): VFY: dead code 0x002e-0066 in Lorg/osmdroid/views/MapController;.<init> (Lorg/osmdroid/views/MapView;)V
12-15 23:51:16.366 I/dalvikvm(  327): Could not find method android.animation.Animator.end, referenced from method org.osmdroid.views.MapController.stopAnimation
12-15 23:51:16.376 W/dalvikvm(  327): VFY: unable to resolve virtual method 8: Landroid/animation/Animator;.end ()V
12-15 23:51:16.376 D/dalvikvm(  327): VFY: replacing opcode 0x6e at 0x002e
12-15 23:51:16.436 I/dalvikvm(  327): Could not find method android.animation.ValueAnimator.start, referenced from method org.osmdroid.views.MapController.zoomInFixing
12-15 23:51:16.465 W/dalvikvm(  327): VFY: unable to resolve virtual method 22: Landroid/animation/ValueAnimator;.start ()V
12-15 23:51:16.465 D/dalvikvm(  327): VFY: replacing opcode 0x6e at 0x0055
12-15 23:51:16.515 I/dalvikvm(  327): Could not find method android.animation.ValueAnimator.start, referenced from method org.osmdroid.views.MapController.zoomOutFixing
12-15 23:51:16.515 W/dalvikvm(  327): VFY: unable to resolve virtual method 22: Landroid/animation/ValueAnimator;.start ()V
12-15 23:51:16.515 D/dalvikvm(  327): VFY: replacing opcode 0x6e at 0x0055
12-15 23:51:16.545 I/dalvikvm(  327): Failed resolving Lorg/osmdroid/views/MapController$ZoomAnimatorListener; interface 7 'Landroid/animation/Animator$AnimatorListener;'
12-15 23:51:16.545 W/dalvikvm(  327): Link of class 'Lorg/osmdroid/views/MapController$ZoomAnimatorListener;' failed
12-15 23:51:16.565 E/dalvikvm(  327): Could not find class 'org.osmdroid.views.MapController$ZoomAnimatorListener', referenced from method org.osmdroid.views.MapController.zoomToFixing
12-15 23:51:16.565 W/dalvikvm(  327): VFY: unable to resolve new-instance 1769 (Lorg/osmdroid/views/MapController$ZoomAnimatorListener;) inLorg/osmdroid/views/MapController;
12-15 23:51:16.565 D/dalvikvm(  327): VFY: replacing opcode 0x22 at 0x00bf
12-15 23:51:16.565 D/dalvikvm(  327): VFY: dead code 0x00c1-00e8 in Lorg/osmdroid/views/MapController;.zoomToFixing (III)Z
12-15 23:51:16.666 I/OsmDroid(  327): Using tile source: Mapnik
12-15 23:51:17.856 I/OsmDroid(  327): sdcard state: mounted
12-15 23:51:17.946 I/OsmDroid(  327): sdcard state: mounted
12-15 23:51:17.986 I/OsmDroid(  327): sdcard state: mounted
12-15 23:51:25.210 W/ActivityManager(   63): Launch timeout has expired, giving up wake lock!
12-15 23:51:25.283 W/ActivityManager(   63): Activity idle timeout for HistoryRecord{4a39caf0 org.osmdroid/.MapActivity}

**Comment by neilboyd** [comment]
I had this issue on an api 8 emulator. I tried on an api 10 emulator and didn't have the issue although I expected to. Maybe it's just an emulator issue. Needs further investigation.

**Comment by neilboyd** [comment]
I think this is best solved by running CI on an API 8 and 10 emulator. See issue #227. One drawback of that is that [Travis only supports API 10 and up](https://docs.travis-ci.com/user/languages/android).

**Comment by spyhunter99** [comment]
i'm making progress over here, i got the integration test running in gradle and i was able to get an api 10 emulator running locally with passing tests. I cannot make an API8 avd locally though, there's something wrong with it.  Maybe an API9 setup would replicate the issue.

**Comment by spyhunter99** [comment]
I'm having a different issue with api 8 here....
````
ssage: android.support.v4.os.ParcelableCompatCreatorHoneycombMR2
W/ClassPathPackageInfoSource(  408): java.lang.ClassNotFoundException: android.support.v4.os.ParcelableCompatCreatorHoneycombMR2
W/ClassPathPackageInfoSource(  408): 	at java.lang.Class.classForName(Native Method)
W/ClassPathPackageInfoSource(  408): 	at java.lang.Class.forName(Class.java:235)
W/ClassPathPackageInfoSource(  408): 	at android.test.ClassPathPackageInfoSource.createPackageInfo(ClassPathPackageInfoSource.java:89)
W/ClassPathPackageInfoSource(  408): 	at android.test.ClassPathPackageInfoSource.access$000(ClassPathPackageInfoSource.java:40)
W/ClassPathPackageInfoSource(  408): 	at android.test.ClassPathPackageInfoSource$1.load(ClassPathPackageInfoSource.java:51)
W/ClassPathPackageInfoSource(  408): 	at android.test.ClassPathPackageInfoSource$1.load(ClassPathPackageInfoSource.java:50)
W/ClassPathPackageInfoSource(  408): 	at android.test.SimpleCache.get(SimpleCache.java:31)
W/ClassPathPackageInfoSource(  408): 	at android.test.ClassPathPackageInfoSource.getPackageInfo(ClassPathPackageInfoSource.java:73)
W/ClassPathPackageInfoSource(  408): 	at android.test.ClassPathPackageInfo.getSubpackages(ClassPathPackageInfo.java:48)
W/ClassPathPackageInfoSource(  408): 	at android.test.ClassPathPackageInfo.addTopLevelClassesTo(ClassPathPackageInfo.java:61)
W/ClassPathPackageInfoSource(  408): 	at android.test.ClassPathPackageInfo.getTopLevelClassesRecursive(ClassPathPackageInfo.java:55)
W/ClassPathPackageInfoSource(  408): 	at android.test.suitebuilder.TestGrouping.testCaseClassesInPackage(TestGrouping.java:154)
W/ClassPathPackageInfoSource(  408): 	at android.test.suitebuilder.TestGrouping.addPackagesRecursive(TestGrouping.java:115)
W/ClassPathPackageInfoSource(  408): 	at android.test.suitebuilder.TestSuiteBuilder.includePackages(TestSuiteBuilder.java:103)
W/ClassPathPackageInfoSource(  408): 	at android.test.InstrumentationTestRunner.onCreate(InstrumentationTestRunner.java:360)
W/ClassPathPackageInfoSource(  408): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4218)
W/ClassPathPackageInfoSource(  408): 	at android.app.ActivityThread.access$3000(ActivityThread.java:125)
W/ClassPathPackageInfoSource(  408): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2071)
W/ClassPathPackageInfoSource(  408): 	at android.os.Handler.dispatchMessage(Handler.java:99)
W/ClassPathPackageInfoSource(  408): 	at android.os.Looper.loop(Looper.java:123)
W/ClassPathPackageInfoSource(  408): 	at android.app.ActivityThread.main(ActivityThread.java:4627)
W/ClassPathPackageInfoSource(  408): 	at java.lang.reflect.Method.invokeNative(Native Method)
W/ClassPathPackageInfoSource(  408): 	at java.lang.reflect.Method.invoke(Method.java:521)
W/ClassPathPackageInfoSource(  408): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:868)
W/ClassPathPackageInfoSource(  408): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:626)
W/ClassPathPackageInfoSource(  408): 	at dalvik.system.NativeStart.main(Native Method)
W/ClassPathPackageInfoSource(  408): Caused by: java.lang.NoClassDefFoundError: android.support.v4.os.ParcelableCompatCreatorHoneycombMR2
W/ClassPathPackageInfoSource(  408): 	... 26 more
W/ClassPathPackageInfoSource(  408): Caused by: java.lang.ClassNotFoundException: android.support.v4.os.ParcelableCompatCreatorHoneycombMR2 in loader dalvik.system.PathClassLoader[/system/framework/com.google.android.maps.jar:/system/framework/android.test.runner.jar:/data/app/org.osmdroid.test-1.apk:/data/app/org.osmdroid-1.apk]
W/ClassPathPackageInfoSource(  408): 	at dalvik.system.PathClassLoader.findClass(PathClassLoader.java:243)
W/ClassPathPackageInfoSource(  408): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:573)
W/ClassPathPackageInfoSource(  408): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:532)
````

**Comment by spyhunter99** [comment]
got the api8 avd to fire up and confirmed that api 8 doesn't work. the splash activity does fire up, however any of the map activities just shows a black screen. Could this be related to hardware acceleration?

**Comment by spyhunter99** [comment]
Had some time to test, only one thing fails on API 8, the starter map. Here's the results

Activities
OsmDroid Starter Map (black screen, no longer responsive)
OSMapView with Minimap (works)
OSMapView with Itemized Overlay (works)
OSMapView with Minimap and Zoom controls (works)
Sample tiles overlay (works)
Sample tiles overlay with custom source (works)
Sample with custom resources (works)


Extra Samples (fragments)
-Itemized Icon Overlay with focus (works)
-Itemized Icon Overlay at scale (works)
-Limited scroll area (no map tiles render but responsive)
-Mapview in XML layout (works
-OsmPath Drawing (works
-Inverted tiles (works)
-Offline tiles only (works)
-Alt cache dir (works)
-Military Icons (works)
-Mapbox ( needs api key, but works)
-Jumbo Cache (works)
-Custom Tile Source (works)
-Animated Zoom To on location (no gps available, map renders)
-Whacky colored tiles (works)

**Comment by spyhunter99** [comment]
I've narrowed it down to the compass overlay!

**Comment by spyhunter99** [comment]
resolved by disabling the compass overlay on api 8 devices. it's good enough for now, but not a real solution.
