### ISSUE TITLE
Can't resolve "org.osmdroid.views.MapView" after update to osmdroid 5.0.1

### ISSUE THREAD

**Issue by zulluadi** [osmdroid/osmdroid#222]
Hi,

I would really like to upgrade my project with the latest OSM lib but I got stuck at this issue. Previously I was using compile 'org.osmdroid:osmdroid-android:4.3' and it was working just fine but after trying to use the latest version with compile 'org.osmdroid:osmdroid-android:5.0.1@aar' it can't find any classes from osmdroid lib. 

I tried to create a new project and used the latest version and it seemed to work. After that I was trying to combine gradle and idea files between the projects and see if I can come up with some working workaround but I failed to find a good mix. I also tried to create a new module in my project and check if it works there but it doesn't.

Can you help me out with this one? What can I do to make it work?

**Comment by spyhunter99** [comment]
Try to build from the command line.  Android studio can be weird.  Also I
wouldn't recommend mucking about with iml files.

**Comment by zulluadi** [comment]
This is my projects build.gradle:

// Top-level build file where you can add configuration options common to all sub-projects/modules.
buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.0.0-alpha3'
    }
}

allprojects {
    repositories {
        jcenter()
    }
}


And this is my module build.gradle:

apply plugin: 'com.android.library'

android {
    signingConfigs {
    }
    compileSdkVersion 23
    buildToolsVersion '23.0.2'
    defaultConfig {
        minSdkVersion 14
        targetSdkVersion 23
        compileOptions {
            sourceCompatibility JavaVersion.VERSION_1_7
            targetCompatibility JavaVersion.VERSION_1_7
        }
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.txt'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_7
        targetCompatibility JavaVersion.VERSION_1_7
    }
    lintOptions {
        abortOnError false
    }
    productFlavors {
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    testCompile 'junit:junit:4.12'
    compile project(':mapCoordinates_i18n')
    compile 'com.android.support:design:23.1.1'
//    compile 'org.osmdroid:osmdroid-android:4.3'
//    compile 'org.osmdroid:osmdroid-android:5.0.1'
    compile 'org.osmdroid:osmdroid-android:5.0.1@aar'
}

**Comment by cfsbhawkins** [comment]
Have you done a gradle sync within android studio?

**Comment by zulluadi** [comment]
Yes, after sync I saw that all the imports from osm packages can't be resolved.

**Comment by spyhunter99** [comment]
try deleting your gradle cache directories. ~/.gradle and
yourProject/.gradle and the maven cache at ~/.m2/repository

**Comment by zulluadi** [comment]
Just did but unfortunately it's not working :(

**Comment by zulluadi** [comment]
Hi, I just created a new project, copied my modules inside the new project and then replaced all contents of the old project with the contents from the new one and it seems to be working fine now. 

My guess is that I had some bad configuration files because my project is migrated from Eclipse. 

Thank you very much for your support.
