### ISSUE TITLE
Tiles not loading on android 6(API 23)

### ISSUE THREAD

**Issue by ViHtarb** [osmdroid/osmdroid#223]
I`m using latest library version(5.0.1). On android 6 tiles not loading. On android 4.4.2 tiles loading successfully. What could be the problem and how to fix it?

**Comment by ZKjellberg** [comment]
Android 6.0 requires you to code in permission requests. If you do not request the permission, it will fail.

See the [checkPermissions() method in the sample app](https://github.com/osmdroid/osmdroid/blob/master/OpenStreetMapViewer/src/main/java/org/osmdroid/MainActivity.java)

**Comment by spyhunter99** [comment]
concur on this one, reopen if you still have issues

**Comment by ViHtarb** [comment]
Ty for help. it`s really working.

**Comment by firelight22** [comment]
I copied the same code and I called "checkPermissions" function. Dialogs for asking permissions are not showing. 

I added these two lines on the AndroidManifest.xml and of course I've <uses-permission> tags corresponding

```
<permission android:name="com.squealit.squealit.permission.ACCESS_FINE_LOCATION" />
<permission android:name="com.squealit.squealit.permission.WRITE_EXTERNAL_STORAGE"/>
```

**Comment by spyhunter99** [comment]
Does the example app work?  5.2 was just released too. If the example
works, the problem is your code
