### ISSUE TITLE
Add a Center Map To My Location button.

### ISSUE THREAD

**Issue by 2ndGAB** [osmdroid/osmdroid#226]
Hello,

There is a cool feature in Google Maps which displays a 'Center map to my location' button when we call ``mMap.setMyLocationEnabled(true);``

It's also displayed by default just up the itinerary button in Google Maps.

Could you consider to add it in OSMdroid?

Regards,
Al

**Comment by 2ndGAB** [comment]
Ok, 
So, this I can propose to use such feature: https://github.com/2ndGAB/OSMCenterToMyPosition

**Comment by spyhunter99** [comment]
Are you ok with bringing this example into osmdroid? including the images? it would be subject to the terms of the ASF license

**Comment by spyhunter99** [comment]
pist, i've already done the work, just waiting to click the commit button

**Comment by 2ndGAB** [comment]
Sure you can.

**Comment by spyhunter99** [comment]
thanks!, merged
