### ISSUE TITLE
Determine the correct capitalization of osmdroid

### ISSUE THREAD

**Issue by spyhunter99** [osmdroid/osmdroid#234]
All over the and wiki we have the following variants
* osmdroid
* OSMdroid
* OSMDroid
* OsmDroid
* Osmdroid
* OSMDROID

What does "right" look like?

**Comment by neilboyd** [comment]
I vote for all lowercase

**Comment by kurtzmarc** [comment]
I also think all lowercase.

**Comment by spyhunter99** [comment]
ok sounds good, i'll rip through the wiki and make the updates
