### ISSUE TITLE
google wrapper app crashes when switching between google maps v1 and v2

### ISSUE THREAD

**Issue by spyhunter99** [osmdroid/osmdroid#235]
Goto v1, then v2, then back to v1 (crash)

something about there's only one map view allowed

**Comment by neilboyd** [comment]
Yes. The sample app is a bit too simple.

**Comment by spyhunter99** [comment]
@neilboyd this is fixed, however the tests won't run on API 8 since this is the min for google maps. So it builds, but the tests fail on API8 on travis. Not sure what to do here. We can either bump everything to api 9 or disable the tests entirely for the GoogleWrapperApp

**Comment by neilboyd** [comment]
I would be fine with going to API 10, however there are still quite some users on 8.

![osmdroid-stats-2016-01-27](https://cloud.githubusercontent.com/assets/1768373/12626716/5c17de76-c53a-11e5-9e65-ffec44bd1f29.png)

**Comment by spyhunter99** [comment]
Sounds like the decision is to skip the tests for now. k

**Comment by spyhunter99** [comment]
On a related note, there's a lot of APIs used within osmdroid-android/src/main.../api that are only used in the GoogleWrapper app, do we want to consider moving them into the 3rd party library?

**Comment by neilboyd** [comment]
Skipping GoogleWrapper in API 8 CI sounds like the best solution.

What do you mean about the APIs in osmdroid-android? The idea is that the interface is defined there and it implements it. If the interface was in third-party then it couldn't implement it without a circular reference.

**Comment by spyhunter99** [comment]
we have the IMapView, Marker, Polyline, and several others that aren't used
within osmdroid-android in the package org.osmdroid.api.

I'm close to a solution for CI

**Comment by neilboyd** [comment]
But they are used. MapView implements IMapView etc

**Comment by spyhunter99** [comment]
Yes "IMapView" is used but "IMap" is not

**Comment by spyhunter99** [comment]
merged
