### ISSUE TITLE
performance profiling on the 'doubles' branch

### ISSUE THREAD

**Issue by spyhunter99** [osmdroid/osmdroid#237]
PR https://github.com/osmdroid/osmdroid/pull/48 has been integrated into the branch 'doubles'. This should hopefully provide better accuracy when setting the map extents and when plotting points. Since this is a large change, I'd love for someone to run some kind of performance impact analysis on this to find out if it's worth it or not. 

It may actually be better to do the same type of branch with floats as the accuracy of floats may be good enough

and i don't want to do it ;)

maybe @ZKjellberg will take on the challenge!

**Comment by ZKjellberg** [comment]
What type of performance analysis would you be looking to test? [Android Studio has a lot of nice tools for testing performance](http://developer.android.com/tools/performance/index.html). Would this be mostly a memory related issue? If so, the [Memory Monitor](http://developer.android.com/tools/performance/memory-monitor/index.html) could be an easy way for a quick glimpse of the impact. I would expect a sample such as the Military Icons fragment sample would be a good test?

**Comment by ZKjellberg** [comment]
Here are [some images from the Memory Monitor with a comparison between master & doubles](http://imgur.com/a/DPor4). You can also see CPU & GPU performance with the tool if desired.

**Comment by spyhunter99** [comment]
perfect. so we're looking at at least an extra 10 megs of ram. that's not
too terrible

**Comment by spyhunter99** [comment]
i guess the work from here is whether or not we find a way to reduce the memory foot print. 10MB seems a bit high IMO. A double is 8 bytes, integer is 4 bytes. That means we had at least 10MB's worth of integers previously, which is 2.5 million ints. Again, it seems high

**Comment by kjeremy** [comment]
@spyhunter99  Looking at the screenshot it looks to only be an increase of 3-4MB.
