### ISSUE TITLE
Add Instrumentation tests that hit all fragments/activities of the sample app

### ISSUE THREAD

**Issue by spyhunter99** [osmdroid/osmdroid#238]

**Comment by spyhunter99** [comment]
update on, it builds and runs all the tests fine locally, on hardware and on avds. no idea why it's failing on travis

**Comment by spyhunter99** [comment]
@neilboyd you may want to take a look at this. We're getting an OOM error on a number of AVDs. Apparently one of the fragments in the demo app causes a crash. just pushed a change which should dump the name of the offending fragment. Might want to consider some kind of crash utility to report back to us when the demo app crashes. it could help troubleshoot issues with versions out in the wild

**Comment by neilboyd** [comment]
That implies that someone should monitor the crash reports and investigate OOM's.  That doesn't sound like fun ;)
