### ISSUE TITLE
How to display several MapsForge .map files?

### ISSUE THREAD

**Issue by 2ndGAB** [osmdroid/osmdroid#240]
Hello,

I'd like to display several MapsForge .map files at the same time because France is cutted out in several regions.
I tried the code below. I don't know if it's the good way to it anyway, I have a problem with it.
When I zoom in and out, I briefly see all maps but I finally see only the last overlay because they are rendered with a with background instead of a transparent one.
So how to use several .map files?

And I also see that rendering such offline map seems to be slower than rendering online default one. Strange, why?

So my code is:

    boolean setMapsForgeTileProvider(){

        String path = Environment.getExternalStorageDirectory().getPath()+"/mapsforge/";
        File folder = new File(path);
        File[] listOfFiles = folder.listFiles();

        if (listOfFiles == null)
            return false;

        File mapFile = null;
        for (File file:listOfFiles){
            if (file.isFile() && file.getName().endsWith(".map")){
                mapFile = file;
                MapsForgeTileProvider mfProvider = new MapsForgeTileProvider(new SimpleRegisterReceiver(getActivity()), mapFile);
                final TilesOverlay tilesOverlay = new TilesOverlay(mfProvider, getActivity());
                tilesOverlay.setLoadingBackgroundColor(Color.TRANSPARENT);
                mMapView.getOverlays().add(tilesOverlay);
            }
        }

        if (mapFile == null)
            return false;

        mMapView.setUseDataConnection(false);
        return true;
    }

Before my application calls ``setMapsForgeTileProvider()``, it calls ``setStdTileProvider()`` below:

    void setStdTileProvider(){
        if ((mMapView == null) || !(mMapView.getTileProvider() instanceof MapTileProviderBasic)){
            GenericMapView genericMap = (GenericMapView) rootView.findViewById(R.id.mapview);
            MapTileProviderBasic bitmapProvider = new MapTileProviderBasic(getActivity().getApplicationContext());
            genericMap.setTileProvider(bitmapProvider);
            mMapView = genericMap.getMapView();
            mMapView.setTileSource(TileSourceFactory.MAPQUESTOSM);
        }
    }

Regards,
Alain

**Comment by spyhunter99** [comment]
I'm afraid this is out of scope of osmdroid. You need to ask the mapforge folks. See here: https://github.com/mapsforge/mapsforge

**Comment by 2ndGAB** [comment]
Hi spyhunter99,

Ok, thanks. I see with mapsforge team.

Regards,
Alain

**Comment by spyhunter99** [comment]
reopening this, since i'm a fan of mapsforge (and i already have a significant time investment into osmdroid)

**Comment by spyhunter99** [comment]
#245 work being on on that ticket. closing this one
