### ISSUE TITLE
invalidate in Thread.

### ISSUE THREAD

**Issue by bidasknakayama** [osmdroid/osmdroid#241]
Hi All

To call invalidate() in thread, It does not work with a error..
"android.view.ViewRootImpl$CalledFromWrongThreadException: 
Only the original thread that created a view hierarchy can touch its views."

(Q) 
Is there any way to update added markers from thread ?

Kazu

**Comment by spyhunter99** [comment]
Yes but it has to be on the ui thread

````
activity.runFromUiThread(new Runnable(....));
````

**Comment by spyhunter99** [comment]
reopen if there's still questions, but this is an android question, not really an osmdroid specific thing
