### ISSUE TITLE
About offline maps.

### ISSUE THREAD

**Issue by 2ndGAB** [osmdroid/osmdroid#242]
Hello,

I've experimented using MapsForge .map file with OSMBonusPack/MapsForgeForOSMDroid module which maybe causes a problem when we want to display several .mp files at same time. 
But at least it seems to be usable at any zoom level with files of reasonable size.

And I also had a look at this solution of MOBAC but after 3 hours, I'm still waiting for my atlas created for Corsica at level 16. And I'm afraid about the size obtained for the map file!

So, I'd like some advices to use OSMDroid with offline maps. What's the good solution.
Does it exists reay made map files on Internet for OSMDroid offline use? Except MapForge.

Is it possible to use several map files the time as France is cutted out in several departments (at least for MapForge), but as I see with Sygic for example, it's certainly possible to have all France in one map only.

Regards,
Alain

**Comment by ZKjellberg** [comment]
I recommend viewing the [Wiki for the creation of Offline Map Tiles](https://github.com/osmdroid/osmdroid/wiki/Offline-Map-Tiles)

OpenStreetMaps used to offer a wiki page to download ZIPs of regions, but that is no longer available it seems.

osmdroid includes a tool called OSMMapTilePackager, I suggest reading the [README](https://github.com/osmdroid/osmdroid/blob/master/OSMMapTilePackager/readme.md). It includes sample commands to pull regions such as [France](https://github.com/osmdroid/osmdroid/blob/master/OSMMapTilePackager/readme.md#france)

**Comment by 2ndGAB** [comment]
Hi ZKjellberg,
hmm well, as I said, using MOBAC seems not to be a reliable solution for creating map of more than a city. 
OSMDroid is a really interesting solution to replace googleMap but for offline solution, I think that MapsForge is maybe better.
At least up for now.
But I'm still interesting for other opinions.

Alain

**Comment by spyhunter99** [comment]
Those are really the only options besides geopackage. If you want offline maps, you have to pay for it in terms of storage
