### ISSUE TITLE
5.0.1: onZoom not fired before getting onScroll

### ISSUE THREAD

**Issue by 2ndGAB** [osmdroid/osmdroid#248]
Hello,

After looking for problem updating the map in my application, I discovered that onZoom event is never fired before scrolling the map first.

**EDIT:** only occurs when we use MapsForge adapter.
Do you confirm?

**Comment by spyhunter99** [comment]
The usage of the maps forge adapter most likely isn't related to this issue

**Comment by 2ndGAB** [comment]
Strange.

**Comment by hlaurent** [comment]
I am having the same issue. OnZoom is called when you have the zoom controls and you press a button, otherwize, if you zoom with a double tap or with a 2 finger pinch to zoom, it is not called.

**Comment by spyhunter99** [comment]
Thanks! this info helps a lot with tracking down the root cause

**Comment by spyhunter99** [comment]
what version is this on again? i'm having some issues replicating this. It appears to be working ok on 5.1 and on master. i just added a sample to validate so at least we'll have something in the future

**Comment by spyhunter99** [comment]
merged to master

**Comment by hlaurent** [comment]
The issue was on 5.0.1. I have not tested with 5.1.
Thanks a lot for your help.
