### ISSUE TITLE
Custom Marker Icon

### ISSUE THREAD

**Issue by jpaseneta** [osmdroid/osmdroid#249]
Is there any simpler way besides making a custom resource proxy to just change the default DirectedLocationOverlay icon(ResourceProxy.bitmap.direction_arrow) to , for example, my own car icon drawable?

Thanks.

**Comment by spyhunter99** [comment]
for MyLocationNewOverlay there is. shouldn't be too much work to have it adjustable post constructor. feel tree to open a PR.
