### ISSUE TITLE
Migration of OsmBonusPack classes over to osmdroid

### ISSUE THREAD

**Issue by spyhunter99** [osmdroid/osmdroid#252]
https://github.com/MKergall/osmbonuspack/issues/200#issuecomment-173716616

after talking it over with @MKergall at OBP, sounds like we have concurrence to migrate the mentioned classes over to osmdroid. This will provide reduced complexity in osmdroid and reduce the somewhat cyclic dependency we have. OBP needs osmdroid, osmdroid deprecated PathOverlay saying to use OBP.

Anyhow this will be good for both projects

**Comment by spyhunter99** [comment]
merged

**Comment by MKergall** [comment]
You can remove all res/values directories => strings.xml only contains routing instructions, which are useless in osmdroid.

**Comment by MKergall** [comment]
In osmdroid/api, there are already a Marker and a Polyline class. They do nothing. 
I don't know their purpose. 
It can confuse to users, when using a Marker, to have to choose between "api" and "bonuspack" imports. 
To be checked if they should be kept or not.

**Comment by spyhunter99** [comment]
the Marker class looks like an adapter for google maps via IMap which is "An interface that contains the common features of osmdroid and Google Maps v2."

**Comment by spyhunter99** [comment]
i probably should have waited a bit to merge this. Although the code is there, it's not exactly integrated

**Comment by spyhunter99** [comment]
@MKergall i shuffled a bunch of stuff around with commit https://github.com/osmdroid/osmdroid/commit/181d8551997db8ed74b38de626929ebe4e6e8127

all of the OBP overlay classes were moved into org.osmdroid.views.overlay
cache manager went to org.osmdroid.tileprovider.cachemanager
