### ISSUE TITLE
Changing cache directory

### ISSUE THREAD

**Issue by 2ndGAB** [osmdroid/osmdroid#253]
So, according to https://github.com/osmdroid/osmdroid/issues/96, is it now possible to change the cache directory which is by default in public external dir?
Could be interesting to set it with getExternalFilesDir() to enable to remove it when uninstalling the application.
Regards,

**Comment by spyhunter99** [comment]
When your app starts, just change it as the first thing. it can be set the apps's private folder too or perhaps the cache folder for the app. the default is /getExternalStorage()/osmdroid/

Is there a question or suggestion here

**Comment by 2ndGAB** [comment]
Ok, it's done by ``OpenStreetMapTileProviderConstants.setCachePath(new File("/my/new/path/to/osmdroid/").getAbsolutePath());``

thanks
