### ISSUE TITLE
osmdroid tile server

### ISSUE THREAD

**Issue by spyhunter99** [osmdroid/osmdroid#255]
wouldn't it be nice to have a JDK and ADK based tool that can provide tiles from our sqlite database structure to osmdroid client apps

**Comment by spyhunter99** [comment]
@neilboyd it's ready, do you want this osmdroid proper or a separate repo under osmdroid?

**Comment by neilboyd** [comment]
What is this?  Is it something similar to the tile packager?

**Comment by spyhunter99** [comment]
It's a standalone java app or war file that uses osmdroid style sqlite database and serves them up using the same url format as osm. This basically enables you to have gigantic osmdroid sqlite databases and use osmdroid to access it over the network

**Comment by spyhunter99** [comment]
oh, and i have an ADK version that does the same thing from android, providing your tiles to peers on the network. I know this doesn't have much of use case for normal users, but there is usefulness here for edge cases and disconnected operations, isolated network bubbles and what not

**Comment by spyhunter99** [comment]
needs build integration
