### ISSUE TITLE
release management, include binaries?

### ISSUE THREAD

**Issue by spyhunter99** [osmdroid/osmdroid#256]
@neilboyd can we include the release artifacts and apks with the release zip? it would be nice to have ready to install artifacts there

**Comment by neilboyd** [comment]
The artifacts are in Maven Central which is referenced in the [wiki](https://github.com/osmdroid/osmdroid/wiki/How-to-include-OsmDroid-in-a-non-Gradle,-non-Maven-project).

I don't know where you would put the signed apk.  You can get it from Google Play.

If you're referring to the release zip that GitHub creates, that looks like it's just a snapshot of the repository when the tag was created, so there's no control over what goes in there.

**Comment by spyhunter99** [comment]
Yeah i was thinking about just putting the APKs or Zip distributions of any
JDK based components on the github release page

**Comment by spyhunter99** [comment]
just added to the release profile and a "dist" profiles a maven task which zips everything up. then we can add it to the github release page

**Comment by spyhunter99** [comment]
@neilboyd this ticket is done. the only additional action needed is that post release, we upload the artifacts from /osmdroid-dist/target (a tar.gz and a zip) to github release section.
