### ISSUE TITLE
Common Map API adapter

### ISSUE THREAD

**Issue by spyhunter99** [osmdroid/osmdroid#257]
http://cmapi.org/

would be cool if we had an adapter/implementation of the common map api.

**Comment by 2ndGAB** [comment]
+1

**Comment by spyhunter99** [comment]
turns out this is a big project and will require osmbonus pack for geojson and kml processing. And a javascript to java port (which is mostly done), and some kind of message broker to emulate the OZP stuff

**Comment by spyhunter99** [comment]
not going to finish it unfortunately, maybe another day
