### ISSUE TITLE
Evaluate moving unused 3rd party classes in osmdroid-android into the 3rd party library

### ISSUE THREAD

**Issue by spyhunter99** [osmdroid/osmdroid#259]
as referenced in #252 and in #235, there's a few classes in osmdroid-android that aren't used within osmdroid proper and are only actually used in the 3rd party support library and the Google Wrapper application. Here's the list
 * org.osmdroid.api.IMap
 * org.osmdroid.api.IPosition
 * org.osmdroid.api.Marker
 * org.osmdroid.api.OnCameraChangeListener
 * org.osmdroid.api.Polyline

When I first started using osmdroid, there was a lot of initial confusion, especially with the OnCameraChangeListener. At the time, we thought it was the way to go, however none of these are actually used or implemented by osmdroid and there's next to nothing in terms of documentation and use cases.

Proposal: we move these to the 3rd party support library.
@neilboyd @kurtzmarc thoughts or opinions on this?

**Comment by neilboyd** [comment]
I think I added a load of classes for the v2 wrapper. Maybe some are not used by osmdroid proper but it probably made sense to keep them all together.

**Comment by k3b** [comment]
proposal:

* in modul osmdroid-third-party: new interface `org.osmdroid.api.IMapExt` extends `org.osmdroid.api.IMap` that gets all methods from `IMap` that `map` does not implement (yet).
* move from modul osmdroid-android to module osmdroid-third-party (without changing the packages)
	* org.osmdroid.api.IPosition
	* org.osmdroid.api.Marker
	* org.osmdroid.api.OnCameraChangeListener
	* org.osmdroid.api.Polyline

I cannot do this on my own because i do not have google-maps-dev acount (since i do not use google-maps at all)

**Comment by spyhunter99** [comment]
@neilboyd  what methods would need to be added to IMapExt?

bullet two, moving those classes over to the 3rd party lib and leaving IMap in osmdroid-android actually breaks the IMap interface, since it's references the Marker and Polyline

what's the relationship between IMap and IMapView? right now there's nothing

**Comment by spyhunter99** [comment]
I think you mean move the 3rd party specific APIs from IMap to IMapExt

**Comment by spyhunter99** [comment]
Maybe
IMap
  |-IMapView
  |    |----osmdroid MapView
  |-IMapExt
      |----Google MapView

**Comment by k3b** [comment]
In https://github.com/k3b/osmdroid/tree/master-api I did this


* removed unused import org.osmdroid.api.IMap;
  * osmdroid-android\src\main\java\org\osmdroid\tileprovider\modules\TileWriter.java
* moved from 	osmdroid-android\src\main\java\* to osmdroid-third-party\src\main\java\
  * org\osmdroid\api\IMap.java
  * org\osmdroid\api\IMyLocationOverlay.java
  * org\osmdroid\api\IPosition.java
  * org\osmdroid\api\Marker.java
  * org\osmdroid\api\OnCameraChangeListener.java
  * org\osmdroid\api\Polyline.java
  * org\osmdroid\util\Position.java

Part of the Travis build succeded https://travis-ci.org/k3b/osmdroid/builds/156615962 .
The failed part is timeout when waiting for the automated tests.

It seems to be syntacticaly ok but i have no means to verify if the google-maps stuff still works.

@neilboyd and @spyhunter99  : can you verify if the code still works? should this be merged into master and the related tickets #259 #252 #379  and #235 be closed?

**Comment by spyhunter99** [comment]
so travis periodically and randomly fails. just restart the specific job that failed. usually the failures are:

* timeouts
* CommandShellUnresponsive
* installation failures

all of these are issues with the travis ecosystem and not our problem. Travis fires up AVD's with and without the Google junk installed. The AVD's with Google's stuff should automatically run at least a basic test, which looks to be, start the activity. We should probably add some more tests to make sure the 3 activities fireup
