### ISSUE TITLE
How to use map with offline and How to draw route between two location.(Android app)

### ISSUE THREAD

**Issue by moonandroid** [osmdroid/osmdroid#260]
For Android:
I have some questions regarding to osmdroid.
1)Offline map working in it.
2)We can draw route between two location.
3)Route draw also working with offline mode.
4)We need to refresh currently location manually for any service there.

**Comment by spyhunter99** [comment]
1) read the wiki https://github.com/osmdroid/osmdroid/wiki/Offline-Map-Tiles
2) see the examples for OsmPathOverlay or bring in osmbonus pack into your project and use polyline. Just add the points and it draws it
3) no network is required for drawing points or lines
4) what? there's a number of osmdroid overlays for displaying my location. see the sample app

**Comment by moonandroid** [comment]
Hello,
I want offline functionality with route draw there will be any sample code ?

**Comment by spyhunter99** [comment]
Network is not required to draw a line on the map. What do you mean by "route"? you want turn by turn directions?

**Comment by moonandroid** [comment]
I want to draw line from source to destination.

**Comment by spyhunter99** [comment]
So, yeah. Using release versions of everything, bring in osmdroid and osmdroid-bonuspack, then use something like this
````

		//mOsmPathOverlay = new OsmPathOverlay(context);
		//mMapView.getOverlayManager().add(mOsmPathOverlay);
		Polyline line = new Polyline(context);
		line.setTitle("Central Park, NYC");
		line.setSubDescription(Polyline.class.getCanonicalName());
		line.setWidth(20f);
		List<GeoPoint> pts = new ArrayList<>();
		//here, we create a polygon, note that you need 5 points in order to make a closed polygon (rectangle)

		pts.add(new GeoPoint(40.796788, -73.949232));
		pts.add(new GeoPoint(40.796788, -73.981762));
		pts.add(new GeoPoint(40.768094, -73.981762));
		pts.add(new GeoPoint(40.768094, -73.949232));
		pts.add(new GeoPoint(40.796788, -73.949232));
		line.setPoints(pts);
		line.setGeodesic(true);
		line.setInfoWindow(new BasicInfoWindow(R.layout.bonuspack_bubble, mMapView));
		//Note, the info window will not show if you set the onclick listener
		//line can also attach click listeners to the line
		/*
		line.setOnClickListener(new Polyline.OnClickListener() {
			@Override
			public boolean onClick(Polyline polyline, MapView mapView, GeoPoint eventPos) {
				Toast.makeText(context, "Hello world!", Toast.LENGTH_LONG).show();
				return false;
			}
		});*/
		mMapView.getOverlayManager().add(line);
````

**Comment by spyhunter99** [comment]
@moonandroid ping. problem solved?

**Comment by moonandroid** [comment]
Yes
Thanks man.

I need one more help
We can change current location Ping image ?
Now displaying green image with arrow i can use my custom?

**Comment by spyhunter99** [comment]
Extend the DefaultResourceProxy

**Comment by moonandroid** [comment]
I have used above class but still default green icon displaying.

Any solution for this.
I want to replace green icon with my own icon,it's possible.

**Comment by spyhunter99** [comment]
You have to extend the Default Resource Proxy and override the methods to
fetch the default marker.

then when creating your overlays, supply your instance of the resource
proxy.

**Comment by spyhunter99** [comment]
Also, see the sample app with "military icons"

**Comment by moonandroid** [comment]
There will be any sound option which play during direction ?

**Comment by spyhunter99** [comment]
osmdroid only displays the map.

**Comment by mwshubham** [comment]
https://github.com/osmdroid/osmdroid/issues/260#issuecomment-179551654
thanks for the example. I am able to draw the polyline between source and destination. However, I have two question. Hope you will love to answer that.
1. What is the use of osmdroid-bonuspack since I am able to draw a turn-by-turn route with using only osmdroid sdk?
2. For plotting the turn-by-turn route i require lat long for each turn in order to display the route. For this i am using google's direction api which is a paid service. Is there anyway we can do this without using any paid services?

**Comment by MKergall** [comment]
2. Yes you can ! Use one of the free routing services made available with OSMBonusPack. 

1. And doing 2, you will immediately understand (one of) the purpose of OSMBonusPack.
