### ISSUE TITLE
Offline maps are not working.

### ISSUE THREAD

**Issue by clem44** [osmdroid/osmdroid#261]
My phone specs:
HTC desire 816,  API 21 (LOLLIPOP).

Hi, 
I'm quite new to osmdroid and I know this issue has been brought up many times, but I have searched through all the forums covering this topic but nothing is working for me. I followed your offline tutorial -https://github.com/osmdroid/osmdroid/wiki/Offline-Map-Tiles .... and I've followed Johns tutorial http://www.haakseth.com/?p=30  on creating offline map zips via MOBAC and uploading to sdcard/osmdroid ...but all is failing.

I've checked and ensured the appropriate Manifest permissions are set. And they are because running osmdroid with network enable (or map.setUseDataConnection(true);) seems to work fine. All the external caching is done when network is enabled. Its just zip files are not being unzipped. I'm receiving no debugs errors either.

I've tried the example app posted on John's toturial - http://www.haakseth.com/?p=64  (Download EnschedeLocator Beta [.apk])  But his app is also failing to render the mapview. All I'm seeing is gridlines.  So maybe the issue is related to Android Lollipop and the MapTileFileArchiveProvider.class?

**Comment by spyhunter99** [comment]
1) What version of osmdroid are you using?
2) consider using sqlite, it doesn't have size limitations. Zip files are around 65k tiles
3) it works just fine but here's a few things to check

- look at the contents of your zip file, the root direction is probably something other than "Mapnik". That directory name is important and it maps to osmdroid's tile source name. If the two don't match, it won't load.
- turn on tile debugging, it may reveal the root cause
````OpenStreetMapTileProviderConstants.DEBUG_TILE_PROVIDERS = true;
OpenStreetMapTileProviderConstants.DEBUGMODE = true;````
- your device may have strange file patch mappings. try running this.
`Log.i(TAG, OpenStreetMapTileProviderConstants.getBasePath().getAbsolutePath());` That's where osmdroid will look for the the archives. It can be overridden as needed.

if you need more control over where the archives are loaded from, there's a few helper classes to do explicit loading via the MapTileProvider classes. This post http://stackoverflow.com/a/19982451/1203182 also has a neat example for searching for file mounts

**Comment by clem44** [comment]
1)I'm using  compile 'org.osmdroid:osmdroid-android:5.0.1@aar 
2)my zip size is very small Just under 1mb.
3)I thought setting my maprovider tilesource  would override the default 'Mapnik'. My zip hierarchy has a different name.

I will try out your suggestions and see what happens. Thanks

**Comment by spyhunter99** [comment]
Whatever's in the zip hierarchy is what you need to tell osmdroid that the
tile source is. If the directory name is "xyz" then you need something like

OnlineTileSourceBase source = new XYTileSource("xyz",
      0, 18, 256, ".png",
      new String[0] );

**Comment by clem44** [comment]
I've tried using both the osmdroid sqlite and zip formats from MOBAC. I've set the source to Mapnik from within my code. I've renamed the folder in the zip to Mapnik..etc  but I'm still getting an empty grid. 

> OpenStreetMapTileProviderConstants.DEBUG_TILE_PROVIDERS

   is a final variable so I can't change its variable to true. But from the Logs of the DEBUGMODE its saying that the tiles don't exist when actually they do. Is there something wrong with my zip structure?

[tiles.zip](https://github.com/osmdroid/osmdroid/files/116825/tiles.zip)

heres a snippet of the map code

` 
   
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_super_map);
        Nammu.init(getApplicationContext());

        menuLayout = findViewById(R.id.menu_layout);
        mLayout = findViewById(R.id.map_content);

        checkPermission();

        RelativeLayout rl = (RelativeLayout) findViewById(R.id.mapview);

        map = new MapView(this, new ResourceProxyImpl(this), new              MapTileProviderBasic(this,TileSourceFactory.PUBLIC_TRANSPORT));
     
        IMapController mapController = map.getController();
        mapController.setZoom(13);
        GeoPoint startPoint = new GeoPoint(18.2170400, -63.0578300);
        mapController.setCenter(startPoint);
        this.mLocationOverlay = new MyLocationNewOverlay(this, new GpsMyLocationProvider(this), map);

        map.getOverlays().add(this.mLocationOverlay);
        map.setBuiltInZoomControls(false);
        map.setMultiTouchControls(true);
        map.setUseDataConnection(false);

        rl.addView(map, RelativeLayout.LayoutParams.MATCH_PARENT, RelativeLayout.LayoutParams.MATCH_PARENT);
`

**Comment by spyhunter99** [comment]
try version 5.1, OpenStreetMapTileProviderConstants.DEBUG_TILE_PROVIDERS
should be writable.

are you sure you have tiles for the zoom and location that you are setting
the map to?

**Comment by clem44** [comment]
Pretty sure I do.

**Comment by clem44** [comment]
Finally got it to work after upgrading to version 5.1 and cleaning the project.
