### ISSUE TITLE
getBoundingBox returns same value everytime : I want current coordinates

### ISSUE THREAD

**Issue by buGGed1** [osmdroid/osmdroid#262]
I want to get the bounding box of the currently displayed area on the smarthphone but whenever I call the .getBoundingBox method, it returns these values :﹕ N:85051128; E:-180000000; S:85051128; W:-180000000

Because of this issue, I can't even cache the currently displayed area. I dont think this is how it is supposed to work, so how to get the correct coordinates ?

**Comment by spyhunter99** [comment]
at what zoom level?

**Comment by buGGed1** [comment]
I think I fixed it by adding a button and putting the method inside the listener.

I've got another problem now. I've tried all the solutions on stackoverflow, but I simply can't load the cached tiles downloaded using CacheManager.

Have you got a working solution /

**Comment by spyhunter99** [comment]
The cache manager was written by @MKergall as part of osmbonus pack. Perhaps he can chime in. I'm guessing he's going to ask for a code snippet of what you have and what version you're running and any other information that required to replicate the problem.

**Comment by buGGed1** [comment]
I got it working by using a different map source.

Thanks anyway!
