### ISSUE TITLE
5.1: problem with animateTo()

### ISSUE THREAD

**Issue by 2ndGAB** [osmdroid/osmdroid#264]
Hello,

I have a problem, I think already had in 5.0.1 with ``animateTo()`` that I have to often call twice to reach to the given location.

My code is:

    btCenterMap.setOnClickListener(new View.OnClickListener() {
        @Override
        public void onClick(View v) {
            GeoPoint myLocation= new GeoPoint(site.getLatitude(), site.getLongitude());
            mMapView.getController().setCenter(myLocation);
            //mMapView.getController().animateTo(myLocation);
            mMapView.getController().setZoom(Constants.OSM_DEFAULT_ZOOM);
        }
    });

so if I call ``setCenter()``, it works fine but if I call ``animateTo()`` after zooming in/out and scrolling the map, I often don't reach to requested location the first time I click my button.

**Note:** The problem is the same with ``zoomToBoundingBox(..., true)``

**Comment by 2ndGAB** [comment]
I'm not absolutely sure that the problem is the same.
Here the problem occurs even after displaying the map for a while, whereas the problem about `zoomToBoundingBox()` seems coming from the fact that the map is not ready again to take it in account.
I think a onMapReady() event is missing or maybe `addOnFirstLayoutListener()` as you told me to look at, is supposed to do that?

**Comment by spyhunter99** [comment]
I just added a quick sample that uses a timer task and some random numbers of "animateTo" a location on the map. I haven't seen an inaccuracies or problems animating to a specific location. Please check out the branch bug/#264 and see if you can replicate. Maybe i'm not understanding or it's a device and/or android version specific problem

**Comment by 2ndGAB** [comment]
Ok, spyhunter, I have something important to do right now but I do my best to check it before this end of week.

**Comment by 2ndGAB** [comment]
I confirm animate cause the map to be centered on a different location than the given one on my Nexus 7 - 6.01

**Comment by spyhunter99** [comment]
Is this with the example application and the "Animate to" sample? I just fired up an emulate for api 23 and didn't see any issue. The sample adds lat/lon gridlines to give you a visual reference to where the center point is supposed to be

**Comment by 2ndGAB** [comment]
I tried Open Map, I suppose it's the app you are talking about, and it seems working correctly.

**Comment by spyhunter99** [comment]
If it's working there, then the problem is most likely in your code. Can
you provide an example to recreate the issue?

**Comment by 2ndGAB** [comment]
Hello spyhunter99,
I don't have any problem anymore with this feature. I don't really know what the problem was sorry.
