### ISSUE TITLE
It would be nice to get the cache folder path.

### ISSUE THREAD

**Issue by 2ndGAB** [osmdroid/osmdroid#265]
Hi,

We have a ``OpenStreetMapTileProviderConstants.setCachePath()`` method but not  ``OpenStreetMapTileProviderConstants.getCachePath()`` and obviously ``OpenStreetMapTileProviderConstants.getBasePath()`` doesn't return the cache path.

just try:

    File folderCache = new File(activity.getExternalFilesDir(null) + "/osmdroid");

    if (!folderCache.exists()) {
        folderCache.mkdir();
    }

    OpenStreetMapTileProviderConstants.setCachePath(folderCache.getAbsolutePath());
        
    File folderCache = OpenStreetMapTileProviderConstants.getBasePath();

**Comment by spyhunter99** [comment]
OpenStreetMapTileProviderConstants .TILE_PATH_BASE is what you want

**Comment by 2ndGAB** [comment]
ok, thanks
