### ISSUE TITLE
Rotate OverlayItem using ItemizedIconOverlay

### ISSUE THREAD

**Issue by rbrueckner11** [osmdroid/osmdroid#266]
I have an ItemizedIconOverlay which includes MyOverlayItems which are extending OverlayItems.  Now, I want to rotate the MyOverlayItems based on the bearing of a Android Location object which I am receiving from a LocationListener and which are individually bound to a MyOverlayItem as a class variable. The reason for this request is I need to show the path and direction of a tracked path. The icon used for MyOverlayItems is a triangle. The chain of triangles on the map indicate the direction of the path. 
I was trying to create a subclass of the ItemizedIconOverlay but struggling to create an overridden onDrawItem() method.
What is the solution for my issue?

Many thanks.

**Comment by MKergall** [comment]
A simple solution is to use OSMBonusPack Marker, which supports bearing (Marker.setRotation).

**Comment by spyhunter99** [comment]
I think the current behavior is that ItemizedIconoverlays based things always remain at the same rotation, regardless of map rotation. I think @MKergall is right. The only way to rotate individual items at a set rotation is with the Marker class
