### ISSUE TITLE
where can I download a latest jar? no gradle

### ISSUE THREAD

**Issue by djdance** [osmdroid/osmdroid#267]
in android studio without gradle I can not add aar.
Can you make a old good jar?
thanks

**Comment by spyhunter99** [comment]
Follow the wiki. Android Studio doesn't work without gradle.

**Comment by spyhunter99** [comment]
You can also download the file direct from maven central. Then you'll need
to convince gradle to import an aar from the file system, which
unfortunately isn't an simple as just dropping it into the "libs" folder.

**Comment by djdance** [comment]
> Android Studio doesn't work without gradle.
it works.. but they removed import of online repos (maven etc)

> You can also download the file 
there is no jar file, only old one.
aar is not a case, need gradle to...

**Comment by spyhunter99** [comment]
hmm incorrect. gradle can use maven central with no issues. Just add mavenCentral() to the repositories list

i'm not sure where the confusion is, but it's not really an osmdroid issue. 

the AAR is the distribution now. AAR's import using gradle or maven just fine. It's probably a configuration issue on your end.

**Comment by djdance** [comment]
> hmm incorrect. gradle can...

no gradle. No any gradle. Old project. So no add library from maven as before. This button in AS diappeared.

> i'm not sure where the confusion is, but it's not really an osmdroid issue.

Yes. I ask for jar only. Soory, can't understand why there is no jar. Previous versions was with jar, now - not. Why?

**Comment by spyhunter99** [comment]
Probably easier to update the project. Current version is AAR to include
the default resource images. You could pull down the sources for the
release version and change the target type to jar. It shouldn't be too
difficult. Or use osmdroid 4.3. The delta isn't that big between 4.3 and 5.x

**Comment by djdance** [comment]
oookay, clear.
