### ISSUE TITLE
kill the resource proxy

### ISSUE THREAD

**Issue by spyhunter99** [osmdroid/osmdroid#268]
when using tools like osmbonuspack, the creation of markers and various overlays references MapView.resourceProxy. If you're defining the mapview in a layout file, there's no clear way to set the resource proxy class, thus you can run into issues with resources not found. adding a quick method to change it shortly after construction time well help resolve this

**Comment by MKergall** [comment]
No way to get rid of this ResourceProxy? 
Is it still required, now that osmdroid is an aar, including regular Android resources?

**Comment by neilboyd** [comment]
@MKergall No it shouldn't be necessary any more. This was mentioned in #146 but not implemented.

**Comment by spyhunter99** [comment]
oh boy... i smell osmdroid 6.0 is around the corner...

**Comment by spyhunter99** [comment]
So question a few questions on the removal of the resource proxy. Let's take the MyLocation Overlay. It fires up and looks for org.osmdroid.R.person.png and uses that for visualization.

If someone wants to override that, do we then change the constructor or whatever to pass in the resource id or a drawable of what they want icon to be?

**Comment by MKergall** [comment]
Don't change the constructor, but add a setter: MyLocation.setIcon(Drawable). 
Allowing to change icon at runtime. And homogeneous with Marker. 

BTW: MyLocationNewOverlay.setPersonIcon(Bitmap icon) already exists. 

Same approach can be applied to DirectedLocationOverlay icon.

**Comment by spyhunter99** [comment]
Quick update on this, I started a branch for this and although it looks
feasible, although it's a lot of work. Pretty much every constructor and
every file needs to be touched. There's tons of stuff related to options
menus that pulls out various strings and drawables....

My open concern is how would libraries that use osmdroid override some of
the functionality, string values, images, etc

**Comment by spyhunter99** [comment]
ready to merge, pending review

**Comment by spyhunter99** [comment]
merged
