### ISSUE TITLE
OSMDroid pinch to zoom sensitivity issue

### ISSUE THREAD

**Issue by hak24** [osmdroid/osmdroid#269]
Zooming in out using pinch gesture is too sensitive that upon zooming in it changes the center. i.e the map flings to different location. How to adjust the touch sensitivity?

**Comment by spyhunter99** [comment]
What version are you using? there were some recent changed that improved this a bit.

**Comment by hak24** [comment]
I'm using 5.1. Resolved this issue to some extent by setting `setFlingEnabled(false)` for a sec on `MotionEvent.ACTION_POINTER_2_UP`.  But still waiting for a proper solution

**Comment by spyhunter99** [comment]
I've definitely noticed this issue, but only on the zoom out gesture. Not sure how to fix it though. Sometime in october I added some code to make the rotation action a bit smoother. We may be able to alter that bit to trap the fling

**Comment by chrisail** [comment]
Hello,
I encountered the same problem with 5.0.1 version. 
After having set some logs to understand how it was working and assuming, I always have setFlingEnabled(true), then, in "MapView" class, when "setZoomLevel" occurs, just after lines :  
"if (isLayoutOccurred()) { ... mTileProvider.rescaleCache(pj, newZoomLevel, curZoomLevel, getScreenRect(null)); }", I set "enableFling" to false to avoid unexpected fling when zooming/scrolling.
In "onFling" method, when the fling occurs, I reactivate "enableFling" by setting it to true.
It works fine for me.
The next step is just to use another boolean that define if the fling is paused or not, independently of setFlingEnabled(...).

Hoping it's the good way to do it.

**Comment by spyhunter99** [comment]
great work, open a pull request when it's done

**Comment by sereja93** [comment]
this problem is solved ?

**Comment by chrisail** [comment]
I'm was recently busy. I find a solution for version 5.01. I have to test my changes on the lastest Osmdroid. I'll do it on monday.
