### ISSUE TITLE
Callback for CacheManager

### ISSUE THREAD

**Issue by JensJensen** [osmdroid/osmdroid#270]
It would be great if there was a listener which I can use with `CacheManager`, to get a callback after `downloadAreaAsync()` finished and the `ProgressDialog` disappears.

**Comment by spyhunter99** [comment]
looks like an easy one. it would also be great if we had a sample for actually using it.

**Comment by spyhunter99** [comment]
how's that for service? booya!

@MKergall cc'ing you since you wrote the original cache manager and as an fyi

**Comment by spyhunter99** [comment]
merged
