### ISSUE TITLE
Are the nightlies or snapshots?

### ISSUE THREAD

**Issue by InI4** [osmdroid/osmdroid#274]
I am using Osmdroid in a app which is currently under test. I wouldn't mind using the latest changes of Osmdroid, even if their are not yet fully tested. Can I skip builing Osmdroid myself, is there a gradle target to use some latest development version as a snapshot or nightly in my app?

**Comment by neilboyd** [comment]
I put snapshots on maven central occasionally, but there's no automated procedure or nightlies.

**Comment by spyhunter99** [comment]
there's a few options. build osmdroid, then manually copy the aar library into your project. assuming gradle, you'll need some additional gradle mojo to actually include an aar from the file system (ugh!) http://stackoverflow.com/questions/24506648/adding-local-aar-files-to-gradle-build-using-flatdirs-is-not-working

or just use maven

'mvn install'

then import as normal with gradle or maven with the snapshot version.


we can look into using travis ci to auto deploy the snapshot version somewhere but until that happens, you're stuck

**Comment by neilboyd** [comment]
I don't know how you could do ci without putting the credentials on the public repository

**Comment by spyhunter99** [comment]
@neilboyd travis has some kind of encrypted token thing

**Comment by spyhunter99** [comment]
we can post nightlys as requested, but it's a manual process. nothing that's automated
