### ISSUE TITLE
Android 6 storage-permission

### ISSUE THREAD

**Issue by tetzschner** [osmdroid/osmdroid#275]
Would be nice to have a setCachePath method, so we can control what storage-path is used.

Reason:

On Nexus 7 (Android 6) the requestPermissions on Manifest.permission.WRITE_EXTERNAL_STORAGE are never asking the user to allow this. It is not even under settings->apps->my-app->permission. Other requestPermission works fine, but not WRITE_EXTERNAL_STORAGE.

Regards, Ole

**Comment by spyhunter99** [comment]
do you mean for the sample app or for the osmdroid library? in either case you want
org.osmdroid.tileprovider.constants.OpenStreetMapTileProviderConstants.TILE_PATH_BASE

it's writable

**Comment by tetzschner** [comment]
Thanks spyhunter99, i'll give it a shot.

Regards, Ole
Den 27/02/2016 00.59 skrev "spyhunter99" <notifications@github.com>:

**Comment by tetzschner** [comment]
@spyhunter99 solved the problem :)

Actually there is a setCachePath, and the code-snippet below solved the permission-hell in Android 6.

```
String cachePath = getCacheDir().getAbsolutePath();
org.osmdroid.tileprovider.constants.OpenStreetMapTileProviderConstants.setCachePath(cachePath);

```
Regards, Ole
