### ISSUE TITLE
Tiles not loading after fragment restart

### ISSUE THREAD

**Issue by zulluadi** [osmdroid/osmdroid#277]
Hi, I have a MapView nested in a fragment. Right after the MapView is created, everything works just fine. The problem is that if I navigate away from my app -> fragment is stopped and then come back to my app -> fragment is started, the tiles that were previously visible, disappear and they are no longer loaded. Using debug mode I get this: "MapTileProviderArray.getMapTile() requested but not in cache, trying from async providers: " a few times and that's it. 

Can I do anything to reuse the MapView or I need to recreate it each time the fragment restarts?

**Comment by spyhunter99** [comment]
you can try setting retainInstance(true) on the fragment. 

what version of osmdroid is this?

**Comment by zulluadi** [comment]
I tried with setRetainInstance(true) but I get the same result.

I'm using compile 'org.osmdroid:osmdroid-android:5.1@aar' in my gradle file.

**Comment by spyhunter99** [comment]
what version of android and type of device?

**Comment by spyhunter99** [comment]
Looks like the mapview overrides onDeattachedFromWindow, where it detaches the tile provider.... but does not override onAttachedToWindow....this could be the problem. it's surprising that this hasn't been noticed or reported before hand. Does the demo app exhibit this behavior too?

**Comment by spyhunter99** [comment]
Are you by chance removing the fragment with the map view on pause, then re-adding the same instance later? is the mapview instance static?

**Comment by zulluadi** [comment]
Android 5.1.1 on Xperia Z1 Compact. It seems that on emulator with Android 6 is working fine.

I am removing the fragment when user wishes because I have multiple fragments which are replaced by each other. The mapView doesn't have a static instance but the fragment has because I didn't want to recreate the fragment on each replace.

**Comment by spyhunter99** [comment]
Ahh that's the problem. Static references to anything with context or views
is usually a bad idea.

**Comment by zulluadi** [comment]
I know it's not a good idea to use static references. I was somehow constrained to do it so. I'll try to find another way as soon as possible.

**Comment by spyhunter99** [comment]
after some experimentation in #335 that's definitely the problem. You can't have a static reference to a view. Are you adding the map view programmatically? that's a common cause of memory leaks since android won't call onDetach for you. There may also be a problem with trying to reuse fragments that were attached, then detached, then reattached. I don't believe that scenario currently works since detach destroys all the background tile loading threads

**Comment by zulluadi** [comment]
The fragment and the map view are used programmatically (MapView is returned in onCreateView). Attach - detach - reattach was the case for my problems. 

In the end, I removed the static reference to the fragment and used the fragment tag instead. This fixed my issue and everything is working fine right now.

**Comment by spyhunter99** [comment]
great

**Comment by EdgarK** [comment]
In my case a fragment was detached and reattached again without any static reference (by tag from fragment manager). And that same problem occurred.

In such a case this code made map working again:

`MapTileProviderBasic tileProvider = new MapTileProviderBasic(getContext().getApplicationContext(), TileSourceFactory.MAPNIK);`
`SimpleInvalidationHandler mTileRequestCompleteHandler = new SimpleInvalidationHandler(getBinding().getMap());`
`tileProvider.setTileRequestCompleteHandler(mTileRequestCompleteHandler);`
`map.setTileProvider(tileProvider);`

Just in case anyone is searching for this :)
