### ISSUE TITLE
what would cause animateTo() fail?

### ISSUE THREAD

**Issue by snowle0pard** [osmdroid/osmdroid#278]
I'm new  in osm. sometime,it fail when i set animateTo a special point.

**Comment by spyhunter99** [comment]
try putting the call for animateTo into on resume or afterwards

**Comment by snowle0pard** [comment]
what if i call it when i click the cluster or add marker? it seem the same question with zoomToBoundingBox()

**Comment by spyhunter99** [comment]
no idea. run the sample app. it's on play store as 'Open Map'. check out the source and how animate to is called.

**Comment by spyhunter99** [comment]
maybe you're calling it from a non-ui thread?

**Comment by spyhunter99** [comment]
if this is still a problem, reopen it with instructions/code to reproduce the problem. otherwise i have no way to help
