### ISSUE TITLE
why the overlay and marker keep drawing when adding to the map?

### ISSUE THREAD

**Issue by snowle0pard** [osmdroid/osmdroid#279]
why does the overlay and marker keep drawing after  adding to the map?

**Comment by spyhunter99** [comment]
What version? can you provide sample code and/or more information?

**Comment by snowle0pard** [comment]
# here is my code：


public class CustomeMarker extends Marker
{
    private Bitmap mCacheBitmap;
    private Canvas mCacheCanvas;
    private Paint mCachePaint;
    private TextPaint mTextPaint;
    private String mName;
    private int padding;
    private Drawable mIcondrawable;
    /**
     * 标题背景色
     */
    private int textBackGroud = UIUtils.getcolor(R.color.textbg_half_transparent_black);
    private int mCacheBitmapWidth;

    public CustomeMarker(MapView mapView)
    {
        super(mapView);
        mCachePaint = new Paint(Paint.FILTER_BITMAP_FLAG);
        mCachePaint.setAntiAlias(true);
        mTextPaint = new TextPaint(Paint.FILTER_BITMAP_FLAG);
        mTextPaint.setAntiAlias(true);
        mTextPaint.setTextSize(UIUtils.dp2px(11));
        padding = UIUtils.dp2px(5);
        mAnchorU = ANCHOR_CENTER;
        mAnchorV = 0.6f;
        int screenWidth = getScreenWidth(mapView.getContext());
        mCacheBitmapWidth = screenWidth / 5;
    }

    public String getName()
    {
        return mName;
    }

    public void setName(String name)
    {
        this.mName = name;
    }

    public void setPadding(int padding)
    {
        this.padding = padding;
    }

    public int getPadding()
    {
        return padding;
    }

    public void setTextBackGround(int color)
    {
        textBackGroud = color;
    }

    @Override
    public void draw(Canvas canvas, MapView mapView, boolean shadow)
    {
        long time = System.currentTimeMillis();
        if (shadow)
            return;
        if (mIcon == null)
            return;
        int mIconWidth = mIcon.getIntrinsicWidth();
        int mIconHeight = mIcon.getIntrinsicHeight();
        if (mCacheBitmap == null)
        {
            mCacheBitmap = Bitmap.createBitmap(mCacheBitmapWidth, mCacheBitmapWidth, Bitmap
                    .Config.ARGB_4444);
            mCacheCanvas = new Canvas(mCacheBitmap);
        }
        mCacheBitmap.eraseColor(Color.TRANSPARENT);
        Bitmap bitmap = drawalbe2Bitmap(mIcon);
        mCacheCanvas.drawBitmap(bitmap, (mCacheBitmapWidth - mIconWidth) / 2,
                mCacheBitmapWidth * mAnchorV - mIconHeight,
                mCachePaint);
        mIcondrawable = new BitmapDrawable(mapView.getContext().getResources(), mCacheBitmap);
        if (mName != null)
        {
            int textHeight = (int) (mTextPaint.descent() - mTextPaint.ascent());
            float textWidth = UIUtils.getTextWidth(mTextPaint, mName);
            mTextPaint.setColor(textBackGroud);
            float left = (mCacheBitmapWidth - textWidth) / 2 - padding;
            float top = mCacheBitmapWidth * mAnchorV + padding;
            float right = (mCacheBitmapWidth - textWidth) / 2 + textWidth + padding;
            float buttom = mCacheBitmapWidth * mAnchorV + textHeight + padding * 3;
            mCacheCanvas.drawRect(left, top, right, buttom, mTextPaint);
            mTextPaint.setColor(UIUtils.getcolor(R.color.white));
            mCacheCanvas.drawText(mName, (mCacheBitmapWidth - textWidth) / 2,
                    top - mTextPaint.ascent() + padding, mTextPaint);
        }

        final Projection pj = mapView.getProjection();
        pj.toPixels(mPosition, mPositionPixels);
        Rect rect = new Rect(0, 0, mCacheBitmapWidth, mCacheBitmapWidth);
        rect.offset(-(int) (mAnchorU * mCacheBitmapWidth), -(int) (mAnchorV * mCacheBitmapWidth));
        mIcondrawable.setBounds(rect);
        mIcondrawable.setAlpha((int) (mAlpha * 255));
        float rotationOnScreen = (mFlat ? -mBearing : mapView.getMapOrientation() - mBearing);
        drawAt(canvas, mIcondrawable, mPositionPixels.x, mPositionPixels.y, false, rotationOnScreen);
        LogUtils.d(getClass().getSimpleName(), "drawTime=" + (System.currentTimeMillis() - time));
    }

    private Bitmap drawalbe2Bitmap(Drawable drawable)
    {
        BitmapDrawable bd = (BitmapDrawable) drawable;
        return bd.getBitmap();
    }

    public int getScreenWidth(Context context)
    {
        WindowManager wm = (WindowManager) context.getSystemService(Context.WINDOW_SERVICE);
        Point point = new Point();
        wm.getDefaultDisplay().getSize(point);
        return point.x;
    }

    public boolean hitTest(final MotionEvent event, final MapView mapView)
    {
        final Projection pj = mapView.getProjection();
        pj.toPixels(mPosition, mPositionPixels);
        final Rect screenRect = pj.getIntrinsicScreenRect();
        int x = -mPositionPixels.x + screenRect.left + (int) event.getX();
        int y = -mPositionPixels.y + screenRect.top + (int) event.getY();
        return mIcondrawable.getBounds().contains(x, y);
    }

    private Object mTag;

    public void setTag(Object mTag)
    {
        this.mTag = mTag;
    }

    public Object getTag()
    {
        return mTag;
    }
}

**Comment by snowle0pard** [comment]
## here is log：
03-10 14:41:28.771 16170-16170/? D/CustomeMarker: drawTime=1
03-10 14:41:28.856 16170-16170/? D/CustomeMarker: drawTime=1
03-10 14:41:28.921 16170-16170/? D/CustomeMarker: drawTime=1
03-10 14:41:29.006 16170-16170/? D/CustomeMarker: drawTime=1
03-10 14:41:29.141 16170-16170/? D/CustomeMarker: drawTime=2
03-10 14:41:29.221 16170-16170/? D/CustomeMarker: drawTime=1
03-10 14:41:29.306 16170-16170/? D/CustomeMarker: drawTime=1
03-10 14:41:29.406 16170-16170/? D/CustomeMarker: drawTime=1
03-10 14:41:29.491 16170-16170/? D/CustomeMarker: drawTime=1
03-10 14:41:29.571 16170-16170/? D/CustomeMarker: drawTime=1
03-10 14:41:29.656 16170-16170/? D/CustomeMarker: drawTime=1
03-10 14:41:29.681 2612-2771/? V/GpsLocationProvider: SV count: 2 ephemerisMask: d3202204 almanacMask: d720a204
03-10 14:41:29.681 2612-2771/? V/GpsLocationProvider: sv: 22 snr: 1.0 elev: 47.0 azimuth: 253.0 E A
03-10 14:41:29.686 2612-2771/? V/GpsLocationProvider: sv: 10 snr: 1.7 elev: 16.0 azimuth: 173.0 E A
03-10 14:41:29.741 16170-16170/? D/CustomeMarker: drawTime=1
03-10 14:41:29.821 16170-16170/? D/CustomeMarker: drawTime=1
03-10 14:41:29.921 16170-16170/? D/CustomeMarker: drawTime=1
03-10 14:41:30.006 16170-16170/? D/CustomeMarker: drawTime=1
03-10 14:41:30.106 16170-16170/? D/CustomeMarker: drawTime=1
03-10 14:41:30.206 16170-16170/? D/CustomeMarker: drawTime=1
03-10 14:41:30.321 16170-16170/? D/CustomeMarker: drawTime=1
03-10 14:41:30.406 16170-16170/? D/CustomeMarker: drawTime=2

**Comment by snowle0pard** [comment]
it work wuth version 5.1

**Comment by snowle0pard** [comment]
it  work with version 5.1

**Comment by spyhunter99** [comment]
Wait, the problem is with v5.1 or that it works correctly in 5.1?

**Comment by snowle0pard** [comment]
I test it on android 4.4.4, 5.1.1 and 6.0 with osmdroid 5.1,it has the same question!

**Comment by spyhunter99** [comment]
short answer: because android told the map view to draw the screen.

**Comment by spyhunter99** [comment]
i suppose there's potential to only redraw when the map has moved or when an overlay has changed, but that's probably going to require some work. if you're up for a challenge, go for it and open a PR
