### ISSUE TITLE
Routing between two points

### ISSUE THREAD

**Issue by iMakerkaushal** [osmdroid/osmdroid#280]
i want to show routing between 2 points. how can i do this?

**Comment by cfsbhawkins** [comment]
OSM Bonus pack has support for a few services, including OSRM. This will require online access, if you need offline routing, there are a few projects for that too, will take a bit of work and you will need OSM data locally.

**Comment by spyhunter99** [comment]
mapsforge is one of them. regardless, there isn't much that can be done on this side.
