### ISSUE TITLE
Cached tiles load inconsistently 

### ISSUE THREAD

**Issue by bandyguy** [osmdroid/osmdroid#281]
I created a basic map app using a OnlineTileSourceBase. This works when connected to the internet. When I go offline and do actions that cause the map to reload like rotating and resuming some random tiles will not come back. I know that OSMDroid still has these cached because when I continue to rotate the phone tiles that previously did not load will load and others will fail to load.

I'm using osmdroid 5.1
I didn't see any evidence of thread locking or logging that pertained to the issue other than it attempting to connect to the online source.

**Comment by spyhunter99** [comment]
this has been reported a few times before. still not sure what the root cause is. hopefully the database switch over should fix the problem. Is this reproducible every time?

**Comment by spyhunter99** [comment]
it's possible this is a concurrency issue. the tile loading system is basically a queue of tile requests that may or may not get filled due to tile available. did you try turning on tile loading debugging?

**Comment by hlaurent** [comment]
I do experience the exact same issue with 5.0.1.
When online, tiles load find. When I go offline, some tiles which are in cache do not load. If I zoom in and zoom out back, tiles might come back. I turned in debugging and did not see anything strange. Should I look for anything specific?

**Comment by hlaurent** [comment]
Same with 5.1.
Is there anything we can do to try to sort that out before the database switch?

**Comment by spyhunter99** [comment]
i'm hoping that the database switch will resolve it. Did anyone else the following in the logs?
"Trimming tile cache from..." It's possible that your cache was trimmed at some point. It should delete the oldest files in the cache when this occurs.

The default cache size is 500MB. This can be adjusted in OpenStreetMapTileProviderConstants. The class that both saves downloaded tiles and trims the cache is TileWriter.

**Comment by spyhunter99** [comment]
I just pushed a change for additional log output with the writer. We need to confirm if the problem is related to

- saving/storing tiles on local storage
- cache trimming
- loading from local storage
- downloading tiles (unlikely but you never know...)
- or maybe something else

**Comment by hlaurent** [comment]
Thanks for looking at this.
The size of the cache in the osmdroid directory is 130Mb, far from the
500Mb limit.

1/ I currently include OSMDroid in my Android app using gradle:
compile 'org.osmdroid:osmdroid-android:5.1@aar'
What should I do to test with your changes?

2/ I did some more tests to try to isolate the issue.
Here is what I found:
- when starting the app while online through wifi, it works fine, tiles are
either loaded from cache or downloaded. If I then switch to a wifi
connection that does not have an internet connection, it works fine and
loads the tiles from cache.
- if I start on a wifi connection that does not have an internet
connection, some tiles are not loaded from cache and are greyed out. If I
switch back to a wifi that does have an internet connction, some tiles are
still not loaded.
- if I start with wifi switched off, it works fine, tiles are loaded from
cache.
- if I start on a wifi connection that does not have an internet connection
but I have set the offline mode using mapView.setUseDataConnection(false),
it works fine, tiles are loaded from cache.
- if I start on a wifi connection that does not have an internet
connection, some tiles are not loaded from cache and are greyed out. If I
then set the offline mode using mapView.setUseDataConnection(false), some
tiles are still not loaded from cache.

Any thoughts? Is there a way to handle these behaviors properly in the
library?


2016-04-25 13:15 GMT+02:00 spyhunter99 <notifications@github.com>:

**Comment by hlaurent** [comment]
Note that this can be reproduced using the osmdroid sample app.

- start by opening the app while online to make sure tiles will be loaded
in cache (device-2016-04-25-200033.png).
- exit the app
- switch to a wifi network with no internet connection
- restart the app (the app in is online mode but the wifi is not connected
to the internet), some tiles will not be loaded
(device-2016-04-25-200143.png).




2016-04-25 16:44 GMT+02:00 henri laurent <henri.laurent@gmail.com>:

**Comment by spyhunter99** [comment]
this helps a lot. this could indicate a problem with the connectivity check. i'll check into it

**Comment by spyhunter99** [comment]
oh to use the latest and greatest, you'll have to pull down the source, then build it using gradle or maven, then copy the output aar into your project (which varies depending on build tool)

**Comment by spyhunter99** [comment]
Lots of things have happened in the source base since this was posted. please retry with osmdroid/master or wait for the upcoming release

**Comment by spyhunter99** [comment]
Retry with 5.4, reopen if necessary

**Comment by apacha** [comment]
Still an issue with 5.6.4

Only happens if I change the zoom-level in the following scenario:

- One offline TileProvider (MBTiles) as Overlay
- One online TileProvider (e.g. OpenStreetMaps) as Overlay
- No online connectivity

![screenshot_1487065880](https://cloud.githubusercontent.com/assets/594497/22924047/f2495cf2-f2a3-11e6-836b-547a56cd6d61.png)

Panning around in the image brings back all tiles, though:
![screenshot_1487065886](https://cloud.githubusercontent.com/assets/594497/22924048/f5b03cee-f2a3-11e6-8e20-74795a90a7f3.png)

Does not happen, once the Internet connectivity gets back.

I initialize my MapsView with a `MapTileProviderArray` that contains both tile providers and add it via `mapView.getOverlays().add(mapTileProviderArray);`
