### ISSUE TITLE
Zoom in accordance with the radius.

### ISSUE THREAD

**Issue by thalissondev** [osmdroid/osmdroid#284]
When I call the **zoomToSpan()** function the result is expected, the zoom changes. But soon after I call **getZoomLevel()** and the return value is the former and not the updated value after calling **zoomToSpan()**. Does anyone know what's going on can? Thank you.

**Comment by spyhunter99** [comment]
is it possible the map is still in the process of zooming when you're calling getZoomLevel?

**Comment by spyhunter99** [comment]
ping?
