### ISSUE TITLE
When 2 markers overlap click occurs on the marker behind.

### ISSUE THREAD

**Issue by 2ndGAB** [osmdroid/osmdroid#285]
Hello,
I've sometimes 2 markers overlapping on my map and strangely, when I click on the one I see, so displayed on top, I open the infoWindow of the one which is behind.

Where do this problem come from?
Alain

**Comment by spyhunter99** [comment]
This is probably related to the draw order. Goes from the first thing added to the map to the last, checking for a "hit". I don't believe there's anything in place to manage multiple points at the same location. What would be the desired behavior? You could try the clustering tool with osm bonus pack

**Comment by 2ndGAB** [comment]
Hi spyhunter,
It's quite strange:
I use the clustering functionnality and I sort my marker list before display in order that the most important markers be drawn in the last to be visibles on top of the others so, it seems that's not related to the display order.
That is, it's quite strange that when I click on 2 overlapped markers, the one which receives the click is the one behind.

**Comment by spyhunter99** [comment]
try reversing the sort order.

**Comment by 2ndGAB** [comment]
No Spyhunter, if I reverse the sort order I go back to the situation I had before, i.e. some of the important markers are displayed in background.
As I said, the good markers is topmost but the bottommost one gets the click.

**Comment by spyhunter99** [comment]
Strange. Can you work up a small example that replicates the issue? And
what do you want the expected behavior to be? The top most icon get the
click?

**Comment by 2ndGAB** [comment]
Hi spyhunter,
After more test in a sample application, I realized this is something related to `RadiusMarkerClusterer()` so `OSMDroidBonusPack`.
Sorry.

**Comment by spyhunter99** [comment]
no problem
