### ISSUE TITLE
Cloning into android studio

### ISSUE THREAD

**Issue by wildfiregt** [osmdroid/osmdroid#286]
Hello
I'm having trouble cloning this link https://github.com/osmdroid/osmdroid/tree/master/OpenStreetMapViewer
to android studio. I can clone whole osmdroid but that's not what i'm searching. Can you tell how i can get only this project working ? thanks

**Comment by spyhunter99** [comment]
I don't think git works that way. It's all or nothing

**Comment by spyhunter99** [comment]
https://github.com/osmdroid/osmdroid/wiki/How-to-build-osmdroid-from-source

git clone https://github.com/osmdroid/osmdroid.git
