### ISSUE TITLE
Download map for city or country.

### ISSUE THREAD

**Issue by moonandroid** [osmdroid/osmdroid#287]
Hello,
I want to use offline map functionality in which before open app,we can download map of specific City or country.
so we can offline map for that city.

So is this possible by osmdroid ?

**Comment by spyhunter99** [comment]
read the wiki article for offline maps

**Comment by moonandroid** [comment]
Yes read wiki article from https://github.com/osmdroid/osmdroid/wiki/Offline-Map-Tiles
But not getting idea how it work for my case.

**Comment by spyhunter99** [comment]
You'll need to use some kind of geocoding service to turn the location to a geographic bounds (lat/lon) then use either mobac or the cache manager from osmbonus pack to download that region.
