### ISSUE TITLE
Update osmdroid-android-binding for Xamarin to latest version

### ISSUE THREAD

**Issue by kjeremy** [osmdroid/osmdroid#289]
@neilboyd it looks like the Xamarin component is out of date.  Please update to the latest.

**Comment by neilboyd** [comment]
See [OsmdroidXamarin issue 8](https://github.com/osmdroid/OsmdroidXamarin/issues/8)

**Comment by isr-mlambert** [comment]
It is possible to get the latest metadata.xml for xamarin?
