### ISSUE TITLE
get Location from onclick on the map

### ISSUE THREAD

**Issue by wildfiregt** [osmdroid/osmdroid#295]
Hello
Basically what I have is a simple MapView and I want to implement methods OnSingleTap or LongPress to give me latitude and longitude wherever i click on a Toast message.
All I found on searching is adding Marker Overlays but that is not what i'm searching.
Thanks

**Comment by spyhunter99** [comment]
Place a transparent view on top of the map view and attach a click listener to it. It may be possible to attach the listener to the mapview, but it may interfere with map scrolling. Give both a shot and see what happens. Once you receive the press event, get the screen x,y coordinates from the event. Then there's a function in either mapview, map controller, or projection that converter screen coordinates to lat/lon coordinates.

There's some related code in one of the samples for map motion/zoom events .

**Comment by spyhunter99** [comment]
let me know if you need further guidance. it's definitely doable

**Comment by wildfiregt** [comment]
Okay i did this :   
     
`


            MapEventsReceiver mReceive = new MapEventsReceiver() {
            @Override
            public boolean singleTapConfirmedHelper(GeoPoint p) {
                    Toast.makeText(getBaseContext(),p.getLatitude() + " - "+p.getLongitude(),Toast.LENGTH_LONG).show();

                return false;
            }

            @Override
            public boolean longPressHelper(GeoPoint p) {
                return false;
            }
        };


        MapEventsOverlay OverlayEvents = new MapEventsOverlay(getBaseContext(), mReceive);
        map.getOverlays().add(OverlayEvents);`


It's working fine with simple code

**Comment by spyhunter99** [comment]
ahh so for future readers, this was off of develop, which at the moment is post osmbonuspack partial migration. So for 5.1 and older, this code requires osmbonuspack on the classpath. post 5.1 will not require osmbonuspack dependencies

**Comment by bitsnaps** [comment]
Since `MapEventsOverlay(Context ctx, MapEventsReceiver receiver)` becomes deprecated you can use the other constructor `MapEventsOverlay(MapEventsReceiver receiver)`, here is an example:
```
        final MapEventsReceiver mReceive = new MapEventsReceiver(){
            @Override
            public boolean singleTapConfirmedHelper(GeoPoint p) {
                Toast.makeText(getBaseContext(),p.getLatitude() + " - "+p.getLongitude(), Toast.LENGTH_LONG).show();
                return false;
            }
            @Override
            public boolean longPressHelper(GeoPoint p) {
                return false;
            }
        };
        map.getOverlays().add(new MapEventsOverlay(mReceive));
```

**Comment by BWappsandmore** [comment]
Has anyone done this in Kotlin already? I'm curretly struggling with `MapEventsReceiver` interface. Many thanks in advance.

**Comment by patrickunterwegs** [comment]
If you're using jetpack compose you might want to use it directly without extending a class, so this might be useful for some of you:

```
val tapOverlay = MapEventsOverlay(object: MapEventsReceiver {
	override fun singleTapConfirmedHelper(p: GeoPoint?): Boolean {
		// Do whatever
		return true
	}
	override fun longPressHelper(p: GeoPoint?): Boolean {
		// Do whatever
		return true
	}
})
map.overlays.add(tapOverlay)
```

**Comment by YohannesTz** [comment]
> If you're using jetpack compose you might want to use it directly without extending a class, so this might be useful for some of you:
> 
> ```
> val tapOverlay = MapEventsOverlay(object: MapEventsReceiver {
> 	override fun singleTapConfirmedHelper(p: GeoPoint?): Boolean {
> 		// Do whatever
> 		return true
> 	}
> 	override fun longPressHelper(p: GeoPoint?): Boolean {
> 		// Do whatever
> 		return true
> 	}
> })
> map.overlays.add(tapOverlay)
> ```

your reply worked easy and fast. thank you!
