### ISSUE TITLE
Offline map and geocoding

### ISSUE THREAD

**Issue by wildfiregt** [osmdroid/osmdroid#297]
When it comes to offline maps ,we can make use of MOBAC to get tiles. But when the portion is too big like a whole country, we will have big files of jpg's 
Is there any way to get data from extracts here ? 
http://download.openstreetmap.fr/extracts
For example ,50 mb of pbf file will result into 1GB of xml.

Also is there a way to get offline reverse geocoding ? I tried Nominatim which i find nice and simple but still requires internet

**Comment by spyhunter99** [comment]
Mapsforge

**Comment by spyhunter99** [comment]
To add some more context, mapsforge is the only tool i know of that comes close. It is GPL licensed though. Some other info, I did do some initial work to write a java utility to read the source data from osm. The next step is to insert the data into a sqlite database of some sort. This would give you the raw osm data which are points and ways. 

What might be easier is to rip though the data looking for explicit city/town/state/place POIs and store them to a database, then distribute that with your application. It's probably in the million so size may be a factor. I'd be interested in collaborating with you on this

**Comment by devemux86** [comment]
[Mapsforge](https://github.com/mapsforge/mapsforge) is licensed under LGPL3. :smile:

**Comment by spyhunter99** [comment]
@wildfiregt quick update, i reworked my code to use xml pull parser right from the compressed extracts which are bz2 files. Long story short, we can process on device, but it's slow....... very slow. It took hours to process in the emulator for the smallest extract i could find, Delaware, USA.

After it's processed though, queries are pretty quick for reverse geocoding.  This gives you both city, state, and street name to lat/lon

**Comment by spyhunter99** [comment]
1460601726044 commit! inserts, total record count 5960732 stack 0
1460601770285 commit! inserts, total record count 6119683 stack 0

time 44.241s
record 158951

**Comment by wildfiregt** [comment]
Dunno what i can help you with. But if you provide how I can make queries. I will be glad to offer search nodes for the app like restaurants,hospitals,hotels ... I'm currently working on this on my project using online Nominaatim

**Comment by spyhunter99** [comment]
I posted the library here, mostly because i don't have permissions to make new repo's under the osmdroid organization. Enjoy
https://github.com/spyhunter99/osmreader
