### ISSUE TITLE
MBTiles UTFGrid integration

### ISSUE THREAD

**Issue by mikolaiguetschow** [osmdroid/osmdroid#299]
As I asked [here](http://stackoverflow.com/questions/36483466/osmdroid-and-mbtiles-get-area-information/), I would like to have [UTFGrid](https://github.com/mapbox/utfgrid-spec/blob/master/1.3/utfgrid.md) support for the MBTiles Offline Tile Provider.

I've already looked a bit into the code, tried to understand the tile loading process and searched for where I could hook into while adding the metadata-support. I thought of simply adding a function inside [MBTilesFileArchive.java](https://github.com/osmdroid/osmdroid/blob/master/osmdroid-android/src/main/java/org/osmdroid/tileprovider/modules/MBTilesFileArchive.java), but then I need to calculate the tile-coordinates again and it won't be cached as the normal tiles are. So if someone could point me in the right direction and give a idea where to start, I would like to contribute :)

I know it doesn't really fit well with the normal TileProvider-workflow, because a TileSource normally cannot give any meta-information. But MBTiles coupled with UTFGrid can, so I would like to be able to access them.

**Comment by spyhunter99** [comment]
not sure how UTFGrid is going to help you. You need to have the bounds of the countries. I'd suggest pairing osmdroid with osmbonuspack. Then find a country boundary kml file, import that kml, then use click listeners on each polygon that represents a country. You're barking up the wrong tree (tile provider)
