### ISSUE TITLE
cannot build the `Map Tile packager` using gradle

### ISSUE THREAD

**Issue by roostaamir** [osmdroid/osmdroid#300]
I am trying to build the tile packager in order to build an offline map. But I am unable to build the tile packager using the `gradle compilejava` command. I get the two following errors:

> > Cannot resolve external dependency org.apache.httpcomponents:httpmime:4.0.1 be
> cause no repositories are defined.
>   Required by:
>       :OSMMapTilePackager:unspecified
> > Cannot resolve external dependency org.apache.james:apache-mime4j:0.6 because
> no repositories are defined.
>   Required by:
>       :OSMMapTilePackager:unspecified

how can I resolve this?

**Comment by spyhunter99** [comment]
Try building with maven.  I should have a gradle fix shortly

**Comment by spyhunter99** [comment]
update, try building from the parent directory

**Comment by roostaamir** [comment]
I tried to build the project form the parent window and now I am getting a new error about android sdk:

> > SDK location not found. Define location with sdk.dir in the local.properties f
> ile or with an ANDROID_HOME environment variable.

I have android sdk, and I have both an ANDROID_HOME varibale in my enviroment varibales, and both tools and platform tools in the path varibale.(I am using windows)

what should I do now?

**Comment by roostaamir** [comment]
Ok I managed to solve this too. but now it gives me this error on GoogleWrapperSample project:

> Cannot invoke method defaultConfig() on null object

and if I delete allthe project except the tile packager(since it is the only one I want), I get this error:

> Could not find tools.jar

what do you suggest me to do?

**Comment by roostaamir** [comment]
I tried compiling it from the parent directory but now I get 13 compilation errors:

> D:\projects\GitHub\osmdroid-master\osmdroid-master\OSMMapTilePackager\src\main\j
> ava\org\osmdroid\mtp\download\DownloadManager.java:18: error: package org.osmdro
> id.tileprovider.util does not exist
> import org.osmdroid.tileprovider.util.StreamUtils;
>                                      ^
> D:\projects\GitHub\osmdroid-master\osmdroid-master\OSMMapTilePackager\src\main\j
> ava\org\osmdroid\mtp\OSMMapTilePackager.java:17: error: package org.osmdroid.uti
> l does not exist
> import org.osmdroid.util.GEMFFile;
>                         ^
> D:\projects\GitHub\osmdroid-master\osmdroid-master\OSMMapTilePackager\src\main\j
> ava\org\osmdroid\mtp\util\FolderZipper.java:12: error: package org.osmdroid.tile
> provider.util does not exist
> import org.osmdroid.tileprovider.util.StreamUtils;
>                                      ^
> D:\projects\GitHub\osmdroid-master\osmdroid-master\OSMMapTilePackager\src\main\j
> ava\org\osmdroid\mtp\download\DownloadManager.java:130: error: cannot find symbo
> l
>                                 in = new BufferedInputStream(new URL(finalURL).o
> penStream(), StreamUtils.IO_BUFFER_SIZE);
> 
>              ^
>   symbol:   variable StreamUtils
>   location: class DownloadManager.DownloadRunner
> D:\projects\GitHub\osmdroid-master\osmdroid-master\OSMMapTilePackager\src\main\j
> ava\org\osmdroid\mtp\download\DownloadManager.java:133: error: cannot find symbo
> l
>                                 out = new BufferedOutputStream(fileOut, StreamUt
> ils.IO_BUFFER_SIZE);
>                                                                         ^
>   symbol:   variable StreamUtils
>   location: class DownloadManager.DownloadRunner
> D:\projects\GitHub\osmdroid-master\osmdroid-master\OSMMapTilePackager\src\main\j
> ava\org\osmdroid\mtp\download\DownloadManager.java:135: error: cannot find symbo
> l
>                                 StreamUtils.copy(in, out);
>                                 ^
>   symbol:   variable StreamUtils
>   location: class DownloadManager.DownloadRunner
> D:\projects\GitHub\osmdroid-master\osmdroid-master\OSMMapTilePackager\src\main\j
> ava\org\osmdroid\mtp\download\DownloadManager.java:142: error: cannot find symbo
> l
>                                 StreamUtils.closeStream(in);
>                                 ^
>   symbol:   variable StreamUtils
>   location: class DownloadManager.DownloadRunner
> D:\projects\GitHub\osmdroid-master\osmdroid-master\OSMMapTilePackager\src\main\j
> ava\org\osmdroid\mtp\download\DownloadManager.java:143: error: cannot find symbo
> l
>                                 StreamUtils.closeStream(out);
>                                 ^
>   symbol:   variable StreamUtils
>   location: class DownloadManager.DownloadRunner
> D:\projects\GitHub\osmdroid-master\osmdroid-master\OSMMapTilePackager\src\main\j
> ava\org\osmdroid\mtp\OSMMapTilePackager.java:258: error: cannot find symbol
>                final GEMFFile file = new GEMFFile(pDestinationFile, sourceFolder
> s);
>                      ^
>   symbol:   class GEMFFile
>   location: class OSMMapTilePackager
> D:\projects\GitHub\osmdroid-master\osmdroid-master\OSMMapTilePackager\src\main\j
> ava\org\osmdroid\mtp\OSMMapTilePackager.java:258: error: cannot find symbol
>                final GEMFFile file = new GEMFFile(pDestinationFile, sourceFolder
> s);
>                                          ^
>   symbol:   class GEMFFile
>   location: class OSMMapTilePackager
> D:\projects\GitHub\osmdroid-master\osmdroid-master\OSMMapTilePackager\src\main\j
> ava\org\osmdroid\mtp\util\FolderZipper.java:50: error: cannot find symbol
>                         StreamUtils.closeStream(out);
>                         ^
>   symbol:   variable StreamUtils
>   location: class FolderZipper
> D:\projects\GitHub\osmdroid-master\osmdroid-master\OSMMapTilePackager\src\main\j
> ava\org\osmdroid\mtp\util\FolderZipper.java:72: error: cannot find symbol
>                                 StreamUtils.copy(fileIn, zip);
>                                 ^
>   symbol:   variable StreamUtils
>   location: class FolderZipper
> D:\projects\GitHub\osmdroid-master\osmdroid-master\OSMMapTilePackager\src\main\j
> ava\org\osmdroid\mtp\util\FolderZipper.java:73: error: cannot find symbol
>                                 StreamUtils.closeStream(fileIn);
>                                 ^
>   symbol:   variable StreamUtils
>   location: class FolderZipper
> 13 errors
> :OSMMapTilePackager:compileJava FAILED
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':OSMMapTilePackager:compileJava'.
> > Compilation failed; see the compiler error output for details.

any suggestions?

**Comment by spyhunter99** [comment]
interesting. what version are you trying to build? is this master or one of the release versions? i'll just build it and post the version on github

**Comment by roostaamir** [comment]
It is the master one.

**Comment by roostaamir** [comment]
ok somehow, out of nowhere, the compilation went fine this time and I got a `BUILD SUCCESSFUL` message after three days.But now, there are no jar executable that I can use.

**Comment by roostaamir** [comment]
Ok for some reason, it now decided to build and finally I got the `BUILD SUCCESSFUL` message.But now when I want to use the created jar file with the `java -jar` command, I get this error:

> no main manifest attribute, in OSMMapTilePackager-5.1-SNAPSHOT.jar

**Comment by spyhunter99** [comment]
hmm ok one minute

**Comment by spyhunter99** [comment]
'gradle run' should start it
'gradle distZip' as well as 'gradle build' will build a zip in the build/distributions folder, which you then need to unzip, then run the batch/shell script

**Comment by roostaamir** [comment]
sorry that this thread is taking too long but I am still getting the same error

**Comment by spyhunter99** [comment]
gradle build
or try with the gradle wrapper
./gradlew build

localhost:osmdroid alex$ cd OSMMapTilePackager/
localhost:OSMMapTilePackager alex$ gradle run
copying StreamUtils sources
copying GEMF sources
copying api sources
removing android specific api sources
:OSMMapTilePackager:preBuildTask1 UP-TO-DATE
:OSMMapTilePackager:preBuildTask2 UP-TO-DATE
:OSMMapTilePackager:preBuildTask3
:OSMMapTilePackager:preBuildTask4
:OSMMapTilePackager:compileJava UP-TO-DATE
:OSMMapTilePackager:processResources UP-TO-DATE
:OSMMapTilePackager:classes UP-TO-DATE
:OSMMapTilePackager:run
Usage:
-gui	Launch the GUI
-u	[OSM-style tile URL: http://_URL_/%d/%d/%d.png]
-t	[Temporary Folder]
-d	[Destination-file: C:\mappack.zip]
-zmin	[Minimum zoomLevel to download. Default: 0]
-zmax	[Maximum zoomLevel to download]
-fa	[Filename-Appendix. Default: ""]
-n	[North Latitude]
-s	[South Latitude]
-e	[East Longitude]
-w	[West Longitude]
-nthreads	[Number of Download-Threads. Default: 2]


BUILD SUCCESSFUL

Total time: 10.249 secs

This build could be faster, please consider using the Gradle Daemon: http://gradle.org/docs/2.4/userguide/gradle_daemon.html
localhost:OSMMapTilePackager alex$

**Comment by spyhunter99** [comment]
The reason why java -jar ....jar doesn't work is because gradle by default, doesn't do the maven single jar with dependencies. Instead it builds a distribution zip/tar with some generated sh/bat files to start up the app. I personally don't like it. We can make gradle produce the single jar with dependencies however it's painfully slow. Like really slow. Because gradle is stupid.


So your options are:
gradle build
cd build\distributions
unzip OSMMapTilePackager-5.1-SNAPSHOT.zip
cd OSMMapTilePackager-5.1-SNAPSHOT/bin
./OSMMapTilePackager

or from the OSMMapTilePackager
gradle run

**Comment by roostaamir** [comment]
ok I started the application using the file in the `/bin` folder and used the -gui switch.
I left the url textbox to what it already is and set the bounding boxes for my map.
I set the destinatino file to `D:\Maps\Mapnik\maps.zip` and the temp folder to `D:\Maps\Mapnik` (don't really know what this temp folder does, if you could enlighten me that would be great too.
The application will download the tiles successfully (I can see the folders and some png files inside them) but the problem is, it will start to build the `maps.zip` file to the point that there is no space left in my drive and I get a `not enough space` error.This is what the command line shows to me:

> Zipping files to D:\Maps\Mapnik\maps.zip ...java.io.IOException: There is not en
> ough space on the disk
>         at java.io.FileOutputStream.writeBytes(Native Method)
>         at java.io.FileOutputStream.write(FileOutputStream.java:345)
>         at java.util.zip.DeflaterOutputStream.deflate(DeflaterOutputStream.java:
> 253)
>         at java.util.zip.DeflaterOutputStream.write(DeflaterOutputStream.java:21
> 1)
>         at java.util.zip.ZipOutputStream.write(ZipOutputStream.java:314)
>         at org.osmdroid.tileprovider.util.StreamUtils.copy(StreamUtils.java:64)
>         at org.osmdroid.mtp.util.FolderZipper.addFolderToZip(FolderZipper.java:7
> 2)
>         at org.osmdroid.mtp.util.FolderZipper.zipFolderToFile(FolderZipper.java:
> 48)
>         at org.osmdroid.mtp.OSMMapTilePackager.runZipToFile(OSMMapTilePackager.j
> ava:268)
>         at org.osmdroid.mtp.OSMMapTilePackager.execute(OSMMapTilePackager.java:1
> 95)
>         at org.osmdroid.mtp.ui.OSMMapTilePackagerUI$6$1.run(OSMMapTilePackagerUI
> .java:485)
>         at java.lang.Thread.run(Thread.java:745)
>  done.
> ---------------------------
> ---------------------------
> Deleting temp folder ...Could not delete D:\Maps\Mapnik\maps.zip
>  done.

the last two lines of error shows up after the gui asks me if I want to delete the temp folder.
what should I do now?

**Comment by spyhunter99** [comment]
it says there's no space left. maybe there's no space  left or there's some file permission issue

**Comment by roostaamir** [comment]
As i said in the post above, I have like 10 gigabytes left in my `D` drive and I am only getting 9x and 10x zoom levels

The problem is that the tilepackager starts to build a .zip file and then fills it until there is no more space left. These two zoom levels should not take more than 100 megabytes and the zip file continues to grow until i get this error (which is right since I end up having a 10+gigabyte zip file)
What do you think is the problem?

**Comment by spyhunter99** [comment]
Can you post the exact input parameters so i can replicate? I know there's an issue getting the whole planet, but it should just work in this case

**Comment by roostaamir** [comment]
![untitled](https://cloud.githubusercontent.com/assets/10849094/14693383/a3326b8e-0773-11e6-84b5-dd6a1eedab58.png)

**Comment by spyhunter99** [comment]
try setting the temp-folder to just "Mapnik"

**Comment by spyhunter99** [comment]
From the command line, this ran ok....
`./OSMMapTilePackager -t Mapnik -d mapmack.zip -zmin 9 -zmax 10 -n 29.8418 -s 29.4922 -e 52.6410 -w 52.3869 -u http://b.tile.openstreetmap.org/%d/%d/%d.png`

**Comment by roostaamir** [comment]
yes it worked with the way you suggested. thank you very much for that
I extracted the zip file.put the folders(named 9 and 10) into /osmdroid/tiles/Mapnik folder but none of the tiles will be shown offline

what is wrong now?

**Comment by spyhunter99** [comment]
dont extract them, just but the zip at /sdcard/osmdroid/

**Comment by roostaamir** [comment]
Still not seeing any maps

**Comment by spyhunter99** [comment]
The contents of the zip should be
/{MapSource}/{z}/{x}/{y}.png or .jpg

What does yours look like?

What map source did you tell osmdroid to load? the {MapSource} string in
the zip much match the ITileSource name that you tell the mapview to display

**Comment by spyhunter99** [comment]
You app will also need read/write access to external storage. If you're
running an API23+ device or vm, these permissions need to be granted by the
user explicitly

**Comment by roostaamir** [comment]
this is the zip file I have:
[https://www.mediafire.com/?vtjqvdrb24r1fl2](url)
as you can see from my code above, I am using `Mapnik` tile source and the parent folder is also named `Mapnik`.Also I am on lollipop so there is no explicit permission required here.

**Comment by spyhunter99** [comment]
The contents of your zip is "Mapnik/Mapnik/z/x/y.png

**Comment by roostaamir** [comment]
Oh you are absolutely right and now it is working. Now I have two more questions:
1- is it possible to cache different  parts of the maps with different zooms and put their separate zip files in `/osmdroid` folder in order for them to work?
2- is it possible to have tiles with a specific message such as `this part of the map is not available.either download the offline tiles or connect to internet` replace the raw square like pattern for when a part of the map is not available?

**Comment by spyhunter99** [comment]
1) yes, the default tile loading mechanism will scan all tile archives for a matching source/z/x/y file.
2) i think the answer is yes and have attempted it be was able to figure out it out. I think you can return a default 256x256 image if no tile is available for that source and zoom level. I think it needs to be in the MapTileModuleProviderBase.

**Comment by roostaamir** [comment]
I couldn't find such a class or interface in the packages :(

**Comment by spyhunter99** [comment]
https://github.com/osmdroid/osmdroid/blob/master/osmdroid-android/src/main/java/org/osmdroid/tileprovider/MapTileProviderBase.java

**Comment by spyhunter99** [comment]
edit on point 2, i was NOT able to figure it out. I left out an important word. Anyhow i'm sure it's possible, I just wasn't successful in doing so

**Comment by roostaamir** [comment]
Thanks again for your patience and help

**Comment by aserhany** [comment]
Hi @spyhunter99, I followed this thread and unfort. had the following error while downloading the maps data: 

***@XubuntuVirtualBox:~/AndroidStudioProjects/osmdroid/OSMMapTilePackager/build/distributions/OSMMapTilePackager-5.3-SNAPSHOT/bin$ ./OSMMapTilePackager -gui
---------------------------
ZoomLevel: 0 .Error downloading: 'z=0 x=0 y=-6' from URL: http://b.tile.openstreetmap.org/0/0/-6.png : java.net.ConnectException: Connection refused
.Error downloading: 'z=0 x=0 y=-5' from URL: http://b.tile.openstreetmap.org/0/0/-5.png : java.net.ConnectException: Connection refused
.Error downloading: 'z=0 x=0 y=-4' from URL: http://b.tile.openstreetmap.org/0/0/-4.png : java.net.ConnectException: Connection refused
.Error downloading: 'z=0 x=0 y=-3' from URL: http://b.tile.openstreetmap.org/0/0/-3.png : java.net.ConnectException: Connection refused
.Error downloading: 'z=0 x=0 y=-2' from URL: http://b.tile.openstreetmap.org/0/0/-2.png : java.net.ConnectException: Connection refused
.Error downloading: 'z=0 x=0 y=-1' from URL: http://b.tile.openstreetmap.org/0/0/-1.png : java.net.ConnectException: Connection refused
.Error downloading: 'z=0 x=0 y=0' from URL: http://b.tile.openstreetmap.org/0/0/0.png : java.net.ConnectException: Connection refused
.Error downloading: 'z=0 x=0 y=1' from URL: http://b.tile.openstreetmap.org/0/0/1.png : java.net.ConnectException: Connection refused
.^Cesk@XubuntuVirtualBox:~/AndroidStudioProjects/osmdroid/OSMMapTilePackager/build/distributions/OSMMapTilePackager-5.3-SNAPSHOT/bin$ 

I believe this error is due to the fact that I am sitting behind a proxy and need to make the respective settings for it but I see no options to do so. Any idea where/how can I enter the proxy settings (hostname, port)

Thanks in advance for any hint.

**Comment by spyhunter99** [comment]
Probably via the standard java proxy settings, which are set via system properties.
java -Dhttp.proxyHost=10.0.0.100 -Dhttp.proxyPort=8800 -jar OSM..... {params}

**Comment by aserhany** [comment]
Thanks for your reply. Unfort. I cant run the jar (prob the same problem with gradle as mentioned above) and therefore I use the sh script: 
cd OSMMapTilePackager-5.1-SNAPSHOT/bin
./OSMMapTilePackager

Is it possible to configure the proxy settings in the sh file?

**Comment by spyhunter99** [comment]
Ahh set. Just edit the bash script. There should be a line that says
JAVA_OPTS, just add your settings to that line

**Comment by mminelli** [comment]
I'll comment here because the problem is ultimately the same, but maybe it's better to open another issue?

In short, I cannot build OSM Map Tile Packager with gradle 6.5.1. This is the error I get when I run `gradle build` in the `OSMMapTilePackager` folder:

```
FAILURE: Build failed with an exception.

* Where:
Script 'https://raw.githubusercontent.com/gradle-fury/gradle-fury/v1.1.4/gradle/maven-support.gradle' line: 1453

* What went wrong:
Could not compile script 'https://raw.githubusercontent.com/gradle-fury/gradle-fury/v1.1.4/gradle/maven-support.gradle'.
> startup failed:
  script 'https://raw.githubusercontent.com/gradle-fury/gradle-fury/v1.1.4/gradle/maven-support.gradle': 1453: unable to resolve class org.gradle.api.internal.ClosureBackedAction 
   @ line 1453, column 13.
                 new org.gradle.api.internal.ClosureBackedAction({
                 ^
  
  1 error


* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org
```

Maybe this helps: I read [here](https://github.com/gradle/gradle/issues/8026#issuecomment-446838160) that 
> The class ClosureBackedAction is moved from org.gradle.api.internal.ClosureBackedAction to org.gradle.util.ClosureBackedAction since Gradle 5.0.

**Comment by monsieurtanuki** [comment]
@mminelli Maybe related to #1594.

**Comment by mminelli** [comment]
@monsieurtanuki Thanks, I'll check that out.

**Comment by hannesa2** [comment]
Maybe you can try out if this modernized repo helps

Step 1. Add the JitPack repository to your build file
Add it in your root build.gradle at the end of repositories:

	allprojects {
		repositories {
			...
			maven { url 'https://jitpack.io' }
		}
	}

Step 2. Add the dependency

	dependencies {
	        implementation 'com.github.hannesa2:osmdroid:6.1.6.2'
	}
