### ISSUE TITLE
setMapOrientation

### ISSUE THREAD

**Issue by Mantj** [osmdroid/osmdroid#301]
when i am moving , i want to change my map orientation so i can always see the correct direction of my map.
i want to do it by using :
# map.setMapOrientation();
but how i can get my orientation when i am moving .
please help me ,thanks~ ,and forgive my poor English~

**Comment by spyhunter99** [comment]
it's the same command, but you'll need to set the map orientation based on gps heading or compass orientation.

**Comment by Mantj** [comment]
Thank for your focus.
i try to use ## mCompassOverlay.getOrientation() to get the orientation,and i successfully get what i want .
but i notice that my compass sometimesiInaccuracy，so i want to use the gps,but i don't know how to use it.
## MyLocationNewOverlay mLocationOverlay = new MyLocationNewOverlay(new GpsMyLocationProvider(this), map, mResourceProxy);
is it use "mLocationOverlay" to get the orientation?

**Comment by spyhunter99** [comment]
Just use android's location manager and handle onLocationChanged in whatever way you want
