### ISSUE TITLE
Offline map doesn't display

### ISSUE THREAD

**Issue by anto2b** [osmdroid/osmdroid#302]
Config : 
Device : Samsung Galaxy S6
Android 5.1.1

I would like to display my offline tiles on mapview but doesn't display.
I followed the wiki for offline map tiles : [https://github.com/osmdroid/osmdroid/wiki/Offline-Map-Tiles](https://github.com/osmdroid/osmdroid/wiki/Offline-Map-Tiles)
I put my _tiles.zip_ (generated with MOBAC) in emulated/0/osmdroid folder (in galaxy s6 have not physical sd card).
The artchitecture on my zip file : 

_MapQuest_
|_ 14
         |__ _34445
                    |_____ 24302.jpg
                    |_____ 24303.jpg
...

Here is my code : 

```
@Override
protected void onCreate(Bundle savedInstanceState)
{
super.onCreate(savedInstanceState);
setContentView(R.layout.main_activity);

MapView map = (MapView) findViewById(R.id.mapview);

map.setTileSource(new XYTileSource("MapQuest", 0, 18, 256, ".jpg", new String[] {}));
map.setUseDataConnection(false); //optional, but a good way to prevent loading from the network and test your zip loading.

IMapController mapController = map.getController();
mapController.setZoom(14);
}

```
My logcat

```
04-24 19:38:42.621 30908-30908/com.ghisoni I/OsmDroid: Using tile source: Mapnik
04-24 19:38:42.631 30908-30908/com.ghisoni I/OsmDroid: sdcard state: mounted
04-24 19:38:42.631 30908-30908/com.ghisoni I/OsmDroid: sdcard state: mounted
04-24 19:38:42.641 30908-30908/com.ghisoni I/OsmDroid: sdcard state: mounted
04-24 19:38:42.951 30908-30908/com.ghisoni I/OsmDroid: Tile cache increased from 9 to 70
```

Thanks your for your help

**Comment by spyhunter99** [comment]
Are you sure the map is centered whereever you have map tiles?

**Comment by spyhunter99** [comment]
Also, your zip structure is strange, it should be
{Map Source}/Zoom/X/Y.extension

Also, osmdroid references Environment.getExternalStorageDir when looking for tile archives. this can be overridden, depending on what version  you're using. You can also explicitly set which offline tile archives to load uses a custom Map Tile Provider. there's a few examples in the sample app

**Comment by anto2b** [comment]
My zip corresponds to this format : {Map Source}/Zoom/X/Y.extension
