### ISSUE TITLE
setNumberOfTileDownloadThreads should be static

### ISSUE THREAD

**Issue by Matungos** [osmdroid/osmdroid#303]
Please make setNumberOfTileDownloadThreads static, so I could do:

OpenStreetMapTileProviderConstants.setNumberOfTileDownloadThreads(5);

Thank you.

**Comment by spyhunter99** [comment]
great catch. fixed

**Comment by aritrabasu104** [comment]
Hey @spyhunter99 / @neilboyd , Can you let me know how I can do with current build..since these methods are not there anymore?

**Comment by spyhunter99** [comment]
Configuration.getInstance().set....

See the upgrade guide in the wiki for more information
