### ISSUE TITLE
having trouble to set tile overlay to display city name.

### ISSUE THREAD

**Issue by snowle0pard** [osmdroid/osmdroid#307]
when i setting another tile overlay to display city name,the map was covered,and turn out  a  white background.The tile i use is in png picture. any suggestion for that?

**Comment by spyhunter99** [comment]
See your second tile overlay background color to transparent. i had an
example somewhere but i can't find it at the moment.

**Comment by spyhunter99** [comment]
https://github.com/osmdroid/osmdroid/blob/master/osmdroid-android/src/main/java/org/osmdroid/views/overlay/TilesOverlay.java#L313

That's about the best we can do on this end. the rest has to do what the tiles look like (if they have transparency or not).
