### ISSUE TITLE
[Q] Use obf file

### ISSUE THREAD

**Issue by diabloo** [osmdroid/osmdroid#308]
hi, 
can the library use an obf file for offline map ?

**Comment by spyhunter99** [comment]
Hmm not at the moment. What's your requirement or need? Rendering tiles or doing queries or POIs or something else?

**Comment by diabloo** [comment]
i have a obf file of a offline map and i wanted to use it in my application , because i need an offline map for an entire country (with level zoom 18) , and it was the only file with resonable size i found , thank you for the hint i will try to do more researche on what you said .

**Comment by spyhunter99** [comment]
Mapsforge (either outright, or with the osmdroid adapter) is your best bet. good luck
