### ISSUE TITLE
How to include OsmDroid in a non Gradle, non Maven project

### ISSUE THREAD

**Issue by djdance** [osmdroid/osmdroid#310]
I came here again with question about **5.1 and non-Gradle.**

I've seen [the new FAQ topic](https://github.com/osmdroid/osmdroid/wiki/How-to-include-OsmDroid-in-a-non-Gradle,-non-Maven-project), but still can not build.

Wiki says: _You have a choice between using an AAR (for >=5.0) or JAR (for < 4.3) in your libs folder._

And... whats next? Just drop aar to libs? Not work. Unzip, extract and drop classes.jar? Work, but can't find drawable (see below). So please add more instruction to the wiki topic linked above.

```
java.lang.NoClassDefFoundError: org.osmdroid.library.R$drawable

        this.mOnMarkerDragListener = null;
        if(mDefaultIcon == null) {
            mDefaultIcon = resourceProxy.getResources().getDrawable(drawable.marker_default);
        }
```

**Comment by spyhunter99** [comment]
I'm not sure if it's possible if (whatever your build system is) doesn't support AAR files. Sounds like an ancient eclipse based project. The easiest thing to do: switch to gradle/android studio. Alternatively, start googling if eclipse (or whatever it is) supports AAR files

**Comment by djdance** [comment]
but what about FAQ topic linked above? for what it was written? does it checked by someone? I mean AAR and non-gradle.

**Comment by spyhunter99** [comment]
To be honest, it was written when osmdroid was a jar output. It is now an AAR output. I don't have numbers, but I'm willing to bet most people have moved their android projects into android studio, which also forces gradle. I don't believe the eclipse setup is still supported by Google except for C++ bindings. If the FAQ is giving your heart burn, I'm not sure what I can do besides removing that part of the FAQ.

After 2 seconds of googling. i found this: https://commonsware.com/blog/2014/07/03/consuming-aars-eclipse.html 

hope this helps. The FAQ wiki page should be writable, so feel free to edit it as necessary or post suggested changes here and we'll get it updated. Sorry if this wasn't the answer you were hoping for. The only thing constant is change in this industry.

**Comment by djdance** [comment]
Thank you for the link, it looks promising! Before I tried only unzip aar. I will try and we'll change wiki, ok?

p.s. I use not eclipse, but newest android studio, with wide ancient project for ancient embedded. gradle fails here.
