### ISSUE TITLE
Testing osmdroid 5.2 with offline map

### ISSUE THREAD

**Issue by serenityluna24** [osmdroid/osmdroid#311]
Greeting.

I'm trying osmdroid 5.2 and OSMBonusPack 5.8, and i need to use some offline vector map with OSMDroid. I've been testing mapsforge format (.map) but I have experienced two problems:

The first is: This has problems loading some tiles at all zoom levels, but is most noticeable in lower levels of zoom where the letters are very large. Do you have experienced this error when rendering some tiles? when I tried separately mapsforge not notice that issues. Is it possible to change the size of the letters?

The second: As much research I could not find how to load the map from the "assets" folder. Is there any way to load the map from the assets folder?, or alternatively from another direction within the internal memory of the phone. This is because i do not want depener an SD card.

P.D.: Of all the formats supported by OSMDroid, What is the best format for vector maps of Open Street Map?
MapBox maps look good, but are they free? Can I download and use freely with OSMDroid?

Sorry for so many questions I'm starting in this wonderful world.

**Comment by spyhunter99** [comment]
Haven't ran into the issue with the mapsforge adapter. If you can provide enough information to recreate the problem and/or some screenshots, I can take a look at it. Changing the font sizes is usually though the MapsForge Theme. See the forge adapter's assets folder for the example provided by maps forge.

For maps forge databases from the assets file, I don't think that's supported at the moment, but it looks easy enough to do. Alternatively, you can copy the map file from assets to local app storage, then open it that way. Tile archives, zips, sqlite, and unzipped tiles can be loaded from assets. In fact, the sample app includes it out of the map from zoom =0-1.

MapBox is raster tiles, as is every other format that osmdroid supports. Unsure if mapbox is free or not. 

Mapsforge is the only on device renderer for vector graphics that osmdroid supports at the moment. There's trade offs though, you'll need to download some large files and store them on device + space for the tile cache. Expect 40-50 GBs for the planet, just for the vector data.

There was some discussion on supporting vector tiles, however the only open source libraries that support is right now are GPL licensed, which clashes with the ASF license.

I also did some work using NGA's geopackage format, but only for the raster tiles, not the vector tiles. It may be possible to adapter their renderer and file structure.

As far as what's best, it's probably a matter of opinion. I personally like the mapquest files. That said, I'm not a lawyer but i don't believe you are allowed to download them and use offline. OpenStreetMaps.org's tiles should be usable offline.

For US based maps, USGS maps can be downloaded and used offline (again I'm not a lawyer). The TOPO maps are pretty nice, but the sat and road maps aren't quite as easy on the eyes as other formats. Your mileage will vary based on region.

**Comment by spyhunter99** [comment]
well reopen if you have further questions. not sure if there's any actions to take on this end.
