### ISSUE TITLE
offline-map

### ISSUE THREAD

**Issue by Mantj** [osmdroid/osmdroid#312]
when i used 
map.setTileSource(new XYTileSource("MapQuest", 0, 18, 256, ".jpg", new String[] {}));
eclipse tell me thats error.
So I use
 map.setTileSource(new XYTileSource("MapQuest", null,0, 18, 256, ".jpg", new String[] {}));
but I can not see the map.
By the way 
osmdroid 4.3
osmbonuspack 5.0
slf4j 1.6.1

please help me~

**Comment by spyhunter99** [comment]
do you have an offline tile archive already prepared and copied to the device in /sdcard/osmdroid?
does the offline tile archive use the "MapQuest" tile source name?

**Comment by Mantj** [comment]
yes,I used MOBAC to download the offline tile.

**Comment by spyhunter99** [comment]
Did you produce a sqlite file or a zip file? In either case, you'll want to open the archive and verify that the source name is exactly "MapQuest"

**Comment by Mantj** [comment]
Yes,of course.
I use
map.setTileSource(new XYTileSource("MapQuest", 0, 18, 256, ".jpg", new String[] {}));
in android studio,and I can successfully get my offline-map
but when I use this in eclipse,it tells me thats error,and ask me use 
map.setTileSource(new XYTileSource("MapQuest", null,0, 18, 256, ".jpg", new String[] {}));
why I must add "null"?is it because I use osmdroid 4.3.jar?

**Comment by spyhunter99** [comment]
the only possibility if that you have two different versions in play for
android studio and for eclipse. There was an API change that removed the
need for the null parameter when the resource proxy was removed.
