### ISSUE TITLE
Does OSMDroid 5.2 include RadiusMarkerClusterer?

### ISSUE THREAD

**Issue by 2ndGAB** [osmdroid/osmdroid#313]
Hello,
RadiusMarkerClusterer and StaticCluster

> Namely, everything but the KML/GeoJson parsing and online routing tools have been migrated (with Git history)

Because I cannot resolve it at build

**Comment by spyhunter99** [comment]
No. It was one of the things @MKergall did not want to migrate. Looks like it's still in osmbonus pack

**Comment by spyhunter99** [comment]
Looks like there's still a lot of duplicate classes including Marker. Not sure what the status is
