### ISSUE TITLE
Customizing CacheManager UI

### ISSUE THREAD

**Issue by 2ndGAB** [osmdroid/osmdroid#315]
Hello spyhunter99,

Maybe I didn't well explained my needs on that point https://github.com/MKergall/osmbonuspack/issues/231, because I took a look at the application sample but I didn't see how to customize the downloading message.

I mean this dialog: [Imgur](http://i.imgur.com/oxR6FRK.png)

So I suggested to pass the progressDialog to CacheManagerTask.

**Comment by spyhunter99** [comment]
It looks like a protected string sets the "Handling zoom" message. Extend
the class and override it.

**Comment by 2ndGAB** [comment]
Hi Spyhunter,
Sorry but that's not enough, I'd want to set my own title, maybe ues a non cancelable progressDialog, etc...
Again, passing our own dialog would be fine.

**Comment by spyhunter99** [comment]
hmmk, i don't have a lot of free time at the moment. Feel free to open a PR for this

**Comment by spyhunter99** [comment]
Maybe we can change cachemanager to just do the work and have the UI be optional. That may be a better solution

**Comment by spyhunter99** [comment]
@2ndGAB please check out the delta's with that commit and the example. if you're ok with it and it meets the needs (and hopefully future needs) and the build passes, i'll merge it

**Comment by 2ndGAB** [comment]
I saw that you added a boolean to not use ant UI.
Ok, that could be useful but the problem is that prevent to have any progress.
So, would it be possible to pass our ProgressDialog as parameter.
If this parameter is null, you use your ProgressDialog, if the parameter is non null, you use our ProgressDialog with our title, message, etc..

**Comment by spyhunter99** [comment]
Check out the example to,  it's a custom ui with progress

**Comment by 2ndGAB** [comment]
Ok I check it today

**Comment by 2ndGAB** [comment]
Interesting.
Maybe a `callback.publishProgress()` could be interesting as well.

**Comment by 2ndGAB** [comment]
Just a question; I commented out `compile 'org.osmdroid:osmdroid-android:5.2@aar'` and I've added osmdroid-android (#315) as module.

I've cleaned up the project but I got the error:

    Error:Execution failed for task ':app:processDebugResources'.
    > Error: more than one library with package name 'org.osmdroid.library'

What did I miss?

**Comment by 2ndGAB** [comment]
Hi Spyhunter99,
I've implemented it and for me everything is ok.
Many thanks!!

**Comment by spyhunter99** [comment]
merged
