### ISSUE TITLE
Polyline disappear RecyclerView scrolling

### ISSUE THREAD

**Issue by DeveloperC4P** [osmdroid/osmdroid#316]
I add a map view inside RecyclerView item and when i scroll up and down 
If the onBindViewHolder(...) method is called will draw the route properly but if you scroll up and down and that method is not called cos the view is not needed to redraw, the Polyline which show the route will just disappear. 
Here i let the pice of code and the Log that show when a item is draw or not. 
All the 100% of times that the onBindViewHolder is called draw it correctly. 
Some idea how to deal with that issue? Thanks in advance :)

```
public void onBindViewHolder(RecyclerView.ViewHolder holder, int position){
Log.d(MyApp.DEBUG_TAG,"onBindViewHolder position="+position); //Here I can see when the map card is redrawed or not when scrolling.

        ICardRecyclerAdapter listener = holder instanceof ICardRecyclerAdapter ?
                (ICardRecyclerAdapter) holder : null;
        if (listener != null) {
            listener.onBindViewHolder(data.get(position));
        }
}
```

**Comment by spyhunter99** [comment]
Would it be possible to get a more complete example? Perhaps you can fork osmdroid and recreate the issue with the sample application?

**Comment by DeveloperC4P** [comment]
I found the reason and seems to be the MapView detach method called when is detach from the window.
With a workaround I manage to solve it. Here I let an example how to solve it. I hope that helps to others.

That code is from my RecyclerViewAdapter 

```
@Override
    public void onViewAttachedToWindow(RecyclerView.ViewHolder holder) {
        super.onViewAttachedToWindow(holder);
        if(holder instanceof RouteCardView){
           //Here i just call myself the onBindViewHolder from the holder.
        }
    }

    @Override
    public void onBindViewHolder(RecyclerView.ViewHolder holder, int position) {
        Log.d(TAG,"onBindViewHolder position="+position);
        if(holder instanceof RouteCardView) return; // RouteCardView is handled onViewAttachedToWindow
        ICardRecyclerAdapter listener = holder instanceof ICardRecyclerAdapter ?
                (ICardRecyclerAdapter) holder : null;
        if (listener != null) {
            listener.onBindViewHolder(data.get(position));
        }
    }

```

**Comment by spyhunter99** [comment]
Cool, grad you solved it. Maybe one day we'll work up an example for the sample app using this code and a recycler

**Comment by spyhunter99** [comment]
#588 #568 related tickets
