### ISSUE TITLE
The window when setFocusItemsOnTap?

### ISSUE THREAD

**Issue by Schattenklinge1** [osmdroid/osmdroid#317]
Having mapView.setFocusItemsOnTap(true);
How do I change the font size and the windows size? When trying out on the osmdroid's provided samples, it is big enough, however mine is too small and barely readable, how do I fix it? 
I've been looking into those samples and studying them, but couldn't find any code or references, which indicates where I am configuring that. Thanks in advance!

Talking about this info window, just for clearance...

![screenshot_2016-05-28-00-24-28-1](https://cloud.githubusercontent.com/assets/12400742/15622617/c6d5f25e-246a-11e6-97a5-b584e31bdd0f.png)

**Comment by spyhunter99** [comment]
See org.osmdroid.views.overlay.ItemizedOverlayWithFocus. There's a number of protected static variables that represent how it's drawn. Extend the class with your own and override the values

**Comment by Schattenklinge1** [comment]
Hi, thanks for this information, can you provide code to show how this could be accomplished? As far as I can see, they are all finals, so I cant just override them. I have my own Itemized things which extends ItemizedOverlayWithFocus, and now?

**Comment by spyhunter99** [comment]
I think i'll just make setters for all of the variables, that way you can configure them on a per marker basis.

**Comment by spyhunter99** [comment]
merged to develop, see if that you meets your needs. You can also look at the "Marker" class, which has more options

**Comment by spyhunter99** [comment]
operation timeout. reopen if this is still an issue for you
