### ISSUE TITLE
MapTileProviderBasic leaks

### ISSUE THREAD

**Issue by snowle0pard** [osmdroid/osmdroid#318]
Thanks for last issues.Now , i come to another problem.MapTileProviderBasic  cause memory leaks occasionally. I guess  it is because the tile is unreachable or the tile is broken.
Here the code i set :
    private void setTiles( )
    {
        mMapView.setTileSource(
                new GoogleTileSource( GoogleTileSource.NAME, 1, 20, 256 ) );
        MapTileProviderBasic _mapTileProviderBasic =
                new MapTileProviderBasic( getApplicationContext( ) );
        _mapTileProviderBasic.setTileSource(
                new TianDiTuTileSource( TianDiTuTileSource.NAME, 1, 20, 256 ) );
        mTianDiTuTilesOverlay = new TilesOverlay( _mapTileProviderBasic, getApplicationContext( ) );
        mTianDiTuTilesOverlay.setLoadingBackgroundColor( Color.TRANSPARENT );
        mTianDiTuTilesOverlay.setLoadingLineColor( Color.TRANSPARENT );
        mMapView.getOverlays( ).add( mTianDiTuTilesOverlay );
    }

   @Override
    protected void onDestroy( )
    {
        super.onDestroy( );
        mTianDiTuTilesOverlay.onDetach( mMapView );
        mEyeMapLocationClient.onDestroy( );
        mMapView.onDetach( );
        mTianDiTuTilesOverlay = null;
    }

![s60528-194819](https://cloud.githubusercontent.com/assets/11714210/15627146/86c7deea-250d-11e6-918f-afce241172d5.jpg)
![Uploading S60528-194835.jpg…]()

**Comment by spyhunter99** [comment]
if you can identify where the leak is or open a PR, we can fix it.

**Comment by snowle0pard** [comment]
![885cde44-9ab9-4089-9188-bfc98c3e4b9a](https://cloud.githubusercontent.com/assets/11714210/15628123/0131b890-252c-11e6-9232-9243d0a38fe9.png)

**Comment by snowle0pard** [comment]
Dose it  help?

**Comment by spyhunter99** [comment]
Not really, is this saying that the LRU cache is the source?

**Comment by snowle0pard** [comment]
I has no idea! Maybe ,i need more time to go deep into the source code.

**Comment by spyhunter99** [comment]
If it's related to LRU, that might make sense. We can had some explicit
hooks to purge that at shutdown/detach. Eventually, everything the LRU
cache gets purged

**Comment by spyhunter99** [comment]
I can add an explicit LRU purge on detach. that may fix it

**Comment by spyhunter99** [comment]
Fix committed to branch bug/#318, @snowle0pard would you be willing to test with the same tool that you're using? Esscentially, you'd have to check out the branch, build it locally, then copy the output aar and use that in your project instead of however you're doing it now.

**Comment by snowle0pard** [comment]
I open two PR for that(Hopefully, i make it right).
It seem passing the wrong context will cause that leaks. I change the context for MapTileProviderBasis and the TileOverlay from ApplicationContext to mapView's context ,my code work much better for a while. Then after changing some code, the problem keep showing up. I need to test more.

**Comment by snowle0pard** [comment]
@spyhunter99  I write a demon for testing it .[https://github.com/snowle0pard/OsmDroidLeaksTestDemon.git](url)
It can tell that it is the tile download request cause the leaks.I try to put the httpURLconnections to a list and disconnect the remain httpURLconnections when  detaching the activity,but it doesn't make much chang. Now ,I wonder if using the EventBus to refresh the map will be better instead of handler.

**Comment by spyhunter99** [comment]
I just fix a minor issue on branch 318. can you run it through your test again?

**Comment by snowle0pard** [comment]
I have been tryed these codes before,it cound not solve the problem!

**Comment by spyhunter99** [comment]
I was able to fix the issue with the LRU Caching not getting purged, which helped a lot. The sample application also had a number of memory leak issues which I'm working on now. I think a lot of the issues is related to Bitmap and the recycle method

**Comment by spyhunter99** [comment]
I think I found it. Hang on

**Comment by spyhunter99** [comment]
What API was your test ran on? The sample app doesn't appear to exhibit the same issue that your are describing. I have see this issue before on older versions, but I'm not sure if it's still an issue and on what API level it was on. My issue was seen on API 19 and 23. using osmdroid 5.1 give or take

**Comment by spyhunter99** [comment]
I ran into a similar issue with leak canary complaining when the map was visible and the screen was turned off and on again.

**Comment by snowle0pard** [comment]
sorry for such a long time to reply,but i was busying with some other project!
My issue was seen on API 15 and 23,using osmDroid 5.2. the olders seem to has it too. And My MapActivity add location listener,sensor listener et, once it leaks ,the app will crash vary easily. I think it also connect with the Network Quality.

**Comment by spyhunter99** [comment]
are you creating the map view via xml or programmatically? your link for the test daemon is a 404

**Comment by snowle0pard** [comment]
you could reach my demon via copying the address to the browser's address bar;I has no idea why.
My map is created via xml.and i can check the onDetach() is called.

**Comment by spyhunter99** [comment]
Ahh got it, it was a minor type on the markdown for the link. cloning it now, i'll see what i can do

**Comment by spyhunter99** [comment]
well i got your example to work on api 15, it works and is stable. Hasn't crashed yet. Haven't seen anything in the logs to indicate the leak

**Comment by spyhunter99** [comment]
works fine on api 23, as long as you explicitly enable the permissions

**Comment by snowle0pard** [comment]
Technically speaking ,the demon will not crash! Its memory just increase gradually.Considering of your Network Quality,you may not reapear the case.can you set your phone to 2g network.

**Comment by spyhunter99** [comment]
@snowle0pard after it runs through one cycle and get the tiles, it's loaded from the cache afterwards, then network connectivity does not make a different after the first run. Then starting it clean (rm -rf /sdcard/osmdroid) with the avd set to edge network, it still runs just fine.

This is testing with master which has had a lot of work done recently to resolve memory leaks on an API 15 avd.

To replicate my setup, clone osmdroid on branch master. run "gradlew install"

Then edit your root build.gradle to add "mavenLocal()" to the repositories
Then edit your "app" build.gradle and change the dependency to
`compile 'org.osmdroid:osmdroid-android:5.3-SNAPSHOT@aar'`

Please give it a try on whatever setup you have, because I can't replicate it here.

**Comment by spyhunter99** [comment]
One last question, how long did you have run it to notice the increased memory allocation?

**Comment by snowle0pard** [comment]
![g920v](https://cloud.githubusercontent.com/assets/11714210/16718630/516b9962-4754-11e6-8566-cb56e8af273f.png)

**Comment by snowle0pard** [comment]
![920v](https://cloud.githubusercontent.com/assets/11714210/16718654/843a9ba4-4754-11e6-9210-abc874409990.png)

**Comment by snowle0pard** [comment]
![m356](https://cloud.githubusercontent.com/assets/11714210/16718657/950d72bc-4754-11e6-8641-887a0af8893f.png)

**Comment by spyhunter99** [comment]
looks pretty stable...

**Comment by snowle0pard** [comment]
it leaks once.the second image.

**Comment by spyhunter99** [comment]
what were the circumstances for the 2nd image? was the app resumed by chance?

**Comment by snowle0pard** [comment]
Actually,the demon can easily check the leaks before.The 2nd image just show up for one time now,nothing special.Did you do anything to improve the code in the repositories "compile 'org.osmdroid:osmdroid-android:5.2@aar' " And one thing you should know there is a "great wall" between you and me.

**Comment by spyhunter99** [comment]
Yes, you want to run 5.3-SNAPSHOT, see the comment above for instructions.

**Comment by InI4** [comment]
Note: There might be some minor issue with above setup. On my machine I get a ...5.3-SNAPSHOT-debug.aar file which I need to rename by hand, to allow my apps gradle to pick it up.

**Comment by spyhunter99** [comment]
@snowle0pard any luck?

**Comment by spyhunter99** [comment]
Fixed in 5.4
