### ISSUE TITLE
Problem with BoundingBoxE6.contains()

### ISSUE THREAD

**Issue by 2ndGAB** [osmdroid/osmdroid#319]
Hello,

I have the following `BoundingBoxE6`:

    N:44916064; E:5040992; S:44880091; W:4990209

And the following `GeoPoint`:

    44916064,4990209,0

So this point is the NW corner but boundingBoxE6.contains(geoPoint) returns false.

It seems to be incorrect no?

**Comment by spyhunter99** [comment]
Is the point really within the bounds, or on the bounds? there's probably an argument either way

**Comment by 2ndGAB** [comment]
Effectively, that's a question..., maybe it's not so important, just to clarify.

**Comment by spyhunter99** [comment]
Maybe another method that does >= <=, meaning it's either within the bounds or on the bounds exactly?

**Comment by 2ndGAB** [comment]
Maybe it's better to consider that the bounds belong to the area, but it's just my point of view....

**Comment by spyhunter99** [comment]
merged
