### ISSUE TITLE
Maven based builds no longer build

### ISSUE THREAD

**Issue by spyhunter99** [osmdroid/osmdroid#321]
google updated the SDK again...

```
[ERROR] Failed to execute goal on project osmdroid-third-party: Could not resolve dependencies for project org.osmdroid:osmdroid-third-party:aar:5.3-SNAPSHOT: Failed to collect dependencies at com.google.android.gms:google-play-services:jar:[27,): No versions available for com.google.android.gms:google-play-services:jar:[27,) within specified range -> [Help 1]
```

**Comment by spyhunter99** [comment]
Ref: https://github.com/simpligility/maven-android-sdk-deployer/issues/295

**Comment by ChuyingHe** [comment]
i have the save problem, did you fix it??

**Comment by spyhunter99** [comment]
uhh no. thus the issue is still open. it's not an osmdroid issue, but a larger issue that google has. It'll take time for the maven android folks to sort it out. use gradle in the time being

**Comment by spyhunter99** [comment]
so partial solution. you can now run `gradle install` which will publish the aar's to maven local. Then in your app, you can add mavenLocal to the repo list, then include the library as normal

**Comment by spyhunter99** [comment]
current issues:
 - all the android support libraries are missing/not available
 - gmaps and gservices are missing too

**Comment by spyhunter99** [comment]
even though i love the effort, the maven android plugin just doesn't have the support it needs from the ide community. since we've solved all the publishing issues with gradle fury, there's little need to keep this ticket open.
