### ISSUE TITLE
Display layout complete?

### ISSUE THREAD

**Issue by 2ndGAB** [osmdroid/osmdroid#324]
Hello,

What event to use to call `zoomToBoundingBox()` or `showInfoWindow()` ?

I currently use `addOnFirstLayoutListener()` but this event is trigged too early to allow to given methods to work properly.

Is there an event telling the layout is ready? Something like `onMapReady()` in GoogleMap API.

**Comment by spyhunter99** [comment]
That's all we have the moment. I'm surprised that it's not working correctly for you. Open a PR if you think you have a solution for it. I'm not too familiar with the initial life cycle

**Comment by 2ndGAB** [comment]
I have no solution but calling these functions in `addOnFirstLayoutListener()` doesn't do anything. :-(

**Comment by spyhunter99** [comment]
Have you tried onResume in your app?

the javadocs for onLayout is `Called from layout when this view should assign a size and position to each of its children.`

i'd guess that moving the callback from onLayout to the first onDraw might do the trick

**Comment by spyhunter99** [comment]
I just whipped up an example for the sample app. OnFirstLayout definitely works fine for zoomToBoundingBox(), post a code example if you can

**Comment by 2ndGAB** [comment]
Ok, I'll try to do that asap.
In my case I had to delay these calls by 1sec to get it working.

**Comment by spyhunter99** [comment]
It's possible it's a device specific thing or an os version specific thing

**Comment by 2ndGAB** [comment]
Hi Spyhunter99,
[Here](https://github.com/2ndGAB/MyZoomToBoundingBoxTest) is a very simple example to show the problem with `ZoomToBoundingBox()`.

**Comment by MKergall** [comment]
@2ndGAB I tried the OnFirstLayoutListener solution: it works fine for me! 
Like spyhunter, I'm surprised it doesn't works for you. 

Try with a debug session?

**Comment by 2ndGAB** [comment]
Very strange as I get the same problem on different devices.
Did you try the project suggested [here](https://github.com/2ndGAB/MyZoomToBoundingBoxTest)?

**Comment by MKergall** [comment]
I've not tried your project. However, making some experiments, I also got an issue: 
the addOnFirstLayoutListener could arrive too late in onCreate. 

So here is an implementation which seems to be OK: 

```
	BoundingBoxE6 mInitialBoundingBox = null;
	void setInitialViewOn(BoundingBoxE6 bb) {
		if (map.getScreenRect(null).height() == 0) {
			mInitialBoundingBox = bb;
			map.addOnFirstLayoutListener(this);
		} else
			map.zoomToBoundingBox(bb, false);
	}

	@Override public void onFirstLayout(View v, int left, int top, int right, int bottom) {
		if (mInitialBoundingBox != null)
			map.zoomToBoundingBox(mInitialBoundingBox, false);
	}

```

Then in onCreate, you can call: 
`setInitialViewOn(myBB);
`

**Comment by 2ndGAB** [comment]
Hi MKergall,
Yes! Seems to be OK.

**Comment by 2ndGAB** [comment]
Hi MKergall,
I try your implementation but I don't really see what problem it supposed to solve.

In my case, it always verify `(map.getScreenRect(null).height() == 0)` and so it calls `map.addOnFirstLayoutListener(this);` in the same timing as before. I don't see how it's suppose to delay to delay the call to `onFirstLayout()`.
So for me the only working solution is the next code:  

    @Override
    public void onFirstLayout(View v, int left, int top, int right, int bottom) {

            if (boundingBox != null) {

                final Handler handler = new Handler();
                handler.postDelayed(new Runnable() {

                    @Override
                    public void run() {
                        if (boundingBox != null) {
                            mMapView.zoomToBoundingBox(boundingBox, false);
                        }
                        endMarker.showInfoWindow();
                        mMapView.invalidate();
                    }
                }, 500);
            }
    }

**Comment by MKergall** [comment]
Did you try a debug session on "faulty" devices, stepping into map.zoomToBoundingBox? 
Issue is in Projection constructor. 

Do you have the same issue using the sample from @spyhunter99 ?
He is adding the listener in onActivityCreated, when you add it in onViewCreated.

**Comment by spyhunter99** [comment]
@2ndGAB ping, any updates on this?

**Comment by 2ndGAB** [comment]
Hi,
No,  @MKergall I'm almost sure it's not related to devices as I get the same problem on 3 différent ones.
I didn't know about @spyhunter99's sample so I didn't try to add the listener in onActivityCreated. I have a doubt on this solution but I could try.

**Comment by spyhunter99** [comment]
@2ndGAB are you good with this?

**Comment by jankalfus** [comment]
I too miss a function like this.

When I use the `RadiusMarkerClusterer` from osmbonuspack and use `setZoom` method of `MapView`, the `getWidth()` and `getHeight()` methods of `MapView` return 0. This messes up marker clustering - the markers are either not clustered at all, or clustered incorrectly, because `Projection` and thus bounding box are initialized incorrectly, with 0 width and height.

**Comment by spyhunter99** [comment]
@2ndGAB looking at your sample now. The primary difference is that your implementation registers the `addOnFirstLayoutListener` in `onViewCreated` whereas the one is the osmdroid sample app registers in `onActivityCreated`. Debugging now...

**Comment by spyhunter99** [comment]
making progress, i've got it narrowed down to the compass! comment out the "enable" statement and adding it to the map and you're up and running

**Comment by spyhunter99** [comment]
as a work around, add to the map and enable the compass over in your onFirstLayout listener and it should solve the problem

**Comment by spyhunter99** [comment]
in the mean time, i'll try to find a more elegant solution.
