### ISSUE TITLE
Tiles corrupted

### ISSUE THREAD

**Issue by commksam** [osmdroid/osmdroid#33]
Samsung Tab3 7in, TM-210, Androis 4.1.2

As soon as I zoom or pan, corrupted tiles appear on the screen (sometimes a negative version of the tile, sometimes a kind of random noise). After a few seconds the application freezes, then closes down.

Thanks for any hint.
JPB

**Comment by spyhunter99** [comment]
ping timeout. reopen if this is still an issue. not reproducible over here
