### ISSUE TITLE
Update mapquest tile provide to match their updated TOS and URL paths

### ISSUE THREAD

**Issue by spyhunter99** [osmdroid/osmdroid#332]

**Comment by 2ndGAB** [comment]
+1

**Comment by spyhunter99** [comment]
feel free to take it on, use the mapbox or bing source as an example

**Comment by darkwizzard** [comment]
There is an alternative to use mapbox sdk (map) or mapquest map sdk with osmdroid only using the gradle? Or, we need implement the service for that? And if we need implement it, how we can proceed?

**Comment by spyhunter99** [comment]
@darkwizzard, no idea what you are asking for. 

mapquest is still working at the moment...

**Comment by spyhunter99** [comment]
MapQuest direct access to open tiles ends 11 July 2016 - info on switching to leaflet

MapQuest will end direct access to open tiles on 11 July 2016. Access to open tiles will require a key and use of the open plug-ins for Leaflet.  Details and documentation are here:

https://developer.mapquest.com/documentation/leaflet-plugins/open

You will also need an account (and a key).  Free accounts support up to 15,000 transactions per month.  Sign up here:

https://developer.mapquest.com/

**Comment by spyhunter99** [comment]
@darkwizzard i understand what you were saying earlier. At this juncture, it's unclear whether or not it's possible for us to support mapquest anymore. Sounds a lot like they are discontinuing access to tiles via osm's url pattern. The Mapquest sdk is a whole another map engine (i think)

**Comment by darkwizzard** [comment]
@spyhunter99 .. Can we open a pull request for adding several vector tiles like mapzen, mapbox, or new mapquest map? .. because the old tiles are almost deprecated. i assume that we can use mapsforge to render the maps. [(#246)](https://github.com/osmdroid/osmdroid/issues/246).

I think that the mapquest sdk is forked from mapbox, but otherwise don't matter if we can support mapquest or no, the thing is support newest maps.

I consider it is most important.

**Comment by spyhunter99** [comment]
Go right ahead, however mapsforge is also under a different license, so it can't be in osmdroid-android. a separate library would be better or perhaps in the forge adapter library

**Comment by danipl** [comment]
Any solution, any tiles source... or something to do to the map to works again?

I have my app map offline right now...

**Comment by MKergall** [comment]
Effectively, MapQuest open tiles are not working anymore. Replaced by a message: "Direct tile access has been discontinued, bla bla bla". 

Moving to vector tiles (#249) would be great, but certainly a huge work. 

Until a solution is found, you can just change your app to use Mapnik tiles (osmdroid default provider).

**Comment by danipl** [comment]
Yeah!, I have been before testing the Tiles from TilesFactory, setting MapNick, it works fine, for the moment, its a good and fast solution.

**Comment by MKergall** [comment]
Well, I just had a look at https://developer.mapquest.com/documentation/leaflet-plugins/open
It looks like MapQuest is now closely linked to MapBox: their URL scheme is exactly the MapBox URL scheme. 
So if you register to MapQuest and get your AppKey, you can probably access it using the osmdroid MapBoxTileSource out of the box, setting the MapBoxMapId ("mapquest.streets-mb", or "mapquest.satellitenolabels") and accessToken (your AppKey) appropriately.

**Comment by spyhunter99** [comment]
https://b.tiles.mapbox.com/v4/mapquest.streets-mb/{Z}/{X}/{Y}@2x.png?access_token={token}

appears to be the pattern to use. the @2x bit changes the scaling of the returned image. After trying to implement this and getting a token from mapquest (which looks nothing like the token i sniffed via the browser), I'm getting
`IOException downloading MapTile: /1/0/1 : java.io.IOException: Received authentication challenge is null`

There must be something else I'm missing here.

**Comment by spyhunter99** [comment]
I got it!

Go to mapbox's site and get yourself an access token and use that for mapquest. Commit imminent with updated tile sources and examples
