### ISSUE TITLE
CacheManager based on GeoPoints List

### ISSUE THREAD

**Issue by 2ndGAB** [osmdroid/osmdroid#333]
Hello,

Currently `CacheManager` downloads tiles contained in a `BoundingBox`.
That's a good approach but if you develop an application for walking, cycling tours or similar, you can have a circuit of a quite large diameter and you will notice that the tiles in the center, mainly for high zoom levels, are unuseful.

This is because I propose to extend `CacheManager` to allow it to download the tiles covered by a `geoPoints` list and more, to also download the tiles between 2 `geoPoints` and a bit more again, the tiles immediately around the ones covered.  
That way, you can see the map a bit around you trip, which is quite cool.

The main benefit is that even for a quite large surface where the original `CacheManager` could download thousands tiles, the extended one will only download the necessary ones.

The code is [here](https://github.com/2ndGAB/WPCacheManager) and is of course completely free.
You can integrate it in your application in place of the original `CacheManager`, and OSMDroid team can freely replace `CacheManager` by this one if they are interested in.

This extended CacheManager is based on [feature315 commit](https://github.com/osmdroid/osmdroid/issues/315).

**Comment by spyhunter99** [comment]
So it's a path (list of points) and then it downloads tiles that covers a certain radius of the points? There's not too much document to understand what's going.

**Comment by 2ndGAB** [comment]
Hi spyhunter99,
I'll try to elaborate a bit more the readme.
But basically, the algorithm consider that you follow the path between 2 successive points in the list and download the 8 tiles around the one covered. 
That way, you won't have a point or a path close to a not mapped area.

**Comment by 2ndGAB** [comment]
[WPCacheManager documentation improved](https://github.com/2ndGAB/WPCacheManager)

**Comment by spyhunter99** [comment]
ok so where's the following methods....

- getCoordinatesFromMapTile
- Constants.OSM_MIN_ZOOM_FOR_DOWNLOADED_AREA
- Constants.EARTH_RADIUS (what unit of measure is this in?)

**Comment by 2ndGAB** [comment]
Hi spyhunter99,

Sorry for the mistakes. So I added constants `EARTH_RADIUS_IN_METER`

`OSM_MIN_ZOOM_FOR_DOWNLOADED_AREA` is now passed as parameter to `extendedBoundsFromGeoPoints()`

`getCoordinatesFromMapTile` is in the file line 80 !?!

**Comment by spyhunter99** [comment]
alright i did the work for you this time. Next time please follow the standard git procedures for submitting patches, which is 

1. Fork this project
2. git clone (your fork)
3. Make a branch for your changes
4. make and test your changes
5. open a pull request to osmdroid:master

**Comment by 2ndGAB** [comment]
Ok spyhunter99, thanks a lot
