### ISSUE TITLE
zoomToBoundingBox and zoomToSpan wrong zoom calculation

### ISSUE THREAD

**Issue by davemeier82** [osmdroid/osmdroid#334]
When the map is shown repeatedly `getBoundingBox()` returns a BB with positions in _different Worlds_. This leads to a wrong zoom.

E.g. when I just load the map without setting a zoom level or position then latitude is -180000000 for both points.
In this case`getLatitudeSpanE6()` returns 0. This leads to division by 0 in both methods.

One workaround is to zoom in before you call this methods: 
`setZoom(mapView.getMaxZoomLevel())`

**Comment by spyhunter99** [comment]
"shown repeatedly" do you mean when the you're zoomed out and the map wraps around and repeats multiple times?

**Comment by davemeier82** [comment]
> "shown repeatedly" do you mean when the you're zoomed out and the map wraps around and repeats multiple times?

exactly

**Comment by 2ndGAB** [comment]
could be related to [#324](https://github.com/osmdroid/osmdroid/issues/324) ?

**Comment by spyhunter99** [comment]
@monsieurtanuki isn't this resolved now?

**Comment by monsieurtanuki** [comment]
@spyhunter99 I fixed #683. Maybe this one is solved too but I didn't work specifically on it (and I'm not sure I understand how to reproduce the issue)

**Comment by monsieurtanuki** [comment]
Fixed by #329
