### ISSUE TITLE
Problem with zoomToBoundingBox()

### ISSUE THREAD

**Issue by anto2b** [osmdroid/osmdroid#337]
When I use _zoomToBoundingBox()_ method for display all points doesn't work.
Here is my code : 

```
@Override
    public void onCreate(Bundle savedInstanceState)
    {
        super.onCreate(savedInstanceState);

       // Here i get my differents points 
      BoundingBoxE6 boundingBox = new BoundingBoxE6(maxLat, maxLong, minLat, minLong);
      mapView.zoomToBoundingBox(boundingBox,false);
      mapView.invalidate();
    }
```

Thanks you for your help !

**Comment by spyhunter99** [comment]
what do you mean by "display all points"? what zoom level and what are the points you're feeding it?

**Comment by anto2b** [comment]
I have an Arraylist<Geopoint>. 
I would like to show on the screen all points visibiles (each point i added a marker)

**Comment by MKergall** [comment]
zoomToBoundingBox doesn't work in onCreate. 
This is a very old osmdroid issue. 
Root cause: when in onCreate, the mapview dimensions values are still null. They are defined during the first draw, "a little bit later". 

A workaround was to "wait a little bit". 

Alternative: define a OnFirstLayoutListener to the mapview and perform the zoomToBoundingBox inside?

**Comment by spyhunter99** [comment]
it's probable that the map isn't ready yet during onCreate, try a method
that's later in the lifecycle

**Comment by 2ndGAB** [comment]
Hi,
I don't agree MKergall [See this issue](https://github.com/osmdroid/osmdroid/issues/324)

**Comment by devemux86** [comment]
If I may help the discussion, related issue #22 existed a long time ago regarding map layout ready. There were two solutions:
- External via the `OnGlobalLayoutListener`, see https://github.com/osmdroid/osmdroid/issues/22#issuecomment-48467851.
- Internal by @kurtzmarc, which probably needs to include the `zoomToBoundingBox` too. e.g. see in [MapController.zoomToSpan](https://github.com/osmdroid/osmdroid/blob/master/osmdroid-android/src/main/java/org/osmdroid/views/MapController.java#L105) for the implementation.

**Comment by MKergall** [comment]
@2ndGAB effectively, this issue is redundant with #324.
