### ISSUE TITLE
Grant Mathew Kergall write access

### ISSUE THREAD

**Issue by spyhunter99** [osmdroid/osmdroid#338]
@neilboyd @kurtzmarc 

Recently, we merge a significant quantity of code from osmbonuspack into this library, which is maintained by @MKergall. I'm willing to bet it would make everyone's life a bit easier to grant him write access to osmdroid. This would most likely decrease maintenance time and probably make his life much easier. An added bonus would be to help cross pollenate new ideas between the projects. Just a suggestion since we don't have a formal process for voting in new members.

**Comment by neilboyd** [comment]
Of course! welcome to the club @MKergall 
I also made @spyhunter99 admin ;)
The permissions model in GitHub changed so I hope I didn't break anything.
