### ISSUE TITLE
CacheManager onTaskFailed()

### ISSUE THREAD

**Issue by 2ndGAB** [osmdroid/osmdroid#342]
Hi,

Could you please implement `onTaskFailed()` callback ?

        @Override
        protected void onPostExecute(final Integer errors) {
            if (showUI) {
                if (errors != 0) {
                    Toast.makeText(mCtx, "Loading completed with " + errors + " errors.", Toast.LENGTH_SHORT).show();
                }
                if (mProgressDialog.isShowing()) {
                    mProgressDialog.dismiss();
                }
            }
            if (callback != null) {
                try {
                    if (errors == 0) {
                        callback.onTaskComplete();
                    } else {
                        callback.onTaskFailed();
                    }
                } catch (Throwable t) {
                    Log.w(IMapView.LOGTAG, "Error caught processing cachemanager callback, your implementation is faulty", t);
                }
            }
        }

**Comment by spyhunter99** [comment]
done
