### ISSUE TITLE
Tile loading problem

### ISSUE THREAD

**Issue by janoferenczi** [osmdroid/osmdroid#345]
Hi all.
In the last couple of days I observed a strange bug.
When I`m zooming in or out the tiles are not loaded properly.
See the attached files.

On the logcat also this message appears:
"SkImageDecoder::Factory returned null" 

Thank you for your help.

![zoom_in](https://cloud.githubusercontent.com/assets/763092/16481489/34926ba2-3eb4-11e6-8302-4d560a25cb3f.png)
![zoom_out](https://cloud.githubusercontent.com/assets/763092/16481488/34924924-3eb4-11e6-9753-d4ad5c25217a.png)

**Comment by spyhunter99** [comment]
what version are you using? what tile source are you using?

**Comment by janoferenczi** [comment]
The version of OSMDroid is 5.1
Tile source is Mapnik.
Android version, All.

**Comment by spyhunter99** [comment]
is this only during the zoom in/out animation? are tiles loading ok normally (not pinching)?

did it behave differently in previous versions?

**Comment by janoferenczi** [comment]
It's not only on the zoom in/out animation. The problem persists when we swipe the map as well.
We were using only 5.1.

**Comment by janoferenczi** [comment]
Another thing. Till last week we did all the map related operations in the main activity, but the I exported all the map related functions(zoom, marker rendering, layers etc) into a manager class. This could be a problem?

**Comment by spyhunter99** [comment]
@janoferenczi no idea, try rolling it back to see if that's the problem

**Comment by spyhunter99** [comment]
any luck?

**Comment by janoferenczi** [comment]
Yes, 
In my manifest I tried to adept the permissions for android 6.0 and added android:maxSdkVersion="18" to the WRITE_EXTERNAL_STORAGE.

Thank you for your time.
