### ISSUE TITLE
MapView out of memory

### ISSUE THREAD

**Issue by HelloGalaxy** [osmdroid/osmdroid#35]
Hello, I created a MapView object in an activity. But I found out a terrible issue. After I have rotated the tablet many times, the MapView object always throws Out Of Memory exception. As the result, the activity is blocked or reflect slowly....

**Comment by spyhunter99** [comment]
if you programmatically construct the map view, then add it to the activity and don't clean it up on destroy, you may end up with a map view that doesn't get GC'd. @HelloGalaxy can you post the creation code?

**Comment by spyhunter99** [comment]
ping time out. reopen the ticket if you still have the issue. it sounds like you're not removing the created view on destory
