### ISSUE TITLE
Offline map display grid

### ISSUE THREAD

**Issue by LAzyOnline** [osmdroid/osmdroid#352]
When I use OSMDroid to show off line maps, I have a problem. The offline map shows the grid. My configuration is as follows:
 MapView mapView = (MapView) findViewById(R.id.map);
        mapView.setClickable(true);
        mapView.setBuiltInZoomControls(true);
        mapView.setMultiTouchControls(true);
        mapView.setUseDataConnection(true);
        mapView.setTileSource(TileSourceFactory.MAPQUESTOSM);
        GeoPoint BERLIN = new GeoPoint(52.516667, 13.383333);
        IMapController mapViewController = mapView.getController();
        mapViewController.setZoom(15);
        mapViewController.setCenter(BERLIN);
I have a slice tiles.zip, I put it in the /osmdroid directory under the SD card.But the map cannot be displayed.I try to decompression it. Then open the network, you can display a few slices (I have a very large slices ), and can only show that a few pictures. Zoom in, but this a few pictures to enlarge, will not be replaced by the corresponding zoom level of the map. I hope I can get your help, thank you.

**Comment by spyhunter99** [comment]
what does the contents of the zip look like?

**Comment by LAzyOnline** [comment]
A MapquestOSM directory folder inside the tiles.zip, folder inside a 15 level slicing folder, the folders name are 1, 2, 3, 15, each folder inside contains sections folder, to the number of names, slice folder contains, file slices is PNG format of. For example, the path to a slice of the level 15 file is: tiles.zip\MapquestOSM\15\17607\10748.png

**Comment by spyhunter99** [comment]
Well it looks right. What version of osmdroid? what os version?

**Comment by LAzyOnline** [comment]
Thank you for your reply. OSMdroid version is 5.2;OS version is 4.1.2 。 
If you can provide the email address, I can send Demo to you.

**Comment by spyhunter99** [comment]
alexoree at apache.org will work

**Comment by LAzyOnline** [comment]
I'm sorry. 
Osmdroid offline map need not need to configure the file. I have no configure file Demo.

**Comment by spyhunter99** [comment]
are you still having this issue?

**Comment by LAzyOnline** [comment]
Yes, I'm. Because I didn't solve the problem.

**Comment by spyhunter99** [comment]
I'm still not sure what the problem is. Can you record a video of it?

If your zip file only has tiles at zoom 15, then zooming past 15 would at first display "scaled" tiles, then as you pan the map, the grey grid. That's perfectly normal. If there's nothing to display, you get the grid.

**Comment by LAzyOnline** [comment]
Ok.
http://test.360guanggu.com/cjbook/source.png
This is the code screenshot.
http://test.360guanggu.com/cjbook/record.mp4
This is the record a video.

Thank you for your reply.

**Comment by spyhunter99** [comment]
The zip looks fine. Is there anything in logcat? It's probably a permissions issue

**Comment by LAzyOnline** [comment]
This is the logcat information screenshot. 
http://test.360guanggu.com/cjbook/logcat.png
but, I didn't find useful information from it.

**Comment by spyhunter99** [comment]
https://github.com/osmdroid/osmdroid/wiki/FAQ#debugging-tile-loading-issues

sorry, forgot to mention, turn on tile loading debugging. it should help produce more log output

**Comment by LAzyOnline** [comment]
There is my logcat information.
http://test.360guanggu.com/cjbook/logcat.txt

I found a issue, like this: http://test.360guanggu.com/cjbook/error.png
Is it a issue?

**Comment by spyhunter99** [comment]
Mapquest's tile source is by default set to a 'jpg' extension. Your files are .png, thus the error.

**Comment by LAzyOnline** [comment]
As you said, my problem is solved, thank you very much.
