### ISSUE TITLE
Polyline Path too large to render into a texture

### ISSUE THREAD

**Issue by 2ndGAB** [osmdroid/osmdroid#353]
Hello,

I'm creating a polyline of about 12kms, correctly displayed at zoom level 13 and 14 but for higher zoom level, the path is not displayed anymore and I indefinitely get the following message:

   W/OpenGLRenderer: Path too large to be rendered into a texture

Why? 
How to fix it please?

**Comment by MKergall** [comment]
Known issue: https://github.com/MKergall/osmbonuspack/issues/168

Turn HW acceleration off. No other way: OpenGL cannot handle large values.

**Comment by 2ndGAB** [comment]
Turn HW acceleration off ?? :-(((
Ok saw the issue.

**Comment by spyhunter99** [comment]
Just on the map view, not the whole app, that would be silly

**Comment by 2ndGAB** [comment]
well, I think that the map view is the one who need HW acceleration unfortunately.

**Comment by spyhunter99** [comment]
In either case, nothing we can do about it at the moment.

**Comment by 2ndGAB** [comment]
@spyhunter99 I think [this solution](http://fiskurgit.github.io/osmdroid_polyline_performance) is a good approach.
I'l give it a try.

**Comment by spyhunter99** [comment]
Nice find! Clipping at map bounds is critical

**Comment by spyhunter99** [comment]
It may be useful to include a similar algorithm in osmdroid. A clip to
bounds method. It be also apply to polygons too.

**Comment by MKergall** [comment]
Warning: Clipping at map bounds would be nice, but is not obvious. 

A "simple" optimization was made in PathOverlay: when the 2 points of a segment are outside the view, don't draw it. This solution is wrong, introducing numerous issues (glitches on segments), because there are various cases of a segment traversing the view even if both points are outside the bounds. 

The fiskur solution seems to be the same: "only render the points that will appear on screen". So as he says, he also get "occasional glitches". 

In addition, this simple optimization is not sufficient to avoid the "path too large" issue, because you can have a segment with one point inside the view, and the second point very far away. 

So, to be able to turn HW acceleration on, a real clipping on bounds seems necessary. 
It's really a pitty that Android/OpenGL doesn't provide that out of the box!

**Comment by 2ndGAB** [comment]
@MKergall . I'm going to give it a try in the next days and see how to optimize it.
Not drawing a segment is maybe better than not drawing anything at all but in case, it could be not so difficult to create an extra point on the bound for segment starting inside and going outside.

**Comment by MKergall** [comment]
@2ndGAB yes the good solution is to replace the "outside" point by a point on the bound. This is a real clipping. The difficulty is to calculate this point.

**Comment by 2ndGAB** [comment]
@MKergall. Yes, I have no precise idea at the moment.

**Comment by always-beta** [comment]
What I did was, have a subclass of Overlay, hold all the geopoints as a list, and inside draw(), skip drawing if both of the successive two points are outside of the bounds and also on the same side of the bounds (e.g: both on the left, both on the top), also skip drawing if the two geopoints projected to the same pixel (on small zoom levels a lot of points are projected to same pixels). It still needs to iterate all the points (extreme cases I have over 10k points) but can save a lot of drawing time.

**Comment by MKergall** [comment]
Good optimization - if you provide it, could be integrated. 
But it's not solving the "Polyline Path too large" error in all cases. 
Just one example: long line crossing the view, one point on the left, one the right, both outside the view. 
So you cannot switch HW acceleration on.

**Comment by MKergall** [comment]
Just an idea (not tested at all) - our key issue to switch HW acceleration on is a clipping issue. 

In MapView.dispatchDraw(final Canvas c), should we set the clipping rectangle of the View to the Canvas, using: c.clipRect(), before  calling onDraw on overlays?

Or is the Canvas clipping rect already set by Android framework?

**Comment by MKergall** [comment]
Bad news: Canvas clipping rect is already set to the View box. 
So it seems to have no effect on OpenGL renderer.

**Comment by kvoronov** [comment]
What about honest clipping in draw method of Polyline? And simplification of Polyline on some zoom levels? I had reached great performance and smooth behavior(~60fps in opposite to 5-10fps using Polyline), created different implementation of Polyline(I called it SmoothPolyline). It simplifies path on big zoom, rounding corners and making honest segment clipping, which make possible enable hardware acceleration everywhere(because clipped path not produces too large texture). I can make pull request if this feature is needed for someone.

**Comment by spyhunter99** [comment]
yes please!

**Comment by 2ndGAB** [comment]
@kvoronov I'd be interested to test it as I had no time to investigate in this problem.

**Comment by MKergall** [comment]
It's needed by all of us. 

Have you tried to implement this "honest clipping" on Polygons? Because they have the same issue, and if not available, this will prevent enabling HW acceleration ...

**Comment by shiroyagi** [comment]
Is it possible Path is not the best implementation for Polyline?  Vector graphics would seem more appropriate than a texture/bitmap and this should be possible with OpenGL.  Using GLSurfaceView would be a lot of effort however.

The [API Guide](https://developer.android.com/guide/topics/graphics/hardware-accel.html#tips) suggests modifying a Path too often will reduce performance and presumably this would apply to manual clipping in draw().  Perhaps Canvas.drawLines() isn't rendered with a texture and would work better?

**Comment by MKergall** [comment]
Canvas.drawLines() seems promising for Polylines. 
But issue will remain for Polygons...

**Comment by shiroyagi** [comment]
Have you tried Path.op(viewRect, INTERSECT) to perform the clip for Polygon?
Maybe performance could be improved over repeated clipping by partitioning and caching Paths for the Polygon and only drawing those that intersect the view?

**Comment by MKergall** [comment]
Yes, Canvas.drawLines() works with HW acceleration on! You can see implementation [here](https://github.com/MKergall/osmbonuspack/blob/master/OSMBonusPackTuto/src/main/java/com/example/osmbonuspacktuto/Polyline.java), and test it with OSMBonusPackTuto app. 

@shiroyagi Thanks a lot, this is a great improvement to osmdroid. 
@spyhunter99 Once tested, could you integrate this revised Polyline to osmdroid? (my attempts to push a PR do not work)

I will now look at Path.op(viewRect, INTERSECT) for Polygons. I'm less optimistic.

**Comment by shiroyagi** [comment]
Excellent, you beat me to it.

I don't know if it is worth trying drawLines() with duplicated points, instead of repeated drawLine().  With OpenGL a single call with an array is usually much more efficient than the equivalent number of single primitive calls.  You could make float[4*(n-1)] a class member to avoid repeated alloc and update it when the projection changes.  How significant this would be compared to the other rendering operations I couldn't say.

If Path.op() clip to view works, perhaps performance could be improved using the TileProvider API to generate and cache clipped images?

**Comment by MKergall** [comment]
Yes, Path.op(viewRect, INTERSECT) is a solution for Polygons! 
Implementation [here](https://github.com/MKergall/osmbonuspack/blob/master/OSMBonusPackTuto/src/main/java/com/example/osmbonuspacktuto/Polygon.java), and OSMBonusPackTuto  to test it. 

But with an important constraint: it requires API level 19 or above. 
So it doesn't work on my device, a Jelly Bean (10% market share) :-(

**Comment by spyhunter99** [comment]
i :heart: this thread

**Comment by MKergall** [comment]
(me too)

I just pushed a simple change on my Polygon implementation, to handle API level constraint: below API 19, we don't clip (and I don't switch HW acceleration on). 
Those Polygon and Polyline are tested OK on my old device and my recent emulator. 

@spyhunter99 What do you think? Could be integrated?

**Comment by spyhunter99** [comment]
@MKergall sure thing. I think i gave you write access to this repo. In which case you can make the change yourself.

**Comment by shiroyagi** [comment]
I've just been testing the drawLine() implementation of Polyline.java and can confirm that the line doesn't vanish at high zoom levels as it did with drawPath(). Unfortunately the performance as measured with the [GPU profiler](https://developer.android.com/studio/profile/dev-options-rendering.html) when panning is worse, both with and without hardware acceleration enabled (Android 5.1, Qualcomm MSM8960DT, 6400 points).  Generally it indicates there is too much time spent in onDraw() methods (blue, as below), and it is way above the 60fps line (without the Polyline drawn it is around 60fps without hardware accn, and 2x a fast with it).

drawLine with hardware acceleration:
![line-hw](https://cloud.githubusercontent.com/assets/8389325/24074854/a556113c-0c08-11e7-9863-23050132d286.png)

drawLine without hardware acceleration:
![line](https://cloud.githubusercontent.com/assets/8389325/24074853/a55508f0-0c08-11e7-8f4e-a4668f28d662.png)

drawPath with hardware acceleration:
![path-hw](https://cloud.githubusercontent.com/assets/8389325/24074855/a557084e-0c08-11e7-8912-4ba321034ba2.png)

drawPath without hardware acceleration:
![path](https://cloud.githubusercontent.com/assets/8389325/24074856/a5577702-0c08-11e7-8d47-f9cc5b584406.png)

I will try drawLines() with cached points.

**Comment by MKergall** [comment]
Did you compare current osmdroid Polyline implementation (without HW acc), versus the new Polyline (with HW acc)?

**Comment by shiroyagi** [comment]
Yes, those are the 4th and 1st pictures above respectively.

With drawLines() & HW accn it is looking better than all the above.  However drawLines() without HW accn is looking bad (solid blue).  I am seeing strange behaviour drawing multiple paths at some zoom levels so probably have a bug.  It seems the projection changes more often than I thought so caching points doesn't work.  At the moment I'm thinking it may be best to use drawLines() when HW is enabled, and the old drawPath() when not.

drawLines with hardware acceleration:
![lines-hw](https://cloud.githubusercontent.com/assets/8389325/24076115/39b9be24-0c21-11e7-9dc3-4c2a282d4807.png)

**Comment by shiroyagi** [comment]
Bug fixed and simple culling of line segments outside of the view gives reasonable performance with and without hardware acceleration.  Code [here](https://github.com/osmdroid/osmdroid/files/853325/Polyline.txt), I can create a pull request later if that helps?

drawLines with hardware accn and clipping:
![lines-clip-hw](https://cloud.githubusercontent.com/assets/8389325/24082363/48da856e-0cbc-11e7-9ca2-d61b94bfba0e.png)

drawLines without  hardware accn and clipping:
![lines-clip](https://cloud.githubusercontent.com/assets/8389325/24082368/59dd7966-0cbc-11e7-8f3e-130957c394b9.png)

**Comment by spyhunter99** [comment]
awesome thread, awesome work.

do any of these improvements still work map rotation?

**Comment by shiroyagi** [comment]
I haven't tested map rotation, but as the changes are to projected points in view coords it will hopefully be ok.  It would be good to test on different hardware and with a large screen (tablet).

**Comment by MKergall** [comment]
Map rotation is not good for Polygon: my clipping was too short. Fixed.

**Comment by MKergall** [comment]
@shiroyagi you will have the same issue with your Polyline clipping. 
Replace: mapView.getIntrinsicScreenRect(mClipRect); 
by: mapView.getScreenRect(mClipRect); 

And move this call before the for loop.

**Comment by shiroyagi** [comment]
Thanks, hopefully [this](https://github.com/osmdroid/osmdroid/files/869309/Polyline.txt) will be better.

**Comment by spyhunter99** [comment]
@MKergall i just tested out the changes that you linked to. I still have issues with polygons disappearing using the sample apps > More Samples > Data> Osmpath demo. Center over the red square and zoom in. I think it disappears at either 19 or 20.

What is your test case for the polygon fixes?

**Comment by MKergall** [comment]
My test case is in the [OSMBonusPack tuto](https://github.com/MKergall/osmbonuspack/blob/master/OSMBonusPackTuto/src/main/java/com/example/osmbonuspacktuto/MainActivity.java). 

Note that your device MUST have at least KitKat to have Polygon working with HW acceleration on. 
So my test: 
```
boolean hwAccelerationOK = com.example.osmbonuspacktuto.Polygon.SDKsupportsPathOp();
Configuration.getInstance().setMapViewHardwareAccelerated(hwAccelerationOK);

```

**Comment by spyhunter99** [comment]
I'm API 23. It "works" but only up to zoom 20 i think. I'll test with your
example

**Comment by MKergall** [comment]
@jankalfus What is the API level of your device?

**Comment by jankalfus** [comment]
@MKergall It's 22.

**Comment by MKergall** [comment]
I wonder if @TargetApi(Build.VERSION_CODES.KITKAT) is "true" when API level is higher than KITKAT. 
If you can give it a try, adding a logcat inside the clip method. Or I will try myself with an emulator.

**Comment by jankalfus** [comment]
The annotation is not used at run time, but only for linting AFAIK. I wonder in what way it might be related to the issue?

**Comment by spyhunter99** [comment]
I thought that targetapi was a runtime annotation which would be replaced
at runtime with noop if the condition doesn't match

**Comment by jankalfus** [comment]
Well, even if it did, it's not the problem :) The problem is that the crop method is called and that it somehow incorrectly crops the polygon, resulting in the polygon filling the whole screen. I would love to fix it myself, but I unfortunately don't understand what the method is exactly doing.

**Comment by MKergall** [comment]
the method clips the polygon to the mapview visible area.

**Comment by MKergall** [comment]
I tested with the same KML. I didn't got the issue you describe, but another one: the clipping is incredibly slowing down the drawing. Even with just 1 polygon. At least on emulator. 
I don't see any solution currently.

**Comment by shiroyagi** [comment]
Is it possible Path.Direction is inconsistent between the polygon and rectangle?

**Comment by spyhunter99** [comment]
where are we at with this? The last commit i think was to fix poly line with acceleration turned on

**Comment by MKergall** [comment]
"The last commit i think was to fix poly line with acceleration turned on"
=> Yes. 
And then, we also discovered that the solution for Polygon is not usable (too slow).
