### ISSUE TITLE
some offline tiles not immediately displayed

### ISSUE THREAD

**Issue by 2ndGAB** [osmdroid/osmdroid#354]
Hello,

I use the CacheManager and so I scroll a part of the map **offline** (the concerned area is downloaded of course).
I notice that sometimes, some tiles are not immediately displayed and the map looks like [here](http://i.imgur.com/XO4fWZK.png).

The behavior is a bit strange, sometimes the missing tile will come few seconds later, sometimes never and I have scroll the map and come back to the previous position to see it displayed.

**Comment by spyhunter99** [comment]
i just merged in #213 it may resolve this issue. consider testing your scenario off of osmdroid/master

**Comment by 2ndGAB** [comment]
Cool spyhunter99, I'm a bit under the water level at the moment..... I'll see it ASAP

**Comment by miguel-porto** [comment]
Hi,
I have the very same issue with the current version, often I have to zoom out / in to trigger the missing tiles being displayed. The typical situation when this happens is when the tiles were downloaded at a lower zoom level than the zoom level that the user is viewing, and the user moves the map by panning only. The tiles only appear after the user zooms out to the level at which they were downloaded. After this, I can zoom in again and they're still there, but they don't appear if they are "reached" by panning only.

**Comment by spyhunter99** [comment]
@2ndGAB is still an issue for you?

**Comment by 2ndGAB** [comment]
@spyhunter99, I don't think so, I didn't really pay attention to it these last weeks because I'm very busy on other problems but I don't remember having noticed it.

**Comment by spyhunter99** [comment]
5.6 should be cut soon, in the mean time, try building master and using that in your app. it should fix the issue. reopen if it's still a problem

**Comment by 2ndGAB** [comment]
ok thanks a lot
