### ISSUE TITLE
Unable to decode stream: java.io.FileNotFoundException

### ISSUE THREAD

**Issue by pawelchmara** [osmdroid/osmdroid#355]
Hi all,

When application with osmdroid maps is started first time I get error 'Unable to decode stream: java.io.FileNotFoundException' and maps tiles are not shown. After kill and start again application map works proper.

In the AndroidManifest file permission to WRITE_EXTERNAL_STORAGE is set. Mobile phone has own internal storage and sd card is not inserted. This issue occurs on Android 6.0.1 .

There are logs from android:

```
07-20 10:53:02.569 15124-15124/... I/OsmDroid: Tile cache increased from 9 to 30
07-20 10:53:02.654 15124-15265/... E/BitmapFactory: Unable to decode stream: java.io.FileNotFoundException: /storage/emulated/0/osmdroid/tiles/Mapnik/16/35870/21902.png.tile: open failed: EACCES (Permission denied)
07-20 10:53:02.654 15124-15265/... D/OsmDroid: /storage/emulated/0/osmdroid/tiles/Mapnik/16/35870/21902.png.tile is an invalid image file, deleting...
07-20 10:53:02.654 15124-15266/... E/BitmapFactory: Unable to decode stream: java.io.FileNotFoundException: /storage/emulated/0/osmdroid/tiles/Mapnik/16/35868/21902.png.tile: open failed: EACCES (Permission denied)
07-20 10:53:02.654 15124-15266/... D/OsmDroid: /storage/emulated/0/osmdroid/tiles/Mapnik/16/35868/21902.png.tile is an invalid image file, deleting...
```

Thanks for help!

**Comment by spyhunter99** [comment]
#329 related. In this case, you'll probably have to discover the writable mount points, then set the that path for the osmdroid tile cache path. What version of osmdroid are you using?

**Comment by pawelchmara** [comment]
I'm using version 5.2 from gradle repository.

**Comment by spyhunter99** [comment]
What kind of device is this?

**Comment by pawelchmara** [comment]
It's Samsung S3 (GT I9300) with Cyanogenmod 6.0.1. Maybe that's the problem...

**Comment by spyhunter99** [comment]
Oh, did you grant the app permission for write storage? Android 6 has a new permissions structure. The sample osmdroid app has some copy and past code for requesting permissions that should be ran before loading the mapview

**Comment by spyhunter99** [comment]
It's possible that Environment.getExternalStorageDir() is returning a read only partition. If that's the case, there's probably another mount point that can be used instead, which you would set before the mapview is created.

see this
https://github.com/osmdroid/osmdroid/blob/master/osmdroid-forge-app/src/main/java/org/osmdroid/forge/app/StorageUtils.java

it should give you all writable mount points which can you use to set the cache directory for osmdroid.
The other option would be to use your application's private storage folder for map data.

In both case, reference this class
https://github.com/osmdroid/osmdroid/blob/master/osmdroid-android/src/main/java/org/osmdroid/tileprovider/constants/OpenStreetMapTileProviderConstants.java

setCachePath(String dir)
setOfflineMapsPath(String dir)

**Comment by spyhunter99** [comment]
@pawelchmara any updates?

**Comment by spyhunter99** [comment]
cache storage location was reworked for v5.6, please see the upgrade guide in the wiki for more information,  then retest your scenario

**Comment by spyhunter99** [comment]
operation timeout. please reopen or comment back if you have further questions
