### ISSUE TITLE
HERE WeGo Maps - Tile Provider

### ISSUE THREAD

**Issue by eduatletico** [osmdroid/osmdroid#360]
Any chance to include HERE WeGo Maps as tile provider?

**Comment by spyhunter99** [comment]
possibly, would require investigating their tile usage policy, which is missing from their terms of service and  we'd need to fine sdk information, which is missing. The URL pattern is non standard and appears to use 4 parameters, and several id's.

**Comment by eduatletico** [comment]
Actually, I'd try to create with OnlineTileSourceBase using

new String[] { "http://1.aerial.maps.cit.api.here.com/maptile/2.1/maptile/newest/hybrid.day/{z}/{x}/{y}/256/png8?app_id=MY_APP_ID&app_code=MY_APP_CODE&lg=pt-BR",
"http://2.aerial.maps.cit.api.here.com/maptile/2.1/maptile/newest/hybrid.day/{z}/{x}/{y}/256/png8?app_id=MY_APP_ID&app_code=MY_APP_CODE&lg=pt-BR",
"http://3.aerial.maps.cit.api.here.com/maptile/2.1/maptile/newest/hybrid.day/{z}/{x}/{y}/256/png8?app_id=MY_APP_ID&app_code=MY_APP_CODE&lg=pt-BR",
"http://4.aerial.maps.cit.api.here.com/maptile/2.1/maptile/newest/hybrid.day/{z}/{x}/{y}/256/png8?app_id=MY_APP_ID&app_code=MY_APP_CODE&lg=pt-BR" }

But, I don't know what is the 'x' and 'y'. And, apparently, 'z' is the zoom level.

**Comment by 2ndGAB** [comment]
@eduatletico x and y are certainly the coordinates as explained [here](http://www.maptiler.org/google-maps-coordinates-tile-bounds-projection/) I suppose

**Comment by eduatletico** [comment]
Man! I think that's the answer! I'll try that.. Thanks @2ndGAB ! 
I'll post here later.

**Comment by eduatletico** [comment]
> @eduatletico x and y are certainly the coordinates as explained here I suppose.
Maybe try http://1.aerial.maps.cit.api.here.com/maptile/2.1/maptile/newest/hybrid.day/11/1046/1311/256/png8?app_id=MY_APP_ID&app_code=MY_APP_CODE&lg=pt-BR

@2ndGAB You are right! But, I have another question... How can I get the visible area from user's screen (and zoom, obviously) and "make" the map with parts of tiles?

**Comment by spyhunter99** [comment]
done and done. enjoy.

Don't use our key in your implementation.

**Comment by 2ndGAB** [comment]
@eduatletico You cannot get only a part of tile; the world map is cutted out in png squares of 256x256 or 512x512 maybe (my knowledge cannot give you more info about the png size) and depending on the zoom level, these pngs cover a corresponding earth surface.
So if at a given zoom level you want to see the area given by the red square in your image, you will mandatory download tiles covering the blue rectangle in your case.
Maybe vector tiles can allow you to have tiles cover your red square, maybe by using float zoom level. I cannot say...
You could have more info [here](http://www.maptiler.org/google-maps-coordinates-tile-bounds-projection/).
