### ISSUE TITLE
TileSourceFactory.MAPQUESTOSM

### ISSUE THREAD

**Issue by muhammad-naderi** [osmdroid/osmdroid#363]
starting July 11th, MapQuest needs apikey to respnd,

[Modernization of MapQuest results in changes to direct tile access](http://devblog.mapquest.com/2016/06/15/modernization-of-mapquest-results-in-changes-to-open-tile-access/)

how can I pass the api key ?

**Comment by spyhunter99** [comment]
It would be nice if mapquest gave us some documentation on this, but sadly i haven't found any. And this is a duplicate ticket

**Comment by spyhunter99** [comment]
#332

**Comment by spyhunter99** [comment]
duplicate
