### ISSUE TITLE
USGS_TOPO "HTTP response: Not Found"

### ISSUE THREAD

**Issue by commonsguy** [osmdroid/osmdroid#364]
Given code like this:

```java
    MapView map=(MapView)findViewById(R.id.map);

    map.setTileSource(TileSourceFactory.USGS_TOPO);
    map.setMultiTouchControls(true);
    map.getController().setZoom(18);
    map
      .getController()
      .setCenter(new GeoPoint(40.76793169992044, -73.98180484771729));
```

you get a list of messages like this:

```
W/OsmDroid: Problem downloading MapTile: /18/77203/98509 HTTP response: Not Found
```

and the map does not display. Using `MAPNIK` works fine, so the issue is not with osmdroid integration in general -- the issue seems to be unique to `USGS_TOPO`. This is with `org.osmdroid:osmdroid-android:5.2@aar`, tested on a Nexus 5 running Android 6.0.

[This sample app](https://github.com/commonsguy/cw-omnibus/tree/master/OpenStreetMap/osmdroid/Basic) reproduces the problem.

**Comment by spyhunter99** [comment]
Good find, looks like they updated the base URL to this
http://basemap.nationalmap.gov/arcgis/rest/services/USGSTopo/MapServer/tile/
