### ISSUE TITLE
HTC 10 shows grey tiles

### ISSUE THREAD

**Issue by jeanboum** [osmdroid/osmdroid#365]
The android app with osmdroid functioned well on several android devices.
But not on a HTC 10. This devices shows grey tiles.
Does anybody knows why?

**Comment by spyhunter99** [comment]
It's possible there's no writable directory returned for
getExternalStorageDir(). This can be resolved by telling osmdroid to use a
different directory for tile storage. See
OpenStreetMapTileProviderConstants (or something like that)

**Comment by spyhunter99** [comment]
what map source? If it's mapnik, perhaps you're bitten by this
https://github.com/osmdroid/osmdroid/issues/366

**Comment by spyhunter99** [comment]
check the logcat for any hints

**Comment by jeanboum** [comment]
Dear spyhunter,

Thanks for your suggestions. I will look at that
(sorry for my delay).
I let you know.

**Comment by jeanboum** [comment]
Dear spyhunter

I have added;
org.osmdroid.tileprovider.constants.OpenStreetMapTileProviderConstants.setUserAgentValue(BuildConfig.APPLICATION_ID);
since then the most androids shows the tiles, but still not on a htc10.

(I have also added an extra userpermission in the manifest: READ_EXTERNAL_STORAGE)

the logcat gives me no extra information.

Hopely you have other suggestions.

**Comment by spyhunter99** [comment]
Try setting the following

````
OpenStreetMapTileProviderConstants.DEBUGMODE=true;
OpenStreetMapTileProviderConstants.DEBUG_TILE_PROVIDERS=true;
````

That should give you more debug output. It's probably a permissions thing. On certain devices, getExternalStorageDir returns a read only mount point. In that case, you'll need to redirect the tile cache to another location that is writable.

Long term, we should identify why no tiles are visible on a read only file system

**Comment by spyhunter99** [comment]
@jeanboum ping

**Comment by spyhunter99** [comment]
v5.6 will be cut shortly. In the time being, try building off of master and using that in your application. It "should" resolve the issue with permissions. Reopen if it continues to be a problem
