### ISSUE TITLE
Problem downloading MapTile: /12/2299/1442 HTTP response: Forbidden

### ISSUE THREAD

**Issue by janoferenczi** [osmdroid/osmdroid#366]
Hi all.

I`ve got a the problem mentioned in the title.
It wont load all the tiles on the map.

![osmdroid_error](https://cloud.githubusercontent.com/assets/763092/17583501/05d9f3b2-5fba-11e6-9bbe-c965779015cc.png)

**Comment by dan89eu** [comment]
Hi guys,
We are having the same issue right now.

**Comment by catalin2402** [comment]
Hello, I'm having the same issue now

08-11 12:48:00.197 W/OsmDroid: Problem downloading MapTile: /10/586/371 HTTP response: Forbidden
08-11 12:48:00.207 W/OsmDroid: Problem downloading MapTile: /10/585/371 HTTP response: Forbidden
08-11 12:48:00.477 W/OsmDroid: Problem downloading MapTile: /10/584/370 HTTP response: Forbidden
08-11 12:48:00.647 W/OsmDroid: Problem downloading MapTile: /10/585/370 HTTP response: Forbidden

**Comment by emildancescu** [comment]
+1

**Comment by spyhunter99** [comment]
It's possible that the sample application's and default value for
osmdroid's aar user agent have been banned. I was noticing it too. Try
changing your user agent value

**Comment by spyhunter99** [comment]
Yup, that's it.

Stick this your application before loading the map

OpenStreetMapTileProviderConstants.setUserAgentValue(BuildConfig.APPLICATION_ID);

**Comment by catalin2402** [comment]
That means that i should update 6 apps that are allready in production... Awesome...

**Comment by catalin2402** [comment]
Are you sure that there isn't other solution to this problem ?

**Comment by Boekatsjakka** [comment]
Spyhunter99 this fixed for me. Thanks for the answer!

**Comment by spyhunter99** [comment]
@catalin2402 sorry for the inconvenience. It's been in the api since 5.0 and in the wiki shortly afterwards. I'm not sure it was ever read only but it's a critical thing.

**Comment by MKergall** [comment]
Its' working again, without any change in my app. 
Policy on Mapnik server has probably been changed again.

**Comment by k3b** [comment]
For details see

* http://wiki.openstreetmap.org/wiki/Blocked_applications
* http://wiki.openstreetmap.org/wiki/Tile_usage_policy

**Comment by Firefishy** [comment]
FYI: Since this commit https://github.com/openstreetmap/chef/commit/bb8fbb886ef77d0e23f675966342c10d1d603e00 we have re-enabled the block if a proper `User-Agent` is not set.

**Comment by SSaqibRuman** [comment]
Even I faced this issue after some googling I came across a solution, we need to set User agent value in configuration. Please refer to this link for furthermore clarification https://github.com/osmdroid/osmdroid/wiki/Important-notes-on-using-osmdroid-in-your-app
