### ISSUE TITLE
OSM Mapnik source Forbidden

### ISSUE THREAD

**Issue by hlaurent** [osmdroid/osmdroid#368]
My app and the Play Store demo app "osmdroid" can't download OSM Mapnik tiles anymore.
We get this type of message :
W/OsmDroid: Problem downloading MapTile: /4/4/8 HTTP response: Forbidden

It looks like this started yesterday 11/08/2016.
I am using version 5.1

**Comment by telipskiy** [comment]
I habe the same problem

**Comment by bkhezry** [comment]
me too

**Comment by spyhunter99** [comment]
duplicate
https://github.com/osmdroid/osmdroid/issues/366
