### ISSUE TITLE
Problem downloading MapTile: /0/0/0 HTTP response: Forbidden

### ISSUE THREAD

**Issue by BackPackerDz** [osmdroid/osmdroid#371]
Hi, I have this error when I try to integrate the map !

**Comment by spyhunter99** [comment]
Duplicate. Set the user agent

**Comment by BackPackerDz** [comment]
@spyhunter99 please how can I set the user agent ? I don't see any method allow me to do it

**Comment by spyhunter99** [comment]
Search closed issues.  I think it's #366. It's also in the wiki.
