### ISSUE TITLE
Error importing source code

### ISSUE THREAD

**Issue by feandrad** [osmdroid/osmdroid#372]
I can't import the source code to my project, getting the following error when gradle runs:
'Error:Cannot get property 'pom' on extra properties extension as it does not exist'

I'm using Android Studio and already run the gradle clean build command before import it. As a Project, the gradle compile OSM and runs just fine.

What am I doing wrong?

**Comment by spyhunter99** [comment]
try via command line with the gradle wrapper?
make sure android studio is importing as a gradle project, not a maven project?

**Comment by eduatletico** [comment]
I have the exactly same issue here...

Running command **gradlew clean build** (like the wiki [here](https://github.com/osmdroid/osmdroid/wiki/How-to-build-osmdroid-from-source))
![image](https://cloud.githubusercontent.com/assets/20795276/17702052/571216d6-639a-11e6-9777-bc6051a7b494.png)

Then, importing module to my project... 
![image](https://cloud.githubusercontent.com/assets/20795276/17702208/f831b4cc-639a-11e6-837d-83dcb70aa250.png)

Gradle sync error...
![image](https://cloud.githubusercontent.com/assets/20795276/17702160/bcf2b488-639a-11e6-8e54-de417eddfe98.png)

**Comment by feandrad** [comment]
Yep, I did just like @eduatletico with the same result

**Comment by spyhunter99** [comment]
Not sure why you would need to import the source into your own project, especially since you can build and install to local maven via
`gradlew clean install`

then in your app, add the dependency for
`compile "org.osmdroid:osmdroid-android:5.3-SNAPSHOT@aar'

and you should be up and running. 

It's possible that one of our gradle plugins is causing the issue.

try appending this to your apk's build.gradle file
`apply from: 'https://raw.githubusercontent.com/chrisdoyle/gradle-fury/master/gradle/android-support.gradle'`

**Comment by eduatletico** [comment]
@spyhunter99 apeending _apply from: 'https://raw.githubusercontent.com/chrisdoyle/gradle-fury/master/gradle/android-support.gradle'_ in my build.gradle, I got the same error.

My local repository doesn't have _osmdroid_ folder:
![image](https://cloud.githubusercontent.com/assets/20795276/17736438/cdbee424-6455-11e6-8dda-2c942cd8a375.png)

**Comment by spyhunter99** [comment]
ahh in which case your gradle dependency would be something like

`compile "org.osmdroid:osmdroid-android:5.3-SNAPSHOT:debug@aar"`

glad you're up and running. Let's the this issue open as a reminder to update the wiki and readme

**Comment by spyhunter99** [comment]
updated. thanks for bringing it to our attention!

**Comment by eduatletico** [comment]
@spyhunter99 actually, to include dependency _compile 'org.osmdroid:osmdroid-android:5.3-SNAPSHOT:debug@aar'_ and _mavenLocal()_, the command to be executed is _**gradlew clean install distZip -Pprofile=sources,javadocs**_ (not _gradlew clean install_) wich will create local repository in .m2 folder

**Comment by spyhunter99** [comment]
@eduatletico no.

**Comment by AsranCJ** [comment]
I am still getting this error "Error:Cannot get property 'pom' on extra properties extension as it does not exist" 
I have changed my "settings.gradle" so it does ->  include ':osmdroid-android'
I have change my "build.gradle" so it  does -> compile project(':osmdroid-android')


And currently I want the project to be as a module in my Android Studio. 
Not compiled as an aar or jar 

What am I missing here =(
Hope someone can help me.

**Comment by JJill** [comment]
Everything done as shown above but the error is still there
![Uploading jpg1.jpg…]()

**Comment by JJill** [comment]
Everything done as shown above but the error is still there

![jpg1](https://user-images.githubusercontent.com/33855686/33229272-cf6e6c58-d1f1-11e7-8d5f-b24259a15208.jpg)

**Comment by spyhunter99** [comment]
not sure why you are doing this as it's unnecessary and IMO a strange practice that is easily avoided

reason why this is happening: in order for us to publish to maven central, we use build helper scripts from gradle fury, which requires a number of configuration parameters in gradle.properties and hooks in the build.gradle files.

to avoid this non sense:

- we publish javadocs and source jars for everything to maven central, android studio should resolve them.
- if you need to change the code, check out your own version of osmdroid, make the changes, then use `gradlew install`. Then in your project, reference the repository mavenLocal and then use the SNAPSHOT version of osmdroid, debug variant. All of this is described in the wiki

**Comment by spyhunter99** [comment]
Third option,  remove all osmdroid gradle build files and make your own
