### ISSUE TITLE
Mixing local offline-tiles with online-tiles from different provider to the map

### ISSUE THREAD

**Issue by k3b** [osmdroid/osmdroid#376]
Thanks to [osmdroid-forge-app demo](https://github.com/osmdroid/osmdroid/tree/master/osmdroid-forge-app) it was easy to learn how to add offline functionality to my existing osmdroid-based app.

I have offline *map files for spain, germany, greece and the canary islands on my android device.

When i zoom out the map for world-view i can see some contures of the offline maps but the rest of the world remains white. (currently i have no offline-world-map file on the device)

Is it possible to tell osmdroid to use an additional online-source for those tiles that are missing in the offline map files so there are no more white-spaces?

**Comment by spyhunter99** [comment]
You can, just include a different tile provider chain. See MapTileProviderBasic. Extend or override it (or just copy it) and you can change the order and what tile providers are used

**Comment by k3b** [comment]
Thanks for fast feedback. 

I did as you proposed but MapsForgeTileModuleProvider still takes over all tiles as white without chaining to download provider.

Details:

I created a new [MapTileProviderWithForge](https://github.com/k3b/osmdroid/blob/ForgeOfflinePlusDownload/osmdroid-forge-app/src/main/java/org/osmdroid/forge/app/MapTileProviderWithForge.java) which combines MapsForgeTileProvider and MapTileProviderBasic.

I put MapsForgeTileModuleProvider just before MapTileDownloader that does osm-mapnik download

Next I have to find out how to tell MapsForge to chain to next provider, if there is no data for current tile.

I keep this ticket updated to report progress.....

**Comment by spyhunter99** [comment]
I think to have to tell mapsforge to return an null image if there's no data available instead of an empty white tile. That would probably solve the problem

**Comment by spyhunter99** [comment]
I'm pretty sure the correct answer is to tell forge to return null if there's no data in the rendered image. then you're good to go. Also, render the background as transparent may help, otherwise you'll get all kinds of jagged edges. Reopen if there's any other questions but you're at the limit of my knowledge. @MKergall may be able to help too

**Comment by k3b** [comment]
after adding world.map to my offline tiles the map does not look ugly at the borders of the map any more. so on my side there is no more need to merege.

Thanks for support
