### ISSUE TITLE
Including osmdroid in my project

### ISSUE THREAD

**Issue by zhaoxuhui** [osmdroid/osmdroid#380]
I created a new android studio project with gradle,and I added
`dependencies {
    compile 'org.osmdroid:osmdroid-android:5.1@aar'
    //Note as of 5.0, this is no longer needed!  compile 'org.slf4j:slf4j-simple:1.6.1'
}`
in the module's build.gradle.
But it always failed build,and says:
![image](https://cloud.githubusercontent.com/assets/17122056/17856979/917b5dd8-68b2-11e6-958b-5f255de0f92c.png)
I don't know what's the problem.

**Comment by spyhunter99** [comment]
See https://github.com/osmdroid/osmdroid/issues/378
