### ISSUE TITLE
Create sample proguard files

### ISSUE THREAD

**Issue by spyhunter99** [osmdroid/osmdroid#381]
primarily for
- minified osmdroid-android
- everything osmdroid-android (complete)

**Comment by k3b** [comment]
Helpfull for this: let gradle show dependencies to other modules:

All i found was this:

* gradle osmdroid-forge-app:dependencies

shows this:

<pre>
+--- org.mapsforge:mapsforge-map-android:0.6.0
|    +--- org.mapsforge:mapsforge-map-reader:0.6.0
|    |    \--- org.mapsforge:mapsforge-map:0.6.0
|    |         +--- org.mapsforge:mapsforge-core:0.6.0
|    |         \--- net.sf.kxml:kxml2:2.3.0
|    \--- com.caverock:androidsvg:1.2.2-beta-1
</pre>

i assume that `net.sf.kxml:kxml2:2.3.0` is not necessary to use mapsforge.

i assume that this will do the trick (without proguaard) but i hav-nt tested it yet

* compile(':osmdroid-mapsforge') {transitive = false}
* compile('org.mapsforge:mapsforge-map-android:0.6.0') {transitive = false}
* compile('org.mapsforge:mapsforge-map:0.6.0') {transitive = false}

http://stackoverflow.com/questions/13923516/how-do-you-exclude-a-transitive-project-dependency-in-gradle


possible todo: exclude kml-stuff from osmdroid-mapsforge

**Comment by spyhunter99** [comment]
There is. Here's an example

````
 compile('ch.acra:acra:4.7.0') {
        exclude group: 'org.json'
    }
````

**Comment by k3b** [comment]
[kxml](http://www.kxml.org/) as a memory efficient xml praser. it has nothing to do with kml. i compiled the forge demo app without it and it seems to be working.

**Comment by spyhunter99** [comment]
Forge uses xml for defining rendering settings. I think it's required. Did
your test include a clean build?
