### ISSUE TITLE
Crashed while moving and scaling

### ISSUE THREAD

**Issue by zhaoxuhui** [osmdroid/osmdroid#382]
I use osmroid load tile from other source.And then I draw a polygon and a path on the map.

![screenshot_2016-08-25-16-08-05_com example myapp0](https://cloud.githubusercontent.com/assets/17122056/17961478/8dcf0742-6ade-11e6-8997-8a8884c14d9a.jpg)

When I scale quickly on the map , it will become very slow and then crashed.Here is a clip of error infomation:
`08-25 15:34:47.250  28734-28734/com.example.myapp08223 I/OsmDroid﹕ Tile cache increased from 143 to 156

08-25 15:34:47.260  28734-28734/com.example.myapp08223 I/OsmDroid﹕ Tile cache increased from 143 to 156

08-25 15:34:47.290  28734-28734/com.example.myapp08223 I/OsmDroid﹕ Tile cache increased from 156 to 169

08-25 15:34:47.290  28734-28734/com.example.myapp08223 I/OsmDroid﹕ Tile cache increased from 156 to 169

08-25 15:34:47.630  28734-28734/com.example.myapp08223 I/OsmDroid﹕ rescale tile cache from 11 to 12

08-25 15:34:47.750  28734-28734/com.example.myapp08223 I/OsmDroid﹕ Finished rescale in 128ms

08-25 15:34:49.450  28734-28734/com.example.myapp08223 I/OsmDroid﹕ rescale tile cache from 12 to 13

08-25 15:34:49.520  28734-28748/com.example.myapp08223 W/art﹕ Suspending all threads took: 10.817ms

08-25 15:34:49.560  28734-28734/com.example.myapp08223 I/OsmDroid﹕ Finished rescale in 110ms

08-25 15:34:50.000  28734-28787/com.example.myapp08223 A/libc﹕ Fatal signal 11 (SIGSEGV), code 1, fault addr 0xa in tid 28787 (RenderThread)`

And I also tried remove the polygon and path ,it will not crash when I scale quickly.So I think this might be the problem of drawings on the map.But how to solve this problem?I've read this.[https://github.com/osmdroid/osmdroid/wiki/How-to-use-the-osmdroid-library#how-many-icons-can-i-put-on-the-map](url) You said with the growing of zoom level ,increasing the fidelity.  But how to do it in practice?Is there any other ways to deal with this?
Thanks!

**Comment by spyhunter99** [comment]
What version of osmdroid? what os version and processor type? the polygons were created how? can you post the code?

**Comment by zhaoxuhui** [comment]
I used the osmroid version 5.2,and the android 5.1 ,qualcomm 810.Here is the code:
`        polygon = new Polygon(this);
        polygon.setPoints(geoPoints.subList(0, 3));
        polygon.setFillColor(0x96FF8200);
        polygon.setStrokeColor(Color.RED);
        polygon.setStrokeWidth(4);
        polygon.setInfoWindow(new BasicInfoWindow(R.layout.bonuspack_bubble, mMapView));
        polygon.setTitle("Polygon tapped!");
        mMapView.getOverlays().add(polygon);
        mMapView.invalidate();`

`        polyline = new Polyline(this);
        polyline.setPoints(geoPoints.subList(3, 6));
        polyline.setColor(Color.YELLOW);
        polyline.setWidth(8);
        polyline.setInfoWindow(new BasicInfoWindow(R.layout.bonuspack_bubble, mMapView));
        polyline.setTitle("Polyline tapped!");
        mMapView.getOverlays().add(polyline);
        mMapView.invalidate();`

The polygon and polyline object are defined in activity:
`    Private Polygon polygon;
    Private Polyline polyline;`

**Comment by spyhunter99** [comment]
I'm having trouble reproducing the crash. Usually a SIGSEGV error is the OS is killing the app because of memory corruption. If you have another device, try to reproduce it on that or in the emulator. You can also try turning off hardware acceleration for the map view.

It would be helpful if i had the exact coordinates from your list. Sometimes gigantic polylines or polygons can cause issues. Here's what i'm using

````
 List<GeoPoint> geoPoints = new ArrayList<>();
        geoPoints.add(new GeoPoint(47d, -74d));
        geoPoints.add(new GeoPoint(46d, -75d));
        geoPoints.add(new GeoPoint(47d, -76d));
        geoPoints.add(new GeoPoint(46d, -75d));
        geoPoints.add(new GeoPoint(44d, -73d));
        geoPoints.add(new GeoPoint(43d, -72d));
````

**Comment by zhaoxuhui** [comment]
I tried your code and it runs better than mine.As you said gigantic polygons and lines could cause this issue.Maybe mine is a little big so that it becomes slow and gets crashed after zooming in.Here is my code:
`geoPoints.add(new GeoPoint(26.0, 113.5));
geoPoints.add(new GeoPoint(26.0, 114.5));
geoPoints.add(new GeoPoint(27.0, 114.5));
geoPoints.add(new GeoPoint(26.0, 115.0));
geoPoints.add(new GeoPoint(26.0, 116.0));
geoPoints.add(new GeoPoint(27.0, 115.0));`

**Comment by spyhunter99** [comment]
I tried your coordinates too and added it to the sample application. I couldn't get it to crash on hw or the avd. Try turning off hardware acceleration on your device.

**Comment by spyhunter99** [comment]
Second part of your question,  I am not sure I understand. You can put a lot of icons on the map but for better performance, icon clustering will help or you can limit what osmdroid knows about by filtering the data before adding it to the map. Then on map movement or zoom, adjust quays on the map as needed

**Comment by spyhunter99** [comment]
Ping
