### ISSUE TITLE
5.2: BingMapTileSource displays Australian tiles for UK lat/long

### ISSUE THREAD

**Issue by atoone** [osmdroid/osmdroid#383]
In the current (5.2) release of osmdroid, I can display maps as expected using the default tile source, or others such as the USGS Topo source. However, if I switch to the thirdparty/BingMapTileSource, it displays maps centered in New South Wales, Australia for lat/long coordinates in the UK.

Edited to add: this appears to be a race condition, in that if the map location and overlays are set before initMetaData is called, they are incorrectly positioned. Unfortunately there is no way to invoke it directly, so Activities that build up a map view before the map is displayed will show the wrong location?

In addition, the maximum zoom level returned for BingMaps seems to exceed the available tile sources for aerial maps by quite a way - ie. if you zoom to maximum, you get 'no tile' images for the three most detailed levels at my current location.

I'm creating the BinMapTileSource as indicated in the Wiki:

```
            BingMapTileSource.retrieveBingKey(context);
            BingMapTileSource bing = new BingMapTileSource(null);
            bing.setStyle(BingMapTileSource.IMAGERYSET_AERIALWITHLABELS);
```

Horrible work around to invoke initMetaData:

```
            BingMapTileSource bing = new BingMapTileSource(null) {
                @Override
                public String toString() {
                    getBaseUrl();
                    return super.toString();
                }
            };
            bing.setStyle(BingMapTileSource.IMAGERYSET_AERIALWITHLABELS);
            bing.toString();
```

Does this also imply that BingMaps will not work in offline mode, as it won't be able to run the initMetaData request when displaying tiles from an offline cache?

**Comment by spyhunter99** [comment]
Ok I'll take a look at it

**Comment by spyhunter99** [comment]
I can make  `initMetaData` public if that will help you. I've also set the max zoom is 19, which does exist in certain areas.

Is your issue with mismatched tiles at a specific zoom level?

**Comment by spyhunter99** [comment]
Also do you have a lat/lon and zoom level to recreate the problem? it's looking ok over here

**Comment by spyhunter99** [comment]
@atoone can you give me more specifics? What coordinates was the issue at? what zoom level? If it was greater than zoom 19, the issue is probably the overflow issue #329. In which case, the only solution is to reduce the max zoom level to 19.

**Comment by atoone** [comment]
Ah, that may well be the problem.

I've heavily refactored the code I was using, which means I don't have a
convenient test case - but on the other hand I'm not experiencing odd
results any more. I believe it was zooming in to maximum during map loading
(I'm loading a flight path progressively, so the initial data covers a very
small distance, which would result in maximum zoom). Now however I load the
data asynchronously and leave the map zoom at 'global', zoomed out at
default. Once the data is loaded, things are zoomed to the extent of the
flight path, which is typically within the maximum zoom of the various
providers.

The location I'm testing with is Cambridge, UK, so 0 degrees long, 52 lat
more or less. It was coming out as New South Wales under the original code.

I'm not totally clear what the metadata load is needed for - what happens
if you're looking at offline, cached tiles?

Andy

**Comment by spyhunter99** [comment]
Once the tile is downloaded, it's stored (cached) in osmdroid's format, metadata isn't needed in that case.  Looks like the metadata thing is some kind of authentication mechanism, min/max zooms, pixel sizes, etc

**Comment by spyhunter99** [comment]
reopen if you run into any more issues with this

**Comment by atoone** [comment]
Many thanks for your help, sorry for pointing in the wrong direction
initially.

Andy
