### ISSUE TITLE
Using org.osmdroid:osmdroid-third-party:5.0.1@aar with sdk v24

### ISSUE THREAD

**Issue by arpitgoyal2008** [osmdroid/osmdroid#388]
Hello,

I am unable to use this library with build tools 24. It shows the error that it can't access MapView. Any idea how can I resolve this or would it be fixed in next versions?

**Comment by spyhunter99** [comment]
Probably a permissions issue. Does the sample app work?

**Comment by spyhunter99** [comment]
Could also be a storage issue. Is /sdcard writable?

**Comment by spyhunter99** [comment]
Can you post the message and any log output that's relevant

**Comment by arpitgoyal2008** [comment]
Hello,

following is my app level build.gradle file: 

`apply plugin: 'com.android.application'
android {
    compileSdkVersion 23
    buildToolsVersion '23.0.3'

    defaultConfig {
        applicationId "com.abc.def"
        minSdkVersion 11
        targetSdkVersion 23
        versionCode 26
        versionName "0.91"
    }
    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    compile 'com.android.support:appcompat-v7:23.1.1'
    compile 'com.facebook.android:facebook-android-sdk:4.1.0'
    compile 'com.mcxiaoke.volley:library:1.0.18'
    compile 'com.google.android.gms:play-services-gcm:8.3.0'
    compile 'com.google.android.gms:play-services-maps:8.3.0'
    compile 'com.google.android.gms:play-services-location:8.3.0'
    compile 'com.google.android.gms:play-services-auth:8.3.0'
    compile 'com.google.android.gms:play-services-appinvite:8.3.0'
    compile 'com.android.support:support-v4:24.0.0'
    compile 'com.rengwuxian.materialedittext:library:2.1.4'
    compile 'com.android.support:design:23.1.1'
    compile 'com.android.support:recyclerview-v7:23.1.1'
    compile 'com.squareup.picasso:picasso:2.5.2'
    compile 'org.osmdroid:osmdroid-android:5.1@aar'
    compile 'org.osmdroid:osmdroid-third-party:5.0.1@aar'
}
apply plugin: 'com.google.gms.google-services'`

and project level gradle file: 
`buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.2.0-beta2'
        classpath 'com.google.gms:google-services:2.0.0-alpha7'
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        jcenter()
    }
}`

When I use this to compile the project, I get the error:

Error:(293, 26) error: cannot access MapView
class file for com.google.android.maps.MapView not found

Can you help me with this?

**Comment by spyhunter99** [comment]
You have proguard turned on. You'll have to either turn it off or add keep
class statements for osmdroid

**Comment by arpitgoyal2008** [comment]
Hi,

Proguard comes into picture only when I build a signed apk. It is still in debug mode. And, I am getting error while compiling. So, proguard has no role in producing this error.

**Comment by spyhunter99** [comment]
first problem is that you have mismatched versions of osmdroid and the 3rd party library. make them both the same version.

If you're using the Google Maps stuff, you have you change the the compileSdkVersion to the Google version, which would be ` compileSdkVersion 'Google Inc.:Google APIs:23'`. Are you sure that's what you want? I think your probably want to reference org.osmdroid.views.MapView

**Comment by arpitgoyal2008** [comment]
Let me try this and get back to you
I am not sure about the osmdroid-thirdparty latest version: is it also 5.2?

**Comment by spyhunter99** [comment]
latest version for both is 5.2

**Comment by spyhunter99** [comment]
sample app works fine with the avd on the latest and greatest.

**Comment by spyhunter99** [comment]
Try with 5.4 or 5.2.

**Comment by spyhunter99** [comment]
No much else i can do for you.  Try blowing up the gradle cache in your user folder.
