### ISSUE TITLE
Asyncronous tile loading

### ISSUE THREAD

**Issue by janoferenczi** [osmdroid/osmdroid#389]
Hi everyone.

I`m trying to Implement a tile source provider with libosmscout but I would like to get the tiles on a secondary thread. Is that possible with osmdroid to load the tiles asyncronously from a secondary thread?

Thanks.

**Comment by spyhunter99** [comment]
All tile loading is done off the main thread already.

**Comment by janoferenczi** [comment]
Yes, I found it.
