### ISSUE TITLE
encrypted mbtiles?

### ISSUE THREAD

**Issue by hlaurent** [osmdroid/osmdroid#395]
I would like to create encrypted mbtiles files.
I would, for example, encrypt the blob of the tiles table when I create the maps outside the app.
The blob would be decrypted in the app when it is displayed.

Is there a way to do this?

**Comment by spyhunter99** [comment]
Yes. Check out sqlcipher which will encrypt the whole db. You'll then have to extend the mbtiles class to hook in the cipher bits

**Comment by spyhunter99** [comment]
You can also roll own solution using aes. The built in java stuff works fine
