### ISSUE TITLE
Trouble with this file kml

### ISSUE THREAD

**Issue by juamor86** [osmdroid/osmdroid#396]
I use this File Kml --> https://dl.dropboxusercontent.com/u/40605841/17752_with_style.kml

this error : 09-02 12:47:41.256: W/System.err(27156): java.lang.NullPointerException: Attempt to invoke virtual method 'boolean org.osmdroid.views.overlay.Overlay.isEnabled()' on a null object reference
09-02 12:47:41.267: W/System.err(27156): at org.osmdroid.views.overlay.DefaultOverlayManager.onDraw(DefaultOverlayManager.java:111)
09-02 12:47:41.267: W/System.err(27156): at org.osmdroid.bonuspack.overlays.FolderOverlay.draw(FolderOverlay.java:68)
09-02 12:47:41.267: W/System.err(27156): at org.osmdroid.views.overlay.DefaultOverlayManager.onDraw(DefaultOverlayManager.java:118)
09-02 12:47:41.267: W/System.err(27156): at org.osmdroid.bonuspack.overlays.FolderOverlay.draw(FolderOverlay.java:68)
09-02 12:47:41.267: W/System.err(27156): at org.osmdroid.views.overlay.DefaultOverlayManager.onDraw(DefaultOverlayManager.java:118)
09-02 12:47:41.267: W/System.err(27156): at org.osmdroid.views.MapView.dispatchDraw(MapView.java:993)
09-02 12:47:41.267: W/System.err(27156): at android.view.View.updateDisplayListIfDirty(View.java:15175)
09-02 12:47:41.267: W/System.err(27156): at android.view.View.draw(View.java:15954)
09-02 12:47:41.268: W/System.err(27156): at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
09-02 12:47:41.268: W/System.err(27156): at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
09-02 12:47:41.268: W/System.err(27156): at android.view.View.updateDisplayListIfDirty(View.java:15175)
09-02 12:47:41.268: W/System.err(27156): at android.view.View.draw(View.java:15954)
09-02 12:47:41.268: W/System.err(27156): at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
09-02 12:47:41.268: W/System.err(27156): at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
09-02 12:47:41.268: W/System.err(27156): at android.view.View.draw(View.java:16187)
09-02 12:47:41.268: W/System.err(27156): at android.view.View.updateDisplayListIfDirty(View.java:15180)
09-02 12:47:41.268: W/System.err(27156): at android.view.View.draw(View.java:15954)
09-02 12:47:41.268: W/System.err(27156): at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
09-02 12:47:41.268: W/System.err(27156): at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
09-02 12:47:41.268: W/System.err(27156): at android.view.View.updateDisplayListIfDirty(View.java:15175)
09-02 12:47:41.268: W/System.err(27156): at android.view.View.draw(View.java:15954)
09-02 12:47:41.268: W/System.err(27156): at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
09-02 12:47:41.268: W/System.err(27156): at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
09-02 12:47:41.268: W/System.err(27156): at android.view.View.draw(View.java:16187)
09-02 12:47:41.269: W/System.err(27156): at android.view.View.updateDisplayListIfDirty(View.java:15180)
09-02 12:47:41.269: W/System.err(27156): at android.view.View.draw(View.java:15954)
09-02 12:47:41.269: W/System.err(27156): at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
09-02 12:47:41.269: W/System.err(27156): at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
09-02 12:47:41.269: W/System.err(27156): at android.view.View.draw(View.java:16187)
09-02 12:47:41.269: W/System.err(27156): at android.view.View.updateDisplayListIfDirty(View.java:15180)
09-02 12:47:41.269: W/System.err(27156): at android.view.View.draw(View.java:15954)
09-02 12:47:41.269: W/System.err(27156): at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
09-02 12:47:41.269: W/System.err(27156): at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
09-02 12:47:41.269: W/System.err(27156): at android.view.View.draw(View.java:16187)
09-02 12:47:41.269: W/System.err(27156): at android.view.View.updateDisplayListIfDirty(View.java:15180)
09-02 12:47:41.269: W/System.err(27156): at android.view.View.draw(View.java:15954)
09-02 12:47:41.269: W/System.err(27156): at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
09-02 12:47:41.269: W/System.err(27156): at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
09-02 12:47:41.269: W/System.err(27156): at android.view.View.draw(View.java:16187)
09-02 12:47:41.269: W/System.err(27156): at android.view.View.updateDisplayListIfDirty(View.java:15180)
09-02 12:47:41.269: W/System.err(27156): at android.view.View.draw(View.java:15954)
09-02 12:47:41.270: W/System.err(27156): at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
09-02 12:47:41.270: W/System.err(27156): at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
09-02 12:47:41.270: W/System.err(27156): at slideholderpack.SlideHolder.dispatchDraw(SlideHolder.java:440)
09-02 12:47:41.270: W/System.err(27156): at android.view.View.updateDisplayListIfDirty(View.java:15175)
09-02 12:47:41.270: W/System.err(27156): at android.view.View.draw(View.java:15954)
09-02 12:47:41.270: W/System.err(27156): at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
09-02 12:47:41.270: W/System.err(27156): at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
09-02 12:47:41.270: W/System.err(27156): at android.view.View.draw(View.java:16187)
09-02 12:47:41.270: W/System.err(27156): at android.view.View.updateDisplayListIfDirty(View.java:15180)
09-02 12:47:41.271: W/System.err(27156): at android.view.View.draw(View.java:15954)
09-02 12:47:41.271: W/System.err(27156): at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
09-02 12:47:41.271: W/System.err(27156): at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
09-02 12:47:41.271: W/System.err(27156): at android.view.View.updateDisplayListIfDirty(View.java:15175)
09-02 12:47:41.271: W/System.err(27156): at android.view.View.draw(View.java:15954)
09-02 12:47:41.271: W/System.err(27156): at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
09-02 12:47:41.271: W/System.err(27156): at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
09-02 12:47:41.271: W/System.err(27156): at android.view.View.draw(View.java:16187)
09-02 12:47:41.271: W/System.err(27156): at com.android.internal.policy.PhoneWindow$DecorView.draw(PhoneWindow.java:2690)
09-02 12:47:41.271: W/System.err(27156): at android.view.View.updateDisplayListIfDirty(View.java:15180)
09-02 12:47:41.271: W/System.err(27156): at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:281)
09-02 12:47:41.271: W/System.err(27156): at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:287)
09-02 12:47:41.271: W/System.err(27156): at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:322)
09-02 12:47:41.271: W/System.err(27156): at android.view.ViewRootImpl.draw(ViewRootImpl.java:2615)
09-02 12:47:41.271: W/System.err(27156): at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2434)
09-02 12:47:41.272: W/System.err(27156): at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2067)
09-02 12:47:41.272: W/System.err(27156): at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1107)
09-02 12:47:41.272: W/System.err(27156): at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6013)
09-02 12:47:41.273: W/System.err(27156): at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
09-02 12:47:41.273: W/System.err(27156): at android.view.Choreographer.doCallbacks(Choreographer.java:670)
09-02 12:47:41.273: W/System.err(27156): at android.view.Choreographer.doFrame(Choreographer.java:606)
09-02 12:47:41.273: W/System.err(27156): at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
09-02 12:47:41.273: W/System.err(27156): at android.os.Handler.handleCallback(Handler.java:739)
09-02 12:47:41.273: W/System.err(27156): at android.os.Handler.dispatchMessage(Handler.java:95)
09-02 12:47:41.273: W/System.err(27156): at android.os.Looper.loop(Looper.java:148)
09-02 12:47:41.273: W/System.err(27156): at android.app.ActivityThread.main(ActivityThread.java:5417)
09-02 12:47:41.274: W/System.err(27156): at java.lang.reflect.Method.invoke(Native Method)
09-02 12:47:41.274: W/System.err(27156): at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
09-02 12:47:41.274: W/System.err(27156): at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

this is my code :

public class MapFragmentd extends FragmentBase {

Context context;
MapView map;
KmlDocument mKmlDocument;
MapController mapControl;
View inflatedView;
SharedPreferences pref;
CmsxObject cmsxObject;
DatabaseEngine db;
File fileKml;
public static final String TYPE_KML = "KML";
public static final String MEDIATASK = "MediaTask";

public MapFragmentd(Context context, CmsxObject cms) 
{
    this.context = context;
    this.cmsxObject = cms;
    pref = context.getApplicationContext().getSharedPreferences("MyMacros",1);
    db = DatabaseEngine.getInstance(context);
}

@Override
public View onCreateView(LayoutInflater inflater, ViewGroup container,Bundle savedInstanceState) {
    inflatedView = inflater.inflate(R.layout.fragment_kml_map, container, false);

    // Disable StrictMode.ThreadPolicy to perform network calls in the UI// thread.
    StrictMode.ThreadPolicy policy = new StrictMode.ThreadPolicy.Builder().permitAll().build();
    StrictMode.setThreadPolicy(policy);

    LatLng currentPositionCmsxObject=Session.getInstance().getpos(cmsxObject);
    map = (MapView) inflatedView.findViewById(R.id.map);
    map.setBuiltInZoomControls(true);
    map.setMultiTouchControls(true);
    GeoPoint startPoint = new GeoPoint(currentPositionCmsxObject.latitude, currentPositionCmsxObject.longitude);
    IMapController mapController = map.getController();
    mapController.setZoom(10);
    mapController.setCenter(startPoint);
    View marker = ((LayoutInflater) context.getSystemService(Context.LAYOUT_INFLATER_SERVICE)).inflate(R.layout.custom_marker_layout, null);
    ImageView imvIconMapInMarker = (ImageView) marker.findViewById(R.id.imv_icon_map);

    Bitmap iconMapBitmap=Session.getInstance().getIconMap(cmsxObject.ExternalUID);
    if(iconMapBitmap!=null)
    {
        imvIconMapInMarker.setImageBitmap(iconMapBitmap);
    }   
    //Marker overlay
    Marker startMarker = new Marker(map);
    startMarker.setPosition(startPoint);
    startMarker.setAnchor(Marker.ANCHOR_CENTER, Marker.ANCHOR_BOTTOM);
    startMarker.setTitle(String.valueOf(cmsxObject.ExternalUID));
    startMarker.setSnippet(cmsxObject.Name);

    Drawable drawable = new BitmapDrawable(getResources(), createDrawableFromView(context, marker)); 
    startMarker.setIcon(drawable);
    startMarker.setDraggable(true);
    startMarker.setOnMarkerDragListener(new OnMarkerDragListenerDrawer());
    map.getOverlays().add(startMarker);

    //Loading KML content
    mKmlDocument = new KmlDocument();
    boolean successKml = false;
    if(getkmlFileCmsxObjectMedia())
    {
        successKml = mKmlDocument.parseKMLFile(fileKml);
    }

    if (successKml){

        FolderOverlay kmlOverlay = (FolderOverlay)mKmlDocument.mKmlRoot.buildOverlay(map, null,null, mKmlDocument);
        map.getOverlays().add(kmlOverlay);
        map.invalidate();
        BoundingBoxE6 bb = mKmlDocument.mKmlRoot.getBoundingBox();
        if (bb != null){
            map.getController().setCenter(bb.getCenter());
        }
    } else
    {
        //Toast.makeText(context, "Error when loading KML", Toast.LENGTH_SHORT).show();
    }

    return inflatedView;

}

// Convert a view to bitmap
public Bitmap createDrawableFromView(Context context, View view) {

    WindowManager wm = (WindowManager) context.getSystemService(Context.WINDOW_SERVICE);
    final DisplayMetrics displayMetrics = new DisplayMetrics();
    wm.getDefaultDisplay().getMetrics(displayMetrics);
    int height = displayMetrics.heightPixels;
    int width = displayMetrics.widthPixels;
    view.setLayoutParams(new LayoutParams(LayoutParams.WRAP_CONTENT, LayoutParams.WRAP_CONTENT));
    view.measure(width,height);
    view.layout(0, 0, width, height);
    view.buildDrawingCache();
    Bitmap bitmap = Bitmap.createBitmap(view.getMeasuredWidth(), view.getMeasuredHeight(), Bitmap.Config.ARGB_8888);

    Canvas canvas = new Canvas(bitmap);
    view.draw(canvas);

    return bitmap;
}

// 0. Using the Marker and Polyline overlays - advanced options
class OnMarkerDragListenerDrawer implements OnMarkerDragListener {
    ArrayList<GeoPoint> mTrace;
    Polyline mPolyline;

    OnMarkerDragListenerDrawer() {
        mTrace = new ArrayList<GeoPoint>(100);
        mPolyline = new Polyline(map.getContext());
        mPolyline.setColor(0xAA0000FF);
        mPolyline.setWidth(2.0f);
        mPolyline.setGeodesic(true);
        map.getOverlays().add(mPolyline);
    }

    @Override
    public void onMarkerDrag(Marker marker) {}

    @Override
    public void onMarkerDragEnd(Marker marker) {
        mTrace.add(marker.getPosition());
        mPolyline.setPoints(mTrace);
        map.invalidate();
    }

    @Override
    public void onMarkerDragStart(Marker marker) {}
}

@Override
public void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
}

public Boolean getkmlFileCmsxObjectMedia()
{

        ImageDownloader imageDownloader = new ImageDownloader();
        byte[] byteKML = null;
        try {
            String URL = "https://dl.dropboxusercontent.com/u/40605841/17752_with_style.kml";

            byteKML = imageDownloader.execute(URL).get();
        } catch (InterruptedException e) {
            e.printStackTrace();
        } catch (ExecutionException e) {
            e.printStackTrace();
        }

        if (byteKML == null) {
            return false;
        }else
        {
            File root = Environment.getExternalStorageDirectory();
            File dir = new File(root.getAbsolutePath());

            if (!dir.isDirectory()) {
                dir.mkdir();
            }

            try {

                if (!dir.isDirectory()) {
                    throw new IOException("Unable to create directory myFolder. SD card mounted?");
                }

                fileKml = new File(dir, "name.kml");
                FileUtils.writeByteArrayToFile(fileKml, byteKML);

            } catch (IOException e) {
                Log.w("write log", e.getMessage(), e);
                return false;

            }   
        }

    return true;
}

@Override
public boolean onKeyDown(int keyCode, KeyEvent event) {
    return false;
}

**Comment by spyhunter99** [comment]
@MKergall this one is all you

**Comment by MKergall** [comment]
(Would be better to create this issue in OSMBonusPack project...)

At first glance, the issue cause is that you have a gx:Track Placemark in your KML file (the "track" placemark). Such placemark is not supported by OSMBonusPack (see https://github.com/MKergall/osmbonuspack/wiki/KML to see what is supported). 

Now, this is quite bad to get a NPE for this reason. I will investigate further. 
In the meantime, removing this "track" placemark from your KML file should solve your issue.

**Comment by spyhunter99** [comment]
i'll see if i can trap the NPE

**Comment by spyhunter99** [comment]
waiting on travis to finish the tests, but it should be fixed from osmdroid's perspective. It's probable that `  FolderOverlay kmlOverlay = (FolderOverlay)mKmlDocument.mKmlRoot.buildOverlay(map, null,null, mKmlDocument);` returned a null value and the overlay manager lacked any checks for it

**Comment by spyhunter99** [comment]
merged. nothing else i can do from this end. the rest is up to @MKergall
