### ISSUE TITLE
Compass flickering

### ISSUE THREAD

**Issue by rbrueckner11** [osmdroid/osmdroid#400]
I am using the embedded compass of the Mapview. I recently have migrated my project from osmdroid 5.1. to 5.2. In parallel, also my mobile phone was upgraded from Android 5.0 to 6.0 almost at the same time.
After the migration of both the project and phone's OS mapview's embedded compass' pin now is quickly flickering in all directions. Before it has shown the direction to North. But I cannot say if the reason of the flickering is the project upgrade or the OS upgrade. Also, calibrating the compass does not help.
Anyway, in my app I have a separate compass view in another fragment separate from the osmdroid mapview and it's pin still is showing to North correctly.

Any idea? 

Thank you.

**Comment by spyhunter99** [comment]
is this issue present in the emulator or just on hardware? Do you have hardware acceleration turns on or off for your application? Also does the sample "Open Map" have the same issue?

**Comment by spyhunter99** [comment]
Running on a samsung s5 with android 6 api23. Not really seeing flickering worth complaining about with the compass on the sample app. There's a bit of stuttering. I think that was a consequence of a fixing a memory leak.

**Comment by rbrueckner11** [comment]
Sorry, must have been a problem with my phone. After a reboot the issue has gone and the compass is rotating normally. Thank you.
