### ISSUE TITLE
Could not find osmdroid-android.aar (org.osmdroid:osmdroid-android:5.4)

### ISSUE THREAD

**Issue by rbrueckner11** [osmdroid/osmdroid#401]
Trying to integrate osmdroid 5.4. Get the following error:
---------------
Error:A problem occurred configuring project ':navAid'.
> Could not find osmdroid-android.aar (org.osmdroid:osmdroid-android:5.4).
  Searched in the following locations:
      https://jcenter.bintray.com/org/osmdroid/osmdroid-android/5.4/osmdroid-android-5.4.aar

osmdroid-android-5.2.aar
osmdroid-android-5.4-release.aar
---------------

I used:
dependencies {
    compile 'org.osmdroid:osmdroid-android:5.4:release@aar'
}

**Comment by k3b** [comment]
*  jcenter.bintray.com/org/osmdroid/osmdroid-android/5.4/osmdroid-android-5.4.aar

sorry something with the jcenter upload went wrong

the mavencentral should work

     repositories {
        mavenCentral()
      }

**Comment by spyhunter99** [comment]
It was published last night and may not be available on all mirrors yet.
Usually within 3 days it's all updated.

On Sep 7, 2016 12:41 PM, "k3b" <notifications@github.com> wrote:


   - jcenter.bintray.com/org/osmdroid/osmdroid-android/5.4/
   osmdroid-android-5.4.aar

sorry something with the jcenter upload went wrong

the mavencentral should work

 repositories {
    mavenCentral()
  }

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/osmdroid/osmdroid/issues/401#issuecomment-245342535>,
or mute the thread

**Comment by rbrueckner11** [comment]
When using mavencentral they report:

Error:Could not find osmdroid-android.aar (org.osmdroid:osmdroid-android:5.4).
Searched in the following locations:
    https://repo1.maven.org/maven2/org/osmdroid/osmdroid-android/5.4/osmdroid-android-5.4.aar

Will wait another day or two hoping it'll be updated everywhere?

**Comment by spyhunter99** [comment]
You need the qualifier debug or release.
org.osmdroid:osmdroid-android:5.4:release@aar

**Comment by rbrueckner11** [comment]
Confirmed. I have exactly the same line in my grade.build file as suggested on github:

compile 'org.osmdroid:osmdroid-android:5.4:release@aar'

So, still the same issue today.

As a fyi, no issues at all with the previous version:

compile 'org.osmdroid:osmdroid-android:5.2@aar'

**Comment by spyhunter99** [comment]
that's strange. I just made a new project using only jcenter a repo

`compile 'org.osmdroid:osmdroid-android:5.4:release@aar'`

**Comment by spyhunter99** [comment]
what version of gradle are you using?

**Comment by rbrueckner11** [comment]
I am using gradle version 2.14.1

**Comment by spyhunter99** [comment]
what does your root build.gradle file look like?

**Comment by rbrueckner11** [comment]
That's my project level build.gradle file:

// Top-level build file where you can add configuration options common to all sub-projects/modules.
buildscript {
    repositories {
        mavenCentral()
        maven { url "https://jitpack.io" }

    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.2.0-rc1'
    }
}

allprojects {
    repositories {
        mavenCentral()
        maven { url "https://jitpack.io" }
    }
}

**Comment by rbrueckner11** [comment]
Hi, any update on this. I tried yesterday. Still the same issue. 
Thank you.

**Comment by k3b** [comment]
these gradle build files work for me

 Top-level build file where you can add configuration options common to all sub-projects/modules.


		buildscript {
			repositories {
				jcenter()
			}
			dependencies {
				classpath 'com.android.tools.build:gradle:2.1.2'
			}
		}

		allprojects {
			repositories {
				jcenter()
			}
		}

app/build.gradle

		// sub-projects/modules.
		apply plugin: 'com.android.application'

		dependencies {
			// this is osmdroid
			compile 'org.osmdroid:osmdroid-android:5.4:release@aar'
		}

**Comment by rbrueckner11** [comment]
I now use the same top level file. Just included maven { url "https://jitpack.io" } for the OsmBonusPack to be found. So it looks like this: 

buildscript {
    repositories {
        jcenter()
        maven { url "https://jitpack.io" }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.1.3'
    }
}

allprojects {
    repositories {
        jcenter()
        maven { url "https://jitpack.io" }
    }
}

Project grade file looks exactly the same as your extract.

But the osmdroid 5.4 is not found:

Error:A problem occurred configuring project ':navAid'.
> Could not find osmdroid-android.aar (org.osmdroid:osmdroid-android:5.4).
  Searched in the following locations:
      https://jcenter.bintray.com/org/osmdroid/osmdroid-android/5.4/osmdroid-android-5.4.aar

Can you try on Android Studio 2.2. RC 2?

**Comment by MKergall** [comment]
If you are using OSMBonusPack 5.8.1, you MUST use osmdroid-android:5.2. 
You cannot use osmdroid 5.4, as OSMBonusPack has not been released for osmdroid 5.4 yet.

**Comment by spyhunter99** [comment]
as mentioned before, with the 5.4 series, you'll have to add the debug/release qualifier

https://jcenter.bintray.com/org/osmdroid/osmdroid-android/5.4/osmdroid-android-5.4-release.aar

which works just fine over here.

**Comment by rbrueckner11** [comment]
Ahh, MKergall, this then may be the issue. Any plans as to when the bonuspack will be available for osmdroid 5.4? There are a couple of features in 5.4 which I need to use to improve the experience of my app. Thanks.

**Comment by MKergall** [comment]
The commit is already pushed (66217d1). 
I have now to upgrade to osmdroid 5.4.1, which fixes anoying issues. 
Then I will create the release. It's a matter of days.

**Comment by rbrueckner11** [comment]
Everything now works fine with osmdroid 5.4 and bonuspack 5.9. Thank you.

Mapview is not flinging around anymore when zooming in or out. Great improvement.

In osmdroid 5.4 a SQLite database is used for tile cache instead of file system. Formerly, I used a recursive procedure to delete the tile files from the storage in order to clear the cache. Could you advise how the sqllight d/b can be deleted?
I assume the cache deletion feauture of my app has to look for both the tile files and the sqllight d/b until all users are migrated to an app version only using osmdroid 5.4?
