### ISSUE TITLE
Submit open map to fdroid repo

### ISSUE THREAD

**Issue by spyhunter99** [osmdroid/osmdroid#407]

**Comment by spyhunter99** [comment]
https://f-droid.org/forums/topic/osmdroid/#post-21752

**Comment by legrostdg** [comment]
Any progress?

**Comment by rojoweko** [comment]
The link to the f-droid forum is dead. Is there a major blocker preventing an inclusion in the f-droid repo?

**Comment by spyhunter99** [comment]
Whoa, that forum is completely different now. no idea

**Comment by spyhunter99** [comment]
@rojoweko i don't believe there was, other than they are picky about our dependencies, specifically the 3rd party module and demo library that uses the google maps library. They also insist on building the code themselves too. There's an alternate settings.gralde file fore this purpose, which would mean they would have to run a simple rename/move command before building

**Comment by rojoweko** [comment]
@spyhunter99 ah, ok. Thanks for the info. ;-)

**Comment by spyhunter99** [comment]
https://gitlab.com/fdroid/rfp/issues/314

**Comment by spyhunter99** [comment]
i'm giving up on this.
