### ISSUE TITLE
BoundingBox.fromGeoPoints incorrect when points with negative lats or lons

### ISSUE THREAD

**Issue by MKergall** [osmdroid/osmdroid#408]
When you build a bounding box from a list of GeoPoints: BoundingBox.fromGeoPoints, if your GeoPoints have negative lats and/or lons, they are not taken properly into account. 
(I struggled a lot to identify this one! Initially suspecting zoomToBoundingBox)

The root cause: when migrating from BoundingBoxE6 to BoundingBox, 
`int maxLat = Integer.MIN_VALUE; 
`
has been ported to 
`double maxLat = Double.MIN_VALUE;
`

But Double.MIN_VALUE is not negative, as Integer.MIN_VALUE was! It is "a value very close to zero" (4.9E-324). 
So the fix: 
`double maxLat = -Double.MAX_VALUE;
double maxLon = -Double.MAX_VALUE;
`

**Comment by spyhunter99** [comment]
Ahhhhh! Great find

**Comment by spyhunter99** [comment]
We should definitely find a way to add a unit test for this one. Do you have a set of input values @MKergall ?

**Comment by spyhunter99** [comment]
@neilboyd i think after this issue is fixed, we should probably cut another version. v5.4 is current, so maybe a v5.4.1 since it'll just be bug fixes
