### ISSUE TITLE
Minimap Overlay Tile Size 

### ISSUE THREAD

**Issue by dimy93** [osmdroid/osmdroid#41]
When I create a custom minimap tile provider with tilesize different than the one of the map and apply it to the minimap, Instead of loading the minimap's tiles with the size imposed by the tileprovider it uses the one of the TileSystem which is essentially the one of the mapview. I am using OSMDroid 4.1.

**Comment by spyhunter99** [comment]
can you post the code for constructing the minimap?

an option is to make your own minimap, which is just another osmdroid instance that's just smaller.

**Comment by spyhunter99** [comment]
ping time out. reopen the ticket if its still a problem (and with enough information to recreate)
