### ISSUE TITLE
Polyline and Polygon still using int at various places

### ISSUE THREAD

**Issue by MKergall** [osmdroid/osmdroid#410]
Minor issues: 

1) Polyline and Polygon hold original values of GeoPoints that have been set, so that users have a getter a copy of them later. 

```
polyline.setPoints(initialList);
Array<GeoPoint> list = polyline.getPoints();
```

Those values are stored in an array of int: 
`int mOriginalPoints[][];`

It should be moved to an array of double:
`double mOriginalPoints[][];`

2) The 2 Polygon.pointsAsRect methods are still based on BoundingBoxE6. 

3) Polyline.addPoint methods are still based on int.

**Comment by spyhunter99** [comment]
i just did everything but Polyline.addPoint, which is an android coordinate int, not a lat/lon

**Comment by spyhunter99** [comment]
merged, i'll open a new ticket for the last item
