### ISSUE TITLE
Unexpected log message while zooming in/out: Called reconfigure on a bitmap that is in use

### ISSUE THREAD

**Issue by spyhunter99** [osmdroid/osmdroid#413]
Called reconfigure on a bitmap that is in use! This may cause graphical corruption!

probably related to #335's change set which is aggressive for cleanup up bitmap resources. Does not appear to cause issues though

**Comment by jankalfus** [comment]
I can confirm that I am also getting this message in logcat when zooming in/out.

**Comment by InI4** [comment]
Zooming out on both an 4.2.2 Android hardware and an 6.0.0 emulator (only these 2 tested)

**Comment by monsieurtanuki** [comment]
Possibly not happening anymore, as the zoom in/out process totally changed around 6.0.0 (real time tile approximation now vs. canvas scale before)

**Comment by monsieurtanuki** [comment]
Obviously not happening anymore.
Feel free to reopen.
