### ISSUE TITLE
ClassNotFoundException: org.sqlite.JDBC while exporting map with OSMMapTilePackager

### ISSUE THREAD

**Issue by SekthDroid** [osmdroid/osmdroid#414]
Hi all,

I am new with this library, and I was just trying to use OSMMapTilePackager to export a sqlite database from a given zone (just my city).

I was using some code from @spyhunter99 in #300 and noticed that I was not able to create an sqlite map due to this error.

Then i found that OSMMapTilePackager `build.gradle` does not have the required `org.xerial.sqlite-jdbc:3.7.2`, dependency which is declared in `pom.xml`

Jus adding the `compile group: 'org.xerial', name: 'sqlite-jdbc', version: '3.7.2'` under the dependencies block in `build.gradle` solves this error, and you can export a SQLite database with your map.

I don't know if this is really an error due to some step I didn't do, but it got some hours for me to notice this, and maybe could be of help for somebody.

Thanks in advance for your library, and sorry if this is not the proper way to solve this.

Regards,

**Comment by spyhunter99** [comment]
Great find. Probably an artifact of "get everything to build with gradle
because maven with android isn't working any more"

**Comment by spyhunter99** [comment]
Sorry you lost time on it, we really should have some unit tests for it
