### ISSUE TITLE
MyLocationNewOverlay&PolyLine disappear when zoomLevel > 21

### ISSUE THREAD

**Issue by gruelfin** [osmdroid/osmdroid#416]
When i add a MyLocationNewOverlay and a PolyLine and zoom in to a zoomlevel higher than 21, they both disappear.
Is this a wanted behaviour or a bug? 
And how to prevent them from disappearing?

**Comment by spyhunter99** [comment]
Known issue, zoom 20 is really the max we can support

**Comment by gruelfin** [comment]
> Known issue, zoom 20 is really the max we can support
Why is it like this?

**Comment by spyhunter99** [comment]
#329  #230 #114 #46 here are some related tickets when I searched the issue list for "zoom". Essentially, it's an android View class limitation that causes integer overflow

**Comment by spyhunter99** [comment]
I just added this bit to the FAQ for further clarity

https://github.com/osmdroid/osmdroid/wiki/FAQ#i-zoomed-past-level-20-and-the-everything-disappeared

**Comment by gruelfin** [comment]
I need this to display for Indoor Tiles. I hope there will be a solution in the future. Thanks for the FAQ!

**Comment by yang093** [comment]
Dear @spyhunter99, when will v5.6 be release? Is it really fix this issue as FAQ announcement? Appreciate if it is fixed soon :)

**Comment by wolojoli** [comment]
It was released yesterday.

**Comment by spyhunter99** [comment]
It should be functional for zoom 20 to 22. 22 is still the max
