### ISSUE TITLE
How to add click event for my location icon?

### ISSUE THREAD

**Issue by zhaoxuhui** [osmdroid/osmdroid#417]
I can open or close the location overlay by set the enabled.
`mLocationOverlay.setEnabled(false);`
`mLocationOverlay.setEnabled(true);`
But now I want to add the click event for the location icon for more functions,
for example when I click the icon it will pop up a info menu for more usages.
How do I deal with it?
Thanks~

**Comment by spyhunter99** [comment]
You'll probably have to extend the mylocation overlay class to add the
click listener,  or just make your own icon overlay or marker instance
