### ISSUE TITLE
Trying to display many polygons overlay

### ISSUE THREAD

**Issue by michelevirgilio** [osmdroid/osmdroid#42]
Hi, i need to overlay many (clickable) polygons on the map (over 5000), so the normal Polygon overlay is slow in performance. 
I've tried many ways with no luck.
My idea is to create a custom bitmap overlay, drawing on a bitmap canvas only polygons that are inside current bounding coordinates. 
Moreover i would to redraw the overlay only when the user has finished to zoom or panning, not during this operation, for performance reasons.
Can someone please point some help to me?
Thanks.

**Comment by spyhunter99** [comment]
If the data is static or doesn't update frequently, paint the data right on to the tiles.
