### ISSUE TITLE
java.lang.NoClassDefFoundError: org.osmdroid.views.MapController

### ISSUE THREAD

**Issue by ruiter** [osmdroid/osmdroid#422]
This error occurs only on devices < = 4.0. I cleared cache, already performed clean project but not solved.

help me.

**Comment by spyhunter99** [comment]
We test and support down to api8. Not sure what your issue is.  I'd this
with the sample osmdroid app or something you've created?

**Comment by spyhunter99** [comment]
ping, need more information to recreate the problem.
