### ISSUE TITLE
Osmdroid-android does not exists 

### ISSUE THREAD

**Issue by Rainexxx** [osmdroid/osmdroid#423]
Using string
`
dependencies {
    compile 'org.osmdroid:osmdroid-android:5.4.1:release@aar'
}
`
But, I get error "does not exists". Gradle modifies the filename to "osmdroid-android-5.4.1.aar" when trying to download from the repository

**Comment by spyhunter99** [comment]
http://central.maven.org/maven2/org/osmdroid/osmdroid-android/5.4.1/

Strange.  It's on central

**Comment by Rainexxx** [comment]
Gradle creates a link "http://central.maven.org/maven2/org/osmdroid/osmdroid-android/5.4.1/osmdroid-android-5.4.1.aar" for  'org.osmdroid:osmdroid-android:5.4.1:release@aar'. This file does not exists on central. Only to have the "osmdroid-android-5.4.1-release.aar", but  needed "osmdroid-android-5.4.1.aar".

**Comment by spyhunter99** [comment]
What version of gradle and the android gradle plugin are you using? There's
been a number of similar tickets recently. Trying to find some commonality
among them and to reproduce

**Comment by yoyo-san** [comment]
I have the same problem, gradle version 2.14.1 and android gradle plugin 2.2.0.
Not sure if intentional, but as Rainexxx mentioned, in versions under 5.4 there was a file named _osmdroid-android-x.y.aar_ which is not there in the latest (5.4+) versions. The easiest solution would probably be to upload this file as well, but I have no experience with maven and/or gradle, so I don't know if gradle should resolve 'org.osmdroid:osmdroid-android:5.4.1:release@aar' to 'http://central.maven.org/maven2/org/osmdroid/osmdroid-android/5.4.1/osmdroid-android-5.4.1-release.aar'

**Comment by spyhunter99** [comment]
It is supposed to, we have unit tests for it but it's possible something is incorrect

**Comment by spyhunter99** [comment]
I just made a new project using your exact setup and it worked just fine. The only different was the android plugin version
```
classpath 'com.android.tools.build:gradle:2.2.0-rc2'
```

Other than that, everything else was the same. Try deleting your projectHome/.gradle/ folder and try again?

**Comment by spyhunter99** [comment]
Oh, I also added mavenCentral to both buildScript and allProjects/dependencies

**Comment by yoyo-san** [comment]
This didn't work, but I found the clue in [this](https://github.com/osmdroid/osmdroid/issues/401#issuecomment-246973504) issue:

There was a problem when using OSMBonusPack 5.8.1, which is resolved by updating it to 5.9.
Thank you for help spyhunter99.

**Comment by moonandroid** [comment]
I also faced same issue with    compile 'org.osmdroid:osmdroid-android:5.4.1:release@aar'

Can you help me what need to do here ?

------------Root gradle:----------
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.2.0-rc2'
        classpath 'com.github.dcendents:android-maven-gradle-plugin:1.3'
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        jcenter()
        maven { url "https://jitpack.io" }
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
