### ISSUE TITLE
Pre 5.2 map tiles to SQLite routine

### ISSUE THREAD

**Issue by VictorPurMar** [osmdroid/osmdroid#425]
In the wiki we could read about to make an own routine to store your downloaded tiles to add in to the db file. 

In the Upgrade Guide

> Tiles that were already loaded in device....
> TBD do we leave it or delete it? Or run an import routine, then delete from local storage....

In the Offline Map Tiles

> Use the Cache Manager on device ( > version 5.2)
> TODO

How we can start with this? Any tip to develope it?
There are some files in the OSDroid project to help in this routine?

Thanks

**Comment by spyhunter99** [comment]
Thanks for the reminder. I've mocked up the methods but still need to test them

**Comment by spyhunter99** [comment]
Pushed to branch feature/#425 want to test it out or make suggestions to improve

**Comment by spyhunter99** [comment]
@VictorPurMar ping

**Comment by VictorPurMar** [comment]
Im not sure this code is getting the old file structure of pngs, like /osmdroid/tiles/Mapnik/..., to add they to the sql. Looks like it converts the old cache to a new sql cache? 

But is the old cache related to the png files directly? 

I was interested in convert the old png files to sql.  (I was using a zip with the mapnik to use it ofline but as my project is not released yet i can directly add a copy of the new database "cache.sql" to the app instead to do this)

Thanks for all & Sorry4delay

**Comment by spyhunter99** [comment]
I added a few different examples. The import cache function imports from the local file system into the cache database. The old cache was tiles stored in disk in whatever format they were downloaded in. The .tile extension was added just to make the gallery app ignore it but it is typically a png or jpg file.

**Comment by VictorPurMar** [comment]
When i press cache filesystem import in the "Import the file system cache into..." example, i see  the toast "Cache import [...] 0/0/0/0" .

No tiles imported. I have the Mapnik file placed in /osmdroid/tiles/Mapnik.... 
maybe i must set the "Mapnik" TileProvider before pressing the button?

**Comment by spyhunter99** [comment]
it's looking in getExternalStorageDir() + "/osmdroid/tiles/" which is usually /sdcard/osmdroid/tiles/. can you confirm that path?

**Comment by VictorPurMar** [comment]
/storage/emulated/0/osmdroid/tiles/Mapnik/....  its the route in the app. Its a diferent name for the same right?

**Comment by spyhunter99** [comment]
yes that's right. do you actually have tiles in /storage/emulated/0/osmdroid/tiles/Mapnik/?

should be something like
/storage/emulated/0/osmdroid/tiles/Mapnik/0/0/1.png

**Comment by VictorPurMar** [comment]
Yep yep exactly, it has stored tiles from /storage/emulated/0/osmdroid/tiles/Mapnik/0/0/1.png to 5/31/31.png

**Comment by spyhunter99** [comment]
Was there any log output to help me troubleshoot this? It seems to work over here so maybe i missed something

**Comment by VictorPurMar** [comment]
Sorry. Not basic error logs. There are any command implemented to see a deep log?

**Comment by VictorPurMar** [comment]
I think the file (Mapnik directory) is not passing by this line:
if (tileSources[i].isDirectory() && !tileSources[i].isHidden() && tileSources[i].isFile()

Method:
public int[] importFromFileCache(boolean removeFromFileSystem) {

Class: SqlTileWriter

**Comment by VictorPurMar** [comment]
tileSources[i].isDirectory() && tileSources[i].isFile()  ??? this is possible?

maybe:
if (tileSources[i].isDirectory() && !tileSources[i].isHidden() && !tileSources[i].isFile()

**Comment by spyhunter99** [comment]
usually a directory is a file. it's just special, try removing the check

**Comment by VictorPurMar** [comment]
Without this check is entering correctly.
I must quit also others "isFile()" checks:

But the method is still crashing at : final long y1 = Long.parseLong(y[yy].getName()); launching the exception.

Actually the method is : 
`    public int[] importFromFileCache(boolean removeFromFileSystem) {
        int[] ret = new int[] {0,0,0,0};
        //inserts
        //insert failures
        //deletes
        //delete failures
        File tilePathBase = OpenStreetMapTileProviderConstants.TILE_PATH_BASE;
        if (tilePathBase.exists()){
            File[] tileSources = tilePathBase.listFiles();
            if (tileSources!=null){
                for (int i=0; i<tileSources.length; i++){
                    if (tileSources[i].isDirectory() && !tileSources[i].isHidden()){
                        //proceed
                        File[] z = tileSources[i].listFiles();
                        if (z!=null)
                            for (int zz=0; zz<z.length; zz++){
                                if (z[zz].isDirectory() && !z[zz].isHidden()){
                                    File[] x = z[zz].listFiles();
                                    if (x!=null)
                                        for (int xx=0; xx<x.length; xx++){
                                            if (x[xx].isDirectory() && !x[xx].isHidden()){
                                                File[] y = x[xx].listFiles();
                                                if (x!=null)
                                                    for (int yy=0; yy<y.length; yy++){
                                                        if (!y[yy].isHidden() && y[yy].isFile() && !y[yy].isDirectory()){

                                                            try {
                                                                ContentValues cv = new ContentValues();
                                                                final long x1 = Long.parseLong(x[xx].getName());
                                                                final long y1 = Long.parseLong(y[yy].getName());
                                                                final long z1 = Long.parseLong(z[zz].getName());
                                                                final long index = ((z1 << z1) + x1 << z1) + y1;
                                                                cv.put(DatabaseFileArchive.COLUMN_PROVIDER, tileSources[i].getName());
                                                                BufferedInputStream bis = new BufferedInputStream(new FileInputStream(y[yy]));

                                                                List<Byte> list = new ArrayList<Byte>();
                                                                //ByteArrayBuffer baf = new ByteArrayBuffer(500);
                                                                int current = 0;
                                                                while ((current = bis.read()) != -1) {
                                                                    list.add((byte) current);
                                                                }

                                                                byte[] bits = new byte[list.size()];
                                                                for (int bi = 0; bi < list.size(); bi++) bits[bi] = list.get(bi);
                                                                cv.put(DatabaseFileArchive.COLUMN_KEY, index);
                                                                cv.put(DatabaseFileArchive.COLUMN_TILE, bits);

                                                                db.insert(TABLE, null, cv);
                                                                Log.d(IMapView.LOGTAG, "tile inserted " + tileSources[i].getName()+"/"+  z1 + "/" + x1 + "/" + y1);
                                                                ret[0]++;
                                                                if (removeFromFileSystem){
                                                                    try {
                                                                        y[yy].delete();
                                                                        ret[2]++;;
                                                                    }catch (Exception ex){
                                                                        ret[3]++;;
                                                                    }
                                                                }
                                                            } catch (Throwable ex) {
                                                                //note, although we check for db null state at the beginning of this method, it's possible for the
                                                                //db to be closed during the execution of this method
                                                                Log.e(IMapView.LOGTAG, "Unable to store cached tile from " + tileSources[i].getName() + " db is " +(db==null ? "null":"not null"), ex);
                                                                ret[1]++;
                                                            }
                                                        }
                                                    }
                                            }
                                        }
                                }
                            }



                    } else {
                        //it's a file, nothing for us to do here
                    }
                }
            }

        }
        return ret;
    }`

**Comment by spyhunter99** [comment]
ahh i see, needs to be
y[yy].getName().substring(0, y[yy].getName().indexOf("."))

**Comment by VictorPurMar** [comment]
Yep... now i can saw the message "Cache import [...] 153/0/153/0" the first time (second 0/0/0/0 i suposse they were deleted...)

I do that after a db purge (0 MB) ....

But the db was still 0Mb... they where not imported but earsed. (Only the files... not the directory structure...)

**Comment by spyhunter99** [comment]
so the import sample has a flag to delete the files after importing into the database. the sample is set to true. The database is in  getExternalStorageDir() + "/osmdroid/tiles/cache.db" i think. It was still 0MB?

i can put some code in there to clean up the directories too. i'm puzzled as to why it didn't insert

**Comment by VictorPurMar** [comment]
Yep... Its placed there. And yep 0mb ... Well 400 kb i think from the assets 2 depth maps

**Comment by spyhunter99** [comment]
i just pushed some code. primarily the updates from this discussion and some additional debugging code

**Comment by VictorPurMar** [comment]
Looks its working propperly... maybe i dont wait to the clean cache process was finished. I tryied 3 more times all working. 
👍

**Comment by spyhunter99** [comment]
keep this open until the branch has been merged

**Comment by spyhunter99** [comment]
and i merged it last night. never mind
