### ISSUE TITLE
CacheManager.cleanAreaAsync not working

### ISSUE THREAD

**Issue by MKergall** [osmdroid/osmdroid#426]
When the MapView is using the SqlTileWriter (now standard), CacheManager.cleanAreaAsync is not deleting anything. Number of deleted tiles is always zero. 

Root cause: in CleaningTask.cleanArea, there are two errors: 
1) the test to check tile existence is file-based: if (file.exists()) 
2) and the action is file-based: file.delete();

This is because code is still targeting file-based TileWriter. 
Solutions: 

For 1) : Do the test with: mTileWriter.exists(ITileSource pTileSource, MapTile pTile)

For 2) : In IFilesystemCache abstract class, add an abstract method: remove(TileSource, MapTile), 
then implements it properly in TileWriter and in SqlTileWriter.

**Comment by spyhunter99** [comment]
merged pending ci test. @MKergall if you have time, can you test this? we don't have any automated tests for this

**Comment by MKergall** [comment]
Not tested, but looking at the code, it seems to be OK.

**Comment by spyhunter99** [comment]
merged for 5.6
