### ISSUE TITLE
ZoomToBoundingBox not working

### ISSUE THREAD

**Issue by hlaurent** [osmdroid/osmdroid#429]
Just updated to 5.4.1
ZoomtoBounding box does not look to work. It sets the zoom to 0.

If maxLat,maxLon,minLat,minLon are doubles.
BoundingBox boundingBox = new BoundingBox(maxLat,maxLon,minLat,minLon);
mapView.zoomToBoundingBox(boundingBox, true);

**Comment by spyhunter99** [comment]
are you saying that zoomToBoundingBox works for doubles or ints or neither?

**Comment by spyhunter99** [comment]
looks like it doesn't work until after the map is ready. I'm not too familiar with that bit of code but the behavior i'm seeing is:

- if the destination zoom is significantly greater than the current zoom, it centers and zooms in about half way between current and destination zoom
- if the destination zoom is equal to or less than the current zoom, it centers and zooms to the target zoom level.

calling it right on map start or before the map is render appears to not trigger

**Comment by hlaurent** [comment]
Making sure the map is ready, it is now working with doubles. Thank you for your help.
