### ISSUE TITLE
MapBox source not authorized with 5.4.1?

### ISSUE THREAD

**Issue by hlaurent** [osmdroid/osmdroid#430]
I just upgraded to 5.4.1 and MapBox is no longer working.
I am getting : W/OsmDroid: Problem downloading MapTile: /8/125/91 HTTP response: Unauthorized
It used to work on 5.1.

I use the following code:
in the Manifest:
meta-data android:name="MAPBOX_MAPID" android:value="MY_KEY"
meta-data android:name="ACCESS_TOKEN" android:value="MY_TOKEN"

In the code:
final MapBoxTileSource tileSource = new MapBoxTileSource();
tileSource.retrieveAccessToken(ctx);
tileSource.retrieveMapBoxMapId(ctx);
mapView.setTileSource(tileSource);

**Comment by hlaurent** [comment]
I set 
OpenStreetMapTileProviderConstants.DEBUG_TILE_PROVIDERS = true;
OpenStreetMapTileProviderConstants.DEBUGMODE = true;
to investigate further.

It looks like the token is being passed.

If I change my code to the second method :
tileSource.setAccessToken("MY_TOKEN");
tileSource.setMapboxMapid("MY_KEY");

It does work

**Comment by MKergall** [comment]
Now: 
`meta-data android:name="MAPBOX_ACCESS_TOKEN" android:value="MY_TOKEN"
`

**Comment by spyhunter99** [comment]
@hlaurent, yup what @MKergall said. Covered (at least it should be) in the upgrade guide on the wiki at https://github.com/osmdroid/osmdroid/wiki/Upgrade-Guide

**Comment by spyhunter99** [comment]
to add, the sample app is working ok. Sample is called split screen with mapbox

**Comment by hlaurent** [comment]
Thank you, I missed it in the upgrade guide.
