### ISSUE TITLE
Cachemanager progress bar issue

### ISSUE THREAD

**Issue by rbrueckner11** [osmdroid/osmdroid#431]
There must be an issue with the cachemanager. When downloading tiles the progress bar of the cachemanager's default progress window moves to 100% after the download of the first tile layer/zoom level. The cachemanager continues downloading and is counting up the zoom level according to it's progress, however, the progress bar remains at 100%. The progress bar actually should reflect the progress of the entire download process including all zoom levels.

**Comment by spyhunter99** [comment]
I'm not seeing that behavior with the sample app. what version of osmdroid are you using?

**Comment by MKergall** [comment]
Probably the same issue than #427
As the number of tiles is wrong, the progress bar is wrong as well.

**Comment by spyhunter99** [comment]
ahh roger. Probably time to cut a new version

@neilboyd fire when ready IMO

**Comment by rbrueckner11** [comment]
I am using osmdroid version 5.4.1

**Comment by spyhunter99** [comment]
should be fixed in v5.5
