### ISSUE TITLE
Setting the tiles cache path in 5.4.1

### ISSUE THREAD

**Issue by hlaurent** [osmdroid/osmdroid#433]
I am using 5.4.1 and trying to change the tiles cache path to:  /storage/emulated/0/test4osmdroid/tiles
The cachePath is stored in a sharedPreference as: /storage/emulated/0/test4osmdroid/tiles

I try to set the path running in onCreate() of my main Activity:
String defaultCachePath = Environment.getExternalStorageDirectory() + "/osmdroid/tiles";
String cachePath = sharedPrefs.getString("osmdroid_cache_path", defaultCachePath);
**OpenStreetMapTileProviderConstants.setCachePath(cachePath);**
Log.d(TAG, "osmdroid_cache_path: " + OpenStreetMapTileProviderConstants.TILE_PATH_BASE.getAbsolutePath());

The  Log is showing the correct path : osmdroid_cache_path: /storage/emulated/0/test4osmdroid/tiles

If I check that directory, 2 files have been created : cache.db and cache.db-journal

But When I run the app, the cache.db file does not grow in size while the one in /storage/emulated/0/osmdroid/tiles still does.

If I delete the cache.db file in /storage/emulated/0/osmdroid/tiles, the app shows errors proving this one is still being used.

Any idea as to what I am doing wrong?

**Comment by spyhunter99** [comment]
You have to set the cache locations before the map view is created. That's before the layout is inflated

**Comment by hlaurent** [comment]
Thank you, it is now working just fine.
I was initially setting the constants after inflating the layout.
