### ISSUE TITLE
About a renewal of cache of OpenStreetMap tile.

### ISSUE THREAD

**Issue by sdusdu** [osmdroid/osmdroid#434]
In unskillful English, sorry
When a OpenStreetMap tile was renewed, is cache in a relevant part also renewed?

**Comment by spyhunter99** [comment]
when a tile is expired and needed by the map view, it will attempt to get an updated tile. If the new tile can't be refreshed, then the cached version is displayed until a new one can be retrieved

**Comment by sdusdu** [comment]
Thank you very much!

**Comment by sdusdu** [comment]
Thank you very much
