### ISSUE TITLE
How do I download tiles in SQLite database?

### ISSUE THREAD

**Issue by zhaoxuhui** [osmdroid/osmdroid#437]
The OsnDroid now is using SQLite as the default cache.I want to download tiles in SQLite too,so to use in offline mode.How do I use CacheManager to realize this function?How to custom the download path?
I've found that there are some differences from earlier version of OsmDroid. Thanks~

**Comment by spyhunter99** [comment]
See the sample app, there's a bunch of examples. And the wiki, and mobac.

**Comment by spyhunter99** [comment]
You want the sample `SampleCacheDownloaderArchive` 
https://github.com/osmdroid/osmdroid/blob/master/OpenStreetMapViewer/src/main/java/org/osmdroid/samplefragments/SampleCacheDownloaderArchive.java

Use with caution, it's easy to get banned to downloading the whole planet or something equally as ridiculous. And please see the wiki on updating user agents. It's important
