### ISSUE TITLE
Positioning problem of a window on the MapView, API 24 and Osmdroid 5.5

### ISSUE THREAD

**Issue by Conan42** [osmdroid/osmdroid#444]
Since using API 24, I have a weird thing: the window or I create a Popumenu in a small window on the MapView is the top left while I provided the well Geopoint. This works well with API 23. Have you any idea? Thank you in advance. Here's the code:

```
@Override
public boolean longPressHelper(GeoPoint p) {
    this.p = p;
    return showContextMenu(p);
}

private boolean showContextMenu( GeoPoint geoPosition ) {
    MenuInflater inflater = activity.getMenuInflater();
    this.removeView( tempView );
    View view = createPopupMenuView( geoPosition );
    PopupMenu menu = new PopupMenu( context , view );

    if( numSelect > 0 && numSelectWayPoint == 0 ) {
        inflater.inflate( R.menu.context2_menu, menu.getMenu() );
    .....

private View createPopupMenuView( GeoPoint geoPoint ) {
    if( tempView != null ) this.removeView( tempView );

    tempView = new View( context );

    MapView.LayoutParams lp = new MapView.LayoutParams( 0 , 0 , geoPoint , MapView.LayoutParams.CENTER , 0 , 0 );
    tempView.setVisibility(View.VISIBLE);

    this.addView( tempView, lp );
    return tempView;
}
```

**Comment by spyhunter99** [comment]
Would it be possible to get you to record a screencast of this? I'm not sure i'm following you

**Comment by spyhunter99** [comment]
or a screenshot or whatever? I'm looking at the avd24 and it's looks ok for the top right menu, but i'm not sure i understand what you are referring too

**Comment by spyhunter99** [comment]
after reviewing the screenshots, it looks like there is a single tap listener or something like that on a map icon that opens a menu. On older APIs, the menu pops up around the same location as the icon. On API24 it displays on top left.

Is the icon a member of an ItemizedIconOverlay or a Marker class?

**Comment by Conan42** [comment]
no, I customizes a class Overlay. But do not look at the icon, the context
menu does not appear on the touch location from API24. I think that there
is some thing that to change in the line:

MapView.LayoutParams lp = new MapView.LayoutParams( 0 , 0 , geoPoint ,
MapView.LayoutParams.CENTER , 0 , 0 );

geoPoint is not used correctly


2016-10-23 15:13 GMT+02:00 spyhunter99 <notifications@github.com>:

**Comment by Conan42** [comment]
Here are the screenshots, API 23 is good (position GeoPoint), API24 is top
left

2016-10-22 2:08 GMT+02:00 spyhunter99 <notifications@github.com>:

**Comment by spyhunter99** [comment]
operation timeout. please reopen or comment back if you have further questions
