### ISSUE TITLE
Tile caching - debug and control

### ISSUE THREAD

**Issue by atoone** [osmdroid/osmdroid#445]
I'm using the 5.5 release, with Mapnik tile source and default cache settings. I'm examining the same area (about 500m across) and zooming through the three highest magnifications.

When online, all tiles are retrieved and the map view works flawlessly. If I return to the app 12 hours later, offline, only a handful of tiles are cached at the lowest zoom, and zooming in further only uses scaled tiles.

The app appears to be retaining far fewer tiles than I expected and I'm not sure the best way to debug what is being cached, or to control it. Ultimately, I'd like a Google Maps style 'offline map' facility (and may be in a position to implement this depending on my business), but short term, I'd like to ensure that tiles at a certain zoom level are cached for a predictable period.

As I'm working within a small area, I assumed that the cache would easily cover the tiles required?

**Comment by spyhunter99** [comment]
do you mean 500 miles or 500 meters?

there's some info here for debugging tile loading

https://github.com/osmdroid/osmdroid/wiki/FAQ#debugging-tile-loading-issues

**Comment by atoone** [comment]
500 meters. Essentially, just a small number of tiles at the three highest zoom levels and they don't appear to be cached. I'll enable the debug for the tile source to see what it's doing.

**Comment by cfsbhawkins** [comment]
What map source are you using? The expiry code comes from a header in the mapnik response. Its possible the response is short.

**Comment by spyhunter99** [comment]
interesting, can you get me a bounding box and zoom levels for the area affected?

**Comment by atoone** [comment]
Around 52.2742, 0.21130 three highest zoom levels for Mapnik, the default Tile source

**Comment by cfsbhawkins** [comment]
I have seen OpenStreetMap keep low expiration times. If you browse to one of the URLs for a tile in question in chrome and open the developer console, you can see the headers. You will see one for expiration. It should be a date or long since epoch time. I bet the date is short, in the end of my company created our own mapnik servers and I configured the expiration based on the zoom levels to keep tiles almost a year out for the lower levels. Osm runs code to keep the database size down to delete rows older than the expiration date.

**Comment by spyhunter99** [comment]
What's the time delta from the initial tile load and cache to when you go into offline mode? I just made a sample and test case for this. honestly, we should have had the test ages ago, but it appears to work and pass. I'll wait for travis before merging.

**Comment by spyhunter99** [comment]
@cfsbhawkins i noticed that today too, it was a very fast expiration time. We may need to relook at the algorithms for purging the database of expired tiles. If a tile is expired and there's no network connection (or a newer one doesn't exist), we shouldn't purge the tile

**Comment by spyhunter99** [comment]
merged with test cases. it probably needs more work to handle the "i was online but am now offline, don't purge the cache" scenario

**Comment by spyhunter99** [comment]
@atoone we the map starts up and let's just say that the database is bigger than cache is supposed to be, what's the preference for trimming the cache?

 - delete the oldest tiles first? (tile source independent)
 - delete expired tiles first?

i'm not sure what's right here

**Comment by spyhunter99** [comment]
@atoone was this problem present with previous versions? I'm thinking it was and it's isolated to the mapnik/osm tile source.

**Comment by atoone** [comment]
@spyhunter99 Yes, I suspect that it was present with previous versions, but the change to the SQLite database was a distraction that muddied the water a little. It might be handy to have some sort of log/debug/metric to indicate when tiles come in with unexpectedly short expiration times?

As I've been working within a small area for testing purposes, I don't expect my database is getting large enough to require trimming - again this is a metric it would be helpful to expose. It might help to have a 'last seen' timestamp for tiles so you could trim the least-recently used tiles rather than those that have been in regular use for a long time.

It makes a *lot* of sense to not expire tiles when there is no network connection. If I've recently seen a tile, I'd only expect it to go away when a newer one can immediately replace it. Most of my use cases revolve around field work, so suddenly having maps disappear when you have no network connection is distressing. Of course there is then the challenge of 'partial connection' where you may be connected to a hotspot, but still cannot get a link to the server.

Perhaps the answer here is not to use expiry time at all for purging tiles from the database, but use it purely as a flag to indicate when an attempt should be made to get a fresher tile? If one can be retrieved then it replaces the old one, but otherwise the cache is legitimately used?

**Comment by spyhunter99** [comment]
found something. MapTileDownloader has a public static boolean for debug logging, that may hold the clue

**Comment by spyhunter99** [comment]
i just added some more logging, looks like mapnik is returning a 60 hr window give or take for tile expiration

**Comment by spyhunter99** [comment]
To address your other concerns. 

The way the sqlwriter is right now, it only trims the database if needed (the database is bigger than the user/developer selected max size or the amount of free disk space).

If you're going to be offline for an extended period, consider using the cache manager to produce an archival database (similar to how mobac works). This will make sure that you get all the tiles for the given area and store them in a database which will never purge or expire.

> Perhaps the answer here is not to use expiry time at all for purging tiles from the database, but use it purely as a flag to indicate when an attempt should be made to get a fresher tile? If one can be retrieved then it replaces the old one, but otherwise the cache is legitimately used?

This is the current behavior. The MapTileProviderBase attempts to load from all local sources. if the tile is expired, it will be a new one will attempt to be loaded, but it should use the expired in the event of a load failure
