### ISSUE TITLE
Not show all elements with MapView in layout and in App

### ISSUE THREAD

**Issue by fedka27** [osmdroid/osmdroid#452]
When added MapView in layout with any parent not show all elements in layout and in application too.
Android Studio v.2.2.2
. . .
compile 'org.osmdroid:osmdroid-android:5.5:release@aar'
. . .

How to fix ?
Thanks!
![image](https://cloud.githubusercontent.com/assets/15886871/19600952/6b2785dc-97d1-11e6-8df0-4e4e9798280d.png)
![image](https://cloud.githubusercontent.com/assets/15886871/19601005/9dcbe6a4-97d1-11e6-8aaf-85a0c5bdb43d.png)

**Comment by spyhunter99** [comment]
related #439

**Comment by spyhunter99** [comment]
working ok over here with 2.2.1 using the api 24 renderer. Not sure. The preview thing has always been flaky. I've learned to live without it. It is nice to have but never something i've relied on

**Comment by spyhunter99** [comment]
https://www.reddit.com/r/androiddev/comments/58ykvo/android_layout_editor_99_of_the_time/

**Comment by spyhunter99** [comment]
works fine here. reopen if its still a problem

**Comment by fedka27** [comment]
Thanks. 
I to reinstalled Android Studio, updated her and this helped me.
