### ISSUE TITLE
Moving tiles to database possible glitch?

### ISSUE THREAD

**Issue by InI4** [osmdroid/osmdroid#455]
It seems I just merged the "moving tiles from filesystem to database" stuff in my private branch.

I observer the following 3 issues.

1. It takes long, making the map not starting up for a while. I see lots of those: `10-23 12:30:56.980 19168-20993/de.spieleck.app.badgers.debug W/SQLiteConnectionPool: The connection pool for database '+storage+emulated+0+osmdroid+tiles+cache_db' has been unable to grant a connection to thread 324302 (sqlcache) with flags 0x1 for 28.005001 seconds.
                                                                                     Connections: 1 active, 0 idle, 0 available.
                                                                                     
                                                                                     Requests in progress:
                                                                                       executeForCursorWindow started 28075ms ago - running, sql="SELECT tile, expires FROM tiles WHERE key = 16675580836 and provider = 'Mapnik'"`

2. It does not really help, rather hurt, as long as there are other apps on my phone, which use an older version of osmdroid. Don't  those just lose their cache and reload stuff new on next start?

3. Well, maybe not, cause the files in the file system are not gone. Well, this interacts with 2, so I wonder, when does this deletion happen? At least the database import does not happen again on next start.

**Comment by spyhunter99** [comment]
1) good point, i'll add it to the javadocs. It shouldn't be called from the UI thread. Also when looking at the code, there's some optimizations to make, specifically skipping importing a tile if it's already been imported. what API level is your device? i haven't seen that message before

2) the sql based solution is generally faster

3) they can be removed via `importFromFileCache(true)` The database import is not called anywhere some osmdroid's code. It's up to the integrator (something building an app using osmdroid) to determine what's best for their application. The importFromFileCache mechanism isn't called on startup

**Comment by InI4** [comment]
Thanks for explaining.

about 1) I am 95% sure this was a 4.2.2 device. It doesn't happen anymore right now :-(

**Comment by spyhunter99** [comment]
k, reopen if the issue comes up again
