### ISSUE TITLE
Description on how to add osmdroid library via gradle seems incorrect

### ISSUE THREAD

**Issue by alexvanderlinden** [osmdroid/osmdroid#456]
Please take a look at this page:
https://github.com/osmdroid/osmdroid/wiki/How-to-add-the-osmdroid-library-via-Gradle

It seems the key-word 'release' is missing at this page as discussed in this issue:
https://github.com/MKergall/osmbonuspack/issues/249

I was puzzled a bit for a while, because
For me these statements do work:

- compile 'org.osmdroid:osmdroid-android:5.2@aar'
- compile 'org.osmdroid:osmdroid-android:5.4.1:release@aar'

And this statement does not work:

- compile 'org.osmdroid:osmdroid-android:5.4.1@aar'

**Comment by spyhunter99** [comment]
thanks. fixed
