### ISSUE TITLE
Feature (working on it): overlay for simple and fast display of several K's of points

### ISSUE THREAD

**Issue by miguel-porto** [osmdroid/osmdroid#457]
Hi,
I'm working on an overlay to enable adding several thousands of points without significant performance issues. It has fairly good performance with 100 K points full zoomed out, and there are no performance issues when zoomed in, even with 1 M points.
I'm doing it fairly simple focusing on performance, cause I really needed something to display M's of points, and nothing more, so, it only draws the basic shapes with basic styling.
I'll be posting the code [here](https://github.com/miguel-porto/osmdroid).
More details later, still not finished.
Cheers!

**Comment by spyhunter99** [comment]
Nice! I was able to get in the 3k range on my S5 using the itemized icon overlay.
