### ISSUE TITLE
Projection.fromPixels does not account for map orientation/rotation

### ISSUE THREAD

**Issue by spyhunter99** [osmdroid/osmdroid#459]

**Comment by spyhunter99** [comment]
fixed on #155

**Comment by monsieurtanuki** [comment]
> Projection.fromPixels does not account for map orientation/rotation

@spyhunter99 Definitely. Should it? I'm not sure.

I agree that the name of the methods are sometimes source of confusion. We are trapped between historical reasons and compatibility consistency!
* We can agree on the fact that `toPixels` and `fromPixels` should have the same behavior, map-orientation-wise
* Usually, the map rotation is displayed by a `Matrix` applied to the `MapView`'s `Canvas`, therefore we don't need `toPixels` to handle the map-orientation
* Methods `rotateAndScalePoint` and `unrotateAndScalePoint` handle the extra step.

My suggestion: either close this issue, or take enough time to give methods more appropriated names - which doesn't look easy during the current collision of PRs.
