### ISSUE TITLE
i have some problems when i draw a polygon on the map!

### ISSUE THREAD

**Issue by jayhuang861019** [osmdroid/osmdroid#461]
i create a polygon in my project,but it refresh very slowly when i zoomin to level 15 or upper! 
the Hardware acceleration is on!!!!

**Comment by MKergall** [comment]
Turn HW acceleration off. At close zoom levels, Polygon and Polyline will not work at all.

**Comment by spyhunter99** [comment]
Just turn it off for the map view.  5.6 will have it turned off by default

**Comment by jayhuang861019** [comment]
thanx! but when i trun it off ,the map rendering will become  slow !!

**Comment by spyhunter99** [comment]
how slow?

**Comment by spyhunter99** [comment]
ping timeout. reopen if this is still an issue for you

**Comment by spyhunter99** [comment]
related #353
