### ISSUE TITLE
I have cached offlinemap, but there are some problems

### ISSUE THREAD

**Issue by juemuren4449** [osmdroid/osmdroid#464]
I have cached offlinemap, but when there is no internet, the map can not load from cache.db immediately.
When I scroll the map or zoom in, map came out, but map may be unclear unless I scroll it out then back.
My way is just like the sample SampleCacheDownloader.java, can anyone give me some advice? Thanks !

**Comment by neilboyd** [comment]
This looks similar to #354

**Comment by juemuren4449** [comment]
@neilboyd You are right, it is similar, so there is no way to do with is for now? 😢

**Comment by spyhunter99** [comment]
#448 #445 related issues

**Comment by spyhunter99** [comment]
@juemuren4449  what version over osmdroid are you using?

**Comment by juemuren4449** [comment]
5.5

**Comment by spyhunter99** [comment]
which map source are you using? Is it possible that the tiles are expiring before you go to view them? If so, master has some work to help combat that. It may be worth trying building osmdroid from source and using the latest and greatest. We also now have a test case for this issue. It's possible there still is a bug though

**Comment by juemuren4449** [comment]
I use googlemap tile. I download them and cut off the net, then the map can not load from cache.db immediately.

**Comment by spyhunter99** [comment]
how are you using google map tiles with osmdroid?

**Comment by spyhunter99** [comment]
Try turning on tile debugging, it will log every tile inserted into the database. Then once you're offline, see if you can trap any of the error conditions. I'm not entirely sure what's happening at this point. Might want to check the tile expiration date that the tile source is providing. It's possible it's being flagged as expired and then being removed immediately

**Comment by spyhunter99** [comment]
probably related to 496 and the fixed queue size for tile loading. Try increasing the queue by either programmatically creating the MapTileProvider or by using the configuration class to just the queue size. Reopen if it's still an issue.
