### ISSUE TITLE
Scroller in MapView never finishes

### ISSUE THREAD

**Issue by wolojoli** [osmdroid/osmdroid#465]
When mMapView.getScroller().startScroll(xStart, yStart, mercatorPoint.x - xStart, mercatorPoint.y - yStart, ANIMATION_DURATION_DEFAULT);
is called and the dx and dy values are both zero, the scroller will start but never end. This causes an infinite loop.

You can reproduce this with a Mapview which uses the MyLocationNewOverlay. When the location is fixed, and a zoom action in initiated via the zoom-buttons, MapView.setZoom will call getController().animateTo(geoPoint); which will initiate the loop.

**Comment by spyhunter99** [comment]
how do you suggest that we fix this?

**Comment by spyhunter99** [comment]
#411 looks like this is the same issue

**Comment by InI4** [comment]
Could be #411. However I cannot deliver stripped down code to show that. I have suggested a workaround there. A workaround, that I honestly do not really understand, but it helps and I do not observe any issues in my app.

**Comment by wolojoli** [comment]
Suggested solution is to replace the following line (in MapController.java:199)
```java

mMapView.getScroller().startScroll(xStart, yStart, mercatorPoint.x - xStart,
		mercatorPoint.y - yStart, ANIMATION_DURATION_DEFAULT);

```
with:
```java

final int dx = mercatorPoint.x - xStart;
final int dy = mercatorPoint.y - yStart;

if(dx != 0 || dy != 0) {
	mMapView.getScroller().startScroll(xStart, yStart, dx, dy, ANIMATION_DURATION_DEFAULT);
	mMapView.postInvalidate();
}

```

**Comment by InI4** [comment]
I've put that in my local test branch and it looks fine here. Beware of too many postInvalidate().

**Comment by spyhunter99** [comment]
pushed and merged., it appears to work. you may want to test it again off of master before we cut the version
