### ISSUE TITLE
Declare Overlay.draw as public

### ISSUE THREAD

**Issue by MKergall** [osmdroid/osmdroid#466]
It's currently protected. 

Some use cases for this change: 
- I got the issue when implementing the FolderOverlay. I found a trick by reusing the  OverlayManager. 
- I also got the issue for Marker Clustering. So I set Marker.draw as public. 
- Now, I want to implement a variant of FolderOverlay handling z-index: impossible to implement the draw method. 

Solution: declare Overlay.draw as public (and apply the same to all its sub-classes).

**Comment by spyhunter99** [comment]
I think you have write access, go ahead and do it

**Comment by spyhunter99** [comment]
merged

**Comment by MKergall** [comment]
So you already did it. Spy, you are going too fast :-)
Thanks.
