### ISSUE TITLE
"mLocationOverlay" Symbol cannot be resolved.

### ISSUE THREAD

**Issue by TheGlave** [osmdroid/osmdroid#467]
Hello,

i want to use your "MyLocationOverlay" but I think I misunderstood something in the tutorial. My project cannot resolve the symbol "mLocationOverlay". Do you know what the problem might be?

Everthing in this code works fine, except the last part under "My Location":

>     @Override
>     public void onCreate(Bundle savedInstanceState) {
>         super.onCreate(savedInstanceState);
>         setContentView(R.layout.activity_main);
>         org.osmdroid.tileprovider.constants.OpenStreetMapTileProviderConstants.setUserAgentValue(BuildConfig.APPLICATION_ID);
>         if (Build.VERSION.SDK_INT >= 23) {
>             checkPermissions();
>         }
>         MapView map = (MapView) findViewById(R.id.map);
>         map.setTileSource(TileSourceFactory.MAPNIK);
> 
>         //Zoom-Buttons:
>         map.setTilesScaledToDpi(true);
>         map.setMaxZoomLevel(25);
>         map.setBuiltInZoomControls(true);
>         map.setMultiTouchControls(true);
> 
>         //Default-Coordinates
>         IMapController mapController = map.getController();
>         mapController.setZoom(12);
>         GeoPoint startPoint = new GeoPoint(51.4344079, 6.780487094074488);
>         mapController.setCenter(startPoint);
> 
>         //My Location
>         this.mLocationOverlay = new MyLocationNewOverlay(new GpsMyLocationProvider(context),map);
>         this.mLocationOverlay.enableMyLocation();
>         map.getOverlays().add(this.mLocationOverlay);
>     }

**Comment by spyhunter99** [comment]
Can you show the declaration of `mLocationOverlay`?

**Comment by TheGlave** [comment]
I copied it from the tutorial. Like in the tutorial there is no further declaration and I would know how to write it. Sorry I am not a very experienced programmer. So what lines are missing?

**Comment by spyhunter99** [comment]
can you link me to the tutorial. it probably has a typo

**Comment by TheGlave** [comment]
https://github.com/osmdroid/osmdroid/wiki/How%20to%20use%20the%20osmdroid%20library#how-to-add-the-my-location-overlay

**Comment by spyhunter99** [comment]
Got it. the data type is "MyLocationNewOverlay".

So to fix your code, stick this near the top of your .java file `MyLocationNewOverlay mLocationOverlay;`

**Comment by TheGlave** [comment]
That fixed it. Thank you. Yet it still cannot resolve the symbol "context" from the same line. Android studio suggests to create a local variable "Context context". When I do it, it complains that the variable might not have been initialized, which I dont know how to do exactly.

**Comment by spyhunter99** [comment]
yeah not an osmdroid thing. it's an android thing. You can use "this" if your class is an activity. See the android docs

**Comment by TheGlave** [comment]
At least the app starts now with using "this". Nevertheless there is no myLocationOverlay anywhere, so I checked out the osmdroid sample and it is also not in the view where it is supposed to be, according to the description. [(Image of the second example view)](http://www.pic-upload.de/view-32090481/OSMdroid.png.html)

**Comment by TheGlave** [comment]
Nevermind, I expected the overylay to be a button that you can press, that will you center the map on your location, when actually it looks like [this](http://www.pic-upload.de/view-32090653/MyLocationOverlay.png.html).

**Comment by spyhunter99** [comment]
please consider installing the sample application, then look at the corresponding source code. There is an example of "center map on my location" along with icons you can borrow too
