### ISSUE TITLE
MyLocationOverlay behaving strangely

### ISSUE THREAD

**Issue by TheGlave** [osmdroid/osmdroid#471]
I am trying to extract latitude and longitude out of the GpsMyLocationProvider with this code:

```
        this.mLocationOverlay = new MyLocationNewOverlay(new GpsMyLocationProvider(this),map);
        this.mLocationOverlay.enableMyLocation();
        map.getOverlays().add(this.mLocationOverlay);

        double latitude = this.mLocationOverlay.getMyLocationProvider().getLastKnownLocation().getLatitude();
        double longitude = this.mLocationOverlay.getMyLocationProvider().getLastKnownLocation().getLongitude();
```
As soon as it gets to the last two lines, the app crashes with this exception:

`    Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'double android.location.Location.getLatitude()' on a null object reference`

As debugging confirms, the variables mLatitude and mLongitude I get from the Location provider are null.
The strangest part though is, if I close the emulator completely and restart the app, I have the mLocationOverlay on the map, on the exact same coordinates I put in my emulator as my location. If I refresh the activity or restart the app without restarting the emulator, the overlay does not appear. 

Does someone know how to make sense out of this?

**Comment by spyhunter99** [comment]
is gps enabled on the device? does the device even have gps? if it's api23+ does it have fine location permission?

**Comment by TheGlave** [comment]
Yes to all 3.

1. The GPS is enabled as you can see [here](http://www.pic-upload.de/view-32096977/permissions.png.html). The App even asks for the permission on the first startup or when it is disabled. 

2. The device is an emulator of Android Studio. [This ](http://www.pic-upload.de/view-32096989/settings.png.html)is the GPS-Location I put into the emulator. 
As I described in my initial post, the device recognizes this Location and puts the overlay on the map, as can be seen [here](http://www.pic-upload.de/view-32097000/mylocation.png.html), but ONLY when I restarted the whole emulator on the first startup of the app.
If I only restart the app it wont be there. If go into another activity of my app and come back to the map it will be gone.

3. These lines are in my manifest:
` <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />`
`<uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />`

**Comment by spyhunter99** [comment]
I've found that the emulator's "Set location" button is not a continuous function. That is, you have to periodically set the location in order for everything to work correctly. Normal gps spits out a lat/lon every 1 second. The emulator only spits it out when you hit the button. Does that make sense?

**Comment by spyhunter99** [comment]
@TheGlave still an issue?

**Comment by spyhunter99** [comment]
ping timeout, reopen if this is still an issue
