### ISSUE TITLE
Random crash when displaying a map

### ISSUE THREAD

**Issue by tartina** [osmdroid/osmdroid#477]
Sometimes I have crashes when viewing maps with a SimpleLocationOverlay, it doesn't happen always, but every 3 or 4 visualization of different or same maps.
It happens in Android 4.4.4 and 6.0.1, I didn't test other versions.
This is some of the code:
		// Map
		double lat = order.getLatitude();
		double lng = order.getLongitude();
		SimpleLocationOverlay slo = new SimpleLocationOverlay(this);
		IMapController mapController = map.getController();
		startPoint = new GeoPoint(lat, lng);
		slo.setLocation(startPoint);
		BoundingBoxE6 bbe = new BoundingBoxE6(lat - .05, lng + .1, lat + .05, lng - .1);
		map.setScrollableAreaLimit(bbe);
		map.getOverlays().add(slo);
		mapController.setZoom(Config.INITIAL_MAP_ZOOM);
		mapController.setCenter(startPoint);

This is the stack trace:
E/AndroidRuntime( 5943): FATAL EXCEPTION: main
E/AndroidRuntime( 5943): Process: xxx.xxx.xxx.xxx, PID: 5943
E/AndroidRuntime( 5943): java.lang.RuntimeException: Canvas: trying to use a recycled bitmap android.graphics.Bitmap@4219cc28
E/AndroidRuntime( 5943): 	at android.graphics.Canvas.throwIfCannotDraw(Canvas.java:1084)
E/AndroidRuntime( 5943): 	at android.view.GLES20Canvas.drawBitmap(GLES20Canvas.java:811)
E/AndroidRuntime( 5943): 	at org.osmdroid.views.overlay.mylocation.SimpleLocationOverlay.draw(SimpleLocationOverlay.java:81)
E/AndroidRuntime( 5943): 	at org.osmdroid.views.overlay.DefaultOverlayManager.onDraw(DefaultOverlayManager.java:134)
E/AndroidRuntime( 5943): 	at org.osmdroid.views.MapView.dispatchDraw(MapView.java:1082)
E/AndroidRuntime( 5943): 	at android.view.View.getDisplayList(View.java:13570)
E/AndroidRuntime( 5943): 	at android.view.View.getDisplayList(View.java:13617)
E/AndroidRuntime( 5943): 	at android.view.View.draw(View.java:14395)
E/AndroidRuntime( 5943): 	at android.view.ViewGroup.drawChild(ViewGroup.java:3237)
E/AndroidRuntime( 5943): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3074)
E/AndroidRuntime( 5943): 	at android.view.View.getDisplayList(View.java:13570)
E/AndroidRuntime( 5943): 	at android.view.View.getDisplayList(View.java:13617)
E/AndroidRuntime( 5943): 	at android.view.View.draw(View.java:14395)
E/AndroidRuntime( 5943): 	at android.view.ViewGroup.drawChild(ViewGroup.java:3237)
E/AndroidRuntime( 5943): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3074)
E/AndroidRuntime( 5943): 	at android.view.View.draw(View.java:14684)
E/AndroidRuntime( 5943): 	at android.widget.FrameLayout.draw(FrameLayout.java:472)
E/AndroidRuntime( 5943): 	at android.widget.ScrollView.draw(ScrollView.java:1612)
E/AndroidRuntime( 5943): 	at android.view.View.getDisplayList(View.java:13575)
E/AndroidRuntime( 5943): 	at android.view.View.getDisplayList(View.java:13617)
E/AndroidRuntime( 5943): 	at android.view.View.draw(View.java:14395)
E/AndroidRuntime( 5943): 	at android.view.ViewGroup.drawChild(ViewGroup.java:3237)
E/AndroidRuntime( 5943): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3074)
E/AndroidRuntime( 5943): 	at android.view.View.getDisplayList(View.java:13570)
E/AndroidRuntime( 5943): 	at android.view.View.getDisplayList(View.java:13617)
E/AndroidRuntime( 5943): 	at android.view.View.draw(View.java:14395)
E/AndroidRuntime( 5943): 	at android.view.ViewGroup.drawChild(ViewGroup.java:3237)
E/AndroidRuntime( 5943): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3074)
E/AndroidRuntime( 5943): 	at android.view.View.draw(View.java:14684)
E/AndroidRuntime( 5943): 	at android.widget.FrameLayout.draw(FrameLayout.java:472)
E/AndroidRuntime( 5943): 	at android.view.View.getDisplayList(View.java:13575)
E/AndroidRuntime( 5943): 	at android.view.View.getDisplayList(View.java:13617)
E/AndroidRuntime( 5943): 	at android.view.View.draw(View.java:14395)
E/AndroidRuntime( 5943): 	at android.view.ViewGroup.drawChild(ViewGroup.java:3237)
E/AndroidRuntime( 5943): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3074)
E/AndroidRuntime( 5943): 	at android.view.View.getDisplayList(View.java:13570)
E/AndroidRuntime( 5943): 	at android.view.View.getDisplayList(View.java:13617)
E/AndroidRuntime( 5943): 	at android.view.View.draw(View.java:14395)
E/AndroidRuntime( 5943): 	at android.view.ViewGroup.drawChild(ViewGroup.java:3237)
E/AndroidRuntime( 5943): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3074)
E/AndroidRuntime( 5943): 	at android.view.View.getDisplayList(View.java:13570)
E/AndroidRuntime( 5943): 	at android.view.View.getDisplayList(View.java:13617)
E/AndroidRuntime( 5943): 	at android.view.View.draw(View.java:14395)
E/AndroidRuntime( 5943): 	at android.view.ViewGroup.drawChild(ViewGroup.java:3237)
E/AndroidRuntime( 5943): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3074)
E/AndroidRuntime( 5943): 	at android.view.View.getDisplayList(View.java:13570)
E/AndroidRuntime( 5943): 	at android.view.View.getDisplayList(View.java:13617)
E/AndroidRuntime( 5943): 	at android.view.View.draw(View.java:14395)
E/AndroidRuntime( 5943): 	at android.view.ViewGroup.drawChild(ViewGroup.java:3237)
E/AndroidRuntime( 5943): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3074)
E/AndroidRuntime( 5943): 	at android.view.View.draw(View.java:14684)
E/AndroidRuntime( 5943): 	at android.widget.FrameLayout.draw(FrameLayout.java:472)
E/AndroidRuntime( 5943): 	at com.android.internal.policy.impl.PhoneWindow$DecorView.draw(PhoneWindow.java:2474)
E/AndroidRuntime( 5943): 	at android.view.View.getDisplayList(View.java:13575)
E/AndroidRuntime( 5943): 	at android.view.View.getDisplayList(View.java:13617)
E/AndroidRuntime( 5943): 	at android.view.HardwareRenderer$GlRenderer.buildDisplayList(HardwareRenderer.java:1577)
E/AndroidRuntime( 5943): 	at android.view.HardwareRenderer$GlRenderer.draw(HardwareRenderer.java:1451)
E/AndroidRuntime( 5943): 	at android.view.ViewRootImpl.draw(ViewRootImpl.java:2551)
E/AndroidRuntime( 5943): 	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2417)
E/AndroidRuntime( 5943): 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2006)
E/AndroidRuntime( 5943): 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1063)
E/AndroidRuntime( 5943): 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5993)
E/AndroidRuntime( 5943): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:761)
E/AndroidRuntime( 5943): 	at android.view.Choreographer.doCallbacks(Choreographer.java:574)
E/AndroidRuntime( 5943): 	at android.view.Choreographer.doFrame(Choreographer.java:544)
E/AndroidRuntime( 5943): 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Chor

**Comment by spyhunter99** [comment]
can you provide any additional clues for reproducing the crash condition or your application? is it only when resuming the app? is the map in an activity or fragment in your case?

 #413 related issue

**Comment by tartina** [comment]
The map is in an acitivity, and it's hidden by default. The user can show the map, using the menu, the map is shown and another image is hidden, to save space.
The map displays the position of a shop, which are choosen from another activity.

I usually can choose 3 or more such shops and display the map, but then I usually get the crash.
As the stack trace shows, there is a reuse of a recycled bitmap, drawing the location mark.
I sometimes display the same map, and I use caching of tiles.

I will try to get other info about this asap.

**Comment by spyhunter99** [comment]
so interesting note, SimpleLocationOverlay isn't exercised on the unit tests. I'll add a test case to make sure it's covered in the future

**Comment by spyhunter99** [comment]
merge, this should fix your problem
