### ISSUE TITLE
Reposition Compass OSM Droid

### ISSUE THREAD

**Issue by kurniawanrizzki** [osmdroid/osmdroid#478]
I want to reposition compass in corner of the map with current height that has been set based on height of device, but it's always failed, the compass is never shown. Can you help me, how to set the compass position, so it will be responsive in any device. Best regard from me. Thank You

**Comment by spyhunter99** [comment]
@kurniawanrizzki  are you referring to `org.osmdroid.views.overlay.compass.CompassOverlay`? 
I think the solution would be to extend that class and override the bits in the constructor. There's also the `setCompassCenter` method. There's no javadocs so I'm not entirely sure. If you come up with a solution, please let us known so we can update the docs

**Comment by kurniawanrizzki** [comment]
Thank you for your advice, yup it can, but too complex for me. I was solve the problem with current formula depend on device density.

**Comment by spyhunter99** [comment]
I'm going to reopen this as a place holder for figuring this out in the future

**Comment by kurniawanrizzki** [comment]
with my solution, the issue still occurred when the app run at different resolution, have any idea to solve it?
In past, i solve with this formula

`compassPadding = (osmMapView.getProjection().getScreenReact().getExactCenterY()/3.4f)/deviceDensity`

**Comment by kurniawanrizzki** [comment]
@spyhunter99 one question, is possible to apply map rotation when pinch to the map similar google maps?

**Comment by spyhunter99** [comment]
https://github.com/osmdroid/osmdroid/wiki/How%20to%20use%20the%20osmdroid%20library#how-to-enable-rotation-gestures

**Comment by kurniawanrizzki** [comment]
Is it use pinch (two finger) to rotate the map?I have try, but it still not working. Is there difference between osm bonuspack by [MKergall](https://github.com/MKergall/osmbonuspack) and osmdroid, please tell me about it, because there are some different issue when i try install them. Thank You

**Comment by spyhunter99** [comment]
@kurniawanrizzki sorry i missed this one. This should do it
````
 mRotationGestureOverlay = new RotationGestureOverlay(mMapView);
          mRotationGestureOverlay.setEnabled(true);

          mMapView.setBuiltInZoomControls(true);
          mMapView.setMultiTouchControls(true);
````

**Comment by aritrabasu104** [comment]
Repositioning the compass overlya... whats the simplemost way to do it?

**Comment by spyhunter99** [comment]
Osm bonus pack depends on the project and adds  routing, kml processing and a bunch of other stuff

Moving the compass is not simple unfortunately

**Comment by kurniawanrizzki** [comment]
Right, you have to calculate the screen device weather the orientation change or not, and finally we done with it.

_Sent from my Xiaomi Redmi 3 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by spyhunter99** [comment]
i think this is resolved with https://github.com/osmdroid/osmdroid/pull/907
