### ISSUE TITLE
MBTiles not working

### ISSUE THREAD

**Issue by jankalfus** [osmdroid/osmdroid#482]
I'm unable to get offline maps to work using MBTiles.

I copied multiple `*.mbtiles` files into `/sdcard/osmdroid/tiles` folder, which contain `My Map Tiles` as the name in metadata.

I'm setting up the tile source like so:

```
map.setTileSource(new XYTileSource(
        "My Map Tiles",
        0,
        9,
        256,
        ".jpg",
        new String[]{}
));
```

I navigate the map programatically to the position where the map should be available, the zoom levels are there in the mbtiles file etc., but osmdroid doesn't load the tiles. I turned on debugging using:
```
OpenStreetMapTileProviderConstants.DEBUG_TILE_PROVIDERS = true;
OpenStreetMapTileProviderConstants.DEBUGMODE = true;
```
The output I get in logcat is like the following:
```
12-01 14:51:54.864 2049-2258/ginasystem.ginago D/OsmDroid: TileLoader.tileLoadedFailed() on provider: SQL Cache Archive Provider with tile: /9/277/171
12-01 14:51:54.864 2049-2258/ginasystem.ginago D/OsmDroid: MapTileModuleProviderBase.removeTileFromQueues() on provider: SQL Cache Archive Provider for tile: /9/277/171
12-01 14:51:54.864 2049-2258/ginasystem.ginago D/OsmDroid: MapTileModuleProviderBase.loadMaptileAsync() on provider: File Archive Provider for tile: /9/277/171
12-01 14:51:54.864 2049-2258/ginasystem.ginago D/OsmDroid: MapTileModuleProviderBase.loadMaptileAsync() adding tile to request queue for modular provider.
12-01 14:51:54.864 2049-2268/ginasystem.ginago D/OsmDroid: TileLoader.nextTile() on provider: File Archive Provider found tile in working queue: /9/277/171
12-01 14:51:54.864 2049-2268/ginasystem.ginago D/OsmDroid: TileLoader.nextTile() on provider: File Archive Provider adding tile to working queue: /9/277/171
12-01 14:51:54.864 2049-2268/ginasystem.ginago D/OsmDroid: TileLoader.run() processing next tile: /9/277/171, pending:1, working:1
12-01 14:51:54.864 2049-2268/ginasystem.ginago D/OsmDroid: Tile doesn't exist: /9/277/171
12-01 14:51:54.864 2049-2268/ginasystem.ginago D/OsmDroid: TileLoader.tileLoadedFailed() on provider: File Archive Provider with tile: /9/277/171
12-01 14:51:54.864 2049-2268/ginasystem.ginago D/OsmDroid: MapTileModuleProviderBase.removeTileFromQueues() on provider: File Archive Provider for tile: /9/277/171
12-01 14:51:54.864 2049-2268/ginasystem.ginago D/OsmDroid: MapTileProviderBase.mapTileRequestFailed(): /9/277/171
```

I was unable to find any up-to-date tutorial about using offline maps. I don't know what to do. Please help.

**Comment by spyhunter99** [comment]
Put the files in /sdcard/osmdroid

**Comment by spyhunter99** [comment]
Just updated it.
https://github.com/osmdroid/osmdroid/wiki/Offline-Map-Tiles#using-offline-tile-archives

make more sense now?

**Comment by jankalfus** [comment]
Yes, this is much more clear now. Thank you! :) I will try it out and report back on Monday.

**Comment by raku** [comment]
Hello, @spyhunter99 will work also with vector mbtiles from here? http://osm2vectortiles.org/downloads/

**Comment by spyhunter99** [comment]
interesting. I just checked it out and can confirm that no, it will not work as is. It looks closer to geopackage than mbtiles. It looks feasible to support that format with relatively little work. I'll open anew ticket for it. The existing MBtiles support basically supports what MOBAC creates which can be referenced here:

https://sourceforge.net/p/mobac/code/HEAD/tree/trunk/MOBAC/src/main/java/mobac/program/atlascreators/MBTiles.java

which references this 1.1 spec of mbtiles here:

https://github.com/mapbox/mbtiles-spec/tree/master/1.1

**Comment by spyhunter99** [comment]
those mbtiles that you linked to are raster tiles

**Comment by raku** [comment]
but on that website they are saying they export vector tiles from osm files

**Comment by spyhunter99** [comment]
yup you are right. Bottom line is that we don't have support for vector tiles at the moment.  In fact, there's already a ticket for it #246. There are some rendering engines but none that are asf license compatible, as i understand.

**Comment by spyhunter99** [comment]
closing as a duplicate since #246 covers this. regular mbtiles formats are working

**Comment by jankalfus** [comment]
Got it working, thanks again!

**Comment by WJ9521** [comment]
could you give me your demo ?

**Comment by CodeK1988** [comment]
@spyhunter99 @WJ9521 hi mate, have you successfully loaded mbtiles? The version 6.1.18 I use always fails. Is my mbtiles format incorrect?   demo OfflinePickerSample
'''
Iterator<String> iterator = tileSources.iterator();
iterator.hasNext() always false
'''
I need your help, thank you.

**Comment by spyhunter99** [comment]
hmm it's been years since i've used them. the test data set that was used for integration was produced by mobac. maybe version 1.8 or 2.0. try opening the mbtiles you have with a sqlite tool.

looks like our code is for mbtiles spec 1.1 with the following schema

TABLE tiles (zoom_level INTEGER, tile_column INTEGER, tile_row INTEGER, tile_data BLOB);

**Comment by CodeK1988** [comment]
@spyhunter99 Thanks for the reply, I'll look for the answer again, I'm not too familiar with the various versions of the mbtiles file spec yet.
