### ISSUE TITLE
Could I use mymap.osm file as my offline map data?

### ISSUE THREAD

**Issue by Mantj** [osmdroid/osmdroid#483]
I have changed mymap,osm in my computer using JOSM,but I do not want to upload it because of some reasons.
I want to know if there are some ways that I can use mymap.osm file as my offline data ?Or change .osm file to another files?
Thank you~

**Comment by spyhunter99** [comment]
I think you can convert it to a mapsforge file then use the osmdroid
adapter for that but no direct path, sorry

**Comment by Mantj** [comment]
@spyhunter99 Thank you very much~
Could you please get me a link of the guide about osmdroid adapter using mapsforge file(.map)?

**Comment by spyhunter99** [comment]
There's no guide, but there is a sample app in the source code

https://github.com/osmdroid/osmdroid/blob/master/osmdroid-forge-app/src/main/java/org/osmdroid/forge/app/MainActivity.java

**Comment by Mantj** [comment]
Hi~,I follow this sample, and I got some errors bellow:
    1.can not find class :MapsForgeTileSoure
    2.can not find class :XmlRenderTheme
    3.can not find class MapsForgeTileProvider

I use 'org.osmdroid:osmdroid-android:5.1@aar' 
is this version too old?

**Comment by spyhunter99** [comment]
https://github.com/osmdroid/osmdroid/wiki/Changelog

The change log says it was added in 5.2 and you'll need to add the dependency for it.

something like this

````
compile 'org.osmdroid:osmdroid-mapsforge:5.2-SNAPSHOT:release@aar'
````

**Comment by Mantj** [comment]
Hi!,I add `compile 'org.osmdroid:osmdroid-mapsforge:5.2-SNAPSHOT:release@aar'` into my gradle,but there is a trouble error: Not only MapsForgeTileSoure/XmlRenderTheme/MapsForgeTileProvider is red ,but also GeoPoint/MapView/MyLocationNewOverlay... is red.
I download 5.2aar in [here](https://oss.sonatype.org/content/groups/public/org/osmdroid/osmdroid-android/5.2/). What's wrong with me?
Thanke you~

**Comment by spyhunter99** [comment]
drop the -SNAPSHOT part

**Comment by Mantj** [comment]
I try to drop the '-SNAPSHOT' and is also error.
The warning goes,
`'Warning:Dependency org.json:json:20160212 is ignored for debug as it may be conflicting with the internal version provided by Android.'`
And error here:
```
Error:A problem occurred configuring project ':app'.
> Could not find osmdroid-mapsforge-release.aar (org.osmdroid:osmdroid-mapsforge:5.2).
  Searched in the following locations:
      https://jcenter.bintray.com/org/osmdroid/osmdroid-mapsforge/5.2/osmdroid-mapsforge-5.2-release.aar
```

I download the aar file named: osmdroid-android-5.2

**Comment by spyhunter99** [comment]
https://repo.jfrog.org/artifactory/libs-release-bintray/org/osmdroid/osmdroid-mapsforge/5.2/osmdroid-mapsforge-5.2.aar

change it to compile 'org.osmdroid:osmdroid-mapsforge:5.2@aar'

**Comment by Mantj** [comment]
Got it ~ Thank you very much 
But `MapsForgeTileSource.createInstance(this.getApplication());`  The Method createInstance is still red.
And the class XmlRenderTheme and AssetsRenderTheme are red too.Why I can not import them?
Thank you .

**Comment by Mantj** [comment]
Oh , XmlRenderTheme and AssetsRenderTheme are in the mapsgorge lib,and the guide says that I can use them optional. 
But why createInstance would error?could I also do not use it?

**Comment by spyhunter99** [comment]
looks like that code was added with osmdroid 5.4.1 and newer. So either use the newer versions or reference the source code.

https://github.com/osmdroid/osmdroid/blob/master/osmdroid-mapsforge/src/main/java/org/osmdroid/mapsforge/MapsForgeTileSource.java#L190

**Comment by Mantj** [comment]
Thank you very much,
I would like to rebuilt my project with version 5.5
It's too late that I will do it tomorrow.
Thank you for your help~

**Comment by Mantj** [comment]
Hi~, I download the 5.5 version.
Then I 
```
compile 'org.osmdroid:osmdroid-android:5.5:release@aar'
compile 'org.osmdroid:osmdroid-mapsforge:5.5:release@aar'
```
And copy the code to my Activity,and put the .map file to ./osmdroid/
But when I run , I've got an error : 
`Could not find class 'org.mapsforge.map.model.DisplayModel', referenced from method org.osmdroid.mapsforge.MapsForgeTileSource.<init>`
and
`Could not find class 'org.mapsforge.core.model.Tile', referenced from method org.osmdroid.mapsforge.MapsForgeTileSource.renderTile`
What is wrong?Thank you~

**Comment by spyhunter99** [comment]
Try removing @aar and see what happens

**Comment by Mantj** [comment]
Hi~
The error is 
`java.lang.NoClassDefFoundError: org.mapsforge.map.android.graphics.AndroidGraphicFactory`

And the error code is 
`MapsForgeTileSource.createInstance(this.getApplication());`

Then I try to remove the @aar ,so now it seems : 
```
compile 'org.osmdroid:osmdroid-android:5.5:release@aar'
    compile 'org.osmdroid:osmdroid-mapsforge:5.5:release'
```
But there is an error:
```
Error:Could not find osmdroid-android.jar (org.osmdroid:osmdroid-android:5.5).
Searched in the following locations:
    https://jcenter.bintray.com/org/osmdroid/osmdroid-android/5.5/osmdroid-android-5.5.jar
```
my whole gradle dependencies bellow:
```
compile fileTree(include: ['*.jar'], dir: 'libs')
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    compile 'com.android.support:appcompat-v7:25.0.1'
    testCompile 'junit:junit:4.12'
    //add by myself
    compile 'org.osmdroid:osmdroid-android:5.5:release@aar'
    compile 'org.osmdroid:osmdroid-mapsforge:5.5:release'
    compile(name: 'osmbonuspack_v6.0', ext: 'aar')
    compile 'org.apache.commons:commons-lang3:3.3.2'
    compile 'com.google.code.gson:gson:2.7'
    compile 'com.squareup.okhttp3:okhttp:3.4.1'
    compile('com.graphhopper:directions-api-java-client:0.7.0.1') {
        exclude group: 'com.google.protobuf', module: 'protobuf-java'
        exclude group: 'org.openstreetmap.osmosis', module: 'osmosis-osm-binary'
        exclude group: 'org.apache.xmlgraphics', module: 'xmlgraphics-commons'
```
Thank you ~

**Comment by spyhunter99** [comment]
I think you've stumbled upon the horrific dependency handling of aars that
gradle + android provides. Try this

compile 'org.osmdroid:osmdroid-android:5.5:release@aar'
compile 'org.osmdroid:osmdroid-mapsforge:5.5:release@aar'

compile 'org.mapsforge:mapsforge-map-android:0.6.1'
compile 'org.mapsforge:mapsforge-map:0.6.1'

**Comment by Mantj** [comment]
OMG,I got it waaaaaaaaaaaaaaa~
And the last question is:How to remove the offline map? 
When I want to change back to online mode, I use:
```
map.setTileSource(TileSourceFactory.MAPNIK);
map.setUseDataConnection(true);
```
The offline map data will cover the MAPNIK mode.

But when I change the map mode from online to offline, every thing is OK.
Thank you very much~

**Comment by spyhunter99** [comment]
Are you switching from MapsForge back to regular online osm tiles (or another online source)? If that's the case, you are switching tile providers which is a higher level in the food chain that a tile source. You'll want to set the MapView's tile provider to something like `new MapTileProviderBasic(context.getApplicationContext(), tileSource)`

**Comment by Mantj** [comment]
Sorry I haven't get your point.
Should I set the `TileSourceFactory.MAPNIK` as the Basic?
I set
`new MapTileProviderBasic(context.getApplicationContext(), TileSourceFactory.MAPNIK);`
but nothing happen...

**Comment by spyhunter99** [comment]
that should do it.
`mMap.setTileProvider(new MapTileProviderBasic(context.getApplicationContext(), TileSourceFactory.MAPNIK));`

**Comment by Mantj** [comment]
Oh~ I got it 
Thank you very much, you help me a lot.Thank you for your patience, love you~
Maybe I can close this issue,thank you~
