### ISSUE TITLE
How do you zoom out in osmdroid

### ISSUE THREAD

**Issue by Raptorel** [osmdroid/osmdroid#484]
I have implemented it in my android application for a tablet, so it sits in a fragment. When I double tap on the map, it zooms it. But there is no way to zoom out. There is no button, and pinching either moves the map, or moves the screen towards another fragment of the application.

I haven't found any intuitive way to zoom out the map. Any ideas?

**Comment by spyhunter99** [comment]
download and install the sample app, then view the source code for it. there's a lot on the wiki too.

**Comment by spyhunter99** [comment]
it's something like, MapView.getController().zoomOut(); for gesture support, you have to add the gesture overlay and enable multi touch controls. There is also the built in on screen buttons that can be enabled on mapView. Again see the sample app

**Comment by Raptorel** [comment]
Yeah but zooming in does work, by double tapping in the map. What is the corresponding "opposing action" for zooming out?

**Comment by spyhunter99** [comment]
Pinch, two finger gesture

**Comment by Raptorel** [comment]
Doesn't work, it doesn't recognize the pinching. Also, if I press to scroll through the map, it only works if you move the finger up or down. If you move it left or right, it moves through the tabs of the applications (this, on a tablet). So if you want to move east or west through the map, if first have to move up or down, and then move left/right.

But yeah, pinching doesn't work. This is how I've implemented it in the application:

```
<org.osmdroid.views.MapView
            android:id="@+id/mapview"
            android:layout_width="match_parent"
            android:layout_height="0dp"
            android:layout_weight="65"
            android:clickable="true" />
```

The only thing that works is the double tap, for zooming in. To move through it, press and hold a bit, move North or South, and then you can also go East or West.

**Comment by spyhunter99** [comment]
If that's all you've done, that's why.  see the starter map sample
https://github.com/osmdroid/osmdroid/blob/master/OpenStreetMapViewer/src/main/java/org/osmdroid/StarterMapFragment.java

additional documentation here:
https://github.com/osmdroid/osmdroid/wiki/How%20to%20use%20the%20osmdroid%20library

most of all, your problem is resolved by reading this bit
https://github.com/osmdroid/osmdroid/wiki/How%20to%20use%20the%20osmdroid%20library#main-activity

**Comment by Raptorel** [comment]
OK, thank you!
