### ISSUE TITLE
Possibly improved CacheManager

### ISSUE THREAD

**Issue by 2ndGAB** [osmdroid/osmdroid#487]
Hello,

Would like to implement an improved version of the [CacheManager ](https://github.com/2ndGAB/WPCacheManager) which better takes care of the Markers and path to download the concerned tiles at different zoom level.

I now use it for months with any problem.

**Comment by spyhunter99** [comment]
Ok what's different?  open a pr

**Comment by 2ndGAB** [comment]
different from what?

**Comment by spyhunter99** [comment]
Is it different that this?
https://github.com/osmdroid/osmdroid/blob/master/osmdroid-android/src/main/java/org/osmdroid/tileprovider/cachemanager/CacheManager.java#L299

downloads all tiles that are along the list of points.

**Comment by 2ndGAB** [comment]
Ah ok, it's true that's I discussed about it few [months ago](https://github.com/osmdroid/osmdroid/issues/333) I didn't know it was implemented yet. That's perfect.

**Comment by spyhunter99** [comment]
Np, but don't thank me, thank the person that wrote it.  #333 was the discussion on it.

**Comment by 2ndGAB** [comment]
it was me! lol
