### ISSUE TITLE
Tiles Scaled To Dpi on high DPI sources

### ISSUE THREAD

**Issue by sandman7920** [osmdroid/osmdroid#488]
In current implementation if we have high DPI sources with 512px tiles
```java
private void updateTileSizeForDensity(final ITileSource aTileSource) {
	float density = isTilesScaledToDpi() ? getResources().getDisplayMetrics().density : 1;
	TileSystem.setTileSize((int) (aTileSource.getTileSizePixels() * density));
}
```
produce wrong value for tile size.
For devices with 3x density tile size become 1536 (512 *3)
my solution is this
```java
private void updateTileSizeForDensity(final ITileSource aTileSource) {
        int tile_size = aTileSource.getTileSizePixels();
        float density =  getResources().getDisplayMetrics().density * 256 / tile_size ;
        int size = (int) ( tile_size * (isTilesScaledToDpi() ? density : 1));
        TileSystem.setTileSize(size);
}
```

**Comment by spyhunter99** [comment]
I appreciate raising the issue and the sample code,, but can you explain a bit more about this?

**Comment by sandman7920** [comment]
If we have custom tile source that serve retina tiles 512(@2x),768(@3x),etc current implementation just multiply density*tile_size.
On Galaxy Note 4
getResources().getDisplayMetrics().density returns 4
aTileSource.getTileSizePixels() returns 512
4*512 = 2048 but correct value for scaled tile is 1024

**Comment by spyhunter99** [comment]
Perfect, I'll get it merged shortly

**Comment by sandman7920** [comment]
But if isTilesScaledToDpi() returns false  aTileSource.getTileSizePixels() must be used

**Comment by wolojoli** [comment]
This is even shorter
'
private void updateTileSizeForDensity(final ITileSource aTileSource) {
    int size = (int) ( isTilesScaledToDpi() ? getResources().getDisplayMetrics().density * 256 :aTileSource.getTileSizePixels());
        TileSystem.setTileSize(size);
}
'
