### ISSUE TITLE
Tiles are too small on high dpi devices 

### ISSUE THREAD

**Issue by ziem** [osmdroid/osmdroid#49]
Tiles are too small on high dpi devices like Nexus 5. Labels are unreadable... I'm attaching screenshots: 
http://imgur.com/Bz5wMyw
http://imgur.com/vfI2e5O
http://imgur.com/Ag4b37M
http://imgur.com/F2xNM0p
http://imgur.com/6X1jmxi

Any solutions?

**Comment by trofimchyk** [comment]
Hi!

**Comment by neilboyd** [comment]
@trofimchyk please create a new issue for markers

**Comment by trofimchyk** [comment]
@neilboyd Ok, I'll make some screenshots for example and create new issue.

**Comment by rpeinl** [comment]
Thanks a lot for the fix. I just verified that 
mMapView.setTilesScaledToDpi(true) 
did work for me as well. Version 4.3 also fixed the issue that setCenter did not center around the coordinates, but make the given coordinates the left upper corner. 
Why is there now binary distribution of osmdroid 5.x any more? I just found a sources.jar, but not the "real" jar with compiled classes.

**Comment by spyhunter99** [comment]
osmdroid >=5.0 is an android archive. I'm not sure why there's such as push back on this. It's the android way to include resource files along with java code. You can still download the AAR on maven central.
