### ISSUE TITLE
osmdroid cache validity time

### ISSUE THREAD

**Issue by rbrueckner11** [osmdroid/osmdroid#490]
Hi,

I am using osmdroid 5.5 with Openstreetmap (source: http://tile.openstreetmap.de/) and Openseamap (source: http://t1.openseamap.org/seamark/) for a nautical navigation app. The tile source object used is XYTileSource. My users complain about short cache times. However, they did not confirm what "short" means to them. In general I understood it is less than one week. Having map tiles offline available for a longer period of time is important for this app which is primarily used outside areas with network coverage.

I have searched the web for a valid answer about tile validity times but was not really able to get a consistent view. As far as I understood that the validity time of tiles is set by the tile source which in my case are OSM and Openseamap?

Could you please confirm the mechanics of the osmdroid cache regarding keeping of downloaded tiles?
Are there any options to influence / extend the validity period of tiles?

Many Thanks.

**Comment by spyhunter99** [comment]
So yes it's set by the source.  There isn't a way right now to override the expires field,  but it can be added in the next version. V5.6 added some additional checks that may fix the issue.

If your users need a longer term solution, the cache manager can make tile archives which never expire

**Comment by rbrueckner11** [comment]
Appreciated. Thanks. Is there documentation available or could you briefly explain what needs to be done in order to make tile archives that never expire?

**Comment by spyhunter99** [comment]
Sample app, see the cache manager archive sample.

**Comment by spyhunter99** [comment]
Sorry i was on mobile earlier. Here's a more direct link
https://github.com/osmdroid/osmdroid/blob/master/OpenStreetMapViewer/src/main/java/org/osmdroid/samplefragments/cache/SampleCacheDownloaderArchive.java

**Comment by spyhunter99** [comment]
Also note worthy, it is possible to override the map tile downloader which sets the expiration timestamp on the MapTile class, once it's then saved in the database, you're good to go. You can also override the TileWriter (IFileSystemCache) provider and override the expiration date there.

Bear in mind, that online tile sources provide an expiration time because they want you to have the most update to date map tiles.
 
At one point in time, there was discussion on forcing a never expires flag on zoom < 10, since they don't change as often but it wasn't implemented

**Comment by spyhunter99** [comment]
@rbrueckner11 how did you get open sea map to show in osmdroid? Does it need a http header for referrer or something to that effect to get the tiles to download correct? Looks like it's returning a transparent image

**Comment by spyhunter99** [comment]
never mind, it's more of an overlay on top of the map imagery

**Comment by rbrueckner11** [comment]
I tried to familiarize myself with the osmdroid object hierarchy and it seems to me I have to rebuild a couple of objects up to the Mapview to get the desired functionality. I'm afraid I don't have the deep knowledge to implement and maintain that particular fuctionality. I would rather appreciate if you could provide the procedures that allow the alteration of the tile expiration time directly on the Mapview level. For example, for me there would be requirement to define expiration times both for the openstreetmap as well as the openseamap being my overlay map. Thank you.

**Comment by spyhunter99** [comment]
ok if i have time i'll look at it tonight. So the goal is to have a
duration of time to force the expiration time stamp of downloaded tiles to
be now + the duration? or would server provided expiration + duration be
better?

also note that if the server doesn't provide an expiration time, the
default value is used, which i think is either 1 or 2 weeks.

**Comment by spyhunter99** [comment]
edit: it's 1 week default. I also found a bug with CacheManager. it's not setting the expiration field in the database and is probably not setting the tilecache column, as such, it probable gets deleted first. that may explain some of the issues your users are having

**Comment by rbrueckner11** [comment]
The preference is to have a user-defined, deterministic, fixed expiration time after the particular tile has been downloaded. So, the first scenario you described above would apply. For example, if someone is planning a sailing trip 4 weeks ahead with my app the map content should be available at least the amount of time the user has specified, i.e. from a predefined list providing a selection from 4 weeks, 12 weeks, etc. Normally, as you said earlier, map content does not change quite often and keeping tiles offline for a longer period of time helps to take load of the map servers as well as provides faster tile loading times. These expirations settings should be applicable to tiles of both the default map and any overlay map of the Mapview.

**Comment by spyhunter99** [comment]
> and any overlay map of the Mapview.

I'm assuming you mean a secondary TilesOverlay? Like in open sea map?

Moving on, i think i have a solution for you, just cleaning up some loose ends. I'm adding a bunch of stuff more stuff to help troubleshoot cache issues.

**Comment by rbrueckner11** [comment]
Sounds great. Thanks. 
One question though: map tiles are downloaded either if the user scrolls the map over a certain area on a certain zoom level or via the cachemanager which formerly was part of the osmdroid bonuspack and now is part of osmdroid itself. Will the cache expiration feature discussed above support both download scenarios or just via the cachemanager?

**Comment by InI4** [comment]
Just thinking about a slightly different usecase: Give users a choice between traffic usage and accuracy, could break down to above formula: cache_time = server_delivered_expiry + user_offset. Where user_offset >= 0 and user_offset > 0 means, the reload is slower than suggested by the server.

**Comment by spyhunter99** [comment]
@InI4 haha so i just added both. You can explicitly set a duration for overriding the server defined value OR you can optionally add an additional amount to the server defined (or default if not specified) value. I added the changes to both the maptile downloader and the cache manager.

**Comment by spyhunter99** [comment]
![It's away](https://media.giphy.com/media/kDVBZcB15s61q/giphy.gif)

**Comment by rbrueckner11** [comment]
Much appreciated, spyhunter99. This will be a significant improvement of my app.  Thank you for the super fast implementation of this feature.

In terms of next steps, could you please advise what I need to do to include this feature in my app?

- I understand I need to use osmdroid 5.6.1?

- In terms of coding this feature into my app I was trying to follow your code samples but not quite sure how this can used within my code environment. See below the lines of code representing the osmdroid object instances I am using and which I basically have access to. I am lacking the point how I can access the objects inside the Mapview to change the tile expiration date. Some little guideance would be highly appreciated.

....
mMapView = (MapView) mapview.findViewById(R.id.mapview_OSM);
mMapnikTileSource = new XYTileSource(MAPDIR_MAPNIK, 1, MAXZOOMLEVEL, 256, ".png", new String[]{"http://tile.openstreetmap.de/", "http://tile.openstreetmap.org/"});
mMapView.setTileSource(mMapnikTileSource);

mSeamarksTileSource = new XYTileSource(MAPDIR_SEAMARK, 1, MAXZOOMLEVEL, 256, ".png", new String[]{"http://t1.openseamap.org/seamark/", "http://tiles.openseamap.org/seamark/"});
TilesOverlay SeamarksOverlay = new TilesOverlay(new MapTileProviderBasic(getActivity(), mSeamarksTileSource), getActivity());
SeamarksOverlay.setLoadingBackgroundColor(Color.TRANSPARENT);
mMapView.getOverlays().add(SeamarksOverlay);
...

**Comment by InI4** [comment]
Sorry, this question is somewhat off. But how can I access this patch? I googled and stackexchanged, but I have no idea how to pull the code. Thx**2

**Comment by spyhunter99** [comment]
`````
git clone https://github.com/osmdroid/osmdroid.git
cd osmdroid
gradlew install
````

then on your project add under repositories for allProjects
`mavenLocal()`

then on your project that uses osmdroid
`compile 'org.osmdroid:osmdroid-android:5.6.1-SNAPSHOT:debug@aar'

alrightly on to the last question, how to configure the new stuff. Everything is configured via `Configuration.getInstance().set....` methods

**Comment by spyhunter99** [comment]
whoops missed a bit.

**Comment by InI4** [comment]
Thx, I already have my own branch osmdroid here, just that checkout failed when I first tried first. Will test.

**Comment by spyhunter99** [comment]
merged
