### ISSUE TITLE
Is there a way to clear the cache of a tile source?

### ISSUE THREAD

**Issue by jankalfus** [osmdroid/osmdroid#493]
I'm looking for a way to clear tile cache of a tile source. But I couldn't find any method to do so. Using `CacheManager` takes too much time and I suspect it clears all tile sources, not just the currently used one.

The reason I want to do this is the following: When using an offline tile source backed by an online source, and expand the coverage of offline tiles by adding more .mbtile files, the cached online tiles take precedence over the new offline tiles (.mbtile files). By clearing the cache, I expect that the offline tiles would gain precedence.

Steps to reproduce the issue:
1. View some area (so osmdroid downloads tiles from server into its cache)
2. Use .mbtile file with tiles that cover the area
3. The tiles from the .mbtile file don't show, cached tiles from online source are still shown instead (when viewing an area that wasn't cached before, they are displayed properly)

An alternative would be to always try to find offline tile, load a cached one if an offline one doesn't exist, and if cached one doesn't exist, download it from the server. Is there a way to do so?

**Comment by spyhunter99** [comment]
You can clear the entire cache but not the cache for a given source right
now.

**Comment by jankalfus** [comment]
Ok, how? :)

**Comment by spyhunter99** [comment]
Oh sorry, see the sample app. PreferenceActivity has an example, as well
was in the samples/cache packages. I think there's a purge thing there.

Basically for Sqlite, create an instance of the SqliteWriter and call the
purge method. For file cache time, recursive delete from cache path.

**Comment by spyhunter99** [comment]
This is the code snippet you want

https://github.com/osmdroid/osmdroid/blob/master/OpenStreetMapViewer/src/main/java/org/osmdroid/PreferenceActivity.java#L204

**Comment by jankalfus** [comment]
Thanks!

Yes, that would be great (if possible).

BTW is there a way to give offline tiles precedence over the cached ones?

**Comment by spyhunter99** [comment]
Yes, I think that's the default behavior

**Comment by jankalfus** [comment]
Unfortunately, it looks like it isn't. The cached tiles take precedence over the offline ones.

**Comment by spyhunter99** [comment]
Are you using the out of the box default MapTileProvider?

**Comment by jankalfus** [comment]
I'm using the XYTileSource class.

**Comment by spyhunter99** [comment]
Higher level than that. this might clear up what i mean. http://osmdroid.github.io/osmdroid/javadocAll/index.html

**Comment by spyhunter99** [comment]
the initial request for clearing a specific tile source has been merged as part of #490
