### ISSUE TITLE
No way to upgrade to v5.6

### ISSUE THREAD

**Issue by MKergall** [osmdroid/osmdroid#497]
Using Gradle, I tried: 
`    compile 'org.osmdroid:osmdroid-android:5.6:release@aar'
`and; 
`    compile 'org.osmdroid:osmdroid-android:5.6@aar'
`always produces: 
`"Error:(24, 13) Failed to resolve: org.osmdroid:osmdroid-android:5.6"
`
(while compile 'org.osmdroid:osmdroid-android:5.5:release@aar' is working fine)

**Comment by spyhunter99** [comment]
Possible sonatype hasn't synced up with central yet...

**Comment by spyhunter99** [comment]
It's available on sonatype

https://oss.sonatype.org/service/local/repositories/releases/content/org/osmdroid/osmdroid-android/5.6/osmdroid-android-5.6.aar

**Comment by spyhunter99** [comment]
Let's give it another day

**Comment by spyhunter99** [comment]
Related ticket on sonatype. Not entirely sure why it hasn't synced to central
https://issues.sonatype.org/browse/OSSRH-26882

**Comment by MKergall** [comment]
Still not working. Could you confirm that the dependency to set is:

`compile 'org.osmdroid:osmdroid-android:5.6@aar
`

**Comment by spyhunter99** [comment]
i just cut 5.6.1, no code changes. the only delta is that it was built using neils signing key

**Comment by spyhunter99** [comment]
just checked central, both are now there

**Comment by MKergall** [comment]
Yes, I confirm dependency is found with 5.6.1 (compile 'org.osmdroid:osmdroid-android:5.6.1'). 
Thanks.
