### ISSUE TITLE
How to set TileSystem zoom level higher than 22?

### ISSUE THREAD

**Issue by xiaoyanqiang** [osmdroid/osmdroid#498]
How to set TileSystem zoom level higher than 22?

**Comment by xiaoyanqiang** [comment]
there is a integer-overflow on method Prjection.adjustForDateLine() 
when zoom level is 22, mapSize=1073741874
the code in Prjection.adjustForDateLine() 
<code>
 if(absY > Math.abs(out.y + yCompare) || this.mMapViewHeight >= 2 * mapSize) {
            out.y += mapSize;
 }
</code>
there is
2* mapSize = -2147483648 // overflow the integer
so.... mMapViewHeight always larger than 2*mapSize

zoom level = 22, I always get the screen point like, Point(52, 1073741888);

**Comment by spyhunter99** [comment]
Gets asked about once a month and there ate several open tickets on this.
In short, we can't right now.  What you found is the tip of the ice berg
