### ISSUE TITLE
Support heatmap

### ISSUE THREAD

**Issue by yang093** [osmdroid/osmdroid#499]
Is there any way to draw heatmap with this lib?

**Comment by spyhunter99** [comment]
With the bonus pack, yes.  You'll have to figure out the points and fill
colors though

**Comment by spyhunter99** [comment]
Actually. Bonus pack isn't needed for this.  All you need is the polygon
class.
https://github.com/osmdroid/osmdroid/blob/master/osmdroid-android/src/main/java/org/osmdroid/views/overlay/Polygon.java

**Comment by MKergall** [comment]
@spyhunter99 Well... a [heatmap](https://en.wikipedia.org/wiki/Heat_map) is not just a polygon... We should have colors variations depending on the "heat". 

@yang093 I'm afraid the answer is currently no: I've not seen any heatmap for osmdroid yet. 
If you have something quite "static", you could build the desired image - for instance with a [LeafLet plugin](http://leafletjs.com/plugins.html#heatmaps) - save it, and then draw it on osmdroid map with the GroundOverlay.

**Comment by yang093** [comment]
Thank @spyhunter99 and @MKergall !
@MKergall is the unit of this method GroundOverlay.setDimensions meter(m)?

**Comment by MKergall** [comment]
[Yes](https://developers.google.com/android/reference/com/google/android/gms/maps/model/GroundOverlay)

**Comment by yang093** [comment]
Thank @MKergall !
By the way, is it possible if we draw the map on bitmap without GUI (map is not displayed on GUI)?

**Comment by MKergall** [comment]
I don't understand.

**Comment by spyhunter99** [comment]
@MKergall wouldn't it be possible to generate a heatmap using polygons of different fill colors and z indexes?

**Comment by MKergall** [comment]
@spyhunter99 Data used to generate heatmaps are  thousands (or hundreds of thousands) of points, each of them with a "heat". I don't see how polygons could handle that.

**Comment by spyhunter99** [comment]
I was able to whip up an example that kind of works. Lots of room for improvement. There's probably a many options to implement this. My example basically chops up the screen into cells, generates some random data, then iterates all of the data and increments up a counter based on the cell that it was rendered into. Finally the cells are converted into square polygons with a fill color based on the counter. I'll push it as soon as i can.

**Comment by spyhunter99** [comment]
@yang093 sample pushed to branch feature/#499

**Comment by spyhunter99** [comment]
![screenshot](https://cloud.githubusercontent.com/assets/1975321/21583083/05968e20-d03e-11e6-9405-8b6b6e68d906.png)

here's what it looked like on my sample app. ignore the "kml" part in the title.

**Comment by yang093** [comment]
Many thanks @spyhunter99 :)

**Comment by spyhunter99** [comment]
no problem. i'll tag is as experimental.  A better solution would be to have a modified R* tree sqlite based index into your data set, then run a custom tile provider + tile source to generate raster tiles on the fly, assuming that the data doesnt change often. Or perform this task server side.
