### ISSUE TITLE
Importing osmdroid-master as a project/OpenStreetMapViewer as a project

### ISSUE THREAD

**Issue by Raptorel** [osmdroid/osmdroid#500]
If I try to import osmdroid-master as a project, I get the following error:

> Error:Cause: failed to find target with hash string 'Google Inc.:Google APIs:23' in: /home/five/Android/Sdk
> <a href="openAndroidSdkManager">Open Android SDK Manager</a>

If I try to import only the "OpenStreetMapViewer", I get the same error.

I DO have API 23 installed. Sometimes, I get the error that the path towards my sdk is not set, and it tells me to check the local properties file, and it's set all fine and dandy, there.

I have yet to find a way to actually open the OpenStreetMapViewer project to make an idea about OSMDroid.

If I only copy the OpenStreetMapViewer folder in my Android Studio projects folder and open it alone, then the error I get is this:

> Error:(3, 0) Plugin with id 'com.android.application' not found.
> <a href="openFile:/home/five/AndroidStudioProjects/OpenStreetMapViewer/build.gradle">Open File</a>

How do I solve this?

**Comment by spyhunter99** [comment]
You probably need to add "Google APIs:23". It's a separate item in the sdk manager. We only use as an bridge. I think that the number of users using it is very low

**Comment by Raptorel** [comment]
I did that. It wasn't installed by default, so I installed it using the SDK Manager. It still gives the same error. In fact, I installed everything that had to do with "Google" in the 23 API.

**Comment by spyhunter99** [comment]
Try to build from the command line first with gradlew...
so `gradlew install`

Also check your ANDROID_HOME environment variable. Can you build any other android projects? What os are you running?

**Comment by spyhunter99** [comment]
is the problem with android studio, intellij or gradle?

**Comment by Raptorel** [comment]
The problem is with Android Studio, and it's a really weird problem, if you ask me. Let me try today to play around with it a bit more and see what I can come up with.

**Comment by stoanarrr** [comment]
Hi I've had the same problem with Android Studio.

Changing  
compileSdkVersion 'Google Inc.:Google APIs:23'
buildToolsVersion "23.0.3"

to
compileSdkVersion 23
buildToolsVersion '23.0.3'

in the build.gradle files in [https://github.com/osmdroid/osmdroid/blob/master/osmdroid-third-party/build.gradle](url) and [https://github.com/osmdroid/osmdroid/blob/master/GoogleWrapperSample/build.gradle](url) solved the problem for me.

**Comment by Raptorel** [comment]
Good to know, I need to check if that works here as well (also thanks for pointing out the actual location of these files)

**Comment by Raptorel** [comment]
Now it says this:

> Error:failed to find Build Tools revision 23.0.3
> <a href="install.build.tools">Install Build Tools 23.0.3 and sync project</a>

I have obviously installed Build Tools revision 23.0.3, and even checked on the SDK manager to see if they're installed. But the problem persists. Any ideas?

**Comment by spyhunter99** [comment]
I bet you have two copies of the sdk installed

**Comment by Raptorel** [comment]
Well, even if I had 20 copies of the SDK installed, as long as Android Studio points to the right one, it should work. The project should care about the SDK that Android Studio is pointing to, and should be agnostic about anything else in my computer. 

But I can't have more than one SDKs since I just installed Android Studio and the JDK with its default settings, and that's it.

**Comment by Raptorel** [comment]
OK so I restarted Android Studio and there are no errors now (with the modifications that stoanarrr talked about in his post).

**Comment by spyhunter99** [comment]
right my point was that you could have more than one and whatever android studio/gradle local.properties is set to may not have the Google Apis . You're best off using the standalone sdk manager the "Google APIs" v23, the build tools 23.0.3 and i'm pretty sure you also need "Google Play Services". I also have the "Android Support Repository" and the "Google Repository" (both listed under "Extras" installed.

**Comment by spyhunter99** [comment]
reopen if you continue to run into troubles. i have publish permissions now so expect more frequent releases
