### ISSUE TITLE
Copyright overlay

### ISSUE THREAD

**Issue by billthefarmer** [osmdroid/osmdroid#501]
I'm a bit puzzled as to why there isn't a copyright overlay, or at least a text overlay so you can implement the OpenStreetMap copyright requirement.in your wiki:

"OpenStreetMap requires that you add “© OpenStreetMap contributors” to the map, if you use their data. For more dedails see http://www.openstreetmap.org/copyright/en"

It's fairly trivial to implement one yourself, but something with a similar API to the ScaleBarOverlay, so you can put it in any corner would be nice.

**Comment by spyhunter99** [comment]
excellent point. This difficulty with implementing it is that osmdroid supports more than just osm based tiles and can render a wide variety of tiles sources. We can extend the constructor to have a copyright notice type of string and then render it in the tilesoverlay layer. so, doable

**Comment by billthefarmer** [comment]
You are welcome to use the code out of my app https://github.com/billthefarmer/location/blob/master/src/main/java/org/billthefarmer/location/CopyrightOverlay.java, but you may well not like it because it probably doesn't use your conventions and doesn't have any javadoc comments.

**Comment by MKergall** [comment]
No need to implement an osmdroid overlay: just put your copyright notice as a TextView in the layer, at any corner of the map.

**Comment by billthefarmer** [comment]
Well yes, but then again, maybe no. So I look up how to lay out a TextView in a MapView in the absence of any documented XML layout parameters and find this gem (in Class MapView.LayoutParams):

public LayoutParams(Context c,
                    AttributeSet attrs)

Since we cannot use XML files in this project this constructor is useless. Creates a new set of layout parameters. The values are extracted from the supplied attributes set and context.

**Comment by spyhunter99** [comment]
@billthefarmer i implemented your code, but the text size jumps around. any idea why or how to fix it?

**Comment by spyhunter99** [comment]
ehh i figured it out. unfortunately it currently suffers from rotation issues.

**Comment by billthefarmer** [comment]
Well it was a bit coarse, I just made it so the text was a third of the view width. Here's one way to do it out of ScaleBarOverlay.java.

		final DisplayMetrics dm = context.getResources().getDisplayMetrics();
		textPaint.setTextSize(10 * dm.density);

It should probably be a bit bigger than that.

**Comment by spyhunter99** [comment]
I've been playing around with this a bit and there's a few options for implementation

1) use @billthefarmer's concept added to the TilesOverlay class, some modifications to ITileSource to have the attribution text. Current issue, rotation is a problem (text rotates with the tiles) and if there's more than one TilesOverlay then we'll end up with two things on top of each other.
2) use a plain old android textview that is user (app developer using osmdroid) added to a layout file. modify ITileSource to have the attributions text. modify mapview to have a setter for the textview, which can then handle tile source changes, multiple tilesoverlays, etcs.
3) programmatically create a textview within mapview (and then everything else from option 2 applies)
4) use @billthefarmer's overlay class pretty much as is, Issues: map rotation, developer needs to update the attribution overlay manually

i'm leaning towards 2 or 3 at this point, looking to have as minimal of an impact to osmdroid users as possible. We probably also need to turn it on by default but have an option to disable it.

**Comment by billthefarmer** [comment]
I'm a believer in the KISS principle - Keep It Simple, Son. What you're proposing sounds complex to me and not so useful to someone who might want to use a text facility of some sort to put something completely different on a map. But then, what do I know - I'd never heard of osmdroid until a couple of weeks ago.

**Comment by spyhunter99** [comment]
@billthefarmer thanks of the feedback. i settled on a simple solution based on your overlay with fixes for map rotation and the strange behavior when zooming.

**Comment by billthefarmer** [comment]
You may have inadvertently propagated inconsistencies from my code. ScalebarOverlay has xOffset and yOffset defined as 10. My code, because it was a quick hack in case someone forked my project, has the offsets embedded in the code, which I didn't get around to fixing. I've got 8 in some places and 10 in another.

**Comment by spyhunter99** [comment]
got to reopen this, on some devices the notice isn't visible. specifically test on an api10 emulator.

**Comment by spyhunter99** [comment]
![issue 501](https://cloud.githubusercontent.com/assets/1975321/21750515/93675218-d582-11e6-93df-3ca24609adb1.png)

**Comment by spyhunter99** [comment]
it looks like older apis and/or device types calculate offsets different or report the wrong screen resolution. Fixed in the sample app
