### ISSUE TITLE
how to change the tilesize

### ISSUE THREAD

**Issue by jayhuang861019** [osmdroid/osmdroid#505]
i change the tilesize in this way:
`TileSystem.setTileSize((int) (tileScaleSize * 256))`
is that the right way?
when i finish this ,the mapcenter will move to another point ,always very far away ,what should i do?

**Comment by spyhunter99** [comment]
No. You set the tile size, in real pixels, when you set the tile source. MapView.getTileProvider().setTileSource(something goes here).

Most tile sources return tiles in 256x256 pixels. To use a custom, create a new ITileSource (or one of it's derived classes, like OnlineTileSourceBase)

**Comment by jayhuang861019** [comment]
sorry maybe i did not say clearly, i mean that  if i want to zoom in a maptile what should i do ?
as u know ,On some high resolution devices， the tile source in 256*256 pixels will become very small,
so i want to zoom in to see clearly! when i use `TileSystem.setTileSize((int) (tileScaleSize * 256))` ,the map center will move to anther point,always very far away...

**Comment by jayhuang861019** [comment]
a nother question:
if i want to adjust the map ,how to add the offset in the map!

**Comment by spyhunter99** [comment]
MapView.setTilesScaledToDpi(true)

MapView.getController().setCenter(...)

**Comment by jayhuang861019** [comment]
`IGeoPoint lastPoint = mapView.getMapCenter();
		// mapView.setTilesScaledToDpi(scaledToDpi);
		TileSystem.setTileSize((int) (tileScaleSize * 256));
		mapView.invalidate();
		mapView.getController().setCenter(lastPoint);`
this is my code,i save the mapcenter before i change the tilesize, but it will move to another point randomly when i set the mapcenter!

**Comment by spyhunter99** [comment]
do not call `TileSystem.setTileSize`

**Comment by spyhunter99** [comment]
reopen if you still have problems

**Comment by MKergall** [comment]
Why not setting MapView.setTilesScaledToDpi(true) as the default?
