### ISSUE TITLE
MapView inside RecyclerView

### ISSUE THREAD

**Issue by PalilloKun** [osmdroid/osmdroid#509]
Hi, i have a RecyclerView with differents layouts to show, one of them is a MapView, the map display correctly,but when i try scroll up or down  the map, the "Scroll" of RecyclerView  takes priority. How to fix?

thanks

This is my RecyclerView xml

`<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:paddingBottom="@dimen/activity_vertical_margin"
    android:paddingLeft="@dimen/activity_horizontal_margin"
    android:paddingRight="@dimen/activity_horizontal_margin"
    android:paddingTop="@dimen/activity_vertical_margin"
    android:background="#606060"
    tools:context=".Indicator">
    <android.support.v7.widget.RecyclerView
        android:id="@+id/recyclerView"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:layout_below="@+id/RoundData"
        />
</RelativeLayout>
`

This is my map.xml  layout:

`<?xml version="1.0" encoding="utf-8"?>
<android.support.v7.widget.CardView xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:card_view="http://schemas.android.com/apk/res-auto"
    android:id="@+id/cardview"
    android:layout_width="fill_parent"
    android:layout_height="fill_parent"
    android:layout_marginTop="16dp"
    android:elevation="100dp"
    card_view:cardBackgroundColor="#d4dcdf">   
                <org.osmdroid.views.MapView
                    android:id="@+id/mapaShow"
                    android:layout_width="match_parent"
                    android:layout_height="match_parent"/> 
</android.support.v7.widget.CardView>`

This is my CustomAdapter

`public class CustomAdapter extends RecyclerView.Adapter<CustomAdapter.ViewHolder> {
   
    public static class ViewHolder extends RecyclerView.ViewHolder {
        public ViewHolder(View v) {
            super(v);
        }
    }
       public class MapaViewHolder extends ViewHolder {

        MapView mapShow;

        public MapaViewHolder(View v) {
            super(v);      
            this.mapShow = (MapView) v.findViewById(R.id.mapShow);
        }
    }
 @Override
    public ViewHolder onCreateViewHolder(ViewGroup viewGroup, int viewType) {
       View v;
         
            v = LayoutInflater.from(viewGroup.getContext()) .inflate(R.layout.map, viewGroup, false);
            return new MapaViewHolder(v);
        }
    }

 @Override
    public void onBindViewHolder(ViewHolder viewHolder, final int position) {

 MapViewHolder Indicator = (MapViewHolder) viewHolder;

             Indicator .mapShow.setBuiltInZoomControls(true);
             Indicator .mapShow.setMultiTouchControls(true);
             Indicator .mapShow.setClickable(false);

             Indicator .mapShow.getController().setZoom(14);
             Indicator .mapShow.getController().setCenter(new GeoPoint(-25.2961407, -57.6309129));

}
}
`

**Comment by spyhunter99** [comment]
I'm willing to look into this further but it you wouldn't mind @PalilloKun, can you provide a complete, simple working example of the issue? It could be in any repo you want or  you can fork osmdroid and add it in directly. If the recycler view can live in a fragment, it can be added to https://github.com/osmdroid/osmdroid/blob/master/OpenStreetMapViewer/src/main/java/org/osmdroid/samplefragments/SampleFactory.java as long as it can extend from https://github.com/osmdroid/osmdroid/blob/master/OpenStreetMapViewer/src/main/java/org/osmdroid/samplefragments/BaseSampleFragment.java. The other option is to put the example is a standalone activity, then replace the `Collections.EMTPY_LIST` here https://github.com/osmdroid/osmdroid/blob/master/OpenStreetMapViewer/src/main/java/org/osmdroid/ExtraSamplesActivity.java#L27 with a list containing your activity. I'm actually doing some work on this now for #491 that should make this easier.

**Comment by PalilloKun** [comment]
Hi, thank you for help @spyhunter99, i upload a sample with the issue, this url https://github.com/PalilloKun/SampleMapWithRecyclerView

i use a CardView for each layout, RecyclerView is in activity_main

Thanks for the help and i hope comments

**Comment by spyhunter99** [comment]
success! for the most part.

This link was the solution

http://stackoverflow.com/a/6883831/

Extend mapview and c&p this

````
@Override
    public boolean onTouchEvent(MotionEvent ev) {
        int action = ev.getAction();
        switch (action) {
            case MotionEvent.ACTION_DOWN:
                // Disallow ScrollView to intercept touch events.
                this.getParent().requestDisallowInterceptTouchEvent(true);
                break;

            case MotionEvent.ACTION_UP:
                // Allow ScrollView to intercept touch events.
                this.getParent().requestDisallowInterceptTouchEvent(false);
                break;
        }

        // Handle MapView's touch events.
        return super.onTouchEvent(ev);

    }
````

**Comment by spyhunter99** [comment]
you'll still have some issues with the recycler view, because there's not much surface area to scroll with a finger. But this solution does work with a map in a scroll view. I'm considering putting this in osmdroid proper

**Comment by spyhunter99** [comment]
@PalilloKun can you borrow your example for putting it into osmdroid's sample app?

**Comment by PalilloKun** [comment]
Hi @spyhunter99, You mean that you upload the example to your repository?  or i upload de example to your repository?

**Comment by spyhunter99** [comment]
@PalilloKun goal would to be to merge portion of your repo into osmdroid has an example for future users (with the fix)

**Comment by PalilloKun** [comment]
Hi @spyhunter99, 
It would be great if the future users occupy it, what is missing?

**Comment by spyhunter99** [comment]
@PalilloKun i can do it. i don't understand the question. The fix was described above, extend MapView and add that bit of code. I was asking if I could borrow your example to put in the osmdroid sample application, in case someone has a similar use case in the future, the solution will be easy to find

**Comment by spyhunter99** [comment]
#588 #568 related tickets
