### ISSUE TITLE
Could not find osmdroid-android-release.aar (org.osmdroid:osmdroid-android:5.6.2)

### ISSUE THREAD

**Issue by Arman92** [osmdroid/osmdroid#514]
It seems you forgot to submit release version to maven repository.

I'm using `compile 'org.osmdroid:osmdroid-android:5.6.2'`
I also tried debug/release qualifier, no luck.

Have a look at [this](http://central.maven.org/maven2/org/osmdroid/osmdroid-android/5.6.2/) and [this](https://jcenter.bintray.com/org/osmdroid/osmdroid-android/5.6.2/).
there is no osmdroid-android-5.6.2-release.aar

**Comment by spyhunter99** [comment]
The release qualifier was dropped because everyone complained about it

**Comment by Arman92** [comment]
Ok, I tried removing release qualifier but  graddle is still looking for `osmdroid-android-release.aar`

Here is the full error log:

	Error:Could not find osmdroid-android-release.aar (org.osmdroid:osmdroid-android:5.6.2).
	Searched in the following locations:
	    http://central.maven.org/maven2/org/osmdroid/osmdroid-android/5.6.2/osmdroid-android-5.6.2-release.aar

**Comment by spyhunter99** [comment]
i just made an app today with `compile 'org.osmdroid:osmdroid-android:5.6.2'` and it worked. try deleting the .gradle folder for your project and possibly the .gradle folder in your user dir

**Comment by hlaurent** [comment]
Having the same issue.
I modified my build.gradle file from
 compile 'org.osmdroid:osmdroid-android:5.4.1:release@aar'
 compile 'org.osmdroid:osmdroid-third-party:5.4.1:release@aar'
to
 compile 'org.osmdroid:osmdroid-android:5.6.2'
 compile 'org.osmdroid:osmdroid-third-party:5.6.2'

I did delete the .gradle folder in my project and the .gradle folder in my user directory.
I am getting:
Error:Could not find osmdroid-android-release.aar (org.osmdroid:osmdroid-android:5.6.2).
Searched in the following locations:
    https://jcenter.bintray.com/org/osmdroid/osmdroid-android/5.6.2/osmdroid-android-5.6.2-release.aar

**Comment by spyhunter99** [comment]
try adding mavenCentral() to the root build repositories list

**Comment by hlaurent** [comment]
I already have it:
repositories {
    mavenCentral()
    flatDir {
        dirs 'libs'
    }
     maven { url "https://jitpack.io" }
}

**Comment by hlaurent** [comment]
Anyone has a clue as to what should be done to solve this? I am stuck. Thanks.

**Comment by spyhunter99** [comment]
please compare your **root** build.gradle with ours which is here
https://github.com/osmdroid/osmdroid/blob/master/build.gradle

**Comment by miguel-porto** [comment]
My **root** build.gradle is like this, and it works with 5.6.2 with the very same line you use @hlaurent :
```
buildscript {
    repositories {
        jcenter()
        mavenCentral()
        mavenLocal()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.2.3'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        jcenter()
        mavenCentral()
        mavenLocal()
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

```

**Comment by spyhunter99** [comment]
@hlaurent still having problems?

**Comment by hlaurent** [comment]
Still no luck.
I have removed the user/.gradle directory again, update my  **root** build.gradle to :

// Top-level build file where you can add configuration options common to all sub-projects/modules.
buildscript {
    repositories {
        jcenter()
        mavenCentral()
        mavenLocal()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.2.3'
        classpath 'com.google.gms:google-services:3.0.0'
    }
}

allprojects {
    repositories {
        jcenter()
        mavenCentral()
        mavenLocal()
    }
}

I am still getting:
Error:Could not find osmdroid-android-release.aar (org.osmdroid:osmdroid-android:5.6.2).
Searched in the following locations:
    https://jcenter.bintray.com/org/osmdroid/osmdroid-android/5.6.2/osmdroid-android-5.6.2-release.aar

One clue though. When I try to access 
https://jcenter.bintray.com/org/osmdroid/osmdroid-android/5.6.2/osmdroid-android-5.6.2-release.aar directly in Chrome, it is being redirected to 
https://repo.jfrog.org/artifactory/libs-release-bintray/org/osmdroid/osmdroid-android/5.6.2/osmdroid-android-5.6.2-release.aar?referrer
and I am getting the following message:
{
  "errors" : [ {
    "status" : 404,
    "message" : "Could not find resource"
  } ]
}

**Comment by spyhunter99** [comment]
can you list the dependencies for your app or library that is failing to
find osmdroid? There used to be a trick you can do with gradle's dependency
task to isolate the problematic reference but i don't recall what it was.
try gradlew -d dependencies

**Comment by spyhunter99** [comment]
I haven't the slightest clue why it is redirecting. Try moving maven central above jcenter in the repository list.

**Comment by spyhunter99** [comment]
The url with "release" doesn't exist, because it does not exist. Remove the "release" part and your browser should download the aar. You can use the aar directly and skip all the repository stuff. Search for using "aar in libs gradle" for some examples.

**Comment by spyhunter99** [comment]
operation timeout. i'm assuming this is fixed. reopen if it's still a problem

**Comment by scaidermern** [comment]
[How to add the osmdroid library via Gradle](https://github.com/osmdroid/osmdroid/wiki/How-to-add-the-osmdroid-library-via-Gradle) still mentions the `release` and `aar` part whereas [README.md](https://github.com/osmdroid/osmdroid/blob/master/README.md) doesn't.
