### ISSUE TITLE
issue with hitTest()  after rotate marker 

### ISSUE THREAD

**Issue by datnguyencr** [osmdroid/osmdroid#516]
i modified marker by using **marker.setRotation()** but now if i click on the marker, the **InfoWindow** does not show up. If i click on the original marker area , the **InfoWindow** shows. 
so i think the **hitTest**() function is not working correctly

**Comment by MKergall** [comment]
That's right. This is mentionned as a TODO in the Marker javadoc.

**Comment by spyhunter99** [comment]
related issues #459 and #460

**Comment by spyhunter99** [comment]
there is what i get
![issue 516](https://cloud.githubusercontent.com/assets/1975321/21750289/da6845fa-d57d-11e6-9b0f-3f8e1d856cba.png)

**Comment by monsieurtanuki** [comment]
Just PR'ed #1115, that fixes the issue and optimizes the drawing performances.
@spyhunter99 Where do you expect the info window to appear with a rotated icon?

**Comment by spyhunter99** [comment]
hmm well, the pointy part of the info window should probably point to the anchor point of the marker, i.e. the lat/lon that the marker represents

**Comment by monsieurtanuki** [comment]
@spyhunter99 Actually I believe there's an anchor for the information window too. It's just that it may look strange on a rotated marker, but I'll implement that too.

**Comment by monsieurtanuki** [comment]
@spyhunter99 Just PR'ed the final version, where the info window takes into account the Marker bearing
![device-2018-07-29-131326](https://user-images.githubusercontent.com/11576431/43365711-3bda19b8-9331-11e8-9f40-ebf24a71ed27.png)

**Comment by spyhunter99** [comment]
sweet i'll put it down, good great work @monsieurtanuki

**Comment by spyhunter99** [comment]
it's perfect

**Comment by monsieurtanuki** [comment]
@spyhunter99 Thanks!
