### ISSUE TITLE
BasicInfoWindow can throw under certain circumstances

### ISSUE THREAD

**Issue by spyhunter99** [osmdroid/osmdroid#518]
Getting a NPE here
https://github.com/osmdroid/osmdroid/blob/master/osmdroid-android/src/main/java/org/osmdroid/views/overlay/infowindow/BasicInfoWindow.java#L74

**Comment by spyhunter99** [comment]
01-06 20:49:12.002 6079-6079/? E/UncaughtException: Got an uncaught exception: java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.View android.view.View.findViewById(int)' on a null object reference
01-06 20:49:12.002 6079-6079/? W/System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.View android.view.View.findViewById(int)' on a null object reference
01-06 20:49:12.002 6079-6079/? W/System.err:     at org.osmdroid.views.overlay.infowindow.MarkerInfoWindow.onOpen(MarkerInfoWindow.java:58)
01-06 20:49:12.002 6079-6079/? W/System.err:     at org.osmdroid.views.overlay.infowindow.InfoWindow.open(InfoWindow.java:79)
01-06 20:49:12.002 6079-6079/? W/System.err:     at org.osmdroid.views.overlay.Marker.showInfoWindow(Marker.java:264)
01-06 20:49:12.002 6079-6079/? W/System.err:     at org.osmdroid.views.overlay.Marker.onMarkerClickDefault(Marker.java:414)
01-06 20:49:12.002 6079-6079/? W/System.err:     at org.osmdroid.views.overlay.Marker.onSingleTapConfirmed(Marker.java:353)
01-06 20:49:12.002 6079-6079/? W/System.err:     at org.osmdroid.views.overlay.DefaultOverlayManager.onSingleTapConfirmed(DefaultOverlayManager.java:237)
01-06 20:49:12.002 6079-6079/? W/System.err:     at org.osmdroid.views.MapView$MapViewDoubleClickListener.onSingleTapConfirmed(MapView.java:1381)
01-06 20:49:12.002 6079-6079/? W/System.err:     at android.view.GestureDetector$GestureHandler.handleMessage(GestureDetector.java:300)
01-06 20:49:12.002 6079-6079/? W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
01-06 20:49:12.002 6079-6079/? W/System.err:     at android.os.Looper.loop(Looper.java:148)
01-06 20:49:12.002 6079-6079/? W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5417)
01-06 20:49:12.002 6079-6079/? W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
01-06 20:49:12.002 6079-6079/? W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
01-06 20:49:12.002 6079-6079/? W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
01-06 20:49:12.007 6079-6085/? I/art: Debugger is no longer active

**Comment by spyhunter99** [comment]
related problem, if an icon is defined and the flag for ENABLE_TEXT_LABELS_WITH_NO_ICON is true, the default marker is displayed (fixed)

**Comment by spyhunter99** [comment]
@MKergall i'm not sure what the exact circumstances are, but it appears that i have a marker who was an mInfoWindow !=null, but that mInfoWindow's references to mMapView and mView are both null

**Comment by spyhunter99** [comment]
i think may have to do with all the memory leak clean up work i did a while ago and the shared static MarkerInfoWindow instance in Marker. @MKergall any reservations for making it non-static?

**Comment by spyhunter99** [comment]
a way to reproduce the error.
create a Marker marker1 and add it to the map
tap on marker1 on the map, info window should show
remove marker1 from the map and call onDestroy
create Marker marker2 and add it to the map
tap on marker2 on the map, info window loading throws a NPE.

the commits both guard against NPE and log the condition and removes the static references for the info window

**Comment by MKergall** [comment]
So I understand the purpose of #519 commit. 
Yes, I have a strong reservation to make mDefaultInfoWindow not static: share it among all OverlayWithIW. 

We may have stuff to fix, but it's important to be able to share infowindows between overlays, for both memory consumption and performance.

**Comment by spyhunter99** [comment]
alright, i'll see if i can rework it back to the static view, any idea how much memory is consumed by one of the info windows?

**Comment by spyhunter99** [comment]
@MKergall i just pushed another commit on 519, reverting the static info window change. After I did that, I ran into an issue where the info window was closing unexpected due to another marker being detached and destroyed. I added a few extra changes in Marker.onDetach. I'd appreciate you either looking at it or testing it yourself with your app. I'm not entirely sure what test procedures you run

**Comment by spyhunter99** [comment]
i'll wait to merge until i here back from you

**Comment by spyhunter99** [comment]
@MKergall do you think you'll have time to give me a yea or neh this week? I've tested every permutation i can think of on this end, but you wrote so i'm fairly certain i missed something

**Comment by MKergall** [comment]
I'm sorry, I will not be able to test anything during the week. 
I looked at your latest Marker code: I'm not 100% sure, but if your use case above with the 2 Markers is now working, it should be OK.

**Comment by spyhunter99** [comment]
@MKergall is it possible to have more than one info window displayed at a time (by default)? that's the only use case i haven't tested. And something with a custom info window

**Comment by spyhunter99** [comment]
merged. if you run into any issues, please let me know, or reopen or whatever
