### ISSUE TITLE
some tiles not refresh after zoom

### ISSUE THREAD

**Issue by shihuacai1989** [osmdroid/osmdroid#52]
the version of osmdroid  is 4.3. I run the project on the Samsung  t520, which the version of android is 4.4.2
mapView.getController().setZoom(5), then I wait for seconds, some tiles is not show, then i move the map,  all tiles show.
someone meet this problems?

![2014072201](https://cloud.githubusercontent.com/assets/6889646/3657220/00e3e8d6-1192-11e4-8882-73f4b0c5607c.png)

**Comment by secondflying** [comment]
I have the same problem. My problem is that when add another TilesOverlay, then when zoom in or zoom out, the map is incomplete. I move the map then all tile is shown.

**Comment by spyhunter99** [comment]
i've noticed that behavior too. maybe need to manually call refresh on secondary tile ovelrays

**Comment by secondflying** [comment]
@spyhunter99, do you know how to refresh the secondary tile ovelray manually?

**Comment by spyhunter99** [comment]
try mapview.invalidate

**Comment by secondflying** [comment]
@spyhunter99 ,I modify the source code, add mapview.invalidate() at the end of  DefaultOverlayManager.onDraw()  method, and solved my problem, thanks.

**Comment by spyhunter99** [comment]
although that solution may work, essentially, it should end up calling the
ondraw method again. It may be better to do an overlay scan and look for
overlays that extend tilesoverlay, then force a redraw on those

**Comment by ThisIsMyWay** [comment]
Is there any solution provided for this problem? Because I propably encountered similar problem and I don't know if I should open new issue. I wrote it on described it on stackoverflow. http://stackoverflow.com/questions/35393295/zooming-in-out-some-tiles-not-rendering-osmdroid-offline-maps

**Comment by hlaurent** [comment]
Having the same issue with MBTiles layers. I can try to solve this as you describe with a mapview.invalidate but I have a related issue where onZoom is not being fired if you do a double or a  2 finger pinch to zoom.

**Comment by spyhunter99** [comment]
please retry with 5.4.1

**Comment by spyhunter99** [comment]
#496 related

**Comment by spyhunter99** [comment]
please retry with the latest version (after reading that related ticket). it may be related to threading and queue sizes. Since this ticket is now very old with no feedback. I'm going to close it. Reopen or comment back if  this is still an issue for you @hlaurent

**Comment by RicardoCostaContin** [comment]
same to me using 5.6.5. zoom, then move and have a lot gray area. zoon out and in...and shows.using  offline map tiles
