### ISSUE TITLE
Help needed.

### ISSUE THREAD

**Issue by free4murad** [osmdroid/osmdroid#520]
How to change the position of the ZoomControllers?
![screenshot_20170107-152856](https://cloud.githubusercontent.com/assets/17262180/21740936/c4a67d52-d4ee-11e6-8f9a-9ecfcf6ca449.png)

Currently the controllers are not accessible because they are under the android system buttons

**Comment by spyhunter99** [comment]
easy one. set useBuildInZoomControls to false, then add your own icons to the layout file and handle zoom events that way. there are several examples in the sample app of using custom icons. The built in zoom controls are actually part of android's view system. It's very strange for them to locate themselves under the software buttons. What brand of phone/device is this?

**Comment by free4murad** [comment]
@spyhunter99
Moto G4 Plus
Android 6.0.1

But i want to know if there is some method to reposition the default buttons.
Actually `ZoomButtonController` class has some functions.
Can we use that that?

**Comment by spyhunter99** [comment]
as far as i know, no there isn't. use your own icons with image buttons or whatever you want
