### ISSUE TITLE
For discussion, splitting up the sample app and some additional configurations

### ISSUE THREAD

**Issue by spyhunter99** [osmdroid/osmdroid#527]
Recently I thinking about the "Open Map" app in the play store, "OpenStreetMapView" in source and was wondering if it were possible to turn it into the ultra demo app by also including forge with it and eventually geopackage. This presents a few problems

1. the sample app is also used for nearly all CI tests. If osmdroid-android is min api 8, then we have to keep the app used for CI tests at api 8.
2. Geopackage is going to force a minsdk of 14, Mapsforge is api 11
3. Still need CI tests on api 8
4. Would be nice to still have an demo app that is purely ASF licensed (which means Mapsforge would be out for this)
5. would be nice to have a config for fdroid repo

I was also thinking that it may be help for users of osmdroid to be able to take some of the stuff from the sample app and use it directly in their application. Perhaps the preference activity would be a good candidate.

So i propose that we do the following

- new sample application just for all api 8 functions (basically what the current OpenStreetMapView is)
- modify the existing OpenStreetMapViewer to include the mapsforge libraries and their examples
- remove the osmdroid-forge-app as it won't be needed anymore

this also produces a few problems
- we won't want to duplicate code between the api8 test app and the main demo app. This can be accomplished via gradle extra source folders, or separating things into aar's leaving the apk's to be next to nothing. It's also possible use some gradle copy tasks but that would get yucky 
- licensing, specially with forge in the mix, becomes unclear. In general anything that depends on GPL also becomes GPL. It's possible to do a plugin with dynamic class loading to overcome the hard link but i'm not a lawyer.

this may be more work than it's worth and separate demo apps may be still be the best option

any thoughts or opinions on this?

**Comment by devemux86** [comment]
[Mapsforge](https://github.com/mapsforge/mapsforge) is licensed under LGPL3 and supports Android 2.3.3 (API level 10) and above. :slightly_smiling_face:

**Comment by spyhunter99** [comment]
easier solution, add, ditch the forge app, add Open Map with the dependencies of forge and geopackage, override the minsdk values and exclude google play services. done

**Comment by spyhunter99** [comment]
@devemux86 didn't realize you follow osmdroid but awesome. love your renderer. LGPL and a strange license. i'm not exactly sure what that makes the sample app.

**Comment by spyhunter99** [comment]
resolved on #180

**Comment by devemux86** [comment]
@spyhunter99 I used Osmdroid a lot and I'm happy that it continues to be active. :slightly_smiling_face:

**Comment by spyhunter99** [comment]
@devemux86 i could use your help on a forge specific thing. I'm getting OOM errors and I think i'm not disposing of the forge objects correctly.  Are there any cleanup procedures necessary other than 
AndroidGraphicFactory.clearResourceMemoryCache(); and MultiMapDataStore.close()?

**Comment by devemux86** [comment]
See also the guide [here](https://github.com/mapsforge/mapsforge/blob/master/docs/Getting-Started-Android-App.md).
At exit we use [MapView.destroyAll](https://github.com/mapsforge/mapsforge/blob/master/mapsforge-map-android/src/main/java/org/mapsforge/map/android/view/MapView.java#L189), you could pick any of the calls depending on the classes being used.
