### ISSUE TITLE
message "not a DRM file" spammed on API 17

### ISSUE THREAD

**Issue by Aginor404** [osmdroid/osmdroid#53]
Test system:
Samsung Galaxy Tab 2 7.0 compiled with API 17 (Android 4.2.2)

It looks like this in LogCat:
07-11 16:12:22.828: I/System.out(10661): Not a DRM File, opening notmally
07-11 16:12:22.828: I/System.out(10661): Not a DRM File, opening notmally
07-11 16:12:22.835: I/System.out(10661): Not a DRM File, opening notmally
07-11 16:12:22.835: I/System.out(10661): Not a DRM File, opening notmally
07-11 16:12:22.835: I/System.out(10661): buffer returned
07-11 16:12:22.835: I/System.out(10661): buffer returned
07-11 16:12:22.835: I/System.out(10661): buffer returned
07-11 16:12:22.835: I/System.out(10661): buffer returned
07-11 16:12:22.843: I/System.out(10661): Not a DRM File, opening notmally
07-11 16:12:22.843: I/System.out(10661): Not a DRM File, opening notmally
07-11 16:12:22.843: I/System.out(10661): buffer returned
07-11 16:12:22.843: I/System.out(10661): buffer returned
07-11 16:12:22.843: I/System.out(10661): Not a DRM File, opening notmally
07-11 16:12:22.843: I/System.out(10661): buffer returned
07-11 16:12:22.859: I/System.out(10661): Not a DRM File, opening notmally
07-11 16:12:22.867: I/System.out(10661): buffer returned
07-11 16:12:22.867: I/System.out(10661): Not a DRM File, opening notmally

This happens every few milliseconds as soon as my mapView is visible. I think this may hurt performance a lot (and it also clutters the log like hell).

Permission issue ruled out I think.

Discussion at Google Groups:
https://groups.google.com/forum/?hl=de#!topic/osmdroid/eXbN3MzyYUo

**Comment by kurtzmarc** [comment]
I think this is external to osmdroid and is an Android issue. Feel free to reopen if you find more information.
