### ISSUE TITLE
How to add event listener to the MyLocationOverlay?

### ISSUE THREAD

**Issue by zhaoxuhui** [osmdroid/osmdroid#536]
How to show a menu or a pop window that conatains some buttons when I click the icon?So that I can do futher things.
![324403370story_pic_merged_1484305803549](https://cloud.githubusercontent.com/assets/17122056/21928114/eb8bc8bc-d9c3-11e6-950a-43399d6a5604.jpg)

**Comment by spyhunter99** [comment]
i think you can override on single tap confirmed but i'm not sure if there's a clear example on doing this at the moment. I'd suggest extending the MyLocationOverlay and going from there. The other option is to just use the Marker class to plot my location, however you'll lose the gps accuracy ring and the directional locator.

**Comment by spyhunter99** [comment]
extend MyLocationNewOverlay and add this

````
@Override
	public boolean onSingleTapConfirmed(MotionEvent e, MapView map) {
		if (getLastFix() != null)
			Toast.makeText(map.getContext(), "Tap! I am at " + getLastFix().getLatitude() + "," + getLastFix().getLongitude(), Toast.LENGTH_LONG).show();
		return true;

	}
````

**Comment by spyhunter99** [comment]
sample added and pushed.

**Comment by cfsbhawkins** [comment]
@spyhunter99 Just as a heads up, make sure you had the hit test method thats in marker, if not the you can touch anywhere on the map and it will fire that event.

public boolean hitTest(final MotionEvent event, final MapView mapView){
		final Projection pj = mapView.getProjection();
		pj.toPixels(mPosition, mPositionPixels);
		final Rect screenRect = pj.getIntrinsicScreenRect();
		int x = -mPositionPixels.x + screenRect.left + (int) event.getX();
		int y = -mPositionPixels.y + screenRect.top + (int) event.getY();
		boolean hit = mIcon.getBounds().contains(x, y);
		return hit;
	}
	
	@Override public boolean onSingleTapConfirmed(final MotionEvent event, final MapView mapView){
		boolean touched = hitTest(event, mapView);
		if (touched){
			if (mOnMarkerClickListener == null){
				return onMarkerClickDefault(this, mapView);
			} else {
				return mOnMarkerClickListener.onMarkerClick(this, mapView);
			}
		} else
			return touched;
	}

**Comment by cfsbhawkins** [comment]
Something like this for the hit test works....

 public boolean hitTest(final MotionEvent event, final MapView mapView) {
        if ((mLocation == null)) return false;
        Rect bounds = getMyLocationDrawingBounds(mapView.getZoomLevel(), mLocation,
                mMyLocationPreviousRect);
        boolean hit = bounds.contains((int)event.getX(),(int) event.getY());
        bounds = null;
        return hit;
    }
