### ISSUE TITLE
 Map Tile Packager - created files wont show up in app

### ISSUE THREAD

**Issue by MarcelBerwanger** [osmdroid/osmdroid#538]
I built the "OSMMapTilePackager-5.6.3.jar" file using Gradle an Android Studio,
for the dependencies I added the following lines in the build.gradle file:
`jar {
    manifest {
        attributes(
                'Main-Class': mainClassName
        )
    }
}`
the variable "mainClassName" has the value:
`mainClassName = "org.osmdroid.mtp.OSMMapTilePackager"`

The OSMPackager seems to work fine, since the examples from
https://github.com/osmdroid/osmdroid/blob/master/OSMMapTilePackager/readme.md
are working without any errors.

This is an output from the CMD with the austria example form the given link above (I just changed the zoom-level to keep the output short):
![example_osmmappackager](https://cloud.githubusercontent.com/assets/16281042/21957707/479dc806-da9d-11e6-961e-238ae5e008e6.png)

The content of the generated zip is
/Mapnik/{z}/{x}/{y}.png
Link to the generated .zip file: https://www.dropbox.com/s/5ztlcskr6bukqbs/at_mapnik_13.zip?dl=0

Now, when I am trying to use the created file in my app I get nothing but a blank grid but when I am using the "fr_mapnik_12.zip" file, which is included in the master branch of the OSMMapTilePackager folder, then the map tiles are displayed as they should.
Link to "fr_mapnik_12.zip":
https://github.com/osmdroid/osmdroid/blob/master/OSMMapTilePackager/fr_mapnik_12.zip
I compared the two zip archives (my own and "fr_mapnik_12.zip" from master branch) but they seem identical in terms of file hierarchy and names of the folders/ files.

This is the source code of my app:
`public class MainActivity extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        OpenStreetMapTileProviderConstants.setUserAgentValue(BuildConfig.APPLICATION_ID);
        setContentView(R.layout.activity_main);
        MapView mMapView = (MapView) findViewById(R.id.map);
        mMapView.setTileSource(TileSourceFactory.MAPNIK);
        mMapView.getController().setZoom(0);
        mMapView.setMaxZoomLevel(2);
        mMapView.setMinZoomLevel(0);
        mMapView.setBuiltInZoomControls(true);
        mMapView.setMultiTouchControls(true);
        mMapView.setUseDataConnection(false);
    }
}`
So what I am doing wrong? Please help me to solve this problem.

**Comment by spyhunter99** [comment]
Did you copy your zip tile "at_mapnik_13.zip" to /sdcard/osmdroid/

What version of osmdroid you are running? If it's 5.6 or newer, you should
also check the base path via Configuration.getInstance().
getOsmdroidBasePath()
If you loaded the map view on your device before granting read permissions,
it will default to application private storage, which is
/data/data/packagename/osmdroid

**Comment by MarcelBerwanger** [comment]
@spyhunter99 
yes, I have copied my "at_mapnik_13.zip" to /sdcard/osmdroid/

My osmdroid version is 5.5:
`compile 'org.osmdroid:osmdroid-android:5.5:release@aar'`
What does that base path?

These are the permissions in my AndroidMinifest.xml:
`<uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION"/>
<uses-permission android:name="android.permission.ACCESS_FINE_LOCATION"/>
<uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />
<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
<uses-permission android:name="android.permission.INTERNET" />
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />`

But the map view is working fine when I am using the file "fr_mapnik_12.zip" in /sdcard/osmdroid so I think it should read the data from the correct path

**Comment by spyhunter99** [comment]
permissions look fine. That version isn't effected by what i mentioned earlier. All you should need to do is copy the new tile zip to /sdcard/osmdroid
`adb push at_mapnik_13.zip /sdcard/osmdroid/`

**Comment by spyhunter99** [comment]
and the zip it produced looks fine. Are you sure the coordinates that you entered are what is currently visible on the map when it loads? You may want to call mMapView .getController().setCenter(lat,lon); to coordinates within the bounding box that was downloaded

**Comment by MarcelBerwanger** [comment]
I copy the files to a physical device via the "connect storage to PC" option by simply dragging & dropping it to /sdcard/osmdroid

I have set a marker within the selected area but no matter how much I zoom in I only see an empty grid.

Do you have any other clues about what could be wrong? Could it be the map tile packager programm? Or maybe the parameters for the map tile packager programm I used (see my first post)?

**Comment by spyhunter99** [comment]
try zooming out all the way. If you downloaded 0 to zoom level 4. it's like
looking at the plant from the moon

**Comment by MarcelBerwanger** [comment]
Yes I tried that too, i zoomed out to zoom-level 0. I think it has something to do with the generated file itself because the file from the master branch "fr_mapnik_12.zip" has the same zoom levels and it is working fine with my setup - is there a possibility to check whether the generated file is correct or not?

**Comment by spyhunter99** [comment]
I wonder.... can you unzip the tile zip that's not working on your computer
and try to view the tiles in a browser (or anything that can display images)

**Comment by MarcelBerwanger** [comment]
Yes, that is working fine. I can view all pictures in the zip.
Do you maybe know with which parameters the demo file in the master branch was created?

**Comment by spyhunter99** [comment]
@MarcelBerwanger not too sure. i think it was with one of the examples in the readme. it's been a while

**Comment by MarcelBerwanger** [comment]
@spyhunter99 Hmm okay I am going to take a look at it. Thanks you for your patience!

**Comment by MarcelBerwanger** [comment]
@spyhunter99 Okay I looked through it but found nothing... I decided now to use the downloadAreaAsync  method from the CacheManager class to get my offline tiles. This, at least, is working fine in my case.
Thank you very much for your patience and help!

**Comment by Evgenchu** [comment]
I have exactly the same problem. When I use zip from MOBAC, everything is displayed well. Archives from OSMMapTilePackager and MOBAC seem identical in terms of file hierarchy and names of the folders/ files. But from OSMMapTilePackager tiles are not displayed.

**Comment by Evgenchu** [comment]
I had the following problem. 
In the zip from the MBOAC, entries had slash separators ("/"), and in the zip from OSMMapTilePackager the backslash ("\"). 
In the FolderZipper.class in addFolderToZip() I added the line: name = name.replaceAll("\\\\", "/"); 
And it worked for me.
