### ISSUE TITLE
Why I zoom the map, my all markers zoom  at the same time。

### ISSUE THREAD

**Issue by ding209** [osmdroid/osmdroid#539]
When I zoom the map, my markers is scaled,
map zoom in and markers zoom in ,map zoom out and markers zoom out.
Help me please. I didn‘’t find the solution to resolve it

**Comment by spyhunter99** [comment]
sounds perfectly normal, it's part of the animation that happens when pinch zooming

**Comment by ding209** [comment]
Thank you for your answer, But I think it's not normal.
As shown in the figure below.
![1](https://cloud.githubusercontent.com/assets/15820075/22005629/e1874c90-dc9f-11e6-979a-70c598c5b7d6.png)
![2](https://cloud.githubusercontent.com/assets/15820075/22005630/e187b680-dc9f-11e6-8bde-9da8f9dffdad.png)
When I zoom in the map,My marker also be amplified. I hope the marker will not change when I zoom.
 I found that when using other map to zoom marker will not change,So I want to solve it. Thank you!

**Comment by spyhunter99** [comment]
looks like you're using a custom marker and have implemented your own onDraw method. You may want to look at the draw method implementations on the existing implementations (ItemizedItemOverlay and Marker) to see how it's done with those classes.

**Comment by spyhunter99** [comment]
not much i can do for you on this besides referring to the build in examples. Your overlay does look nice though!

**Comment by niray** [comment]
I have the same question, when I zoom the map ,the overlay will zoom also... :< @ding209 请问您解决了没？

**Comment by spyhunter99** [comment]
I'm assuming this is for some sort of custom overlay, because none of the provided overlays do this. No one provided code to reproduce the problem so I can't do much to help with this.

**Comment by niray** [comment]
`Marker mMarker = new Marker(mapView);
        mMarker.setPosition(geoPoint);
        mMarker.setIcon(drawable);
        mMarker.setOnMarkerClickListener(listener);
        mMarker.setAnchor(0.5f, 0.5f); 
        OverlayManager controller = mapView.getOverlayManager();
        controller.add(mMarker);
`
:)

**Comment by ding209** [comment]
@niray 不好意思， 这个我依旧没解决，所以我换了显示方式，不再创建Marker，而是使用ItemizedOverlayWithFocus这个OverlayItem集合来显示，OverlayItem就相当于Marker，但是只能在创建OverlayItem的时候设置一个坐标值，然后就不能更改，想要更改的话需要重新创建OverlayItem并添加到ItemizedOverlayWithFocus中。。

**Comment by niray** [comment]
@ding209  感谢你的方案，我使用了，也成功了，但是现在我遇到另外一个问题，就是我想把        `Polyline` 也通过`ItemizedOverlayWithFocus<OverlayItem>`画在地图上，但是好像没有找到`ItemizedOverlayWithFocus<Polyline>` 


How can I draw a Polyline by ItemizedOverlayWithFocus<Polyline>, I don't find a way to solve it.

**Comment by niray** [comment]
Polyline pathOverlay = Polyline()
        pathOverlay.color = Color.parseColor("#99ffff00")
        pathOverlay.width = 5.0f
        pathOverlay.points = points 
        mMapView.overlays.add(0, pathOverlay)
 I use this way to add Polyline on the map , but when I zoom out and zoom in the map , the polyline will also zoom out or zoom in during the zoom animation..

**Comment by ding209** [comment]
@niray  这个没办法。我也没有解决。很多方法都试过了

**Comment by niray** [comment]
@ding209  感谢，不过我发现在《行者》这个APP里使用的OSMDROID 中 ，他就实现了可以保持原大小的Polyline，不知道他是如何实现的，我也尝试了各种各样的方法，最终放弃了……

**Comment by ding209** [comment]
@niray  这个APP我也看了，确实实现的很棒，反编译后也没发现其他什么设置，当时自己也尝试了很多，反正还是没解决。。

**Comment by niray** [comment]
@ding209 哈，没想到你跟我做了同样的事，我看了他的MapUtil里的代码，发现他可能自己封装了一个Polyline,里面竟然有一个Z坐标系的属性值，但是这个OSMDROID里没有这个Z属性，可能是他自己写的，但是我无法找到这个关键的代码。。

`    private static g m14275a(Context context, List<LatLng> list, int i, int i2) {
        g gVar = new g(context);
        gVar.a((float) Density.m13628a(context, ((float) i) * 0.35f));
        gVar.a(i2);
        gVar.a(OsmMapUtil.m14276a((List) list));
        return gVar;
    }` 这是老板的代码

`
   private static Polyline buildLine(Context context, List<IGeoPoint> points, int width, int color, int zindex) {
        if (context == null || points == null) {
            return null;
        }
        Polyline polyline = new Polyline(context);
        polyline.setWidth((float) Density.dp2px(context, ((float) width) * 0.35f));
        polyline.setColor(color);
        polyline.setPoints(convertPoint(points));
        polyline.setzIndex(zindex);
        return polyline;
    }
`
这个是最新的代码……
但是他的`Polyline`我找不到import

**Comment by niray** [comment]
private static Polyline buildLine(Context context, List<IGeoPoint> points, int width, int color, int zindex) {
        if (context == null || points == null) {
            return null;
        }
        Polyline polyline = new Polyline(context);
        polyline.setWidth((float) Density.dp2px(context, ((float) width) * 0.35f));
        polyline.setColor(color);
        polyline.setPoints(convertPoint(points));
        polyline.setzIndex(zindex);
        return polyline;
    }

**Comment by niray** [comment]
private static g m14275a(Context context, List<LatLng> list, int i, int i2) { g gVar = new g(context); gVar.a((float) Density.m13628a(context, ((float) i) * 0.35f)); gVar.a(i2); gVar.a(OsmMapUtil.m14276a((List) list)); return gVar; }

**Comment by firelight22** [comment]
I hava the same problem but I didn't use these methods above. I'm using the `mMapView.addView()` method every time I want add a marker. When I'm zooming, all markers are zooming too. Is there another way to do it ? Please note that my marker is a View and I change a timer every second on each marker.

**Comment by firelight22** [comment]
When I was choosing the best method to use 2 years ago, I've asked on StackOverflow and KurtzMarc told me to use this. [SO post](https://stackoverflow.com/questions/29776930/add-a-view-layout-to-a-map-on-osmdroid). What do you advise me to use ? I want to add my own layout and not something like "OverlayItem"

**Comment by MKergall** [comment]
Use the Marker, not the OverlayItem. 
Tutorial [here ](https://github.com/MKergall/osmbonuspack/wiki/Tutorial_2#7-customizing-the-bubble-behaviour) on how to customize the bubble.

**Comment by firelight22** [comment]
Thank you but I don't want to add a bubble when I click on a point. I want the bubble directly on the map. This bubble is a layout not a Drawable. What is the best practice in this case ?

**Comment by MKergall** [comment]
I would recommend to create a Marker, with for instance a 1x1px transparent icon, and set a Marker infowindow customized to your need. 
This Marker infowindow will be an actual Android View, not a Drawable. 

But of course, you can also follow @kurtzmarc solution. In fact, Marker infowindow is based on it.

**Comment by firelight22** [comment]
Thank you @MKergall but I've the same problem now with InfoWindow. When I unzoom, the info window is detaching from the marker. But the marker is stick to the map when I zoom and unzoom.

**Comment by MKergall** [comment]
osmdroid graphical effect during zoom operation is not perfect, as it's not based on repeated mapview redraws, but on a technical hint: Android zooming effect applied on the latest draw of the mapview. 
So there is nothing we can do at overlay level. 

@spyhunter99 now we have fast CPU on devices, maybe this zoom mechanism could be revisited. Effectively, the zoom effect is quite ugly on overlays.

**Comment by firelight22** [comment]
I didn't understand the difference between the marker and InfoWindow. The marker is a picture draw on the map and the infoWindow is just a view above the map ? How to modify the zoom mechanism ? It's part of the OSMdroid API ? Maybe I can help to resolve this problem ? @spyhunter99 @MKergall

**Comment by spyhunter99** [comment]
Marker is a single point on the map with an icon. The info window is shown when the icon is tapped.

The zoom mechanism is an android animation that scales the currently viewable images (tiles and whatnot) while the zoom is in progress (fingers on screen) or during an api call to setZoom, zoomIn, zoomOut or zoomToBounds. The animation is contained within the MapView class. You should be able to extend map view and override the animation. Once the animation is complete, the closest zoom level to whatever the final image scale was is selected, then the map is redrawn with the new map tile set, which also causes all children overlays to redraw.

@MKergall not sure what we would replace it with.

**Comment by MKergall** [comment]
My idea is to completely remove the android zoom animation, and trigger mapview ondraw as much as needed: 
- when zooming by fingers, at each ACTION_MOVE event. 
- when zooming by API, ... regularly (there is certainly a nice Android way to do that)
So the drawing should be perfect all the time. 

I imagine this is more or less the way it's done inside Google Maps, Waze, or MapBox android sdk.

**Comment by firelight22** [comment]
I've override onTouchEvent in my MapView extend. How can we fire onDraw() with all the views ? With the invalidate() method ? @MKergall You mean that everytime the ACTION_MOVE event is fire, we will re-draw everything ?

How to "disable" the zoom animation of Android? I think this is the problem. Because when I move the map, my views are correctly positioned, but the problem is only when I zoom or unzoom?

**Comment by liuzy1993** [comment]
Can you tell me how you did it? I just need this zoom with map zoom Icon
