### ISSUE TITLE
Swiping left or right on the map moves to another fragment on a tablet

### ISSUE THREAD

**Issue by Raptorel** [osmdroid/osmdroid#540]
Hello,

I have implemented OSMDroid in an application on a tablet that is "tabbed" - you swipe left and right to get to another tab. Now, if you push on the map and drag up or down, then you can also go left-right (west-east). But if you try to go west or east directly, by pushing on the map and dragging, the application will actually swipe left or right to another tab, and not scroll the map.

Do you have any experience with this? How can I say something like "when I swipe left or right on the map, I actually want to scroll the map, and not go to another tab of the application", in code? Because right now, the only way to scroll the map east or west is to first scroll it north or south, and only then you can go east or west, without the application "swiping" to another tab (because when you go north or south, there are no "north" or "south" tabs, only west or east (left or right) tabs, so it doesn't confuse  scrolling the map with swiping to get to another tab when you're doing it vertically).

Hopefully I've been pretty clear in what I'm trying to say.

**Comment by spyhunter99** [comment]
Yes, there's an example and a solution for fixing it.
https://github.com/osmdroid/osmdroid/tree/master/OpenStreetMapViewer/src/main/java/org/osmdroid/samplefragments/layouts

**Comment by spyhunter99** [comment]
see Map in a scroll view and map in a view pager, and of course the RecyclerMapView

**Comment by Raptorel** [comment]
OK, I'll look into it, thanks!

**Comment by Raptorel** [comment]
Hello,

I looked in the files that you mentioned but it's beyond me how they prevent the swiping from a fragment to another using the code inside of them. Are you sure they work? I don't see any mechanism that prevents the scrolling from one fragment to another when you try to scroll the actual map East or West.

In fact, I've tried the Map in a View Pager demonstration on my phone and it behaves the same as I described - when you move on the map left or right (West or East) you move to another fragment instead of scrolling on the map.

I want to make it such that when you put your finger somewhere in the middle of the screen and move left or right - the map moves; whereas when you put your finger on the edge of the screen and swipe, you move to another fragment.

Do you know how this could be implemented?

Thanks,
Robert.

**Comment by wolojoli** [comment]
I use ViewPager.setSwipeable() for that.

**Comment by Raptorel** [comment]
I looked for the method you specified but there is no such method. However, I found something else: https://stackoverflow.com/questions/9650265/how-do-disable-paging-by-swiping-with-finger-in-viewpager-but-still-be-able-to-s

**Comment by wolojoli** [comment]
Then us ToggleViewPager:
https://github.com/Bonnett/Something-Awful-Android/blob/master/Awful.apk/src/main/java/com/ferg/awfulapp/widget/ToggleViewPager.java
