### ISSUE TITLE
Allow to specify mSpecificArchivesProvided in MapTilefileArchiveProvider constructor

### ISSUE THREAD

**Issue by hlaurent** [osmdroid/osmdroid#542]
I am trying to add the new OpenSeaMap tiles following the SampleOpenSeaMap  code.
We construct a MapTileProviderBasic :
mProvider = new MapTileProviderBasic(getContext());

which creates a MapTileFileArchiveProvider :
archiveProvider = new MapTileFileArchiveProvider(
				pRegisterReceiver, pTileSource);
The issue is that when it does so, the IArchiveFile[] pArchives is null and MapTileFileArchiveProvider is trying to findArchiveFiles() :

public MapTileFileArchiveProvider(final IRegisterReceiver pRegisterReceiver,
			final ITileSource pTileSource, final IArchiveFile[] pArchives) {
		super(pRegisterReceiver,
			Configuration.getInstance().getTileFileSystemThreads(),
			Configuration.getInstance().getTileFileSystemMaxQueueSize());

		setTileSource(pTileSource);

		if (pArchives == null) {
			mSpecificArchivesProvided = false;
			findArchiveFiles();
		} else {
			mSpecificArchivesProvided = true;
			for (int i = pArchives.length - 1; i >= 0; i--) {
				mArchiveFiles.add(pArchives[i]);
			}
		}

	}

I do have some mbtiles files in my app that are being found by findArchiveFiles and disrupt the displaying of the OpenSeaMap tiles.

Could it be possible to specify mSpecificArchivesProvided in MapTilefileArchiveProvider constructor (here it would be true and pArchives would be empty) to prevent this?

**Comment by spyhunter99** [comment]
ahh that's because mbtiles does not support or label itself with a tile source. If not using mbtiles isn't an option, make your own version of MapTileProviderBasic and pass in whatever arguments you want

**Comment by hlaurent** [comment]
Ok, thanks, I will make my own version of MapTileProviderBasic.
