### ISSUE TITLE
permissions issue on android 6 with permissions granted (sample app)

### ISSUE THREAD

**Issue by spyhunter99** [osmdroid/osmdroid#544]
OsmDroid: Using tile source: Mapnik
01-17 19:05:42.335 12667 12667 W SQLiteLog: (28) failed to open "/mnt/media_rw/FFFB-1417/osmdroid/tiles/cache.db" with flag (131138) and mode_t (0) due to error (13)
01-17 19:05:42.335 12667 12667 W SQLiteLog: (28) failed to open "/mnt/media_rw/FFFB-1417/osmdroid/tiles/cache.db" with flag (131072) and mode_t (0) due to error (13)
01-17 19:05:42.335 12667 12667 E SQLiteLog: (14) cannot open file at line 31517 of [2ef4f3a5b1]
01-17 19:05:42.335 12667 12667 E SQLiteLog: (14) os_unix.c:31517: (13) open(/mnt/media_rw/FFFB-1417/osmdroid/tiles/cache.db) -
01-17 19:05:42.335 12667 12667 E SQLiteDatabase: Failed to open database '/mnt/media_rw/FFFB-1417/osmdroid/tiles/cache.db'.
01-17 19:05:42.335 12667 12667 E SQLiteDatabase: android.database.sqlite.SQLiteCantOpenDatabaseException: unknown error (code 1806): Could not open database
01-17 19:05:42.335 12667 12667 E SQLiteDatabase: #################################################################
01-17 19:05:42.335 12667 12667 E SQLiteDatabase: Error Code : 1806 (SQLITE_CANTOPEN_EACCES)
01-17 19:05:42.335 12667 12667 E SQLiteDatabase: Caused By : Application has no permission to open the specified database file.
01-17 19:05:42.335 12667 12667 E SQLiteDatabase:        (unknown error (code 1806): Could not open database)
01-17 19:05:42.335 12667 12667 E SQLiteDatabase: #################################################################
01-17 19:05:42.335 12667 12667 E SQLiteDatabase:        at android.database.sqlite.SQLiteConnection.nativeOpen(Native Method)
01-17 19:05:42.335 12667 12667 E SQLiteDatabase:        at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:283)

**Comment by spyhunter99** [comment]
01-17 19:07:32.135 12667 12667 I OsmDroid: Using tile source: Mapnik
01-17 19:07:32.135 12667 12667 W SQLiteLog: (28) failed to open "/storage/emulated/0/osmdroid/tiles/cache.db" with flag (131138) and mode_t (0) due to error (13)
01-17 19:07:32.135 12667 12667 W SQLiteLog: (28) failed to open "/storage/emulated/0/osmdroid/tiles/cache.db" with flag (131072) and mode_t (0) due to error (13)
01-17 19:07:32.135 12667 12667 E SQLiteLog: (14) cannot open file at line 31517 of [2ef4f3a5b1]
01-17 19:07:32.135 12667 12667 E SQLiteLog: (14) os_unix.c:31517: (13) open(/storage/emulated/0/osmdroid/tiles/cache.db) -
01-17 19:07:32.135 12667 12667 E SQLiteDatabase: Failed to open database '/storage/emulated/0/osmdroid/tiles/cache.db'.
01-17 19:07:32.135 12667 12667 E SQLiteDatabase: android.database.sqlite.SQLiteCantOpenDatabaseException: unknown error (code 1806): Could not open database
01-17 19:07:32.135 12667 12667 E SQLiteDatabase: #################################################################
01-17 19:07:32.135 12667 12667 E SQLiteDatabase: Error Code : 1806 (SQLITE_CANTOPEN_EACCES)
01-17 19:07:32.135 12667 12667 E SQLiteDatabase: Caused By : Application has no permission to open the specified database file.
01-17 19:07:32.135 12667 12667 E SQLiteDatabase:        (unknown error (code 1806): Could not open database)
01-17 19:07:32.135 12667 12667 E SQLiteDatabase: #################################################################
01-17 19:07:32.135 12667 12667 E SQLiteDatabase:        at android.database.sqlite.SQLiteConnection.nativeOpen(Native Method)
01-17 19:07:32.135 12667 12667 E SQLiteDatabase:        at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:283)
01-17 19:07:32.135 12667 12667 E SQLiteDatabase:        at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:210)
01-17 19:07:32.135 12667 12667 E SQLiteDatabase:        at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:512)

**Comment by spyhunter99** [comment]
also second time around, sample app doesn't list app private storage as an option (on hardware, emulator is fine)

secondary storage appears to be nonwritable for some reason

**Comment by spyhunter99** [comment]
for some reason my samsung device's /storage/extSdcard, a physical removal sdcard, is not writable for osmdroid/open map but is writable by other apps. It has all the permissions i thought were required but i'm at a loss on this one

**Comment by wolojoli** [comment]
Are you using the right folder? You should use:
/Android/data/<package>

**Comment by spyhunter99** [comment]
StorageUtils, when requested, finds all mount points that are writable. Storage utils does find the external sdcard mount point but it is being denied write access to it for some reason. When manually setting that location, the sqlwrite fails to create the cache database and no tiles are disabled.

/Android/data/package is new to me. Historically, application private storage was always at /data/data/package which should always be writable by an application. This is the fall back for the sample app, but.... you're more likely to have additional external storage than internal storage and storing the tile cache in a shared location vs private is advantageous for multiple apps using osmdroid on the same device.

**Comment by wolojoli** [comment]
private storage is still on the same place. Write permissions on the internal storage are no problem, but when you want to write to the external sdcard you should use the directory which is returned by getExternalFileDirs(NULL). That is the only directory where you have write permissions.

**Comment by spyhunter99** [comment]
@wolojoli progress....

Context.getExternalFileDirs(null) appears to have done the trick. I can now get a writable location at

`/storage/FFFB-1417/Android/data/org.osmdroid/files`

however, it want `/storage/FFFB-1417/osmdroid` despite my best effort, i can't figure out why this location isn't writable. Either android some the vendor (saming s5 in this case) may be put some additional restrictions on it. On previous builds (i had an update recently) of Android M it was fine.

**Comment by wolojoli** [comment]
Those restrictions are put there by Android, and are there since Kitkat as far as I know.  Since Lollipop there is a sort of workaround, but it is not very user friendly. You can read a little more about it [here](https://metactrl.com/docs/sdcard-on-lollipop/).

**Comment by SravanKumarReddy1990** [comment]
Guys android 6 given new way assigning permission of external storage so i have given ActivityCompat.requestPermissions(LoginActivity.this, new String[{Manifest.permission.READ_EXTERNAL_STORAGE,Manifest.permission.ACCESS_FINE_LOCATION},1); or else goto settings->Applications->Application Manager->choose your app->permission and on permissions so that problem will solve.
