### ISSUE TITLE
Adding osmdroid as a gradle dependency

### ISSUE THREAD

**Issue by AlfredAfutu** [osmdroid/osmdroid#545]
When i sync gradle after adding the dependency i get:

Error:A problem occurred configuring project ':app'.
> Could not find osmdroid-android-release.aar (org.osmdroid:osmdroid-android:5.6.2).
  Searched in the following locations:
      https://jcenter.bintray.com/org/osmdroid/osmdroid-android/5.6.2/osmdroid-android-5.6.2-release.aar

**Comment by spyhunter99** [comment]
someone did us a "favor" and added a redirect or something like that on jcenter, which is now invalid. solution: move mavenCentral() above jcenter() in your gradle file.

**Comment by spyhunter99** [comment]
https://bintray.com/bintray/jcenter/org.osmdroid%3Aosmdroid-android/5.6.3#files/org/osmdroid/osmdroid-android/5.6.3

https://bintray.com/bintray/jcenter/org.osmdroid%3Aosmdroid-android/5.6.2#files/org/osmdroid/osmdroid-android/5.6.2

it's clearly there. what other dependencies do you have? can you post the line from your gradle build file that references osmdroid?

**Comment by AlfredAfutu** [comment]
compile 'org.osmdroid:osmdroid-android:5.6.3'

I added the mavenCentral() before jcenter() in my project level gradle file since jcenter() is not present in my app level gradle file still no luck

**Comment by AlfredAfutu** [comment]
This is the list of dependencies in my app level gradle file

 compile fileTree(include: ['*.jar'], dir: 'libs')
    compile 'com.google.android.gms:play-services:9.6.1'
    compile('com.crashlytics.sdk.android:crashlytics:2.5.7@aar') {
        transitive = true;
    }
    compile 'com.koushikdutta.async:androidasync:2.+'
    compile 'com.android.support:multidex:1.0.1'
    compile 'com.github.JakeWharton:ViewPagerIndicator:2.4.1@aar'
    compile 'com.android.volley:volley:1.0.0'
    compile files('libs/jts-1.14.jar')
    compile 'com.amulyakhare:com.amulyakhare.textdrawable:1.0.1'
    compile 'com.github.MKergall:osmbonuspack:6.0'
    compile files('libs/ormlite-android-5.0.jar')
    androidTestCompile 'com.android.support:support-annotations:24.0.0'
    androidTestCompile 'com.android.support.test:runner:0.5'
    androidTestCompile 'com.android.support.test:rules:0.5'
    //Hamcrest library for assertions
    androidTestCompile 'org.hamcrest:hamcrest-library:1.3'
    testCompile 'junit:junit:4.12'
    testCompile 'org.robolectric:robolectric:3.1.4'
    testCompile 'org.robolectric:shadows-multidex:3.1.4'
    compile 'org.osmdroid:osmdroid-android:5.6.3'

**Comment by spyhunter99** [comment]
you have conflicting versions. try updating osmbonouspack to 6.2. It depends on osmdroid and you may end up with multiple versions. I'd suggest just using the osmbonouspack reference, since it should bring in osmdroid automagically

**Comment by spyhunter99** [comment]
paging @MKergall on this for clarification. Looks like obp needs osmdroid 5.5 which does need the -release qualifier. Gradle is probably trying to just bump up the version number. Jcenter redirects are not the cause, it's gradle and your dependencies are out of whack

**Comment by AlfredAfutu** [comment]
It looks like the osmbonus pack reference alone works. Then i would have to track osmbonuspack to increase version numbers in my gradle as as when updates are available. Thanks

**Comment by spyhunter99** [comment]
np
