### ISSUE TITLE
Change cache dir

### ISSUE THREAD

**Issue by MKergall** [osmdroid/osmdroid#548]
Since I moved to 5.6, with SqLite + partitions scanning, this moved my osmdroid path on the (large) external SD card. As expected. 
But I also observed a constant behaviour: as soon as the tiles/cache.db file reaches 7 Mo, tiles display slows down incredibly. In fact, it's usually much more efficient to destroy this file completely and start again (getting tiles from 3G network). 

I suspect my external SD card to be much (much) slower than the built-in SD card, but I've no evidence of that. Or a perf issue on osmdroid Sqlite cache system? But this should be well known now. 

I'm now trying to benchmark the internal/external perf aspect. I tried this: 

```
	Configuration.getInstance().setOsmdroidBasePath((new File(Environment.getExternalStorageDirectory().getAbsolutePath() +"/osmdroid")));
	Configuration.getInstance().setOsmdroidTileCache((new File(Environment.getExternalStorageDirectory().getAbsolutePath() +"/osmdroid/tiles")));
	map = (MapView) findViewById(R.id.map);

```

but it has no effect on the cache file location. 
The SampleAlternateCacheDir is not really clear on what should be done. 
What I'm supposed to do to change this cache file location?

**Comment by spyhunter99** [comment]
after changing the cache and base paths, you have to destroy the map and
restart it. this can be an activity change or a fragment transaction type
of deal but the changes are only loaded when the mapvew is created, either
by the layout inflator or when programmatically creating the map view

**Comment by spyhunter99** [comment]
I think the only change regarding this was that it now self trims the database need on the trim size. Trim size is set to be at 95% of the free space,  maybe that's broken or needs to be revisited

**Comment by MKergall** [comment]
When moving back the cache to the built-in SD, it's fast again: cache file above 20Mb, still no issue at all. 
So it really seems to be related to the perf of my external SD card. Strange. 

About Triming: my external SD has 164Gb total size, 3Gb used. The cache had 7Mb: far below the 95% of free space.

**Comment by spyhunter99** [comment]
hmm i can change the algorithm to check every now and then instead of on
every insert, however the check should be super fast. It's just asking the
file system how big is the database file. Hmm. Previous versions only
checked on start up. Thoughts?

**Comment by spyhunter99** [comment]
@MKergall can you check the trim size? I know I said 95% but what i said and what was calculated are two different things. I think it's Configuration.getInstance().getCacheTrimSize(). This is for your massive external sd card.

**Comment by spyhunter99** [comment]
@MKergall your example code of changing the cache dir is actually doing so after the map was created. try setting it before setContentView

**Comment by MKergall** [comment]
My new attempt: 

	@Override public void onCreate(Bundle savedInstanceState) {
		super.onCreate(savedInstanceState);
		Configuration.getInstance().setOsmdroidBasePath(new File(Environment.getExternalStorageDirectory(), "osmdroid1"));
		Configuration.getInstance().setOsmdroidTileCache(new File(Environment.getExternalStorageDirectory(), "osmdroid1/tiles"));

		LayoutInflater inflater = (LayoutInflater)getSystemService(Context.LAYOUT_INFLATER_SERVICE);
		View v = inflater.inflate(R.layout.main, null);
		setContentView(v);
		map = (MapView) v.findViewById(R.id.map);

		// etc ...
}

I deleted all previous cache dirs before launching the app. 
I now see 2 cache dirs: one "osmdroid1/tiles" on builtin SD, and one "osmdroid/tiles" on external SD!

**Comment by spyhunter99** [comment]
@MKergall is this application available on github? You're certain there's no other calls to create a mapview or mapprovider or any other instances of osmdroid? no other background apps running with osmdroid?

**Comment by MKergall** [comment]
is this application available on github? Yes: OSMNavigator, in [MapActivity](https://github.com/MKergall/osmbonuspack/blob/master/OSMNavigator/src/main/java/com/osmnavigator/MapActivity.java). I just pushed my attempt, so you can have a look. 

You're certain there's no other calls to create a mapview or mapprovider or any other instances of osmdroid? Yes. 

no other background apps running with osmdroid? Yes.

**Comment by spyhunter99** [comment]
ahh sorry for the late reply. this behavior kind of makes sense. the default config provider, for backwards compatibility reasons, will auto select a writable storage location when it is created and thus will try to make the osmdroid directories.
see https://github.com/osmdroid/osmdroid/blob/446fefb1d275934fb1f098c281546b1b257da584/osmdroid-android/src/main/java/org/osmdroid/config/DefaultConfigurationProvider.java#L69

**Comment by MKergall** [comment]
Effectively: the osmdroid/tiles dir on external SD remains empty, while the osmdroid1/tiles on builtin SD holds the cache.sql file which is growing. 
Thanks for the help!
