### ISSUE TITLE
incomplete map is shown

### ISSUE THREAD

**Issue by bindto** [osmdroid/osmdroid#55]
looks like it is very old issue, at least since early 3.X and still is not fixed

What steps will reproduce the problem?

  use openstreetmap in online mode, the tiles will be cached.
  change to offline mode.  on start, screen is completely filled with tiles,
  however, swipe any direction and some tiles are not loaded, swipe more
  and just empty grid is.
  the tiles are for sure in the cache, if zoom out and zoom in 
  everything is shown in normal way. 

after swipe it looks similar to image in issue "some tiles not refresh after zoom #52", but
starting from center everything is empty in opposite direction of the swipe.

What version of the product are you using? On what operating system?

android/ osmdroid 4.2

**Comment by spyhunter99** [comment]
This sounds a lot like "scaled" tiles. Consider the following scenario
zoom level 11, all tiles in view are cached, as well as adjenct tiles
zoom level 12, no tiles are cached.
flip to offline mode
zoom to level 12, tiles in the initial view are "scaled" from zoom level 11, but only in the current view. When scrolling sideways, the grid is displayed.

bottom line, this is normal behavior. if you want to change this behavior, please open a pull request. The algorithm would basically be, if the tile at a given zoom doesn't exist, check for zoom-1, then scale it.

**Comment by spyhunter99** [comment]
no reply in early two years. closing. reopen if it's still an issue
