### ISSUE TITLE
Running slow when upgrading osmdroid and bonus pack

### ISSUE THREAD

**Issue by idafroseth** [osmdroid/osmdroid#552]
Hi,
When upgrading from osmdroid from 5.1aar to 5.6.3 and bonuspack  5.7  to 6.2. my application have started to run very slow, like the menu is lagging when expanding it for example. I am also monitoring the battery usage and it have increased after the upgrade. The issue seems to be the same regardless of numbers of markers in the map. 

Is this a known issue?

**Comment by spyhunter99** [comment]
aside from #548, first report of it. try turning on debug logging, that will probably shed a light on it. Also the device monitor should help you narrow down the cause

````
 Configuration.getInstance().setDebugMapView(true);
        Configuration.getInstance().setDebugMode(true);
        Configuration.getInstance().setDebugTileProviders(true);
        Configuration.getInstance().setMapViewHardwareAccelerated(true);
Configuration.getInstance().setDebugMapTileDownloader(true);
````

**Comment by idafroseth** [comment]
I will try that. I am using the RadiusMarkerClusterer and at first I though it was related to it.

**Comment by stoanarrr** [comment]
I had this lag to. 
With 5.6 the mapview is hardware disabled by default.
Setting the view back to hardware acceleration solved the problem for me.

osmapView.setLayerType(View.LAYER_TYPE_HARDWARE, null);

**Comment by idafroseth** [comment]
Ok, thanks I will try that.

**Comment by idafroseth** [comment]
Adding HW acceleration solved the problem! Thanks.
