### ISSUE TITLE
PathOverlay not working in v5.6.3

### ISSUE THREAD

**Issue by Artemprodigy** [osmdroid/osmdroid#554]
In the example SampleOsmPath does not work PathOverlay. He does not draw the line. How to work with PathOverlay in the new version?

**Comment by spyhunter99** [comment]
Not exactly sure what you're referring too. The SampleOsmPath creates a polyline and renders it on screen. It doesn't work for you?

**Comment by Artemprodigy** [comment]
Polyline works good, 

```
		Polyline line = new Polyline();
		line.setWidth(20f);
		List<GeoPoint> pts = new ArrayList<>();
		pts.add(new GeoPoint(40.796788, -73.949232));
		pts.add(new GeoPoint(40.796788, -73.981762));
		line.setPoints(pts);
		line.setGeodesic(true);		
		mMapView.getOverlayManager().add(line);
```

This code works.

But the code from example not work

```
		PathOverlay path = new PathOverlay(Color.GREEN, 20f);
		List<IGeoPoint> pathpoints = new ArrayList<>();
		pathpoints.add(new GeoPoint(40.796788, -73.949232));
		pathpoints.add(new GeoPoint(40.796788, -73.981762));
		path.getPaint().setStyle(Paint.Style.FILL);
		path.addPoints(pathpoints);
		mMapView.getOverlays().add(path);
```

**Comment by spyhunter99** [comment]
PathOverlay was deprecated a while ago, documented in #40 

`@deprecated This class is no longer maintained and has various issues. Instead you should use the Polyline class in OSMBonusPack.`

**Comment by Artemprodigy** [comment]
Other words, we can say officially, that PathOverlay can not be displayed in the latest version osmdroid?

**Comment by spyhunter99** [comment]
well it's deprecated. you can still turn on hardware acceleration if you want to continue using it, but eventually it will be removed

**Comment by Artemprodigy** [comment]
I turned on hardware acceleration on my Android 4.4.2. But that does not give success to draw PathOverlay.
Are you sure that it is possible even to use PathOverlay in the new version osmdroid? Can you make an example with a PathOverlay?

**Comment by wolojoli** [comment]
Maybe it helps when you set the style to STROKE instead of FILL.

**Comment by Artemprodigy** [comment]
Changing style does not take any results.

**Comment by spyhunter99** [comment]
https://github.com/osmdroid/osmdroid/blob/osmdroid-parent-5.0/OpenStreetMapViewer/src/main/java/org/osmdroid/samplefragments/SampleOsmPath.java

An older version of the same sample using path overlay
