### ISSUE TITLE
Problem with custom MarkerFocused bounding for ItemizedOverlayWithFocus

### ISSUE THREAD

**Issue by Lexxtor** [osmdroid/osmdroid#558]
I creating overlay like this:
```java
new ItemizedOverlayWithFocus<OverlayItem>(
            items,
            getResources().getDrawable(R.drawable.my_marker_default),
            getResources().getDrawable(R.drawable.my_marker_default_focused_base),
            ItemizedOverlayWithFocus.NOT_SET,
            new MyItemizedIconOverlay.OnItemGestureListener<OverlayItem>(),
            getBaseContext()
);
```
Problem: When I click on marker, tooltip is showed over the marker, not on the top of it, as I want and as with default marker `Drawable`.

As I see here: https://github.com/osmdroid/osmdroid/blob/master/osmdroid-android/src/main/java/org/osmdroid/views/overlay/ItemizedOverlayWithFocus.java#L80
If value for `pMarkerFocused` is `null`, then it is obtained via `boundToHotspot()`.
But I can't use this method for my `Drawable`, becouse it is defined as `protected`.
Is this a bug or I should use another way?

https://github.com/osmdroid/osmdroid/blob/e205d7fa2b87dbe6c1cd59a70c602980822606c5/osmdroid-android/src/main/java/org/osmdroid/views/overlay/ItemizedOverlay.java#L347

**Comment by Lexxtor** [comment]
And if I add different markers (`Drawable`) for different items for `ItemizedOverlayWithFocus` I can use `OverlayItem.setMarker()` method https://github.com/osmdroid/osmdroid/blob/master/osmdroid-android/src/main/java/org/osmdroid/views/overlay/OverlayItem.java#L115

But how to set `markerFocused` `Drawable` as in `ItemizedOverlayWithFocus.mMarkerFocusedBase`??

**Comment by Jackcar** [comment]
You need to setMarkerHotspot on the item, like this:
item.setMarkerHotspot(OverlayItem.HotspotPlace.TOP_CENTER);

**Comment by Tupling** [comment]
@Jackcar, however, doing so places the center point of the marker/icon on the geopoint, thus if I have a marker that perhaps like Google Maps with a point on the bottom, this point no longer is placed at the geopoint as desired.

**Comment by spyhunter99** [comment]
i would suggest using the `Marker` class as it provides a lot more drawing options
