### ISSUE TITLE
Cant create external tile source

### ISSUE THREAD

**Issue by jeremycook61** [osmdroid/osmdroid#56]
Can someone tell me how to create a new tile source without using internal resources?
The XYTileSource constructor requires a ResourceProxy.string which are all pre-defined. I can create my own tile source and add it with         TileSourceFactory.addTileSource(tileSource); 
but then I need to use one of the internal to osmdroid resource strings. I need to use my own resource string which is relevant for the new tile source. If this is not possible then the XYTileSource class needs a new constructor with a different signature.

**Comment by spyhunter99** [comment]
It looks like the ResourceProxy strings actually determine what directory downloaded tiles are stored in within /sdcard/osmdroid/tiles. I agree, this should be adjustable for anyone bringing in a custom tile source

**Comment by spyhunter99** [comment]
Correction, resource proxy "string" is not actually used for ITileSources. I just removed the reference to it in master and it will be gone in the next release. What determines the download folder? the "name" that is set for the map provider.

More over, I just added a few examples to both the wiki and the source code for USGS map sources. Fair warning, the example source doesn't use the standard slippy map format ZXY, but rather ZYX. See https://github.com/osmdroid/osmdroid/wiki/How-to-use-the-osmdroid-library#tile-providers-vs-tile-source

To reiterate, the ResourceProxy.string for map source is not used! Just pick one and go for it. Feel free to reopen if there are more questions or open a new ticket.
