### ISSUE TITLE
osmdroid-android Exception

### ISSUE THREAD

**Issue by Reed-Xiong** [osmdroid/osmdroid#562]
Hi guy,I fonud a odd bug and have no idea to deal with with it, so please tell me how to do these .
I used the osmdroid-android with 5.6.3 in my APP,That's ok except when I rotate the screen from landscape toPortrait, the app would be crashed by exception message that "Exception: Receiver not registered: org.osmdroid.tileprovider.modules.MapTileFileStorageProviderBase$MyBroadcastReceiver@448096d0"

Please help me resolve it 

The exception message in details below:
Version: 1.02.170220(2)
Android: 4.4.2(PE-TL00M)
Exception: Receiver not registered: org.osmdroid.tileprovider.modules.MapTileFileStorageProviderBase$MyBroadcastReceiver@448096d0
android.app.LoadedApk.forgetReceiverDispatcher(LoadedApk.java:688)
android.app.ContextImpl.unregisterReceiver(ContextImpl.java:1580)
android.content.ContextWrapper.unregisterReceiver(ContextWrapper.java:489)
org.osmdroid.tileprovider.util.SimpleRegisterReceiver.unregisterReceiver(SimpleRegisterReceiver.java:26)
org.osmdroid.tileprovider.modules.MapTileFileStorageProviderBase.detach(MapTileFileStorageProviderBase.java:51)
org.osmdroid.tileprovider.MapTileProviderArray.detach(MapTileProviderArray.java:76)
com.southgnss.mapsforge.MapsForgeTileProvider.detach(MapsForgeTileProvider.java:69)
org.osmdroid.views.overlay.TilesOverlay.onDetach(TilesOverlay.java:113)
org.osmdroid.views.overlay.DefaultOverlayManager.onDetach(DefaultOverlayManager.java:137)
org.osmdroid.views.MapView.onDetach(MapView.java:856)
org.osmdroid.views.MapView.onDetachedFromWindow(MapView.java:1126)
android.view.View.dispatchDetachedFromWindow(View.java:12642)
android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:2589)
android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:2587)
android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:2587)
android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:2587)
android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:2587)
android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:2587)
android.view.ViewRootImpl.dispatchDetachedFromWindow(ViewRootImpl.java:2958)
android.view.ViewRootImpl.doDie(ViewRootImpl.java:5644)
android.view.ViewRootImpl.die(ViewRootImpl.java:5621)
android.view.WindowManagerGlobal.removeViewLocked(WindowManagerGlobal.java:363)
android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:311)
android.view.WindowManagerImpl.removeViewImmediate(WindowManagerImpl.java:84)
android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3790)
android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:3977)
android.app.ActivityThread.access$1200(ActivityThread.java:139)
android.app.ActivityThread$H.handleMessage(ActivityThread.java:1262)
android.os.Handler.dispatchMessage(Handler.java:102)
android.os.Looper.loop(Looper.java:136)
android.app.ActivityThread.main(ActivityThread.java:5315)
java.lang.reflect.Method.invokeNative(Native Method)
java.lang.reflect.Method.invoke(Method.java:515)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:864)
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:680)
dalvik.system.NativeStart.main(Native Method)

**Comment by spyhunter99** [comment]
do you have any static references to the map? are you programmatically creating the map?

**Comment by Reed-Xiong** [comment]
Yes,I created the Map by WMS and load line-off map

**Comment by spyhunter99** [comment]
if you have code that looks like
`static MapView map` or `MapView map = new MapView(context)` that could be your problem, you have to destroy the map yourself. it's easier to put the mapvew in a layout so android does most of the work for you

**Comment by Reed-Xiong** [comment]
Finally, I debug code and found the error in org.osmdroid.tileprovide.modules . The detach() method as below would executed  and throw exception that mBroadcastReceiver cannot be  unregistered because of it already unregister in other code.

public void detach(){
if(this.mBroadcastReceiver!=null){
     this.RegisterReceiver.unregisterReceiver(this.mBroadcastReceiver)
     this.mBroadcastReceiver=null
    }
}

so i just find all register location in code and remove redundant code
