### ISSUE TITLE
Integrating GeoServer with osmdroid

### ISSUE THREAD

**Issue by waleedb112** [osmdroid/osmdroid#563]
Can any one share an example of how to get layers from geo server and display it on osm? i have been trying different sources but i am not able to achieve success. I have done this kind of work for web applications but this is my first time with android.
Thanks in advance

**Comment by spyhunter99** [comment]
It is possible. I had a working example somewhere on a feature branch. Basically I took the derived url pattern that MOBAC uses to pull data from a WMS server. On the osmdroid side, convert the tile coordinates (Z/X/Y) into the corresponding lat/lon bounding box. Then use those coordinates to ask geoserver/wms server for a tile that at that zoom level and coordinates. One of the problems that you'll run into is projection. OSM/slippy maps are web mercator, geoserver and most wms endpoints push out equalrectangular projections. Geoserver can reproject the imagery but at a close of accuracy. At closer to the ground zoom levels, the distortion isn't too bad but zoomed out is it noticeable. 

I also recall attempting to write an android friendly parser to interpret the WMS get capabilities XML in order to figure out all the layer names and projections that they match up to. Ended up on the back burned with lots of other stuff unfortunately. You're welcome to pick it up.

**Comment by waleedb112** [comment]
Thank you very much for your response. Actually i have managed to get the tiles from geo server to overlay my osm. But the tiles only show on zoom level 6 and they are repeating like shown in the picture below.
![16935471_1537401342945887_1145784052_o](https://cloud.githubusercontent.com/assets/25451395/23207620/bda6fcb8-f913-11e6-97f0-3f295b0d7061.png)

Floowing is my code

        final MapTileProviderBasic tileProvider = new MapTileProviderBasic(this);
        final ITileSource tileSource = new XYTileSource("manhattan:numfloor",0, 18, 456, ".png", new String[]{"http://servername/geoserver/gwc/service/tms/1.0.0"})
        {
  @Override
            public String getTileURLString(MapTile aTile) {
             String hello= getBaseUrl() + "/manhattan:numfloor/"+aTile.getZoomLevel()+"/"+aTile.getX()+"/"+aTile.getY()+".png";
                System.out.println(hello);
                return hello;
            }
        };
        tileProvider.setTileSource(tileSource);
        final TilesOverlay tilesOverlay = new TilesOverlay(tileProvider, this);
        tilesOverlay.setLoadingBackgroundColor(Color.TRANSPARENT);
        map.getOverlays().add(tilesOverlay);
        map.invalidate();

**Comment by spyhunter99** [comment]
not sure, you probably want to check the geoserver log for an error messages. You can also turn on tile debugging or tile download debugging on your app. This will print to logcat the url that the tile downloader is attempting to fetch. Then try putting that in your browser. if it doesn't load, there's nothing osmdroid droid can do to help you (aside from setting a default image for when the file isn't found)

**Comment by zolden** [comment]
@waleedb112  did you find solution? I have same problem ... I am using same geoserver service for OpenLayers application where works fine.  In osmosis I check request url and when I open I in browser it got me this message "Coverage [minx,miny,maxx,maxy] is [1143, 1340, 1150, 1347, 11], index [x,y,z] is [11, 1, 11]" instead tile png.

**Comment by waleedb112** [comment]
@spyhunter99 thank you very much for your help. I have figured it out. My code is running successfully.
@zolden i followed the following and it worked like a charm
https://github.com/OpenHistoricalDataMap/OHDMAndroidEditor/blob/master/app/src/main/java/android/ohdm/de/editor/activities/MainActivity.java
If you still find any trouble in doing so feel free to ask

**Comment by LamraniOthmane** [comment]
i still can't resolve that error: 
I/System.out: http://192.168.1.114:9090/geoserver/gwc/service/tms/1.0.0/tiger:tiger_roads/4/2/0.png

gere is my code : 

`public void getMapFromGeoserver(){
        final MapTileProviderBasic tileProvider = new MapTileProviderBasic(this);
        final ITileSource tileSource = new XYTileSource("tiger:tiger_roads",0, 18, 254, ".png", new String[]{"http://192.168.1.114:9090/geoserver/gwc/service/tms/1.0.0"})
        { @Override
        public String getTileURLString(MapTile aTile) {
            String hello= getBaseUrl() + "/tiger:tiger_roads/"+aTile.getZoomLevel()+"/"+aTile.getX()+"/"+aTile.getY()+".png";
            System.out.println(hello);
            return hello;  }
        };
        tileProvider.setTileSource(tileSource);
        final TilesOverlay tilesOverlay = new TilesOverlay(tileProvider, this);
        tilesOverlay.setLoadingBackgroundColor(Color.TRANSPARENT);
        map.getOverlays().add(tilesOverlay);
        map.invalidate();

        map.getController().setZoom(4);
        map.setBuiltInZoomControls(true);
        map.setMultiTouchControls(true);
    }
`

thank you for answering :D

**Comment by zolden** [comment]
@waleedb112  thanks for answer ... Here I described my problem: [http://stackoverflow.com/questions/42596691/display-map-from-geoserver-in-osmdroid](url) Do you have idea what I did wrong?

**Comment by LamraniOthmane** [comment]
@waleedb112 i will tell you the solution if i find it for sure.

**Comment by spyhunter99** [comment]
let me look through my archives for the wms example i had. it wasn't perfect but it worked

**Comment by LamraniOthmane** [comment]
Thank you a lot.

**Comment by spyhunter99** [comment]
````

public class WMSTileProvider extends OnlineTileSourceBase{


    // Web Mercator n/w corner of the map.
    private static final double[] TILE_ORIGIN = {-20037508.34789244, 20037508.34789244};
    //array indexes for that data
    private static final int ORIG_X = 0;
    private static final int ORIG_Y = 1; // "

    // Size of square world map in meters, using WebMerc projection.
    private static final double MAP_SIZE = 20037508.34789244 * 2;

    // array indexes for array to hold bounding boxes.
    protected static final int MINX = 0;
    protected static final int MAXX = 1;
    protected static final int MINY = 2;
    protected static final int MAXY = 3;
    private String layer="";

    /**
     * Constructor
     *
     * @param aName                a human-friendly name for this tile source
     * @param aBaseUrl             the base url(s) of the tile server used when constructing the url to download the tiles http://sedac.ciesin.columbia.edu/geoserver/wms
     */
    public WMSTileProvider(String aName, String[] aBaseUrl, String layername) {
        super(aName, 0, 22, 256, "png", aBaseUrl);
    }


    final String WMS_FORMAT_STRING =
            "http://%s" +
                    "?service=WMS" +
                    "&version=1.1.1" +
                    "&request=GetMap" +
                    "&layers=%s" +
                    "&bbox=%f,%f,%f,%f" +
                    "&width=256" +
                    "&height=256" +
                    "&srs=EPSG:900913" +
                    "&format=image/png" +
                    "&transparent=true";


    // Return a web Mercator bounding box given tile x/y indexes and a zoom
    // level.
    protected double[] getBoundingBox(int x, int y, int zoom) {
        double tileSize = MAP_SIZE / Math.pow(2, zoom);
        double minx = TILE_ORIGIN[ORIG_X] + x * tileSize;
        double maxx = TILE_ORIGIN[ORIG_X] + (x+1) * tileSize;
        double miny = TILE_ORIGIN[ORIG_Y] - (y+1) * tileSize;
        double maxy = TILE_ORIGIN[ORIG_Y] - y * tileSize;

        double[] bbox = new double[4];
        bbox[MINX] = minx;
        bbox[MINY] = miny;
        bbox[MAXX] = maxx;
        bbox[MAXY] = maxy;

        return bbox;
    }

    @Override
    public String getTileURLString(MapTile aTile) {
        double[] bbox = getBoundingBox(aTile.getX(), aTile.getY(), aTile.getZoomLevel());
        String s = String.format(Locale.US, WMS_FORMAT_STRING, getBaseUrl(), layer, bbox[MINX],
                bbox[MINY], bbox[MAXX], bbox[MAXY]);
        Log.d("WMSDEMO", s);
        return s;
    }
}
````

**Comment by spyhunter99** [comment]
give that a shot

**Comment by LamraniOthmane** [comment]
thank you @spyhunter99, i still can't get it correctly it's showing me many tiles, exactly the same.
i think that im gonna look for google maps, because with Osmdroid they have lack of documentation.

**Comment by zolden** [comment]
@spyhunter99 thanks, you save my life :) ! I have another question, I will be very thankful for any advice. I have service which provide GeoJSON of route which I need draw into map. Can you give me some hint? Thanks

**Comment by spyhunter99** [comment]
Osms bonus pack has that

**Comment by zolden** [comment]
@spyhunter99 Zes, zou have right and I'll tried it, but it could not parse my GeoJSON. I describe error here: http://stackoverflow.com/questions/42695096/draw-route-on-osmdroid-map-with-osmbonuspack-library with example of code.

**Comment by schwantner92** [comment]
@spyhunter99  thanks for sharing your code, it works. Can you help me to understand what this code do, and what is theory of calculating of bbox, or give me some hint for materials where I read more about it?

**Comment by spyhunter99** [comment]
open street maps and may others use the web mercator project (the world is square, 256x256 pixels) with the slippy map tile coordinate system. (zoom/x/y.png). The code converts from user needed osm zoom/x/y tile coordinate to the bounding box in latitude/longitude coordinates for that specific tile, which it sends to geoserver in the request. Geoserver as well as many WMS based servers use a different coordinate system for referencing the map (not lat lon). I'm not entirely sure what it's called but it's used by a lot of things, such as Open Layer (javascript)

Power on zoom is just part of the algorithm to convert xyz to lat lon. More info here
https://github.com/osmdroid/osmdroid/wiki/Map-Sources and
http://wiki.openstreetmap.org/wiki/Slippy_map_tilenames 

I've only been able to get geoserver to produce tiles in equirectangular  projection, which means the world is 256hx512w. This causes a lot of distortion when zoomed out (osm zoom 0-3 or so) it tends to get more accurate the closer to the ground you get. It's just something to be aware of.

**Comment by spyhunter99** [comment]
To add, I'd love to put this in osmdroid but it's not feature complete. We need someone to write a tool that can xml parse the WMS get capabilities results, pull out all of the usable layers and their zoom levels. Then either provide the list to the user for manual selection or perhaps auto level based on zoom level. For a user, It's a non trivial task to pull all the necessary bits to produce the correct url pattern and the WMS get capabilities should provide enough info to automate this

**Comment by LamraniOthmane** [comment]
@spyhunter99, I'm very thankful for your help, i was disappointed to use Osmdroid, and migrated to Googlemaps, finally i realized that google maps doesn't provide much features, so i created a new project following your code and this time it works, thank you a lot.

**Comment by spyhunter99** [comment]
glad it works for you. this is all volunteer driven, there's no corporate support here, contributions are always welcome

**Comment by spyhunter99** [comment]
#177 related ticket, closing this for now

**Comment by spyhunter99** [comment]
@LamraniOthmane i've made a bit of progress with geoserver support and i was able to get everything working fairly well on the #177 branch. i'm still working on ironing out the particulars with NASA's WMS endpoints, all of which will not give me a tile for explicit bounds.
