### ISSUE TITLE
Unable to build OpenStreetMapViewer in AndroidStudio 2.1

### ISSUE THREAD

**Issue by mkey2000** [osmdroid/osmdroid#566]
Hi there,

I was unable to build OpenStreetMapViewer in AndroidStudio 2.1.
**Error Message:**
Error:Cause: failed to find target with hash string 'Google Inc.:Google APIs:23' in: home/martin/Android/Sdk
<a href="openAndroidSdkManager">Open Android SDK Manager</a>

**How to Fix**
replace 
`./osmdroid-third-party/build.gradle:5:    compileSdkVersion "Google Inc.:Google APIs:23"`
`./GoogleWrapperSample/build.gradle:7:    compileSdkVersion 'Google Inc.:Google APIs:23'`
by `compileSdkVersion 23`

**Comment by spyhunter99** [comment]
that means you need to install the google api set for 23. Your fix shouldn't work or may not work on device

**Comment by spyhunter99** [comment]
thanks for the report though i'm sure someone will find it helpful in the future
