### ISSUE TITLE
Map tile disappearing after scrolling recyclerview

### ISSUE THREAD

**Issue by chanisrunnin** [osmdroid/osmdroid#568]
Hello, Nice to meet you, This is chan.
i got a problem when using osm android,

i programmed some list view page by using recyclerview.
and each every row in recyclerview, has MapView.

At first time, when i loaded all list, each row had a perfect map and working nicely,
but when i scrolled dow the list and first row had disappeared, and i scrolled again to the top and came back to first row, then the MapView's tiles were gone.
also marker had still alive but only tile(i think) were gone.. i could see only gray background and some black lines.

when i scroll, 
i do noting special....

i attatched some codes ans some logs.

_@Override
        public void onViewAttachedToWindow(RecyclerView.ViewHolder holder) {
          .....
          ......
         calling below method
         bindMap(vo, position)
          ....
}
private void bindMap(ManifestDetailVo vo, int position){
                    ...............
                    mvAddr.setTileSource(TileSourceFactory.MAPNIK);
                    mvAddr.setBuiltInZoomControls(false);
                    mvAddr.setMultiTouchControls(true);
                    //mvAddr.getController().setZoom("blablabla");
                    //mvAddr.getController().setCenter(new GeoPoint(vo.getLat(), vo.getLon()));
                    GeoPoint geoPoint = new GeoPoint(vo.getLat(), vo.getLon()); 
                    Drawable marker = getResources().getDrawable(R.drawable.marker_default);
                   List<OverlayItem> olList = new ArrayList<>();
                    olList.add(new OverlayItem(vo.getStopNodeNm(), vo.getStopNodeCd(), geoPoint));
                    ItemizedIconOverlay<OverlayItem> iio = new ItemizedIconOverlay<>(olList, marker, null, getActivity());
                    mvAddr.getOverlays().add(iio);
                    .................
                }_

This is logs,
and i bolded some spicious logs.
is this caused by cannot find caching map tile because GC or external storage someting?

D/StorageUtils: /proc/mounts
D/StorageUtils: rootfs / rootfs ro,relatime 0 0
D/StorageUtils: tmpfs /dev tmpfs rw,seclabel,nosuid,relatime,mode=755 0 0
D/StorageUtils: devpts /dev/pts devpts rw,seclabel,relatime,mode=600 0 0
D/StorageUtils: none /dev/cpuctl cgroup rw,relatime,cpu 0 0
D/StorageUtils: proc /proc proc rw,relatime 0 0
D/StorageUtils: sysfs /sys sysfs rw,seclabel,relatime 0 0
D/StorageUtils: selinuxfs /sys/fs/selinux selinuxfs rw,relatime 0 0
D/StorageUtils: /sys/kernel/debug /sys/kernel/debug debugfs rw,relatime 0 0
D/StorageUtils: none /acct cgroup rw,relatime,cpuacct 0 0
D/StorageUtils: tmpfs /mnt/secure tmpfs rw,seclabel,relatime,mode=700 0 0
D/StorageUtils: tmpfs /mnt/secure/asec tmpfs rw,seclabel,relatime,mode=700 0 0
D/StorageUtils: tmpfs /mnt/asec tmpfs rw,seclabel,relatime,mode=755,gid=1000 0 0
D/StorageUtils: tmpfs /mnt/obb tmpfs rw,seclabel,relatime,mode=755,gid=1000 0 0
D/StorageUtils: /dev/block/mmcblk0p9 /system ext4 ro,seclabel,nosuid,nodev,relatime,user_xattr,barrier=1,data=ordered 0 0
D/StorageUtils: /dev/block/mmcblk0p3 /efs ext4 rw,seclabel,nosuid,nodev,noatime,user_xattr,barrier=1,journal_async_commit,data=ordered,noauto_da_alloc,discard 0 0
D/StorageUtils: /dev/block/mmcblk0p8 /cache ext4 rw,seclabel,nosuid,nodev,noatime,user_xattr,barrier=1,journal_async_commit,data=ordered,noauto_da_alloc,discard 0 0
D/StorageUtils: /dev/block/mmcblk0p10 /preload ext4 ro,seclabel,nosuid,nodev,noatime,user_xattr,barrier=1,data=ordered 0 0
D/StorageUtils: /dev/block/mmcblk0p12 /data ext4 rw,seclabel,nosuid,nodev,noatime,user_xattr,barrier=1,journal_async_commit,data=ordered,noauto_da_alloc,discard 0 0
D/StorageUtils: /data/knox/sdcard /mnt/shell/knox-emulated sdcardfs rw,nosuid,nodev,relatime,uid=1000,gid=1000,derive=none 0 0
D/StorageUtils: /data/media /mnt/shell/emulated sdcardfs rw,nosuid,nodev,relatime,uid=1023,gid=1023,derive=legacy,reserved=20MB 0 0
D/StorageUtils: tmpfs /storage/emulated tmpfs rw,seclabel,nosuid,nodev,relatime,mode=751,gid=1028 0 0
D/StorageUtils: /data/media /storage/emulated/0 sdcardfs rw,nosuid,nodev,relatime,uid=1023,gid=1023,derive=legacy,reserved=20MB 0 0
D/StorageUtils: /data/media /storage/emulated/legacy sdcardfs rw,nosuid,nodev,relatime,uid=1023,gid=1023,derive=legacy,reserved=20MB 0 0
I/StorageUtils: /storage/emulated/legacy is writable
**I/StorageUtils: /storage/extSdCard is NOT writable**
I/StorageUtils: /storage/emulated/0 is writable
I/StorageUtils: /mnt/sdcard is writable
I/StorageUtils: /storage/emulated/0 is writable
I/StorageUtils: /mnt/sdcard is writable
I/StorageUtils: /storage/emulated/legacy is writable
I/OsmDroid: Using tile source: Mapnik
I/OsmDroid: sdcard state: mounted
I/OsmDroid: sdcard state: mounted
I/OsmDroid: sdcard state: mounted
D/com.cello.mobile.bpo.tms.exe.ManifestDetailPageFragment: onViewAttachedToWindow: IN ======================
D/com.cello.mobile.bpo.tms.exe.ManifestDetailPageFragment: bindMap: IN
D/com.cello.mobile.bpo.tms.exe.ManifestDetailPageFragment: bindMap: position:0
I/OsmDroid: Using tile source: Mapnik
I/OsmDroid: sdcard state: mounted
I/OsmDroid: sdcard state: mounted
I/OsmDroid: sdcard state: mounted
**D/dalvikvm: GC_FOR_ALLOC freed 4895K, 26% free 16772K/22424K, paused 23ms, total 23ms**
D/com.cello.mobile.bpo.tms.exe.ManifestDetailPageFragment: onViewAttachedToWindow: IN ======================
D/com.cello.mobile.bpo.tms.exe.ManifestDetailPageFragment: bindMap: IN
D/com.cello.mobile.bpo.tms.exe.ManifestDetailPageFragment: bindMap: position:1
I/dalvikvm: Could not find method android.content.res.Resources.getColor, referenced from method com.sds.opus.util.ColorUtil.getColor
W/dalvikvm: VFY: unable to resolve virtual method 542: Landroid/content/res/Resources;.getColor (ILandroid/content/res/Resources$Theme;)I
D/dalvikvm: VFY: replacing opcode 0x6e at 0x000a
I/OsmDroid: Tile cache increased from 9 to 12
D/dalvikvm: GC_FOR_ALLOC freed 387K, 15% free 19156K/22424K, paused 22ms, total 22ms
D/dalvikvm: GC_FOR_ALLOC freed 113K, 11% free 20431K/22944K, paused 20ms, total 20ms
I/OsmDroid: Tile cache increased from 9 to 15
I/OsmDroid: Using tile source: Mapnik
I/OsmDroid: sdcard state: mounted
I/OsmDroid: sdcard state: mounted
I/OsmDroid: sdcard state: mounted
D/com.cello.mobile.bpo.tms.exe.ManifestDetailPageFragment: onViewAttachedToWindow: IN ======================
D/com.cello.mobile.bpo.tms.exe.ManifestDetailPageFragment: bindMap: IN
D/com.cello.mobile.bpo.tms.exe.ManifestDetailPageFragment: bindMap: position:2
I/OsmDroid: Tile cache increased from 9 to 15
D/dalvikvm: GC_FOR_ALLOC freed 558K, 9% free 27371K/29804K, paused 25ms, total 25ms
**I/OsmDroid: Database detached
I/OsmDroid: Database detached**
D/com.cello.mobile.bpo.tms.exe.ManifestDetailPageFragment: onViewAttachedToWindow: IN ======================
D/com.cello.mobile.bpo.tms.exe.ManifestDetailPageFragment: bindMap: IN
D/com.cello.mobile.bpo.tms.exe.ManifestDetailPageFragment: bindMap: position:0
**I/OsmDroid: Database detached
I/OsmDroid: Database detached**

**Comment by sadevelopment** [comment]
I have exactly the same issue and have been looking for a fix for the past 2 weeks now

**Comment by spyhunter99** [comment]
When the map is detached, it self destroys, however it looks like recycler
view is retaining the instance of the map. Try replacing it when a new
instance

**Comment by sadevelopment** [comment]
Sorted thanks.

**Comment by chanisrunnin** [comment]
Thanks for your reply :)
but i cannot understand fully.. 
when the map is detached and destroyed itself, is there any way to retain the exact same state of map before? 
do i have to always replace with a new one?

**Comment by spyhunter99** [comment]
everything in android has a lifecycle. Once the map is done, it releases all resources (background threads, databases, callbacks, etc) Recycler view is very strange. I'm not entire sure what the use case is for a map in a recycler view but i believe there are some examples of doing exactly that

**Comment by wojder** [comment]
Hi, issue is annoying and I hope that will be fixed in the next release... We r facing this bug and looking forward 4 solution. Unfortunetely still without any clue how to solve it

**Comment by sadevelopment** [comment]
I ended up removing the code that destroyed the map, repackaging it up locally and using that ... it suits my project as there was no other way around this.

**Comment by chanisrunnin** [comment]
i done my issue by working around too,
i added map's center and zoom value into each row's vo whenever user moves or touches mapview.
After scrolling recyclerview, when row attatched to window again, i load again along with the saved value.
By doing that, it looks like each row mapview is not detached and remember its state.

**Comment by spyhunter99** [comment]
#588
