### ISSUE TITLE
Panning slow on rotated map

### ISSUE THREAD

**Issue by gruelfin** [osmdroid/osmdroid#569]
When a map is rotated, panning is really slow. It seems as if rotating is a cpu-intensive task. Does someone know a way how the performance of a rotated map could be improved?

**Comment by spyhunter99** [comment]
basically the mapview calls canvas.rotate to handle map rotation. You could try turning on hardware acceleration as it may help but that also causes other issues with polyline

**Comment by monsieurtanuki** [comment]
@gruelfin Canvas performances are supposed to be improved by #800 (no canvas scaling anymore). Could you give it a try?

**Comment by spyhunter99** [comment]
going to make this as fixed in v6, panning seems pretty quick now
