### ISSUE TITLE
More Request Properties for Online Sources

### ISSUE THREAD

**Issue by krabo0om** [osmdroid/osmdroid#570]
The `Configuration` class only allows to set the user agent for `HttpURLConnection`s. However, I need to enable cross domain tile downloads, so I need to set the `origin` property in the request for the tile. This is not possible right now.
I propose to use a `Map` where the user can store their key-value pairs for requests made by the `CacheManger` (and maybe also in other classes?). One default value would be the user agent.

**Comment by spyhunter99** [comment]
Good idea, feel free to open a pull request if you come up with a solution

**Comment by krabo0om** [comment]
I'll look into it, but not before April. So if anyone wants to implement the feature before than, they are welcome to.

**Comment by spyhunter99** [comment]
thanks!
