### ISSUE TITLE
Error:Cannot get property 'pom' on extra properties extension as it does not exist

### ISSUE THREAD

**Issue by AsranCJ** [osmdroid/osmdroid#571]
I am still getting this error "Error:Cannot get property 'pom' on extra properties extension as it does not exist"
I have changed my "settings.gradle" so it does -> include ':osmdroid-android'
I have change my "build.gradle" so it does -> compile project(':osmdroid-android')

And currently I want the project to be as a module in my Android Studio.
Not compiled as an aar or jar

What am I missing here =(
Hope someone can help me.

**Comment by spyhunter99** [comment]
This is an artifact of gradle fury,  unfortunately you'll either have to apply the minimal from fury to your parent  project or alter the build file for your clone of osmdroid .

The other option is git sub module

**Comment by AsranCJ** [comment]
Thx I removed in the build.gradle from osmdroid-android the line 
"apply from: "https://raw.githubusercontent.com/gradle-fury/gradle-fury/v1.1.3/gradle/android-support.gradle""

And added my compileSdkVersion and buildToolsVersion to the file. Now it is included as an module.

Thank you very much!
