### ISSUE TITLE
mapsforge+osmdroid tiles not changing

### ISSUE THREAD

**Issue by Axrorxoja** [osmdroid/osmdroid#572]
Hi, I'm using the Map Forge + osmdroid, when I initialize osm map after set mapsforgeTileProvider instance   can't change osm tiles, I don't understand why

**Comment by spyhunter99** [comment]
You're going to have to provide more information or sample code to reproduce

**Comment by Axrorxoja** [comment]
`public class MainActivity extends AppCompatActivity
    {
        MapView map;
        MapsForgeTileProvider provider;
        MapsForgeTileSource source;
        MapTileProviderBasic providerForMapnik;
        MapTileProviderBasic providerForTashkentOsm;

        @Override
        protected void onCreate(Bundle savedInstanceState)
            {
                super.onCreate(savedInstanceState);
                setContentView(R.layout.activity_main);
                Toolbar toolbar = (Toolbar) findViewById(R.id.toolbar);
                setSupportActionBar(toolbar);

                map = (MapView) findViewById(R.id.map);
                map.setBuiltInZoomControls(true);
                map.setTileSource(TileSourceFactory.MAPNIK);
                IMapController controller = map.getController();
                GeoPoint point = new GeoPoint(41.2585, 69.2097);
                controller.animateTo(point);
                controller.setZoom(10);
                ITileSource source = new XYTileSource("tashkentOSM", 1, 17, 256, ".png", new String[]{});
                providerForMapnik = new MapTileProviderBasic(getApplicationContext(), TileSourceFactory.MAPNIK, new SqlTileWriter());
                providerForTashkentOsm = new MapTileProviderBasic(getApplicationContext(), source, new SqlTileWriter());

            }

        private void setUpMapsForge() throws Exception
            {
                MapsForgeTileSource.createInstance(getApplication());
                File file = new File(Environment.getExternalStorageDirectory().getPath() + "/osmdroid/uzbekistan.map");
                source = MapsForgeTileSource.createFromFiles(new File[]{file});
                IRegisterReceiver receiver = new SimpleRegisterReceiver(getApplicationContext());
                IFilesystemCache cache = new SqliteArchiveTileWriter(Environment.getExternalStorageDirectory().getPath() + "/osmdroid/my.db");
                provider = new MapsForgeTileProvider(receiver, source, cache);
            }

        public void onClickMapsForge(View view) throws Exception
            {
                if (provider==null)
                setUpMapsForge();
                map.setTileProvider(provider);
//                map.setTileSource(source);
            }

        public void onClickMapnik(View view)
            {
                map.setTileProvider(providerForMapnik);
//                map.setTileSource(TileSourceFactory.MAPNIK);
            }

        public void onClickTashkentOSM(View view)
            {
                map.setTileProvider(providerForTashkentOsm);
            }
    }
`

**Comment by spyhunter99** [comment]
a few comments to start, any reason you're not using the osmdroid provided adapter for forge?

There's an example here: https://github.com/osmdroid/osmdroid/blob/master/OpenStreetMapViewer/src/main/java/org/osmdroid/samplefragments/tileproviders/MapsforgeTileProviderSample.java

**Comment by Axrorxoja** [comment]
Thank you I'm fix my bug
