### ISSUE TITLE
OpenCycleMap now requires API key

### ISSUE THREAD

**Issue by shiroyagi** [osmdroid/osmdroid#573]
Tiles are now overlayed with "API Key required".
http://www.thunderforest.com/docs/apikeys/

When you sign up you get access to all 9 maps:
http://www.thunderforest.com/maps/

**Comment by spyhunter99** [comment]
fun times

**Comment by shiroyagi** [comment]
Any thoughts on how you'd like this implemented?  A ThunderforestTileSource that adds CYCLEMAP by default, and makes the other 8 optionally available?  Or have you started looking at it already?

**Comment by spyhunter99** [comment]
There's a number of examples that exist on accessing a map source with an api key already. Bing is one of them, CloudMade, Here we go.

**Comment by shiroyagi** [comment]
Basic implemenation here faf13f0:
`TileSourceFactory.addTileSource(new ThunderforestTileSource(getActivity(),ThunderforestTileSource.CYCLE));`

**Comment by spyhunter99** [comment]
merged
