### ISSUE TITLE
Geofencing

### ISSUE THREAD

**Issue by hamzux** [osmdroid/osmdroid#575]
Hello, 

Is there any equivalent to PolyUtil.isLocationOnPath of http://googlemaps.github.io/android-maps-utils/ in OSMdroid?

Thanks

**Comment by MKergall** [comment]
You have Polyline.isCloseTo(GeoPoint point, double tolerance, MapView mapView)
With one issue: it has been built for event detection, so it operates in screen coords, and tolerance is in pixels.

**Comment by spyhunter99** [comment]
looks like your linked stuff is ASF licensed, if so, it can be ported into osmdroid. but i'm a bit short on time these days, so if you get a solution, please open a pr.
