### ISSUE TITLE
Resize Tiles at runtime for unavailable zoomlevels

### ISSUE THREAD

**Issue by lurtzn** [osmdroid/osmdroid#579]
Hi,
im using the map with zoom levels up to 21. The problem is that raster data doesn't get drawn at high zoom levels.
```
        XYTileSource mapnik = new XYTileSource(getName(),
                0, 19, 256, ".png", new String[]{
                "http://a.tile.openstreetmap.org/",
                "http://b.tile.openstreetmap.org/",
                "http://c.tile.openstreetmap.org/"}, copyright);
```
This tile source gets drawn up to zoom level 19. It will still be drawn at higher zoomlevel if i just zoom in. But if move to the side or restart the mapview, the tiles won't be drawn. Is there a way to fix that?

At the moment im only using mapnik or mbtiles.
```
 XYTileSource mbTilesSource = new XYTileSource(name, 1, 20, 256, ".png", new String[]{}, copyrightLabel);
SimpleRegisterReceiver simpleReceiver = new SimpleRegisterReceiver(map.getContext());
IArchiveFile[] files = new IArchiveFile[mbTileFiles.length];
int i = 0;
for (File mbTileFile : mbTileFiles)
   files[i++] = MBTilesFileArchive.getDatabaseFileArchive(mbTileFile);
MapTileModuleProviderBase moduleProvider = new MapTileFileArchiveProvider(simpleReceiver, mbTilesSource, files);
MapTileProviderArray mProvider = new MapTileProviderArray(mbTilesSource, null, new MapTileModuleProviderBase[]{moduleProvider});
map.setTileProvider(mProvider);
map.setBackgroundColor(Color.WHITE);
map.setTileSource(mbTilesSource);
map.postInvalidate();
```

I know that i probably need to rewrite some of the MapTileProvider classes. Any idea where to start?

**Comment by spyhunter99** [comment]
It would probably be one of the map tile provider classes. You'd have to recursively zoom out until a tile is found, then scale and crop that image to the appropriate size. What you see now is an artifact of the Zoom Animator found in MapView. I know its possible to do so but i haven't had time to look into it. My best guess would to be extend one of the classed located here
https://github.com/osmdroid/osmdroid/tree/master/osmdroid-android/src/main/java/org/osmdroid/tileprovider/modules

**Comment by lurtzn** [comment]
ok, thank you.
