### ISSUE TITLE
How can I remove the zoom button ?

### ISSUE THREAD

**Issue by niray** [osmdroid/osmdroid#580]
I want to use the custom button to instance of the default button, but I don't know how to remove the default zoom in and zoom out button in the view .I need help :)

**Comment by spyhunter99** [comment]
MapView.setUseBuiltInZoomControls(false)

**Comment by niray** [comment]
Ok,thank you.

**Comment by DigitalSamuraiDTM** [comment]
If "setUseBuiltInZoomControls" was deprecated in your version osm, then try 
"mapView.getZoomController().setVisibility(CustomZoomButtonsController.Visibility.NEVER)"
It is help me to remove zoom buttons)
