### ISSUE TITLE
BoundingBox: add clone and concat methods

### ISSUE THREAD

**Issue by MKergall** [osmdroid/osmdroid#581]

**Comment by MKergall** [comment]
Developed. I'm now trying to create the PR.

**Comment by spyhunter99** [comment]
@MKergall try this https://github.com/osmdroid/osmdroid/invitations

**Comment by MKergall** [comment]
Thanks. 
Well... it look like I pushed my commits directly on master... Sorry. 

One commit is good: "BoundingBox: adding clone and concat methods."

The other one is not: "Merge remote-tracking branch 'origin/master'"
If you want and can cancel it... I prefer not to add mistakes on mistakes.

**Comment by spyhunter99** [comment]
it's not on master, looks fine so far.

**Comment by spyhunter99** [comment]
merged
