### ISSUE TITLE
map doesn't appear on tablet Lenovo TAB2 A10-30

### ISSUE THREAD

**Issue by Raptorel** [osmdroid/osmdroid#582]
Hello,

I have created an application that uses OSMDroid in Android and it works just fine. That is, on a Huawei and Samsung tablet.

However, on a Lenovo TAB2 A10-30, the map simply doesn't appear. Instead, you get those pinkish-brown squares that appear when the map can't load or it doesn't have internet connection or something like that. The map overlays appear and they even move (the application monitors vehicles) on the square-filled screen.

Do you have any idea about what might be going wrong here? Again, the maps works perfectly fine on other tablets.

**Comment by spyhunter99** [comment]
Can you checked runtime permissions yet? Is there writable store on the device?

**Comment by Raptorel** [comment]
I have installed an SD card on it, still doesn't work. The difference is that when I installed my application on this device, it didn't ask for ANY permissions, which is weird. On the other devices, it did ask for permissions.

Any ideas?

**Comment by spyhunter99** [comment]
Check the API level of the device for permissions, if it's under API23 it wouldn't ask for permissions and permissions should be granted at install time. Most likely cause is either not having write permissions to any location. What version of osmdroid is it? Can you install the sample app "Open Map" in the play store and test with it?

**Comment by Raptorel** [comment]
I did install it and it works. My application still doesn't.

Here's how my AndroidManifest.xml file looks like:

<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.company.application">

    <application
        android:allowBackup="true"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:supportsRtl="true"
        android:theme="@style/AppTheme">
        <activity android:name=".view.MainActivity"
            android:noHistory="true">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />

                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
        <activity
            android:name=".view.TabbedActivity"
            android:label="@string/app_name"
            android:theme="@style/AppTheme.NoActionBar"
            android:screenOrientation="landscape"
            android:configChanges="keyboardHidden|orientation|screenSize"
            android:noHistory="true">

        </activity>
    </application>

    
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />
    <uses-permission android:name="android.permission.INTERNET" />

    
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />

</manifest>

**Comment by Raptorel** [comment]
I solved it. I have upgraded the tablet to Android 6 (API 23) and I needed to implement the checkPermissions() method that you had in your application in order to make it work. 

The other tablets had earlier Android versions so they requested the permissions when I installed the app. With this API 23 tablet, I had to add this:

// START PERMISSION CHECK
    final private int REQUEST_CODE_ASK_MULTIPLE_PERMISSIONS = 124;

@Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        // Request permissions to support Android Marshmallow and above devices
        if (Build.VERSION.SDK_INT >= 23) {
            checkPermissions();
        }
    }

   private void checkPermissions() {
        List<String> permissions = new ArrayList<>();
        String message = "osmdroid permissions:";
        if (ContextCompat.checkSelfPermission(this, Manifest.permission.ACCESS_FINE_LOCATION) != PackageManager.PERMISSION_GRANTED) {
            permissions.add(Manifest.permission.ACCESS_FINE_LOCATION);
            message += "\nLocation to show user location.";
        }
        if (ContextCompat.checkSelfPermission(this, Manifest.permission.WRITE_EXTERNAL_STORAGE) != PackageManager.PERMISSION_GRANTED) {
            permissions.add(Manifest.permission.WRITE_EXTERNAL_STORAGE);
            message += "\nStorage access to store map tiles.";
        }
        if (!permissions.isEmpty()) {
            Toast.makeText(this, message, Toast.LENGTH_LONG).show();
            String[] params = permissions.toArray(new String[permissions.size()]);
            requestPermissions(params, REQUEST_CODE_ASK_MULTIPLE_PERMISSIONS);
        } // else: We already have permissions, so handle as normal
    }

Now it works. Thanks!
