### ISSUE TITLE
Is there any way to draw path in real time

### ISSUE THREAD

**Issue by Artemprodigy** [osmdroid/osmdroid#583]
Friends tell me how to draw the route in real-time coordinates.

**Comment by spyhunter99** [comment]
Yes see the sample app

**Comment by Artemprodigy** [comment]
I looked at all the examples of OpenStreetMapViewer and did not find such a trail in real time. Tell me which painting object is suitable for rendering a track?

**Comment by MKergall** [comment]
Polyline should be fine for a track.

**Comment by spyhunter99** [comment]
The example i was referring to was More Samples > Drawing > Draw a polyline

Is that what you mean? or plot your current location on device? or ploy everywhere you've been?

**Comment by Artemprodigy** [comment]
I want to draw my current location from device and see the line on the map in real time.

**Comment by spyhunter99** [comment]
your current location is a point. See MyNewLocationOverlay.

What do you want the line to represent?

**Comment by spyhunter99** [comment]
if you know the points of the line, use polyline. If you don't, use osmbonuspack and one of the online routing services to get you turn by turn directions between to points. Lots of examples there

**Comment by Artemprodigy** [comment]
I want to see my route on the map. During the movement I want to add new points to my track. Unfortunately, I can not add new points to Polyline.

**Comment by Artemprodigy** [comment]
MyNewLocationOverlay is a good example, I also want to see the entire traversed route in the form of a line

**Comment by MKergall** [comment]
This is implemented in [OSMNavigator](https://github.com/MKergall/osmbonuspack/blob/master/OSMNavigator/src/main/java/com/osmnavigator/MapActivity.java), using DirectedLocationOverlay to show current position, and a Polyline to show the track. 

You can look at recordCurrentLocationInTrack method.

**Comment by Artemprodigy** [comment]
This example shows what I need to do. But this example does not use a Polyline, it uses a FolderOverlay. For each new coordinate is deleted the current track, then a new one is created and added. I do not think that this is the right way.

What about the PathOverlay? This worked well in the old version OSM. You could not return it to the new version?

**Comment by MKergall** [comment]
A FolderOverlay draws nothing, it just contains other overlays. 
Yes, this example uses a Polyline to draw the track. 
Yes, adding a point in a Polyline impose to set all points again. This conforms to the Google Maps API (no addPoint method, only setPoints). 
The PathOverlay is still there in osmdroid, but deprecated, as it's replaced by Polyline.

**Comment by spyhunter99** [comment]
@Artemprodigy are we good with this issue now? Still have an issue?

**Comment by Artemprodigy** [comment]
I solved the problem of rendering the track in real time in this way:

var pointsall = overlays[overlays.Count - 1].Points;
pointsall.Add(newp);
overlays[overlays.Count - 1].Points = pointsall;

With the addition of a new point every second the track is displayed normally.

Can you implement the AddPoint method in Polylines as it was implemented in PathOverlay?

**Comment by feleke** [comment]
how to get current location of app

**Comment by fariz-siracli** [comment]
Hello. Isn't it possible to draw dashed line or polyline on mapview?

**Comment by monsieurtanuki** [comment]
@fariz-siracli Yes it's possible to draw polylines, using `Polyline`.
Regarding dashed line, change its `Paint` attributes with `getPaint`.
That's the last time I answer your questions on an unrelated (and closed) issue.

**Comment by fariz-siracli** [comment]
Ooh,  i'm sorry. I didn't know that i'm not supposed to ask questions here...

**Comment by monsieurtanuki** [comment]
I have good news: you can create your own issues. If you append your comments to closed or unrelated issues, only few people can see them and help you.

**Comment by fariz-siracli** [comment]
Ok. I will do in that way. Sorry for inconvenience..
