### ISSUE TITLE
Third party isn't working

### ISSUE THREAD

**Issue by altairzuzu** [osmdroid/osmdroid#584]
Cannot create IMap object because MapFactory uses old deprecated getMap(). getMapAsync needs to be used. Is third party project supported now?

**Comment by spyhunter99** [comment]
It hasn't seen love in a long time. Feel free to open a pr. I wasn't aware that anyone was using it. Personally I was hoping to phase it out, but I'm not sure what @neilboyd or @kurtzmarc positions are on the topic.

**Comment by spyhunter99** [comment]
the 3rd party stuff was written for google maps v1 and v2 apis. I have no idea what they are using these days. No one has maintained that capability. If you want to step up and help out, great. open a pr and we'll get it merged. I think you're the only one that has even asked the question about it in several years so i think the demand is probably low.

**Comment by spyhunter99** [comment]
3rd party library was deleted, no longer supported.
