### ISSUE TITLE
crash showing compass

### ISSUE THREAD

**Issue by shiroyagi** [osmdroid/osmdroid#585]
Using the compass option created from MapView.getOverlayManager().onCreateOptionsMenu() I get the following crash:
```
04-14 12:10:10.436 E/AndroidRuntime( 2251): java.lang.RuntimeException: You must pass an IOrientationProvider to setOrientationProvider()
04-14 12:10:10.436 E/AndroidRuntime( 2251): 	at org.osmdroid.views.overlay.compass.CompassOverlay.setOrientationProvider(CompassOverlay.java:139)
04-14 12:10:10.436 E/AndroidRuntime( 2251): 	at org.osmdroid.views.overlay.compass.CompassOverlay.enableCompass(CompassOverlay.java:250)
04-14 12:10:10.436 E/AndroidRuntime( 2251): 	at org.osmdroid.views.overlay.compass.CompassOverlay.enableCompass(CompassOverlay.java:271)
04-14 12:10:10.436 E/AndroidRuntime( 2251): 	at org.osmdroid.views.overlay.compass.CompassOverlay.onOptionsItemSelected(CompassOverlay.java:230)
04-14 12:10:10.436 E/AndroidRuntime( 2251): 	at org.osmdroid.views.overlay.DefaultOverlayManager.onOptionsItemSelected(DefaultOverlayManager.java:359)
```
1) view the map without the compass
2) turn off the screen
3) turn on the screen
4) turn on the compass from the menu

When omitting steps 2 & 3, the compass is displayed correctly.

It is possible I'm misusing this but my code is similar to StarterMapFragment.java.  However in the demo app I don't see a menu to test it.

Would it be better if CompassOverlay did something other than throw a RuntimeException in this situation?

**Comment by spyhunter99** [comment]
it's probably related to the memory leak ticket. On pause you should destroy the compass, on resume, create a new one and add it back to the map

**Comment by MJHache** [comment]
I get this error too when coming back from onResume(). 

I've been developing my app with 5.1 and now that I've went from 5.1 to 5.6.3 I get this`java.lang.RuntimeException: You must pass an IOrientationProvider to setOrientationProvider()`

I've tried using other versions but it does the same error from 5.6.4 to 5.4

It seems CompassOverlay loses its IOrientationProvider somewhere from using .disableCompass() to enableCompass() because using one right after the other gives this error.

**Comment by spyhunter99** [comment]
Right, you need to destroy the compass and recreate it on resume. This was done to prevent memory leaks.

**Comment by MJHache** [comment]
Is this a temporary fix or the library is taking this way permanently?

**Comment by spyhunter99** [comment]
@MJHache it is open source. If you can find a better way, please open a PR. There's always a balance between preventing memory/release leaks and handling android and view life cycles. It will most likely be like this until someone man's up and comes up with a better solution to fixing the memory leaks that the prior versions had
