### ISSUE TITLE
Question: how best to achieve an offset map centre?

### ISSUE THREAD

**Issue by BrantApps** [osmdroid/osmdroid#586]
### First, a thank you
My Android app has two flavours, one for the [Google Play Store](https://play.google.com/store/apps/details?id=com.oceanlife&hl=en_GB), utilising Google Maps (v2) and another for the [Amazon App Store](https://www.amazon.co.uk/BrantApps-Buoys-Tides-and-Weather/dp/B00LVD1DDI), utilizing the greatness of open source that is ````osmdroid````. Thank you for your continued efforts with the library, I just updated to v5.6.4 from a much earlier version and it was great to see the progress that has been made.

### My question
I have been adopting Material design over the last year and a half and recently moved to a card interface when setting up a 'spot' (the main model in my app). The card covers half the map on a phone form factor - see screenshots:

When moving the map | When the map stops
------------ | -------------
![osmdroid-question-moving](https://cloud.githubusercontent.com/assets/1109992/25220599/2b99b57c-25aa-11e7-86c6-6ce1dd9b7736.png) | ![osmdroid-question](https://cloud.githubusercontent.com/assets/1109992/25220527/fe5f8fe6-25a9-11e7-8ecb-7e3a8e3d396d.png)

_Note the difference between the polyline apex coming from what osmdroid believes to be the center and what would be the centre to the user when the card animates to cover part of the map_

Notice that the map centre (denoted by the white place icon when the map stops) is not in the centre, rather it is shifted up by the height of the card and padding. Within Google Maps (v2) this behaviour can be achieved using the [````setPadding(left, top, right, bottom)````](https://developers.google.com/maps/documentation/android-api/map#map_padding). How should a similar effect be achieved in osmdroid?

### What I have tried
To date, I have taken the approach of overriding ````getCenter()```` with code akin to;

```java
 /**
   * @see com.brantapps.polaris.api.Mappable#getCenter()
   */
  @Override
  public GeoPoint getCenter() {
    // Where is the current centre
    final IGeoPoint center = mapView.getMapCenter();

    // Calculate the top-left and bottom-right positions
    IGeoPoint tl = mapView.getProjection().fromPixels(0, 0);
    IGeoPoint br = mapView.getProjection().fromPixels(mapView.getWidth(), mapView.getHeight());

    // reset the centre with the px per degree calc.
    double newLon = leftPxOffset * (br.getLongitude() - tl.getLongitude()) / mapView.getWidth() + center.getLongitude();
    double newLat = bottomPxOffset * (br.getLatitude() - tl.getLatitude()) / mapView.getHeight() + center.getLatitude();

    return GeoPointHelper.fromIGeoPointToPolarisGeoPoint(new org.osmdroid.util.GeoPoint(newLat, newLon));
  }

```

...where ````leftPxOffset```` and ````bottomPxOffset```` represent the movement up and slight to the right of centre (the slight right is a side-effect from the Google logo and my maps abstraction library).

It kind of works, but not great. Does the community have a better idea? Am I missing something in the SDK that takes care of these calculations?

**Comment by BrantApps** [comment]
Asked on Stackoverflow [here](http://stackoverflow.com/questions/44085662/osmdroid-how-best-to-achieve-an-offset-map-centre).

**Comment by spyhunter99** [comment]
Is there a way to get the dimensions of the card? that may be your bet to add some padding to the calculations

**Comment by BrantApps** [comment]
Hi @spyhunter99, thank you for your response. Yes, this is the ````leftPixelOffset```` and ````bottomPixelOffset```` values (````leftPixelOffset```` is zero in OSMDroid but has a value in the Google Maps flavour owing to the Google symbol watermark). The bottomPixelOffset inspects a ````dimen.xml```` value which is also used to set the size of the card. Is my ````getCenter()```` override the way to do it do you think?

**Comment by BrantApps** [comment]
ok, so I have a working implementation that looks like this;

```java
private GeoPoint adjustCentreByPadding(final double latitude, final double longitude, boolean negate) {
    final int newY = negate ? (int) (mapView.getHeight()/2-bottomPxOffset) : (int) (mapView.getHeight()/2+bottomPxOffset);
    mapView.getController().setCenter(new org.osmdroid.util.GeoPoint(latitude, longitude));
    final IGeoPoint offset = mapView.getProjection().fromPixels(mapView.getWidth()/2, newY);
    return KindleGeoPointHelper.fromIGeoPointToRoverGeoPoint(offset);
  }
```
*Snippet 1*: new adjust for padding method

I'm not 100% on why it's working as it is right now but essentially, I call this method from both my ````getCenter()```` and ````setCenter(...)```` overrides which look like this respectively;

```java
/**
   * @see com.brantapps.polaris.api.Mappable#getCenter()
   */
  @Override
  public GeoPoint getCenter() {
    return adjustCentreByPadding(mapView.getMapCenter().getLatitude(), mapView.getMapCenter().getLongitude(), true);
  }
```
*Snippet 2*: getCenter() implementation

```java
/**
   * @see com.brantapps.polaris.api.Mappable#setCenter(GeoPoint)
   */
  @Override
  public void setCenter(final GeoPoint geoPoint) {
    final GeoPoint adjustedCenter = adjustCentreByPadding(geoPoint.getLatitude(), geoPoint.getLongitude(), false);
    mapView.getController().setCenter(new org.osmdroid.util.GeoPoint(adjustedCenter.getLatitude(), adjustedCenter.getLongitude()));
  }
```
*Snippet 3*: setCenter(...) implementation

Notice the "negate" term which is the bit I need to figure out. As I observe it, when shifting the map "up" owing to the card overlay (i.e. the setCenter(...) override) then I add pixels to the height projection. When I subsequently call getCenter() I subtract pixels from the height projection.

The ````KindleGeoPointHelper```` class is an artifact of the _Polaris_ abstraction library I have placed over Google and OSMDroid and can be ignored.
