### ISSUE TITLE
Moving current position marker smoothly

### ISSUE THREAD

**Issue by LamraniOthmane** [osmdroid/osmdroid#589]
Hello community, I want to move the current position marker smoothly, the current animation is too fast and seems to be laggy.
I tried to do it myself but i have no control on the current position marker.
Is there any solution for that ??  Thanks in advance.

**Comment by spyhunter99** [comment]
The current animation is based on the frequency in which GPS updates, which is generally 1hz. You can override the MyNewLocationOverlay or make your own. The logic isn't very difficult. If you come up with a better solution, please open a PR

**Comment by LamraniOthmane** [comment]
Thank i will try my best to find a solution

**Comment by spyhunter99** [comment]
closing to due any other feedback, reopen if needed

**Comment by NimaaZx** [comment]
@spyhunter99 Hey. Can you give me a sample code ? I do not know what property I should override.

**Comment by spyhunter99** [comment]
basically, you have 1 timer task/thread that handles the animation (map.animateTo or centerMap) that runs at some frequency, say every 250ms. The target location should be an average of the current device location vs the current map center point. You'll probably have to play around with this, but it should help smooth out the transitions.

**Comment by NimaaZx** [comment]
@spyhunter99  thanks a lot. I will follow your advice soon. but before that can you see my latest issue(question) that opened in osmdroid , please ?
