### ISSUE TITLE
extending ItemizedOverlayWithFocus

### ISSUE THREAD

**Issue by fredleput** [osmdroid/osmdroid#591]
Hi all,

I'm quite new to java and i don't understand how i can extend ItemizedOverlayWithFocus Class to make my own... I searched for several hours on the net but didn't found what i expected. I want to add custom properties (description....) and display them in a separate Activity when the marker is clicked. 

I tried to override the onItemSingleTapUp method but i can manage how to acces my custom properties.
Dummy isn't it ?

fred

**Comment by MKergall** [comment]
Use the Marker overlay instead. 
Customization of the bubble is explained [here](https://github.com/MKergall/osmbonuspack/wiki/Tutorial_2#7-customizing-the-bubble-behaviour).

**Comment by spyhunter99** [comment]
closing due to lack of feedback/reply. feel free to reopen if this is in error
