### ISSUE TITLE
How Set Tile provider from Sqllite database

### ISSUE THREAD

**Issue by naeimrezaeian** [osmdroid/osmdroid#592]
hi,
My map sqllite database is created through the Mobile Atlas Creator when i use this code for read from database my mobile application show empty screen ,can not load tile from datbase

my code 
`final ITileSource tileSource2 = new XYTileSource("Layer.sqlitedb",
                1, 17, 64, ".png", new String[] {
                ""
        });
        map.setUseDataConnection(false);
        map.setTileSource(tileSource2);
`
![m1](https://cloud.githubusercontent.com/assets/7207622/25551339/04a21110-2c8c-11e7-8c2f-bb182123e6ce.jpg)

![m2](https://cloud.githubusercontent.com/assets/7207622/25551354/37f9e09c-2c8c-11e7-801e-1406dc7e2e4d.jpg)

**Comment by spyhunter99** [comment]
In mobac when you set the layer name, this is the same layer name you reference in osmdroid. That's probably your issue

**Comment by spyhunter99** [comment]
You really need to open the database and see what you saved the name of the layer as. I usually use the sqlite plugin for firefox and open the database. Select * from tiles limit 10; or something like that. Whatever should up for the `provider` table is what you want to match your XYTleSource name
