### ISSUE TITLE
MyLocationOverlay doesn't update position when position change

### ISSUE THREAD

**Issue by walkingtohorizon** [osmdroid/osmdroid#593]
I'm using MyLocationOverlay to show current position of device of map using gps. I can show my location when app start but when i move the position of device on map doesn't change.
```
        GpsMyLocationProvider gpsLocationProvider = new GpsMyLocationProvider(getContext());
        gpsLocationProvider.setLocationUpdateMinTime(100);
        gpsLocationProvider.setLocationUpdateMinDistance(0);
        MyLocationNewOverlay      mLocationOverlay = new MyLocationNewOverlay(mvMap);

        //mLocationOverlay.enableMyLocation(IMyLocationProvider);
        mLocationOverlay.enableMyLocation(gpsLocationProvider);
        mvMap.getOverlays().add(mLocationOverlay); 
```
am i missing something?

**Comment by spyhunter99** [comment]
did you try this?

`mLocationOverlay.enableFollowLocation();`

**Comment by spyhunter99** [comment]
almost a year later, closing due to lack of feedback

**Comment by spyhunter99** [comment]
@walkingtohorizon i did add to our sample app a simple diagnostics tool to print out what location providers are available, you might want to play around with it your device to debug it

**Comment by spyhunter99** [comment]
sorry commented on the wrong ticket
