### ISSUE TITLE
Slow loading and crashes

### ISSUE THREAD

**Issue by blackeagle93** [osmdroid/osmdroid#594]
I've been using osmdroid for some time in my app. Recently some crashes and errors showed up in G Play console so I decided to upgrade the library to the latest version. 
The problems are still here.
1. The MapView (defined in XML) is loading very slow on many devices. Vid: https://pcmlich.fit.vutbr.cz/tmp/20170430_131608.mp4
2. Zooming is lazy and when you zoom fast, the app crashes.

I am using offline tiles from zip archive. JPG overlay as the base layer and PNG overlay for showing airspace layer. Then I draw a KML overlay by bonuspack (in asynctask). It consists of around 50 markers and 20 polylines.

**1st ANR error from Google Play:**
osmdroid-android:5.6.4
Galaxy S5 mini (kminilte), Android 4.4
ANR Input dispatching timed out (Waiting because the touched window has not finished processing the input events that were previously delivered to it.)
https://pastebin.com/zJLskTfM

**2nd ANR error from Google Play:**
osmdroid-android:5.1@aar
Galaxy A5(2016) (a5xelte), Android 6.0
ANR Input dispatching timed out (Waiting to send non-key event because the touched window has not finished processing certain input events that were delivered to it over 500.0ms ago. Wait queue length: 38. Wait queue head age: 20516.9ms.)
https://pastebin.com/3J8XcaS5

**3rd ANR error**
osmdroid-android:5.6.4
Galaxy S5 (klte), Android 6.0
ANR Input dispatching timed out (Waiting to send non-key event because the touched window has not finished processing certain input events that were delivered to it over 500.0ms ago. Wait queue length: 6. Wait queue head age: 20066.8ms.)
https://pastebin.com/zJMKKTk1

I tried to revert to the previous version again and ended up here: http://imgur.com/a/0WNg3
This is from the S5 mini. (I am talking to one of the users who reported the bug). As you can see, the airspace is loaded but the base layer is not. He can move the map, but once he zooms in, the app crashes.

I am fine on my Honor 8 and I was not able to reproduce it on some other devices I have or AVD.
Any clues?

**Comment by blackeagle93** [comment]
One more report:
osmdroid-android:5.6.4
Galaxy S5 (klte), Android 6.0
ANR Input dispatching timed out (Waiting to send non-key event because the touched window has not finished processing certain input events that were delivered to it over 500.0ms ago. Wait queue length: 6. Wait queue head age: 20066.8ms.)
https://pastebin.com/zJMKKTk1

**Comment by spyhunter99** [comment]
With both the secondary tile overlay and the additional polylines/markers, are they created at startup? you might want to stagger that the startup. Is osmdroid set for online tiles at all or is it offline tiles only? There is a known issue that in that osmdroid will continue to try and download tiles that are required for the current view, even if they do not exist on the tile server.

Is it possible that hardware acceleration is turned on for the map view? Can you get the stack trace from the device the app crashed on (s5 mini)?

**Comment by blackeagle93** [comment]
With both the secondary tile overlay and the additional polylines/markers, are they created at startup?
 - Yes they are...It is part of the map. It has to be loaded automatically... What was your idea?

Is osmdroid set for online tiles at all or is it offline tiles only?
- mapView.setUseDataConnection(false); ...anything else I can do?

Is it possible that hardware acceleration is turned on for the map view?
- Do I have to disable it in the manifest? Because I am not doing that at the moment.

Can you get the stack trace from the device the app crashed on (s5 mini)?
- I am afraid I am not able to get the stack trace. The device belongs to the end user who is willing to help me with debugging.

I will now prepare 3 debug .apk files 
 - with disabled hw acceleration, 
 - with online tiles only, 
 - with disabled KML loading

and let him test them if the problem still persists...

**Comment by blackeagle93** [comment]
Confirmed! I created the map files again in MOBAC. Output format changed from osmdroid zip to osmdroid sqlite and everything works fine on the devices where the zip caused the crash.

**Comment by spyhunter99** [comment]
How big was the zip? There is an upper limit on android to the number of entries in a zip file. It's pretty easy to hit with map tiles

**Comment by blackeagle93** [comment]
As I said, 350 and 40 MB, zoom levels 8-14

**Comment by spyhunter99** [comment]
It's not the size of the zip in bytes, it's the number of files within the zip. Android has an upper limit of 65k or so. Rereading your post, this is probably not the issue

**Comment by blackeagle93** [comment]
Theres 75359 files in the zip.

**Comment by spyhunter99** [comment]
That would be why, android's java implementation just swallows the issue. More than 65k tiles per zip and it just won't read it.

**Comment by spyhunter99** [comment]
@blackeagle93 where are you at with this issue?

**Comment by spyhunter99** [comment]
closing due to lack of any additional feedback or comments.
