### ISSUE TITLE
How to deal with the Polyline width when I zoom out the map .       

### ISSUE THREAD

**Issue by niray** [osmdroid/osmdroid#595]
Polyline pathOverlay = Polyline()
        pathOverlay.color = Color.parseColor("#99ffff00")
        pathOverlay.width = 10f
        pathOverlay.points = points 
        mMapView.overlays.add(0, pathOverlay)
 
I use this way to add a Polyline in the map, but when I zoom out or zoom in the map ,the width of 
 polyline  will zoom also. how can I deal with this problem?
  
[no zoom](https://github.com/niray/LbsMap-master/blob/master/1.jpg?raw=true)
[Zooming](https://github.com/niray/LbsMap-master/blob/master/2.jpg?raw=true)

**Comment by spyhunter99** [comment]
The "zooming" image... is that during the process of zooming or after the the zoom animation is completed?

**Comment by niray** [comment]
zooming is during the animation..

**Comment by spyhunter99** [comment]
Well i guess we could turn off the zooming animation, but that's about it

**Comment by niray** [comment]
but which API is close the animation? I use `mMapController.zoomOut()` `mMapController.zoomIn()` and double tap screen to zoom the map . 

When I add the Overlay item with `ItemizedOverlayWithFocus<OverlayItem>`  ， the overlay will keep the same size when zooming map  ,  they are any way to add Polyline use  `ItemizedOverlayWithFocus<Polyline>` this way？

**Comment by spyhunter99** [comment]
the zooming happens in map controller. it may be possible to trigger a onDraw method during the zoom, but this could be expensive when there are many overlays to redraw

**Comment by spyhunter99** [comment]
@MKergall any insight on this?

**Comment by MKergall** [comment]
Other use case for issue #661. 
And (hopefully) same solution...

**Comment by monsieurtanuki** [comment]
@niray Should be fixed by #800. Could you give it a try?

**Comment by spyhunter99** [comment]
this is resolved with v6
