### ISSUE TITLE
set camera angle 

### ISSUE THREAD

**Issue by LamraniOthmane** [osmdroid/osmdroid#596]
Hello guys, i would like to know if there is a possibility to display the map with different camera angle, like  Google Maps Camera "tilt viewing angle".
Thanks in advance

**Comment by spyhunter99** [comment]
No supported and complex to implement with open gl support

**Comment by LamraniOthmane** [comment]
Alright, thank you

Le 5 mai 2017 23:50, "spyhunter99" <notifications@github.com> a écrit :

No supported and complex to implement with open gl support

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/osmdroid/osmdroid/issues/596#issuecomment-299593107>,
or mute the thread

**Comment by mizofumi** [comment]
I achieved this by transforming the MapView canvas into a trapezoid.
For more information, please click here.
https://qiita.com/mizofumi0411/items/ccba3c81922ac50631cf
