### ISSUE TITLE
SQLite Cache still not being cleaned with CacheManager.cleanAreaAsync

### ISSUE THREAD

**Issue by secaw** [osmdroid/osmdroid#598]
Sorry if I'm missing something, as I'm new to this, but this issue (https://github.com/osmdroid/osmdroid/issues/426) does not seem to have been fixed in 5.6.4?

Cache is still only being cleaned from files and not from SQLite as of code in CacheManager -> CleaningTask -> cleanArea() :

```
File file = getFileName(tileSource, tile);
if (file.exists()) {
  file.delete();
  deleted++;
}
tileCounter++;
if (tileCounter % 1000 == 0) {
  if (isCancelled()) {
    return deleted;
  }
  publishProgress(tileCounter, zoomLevel);
}
```

**Comment by spyhunter99** [comment]
looking at it now...

**Comment by spyhunter99** [comment]
confirmed. damn.

**Comment by spyhunter99** [comment]
https://github.com/osmdroid/osmdroid/commit/6fa9ebc64285c005adeeded80459f489294b262d

looks like it was squashed by another commit.

**Comment by secaw** [comment]
Alright, thanks for this and your great work!

**Comment by spyhunter99** [comment]
np

**Comment by dead1ock** [comment]
I seem to be having a similar issue with 5.6.5 and 5.6.4. Always reported 0 tiles deleted in 5.6.4, updated to 5.6.5 today and now I don't get a toast message when I call cleanAreaAsync. I'm assuming the tiles haven't been deleted because when I go to re-cache the area, the download action doesn't take as long (nearly instantaneous) to complete the action as it did the first time (when the tiles were downloaded).

Any ideas?

**Comment by spyhunter99** [comment]
@dead1ock looking at it now

**Comment by spyhunter99** [comment]
@dead1ock don't see anything wrong with it. I just ran a test and it appeared to work. Tested by 

- zooming into a specific area
- wait for the tiles to load
- call clear area for the current location
- exit the fragment/activity
- reenter the fragment/activity
- watch the tiles reload.

and i added a sample to the sample app for doing this task. Anything else specific with your setup?

**Comment by dead1ock** [comment]
@spyhunter99 thank for the reply and the sample!

In my setup, I have a "Menu Menu" activity that displays a list of gpx files and whether or not they have been cached. When the user requests the cache a gpx file, the MainActivity will launch the OSMActivity with the intent of caching or cleaning the area, then returning the MainActivity.

I'm caching the area using a polyline like so:

private void cacheGpxTiles(final GPX cGPX) {

        ArrayList<GeoPoint> track = new ArrayList<>();
        for(int trackNum = 0; trackNum < 1; trackNum++) {
            GPX.Track cTrack = cGPX.tracks.get(trackNum);
            for (int x = 0; x < cTrack.points.size(); x++) {
                GPX.Point cPoint = cTrack.points.get(x);
                track.add(new GeoPoint(cPoint.latitude, cPoint.longitude));
            }
        }

        tileCacheManager.downloadAreaAsync(OSMActivity.this, track, 0, 16, new CacheManager.CacheManagerCallback() {
            @Override
            public void onTaskComplete() {
                Toast.makeText(OSMActivity.this, "Cached " + cGPX.getName() + " ...", Toast.LENGTH_LONG).show();
                finish();
            }

            @Override
            public void updateProgress(int progress, int currentZoomLevel, int zoomMin, int zoomMax) {

            }

            @Override
            public void downloadStarted() {
                Toast.makeText(OSMActivity.this, "Caching " + cGPX.getName() + " ...", Toast.LENGTH_LONG).show();
            }

            @Override
            public void setPossibleTilesInArea(int total) {

            }

            @Override
            public void onTaskFailed(int errors) {
                Toast.makeText(OSMActivity.this, "Failed to cache " + cGPX.getName() + " ...", Toast.LENGTH_LONG).show();
            }
        });
    }

    private void deleteGpxTiles(GPX cGPX) {
        ArrayList<GeoPoint> track = new ArrayList<>();

        for(int trackNum = 0; trackNum < 1; trackNum++) {

            GPX.Track cTrack = cGPX.tracks.get(trackNum);
            for (int x = 0; x < cTrack.points.size(); x++) {
                GPX.Point cPoint = cTrack.points.get(x);
                track.add(new GeoPoint(cPoint.latitude, cPoint.longitude));
            }
        }

        tileCacheManager.cleanAreaAsync(OSMActivity.this, track, 0, 16);
        //finish();
    }

I ran the debugger to be sure I was hitting the correct execution paths, and to be sure the track points being loaded were the same. Caching the area executes as expected (map launches, downloads the area with progress bar, returns to main menu), but when I go to clean an area it launches the map and then does nothing. I commented out the last "finish()" in the deleteGpxTiles function to see if maybe finishing before the tile manager had a chance to finish was the problem.

Thanks for the help!

**Comment by dead1ock** [comment]
@spyhunter99 I was able to get the desired results by using the following:
`        tileCacheManager.cleanAreaAsync(OSMActivity.this, tileCacheManager.getTilesCoverage(track, 0, 16), 0, 16);`

I stepped through the debugger and found mTiles was always empty when it hit doInBackground for a cleaning task based on track points. This is the constructor which was used: 

`public CacheManagerTask cleanAreaAsync(final Context ctx, ArrayList<GeoPoint> geoPoints, int zoomMin, int zoomMax) {
        BoundingBox extendedBounds = extendedBoundsFromGeoPoints(geoPoints,zoomMin);
        return cleanAreaAsync(ctx, extendedBounds, zoomMin, zoomMax);
    }`

When I looked at the extendedBounds object, the bounds were not near my input track.
