### ISSUE TITLE
Marker Animation - Smoothly 

### ISSUE THREAD

**Issue by naeimrezaeian** [osmdroid/osmdroid#599]
hi ,
how i can add Animating  on osmdroid Marker when change GPS coordinates for example animate marker movement from point A to point B smoothly ?

tnx

**Comment by spyhunter99** [comment]
I believe this was asked the other day. I'm not exactly sure what your requirement what you are referring to but I think you mean when using `MyNewLocationOverlay` and you and the device are moving at speed and receiving GPS updates at the rate of about 1hz, the screen basically animates to the new location in 1 second chunks. The solution may be to increase the delay (duration) of the animation for animateTo.

**Comment by spyhunter99** [comment]
closing due to lack of feedback/reply. feel free to reopen if this is in error
