### ISSUE TITLE
MapTileFilesystemProvider always reloads tiles

### ISSUE THREAD

**Issue by Anfet** [osmdroid/osmdroid#60]
If you leave files on your SD for a week or more
FilesystemProvider will start realoading all tiles constantly, and it is constantly eating CPU and memory.

Found out following code:

```
 final long now = System.currentTimeMillis();
                final long lastModified = file.lastModified();
                final boolean fileExpired = lastModified < now - mMaximumCachedFileAge;

                if (fileExpired && drawable != null) {
                    if (DEBUGMODE) {
                        logger.debug("Tile expired: " + tile);
                    }
                    drawable.setState(new int[] {ExpirableBitmapDrawable.EXPIRED });
                }

                return drawable;
```

It seems that mMaximumCachedFileAge is fixed to ONE_WEEK and cannot be modified.
Tried subclassing MapTileFilesystemProvider and replacing it in MapTileProviderBasic subclass, but map simply shows default implementation.
My tileset functions are executed and tiles are loaded from filesystem, but aren't displayed.

Any solution?

**Comment by spyhunter99** [comment]
@Anfet think you an whip up an example to reproduce this?

**Comment by spyhunter99** [comment]
@Anfet we can now adjust or override the expiration time on donwloaded tiles. See #481 and the Configuration class
