### ISSUE TITLE
Hide markers when click on the map

### ISSUE THREAD

**Issue by Jackcar** [osmdroid/osmdroid#600]
I have an ItemizedOverlayWithFocus with a list of items, when I click in any item, a popup is showed up.
What I want is to hide the popup when I click on the map, is there a method for that?

Thanks.

**Comment by niray** [comment]
mMapView.setOnTouchListener { view, motionEvent ->
          //dismissSomething()
            false
        }

**Comment by spyhunter99** [comment]
you can override the click method on itemized overlay, i think you need to provide it with the constructor, but yes

**Comment by spyhunter99** [comment]
closing to due any other feedback, reopen if needed
