### ISSUE TITLE
Animation some Marker not all overlay ?

### ISSUE THREAD

**Issue by mhjjp** [osmdroid/osmdroid#602]
I need to add a lot of animation markers,  The inv need to draw too much, cause the interface card, I have been using in the mapView parent window to add a custom View, letting a custom View to animation, this interface is no longer caton, but InfoWindow was covered by this View
![screenshot](https://cloud.githubusercontent.com/assets/13436989/26051879/2afef85c-3996-11e7-9667-2a895d01b71f.png)

.I have a few questions1, have a kind of method, setting to redraw specific marker?2, on the MapView addView custom View?(I tried but the custom View does not display, is it because the custom View has been covered with overlay? How to solve this problem)

**Comment by spyhunter99** [comment]
try using the marker class,

**Comment by spyhunter99** [comment]
closing to due any other feedback, reopen if needed
