### ISSUE TITLE
Improvement for ScaleBarOverlay

### ISSUE THREAD

**Issue by lurtzn** [osmdroid/osmdroid#604]
The bars of the ScaleBarOverlay don't get rebuild if the screen size changed. So if your Keyboard open/closes or your Activity changes from Landscape to Portrait the bars are the wrong position.

to fix that change the condition for rebuilding in the draw function.
org/osmdroid/views/overlay/ScaleBarOverlay.java#L377
old code:
<pre>
screenWidth = mapView.getWidth();
screenHeight = mapView.getHeight();
final IGeoPoint center = projection.fromPixels(screenWidth / 2, screenHeight / 2, null);
if (zoomLevel != lastZoomLevel
		|| (int) center.getLatitude() != (int) lastLatitude) {
	lastZoomLevel = zoomLevel;
	lastLatitude = center.getLatitude();
	rebuildBarPath(projection);
}</pre>

new code:
<pre>
int _screenWidth	   = mapView.getWidth();
int _screenHeight   = mapView.getHeight();
boolean screenSizeChanged = _screenHeight!=screenHeight || _screenWidth != screenWidth;
screenHeight = _screenHeight;
screenWidth = _screenWidth;
final IGeoPoint center = projection.fromPixels(screenWidth / 2, screenHeight / 2, null);
if (zoomLevel != lastZoomLevel
		|| (int) center.getLatitude() != (int) lastLatitude || screenSizeChanged) {
	lastZoomLevel = zoomLevel;
	lastLatitude = center.getLatitude();
	rebuildBarPath(projection);
}
</pre>

**Comment by spyhunter99** [comment]
merged
