### ISSUE TITLE
Error when trying to update from osmdroid 5.5 to 5.6.4

### ISSUE THREAD

**Issue by zulluadi** [osmdroid/osmdroid#606]
Hi, I get the following error when trying to use the latest osmdroid version:

Error:Could not find osmdroid-android-release.aar (org.osmdroid:osmdroid-android:5.6.4).
Searched in the following locations:
    https://repo1.maven.org/maven2/org/osmdroid/osmdroid-android/5.6.4/osmdroid-android-5.6.4-release.aar

I've added mavenCentral() to all projects repositories and set compile 'org.osmdroid:osmdroid-android:5.6.4' in my dependencies.

Checking https://repo1.maven.org/maven2/org/osmdroid/osmdroid-android/5.6.4/, I've seen that there is no osmdroid-android-5.6.4-release.aar but only osmdroid-android-5.6.4.aar. Can I do something to dismiss the "-release" suffix in my gradle configuration?

**Comment by spyhunter99** [comment]
yup just remove release classifier in your build script

**Comment by istvanszoboszlai** [comment]
Hi, I have the same problem, and it looks like everyone is just ignoring this. There must be a bug somewhere, most likely in gradle.
I just cannot find a solution anywhere to this. There is no ":release" in the gradle dependency definition and gradle still tries to resolve to "...-release:...".
This is totatlly related to the issue https://github.com/osmdroid/osmdroid/issues/514, which is also closed without a real solution.
@spyhunter99, please reopen one of them until there will be a real solution.

**Comment by spyhunter99** [comment]
Post the build script where you declare the osmdroid dependency

**Comment by spyhunter99** [comment]
And the gradle version and android build tools version,  target and compile sdk

**Comment by zulluadi** [comment]
@istvanszoboszlai Check if you also use the latest version of osmbonuspack. I am not sure but I think that I needed to update the osmbonuspack in order to be able to update osmdroid.

**Comment by istvanszoboszlai** [comment]
Thanks a lot @zulluadi, @spyhunter99 for helping so fast. 
No luck yet.
I am also trying to update some packages. I want to do my share or solving the problem before I just drop my gradle configs here.

**Comment by istvanszoboszlai** [comment]
@zulluadi 
You indeed were right. If the osmbonuspack and the osmdrod packages do not match. I get the error with not being able to find the -release suffixed version in maven central.
With
```
    compile 'org.osmdroid:osmdroid-android:5.6.5'
    compile 'com.github.MKergall:osmbonuspack:6.4'
```
It works fine. Thanks again for your help!
