### ISSUE TITLE
ndroid OSM zoom level 19 and above

### ISSUE THREAD

**Issue by Reed-Xiong** [osmdroid/osmdroid#607]
Hi guy
The question I have is that I need to zoom in, past level 18. Which I've also been able to do so by setting the max zoom level. However, there aren't any tiles available from the default tile provider for zoom 19 and above I really only require up to 20, 21 max too.

Is there a way for me to create my own tiles? Have custom tiles? Generate my own map? Or if there's a tile provider that allows me to zoom into the map past level 18 and still be able to see the map tiles?

I need a higher zoom level because I'm overlaying custom markers and if it's not zoomed in enough, the markers overlap,please give me some ideas for this...Thanks

**Comment by spyhunter99** [comment]
Yes you make your own tiles. Out of scope for this project, but check open street maps wiki.
