### ISSUE TITLE
Problem of position of the window of a context menu from API 24.

### ISSUE THREAD

**Issue by Conan42** [osmdroid/osmdroid#608]
Hello,

I always have a position problem while opening a contextual menu with the double click on the map from API 24. Normally the window opens at the coordinates of GeoPoint with API 23, and there it opens up To the right of the screen.

    @Override
    public boolean longPressHelper(GeoPoint p) {
        this.p = p;
        return showContextMenu(p);
    }

    private boolean showContextMenu( GeoPoint geoPosition ) {
        final GeoPoint p = geoPosition;
        MenuInflater inflater = activity.getMenuInflater();
        MapView.LayoutParams lp = new MapView.LayoutParams( 0, 0, geoPosition, 0, 0, 0 );
        if( tempView != null ) this.removeView( tempView );
        tempView = new View( context );
        tempView.setVisibility(View.VISIBLE);
        this.addView( tempView, lp );
        PopupMenu menu = new PopupMenu( context , tempView ); 
        ...
        menu.show();
        return true;
    }

**Comment by spyhunter99** [comment]
most likely this is an android issue, i'm not too sure i can do anything about this. sounds like it duplicates #444

**Comment by litrik** [comment]
I was able to solve this issue by "posting" the creation of the menu. This way the OS has laid out the tempView.

**Comment by Conan42** [comment]
How is it by posting the menu? Do you have a piece of code please?

**Comment by litrik** [comment]
Here's some Kotlin code:
```
private fun showCreateMenu(point: GeoPoint) {
  popupAnchorView?.let { mapView.removeView(popupAnchorView) }
  popupAnchorView = View(requireContext()).apply {
    visibility = View.VISIBLE;
    mapView.addView(this, MapView.LayoutParams(0, 0, point, 0, 0, 0))
    mapView.post {
      val popupMenu = PopupMenu(requireContext(), this);
      requireActivity().menuInflater.inflate(R.menu.map_popup, popupMenu.menu)
      popupMenu.show()
      popupMenu.setOnMenuItemClickListener {
        when (it.itemId) {
          ...
          else -> false
        }
      }
    }
  }
}
```

**Comment by Conan42** [comment]
oh thanks, i'm going to try tonight, and does it work for android 7 and 7.1?

**Comment by litrik** [comment]
I have tested this on API 24 (Android 7.0)

**Comment by Conan42** [comment]
I just tried, it works, thank you very much. it was an old bug. You can find met work on google play by loading Harpoon for android.

**Comment by monsieurtanuki** [comment]
@litrik Perfect! I guess the `post`syntax is generally a good option, and I've just added a comment about this issue in the [FAQ](https://github.com/osmdroid/osmdroid/wiki/FAQ#i-try-to-set-the-zoom-and-center-of-my-mapview-in-activityoncreate-or-fragmentoncreateview-but-it-doesnt-seem-to-work).
@Conan42 Feel free to close the issue.
