### ISSUE TITLE
is there anyway to load PBF tiles in an mbtiles archive offline?

### ISSUE THREAD

**Issue by kingfisherphuoc** [osmdroid/osmdroid#610]
I tried to load Mbtiles file into mapview but failed, nothing is dipsplayed on the map.

```
        mapView = (MapView) findViewById(map);
        // offline usage
        Timber.plant(new Timber.DebugTree());
        File file = new File(Environment.getExternalStorageDirectory() + "/osmdroid/MbTilesBacNinh.mbtiles");
        Timber.e("File exist? : " + file.exists());
        SimpleRegisterReceiver simpleReceiver = new SimpleRegisterReceiver(this);
        XYTileSource mbtilesRender = new XYTileSource(
                "mbtiles",
                0, 18,  // zoom min/max <- should be taken from metadata if available
                256, ".png", new String[]{});

        IArchiveFile[] files = {MBTilesFileArchive.getDatabaseFileArchive(file)};
        MapTileModuleProviderBase moduleProvider = new MapTileFileArchiveProvider(simpleReceiver, mbtilesRender, files);

        MapTileProviderArray mProvider = new MapTileProviderArray(mbtilesRender, null,
                new MapTileModuleProviderBase[]{moduleProvider}
        );
        mapView.setTileProvider(mProvider);
        mapView.setUseDataConnection(false);
        GeoPoint geoPoint = new GeoPoint(21.049034, 105.873479);
        IMapController mapViewController = mapView.getController();
        mapViewController.setZoom(15);
        mapViewController.setCenter(geoPoint);
```
Is there any problem with my code? Can anyone please give me an update example which give me the example of the newest version of osmdroid library?
If I use `private XYTileSource FourUMapsTileSource = new XYTileSource("4uMaps", 0, 18, 256, ".png", new String[]{});`, as below:

```
 mapView.setTileSource(FourUMapsTileSource);
mapView.setUseDataConnection(false);
geoPoint.setCoords(21.049034, 105.873479);
IMapController mapViewController = mapView.getController();
mapViewController.setZoom(15);
mapViewController.setCenter(geoPoint);
```
everything will be ok. However, I want to load mbtile without knowing the map's source. Is it possible?

**Comment by grzesiek2010** [comment]
@kingfisherphuoc 
I have the same problem I can use an example file from http://geoodk.com/mbtiles_howto.html and then everything is ok but it doesn't work if I use other files eg. from https://www.mapbox.com/help/define-mbtiles/

**Comment by spyhunter99** [comment]
The default tile provider should just load them.  I'll take a look at it

**Comment by grzesiek2010** [comment]
@spyhunter99 thanks it would be great. I'm looking forward to results of your investigation.

**Comment by spyhunter99** [comment]
@grzesiek2010 so yes, the default tile provider chain should load them, assuming they are available and stored in at least one of the offline tile storage locations, the default is /sdcard/osmdroid but it may also be on an external sdcard. See the notes on the Configuration class and the wiki change log.

more over, mbtile does not support multiple tile sources per file, so esscentially osmdroid will load any and all tiles from all mbtile archives

**Comment by kingfisherphuoc** [comment]
I'm using 4umaps mbtiles for offline usage. Is there a way that I can load show 4umaps (instead of default map source) online?

**Comment by grzesiek2010** [comment]
@spyhunter99 I can confirm that everything is ok if I use this mbtiles file http://geoodk.com/mbtiles_howto.html the I can copy it to `/sdcard/osmdroid` as you said and it works (this file works with my code as well as I mentioned above). The problem is with some particular files like https://www.mapbox.com/help/define-mbtiles/ it doesn't work if I copy this file to `/sdcard/osmdroid`.

Have you tested my files?

**Comment by spyhunter99** [comment]
just pulled down the dc-baltmore mbtiles set from https://openmaptiles.org/downloads/#country
looking at the database, i don't seen any issue why it wouldn't load, except for the fact that the table "tiles" is usually a real time. It's a "view" in this case. Not sure if thats the cause or not. I do this in the logs quite a bit which leads me to believe that this is the root cause

>  --- SkImageDecoder::Factory returned null

**Comment by spyhunter99** [comment]
this may be related to #615

**Comment by spyhunter99** [comment]
digging deeper, the android bitmap factory only seems to read the first 64 bytes of the image before given up. So i'm guessing that there's something funky with out the image is encoded or it's an android issue. I don't think there's too much i can do about this one.

**Comment by grzesiek2010** [comment]
@spyhunter99 
>  Not sure if thats the cause or not. I do this in the logs quite a bit which leads me to believe that this is the root cause

--- SkImageDecoder::Factory returned null

I can confirm that I can see the same logs.

I've compared those files and those wrong files have `pbf` format in `metadata` table I can't see the same in the metadata table of that one which works well.

**Comment by spyhunter99** [comment]
suggestion, capture one of the tiles from the the mbtiles database that does not work and save it as a separate file, then try to open it with photo editing towards. PBF format is probably not supported by the android image decoder. I believe PBF is the raw open street maps data, points and ways. It may be possible to hack something together with mapsforge to render that data to a image tile but it's probably a bit of work

**Comment by grzesiek2010** [comment]
@spyhunter99 
If I use the correct file (http://geoodk.com/mbtiles_howto.html) I can export one tile to png file and see the result I'm also able to view the image directly in DB Browser:
![dbbrowser1](https://user-images.githubusercontent.com/3276264/27297362-d6768b60-5524-11e7-8f41-d616583bd0c0.png)
if I do the same using `pbf` format it's not possible:
![dbbrowser2](https://user-images.githubusercontent.com/3276264/27297365-d8440d6e-5524-11e7-9386-fdbdf2ab51c5.png)

**Comment by spyhunter99** [comment]
That confirms it then. Pbf outputs are not supported by android bitmap
factory because it is not a bitmap.  Pbf is more of a vector tile format
than an image.  Not to sure what else I can do

**Comment by spyhunter99** [comment]
going to close for now, . pbf support is not trivial.

**Comment by CodeK1988** [comment]
@grzesiek2010 @kingfisherphuoc @spyhunter99 hi mate, has this problem been solved? I migrated from mapsforge-vtm maps and encountered the same problem. best wish.

**Comment by grzesiek2010** [comment]
Hi, @CodeK1988 nothing has changed here and vector (pbf) tiles are still not supported.

**Comment by CodeK1988** [comment]
@grzesiek2010 Thanks for the reply bro.I have re-downloaded the map file. Yes, it is a bitmap map engine that does not support vector map data.

**Comment by CodeK1988** [comment]
But I think it is still possible, but I don’t know how to deal with the logic of pbf decode. Mapbox supports both mbtiles files. But it's not open source and doesn't support full offline support.
