### ISSUE TITLE
kmldocument

### ISSUE THREAD

**Issue by HaniKu** [osmdroid/osmdroid#612]
when im trying read from kml file a got error like "FATAL EXCEPTION: main java.lang.VerifyError: org/osmdroid/bonuspack/kml/KmlDocument "  But it worked right 2 weeks ago.
My code, where im working with kmldocument
` File text = (File) tagPOI.getSelectedItem();
                            kmlDocument = new KmlDocument();
                            Log.v("tralala","som za deklaraciou kmldok");
                            File file = kmlDocument.getDefaultPathForAndroid(text.toString());
                            mKmlOverlay = null;
                        try {
                            putKMLAsync(file);
                        }catch(Exception e){
                        }catch(Error e){
                        }`
Im using osmbonuspack 6.3 and osmdroid 5.6.4
I would greatly appreciate if you could give me a solution. Thank you in advance.

![image](https://user-images.githubusercontent.com/17992073/26838217-cb117720-4adf-11e7-8999-3ab0a9c9c5bc.png)

**Comment by MKergall** [comment]
This is not an osmdroid issue, this is an osmbonuspack one. 
What is the value of the "file" variable? What is the content of your KML file? What is the code of putKMLAsync? No way to help with your input.

**Comment by spyhunter99** [comment]
@HaniKu concur with @MKergall, osmbonuspack issue, please open an issue over there
