### ISSUE TITLE
How can i use EPSG:32632

### ISSUE THREAD

**Issue by Be4r0** [osmdroid/osmdroid#613]
It's possible use EPSG:32632 instead of EPSG:4326 in the map?

**Comment by spyhunter99** [comment]
I'm a bit confused as to what EPSG:32632 actually is. Open Street Maps, osmdroid, Bing, Google and nearly all 2d maps use Web Mercator as a projection and WGS84 for the coordinate system (coordinate to physical places on earth). EPSG:4326 is the same as WGS84 as far as I know, latitude longitude.

Quick answer, no not at the moment. 

Long answer, yes anything is possible. The simplest solution would be to write some kind of conversion method though to go back and forth to WGS84.

**Comment by spyhunter99** [comment]
are you referring to UTM or MGRS coordinates? that's a different deal. https://github.com/Berico-Technologies/Geo-Coordinate-Conversion-Java

**Comment by spyhunter99** [comment]
closing to due lack of other feedback, reopen if needed
