### ISSUE TITLE
Use two Map Views in one Activity

### ISSUE THREAD

**Issue by MrWeezle** [osmdroid/osmdroid#614]
I want to use two Map Fragments, each with a different fragment, side-by-side in an activity. The left map is planned to show an overview over a specific area, the right one zooms in to a specific point.

The problem I'm having is that only the first (left) map fragment is being correctly shown, the second (right) one shows a world map:
![Screenshot](https://cloud.githubusercontent.com/assets/6639017/23069780/fd963c24-f528-11e6-9a48-ddc944208268.png)

Zooming is not working on the right map.

Here is a part of the code I'm using:

    private void initializeMap()
    {       
        MapTileProviderBasic tileProviderOSM = new MapTileProviderBasic(getApplicationContext());
        ITileSource tileSourceOSM = new XYTileSource("OpenFireMap", null, 1, 18, 256, ".png", new String[]{"http://openfiremap.org/hytiles/"});
        tileProviderOSM.setTileSource(tileSourceOSM);
        TilesOverlay tilesOverlayOSM = new TilesOverlay(tileProviderOSM, this.getBaseContext());
        tilesOverlayOSM.setLoadingBackgroundColor(Color.TRANSPARENT);

        OsmFragment frag = (OsmFragment) getFragmentManager().findFragmentById(R.id.osmMap);
        osmMap = frag.getMap();
        osmMap.setMultiTouchControls(true);
        osmMap.getOverlays().add(tilesOverlayOSM);

        MapTileProviderBasic tileProviderOSMDetail = new MapTileProviderBasic(getApplicationContext());
        ITileSource tileSourceOSMDetail = new XYTileSource("OpenFireMap", null, 1, 18, 256, ".png", new String[]{"http://openfiremap.org/hytiles/"});
        tileProviderOSMDetail.setTileSource(tileSourceOSMDetail);
        TilesOverlay tilesOverlayOSMDetail = new TilesOverlay(tileProviderOSMDetail, this.getBaseContext());
        tilesOverlayOSMDetail.setLoadingBackgroundColor(Color.TRANSPARENT);
        
        OsmFragment fragDetail = (OsmFragment) getFragmentManager().findFragmentById(R.id.osmMapDetail);
        osmMapDetail = fragDetail.getMap();
        osmMapDetail.setMultiTouchControls(true);
        osmMapDetail.getOverlays().add(tilesOverlayOSMDetail);
    }

If I change either one of the fragments to a GoogleMaps fragment, the osmdroid map loads correctly.

Any ideas why this is happening and how I can fix it? I'm using the newest osmdroid version from gradle (v5.6.4)

Thanks in advance.

**Comment by spyhunter99** [comment]
There's a preexisting example of this in the sample app, have you look at
this yet?

**Comment by spyhunter99** [comment]
trying to reproduce this issue, does open fire map require some kind key or something?

**Comment by MrWeezle** [comment]
As far as I know you don't need a key for OpenFireMap.

I looked at the sample app, i assume you meant the "Two maps, split screen with mapbox" example? Basically that is what I want, but without linking both maps to the same zoom controls. They should be independent from each other. Especially because the user can choose if he wants to have Google Maps or OSM with OpenFireMap Overlay for both map fragments. So there are four different cases:

- Left Google Maps, Right Google Maps
- Left Google Maps, Right OSM
- Left OSM, Right Google Maps
- Left OSM, Right OSM

**Comment by spyhunter99** [comment]
Yes right sample. To disable syncing the two maps together, just remove those calls in the onzoom and onscroll events.

A few observations. Your sample code uses the default tile overlay plus the open fire map as a secondary overlay. I'm not sure if that was intentional or not.

**Comment by spyhunter99** [comment]
@MrWeezle where are you at with this?

**Comment by MrWeezle** [comment]
I was on vacation, trying it today

**Comment by MrWeezle** [comment]
So I found the solution. The problem was, that the MapView is within a fragment and the fragment is a custom class which had the hardcoded ID's and layouts in it. The solution which worked for me was duplicating the custom fragment class and editing the ID and Layout. Then in MainActivity I had to change the varaible declaration and the cast from OsmFragment to OsmFragmentDetail
Now both maps are showing the wanted content.

**Comment by spyhunter99** [comment]
Glad you found a solution
