### ISSUE TITLE
tiles loading very slow in map view.

### ISSUE THREAD

**Issue by MSSPL-SanjeevSaroj** [osmdroid/osmdroid#617]
hi currently i used this dependency 
 ` compile 'org.osmdroid:osmdroid-android:5.4.1:release@aar'
    compile 'com.github.MKergall:osmbonuspack:5.9'`
after updating this 
   compile 'org.osmdroid:osmdroid-android:5.6.4'
    compile 'com.github.MKergall:osmbonuspack:6.3'
in both case issue is same and after updating setNumberOfTileDownloadThreads() method is not recognise.

**Comment by spyhunter99** [comment]
i'm confused, you have 2 problems then?

slow loading 

you may want to check out the https://github.com/osmdroid/osmdroid/wiki/Changelog and https://github.com/osmdroid/osmdroid/wiki/Upgrade-Guide there were some API changes from 5.4 to 5.6 that are detailed there, specifically the parts about Configuration.getInstance, tile loading, caching and tile selection. Short version: people complained, i made a more flexible solution, then more people complained that it was different.

> unable to resolve the method?

you may want to check out the https://github.com/osmdroid/osmdroid/wiki/Changelog and https://github.com/osmdroid/osmdroid/wiki/Upgrade-Guide there were some API changes from 5.4 to 5.6 that are detailed there. Namely the Configuration class. All adjustable constants where moved there

**Comment by spyhunter99** [comment]
closing due to lack of feedback, reopen if necessary
