### ISSUE TITLE
Geopackage Sample

### ISSUE THREAD

**Issue by melvchan** [osmdroid/osmdroid#618]
I am trying to upload geopackages into the GeopackageSample, but it seems that none of the geopackages I am using will work with the app. Is there a certain format the geopackage needs to be in or a sample geopackage file I could try it out with?

**Comment by spyhunter99** [comment]
ehh not that i know of. only raster tile sources are supported, not vector graphics. does that help?

**Comment by spyhunter99** [comment]
closing due to lack of response. reopen or comment if this is still an issue or if there are further questions
