### ISSUE TITLE
Enhancement: more flexible CacheManager

### ISSUE THREAD

**Issue by monsieurtanuki** [osmdroid/osmdroid#619]
The idea is to give more flexibility to CacheManager.

For the moment the constructor needs a MapView parameter. But:
* not that much from that MapView is needed
* it prevents developers from using CacheManager without a MapView - for instance in an admin dashboard

The idea is to add an alternate constructor that does not need a MapView parameter.

For the moment the features are limited to "performing a task on each tile that match a bounding box / geo points". But I have a simple example where I'm restricted by that behavior:
* I need a not-too-detailed map of Paris
* I also need a detailed map of a district of Paris
* And some day, eventually, I don't need my detailed map on a subset of Paris but I want to keep my big map of Paris

With the current CacheManager, I'm not able to get rid of the district tiles without potentially getting rid of some of the city tiles.
The idea is to develop new constructors for CacheManagerTask, with List<MapTile>s as an input parameter, and to create new methods (based on already existing ones) that return the MapTile's that match a bounding box / geo points.
With that I could easily say:
1. give me the list of the tiles I want to get rid of (bounding box of the district on some zoom levels)
2. give me the list of the tiles I want to keep (bounding box of the city on sometimes the same zoom levels)
3. give me the list of tiles of list 1 that are not in list 2 (using List related methods)
4. perform a CleaningTask on that list

In the process, there will be slight code refactoring, including removing code duplicates (counting the total tiles vs performing a task on each tile).

**Comment by MKergall** [comment]
I think it makes sense. 
Maybe this could also clean the mess around loading based on "a list of geopoints" (pushing tiles list building in a dedicated method). 

I guess @spyhunter99 answer : propose a PR ...

**Comment by spyhunter99** [comment]
100% open to change. Open a PR. This is a community driven product, not a business driven one (to my knowledge, there is no corporate or government sponsorship or funding for osmdroid).
