### ISSUE TITLE
osmdroid Polygon - adding a new point to form a polygon

### ISSUE THREAD

**Issue by abrasaldomark** [osmdroid/osmdroid#621]
I can make a polygon using the `singleTapConfirmedHelper()`. But I still have a problem. How do I remove the line(blue arrow) when adding a fourth point(red circle)? The line does not disappear after I add the fourth point. I hope I explained it well. Thank you.

    `@Override
    public boolean singleTapConfirmedHelper(GeoPoint p) {

    Polygon circle = new Polygon();
    circle.setPoints(Polygon.pointsAsCircle(p, 2.0));
    circle.setFillColor(0x12121212);
    circle.setStrokeColor(Color.RED);
    circle.setStrokeWidth(2);
    map.getOverlays().add(circle);
    circle.setInfoWindow(new 
    BasicInfoWindow(org.osmdroid.bonuspack.R.layout.bonuspack_bubble, 
    map));
    circle.setTitle("Centered on " + p.getLatitude() + "," + 
    p.getLongitude());

    List<GeoPoint> pts = new ArrayList<>();
    pts.add(new GeoPoint(p.getLatitude(), p.getLongitude()));

    Polygon polygon = new Polygon(ctx);
    polygon.setTitle("This is a polygon");
    polygon.setSubDescription(Polygon.class.getCanonicalName());
    polygon.setFillColor(0x12121212);
    polygon.setVisible(true);
    polygon.setStrokeColor(Color.BLACK);
    polygon.setStrokeWidth(4);
    polygon.setInfoWindow(new 
    BasicInfoWindow(R.layout.bonuspack_bubble, map));
    polygon.setPoints(pts);
    map.getOverlays().add(polygon);

    map.invalidate();

    return true;}`

![igzct](https://user-images.githubusercontent.com/13291970/27274712-040ff674-5507-11e7-82c6-ad04cb369212.png)

**Comment by spyhunter99** [comment]
@MKergall any ideas?

**Comment by MKergall** [comment]
Your code is not the code used to create the polygon having the issue.

**Comment by Zishnudev** [comment]
Is the polygon draw possible in Offline map too?

**Comment by MKergall** [comment]
Yes.

**Comment by spyhunter99** [comment]
i would imagine that you need to examine the points that are actually in the polygon. You probably have to call getPoints, then remove the offending point, then call set points agains.
