### ISSUE TITLE
Is there a way to load 4umaps tile source online?

### ISSUE THREAD

**Issue by kingfisherphuoc** [osmdroid/osmdroid#623]
Recently, I check the MOBAC, there are not many tile sources as before. Then I need to use `4uMaps` as the tile source in my App (for offline and online feature).
I want to change the  TileSource to 4uMaps tile source. I can load it offline as below:
`XYTileSource FourUMapsTileSource = new XYTileSource("4uMaps", 0, 18, 256, ".png", new String[]{});`
However, now I want to load 4uMaps online, but I dont know how to do it (the above tileSource only works for offline).

**Comment by spyhunter99** [comment]
nice find, i like the topo shading. looks like it's a standard slippy map format
http://tileserver.4umaps.eu/3/4/2.png

for using in osmdroid use 
`XYTileSource FourUMapsTileSource = new XYTileSource("4uMaps", 0, 18, 256, ".png", new String[]{"http://tileserver.4umaps.eu/"});`

you can then use the cache manager to create offline archives

**Comment by kingfisherphuoc** [comment]
@spyhunter99 nice work! It works, however, it's only in few country. I think I should find another free mapsource instead. Do you know any mapsource which is available in MOBAC (and can load online as well)?
