### ISSUE TITLE
Proposal: Only let tiles from MapTileSqlCacheProvider expire when a network is available

### ISSUE THREAD

**Issue by secaw** [osmdroid/osmdroid#624]
Background: users don't want to have their tiles expire, when there's no possibility to reload them.
Offline maps should always stay available independent from expiration time as long as the user is offline,

Possible solution:
New constructors in MapTileSqlCacheProvider with networkAvailabliltyCheck as parameter analog to MapTileDownloader.
Then if tiles are expired, check if network is available before actually setting them as expired.

**Comment by spyhunter99** [comment]
great idea, the only catch is that it would have to be, expire if the currently selected tile source is network reachable. If you're connected, it doesn't necessarily mean that the tile source is available.

**Comment by monsieurtanuki** [comment]
@spyhunter99: I have a suggestion connected to this one.

In `CacheManager`, add the concepts of
- `isTileToBeDownloaded` - a mix of "tile that's never been downloaded" and "tile that has already been downloaded but is now expired and potentially to be deleted by the next clean up operation"
- `forceLoadTile` - a method that loads a tile, regardless of its presence in the `TileWriter`. Merely a snippet of the current `loadTile` method
With those guys I'm now able to protect the `MapTile` region I cached in the first place.

Does that make sense? If so, I'm ready to develop and deliver by the end of the week.

**Comment by secaw** [comment]
@spyhunter99 : Good point, I'd have to dig a bit deeper, don't quite understand yet how the map tile loading chain including managing expired tiles exactly works...

@monsieurtanuki : Sounds interesting to me. In regards to the CacheManager I would also have two suggestions:
- Add a callback to cleanAreaAsync analog to downloadAreaAsync, so that e.g. we can clean different sources one by one
- Add a callback method 'onTaskCancelled' to CacheManagerCallback, so that e.g. we are able to react on progress dialog dismissals

Should we open another issue for the cache manager topics?

**Comment by monsieurtanuki** [comment]
@secaw:
1. clean up code is in `SqlTileWriter.runCleanupOperation`
2. callbacks can already be added, in branch `osmdroid-parent-5.6.5` (cf. feature/#619)
3. I believe you can already check `CacheManagerTask.onCancelled`, but I'm not sure that answers your `onTaskCancelled` need

Regarding answers 2 and 3, developers only need to code about 3 lines; something like
`final CacheManagerTask task = new CacheManagerTask(...);
task.addCallback(...);
execute(task);`

**Comment by spyhunter99** [comment]
@monsieurtanuki fire at will

**Comment by secaw** [comment]
@monsieurtanuki:

1. Yes, but this is only cleaning, if cache exceeds maximum size. My experience and the topic of the issue is that tiles already start disappearing when they are expired and can not be reloaded even though maximum cache size is not reached. This should not happen. Am I wrong?
2. Ok, I could implement my own task, but I was talking about the possibility of passing a simple interface `CacheManager.CacheManagerCallback` to `cleanAreaAsync` constructors analog to `downloadAreaAsync`
3. Again I'm talking about the interface methods, sorry for being unclear, I still think, an `onTaskCancelled` would be useful.

Any help or clarification is very much appreciated as obviously I'm not as deep in the code as you are...

**Comment by spyhunter99** [comment]
expiration and tile deletion (currently) should open happen the following conditions are true

- the tile is past the expiration date and a new tile is available
- the tile cache is larger than the configuration defined duration (tiles closest or past expiration are deleted first) (this is checked roughly every 5 minutes and at start up)
- clean or purge is called for some reason

the deletion logic is in SqlTileWriter

**Comment by monsieurtanuki** [comment]
@secaw I try to limit the impact of my code, and my personal feeling is that adding variations of `cleanAreaAsync` inside `CacheManager` would dilute/pollute the code (for the record: I didn't code the variations of `downloadAreaAsync`). I don't know if there's a policy on that matter for osmdroid, but I would of course conform.

About `onTaskCancelled` I unfortunately didn't have enough time to think about it as I wanted to deliver fast the other related features.

**Comment by secaw** [comment]
@spyhunter99 : 
Thanks for clarification, that's also what I figured walking through the code. For some reason I noticed a different behavior with longer offline usage, where older tiles seemed to disappear just like that. Thinking about it now, this might have actually been related to automatically reduced max cache size, which is a very good mechanism by the way! Checked again now with a short `mMaximumCachedFileAge` and everything behaves like expected, expired tiles stay visible when offline. Sorry for misleading assumptions...

**Comment by secaw** [comment]
@monsieurtanuki : 
Well thanks for considering, I understand your reservations regarding the number of variations of both `downloadAreaAsync` and possibly `cleanAreaAsync`.
I assume, a new `onTaskCancelled` interface method would also break current implementations of `CacheManager.CacheManagerCallback`.

Still I think both would be useful.

**Comment by shiroyagi** [comment]
I'm also having trouble with tiles being purged from the cache.  It seems just downloading a few tiles when the network becomes available can cause many others to be purged without the user noticing.  In an attempt to maximise the life of tiles offline I have the following:
```
Configuration.getInstance().setExpirationOverrideDuration(1209600000l);//2 weeks in ms,
SqlTileWriter.CLEANUP_ON_START=false;
```
However if I run the cache analyser around 96% are listed as expired and I am losing some a few days old, while others from sources I haven't used for several months are still there.  I need to investigate further.

Presumably it's not a good idea to just replace the oldest tile with a newly downloaded one instead of doing periodic cleanups?

**Comment by spyhunter99** [comment]
It's possible the cache analyzer doesn't take into consideration expiration
overrides.

Tiles being removed can be due to low device storage space and the trim
size

**Comment by secaw** [comment]
@shiroyagi After some more testing, I keep having similar problems. They are completely against the logic of `SqlTileWriter.runCleanupOperation()`, which only kicks in, when available storage is limited anyways - so the problems must be somewhere else, but after digging through `MapTileProviderArray` and `MapTileDownloader`, I wasn't able to track it down. I now have an explicit Offline mode where I remove the `MapTileDownloader` from my `MapTileProviderArray`, which at the moment seems to work.

**Comment by shiroyagi** [comment]
CacheManager.loadTile() sets the expiration override on the Tile and SqlTileWriter.saveFile() puts this in the database for use by runCleanupOperation().  This appears to work and the expiry dates when browsing the cache with the demo app look correct.  The problem seems to be that it is not deleting the old entries.  I didn't check if the database size was bigger than permitted but I notice saveFile() adds a new one before attempting to delete any.

What I find odd is that the [docs](https://developer.android.com/guide/topics/data/data-storage.html#db) say the database is not accessible outside the application and there is no [android:sharedUserId](https://stackoverflow.com/questions/7053809/share-sqlite-database-between-2-android-apps#7935032).  Yet in the demo app I can see tiles in the database both from itself and my app using osmdroid.  I wonder if the access control is partly broken and I can add tiles but not delete them?  In any case it seems I should modify my app not to use the osmdroid/tiles default location.

Having deleted the database and removed the cache overrides, I'll soon be able to tell if the cache is now being cleaned.  Hopefully then with CLEANUP_ON_START=false and a large enough database I will never see recently expired tiles purged.

**Comment by shiroyagi** [comment]
```
/**
* When the cache size exceeds maxCacheSize, tiles will be automatically removed to reach this target. In Mb. Default is 500 Mb.
* @return
*/
long getTileFileSystemCacheTrimBytes();
```
in SqlTileWriter.runCleanupOperation()
`long diff = db_file.length() - Configuration.getInstance().getTileFileSystemCacheMaxBytes();`
shouldn't this be
`long diff = db_file.length() - Configuration.getInstance().getTileFileSystemCacheTrimBytes();`
and vice versa in SqlTileWriter.saveFile()?

This might explain why the old expired tiles were still there, but not why recent tiles are lost (SQLiteDatabase.setMaximumSize() is not called)

**Comment by InI4** [comment]
I apologize for being slightly "off", but this could be connected. Just bash, if useless. 

I use the map in the same region over and over. So I am sure, all tiles are in cache, however when biking around, I often see gray tiles. 

I haven't checked the code path, but can it be, that when a tile from cache is found to be old, it is not drawn, but immediately queued for reload and only drawn after being reloaded?

If so, would it be possible to modify the logic to "draw the old tile while fetching the new one and redraw with new tile after download finished"? This would deliver a much more seemless feeling to the user.

**Comment by monsieurtanuki** [comment]
@InI4 I think it's something else: the expiration is about "if and only if space is needed, then only the oldest tiles will be removed from the cache". It's not about "whenever a tile is expired the end-user deserves to be punished and therefore the tile will be removed from the cache just in case some day we need space".

I have a similar problem now and then though: a gray square where I'm supposed to have a cached tile. My workaround: I tilt my screen portrait-landscape-wise, and the tile appears. I need time to understand exactly in what situations it happens, then I will fix it. But it's definitely going to be dealt with in another issue.

**Comment by secaw** [comment]
@monsieurtanuki The described behavior is actually why I started the issue, though misleadingly suggesting, the reason for this being expired tiles getting deleted at any rate. I also noticed, that when offline, cached map tiles may show up very laggy with some missing and then reappearing very much delayed when moving the map.
I think, the problem lies somewhere in the provider chain and that @InI4 is not that far off with his ideas. I spent some time on this, but couldn't track it down. If you manage to find the cause for this, would be really great.

**Comment by monsieurtanuki** [comment]
Just created issue #630 
I guess we could say that #624 would be the "SQL cache" part of the cache issue, and #630 would be the "memory cache" part.

**Comment by shiroyagi** [comment]
I've addressed the issue I mentioned above on #631.  When testing I noticed that a purge of the cache would remove nearly all the tiles going way beyond the trim size.  This was because the tile size estimate of 4000bytes was significantly too small in some cases.  It now computes the mean size on first use, I think it's worth the second or so to count the tiles.

**Comment by spyhunter99** [comment]
@secaw is this still an issue?

**Comment by spyhunter99** [comment]
@secaw i just committed some code, perhaps it will help. A slightly better solution would be to support a `map.setUseDataConnection()` listener type of thing so that the tile writer can listen for these events and thus auto set this stuff.

**Comment by secaw** [comment]
@spyhunter99 Thanks for getting back on this one. As far as I remember it became clear that the observed behaviour with missing tiles was a bug that was fixed somewhere along the lines above of this issue. Will have a look at your additional enhancement with tests by tomorrow.

**Comment by spyhunter99** [comment]
note to future self, the changes for override cache expiration timestamp was the "fix" for this issue. An alternate mechanism of wiring in the network connectivity check within the SqlTileWriter was written but it requires additional considerations or other tile providers (maps forge, geopackage, etc).
