### ISSUE TITLE
Rotation Listener not working

### ISSUE THREAD

**Issue by aritrabasu104** [osmdroid/osmdroid#628]
Implemented RotationGestureDetector.RotationListener, but the onRotate is not getting called.
Other challenge is to rotate the compass according to map rotaion..any idea how to do it?

**Comment by spyhunter99** [comment]
Interesting. Never tried to use it.  I've always used the map events listener then checked the rotation then.  See the heading, compass up sample

**Comment by spyhunter99** [comment]
Looking at the code, the RotationGestureOverlay sends the "hey someone touched the screen" message to the RotationGestureDetector, which calculates the rotation angle, then sets the map orientation.

**Comment by spyhunter99** [comment]
For the compass overlay, override drawCompass and figure out how much of a rotation to give the compass. Grab the code from SampleHeadingCompassUp ~line 210 for the calculation

**Comment by spyhunter99** [comment]
closing due to lack of response, reopen if needed. javadocs updated
