### ISSUE TITLE
getBoundingBox.getLatitude/getLongitude methods return wrong values..

### ISSUE THREAD

**Issue by aritrabasu104** [osmdroid/osmdroid#629]
getBoundingBox.getLonWest and getBoundingBox.getLonEast returns value of -180 ...getlat methods also returning some wrong value(88.xxx)... Do I need to put some initialization check?

**Comment by spyhunter99** [comment]
Get bonding box returns the west most and east most on screen coordinates.
If the pole or date line is on screen or you are zoomed out to the point
where the map warps,  you may end up with strange values.

**Comment by aritrabasu104** [comment]
"If the pole or date line is on screen "-what do u mean?

**Comment by spyhunter99** [comment]
like if you are at zoom=0 and the globe repeats multiple times. The map is
repeated (multiple maps) and wrapped (as you pan, it just fills the void
with more maps).

**Comment by aritrabasu104** [comment]
its occurring when laying out the map for the first time..i am setting the initial zoom level at 16

**Comment by MKergall** [comment]
Known issue, mapview bounding box not available in oncreate. You must wait.

**Comment by aritrabasu104** [comment]
Actually this was happening on onResume as well

**Comment by MKergall** [comment]
workaround: 


```
//--- Stuff for setting the mapview on a box at startup:

BoundingBox mInitialBoundingBox = null;
  
void setInitialViewOn(BoundingBox bb) {
  if (map.getScreenRect(null).height() == 0) {
    mInitialBoundingBox = bb;
    map.addOnFirstLayoutListener(this);
  } else
    map.zoomToBoundingBox(bb, false);
}

```
