### ISSUE TITLE
Polygon title inside the polygon at center

### ISSUE THREAD

**Issue by girimavin** [osmdroid/osmdroid#632]
Aim:Hi iam trying to display the polygon title(textview) inside the polygon .verified lot of tutorials and stackovrlfws.

Method():
GeoPoint point = (GeoPoint) item.getPoint();
            Point markerBottomCenterCoords = new Point();
mapView.getProjection().toPixels(point, markerBottomCenterCoords);

in onPolygon() method i initialaized the itemaizedoverlay . in itemaized overlay i written canvas.drawText(item.gettitle(),markerBottomCenterCoords.x,markerBottomCenterCoords.y,paint);
![screenshot_2017-07-18-17-04-20-740_info rsr plotavailability](https://user-images.githubusercontent.com/9081463/28315258-55bef96c-6bdb-11e7-80f6-0858d39aec94.png)

Result();displaying the  title at corners instead of polygons center. is it possible to display center of the polygon please need quick response i strucked at peaks!!!!!!!

**Comment by MKergall** [comment]
Unclear what your item.getPoint() goes from. 
Same question for onPolygon(). 

If you want to display something at the center of a polygon, you must compute the center of this polygon. 
Either its center of gravity (sum of coords/n), or the center of its bounding box.

**Comment by girimavin** [comment]
yep your correct i done thank you.. i am getting the polygon by (item.getPoint()).i finally resolved it . but iam unable to fix the osmMap zoom level. In my code on Activity onCreate() method  i initialaise  osmMapView.setBuiltInZoomControls(true);
        osmMapView.setMultiTouchControls(true);
 osmMapView.setMinZoomLevel(18);osmMapView.setMinZoomLevel(12); if i click on zoomout  button continuesly  itis zooming out instead of stop at minimum zoom level 12...how can i resolve it! is there any zoom controlling methods i have refer osm but i didnt find any solution!

**Comment by spyhunter99** [comment]
@girimavin this could be the infamous issue related to setting the map center/zoom level in onCreate. In short, it's too soon. Adding a delay or using the onFirstLayout listener should fix it it

**Comment by girimavin** [comment]
@spyhunter99 yeah

**Comment by spyhunter99** [comment]
closing this, looks like it was resolved. reopen if needed

**Comment by jairodealmeida** [comment]
Is possible calculate from Path
Use this
```java
RectF bounds = new RectF();
			mPath.computeBounds(bounds, false); // fills rect with bounds
			PointF center = new PointF((bounds.left + bounds.right) / 2,
					(bounds.top + bounds.bottom) / 2);
```
