### ISSUE TITLE
Extending the zoom approximation feature, especially in offline mode

### ISSUE THREAD

**Issue by monsieurtanuki** [osmdroid/osmdroid#634]
How does the zoom work right now:
* the map you display is in the memory cache
* during the zoom-in-pinch-gesture a scaled version of the tiles in the memory cache is computed in order to give the zoom feeling
* once the zoom-in is over, the scaled version of the tiles is displayed, to be overwritten by the regular version of the tiles at the new zoom level

Imagine that you're in offline mode, that you have tiles for zoom level L but no tiles for zoom level L+1:
* once the zoom-in is over, you watch the scaled version of the tiles of zoom level L. So far so good: that's the best you can do.
* but if you tilt your phone landscape-portrait-wise the map looks now empty, because the memory cache has been cleared (it's a new `Activity`) and the scaled versions of the tiles haven't been computed by the zoom-in process (you're already at level L+1) => that's sad
* and if you don't tilt your phone but just explore on level L+1 the map beyond the initial level L region, the tiles are not there and look grey => that's sad too

The idea is to improve the user experience by displaying more often scaled approximations:
* not only computed during the zoom pinch gesture
* to be of course overwritten by downloaded tiles when available

That will definitely improve the user experience, especially in offline mode.

It looks like:
* creating a new class that extends `MapTileProviderBase`
* adding it to `MapTileProviderBasic`

I'm about to develop it. Any suggestion is welcomed ;)

**Comment by MKergall** [comment]
My suggestion is: Yes! 

It could be a step toward another great improvement: ability to set "floating point" zoom level instead of integer. Meaning that at intermediate zoom levels, all tiles displayed will have to be scaled.

**Comment by monsieurtanuki** [comment]
Thank you for your "Yes!" ;)

Nevertheless I don't think my feature has a strong link with the floating point zoom.
In my feature, the idea is something like: if I don't have any data for tile z/x/y, I can compute the data as an approximation from zoom z-1.
The goal is to create a new tile source, similar to the other tile sources ("give me the z/x/y tile!")

In the floating point zoom mode, it's more something like: I get 256x256 bitmaps from cache and I will have to display them on 256x256 (included) to 512x512 (excluded) rects on screen according to the floating point zoom.
The goal is to display tiles from the standard 256x256 sources but with magnifing factor 1 to 1.999.

I'm not even sure that floating point zoom is such a good thing regarding user experience.
I think it will depend on the floatability ;)
Would it be good to display a 1.999 magnified tile? I don't think so: we would be better off displaying the tile of the next zoom level.
Therefore we would need to set zoom quantum, or let the app developer set it as a parameter between 0 (excluded) and 1 (included). Today obviously the quantum is 1. A quantum of 0.5 would make it possible to display zoom level 14.5. Could be nice. It's worth trying and developing it.

**Comment by MKergall** [comment]
"Would it be good to display a 1.999 magnified tile? I don't think so: we would be better off displaying the tile of the next zoom level."
=> Effectively. The right solution should be something like: in [14 - 14.5[, magnify from zoom 14 tiles, and in [14.5 - 15.0[, minify from zoom 15 tiles. 

For user experience: the goal is to have fluid zoom by fingers. So quantum will not be appropriate.

**Comment by monsieurtanuki** [comment]
My remarks:
* Oh I meant to have the same fluid zoom by fingers, but instead of going back to 14 if you moved up to 14.6 and released (the current behavior), go back to the new step 14.5 (level 14 magnified by 1.5 or something like that)
* What I meant with quantum is: there's an infinity of values between 14 and 15, and we need to decide how many floating steps it is relevant to be able to display - {14.5} ? {14.33, 14.66} ?
* Hey! All those messages should belong to another thread dedicated to floating point zoom ;)

**Comment by monsieurtanuki** [comment]
Closing the issue for the following reasons:
* code merged
* floating point zoom discussion continued into #640
* just created issue #646: "New feature: MapTileApproximater with several sources"
