### ISSUE TITLE
Adding a layout as icon

### ISSUE THREAD

**Issue by aritrabasu104** [osmdroid/osmdroid#635]
I was trying to use a relative layout as marker icon..Any idea how it can be done?

**Comment by MKergall** [comment]
You can't. 
What you can do is set your layout as the InfoWindow of your Marker, and then open this InfoWindow. This will give you the same result. 
See https://github.com/MKergall/osmbonuspack/wiki/Tutorial_2#9-creating-your-own-bubble-layout
