### ISSUE TITLE
Marker Vanishes after changing position

### ISSUE THREAD

**Issue by aritrabasu104** [osmdroid/osmdroid#636]
I am using a handler to simulate icon animation.
When ever there is a change in position I am calling marker.setposition to change the position.. but the marker disappears after call to mapview.invalidate

**Comment by aritrabasu104** [comment]
@MKergall can this happen due to repititive map.invalidate?

**Comment by MKergall** [comment]
No idea. Never seen that. Provide relevant code.

**Comment by aritrabasu104** [comment]
This is being executed in ui thread
@Override
        public void run() {
            //initialize handler for animation
            Handler handler = new Handler();
            long elapsed = SystemClock.uptimeMillis() - start;
            double t = interpolator.getInterpolation((float) elapsed / duration);
            double lng = t * toPosition.getLongitude() + (1 - t) * fromPosition.getLongitude();
            double lat = t * toPosition.getLatitude() + (1 - t) * fromPosition.getLatitude();
            double angle=t *toAngle +(1-t)*fromAngle;
            Log.d("MarkerPositionAnimator","from "+fromPosition.getLongitude()+" to "+toPosition.getLongitude()
                    +" current "+lng);
            if(lat!=fromPosition.getLatitude()||lng!=fromPosition.getLongitude()||
                    Math.abs(angle-fromAngle)>ApplicationConstants.ANGLE_MIN_DIFF_FOR_BUS_ICON_ANIMATE)
            {
                marker.setPosition(new GeoPoint(lat, lng));
                marker.setRotation((float) angle + ApplicationConstants.ANGLE_OFFSET_FOR_BUS_ICON);
                mMapView.postInvalidate();
            }
            if (t < 1.0) {
                handler.postDelayed(this, ApplicationConstants.TIME_INTERVAL_IN_MILI_ICON_ANIMATE);
            }

        }

**Comment by aritrabasu104** [comment]
@MKergall Can we change a marker position after drawing it and then invalidate to see effect?

**Comment by MKergall** [comment]
Yes of course. If you set your marker as draggable you can easily see that. Can be seen in Osmnavigator app.

**Comment by spyhunter99** [comment]
can't say i've seen this behavior before. I'm catching up some of the old tickets today but i'll have a look at this next

**Comment by spyhunter99** [comment]
i just pushed a new sample, which uses a timer task to update the marker's location. It's based heavily off of the ISS tracker example which plots in real time, the international space station. There's no invalidates going on but there is a lot of trickery related to how android allows or disallows certain actions from a background thread. It's probably not the best way to do but it does work

**Comment by aritrabasu104** [comment]
I was having trouble with some bugs
