### ISSUE TITLE
Is there a way to disable caching?

### ISSUE THREAD

**Issue by goransleko** [osmdroid/osmdroid#638]
I want to use only mobile data, without downloading and saving tiles on phone storage. I don't want to set the cache size to zero or clear it either, but disable it. How can I achieve that?

**Comment by spyhunter99** [comment]
You should be able to set a custom tile provider chain that only includes
the downloader

**Comment by goransleko** [comment]
I see, maybe I'm gonna try that then. Do you think caching can slow down speed of app?

**Comment by goransleko** [comment]
Now I'm trying to implement my custom MapTileDownloader, and if I remove the following code to disable saving into cache, the map won't show anymore. Any help appreciated.

               
                if (mFilesystemCache != null) {
                    mFilesystemCache.saveFile(tileSource, tile, byteStream);
                    byteStream.reset();
                }

**Comment by spyhunter99** [comment]
Caching slow down the app? no that would defeat the purpose. it's there to speed up the map

**Comment by spyhunter99** [comment]
any updates?

**Comment by spyhunter99** [comment]
i don't think this is currently possible with the setup we have for downloading caching then loading and displaying the tiles. sorry

**Comment by fariz-siracli** [comment]
Hi. How can i disable cach-ing for only one Overlay? In my cas it is traffic olverlay which should be always fresh.

**Comment by monsieurtanuki** [comment]
@fariz-siracli cf. #1044
