### ISSUE TITLE
MapView.OnClickListener is not getting called

### ISSUE THREAD

**Issue by aritrabasu104** [osmdroid/osmdroid#641]
@spyhunter99  Any idea why this might happen?

**Comment by aritrabasu104** [comment]
@MKergall 
how do i build the examples
 https://github.com/osmdroid/osmdroid/tree/master/OpenStreetMapViewer

**Comment by aritrabasu104** [comment]
@spyhunter99  can this happen because of markerOverlay on top of mapView

**Comment by spyhunter99** [comment]
i think the mapview implements on click listener. if you need to trap it, extend MapView then override the function call. the alternative is to create a transparent full screen view that is on top of the map. Then trap the tap events there, otherwise pass it to the map view

**Comment by aritrabasu104** [comment]
The overridden method onClick is not getting called..

**Comment by monsieurtanuki** [comment]
Something like that?

> mapView.getOverlays().add(new MapEventsOverlay(new MapEventsReceiver() {
	@Override
	public boolean singleTapConfirmedHelper(GeoPoint p) {
		Log.e("MapView", "normal click");
		return true;
	}
	@Override
	public boolean longPressHelper(GeoPoint p) {
		Log.e("MapView", "long click");
		return false;
	}
}));

**Comment by aritrabasu104** [comment]
something like 
mapview.setonclicklistener(this);
where this implements View.OnClickListener.

**Comment by aritrabasu104** [comment]
@monsieurtanuki Your method is working fine, but i dont understand why my approach is not..

**Comment by aritrabasu104** [comment]
Also whats the best approach to detect map dragging?

**Comment by spyhunter99** [comment]
Dragging the map?  Map event listener.  Dragging an icon?  I think marker supports that

**Comment by aritrabasu104** [comment]
MapEventReceiver only has single and double tap

**Comment by amogh-jrules** [comment]
> Something like that?
> 
> > mapView.getOverlays().add(new MapEventsOverlay(new MapEventsReceiver() {
> > @override
> > public boolean singleTapConfirmedHelper(GeoPoint p) {
> > Log.e("MapView", "normal click");
> > return true;
> > }
> > @override
> > public boolean longPressHelper(GeoPoint p) {
> > Log.e("MapView", "long click");
> > return false;
> > }
> > }));

Thanks this helped solve an issue that I was working for long :)

**Comment by abdeldjalilfl** [comment]
> Something like that?
> 
> > mapView.getOverlays().add(new MapEventsOverlay(new MapEventsReceiver() {
> > @override
> > public boolean singleTapConfirmedHelper(GeoPoint p) {
> > Log.e("MapView", "normal click");
> > return true;
> > }
> > @override
> > public boolean longPressHelper(GeoPoint p) {
> > Log.e("MapView", "long click");
> > return false;
> > }
> > }));

But this make conflict with marker click listener (click marker included in the maps listener)

**Comment by monsieurtanuki** [comment]
It depends on where you add the code: before or after you added the markers.
