### ISSUE TITLE
Osmdroid MapView always displays downloaded mbtile

### ISSUE THREAD

**Issue by kingfisherphuoc** [osmdroid/osmdroid#644]
I want to display the downloaded map tiles only when there's no internet connection. This is the code I tried:
```java
if (NetworkUtils.isNetworkAvailable(container.getContext())) {
            mapView.setUseDataConnection(true);
        } else {
            mapView.setUseDataConnection(false);
            mapView.setTileSource(FourUMapsTileSource);
        }
```
However, the downloaded map is always displayed even when there's network connection (see the image below):
![device-2017-07-28-095041](https://user-images.githubusercontent.com/962484/28700547-9e7e4724-737a-11e7-9066-09e7200a93f2.png)
Do you have any idea? @spyhunter99

**Comment by monsieurtanuki** [comment]
Tip: tilt your smartphone portrait-landscape-wise, it will clear the memory cache.
Does it show now what you expect?

**Comment by spyhunter99** [comment]
looks like you have multiple tile sources involved here. i would suggest changing/refreshing the tile provider based on whatever triggers you need. This would force a reload of the tiles overlay based on whatever the tile provider chain is. In your case, when the device is offline, only provide the sql cache and archive tile providers (if necessary) and omit the map tile downloader. Then online, change it to the default instance and update any tile sources as needed

**Comment by kingfisherphuoc** [comment]
yes, I used mbtiles of `4Umaps` for offline map and default tile source for online map:
```
        if (NetworkUtils.isNetworkAvailable(context)) {
            Timber.e("Online tile source: " + onlineTileSourceBase.name());
            mapView.setUseDataConnection(true);
            mapView.setTileSource(onlineTileSourceBase);
        } else {
            mapView.setUseDataConnection(false);
            mapView.setTileSource(FourUMapsTileSource);
            Timber.e("Offline tile source");
        }
```
how to do something like ` would suggest changing/refreshing the tile provider based on whatever triggers you need`? Can you give me an example?
@spyhunter99

**Comment by spyhunter99** [comment]
you should be able to do something like this

````
mMapView.setTileProvider(new MapTileProviderBasic(getContext()));
````

this should reset it to the defaults and should bounce all the tile caches and whatnot

**Comment by spyhunter99** [comment]
rereading the original question, you want to create a custom MapTileProviderArray object whenever the network connectivity changes, that will remove the MapTileDownloader when offline, then readded it when it is online

**Comment by spyhunter99** [comment]
answer/workaround posted, reopen if this is still a problem
