### ISSUE TITLE
Not able to define zoom speed manually.

### ISSUE THREAD

**Issue by fightaadeshfight** [osmdroid/osmdroid#650]
I want to get an effect of a gradual zooming to a particular marker. But in setZoom(int zoomlevel) 
the speed is predefined as 500ms. 

Is there a way i can do this?

**Comment by monsieurtanuki** [comment]
`MapController.setZoom(int zoomLevel)` calls `MapView.setZoomLevel(int zoomLevel)` that calls `getController().animateTo(geoPoint)`, therefore the duration is supposed to be `MapViewConstants.ANIMATION_DURATION_DEFAULT` (1000 ms).
Since you mentioned 500ms, are we talking about the same animation duration?

**Comment by fightaadeshfight** [comment]
What i want is to set a duration programatically like 5000 ms or something else.

**Comment by spyhunter99** [comment]
I gotcha.  If you are feeling ambitious, here's how I would do it.

Add methods to Iconfigurationprovider and default configuration provider to
slow for assisting the default setting.  Then alter map view controller to
slow for zooming using a specific timing value.

Then open a pr. Or wait,  I can look at this this weekend probably

**Comment by spyhunter99** [comment]
@fightaadeshfight is your requirement to be able to override the default zoom animation setting (used for all zoom events) or do you also need to be able to set the animation speed on a per zoom event basis?

**Comment by fightaadeshfight** [comment]
I want to be able to set the zoom speed on per zoom event basis. Right not the map will zoom in a flash  to a point that is set as the center. What i want is the zoom event to proceed gradually towards a point.

**Comment by spyhunter99** [comment]
ok so the best i can do is this

Override the double tap to zoom in, global setting
Override the built in on screen zoom controls, global setting
Overriding a custom button's zoom in speed control, doable on a per event basis

**Comment by spyhunter99** [comment]
@fightaadeshfight the PR is ready to merge. I'm not sure what else i can do, do you want to review it?

**Comment by fightaadeshfight** [comment]
Can't i use this before the next release?
