### ISSUE TITLE
Create pulse(force field kind of circle) around a marker

### ISSUE THREAD

**Issue by aritrabasu104** [osmdroid/osmdroid#653]
Is there a way to do so?@MKergall @spyhunter99 ?

**Comment by cfsbhawkins** [comment]
There are some samples, in the sample app on how to add animations to map markers, you would basically be drawing a growing circle around the icon every time the on draw is called

**Comment by cfsbhawkins** [comment]
Start with the myuseroverlay icon, you can see how a circle is drawn based on GPS accuracy, you could use the same logic of the animations to grow and shrink that circle

**Comment by aritrabasu104** [comment]
@cfsbhawkins about that, can u tell me why the map is not getting loaded in sample app?

**Comment by cfsbhawkins** [comment]
Animation Example:
https://github.com/osmdroid/osmdroid/commit/0ebc8db8d4fdbf1ea5d3f5f3c0c54031aa3b8b88

Circle Drawing around a marker:
https://github.com/osmdroid/osmdroid/blob/master/osmdroid-android/src/main/java/org/osmdroid/views/overlay/mylocation/MyLocationNewOverlay.java

**Comment by spyhunter99** [comment]
do you need an animated ring or just a static ring?

**Comment by spyhunter99** [comment]
Polygon also as has helper static methods to create a circle around a point.
