### ISSUE TITLE
Opentopomap max zoom is lower than actual max zoom

### ISSUE THREAD

**Issue by brunetton** [osmdroid/osmdroid#654]
Hi, I just realized that tiles on opentopomap.org are available at a zoom 17, but this map conf in OsmoDroid is limited to 15 (or 16, I dont remember).
So I edited it and changed the max zoom number and now I can view more accurates tiles.

I cloned the repo, done a grep on "a.tiles.opentopo" but didn't find the conf file to change and make a PR. Sorry !

**Comment by spyhunter99** [comment]
I think it's in tilesourcefactory

**Comment by spyhunter99** [comment]
@brunetton open topo map source is currently set to a max zoom of 19 via tile source factory. Can you confirm what version of osmdroid you're setting this issue on?

**Comment by spyhunter99** [comment]
closing as not an issue
