### ISSUE TITLE
Detect dragging action on mapview?

### ISSUE THREAD

**Issue by aritrabasu104** [osmdroid/osmdroid#655]
As MapEventReceiver only has two methods - OnSingleTap and OnLongPress, how do i detect dragging in map?

**Comment by spyhunter99** [comment]
https://github.com/osmdroid/osmdroid/blob/master/OpenStreetMapViewer/src/main/java/org/osmdroid/samplefragments/events/SampleMapEventListener.java

Did you see this?

**Comment by aritrabasu104** [comment]
not working
mMapView.setMapListener(new MapListener() {
            @Override
            public boolean onScroll(ScrollEvent event) {
                Log.i("OnScroll", "");
                return true;
            }

            @Override
            public boolean onZoom(ZoomEvent event) {
                Log.i("onZoom","");
                return true;
            }
        });

**Comment by spyhunter99** [comment]
It works on the demo app, download and test that on your device,  is under
msp events

**Comment by pasniak** [comment]
I receive stream of position updates, which I would like to suspend when user _starts_ scrolling the map and resume when she _stops_ scrolling. The MapListener seems to fire identical events when scrolling.  Is there nothing except suspending when scrolling occurs and posting some delayed action "she must have stopped dragging by now (ex: after 5s) so resume updates" ?

**Comment by spyhunter99** [comment]
@pasniak have you tried overriding onTouch?

**Comment by pasniak** [comment]
Thanks! That worked

**Comment by NathanFallet** [comment]
@pasniak @spyhunter99 Can you give an example on how you override `onTouch`? There is no `onTouch` in the `MapListener`, do I need to use `setOnTouchListener` from the `MapView`? Or override the `onTouch` of my `Activity`?

**Comment by spyhunter99** [comment]
hmm i'm not sure, but `do I need to use setOnTouchListener from the MapView` is probably the right answer.
