### ISSUE TITLE
As I put a double value in new OverlayItem

### ISSUE THREAD

**Issue by MauricioCr** [osmdroid/osmdroid#656]
Hi!

As I put a double value in new OverlayItem?

Example:

```
Double dist = 213.5833;
OverlayItem marker= new OverlayItem("String 1", dist, point);
```

But in the marker this value is 0.00

Then:
```
Double dist = 213.5833;
OverlayItem marker= new OverlayItem("String 1", String.ValueOf(dist), point);
```

and value is 0.00 too

How can I solve that?

**Comment by spyhunter99** [comment]
@MauricioCr 
did you look at the javadoc for this?

         /**
	 * @param aTitle
	 *            this should be <b>singleLine</b> (no <code>'\n'</code> )
	 * @param aSnippet
	 *            a <b>multiLine</b> description ( <code>'\n'</code> possible)
	 * @param aGeoPoint
	 */
	public OverlayItem(final String aTitle, final String aSnippet, final IGeoPoint aGeoPoint)

You are setting the description for the icon to whatever the `dist`'s value is. The description only comes into play when the user clicks/taps on an icon. What you can do is extend OverlayItem to include whatever you need.

**Comment by spyhunter99** [comment]
closing to due no feedback, reopen if this is still a problem
