### ISSUE TITLE
Better behavior during zoom gesture

### ISSUE THREAD

**Issue by monsieurtanuki** [osmdroid/osmdroid#661]
From #640, comment by @MKergall:

> @monsieurtanuki OK, understood.
I tested floating zoom to check how it behave with an opened InfoWindow on a Marker: the previous "bad" behaviour is still there:
o the marker is scaled during zoom gesture, and sticks at the right position
o the infowindow is not scaled, but doesn't stick at expected position
o Then, when gesture ends, everything is drawn correctly.
I imagine the issue is that display during zoom gesture still relies on Android views animations. Is it feasible to get rid of that, and call onDraw during zoom gesture?

**Comment by secaw** [comment]
@MKergall 

> and call onDraw during zoom gesture?

Wouldn't this be pretty costly CPU wise? Osmdroid already consumes quite some power when moving the map extensively, especially when having a couple of offline maps on top of the online / cached source plus maybe a map layer like openSeaMaps (e.g. in my use case). I felt that #630 already brought quite some improvement with CPU load optimisation and would be careful to again add more load like constantly calling onDraw when zooming, but maybe I'm wrong..?

**Comment by spyhunter99** [comment]
@monsieurtanuki #640 is passing now, do you want me to merge or wait until this is resolved?

**Comment by monsieurtanuki** [comment]
@spyhunter99 Please merge now.

**Comment by MKergall** [comment]
@monsieurtanuki In fact, in my test, floating zoom was not activated. 
Just calling this is not enough: 
`this.mOsmv.setMultiTouchControls(true);
`
How should we proceed to activate it?

**Comment by monsieurtanuki** [comment]
You don't have to activate it.
You just have to:
* use the latest version of osmdroid
* use `org.osmdroid.views.MapView` (which now has method `double setZoomLevel(final double aZoomLevel)`)

**Comment by MKergall** [comment]
I use your fork, and the MapView. 
The point is that I don't call setZoomLevel: I want to use floating zoom when zooming by pinching, so I just call setMultiTouchControls(true) - probably as most osmdroid users do.

**Comment by monsieurtanuki** [comment]
@MKergall I mentioned `setZoomLevel` just as a quick check about "is it the old `int` version" or "is it the new `double` version".

If you run the "OSMDroid Sample map (Start here)" demo, the pinch mode is activated and it's a good opportunity to watch the `double` zoom. Could you check that demo?

**Comment by MKergall** [comment]
You are right, my mistake: my test was not based on the latest osmdroid, and double setZoomLevel was not present!
With osmdroid properly updated, just calling setMultiTouchControls(true), it's perfect. 

(sorry for low reactivity - reduced Internet access during holidays :-)

**Comment by spyhunter99** [comment]
@MKergall @monsieurtanuki  is this good to close now?

**Comment by MKergall** [comment]
No: the "bad" behaviour is still there. 
But this is a minor point, possibly tricky to improve. This should not block releasing a V6.0.

**Comment by monsieurtanuki** [comment]
@MKergall I agree with you.

What would be the target behavior during zoom pinch gesture? Do we agree on this:
* only the map tiles get bigger / smaller
* all the other displayed geo items keep the same size and move according to the zoom and map center change

**Comment by MKergall** [comment]
The main driver could be feasibility. 

Ideally, if everything was drawn according to "current" zoom, it would be fine (meaning that during zoom pinch, markers keep their normal size, polylines size is updated). 

But if this introduces glitches / non-fluid zoom, then an alternative could be to have all geo items getting bigger/smaller, and just have InfoWindow positions refreshed. 

I noticed that ScaleBarOverlay has a nice support of zoom pinch. I found that in its draw method:
if (mapView.isAnimating()) {
			return;
		}
Don't understand how this alone can be enough.

**Comment by monsieurtanuki** [comment]
I don't think the implementation will be very problematic, nor that it will be an issue regarding performances.
If you have a look at the "More Samples / Data / Itemized overlay at Scale" demo, you'll see that the markers already look ok (they scroll and they keep the same size).
The problem seems to be more specifically with the marker with focus, cf. "More Samples / Data / Itemized overlay w/ focus": only the marker with focus (and its info) looks "different", but the other marker looks ok.

**Comment by monsieurtanuki** [comment]
@MKergall Should be fixed by #800. Could you give it a try?
>If you have a look at the "More Samples / Data / Itemized overlay at Scale" demo, you'll see that the markers already look ok (they scroll and they keep the same size).
The problem seems to be more specifically with the marker with focus, cf. "More Samples / Data / Itemized overlay w/ focus": only the marker with focus (and its info) looks "different", but the other marker looks ok.

Now even the marker with focus looks ok.

**Comment by MKergall** [comment]
This one can be considered as closed now. 
#865 is something new (even if caused by the correction of this one).
