### ISSUE TITLE
New demo, Location bookmarking

### ISSUE THREAD

**Issue by spyhunter99** [osmdroid/osmdroid#662]
would be super helpful if we could have some kind of gmaps equivalent, star this location type of thing.

**Comment by monsieurtanuki** [comment]
I've been working on this kind of app for months. About adding, updating and deleting locations (or "Point Of Interest" / POI)
Among the issues:
* what would the location sources be?
* what is the id of a location?

Is there a unique and permanent OSM id that we could reuse? And then, how do we integrate data not coming from OSM?

If it's just for a demo, will it be something like a world map with a dozen city markers, and when you click on one of them you have the possibility to edit it (like, "add to favorites") and the marker becomes a star?

**Comment by spyhunter99** [comment]
mmm so there's a few things we need.

- ways to bookmark new points
  - [ ] bookmark current location (via menu or button)
  - [ ] bookmark map center (via menu or button)
  - [ ] bookmark map a point on the map via long press
- data model
  - lat/lon, user specified category (star, heart, etc)
  - physical mailing address
  - unique id, probably a database auto inc
  - business hours/phone number(s) might also be helpful
- storage/retrieval
  - [ ] some way to store these bookmarks
  - [ ] some way to query based on bounds
  - [ ] some way to query based on keywords
  - [ ] some way to just get everything from the database with offset/limits
- extras
  - [ ] import addresses from the device's address book and reverse geocode them to lat/lon. This will probably have to wait for #660 
   - [ ] when bookmarking a new point, attempt to cross reference it from the POI database from #660 to autopopulate the data model as much as possible.

**Comment by spyhunter99** [comment]
`Geocoder.getFromLocationName` requires internet connectivity. #660 is for offline support
