### ISSUE TITLE
Feature request: zoomOutToBoundingBox

### ISSUE THREAD

**Issue by rostopira** [osmdroid/osmdroid#669]
I need to show all markers (less than 10) at once. It works, when zoom is less than required with following code

```
val bb = BoundingBox.fromGeoPoints(points)
map.zoomToBoundingBox(bb, false)
```

But obviously fails, if zoom is more than required.

**Comment by spyhunter99** [comment]
hmm zoomToBoundingBox should handle this case. can you wipe up a small example to reproduce this issue?

**Comment by rostopira** [comment]
I've recompiled project... And it's working ¯\_(ツ)_/¯ Sorry
