### ISSUE TITLE
Tile loading bug: Wrong tile source for certain tiles (but geographically correct)

### ISSUE THREAD

**Issue by garvankeeley** [osmdroid/osmdroid#67]
Cloned from: https://github.com/mozilla/MozStumbler/issues/759

For a few months I have been seeing the behaviour in the screenshot with 100% consistency. Certain tiles were loading incorrectly. At a given zoom the same tiles would always render in the OSM style, instead of the MapBox provider style that is specified as a tile source. 

To fix this problem, I had to delete /sdcard/osmdroid/*sqlite.

Things that did not fix this:
* uninstalling the app
* deleting /sdcard/osmdroid/tiles

Since deleting the sqlite files, those files have not reappeared. The MozStumbler app don't use sql-backed tiles.

Potentially, this is not a bug at all, and the MozStumbler app switched its OSMDroid source around in such a way that triggered this (I don't know the history of the apps OSMDroid use).

![8e3c4cc6-1f27-11e4-8dc7-8ef17ff4f20c](https://cloud.githubusercontent.com/assets/5495083/4237205/fe0486da-39cc-11e4-8a77-1306c4ce0ad7.png)

**Comment by neilboyd** [comment]
This looks the same as [old issue 298](https://code.google.com/p/osmdroid/issues/detail?id=298). I'm not sure what the current status is.

**Comment by spyhunter99** [comment]
did you try invalidating after changing tile sources?

**Comment by garvankeeley** [comment]
i'll ping @crankycoder, he might recall. In the month after this bug was filed we made many changes to our OSMDroid usage and the bug no longer occurred. 
Most likely this got worked around when the app switched at that time to using a non-shared directory for the tile source.

**Comment by spyhunter99** [comment]
gonna close this for now. reopen if it reoccurs (hopefully with instructions on reproducing)
