### ISSUE TITLE
Enhancement: list of markers actually displayed

### ISSUE THREAD

**Issue by monsieurtanuki** [osmdroid/osmdroid#670]
The idea is to add in `ItemizedOverlay` a new method called `public List<Item> getDisplayedItems()`, in order to get the list of all markers that are currently drawn on the canvas.

The obvious use case is a "share" or "export" button  on a map, restricted to what is displayed.

I still have a few things to check and will be ready to PR within a week.

**Comment by spyhunter99** [comment]
this would also be very useful for a folder overlay, however the complexity will increase a bit.

**Comment by monsieurtanuki** [comment]
In my initial idea that only makes sense for an `Overlay` that uses `OverlayItem`s, and `FolderOverlay` don't use them.

**Comment by monsieurtanuki** [comment]
I think this should be closed as it's been delivered (not very explicitly because of my git clumsiness).
cf. `ItemizedOverlay.getDisplayedItems()`
