### ISSUE TITLE
OutOfMemory exception

### ISSUE THREAD

**Issue by sadevelopment** [osmdroid/osmdroid#671]
Hi,

We have maps included in one of our apps and our users have been reporting crashes and freezing. Upon examination 100% of the cause of this is org.osmdroid.tileprovider.tilesource.BitmapTileSourceBase.getDrawable. This is periodic but is happening with enough frequency that it is affecting our user experience. We are using 5.6.5 of your library and a variety of devices which are all Android 6.x +

`08-18 10:56:09.515 21709  8380 E OsmDroid: OutOfMemoryError loading bitmap
08-18 10:56:09.525 21709  8380 E OsmDroid: Error loading tile
08-18 10:56:09.525 21709  8380 E OsmDroid: org.osmdroid.tileprovider.tilesource.BitmapTileSourceBase$LowMemoryException: java.lang.OutOfMemoryError: Failed to allocate a 262156 byte allocation with 63008 free bytes and 61KB until OOM
08-18 10:56:09.525 21709  8380 E OsmDroid: 	at org.osmdroid.tileprovider.tilesource.BitmapTileSourceBase.getDrawable(Unknown Source)
08-18 10:56:09.525 21709  8380 E OsmDroid: 	at org.osmdroid.tileprovider.modules.MapTileSqlCacheProvider$TileLoader.loadTile(Unknown Source)
08-18 10:56:09.525 21709  8380 E OsmDroid: 	at org.osmdroid.tileprovider.modules.MapTileModuleProviderBase$TileLoader.run(Unknown Source)
08-18 10:56:09.525 21709  8380 E OsmDroid: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
08-18 10:56:09.525 21709  8380 E OsmDroid: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
08-18 10:56:09.525 21709  8380 E OsmDroid: 	at java.lang.Thread.run(Thread.java:818)
08-18 10:56:09.525 21709  8380 E OsmDroid: Caused by: java.lang.OutOfMemoryError: Failed to allocate a 262156 byte allocation with 63008 free bytes and 61KB until OOM
08-18 10:56:09.525 21709  8380 E OsmDroid: 	at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
08-18 10:56:09.525 21709  8380 E OsmDroid: 	at android.graphics.BitmapFactory.nativeDecodeStream(Native Method)
08-18 10:56:09.525 21709  8380 E OsmDroid: 	at android.graphics.BitmapFactory.decodeStreamInternal(BitmapFactory.java:635)
08-18 10:56:09.525 21709  8380 E OsmDroid: 	at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:611)
08-18 10:56:09.525 21709  8380 E OsmDroid: 	... 6 more
08-18 10:56:09.535 21709  8440 D libc    : [NET] android_getaddrinfofornetcontext+,hn 24(0x632e74696c652e),sn(),hints(known),family 0,flags 1024, proc=com.laundrapp.driver
08-18 10:56:09.535 21709  8440 D libc    : [NET] android_getaddrinfo_proxy get netid:0
`

**Comment by spyhunter99** [comment]
Here's a few pointers to investigate
- are you programmatically creating the map or loading via layout?
- is the map in a view pager?
- are you using mapview out of the box or have you extended it?
- can you post a minimalist example of how you create the map, onStart,stop,pause,resume functions of the map.
- what kind of overlays are you using? custom? marker? itemizediconoverlay? how many overlays/markers are you using? what about polygons/polylines

**Comment by sadevelopment** [comment]
Thanks for the response - the error occurs after we leave the app for a period of time - we launch Waze to guide our drivers - and then return back to the app. In answer to the above:

The map is loaded via a layout
The map is not in a view pager
We are using map out of the box
We have two custom markers; one static and one which moves based on location and we draw a polygon when the location is with 150m of the static icon.

We do not do anything in particular with the map - nothing is done in onPause, onResume, etc. as its contained within a layout which in turn in within a fragment. I have added our initialisation code below.

We restrict user interaction with the map, and have an event on it once layout is finished where we set the position of the 2 markers plus the polygon if required.

`    private void initializeMap() {

        mapView = (MapView)findViewById(map);
        mapView.setTileSource(TileSourceFactory.DEFAULT_TILE_SOURCE);
        mapView.setTilesScaledToDpi(true);
        mapView.setPadding(20,20,20,20);
        mapView.setBuiltInZoomControls(false);
        mapView.setOnTouchListener(new OnTouchListener() {
            @Override
            public boolean onTouch(View v, MotionEvent event) {
                return true;
            }
        });
        if(!mapView.isLayoutOccurred() && mapItem==null) {
            mapView.addOnFirstLayoutListener(new MapView.OnFirstLayoutListener() {
                @Override
                public void onFirstLayout(View v, int left, int top, int right, int bottom) {
                    setField(mapItem);
                    mapView.removeOnFirstLayoutListener(this);
                }
            });
        } else if(mapView.isLayoutOccurred() && mapItem!=null) {
            setField(mapItem);
        }
    }`

**Comment by sadevelopment** [comment]
Sorry we also center the map to contain both markers ...

**Comment by spyhunter99** [comment]
it's possible this is related to the size of the in memory cache. Do you explicit set the value at all? Most likely a call to this?
https://github.com/osmdroid/osmdroid/blob/master/osmdroid-android/src/main/java/org/osmdroid/config/DefaultConfigurationProvider.java#L164

or perhaps adjustment to the tiles overlay?
https://github.com/osmdroid/osmdroid/blob/master/OpenStreetMapViewer/src/main/java/org/osmdroid/samplefragments/cache/SampleJumboCache.java#L55


you might also want to consider this flag
https://github.com/osmdroid/osmdroid/blob/master/OpenStreetMapViewer/src/main/AndroidManifest.xml#L43

**Comment by spyhunter99** [comment]
also, do you have a static reference to the map by chance? use the compass overlay or my location overlays?

**Comment by spyhunter99** [comment]
the error occurs after we leave the app for a period of time

meaning the user has switched to a different android application then flips back to yours? any idea how long? I'm just asking to see if we can recreate it the issue

**Comment by spyhunter99** [comment]
@sadevelopment how did you come to your conclusion by the way? I'm assuming you took a heap dump, ran it through the conversion tool, then opened in something like MAT?

**Comment by spyhunter99** [comment]
i ran several tests today, count 50, destroying and recreating all 50+ examples in the sample app on an API10 device. No memory leaks and it was running at like 4 MB allocation (this excludes bitmaps on this API level). I also ran another test that restarts the activity several times on each fragment and i haven't been able to reproduce.

**Comment by sadevelopment** [comment]
Thanks for the replies @spyhunter99 

We do not have any static references to the map, or use the location or compass overlays.

I came to the conclusion based on seeing the stack traces while out with one of our drivers on Friday. He used his phone as he would the same as any other working day except it was plugged into my laptop where I monitored the logs. I also see crash reports on Google Play with the same error from other drivers.

Basically we use the map for information purposes only, as I said its a simple implementation - we show where he is, where our customer is and a polygon when he is within a certain radius of the customer, the user cannot zoom or pan. Typically the driver will launch Waze or Google Maps from within the app and follow the directions to the customer. This can be anywhere between 5 mins and 30 mins if they cannot find an address (although our typical window between customers is around the 10-15min mark). So yes they leave the app and then come back. I saw the error 3 times in the space of around 3 hrs and based on discussions with this driver (and others) it happens 6-7 times daily. I myself have been trying to reproduce it with little success.

The only api calls we make to the map (apart from adding the 2 icon overlays, the polygon and changing driver pin position) are within the code snippet above. I will give your suggestions above a go - however the time to test this is quite long as the best people to test this is our drivers.

**Comment by spyhunter99** [comment]
Have a look at this
https://github.com/osmdroid/osmdroid/blob/master/OpenStreetMapViewer/src/main/java/org/osmdroid/OsmApplication.java#L109

Specifically the OOM handling. In that case, it will write the memory dump to disk. If you copy that class, you'll also need to reference it from the manifest. If it happens again, you should have a usable memory dump to analyze

**Comment by sadevelopment** [comment]
Great thanks.

**Comment by spyhunter99** [comment]
@sadevelopment any update on this?

**Comment by spyhunter99** [comment]
operation timeout. please reopen or comment back if you have further questions
