### ISSUE TITLE
Polygon issues with the dateline

### ISSUE THREAD

**Issue by spyhunter99** [osmdroid/osmdroid#675]
Loading a data set containing borders of conus. I get this when zoomed out
![image](https://user-images.githubusercontent.com/1975321/29491210-b8f946f4-8521-11e7-9022-e3de77742161.png)

I've seen this issue come up before when polygons cross the dateline, but never with conus.

Video scrolling when soon with some strange behaviors.

**Comment by spyhunter99** [comment]
https://youtu.be/EQsi38PIYm8

**Comment by spyhunter99** [comment]
@MKergall have you seen this before?

**Comment by MKergall** [comment]
No. Combination of dateline crossing + very low zoom level? 
Is it also occuring when your zoom level is higher?

**Comment by spyhunter99** [comment]
i've been able to reproduce this at a number of different zoom levels. I think it's related to map wrapping. I drew a triangle on screen that crossed the date line. Just pushed a new sample. I'll upload a video shortly

**Comment by spyhunter99** [comment]
[polygon.zip](https://github.com/osmdroid/osmdroid/files/1254016/polygon.zip)
unzip it, mp4 inside

**Comment by spyhunter99** [comment]
#476 related

**Comment by MKergall** [comment]
OMG, you were using a Polygon, not a Polyline. This is effectively same than 476. 
I will try to look at the patch.
