### ISSUE TITLE
Incorrect drawing of accuracy range

### ISSUE THREAD

**Issue by roman-nevr** [osmdroid/osmdroid#678]
When I use MyLocationNewOverlay with drawAccuracy(true), accuracy range of draws with twitching when I call zoomIn() and zoomOut()

**Comment by spyhunter99** [comment]
it's probably incorrect while the zoom animation is happening. this is normal, everything is effected by this actually. once the animation is complete, it gets redrawing and should be accurate. Does this make sense?

**Comment by roman-nevr** [comment]
Yes, when the animation is complete, it gets redrawing and is accurate. I guess, it is because of integer zoom level and animation starts after zoom level changed. I think, If animation started with old zoom level it would be accurate animation

**Comment by spyhunter99** [comment]
this may be fixed on the new floating point zoom system. just need to test

**Comment by monsieurtanuki** [comment]
@roman-nevr Should be fixed by #800. Could you give it a try?

**Comment by spyhunter99** [comment]
i'm gonna mark this as closed. the described behavior is no longer present with v6.x
