### ISSUE TITLE
Custom map domain

### ISSUE THREAD

**Issue by himagaran** [osmdroid/osmdroid#679]
How can i add my own map tile server with osm and show it on android mapview?

**Comment by spyhunter99** [comment]
checkout the source to TileSourceFactory.

**Comment by spyhunter99** [comment]
https://github.com/osmdroid/osmdroid/blob/master/osmdroid-android/src/main/java/org/osmdroid/tileprovider/tilesource/TileSourceFactory.java#L94

you'll also want to read the wiki article on tile sources, formats, storage mechanisms, and coordinate systems

**Comment by himagaran** [comment]
The problem is it cant be edited, TileSourceFactory.java is locked

**Comment by spyhunter99** [comment]
You don't need to edit it. Just copy and paste

````
 OnlineTileSourceBase mySource= new XYTileSource("Mapnik",
			0, 19, 256, ".png", new String[] {
					"http://a.tile.openstreetmap.org/",
					"http://b.tile.openstreetmap.org/",
					"http://c.tile.openstreetmap.org/" },"© OpenStreetMap contributors");
mapView.setTileSource(mySource);
````

**Comment by himagaran** [comment]
ok

**Comment by monsieurtanuki** [comment]
@himagaran Seems OK now, doesn't it? Feel free to open a new issue if needed.

**Comment by himagaran** [comment]
> @himagaran Seems OK now, doesn't it? Feel free to open a new issue if needed.
Yeah thanks for closing.
