### ISSUE TITLE
Converting geopoint  to  screen coordinates

### ISSUE THREAD

**Issue by AlexDevelopment** [osmdroid/osmdroid#682]
Hi.

I  get screen coordinates

```
public static Point pointFromGeoPoint(GeoPoint gp, MapView vw){
        Point rtnPoint = new Point();
        Projection projection = vw.getProjection();
        projection.toPixels(gp, rtnPoint);
        // Get the top left GeoPoint
        GeoPoint geoPointTopLeft = (GeoPoint) projection.fromPixels(0, 0);
        Point topLeftPoint = new Point();
        // Get the top left Point (includes osmdroid offsets)
        projection.toPixels(geoPointTopLeft, topLeftPoint);
        rtnPoint.x-= topLeftPoint.x; // remove offsets
        rtnPoint.y-= topLeftPoint.y;
        if (rtnPoint.x > vw.getWidth() || rtnPoint.y > vw.getHeight() ||
                rtnPoint.x < 0 || rtnPoint.y < 0){
            return null; // gp must be off the screen
        }
        return rtnPoint;
    }
```
But I get negative coordinates. How do will compensation?
How correctly to receive coordinates for drawing my view?

**Comment by spyhunter99** [comment]
negative values are off screen too

**Comment by AlexDevelopment** [comment]
Yes. But I set  coordinates which is at screen.

**Comment by spyhunter99** [comment]
Ahh so there's a difference between screen coordinates and canvas coordinates. Screen coodinates are always positive, on screen pixel offsets. Canvas coordinates represent the whole planet. I think what you are looking for is in the projection class.

    public Point toPixelsFromMercator(int x, int y, Point reuse) 
    public Point toMercatorPixels(int x, int y, Point reuse)

**Comment by AlexDevelopment** [comment]
It did not help. Got the same thing

**Comment by AlexDevelopment** [comment]
Can I to get coordinates  at  screen Overlay's?

**Comment by spyhunter99** [comment]
You want pixel coordinates to lat/lon correct?

**Comment by spyhunter99** [comment]
This will go from pixel x,y to lat/lon
GeoPoint iGeoPoint = (GeoPoint) projection.fromPixels(x,y);

This will go from lat/lon to pixel x,y
projection.toPixels(geoPoint, pt);

To project pixels should give you the canvas coordinates
projection.toProjectedPixels(...)

what's your use case for this by the way?

**Comment by AlexDevelopment** [comment]
Sorry. I bad speak English. I want get this https://i.stack.imgur.com/Re92g.jpg 
Overlay is drawn well. And I draw the text in a separate view. I need to get the coordinates for the view

**Comment by AlexDevelopment** [comment]
The text  is biased relative to overlay

**Comment by spyhunter99** [comment]
It may be easier to use the Marker class. Set the image to null, then a simple text label will be displayed. You want the projected pixels

**Comment by AlexDevelopment** [comment]
Yes I want. I want to get  projected pixels from coordinates overlay's

**Comment by AlexDevelopment** [comment]
How can  I  to use class marker?

**Comment by spyhunter99** [comment]
Marker.ENABLE_TEXT_LABELS_WHEN_NO_IMAGE = true;
      Marker m = new Marker(mapView);
                //stylize the marker here
                 m.setTitle("some text");
                //must set the icon last
                m.setIcon(null);
                m.setPosition(new GeoPoint(lat,lon));

**Comment by AlexDevelopment** [comment]
Thanks you. But this does not suit me. I will now give a link how it should turn out

**Comment by AlexDevelopment** [comment]
That's how it should be  http://ipic.su/img/img7/fs/nicmmnkoknjjejgb.1503773834.jpg

**Comment by AlexDevelopment** [comment]
I'll try to do it through OverlayItem.setMarkerHotspot (final HotspotPlace place)

**Comment by spyhunter99** [comment]
operation timeout. please reopen or comment back if you have further questions
