### ISSUE TITLE
How to add the My Location overlay

### ISSUE THREAD

**Issue by AlexDevelopment** [osmdroid/osmdroid#687]
Hi

Add your location. But the icon does not appear. What should I do to make the icon appear?
```

mLocationOverlay = new MyLocationNewOverlay(new GpsMyLocationProvider(getApplicationContext()),mMapView);
        mLocationOverlay.enableMyLocation();
        mMapView.getOverlays().add(mLocationOverlay);
```

**Comment by spyhunter99** [comment]
That should be it, is GPS turned on on the device? permissions granted for fine location?

**Comment by AlexDevelopment** [comment]
I send location in the emulator. And I instal app at real device. Icon is not show

**Comment by spyhunter99** [comment]
Again, if the device or emulate is API23+ you have to ask the user for permission to access GPS

**Comment by AlexDevelopment** [comment]
Ok. I Understand you. Thanks you.

**Comment by AlexDevelopment** [comment]
At what point should I ask the user?

**Comment by spyhunter99** [comment]
It needs to be before the map view is created. i.e. before the layout is
inflated

**Comment by AlexDevelopment** [comment]
Thanks you my friend))
