### ISSUE TITLE
Rotate my location icon osmdroid

### ISSUE THREAD

**Issue by AlexDevelopment** [osmdroid/osmdroid#689]
Hi.
I add my own location icon. But it does not turn when driving. How can I fix this?

```
mLocationOverlay = new MyLocationNewOverlay(new GpsMyLocationProvider(getApplicationContext()),mMapView);
            mLocationOverlay.enableMyLocation();
        mLocationOverlay.setPersonIcon(BitmapFactory.decodeResource(getResources(), R.drawable.ic_mylocation_55dp));
```

**Comment by spyhunter99** [comment]
So you want to rotate the icon, is that correct? If so, there are alternate approaches to solving this. The MyLocationNewOverlay works well if you wants the gps accuracy on the screen. If you don't need the accuracy bubble, you can also try this example.

https://github.com/osmdroid/osmdroid/blob/master/OpenStreetMapViewer/src/main/java/org/osmdroid/samplefragments/data/AnimatedMarker.java

Note: there's probably easier/more efficient ways to do this but this is functional

**Comment by AlexDevelopment** [comment]
I want the icon to turn when moving

I tried so much:

```
 mLocationOverlay.setDirectionArrow(BitmapFactory.decodeResource(getResources(), R.drawable.ic_mylocation_55dp),
                BitmapFactory.decodeResource(getResources(), R.drawable.ic_mylocation_55dp));
```
The second parameter specifies the arrow that rotates. But neither of which failed

**Comment by AlexDevelopment** [comment]
This method is solution LocationOverlay.setDirectionArrow(). I needed a second parameter.  But it work only on the real device))) Thanks)))

**Comment by spyhunter99** [comment]
no problem
