### ISSUE TITLE
Use local storage system for tiles

### ISSUE THREAD

**Issue by nijs9** [osmdroid/osmdroid#691]
In earlier versions, osmdroid did use local storage for caching tiles. Is there a way to use the earlier caching system in 5.6.5? I think you have to use TileWriter instead of SqlWriter, but how to do this? Any help is appreciated.

**Comment by spyhunter99** [comment]
This can be done by programmatically constructing the tile provider. I'd use the MapTIleProviderBasic. Basically, just pass in an instance of the `TileWriter` class

see https://github.com/osmdroid/osmdroid/blob/ba74d6158904b9f247f4c80b395d6683cd82ff5e/osmdroid-android/src/main/java/org/osmdroid/tileprovider/MapTileProviderBasic.java#L59

**Comment by nijs9** [comment]
Thank you spyhunter. I this it this way:

`final ITileSource tileSource2 = new XYTileSource("tile_overlay_3",6, 17, 256, ".png", new String[]{"https://geoserver2.nodemapp.com/geoserver/"})
        {
            @Override
            public String getTileURLString(MapTile aTile) {
                String hello= getBaseUrl() + "gwc/service/gmaps?layers=nodemapp-public-mobile-with-cache&zoom=" + aTile.getZoomLevel() + "&x=" + aTile.getX() + "&y=" + aTile.getY() + "&format=image/png&viewparams=kind:hike;groupid:1&version=1";
                System.out.println(hello);
                return hello;
            }
        };
        final MapTileProviderBasic anotherTileProvider = new MapTileProviderBasic(getApplicationContext(), tileSource2, new TileWriter());

        final TilesOverlay secondTilesOverlay = new TilesOverlay(anotherTileProvider, this.getBaseContext());
        secondTilesOverlay.setLoadingBackgroundColor(Color.TRANSPARENT);

osmMap.getOverlays().add(secondTilesOverlay);`

Now, tiles are cached in folders in osmdroid->tiles->name, but they are not visible on the map

**Comment by spyhunter99** [comment]
what your are probably missing is this.

https://github.com/osmdroid/osmdroid/blob/ba74d6158904b9f247f4c80b395d6683cd82ff5e/osmdroid-android/src/main/java/org/osmdroid/tileprovider/MapTileProviderBasic.java#L87

Simplest path forward is to make your implement MapTileProviderBasic and just build your own setup.

**Comment by spyhunter99** [comment]
@nijs9 figure it out?

**Comment by spyhunter99** [comment]
closing due to no feedback
