### ISSUE TITLE
Out of memory when loading large kml file

### ISSUE THREAD

**Issue by saubhikde** [osmdroid/osmdroid#697]
When I am trying to load large(67mb) kml file to map view it is causing out of memory exception.

**Comment by MKergall** [comment]
https://github.com/MKergall/osmbonuspack/wiki/KML#limits

**Comment by spyhunter99** [comment]
Options,  
use a smaller kml file
Run a point reduction algorithm on it
Turn on the large heap size setting in the manifest

**Comment by spyhunter99** [comment]
throwing one more option out there, take your kml, import it into a database of sorts, then only attempt to display and render what's on screen and update on pan/zoom. other than that, there's not much else that can be done
