### ISSUE TITLE
using WMS problem

### ISSUE THREAD

**Issue by AliKhoshraftar** [osmdroid/osmdroid#700]
i want to use my wms as a tile datasource, but i can't implement , this is my base address:

"service=WMS&request=GetMap&layers=Shiveh%3AShivehGSLD256&styles=&format=image%2Fpng&transparent=false&version=1.1.1&height=256&width=256&srs=EPSG%3A4326&bbox=";

casting xyz to bbox is incorrect , and showing tiles has error
how i can implement it ?

**Comment by spyhunter99** [comment]
See #177

**Comment by spyhunter99** [comment]
wms support is still kind of beta. even at that, the solution we have does work for geoserver but does not appear to function for nasa's endpoints, which i think are esri/arcgis servers.

**Comment by spyhunter99** [comment]
Here's the source for the wms client i've been working on, it should help you out.

https://github.com/osmdroid/osmdroid/blob/feature/%23177/osmdroid-wms/src/main/java/org/osmdroid/wms/WMSTileSource.java

**Comment by spyhunter99** [comment]
closing this as the wms client has been merged to master.
