### ISSUE TITLE
Enhancement: floating point zoom optional set up

### ISSUE THREAD

**Issue by monsieurtanuki** [osmdroid/osmdroid#703]
From @spyhunter99 in #640:

> it would be useful and/or feasible to making the floating point zoom be optional or be able to be disabled? I'm thinking about potential issues users may have with custom layer setups

**Comment by ycuicui** [comment]
float zoom level values will alows for displaying maps at non integer zoom values. Then it will be possible to zoom with two fingers (like on `GoogleMap`).
I do this on my fork of this projects but it is a huge refactoring!

**Comment by monsieurtanuki** [comment]
@ycuicui Actually floating point zoom is already implemented in 6.0.0 and is the only way the zoom works now.
The question here is for the user to be able to switch back to integer zoom for nostalgia reasons.


-------- Message d'origine --------
De : ycuicui <notifications@github.com>
Date : 10/11/2017 21:57 (GMT+01:00)
À : osmdroid/osmdroid <osmdroid@noreply.github.com>
Cc : monsieurtanuki <fabrice_fontaine@hotmail.com>, Author <author@noreply.github.com>
Objet : Re: [osmdroid/osmdroid] Enhancement: floating point zoom optional set up (#703)


float zoom level values will alows for displaying maps at non integer zoom values. Then it will be possible to zoom with two fingers (like on GoogleMap).
I do this on my fork of this projects but it is a huge refactoring!

**Comment by spyhunter99** [comment]
i'd say it's low priority, compared to the remaining open issues. this could even be for the follow up version

**Comment by monsieurtanuki** [comment]
@spyhunter99 The way things are evolving (including recently smooth pinch gesture zoom), it will be very hard to make it possible to switch back to integer-only zoom. Unless you have a use case in mind, I think we could close and forget this issue.
