### ISSUE TITLE
I have my own tile archive format that I was to use！ 

### ISSUE THREAD

**Issue by Amorzhang** [osmdroid/osmdroid#704]
dbName = (char)('A' + z) + "_" + x / 256 + "_" + y / 256;
dbPath = path+ (char)('A' + z) + File.separator+ dbName + ".s";
tableName =(char)('A'+z)+"_"+x/64+"_"+y/64;
How do I get x，y，z?
how do I implement the IArchiveFile interface？

**Comment by spyhunter99** [comment]
Does this help? 
https://github.com/osmdroid/osmdroid/wiki/Offline-Map-Tiles#adding-a-new-file-archive-provider

**Comment by Amorzhang** [comment]
Yes! Thanks! But I've just started learning osmdroid and map,I still hava some questions about the set the tile source.
 I implement the IArchiveFile interface with my own class,override the method of InputStream getInputStream(ITileSource tileSource, MapTile tile) 
Use registerArchiveFileProvider (Class<? extends IArchiveFile> provider, String fileExtension)  to registered it
Then how do I set up tileSource,extend BitmapTileSourceBase? Then what should I do？

**Comment by spyhunter99** [comment]
https://github.com/osmdroid/osmdroid/blob/master/osmdroid-android/src/main/java/org/osmdroid/tileprovider/tilesource/TileSourceFactory.java

Bunch of examples there

**Comment by Amorzhang** [comment]
The key is that my database field has no ‘provider’！ It is ‘ID’，‘Data’， X’， Y’， F’.

**Comment by spyhunter99** [comment]
@Amorzhang is this good to close now?

**Comment by spyhunter99** [comment]
closing due to no feedback
