### ISSUE TITLE
Tiles load extremely slowly

### ISSUE THREAD

**Issue by Mickey-Livesgood** [osmdroid/osmdroid#708]
I am using the latest version (5.6.5) and the tiles load extremely slowly, to the rate of bad UX.
This happens on two devices I tried the app on, both with high-speed internet connection (both cellular and WIFI).
I'm using the MAPNIK map, everything based on the tutorial of osmdroid.

`@Override
protected void onCreate( Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);

    appContext = getApplicationContext();

    //important! set your user agent to prevent getting banned from the osm servers
    Configuration.getInstance().load(appContext, PreferenceManager.getDefaultSharedPreferences(appContext));
    setContentView(R.layout.navigation);

    mMapView = (MapView) findViewById(map);
    mMapView.setTileSource(TileSourceFactory.MAPNIK);
    mMapView.setMultiTouchControls(true);
    mMapView.setBuiltInZoomControls(true);

    // add rotation gesture
    mRotationGestureOverlay = new RotationGestureOverlay(this, mMapView);
    mRotationGestureOverlay.setEnabled(true);
    mMapView.setMultiTouchControls(true);
    mMapView.getOverlays().add(this.mRotationGestureOverlay);

    // Set to default location
    IMapController mapController = mMapView.getController();
    mapController.setZoom(15);
    GeoPoint startPoint = new GeoPoint(48.8589654,2.2926013);
    mapController.setCenter(startPoint);
}`

I can't seem to find the reason for this slow load. Is there an option to use a simpler map? will that help? Are there any other solutions, something I'm doing wrong?

Thanks.

**Comment by secaw** [comment]
After loading the configuration, set your own user agent as the first comment above suggests like this:
```
Configuration.getInstance().setUserAgentValue(getPackageName());
```

**Comment by Mickey-Livesgood** [comment]
Thanks for the quick comment. 
I want to make sure - getPackageName() should be a method that returns a string with the package name?

If so, I have made that change but the tiles still load slowly.

**Comment by spyhunter99** [comment]
It has to be set before the map view is created or inflated

**Comment by spyhunter99** [comment]
can you install this on your device and see if the problem is still present?
https://play.google.com/store/apps/details?id=org.osmdroid

**Comment by spyhunter99** [comment]
@Mickey-Livesgood the getPackageName() bit is just a way for the osm website to uniquely identify applications and their bandwidth usage. You could set a random uuid there if you wanted. I'm not experiencing any slow downs over here. Another suggestion would be to try an alternate tile source. That link app has a bunch. Is the problem present for all tile sources or just mapnik?

**Comment by Mickey-Livesgood** [comment]
@spyhunter99 thanks for all the comments and support.
The osmdroid app from google play works at around 50% faster then my app.
However, the map seemed to be a bit different at lower zoom levels, since the map in my app had a bit more detail even at a lower zoom levels.
I have tried a different tile provider (OpenTopo) but it was still slow.
I want to make sure my dependencies are correct, this is what I have defined:

```
dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    compile 'com.android.support:appcompat-v7:25.3.1'
    compile 'com.android.support.constraint:constraint-layout:1.0.2'
    compile 'org.osmdroid:osmdroid-android:5.6.5'
    compile 'com.android.support:design:+'
    testCompile 'junit:junit:4.12'
}


```


One really weird thing that happened after I have downloaded the Osmdroid app from the google play store on one of the devices, is that the map stopped loading, without any changes to the code. 
This is happening only on one of the devices, which has 18GB free memory available. Restarting the device didn't work. This is the errors I get, which are related to the SQLite db:

> Failed to open database '/storage/emulated/0/osmdroid/tiles/cache.db'.
> android.database.sqlite.SQLiteCantOpenDatabaseException: unknown error (code 14): Could not open database

> 
> E/OsmDroid: Unable to start the sqlite tile writer. Check external storage availability.

**Comment by secaw** [comment]
Are you saying, that with the app from Google Play it takes 5-10 seconds for tiles to load from any tile source? This is not normal. Do you have some parallel network traffic going on?

**Comment by Mickey-Livesgood** [comment]
@secaw nope, I wrote "around 50% faster" as a rough estimate.
I have counted the time to load tiles on the google play app, and at some zoom levels, the last tile to load sometime reach 4 seconds. (most tiles load at 1-2 seconds). 
At my app, tiles usually load at around 5-10 seconds, while some tiles take to load 10-20 seconds as I written before.
The best experience I get is by using the map on openstreetmap.org with a browser on my android device (i.e firefox) - the tiles all load in up to 2 seconds and they are very smooth.
That's why I believe there is a specific problem with my app.

(Also, the new problem of the map not showing at all on a specific device, as I have written in my previous comment)

**Comment by MKergall** [comment]
In the past, I experienced very slow loading on a device as soon as SQLite db was above 4Mb on the external SD card - most likely because this SD card was slow compared with internal storage or more recent ones. 

Could you completely delete the cache (SQLite files), and then try again?

**Comment by Mickey-Livesgood** [comment]
@MKergall I both deleted the cache and the app, this doesn't help.
Will changing the directories help to solve the problems? Both for the slow loading of tiles, and the problem for the other device not showing the tiles at all?
If so - which directories should I use and how should I implement this?

**Comment by MKergall** [comment]
I did that in onCreate to ensure the cache was on fast internal storage instead of slow SD card: 

		super.onCreate(savedInstanceState);
		Configuration.getInstance().setOsmdroidBasePath(new File(Environment.getExternalStorageDirectory(), "osmdroid"));
		Configuration.getInstance().setOsmdroidTileCache(new File(Environment.getExternalStorageDirectory(), "osmdroid/tiles"));

**Comment by Mickey-Livesgood** [comment]
@MKergall , thanks for all the help.
I have added the lines of code to my activity (that contains the fragments) but I am still having the problems:

On the problematic device (where the tiles don't show at all), I still get those two errors:
```

Unable to store cached tile from Mapnik /16/19312/24609 db is null
     java.lang.NullPointerException: Attempt to invoke virtual method 'long android.database.sqlite.SQLiteDatabase.insert(java.lang.String, java.lang.String, android.content.ContentValues)' on a null object reference
     at org.osmdroid.tileprovider.modules.SqlTileWriter.saveFile(SqlTileWriter.java:176)
     at org.osmdroid.tileprovider.modules.MapTileDownloader$TileLoader.loadTile(MapTileDownloader.java:251)
     at org.osmdroid.tileprovider.modules.MapTileModuleProviderBase$TileLoader.run(MapTileModuleProviderBase.java:297)
     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
     at java.lang.Thread.run(Thread.java:818)...
```
and:

```
Unable to start the sqlite tile writer. Check external storage availability.
    android.database.sqlite.SQLiteCantOpenDatabaseException: unknown error (code 14): Could not open database
    at android.database.sqlite.SQLiteConnection.nativeOpen(Native Method)
    at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:208)
    at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:192)
    at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:464)
    at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:186)
    at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:178)
    at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:916)
    at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:893)
    at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:796)
    at android.database.sqlite.SQLiteDatabase.openOrCreateDatabase(SQLiteDatabase.java:811)
    at android.database.sqlite.SQLiteDatabase.openOrCreateDatabase(SQLiteDatabase.java:804)
    at org.osmdroid.tileprovider.modules.SqlTileWriter.<init>(SqlTileWriter.java:71)
    at org.osmdroid.tileprovider.modules.MapTileSqlCacheProvider.<init>(MapTileSqlCacheProvider.java:63)
    at org.osmdroid.tileprovider.modules.MapTileSqlCacheProvider.<init>(MapTileSqlCacheProvider.java:69)
    at org.osmdroid.tileprovider.MapTileProviderBasic.<init>(MapTileProviderBasic.java:88)
    at org.osmdroid.tileprovider.MapTileProviderBasic.<init>(MapTileProviderBasic.java:50)
    at org.osmdroid.views.MapView.<init>(MapView.java:184)...
```

On the other device, tile loading is still slow.

**Comment by spyhunter99** [comment]
https://github.com/osmdroid/osmdroid/blob/master/osmdroid-android/src/main/java/org/osmdroid/tileprovider/util/StorageUtils.java

Try using this class on the device that's not working.  It should tell your what storage locations ate available and can be written too. You can also use app private storage at data/data/packagename

**Comment by Mickey-Livesgood** [comment]
@spyhunter99 thanks, I'm not sure how to use the class though.
Should I use the `getStorage()` method in that class by calling it inside the following function in the activity that calls the map? (like this?):
`
Configuration.getInstance().setOsmdroidBasePath(getStorage());`

if yes, what about `Configuration.getInstance().setOsmdroidTileCache()`?
If no, then how should I use it?

Also, will using the app memory only (and not the SD card if available) improve the speed?

And a bit off subject, just to make sure:
In my gradle, I have defined the following line as I've seen in the tutorials: `compile 'org.osmdroid:osmdroid-android:5.6.5'`. However, in previous versions I have seen the addition of `@arr` at the end. I want to make sure that the version that I've written is the correct one.

Thanks for all the help! I really appreciate it.

**Comment by spyhunter99** [comment]
ahh sorry about that, try this
````
final List<StorageUtils.StorageInfo> storageList = StorageUtils.getStorageList();
````
Iterator over the list then print them to the logger. 
There's a sample usage here https://github.com/osmdroid/osmdroid/blob/master/OpenStreetMapViewer/src/main/java/org/osmdroid/intro/StoragePreferenceFragment.java and here https://github.com/osmdroid/osmdroid/blob/master/OpenStreetMapViewer/src/main/java/org/osmdroid/PreferenceActivity.java

`Configuration.getInstance().getOsmdroidBasePath` will return the currently configured base path (used for loading archives) and `Configuration.getInstance().getOsmdroidTileCache()` returns the currently configured path for storage the cache (which is where your problem might be)

The first time running, it will auto select the large partition that is writable, which may be internal, external or app private storage, depending on device hardware and permissions

**Comment by spyhunter99** [comment]
and 5.6.5 without at aar is correct.

**Comment by spyhunter99** [comment]
@Mickey-Livesgood any updates?

**Comment by spyhunter99** [comment]
operation timeout. please reopen or comment back if you have further questions

**Comment by SravanKumarReddy1990** [comment]
Guys android 6 given new way assigning permission of external storage so i have given ActivityCompat.requestPermissions(LoginActivity.this, new String[{Manifest.permission.READ_EXTERNAL_STORAGE,Manifest.permission.ACCESS_FINE_LOCATION},1); or else goto settings->Applications->Application Manager->choose your app->permission and on permissions so that problem will solve.
