### ISSUE TITLE
Non-free libraries in dependencies

### ISSUE THREAD

**Issue by mvglasow** [osmdroid/osmdroid#71]
https://github.com/osmdroid/osmdroid/blob/master/pom.xml#L69 has a bunch of dependencies that are part of the Google experience and non-free.

Are they really required to build mapsforge, or can they be safely removed? The guys over at F-Droid (https://f-droid.org) would like to include mapsforge in their repository, but cannot do so as long as there are non-free dependencies.

**Comment by spyhunter99** [comment]
The google dependencies are for the example google maps application and are NOT dependencies of the core library. does that clear things up?

**Comment by spyhunter99** [comment]
ping @mvglasow. is this cleared up?
maybe we make a maven profile that only includes the google specific things in an explicit profile.

**Comment by mvglasow** [comment]
Thanks for the reply. Having a separate profile which has no non-free dependencies would definitely be the best way to resolve this.

**Comment by spyhunter99** [comment]
mvn clean install  > does everything as normal
mvn clean install -Pcore > does only FOSS based libraries, aar's, and apk (google maps based apk and 3rd party jar are excluded)

does this meet the goals for getting publication on fdroid?

**Comment by spyhunter99** [comment]
reopen if the solution isn't enough
