### ISSUE TITLE
My Location overlay does not display

### ISSUE THREAD

**Issue by Amorzhang** [osmdroid/osmdroid#710]
My Location overlay does not display

this.mLocationOverlay = new MyLocationNewOverlay(new GpsMyLocationProvider(context),mMapView);
this.mLocationOverlay.enableMyLocation();
mMapView.getOverlays().add(this.mLocationOverlay);

**Comment by spyhunter99** [comment]
Did you check permissions?

**Comment by Amorzhang** [comment]
Just don't show the icon (I can get the location information), and sometimes icon appear after a while!

**Comment by spyhunter99** [comment]
You have a gps fix right? are you testing this outdoors?

**Comment by spyhunter99** [comment]
Also, please install the play app, this is the osmdroid demo app and check to see if the same problem is present

https://play.google.com/store/apps/details?id=org.osmdroid

**Comment by spyhunter99** [comment]
operation timeout. please reopen or comment back if you have further questions
