### ISSUE TITLE
can you provide a algorithm of baidu tile？

### ISSUE THREAD

**Issue by ruizhang81** [osmdroid/osmdroid#711]
i need to use baidu tile in android platform
thanks

**Comment by spyhunter99** [comment]
a what? no idea what you're talking about

**Comment by spyhunter99** [comment]
please reply with additional information

**Comment by ruizhang81** [comment]
use tile source of google map is ok，but use tile source of baidu is not ok,thanks

**Comment by spyhunter99** [comment]
is baidu a tile source? can you link me to it?

**Comment by spyhunter99** [comment]
looking at the network traffic, requests for tiles look to be vector tiles, not raster images. This essentially means that we cannot support it without a large amount of work.
See also https://github.com/osmdroid/osmdroid/issues/246

**Comment by ruizhang81** [comment]
like http://online3.map.bdimg.com/onlinelabel/?qt=tile&x=50&y=18&z=8&styles=pl&udt=20170712&scaler=1&p=1

**Comment by ruizhang81** [comment]
js demo
http://gdyblog.com/Demo/Baidu/index.html

**Comment by spyhunter99** [comment]
well that makes it easier
http://online3.map.bdimg.com/onlinelabel/?qt=tile&x=50&y=18&z=8&styles=pl&udt=20170712&scaler=1&p=1

x=50, y=18, z=8

make a custom xyztilesource instance and override getTileUrl. use that pattern as a guide. it 'should' match up

**Comment by ruizhang81** [comment]
Coordinate system is not the same  @_@!

**Comment by spyhunter99** [comment]
could be TMS, XYZ or YXZ, try switching the pattern around. Clear the tile cache before each attempt

**Comment by ruizhang81** [comment]
https://github.com/sureleo/leaflet-baidu

**Comment by spyhunter99** [comment]
@ruizhang81 not sure i can help you. It looks like it's a web mercator projector so i should work with osmdroid if you can figure out the coordinate system. that github project links to some sites with the equations. If you figure it out, comment back here. closing this issue for now
