### ISSUE TITLE
Markers faster rendering through GeoPoint optimization

### ISSUE THREAD

**Issue by monsieurtanuki** [osmdroid/osmdroid#712]
While (still) working on #329, I think we could make the rendering of `Marker`s  faster.

During the calculation of the pixel position from `GeoPoint`, the calculation for (latitude => Y) includes a code like this:
```java
0.5 - log((1 + sin(latitude)) / (1 - sin(latitude))) / (4 * PI)
```

This is computed each time the marker is to be displayed. That means very often.

Here's my assumption: using `log` and `sin` takes _significantly_ more time than simple multiplications and additions, and if we have many markers/polygons/polylines it would be wise not to compute that constantly.

A solution would be:
* to compute for each `GeoPoint` once and for all the results of those calculations (longitude => X; latitude => Y)
* to transform them into `int`s between 0 and 2^31-1
* to store them in new `int` `GeoPoint` members (`projectedX` and `projectedY`)
* to draw `Marker`s using those new members: we just have to transform a `[0, 2^31[` value into `[0, 2^zoom[`, which is a lossless division (with zoom < 31)

(Inspired by what I saw in `Polygon.LinearRing.buildPathPortion` and `Projection.toProjectedPixels`)

**Comment by spyhunter99** [comment]
sounds good

**Comment by monsieurtanuki** [comment]
I ran some tests this morning:
* first of all, we cannot use `int`s to store the precomputed values, as projected zoom level (30) multiplied by the tile size cannot fit. We should upgrade to `long`. And as `long` is 4 bytes long, we may as well use `double` (4 bytes long too) and store XY01 values instead
* it means also that instead of adding 2 x 2 bytes to each `GeoPoint` with those extra members, we add 2 x 4 bytes, which almost doubles the size (currently: 3 `double`s; with 2 extra members: 5 `double`s).
* there's an existing demo in "More Samples / Data" called "Simple Fast Point Overlay with 10k points". There are no significant speed improvement when using the presumably optimized" `GeoPoint` version. The slowest part seems to be the display, not the computation.

My conclusions after these tests:
* there's no obvious gain in this change (more memory used and no speed improvement)
* unless there's a relevant use case for this optimization attempt, we can forget it

What can still be done - we could get rid of the notion of "projected" pixels. The only position notions should be:
* a `GeoPoint` has a latitude and a longitude
* a latitude can be converted into a `double` value between 0 and 1 ("Y01") computed as its projection on [max_latitude=85;min_latitude=-85]
* a longitude can be converted into a `double` value between 0 and 1 ("X01") computed as its projection on [min_longitude=-180;max_longitude=180]
* a Mercator X (or Y) value is a X01 value (or Y01) multiplied by the map size (tile size x 2^zoom_level)
* a pixel X (or Y) value is a Mercator value with an offset for map centering reasons
