### ISSUE TITLE
Offline Map Tiles

### ISSUE THREAD

**Issue by prabin525** [osmdroid/osmdroid#717]
I am trying to implement osmdroid in my application and i require an offline map for this and i have tried downloading the tiles using MOBAC but none seem to work and most of the tutorials are incomplete or for the older versions. Can anybody suggest me the ways to implement offline maps using any of the way like mobac or mbtiles.

**Comment by spyhunter99** [comment]
Have you seen the wiki here, right? 
What exactly is the problem?

**Comment by spyhunter99** [comment]
https://github.com/osmdroid/osmdroid/wiki/Offline-Map-Tiles

**Comment by spyhunter99** [comment]
operation timeout. please reopen or comment back if you have further questions
