### ISSUE TITLE
Remove 'osmdroid-andorid/src/main/resources/**/*.png' 

### ISSUE THREAD

**Issue by mariotaku** [osmdroid/osmdroid#718]
## Issue Type

- [x] Question
- [ ] Bug
- [ ] Improvement
- [ ] Build system related
- [ ] Performance
- [ ] Documentation

### Version of osmdroid the issue relates to:

5.6.5

I don't see any reference to these images, seems they're never used in recent versions. Also loading resources from apk directly is a bad practice (see http://blog.danlew.net/2013/08/20/joda_time_s_memory_issue_in_android/ )

**Comment by spyhunter99** [comment]
which png files exactly?

**Comment by spyhunter99** [comment]
The AAR has android resources for various icons and whatnot. If you don't need them, they can be excluded with proguard.  There are images in the assets folder representing the top most zoom levels. The linked example is not applicable in this case nor relevant unless i'm missing something. We don't load images as class loader resources. Android resources and assets are loaded differently and it is supported way to load stuff. Do you have a specific example?

**Comment by mariotaku** [comment]
@spyhunter99 They are located at [osmdroid-android/src/main/resources/org/osmdroid](https://github.com/osmdroid/osmdroid/tree/osmdroid-parent-5.6.5/osmdroid-android/src/main/resources/org/osmdroid). I believe those images are now available in res folders, and seems they don't have any references.

**Comment by mariotaku** [comment]
@spyhunter99 I guess those images located in `src/resources` are obsolete stuffs when OSMDroid are packed and shipped in jar format. They become useless after we have aar and density specific resources.

**Comment by spyhunter99** [comment]
yup, you are right
