### ISSUE TITLE
bitmap snapshots based on geo coordinates

### ISSUE THREAD

**Issue by pasniak** [osmdroid/osmdroid#719]
## Issue Type

[x] Question
[ ] Bug
[x] Improvement
[ ] Build system related
[ ] Performance
[ ] Documentation

Is it possible to get a Bitmap snapshots at given geo coordinates box?  This is to get thumbnails for user selected waypoints.

### Version of osmdroid the issue relates to:

5.6.5

**Comment by spyhunter99** [comment]
hmm... try this
mapView.getMapTileProvider().getMapTile(...)

https://github.com/osmdroid/osmdroid/blob/63c876205fb66abd024402dac42060f1bff9011e/osmdroid-android/src/main/java/org/osmdroid/tileprovider/MapTileProviderBase.java#L59

**Comment by pasniak** [comment]
I presume pTile can be created ad hoc using MapTile(final int zoomLevel, final int tileX, final int tileY) ? And I can get x y  from CacheManager.getMapTileFromCoordinates ?

**Comment by spyhunter99** [comment]
Ahh sorry. You need lat/lon to a tile right?
http://wiki.openstreetmap.org/wiki/Slippy_map_tilenames#Java

This looks like it's in the osmmaptilepackager, but i'll add it to a util class somewhere. i feel this is duplicated code and it's all over the place

**Comment by pasniak** [comment]
No, it's just that result of tileProvider.getMapTile(zoom,x,y) is null...

![thumbnail_null](https://user-images.githubusercontent.com/19778666/30737351-441e494a-9f54-11e7-8426-e08aa34832d9.GIF)

(Thanks, it's a better way to get xy of a tile)

**Comment by spyhunter99** [comment]
ok try this

`mMapView.getTileProvider().getTileWriter().loadTile(mMapView.getTileProvider().getTileSource(), tile`);

**Comment by pasniak** [comment]
Hmm, `getTileWriter` does not have `loadTile`. I see `loadTile` method in many places in the lib, but I dont see how to get it from my `MapView` instance.

**Comment by spyhunter99** [comment]
the method `loadTile` is part if the `IFilesystemCache` interface. It should be there.

**Comment by spyhunter99** [comment]
https://github.com/osmdroid/osmdroid/blob/master/osmdroid-android/src/main/java/org/osmdroid/tileprovider/modules/IFilesystemCache.java#L77

javadoc says since 5.6.5 so maybe a version issue?

**Comment by spyhunter99** [comment]
closing due to lack of feedback. i'm assuming your issue is resolved. comment back if not

**Comment by pasniak** [comment]
![5 6 5](https://user-images.githubusercontent.com/19778666/31574961-3ff9c752-b0a9-11e7-805a-e0e98c4c8b7f.GIF)

**Comment by spyhunter99** [comment]
source history says it was added july 22 this year, last release was july 1st. javadoc is wrong, sorry!

**Comment by spyhunter99** [comment]
looks like it was part of the map tile approximator ticket

**Comment by pasniak** [comment]
Glad it's clear now... I'll try to code with my local build and switch to this code when a new release (6.0?) comes out. Maybe remove versions from the interface comments? (Reading "Clean code" and i agree with the guy that comments rot.... I saw this play out at work, other github projects -- especially in function headers vs signatures)

**Comment by pasniak** [comment]
Ok, here's code which returns a tile as drawable and _kind of_ works: it seems I have to match the `zoomLevel` (integer) of the map being displayed (`map.zoomLevel`) otherewise I get a `null`:
```
        fun getTile(lat:Double, lon:Double):Drawable? {
            val tileNum = getTileNumber(lat, lon, map.zoomLevel)
            val tile = MapTile( map.zoomLevel, tileNum.x, tileNum.y)
            return map.tileProvider.tileWriter.loadTile(map.tileProvider.tileSource, tile)
        }
```

**Comment by spyhunter99** [comment]
great! i'll close for now, unless you feel this would be useful to add to the library. Not entirely sure where we would put it though
