### ISSUE TITLE
'osmdroid' folder is always created even when I set a custom storage path

### ISSUE THREAD

**Issue by secaw** [osmdroid/osmdroid#720]
Every time, the first instance of `DefaultConfigurationProvider` is being retrieved through `Configuration.getInstance()`, the folders 'osmdroid' and 'osmdroid/tiles' are automatically being created by its constructor:
```
public DefaultConfigurationProvider(){
  try {
    osmdroidBasePath = new File(StorageUtils.getStorage().getAbsolutePath(), "osmdroid");
    osmdroidTileCache =  new File(getOsmdroidBasePath(), "tiles");
    osmdroidBasePath.mkdirs();
    osmdroidTileCache.mkdirs();
  }catch (Exception ex){

  }
}
```
This is getting pretty annoying, if you are setting a custom storage path, as the user gets put an unnecessary 'empty' folder on his main storage that doesn't relate to anything.

I didn't get to solve this gracefully - anyone got an idea?

**Comment by spyhunter99** [comment]
I think you can make a class that extends the default config provider and just not call super in the constructor, no?

**Comment by secaw** [comment]
No that wouldn't help, because `org.osmdroid.config.Configuration.getInstance()` (calling `org.osmdroid.config.DefaultConfigurationProvider()` on first instance and thus creating the folders) is being called all over osmdroid.

**Comment by secaw** [comment]
Why not move the dir creation from constructor to `DefaultConfigurationProvider.load(ctx, prefs)` at the bottom like this:
```
this.getOsmdroidBasePath().mkdirs();
this.getOsmdroidTileCache().mkdirs();
```
This means that one has to call the load function at least on first use in order for the folders to be created, but isn't this always advised or even necessary before map view creation anyways?

**Comment by spyhunter99** [comment]
well we can put that code in the getters for those functions, would that be sufficient?

**Comment by spyhunter99** [comment]
As part of your app's startup procedure, you can run `Configuration.setInstance(new YourClassExtendngDefaultConfigProvider());`

**Comment by secaw** [comment]
Yes, I saw and tried `Configuration.setInstance(...)` with extended `DefaultConfigProvider()` and preset custom paths already, but still got the folders created. This is strange and I didn't track it down, but I think, that dir creation in the constructor and especially in this 'hardcoded' way is wrong anyways.
Moving it to the getters actually is a great idea!

**Comment by spyhunter99** [comment]
@secaw does that commit work for you?

**Comment by secaw** [comment]
@spyhunter99 looks good, will check beginning of the week..

**Comment by secaw** [comment]
@spyhunter99 perfect, this does the trick - thank you!
