### ISSUE TITLE
mMapView.getController().setCenter does not correct

### ISSUE THREAD

**Issue by wangbincumt** [osmdroid/osmdroid#721]
I used osmdroid-android:5.6.5 and i make a map by a large size image,the image size is 51200*51200 and i cut it to titles with size 256*256
in onCreateView i set 
   mMapView.getController().setCenter(projection.fromPixels(25600,25600));
it works fine.
i have a button in view with  click event  
mMapView.getController().setCenter(projection.fromPixels(20744, 12768));
it move to wrong point .the offset is very large.
i can not find  reason。
is projection is change between two setCenter?

it no probroms in ADV while no work in real phone

**Comment by spyhunter99** [comment]
is it a samsung by chance?

**Comment by spyhunter99** [comment]
fromPixel is on the screen pixel coordinates, not the world canvas.

**Comment by spyhunter99** [comment]
if it works on AVD but not on the phone, perhaps you are not taking into considering the dpi of the device? that would be my bet.

**Comment by spyhunter99** [comment]
closing due to lack of feedback, reopen or comment back if this is still a problem
