### ISSUE TITLE
Bad performance on Samsung S7

### ISSUE THREAD

**Issue by bbb0x** [osmdroid/osmdroid#727]
Hi,

I'm developing on a Samsung S4 with Android 4.4.2 and a Samsung S7 with Android 7.0.
On the S4 osmdroid is smooth and fast (feels like 60 FPS), but on the S7 it's laggy. To show it for you I uploaded it to Youtube (link only, not listed): https://www.youtube.com/watch?v=d5PWkodLjpo&feature=youtu.be

As you can see the scrolling is not smooth at all on the S7. I recorded it outside debug mode, so no debugger slowing it down. Using osmdroid 5.6.5. Any idea how to fix this?

**Comment by spyhunter99** [comment]
Might want to check to see what path the cache is being stored in. Also check for hardware acceleration on/off. Is this present with the sample application?

**Comment by spyhunter99** [comment]
any updates @bbb0x? hard for me to troubleshoot without the physical device

**Comment by roman-nevr** [comment]
I had the same problem. After `mapView.setLayerType(View.LAYER_TYPE_HARDWARE, null);`
all became smooth as silk
PS cache in private storage on disk

**Comment by spyhunter99** [comment]
closing due to lack of feedback, reopen or comment back if this is still a problem
