### ISSUE TITLE
在部分高性能的手机屏幕上，osmdroid mapview 在listview item holder 缓存时无法显示地图，这 估计是 osmdroid_mapview  的 一个bug ，，其他 view 不存在这个情况

### ISSUE THREAD

**Issue by lsc183183** [osmdroid/osmdroid#732]
Please note: issues related to or caused by osmbonuspack will be closed with a
suggested to open the issue at https://github.com/MKergall/osmbonuspack

(feel free to delete whatever doesn't apply)

## Issue Type

[ ] Question
[ ] Bug
[ ] Improvement
[ ] Build system related
[ ] Performance
[ ] Documentation

### If it's a bug, version(s) of android this affects:

All

### Version of osmdroid the issue relates to:

5.6.5

**Comment by lsc183183** [comment]
In some high-performance mobile phone screen, osmdroid Mapview in ListView item holder cache can not display map, this is estimated to be a bug in Osmdroid_mapview, the other view does not exist in this case

**Comment by spyhunter99** [comment]
Osmdroid is not simple text view. It is a complex,  multi threaded object.  I wouldn't recommend more than two running concurrently. There are some life cycle issues with recyclerviews

**Comment by lsc183183** [comment]
http://ww2.sinaimg.cn/large/0060lm7Tly1fkge7l0cmlj30920guq42.jpg

ListView Mapview Holder item for the first time can show the map, up and down after scrolling listview map will not show

**Comment by spyhunter99** [comment]
not sure what to tell you. try looking at adb logcat and troubleshoot from there. it's not an supported configuration. you may be better off identifying what tile you want for each item and displaying a static image rather than a full map.

**Comment by spyhunter99** [comment]
I just made a sample using a map in a list view and it is working just fine. Can you post your code or at least the relevant parts?

**Comment by spyhunter99** [comment]
you may want to switch to master of osmdroid or wait for the next release
