### ISSUE TITLE
Maximum Zoom: floating-point

### ISSUE THREAD

**Issue by Maradox** [osmdroid/osmdroid#734]
Since in the current master it is now possible to zoom by floating-point values, it would be nice to also allow a floating-point for the maximumZoom: `setMaxZoomLevel(double)`.

**Comment by spyhunter99** [comment]
Good idea

**Comment by spyhunter99** [comment]
@Maradox should this be a blocking issue for v6? or could it wait until a follow up version?

**Comment by Maradox** [comment]
It would be more consistent with the rest of the changes of v6. Do we need to keep the old methods or could we just replace them with their `double` versions? Maybe I have time for a PR this week. Otherwise I guess v6 could be shipped without it.
