### ISSUE TITLE
Looking for a restaurant

### ISSUE THREAD

**Issue by monsieurtanuki** [osmdroid/osmdroid#737]
## Issue Type
[X] Improvement

## Description
Provide
* a list of venues
* filtered by keywords/name/categories
* centered on a `GeoPoint` within a decent distance

Related to
* #530 online search on wikimapia data
* #660 offline search on OSM data

Questions:
* what are the potential sources (wikimapia.org, OSM, dbpedia.org, foursquare.com, kml files, ...)
* online/offline

**Comment by MKergall** [comment]
Note that OSMBonusPack provides access to POI services (online only) : Nominatim, OverpassAPI, and GeoNames. You can have a look here: 

- tps://github.com/MKergall/osmbonuspack/wiki/Tutorial_2
- https://github.com/MKergall/osmbonuspack/wiki/OverpassAPIProvider

**Comment by monsieurtanuki** [comment]
Awesome!

I'm not very familiar with the distinction between osmdroid and OSMBonusPack:
* do you implicitly mean that you give me "carte blanche" to adapt (/adopt) the regarded classes into osmdroid? Tricky question, because if you say "Yes it's implicit" it becomes explicit ;)
* or is it more like "just add OSMBonusPack to your app"
* or "if you need inspiration you can have a look at my implementation"

**Comment by MKergall** [comment]
Well, I see OSMBonusPack as an addon to osmdroid. I think that osmdroid should focus on "core" map features, additional libs (like OSMBonusPack, or others) providing additional features. 

I really love Leaflet approach: "While Leaflet is meant to be as lightweight as possible, and focuses on a core set of features, an easy way to extend its functionality is to use third-party plugins. Thanks to the awesome community behind Leaflet, there are literally hundreds of nice plugins to choose from."

We already moved some "core" features from OSMBonusPack to osmdroid (Marker, Polygon and Polyline, and some others). 
Of course, what should be a "core" feature for osmdroid largely vary depending on the point of view (what about KML support? marker clustering? routing?). 

From my point of view, POI subject is too broad (too many services, too many needs) to be integrated as a core feature. So I'm reluctant to move those classes to osmdroid. 

Now, depending on what you want to perform about POI, you can: 
- add OSMBonusPack in your app
- or propose a lib on top of OSMBonusPack, 
- or propose PRs on OSMBonusPack
- or propose an alternate lib, inspired (or not) by OSMBonusPack

**Comment by monsieurtanuki** [comment]
Thanks for the clarification.
I've just had a glimpse of OSMBonusPack and that's precisely what I thought was missing in osmdroid. Bravo!

I think OSMBonusPack should be presented more explicitly in osmdroid: that would help app developers choose osmdroid and OSMBonusPack. A bit like in [leafletjs.com/plugins.html](http://leafletjs.com/plugins.html): "osmdroid has the mandatory core features, and other obvious related features can be found in OSMBonusPack" (and potentially other sources)

**Comment by spyhunter99** [comment]
i agree with @MKergall. POI shouldn't be in osmdroid-android but in a separate module or project.  It's a large feature set that requires infrastructure to support. Offline is sort of feasible by quite slow. From following the osmbonuspack repo, it looks like POI's APIs change frequently and seem to be a constant source of issues reported there. Perhaps it would be a good home for the wikimapia stuff i was working on (separate repo).

The recent addons for geopackage, wms, mapsforge, etc are in this repo, but as separate modules. This at least makes integration testing easier.

@monsieurtanuki good idea, maybe updating the readme would be sufficient. We also have a wiki page for related projects.

Do we need a plugin API or some other API to make make integration easier? I've done cross APK class/resource loading before so that definitely possible. Currently, I think the answer is no.

**Comment by MKergall** [comment]
@spyhunter99 I don't think we can and we need to define a general purpose plugin mechanism. 
We can define "standard ways" for dedicated purposes - typically by defining interfaces or base classes, as osmdroid already does for overlays, or tile management. 

I was not aware of wikimapia. Seems interesting. At first glance, it looks like it could be supported more or less the same way OverpassAPI has been integrated in OSMBonusPack?

**Comment by monsieurtanuki** [comment]
@spyhunter99 Indeed, writing more explicit wiki pages is a solution.
Something like bullet points answering the questions "what is osmdroid and what can I do with osmdroid and its related projects?", potentially with the name of a demo activity in the demo app:
* raster tile based (no vector), with several free tile providers
* zoom 0 to 29
* tiles available online/offline/embedded, with pre-caching options
* POI Markers, Polylines, Polygons
* My current location
* KML / geojson (with OSMBonusPack)
* POI search (with OSMBonusPack)
* Routing (with OSMBonusPack)
* ...

**Comment by spyhunter99** [comment]
https://github.com/osmdroid/osmdroid/wiki/Capabilities

how about that? you should be able to edit it

**Comment by MKergall** [comment]
Good start! And we edit it!

**Comment by monsieurtanuki** [comment]
That's exactly what I had in mind!

**Comment by spyhunter99** [comment]
@monsieurtanuki unrelated, but i just updated this one
https://github.com/osmdroid/osmdroid/wiki/Modular-Tile-Provider-Architecture

any comments welcome on the diagrams. When i first joined osmdroid, i was super confused on the tile loading structure. I hope this adds some clarity to it

**Comment by monsieurtanuki** [comment]
@spyhunter99 My comments on the diagrams: in general I'm not a big fan of UML diagrams - partly because I'm not fluent in UML :)
I prefer paragraphs with bullets like "Tile Provider Modules" or "File System Cache Model" - where the diagrams could even be removed as they are just the same as the text, but with less information.

A little comment beyond the diagrams: I would explicitly mention key methods - like `MapTileProviderArray.getMapTile(final MapTile pTile)` - where developers can actually see the mechanics if needed.

**Comment by spyhunter99** [comment]
well we can also direct link to the javadocs...
http://osmdroid.github.io/osmdroid/javadocAll/index.html

**Comment by spyhunter99** [comment]
direct link http://osmdroid.github.io/osmdroid/javadocAll/index.html?org/osmdroid/tileprovider/MapTileProviderArray.html

**Comment by monsieurtanuki** [comment]
As an open source dev contributor, my personal expectations of online docs is a light overview of the key concepts (like Tile Provider, Tile Source), and then a list of the most relevant classes / methods, with access to details (links to javadocs or actual code).
Most of the time I get very rapidly into the code.
