### ISSUE TITLE
how to store tiles in assets

### ISSUE THREAD

**Issue by elluminati10** [osmdroid/osmdroid#738]
Is there any way to store map in assets instead of store in cache.

**Comment by spyhunter99** [comment]
Yes but it can't be changed on device.  The sample app has a few tiles

**Comment by elluminati10** [comment]
how much tiles are store in assets?

**Comment by spyhunter99** [comment]
there are effective limits to APKs both in terms of quantity and size. I wouldn't do a whole lot. It's actually faster, less cpu intensive to use sqlite. You can package the sqlite in your apk and then copy it out at runtime, but again, there are limits to how big stuff can be in the assets folder

**Comment by spyhunter99** [comment]
but sorry i don't know the limits. I think the APK size is limited by google play to 100MB, but if you are distributing your app yourself, i don't believe there's a limit. i think the assets limit is around 65k
