### ISSUE TITLE
Offline Map not showing

### ISSUE THREAD

**Issue by prabin525** [osmdroid/osmdroid#740]
I am trying to use offline maps with osmdroid. I have created the tiles and stored in the osmdroid directory.

`map.setUseDataConnection(false);

        File f = new File(Environment.getExternalStorageDirectory().getAbsolutePath() + "/osmdroid/");

        if (f.exists()) {
            File[] list = f.listFiles();
            if (list != null) {
                for (int i = 0; i < list.length; i++) {
                    if (list[i].isDirectory()) {
                        continue;

                    }
                    String name = list[i].getName().toLowerCase();
                    if (!name.contains(".")) {
                        continue; //skip files without an extension
                    }
                    name = name.substring(name.lastIndexOf(".") + 1);
                    if (name.length() == 0) {
                        continue;
                    }
                    if (ArchiveFileFactory.isFileExtensionRegistered(name)) {
                        try {
                            OfflineTileProvider tileProvider = new OfflineTileProvider(new SimpleRegisterReceiver(context),
                                    new File[]{list[i]});
                            String source = "";
                            IArchiveFile[] archives = tileProvider.getArchives();
                            if (archives.length > 0) {
                                Set<String> tileSources = archives[0].getTileSources();

                                if (!tileSources.isEmpty()) {
                                    source = tileSources.iterator().next();
                                    map.setTileSource(FileBasedTileSource.getSource(source));
                                } else {
                                    map.setTileSource(TileSourceFactory.MAPNIK);
                                    Toast.makeText(context,"error 1", Toast.LENGTH_SHORT).show();
                                }

                            } else {
                                map.setTileSource(TileSourceFactory.MAPNIK);
                                Toast.makeText(context,"error 2", Toast.LENGTH_SHORT).show();
                            }

                            Toast.makeText(context, "Using " + list[i].getAbsolutePath() + " " + source, Toast.LENGTH_SHORT).show();
                        } catch (Exception ex) {
                            ex.printStackTrace();

                        }
                    }
                }
            }
        }`

The code i have used is as above and the toast message also appears using OSMPublicTransport but i can't see the tiles of the map.

The logcat is as below 

`10-16 17:14:33.134 10626-10626/np.com.techkunja.vtracker.vtracker_driverapp I/StorageUtils: /storage/emulated/0 is writable
10-16 17:14:33.135 10626-10626/np.com.techkunja.vtracker.vtracker_driverapp I/StorageUtils: /sdcard is writable
10-16 17:14:33.138 10626-10626/np.com.techkunja.vtracker.vtracker_driverapp I/StorageUtils: /mnt/sdcard is writable
10-16 17:14:33.194 10626-10626/np.com.techkunja.vtracker.vtracker_driverapp I/OsmDroid: Using tile source: Mapnik
10-16 17:14:33.229 10626-10626/np.com.techkunja.vtracker.vtracker_driverapp I/OsmDroid: sdcard state: mounted`

the logcat gives using tile source of Mapnik still. What's the problem here

**Comment by spyhunter99** [comment]
a few things to try.

1. did you step through the code to determine if the correct offline source is being selected?
2. unfortunately we don't have the ability to determine what zoom levels and bounds are available in each archive or tile source. You may want to consider setting the map center and zoom level based on some tiles that you know are in the archives you have

**Comment by spyhunter99** [comment]
closing due to lack of feedback/response. reopen or comment back if this is still an issue
