### ISSUE TITLE
ScrollableAreaLimit not working

### ISSUE THREAD

**Issue by Maradox** [osmdroid/osmdroid#742]
With the new changes `setScrollableAreaLimit` does not work correctly anymore, but limits the area at "random" borders.

I believe this is due to the fact that the relative scroll-position changed.

**Comment by monsieurtanuki** [comment]
I'll have a look at it this week, but I'm not very familiar with the concept of `scrollableAreaBoundingBox`.
Could we sum it up that way in `MapView.scrollTo`:
* I compute the screen x of bounding box left longitude. If the value is <= 0, it's OK, or else I subtract this value from the scroll x
* I compute the screen x of bounding box right longitude. If the value is >= screen width, it's OK, or else I add this value to the scroll x
* similar things for top and bottom

Of course that doesn't work very well if the bounding box is smaller than the screen (for very low zoom level for instance).
@Maradox Should there be an alternate algorithm for that limit case, and if yes what is it? Something like the bounding box longitude center should be in the middle of the screen (same for latitude)?
