### ISSUE TITLE
Double-Tap-Zoom ignores location of zoom

### ISSUE THREAD

**Issue by Maradox** [osmdroid/osmdroid#745]
A double-tap-zoom zooms the map in, but ignores the location of the finger where the tap was made.

In earlier versions of osmdroid, if the user made a double-tap-zoom in the right-top corner of the map, the map zoomed in and scrolled slightly to the right-top corner. This slight scroll for double-taps is now gone.

**Comment by monsieurtanuki** [comment]
@Maradox Thank you for your accurate tests.
I just fixed the bug - but as I don't understand it fully (it's not obvious for me where the map should recenter - I found my inspiration for the fix in an older version of the code) it would be nice if you could check if the result matches your expectations.

**Comment by Maradox** [comment]
@monsieurtanuki 
There is an issue with the new implementation.
* Double-Tap at right-top
* The map view animates correctly closer to the right-top
* When the animation is finished, the map view snaps the scroll back, to where it would be without this change

So the animation itself now behaves correctly (similar to old osmdroid versions). But after the animation the scroll-position of the "old" center is used.

I pulled master and have currently the following commit: `8badfdf52d0d960000a325a844a6fc16fa29c2c1`

**Comment by monsieurtanuki** [comment]
@Maradox I think I just fixed it in #751
