### ISSUE TITLE
Error:(18, 28) error: package org.osmdroid.library does not exist

### ISSUE THREAD

**Issue by Ponywka** [osmdroid/osmdroid#748]
[ ] Question
[ ] Bug
[ ] Build system related

### Version of osmdroid the issue relates to:

5.6.5

Error:(18, 28) error: package org.osmdroid.library does not exist

**Comment by spyhunter99** [comment]
is this a compile issue or runtime? any more context?

**Comment by Ponywka** [comment]
is this a compile issue

**Comment by spyhunter99** [comment]
ok, it's probably a gradle issue. can you post the dependency line where you are referencing osmdroid?

**Comment by Ponywka** [comment]
import org.osmdroid.library.R;

**Comment by spyhunter99** [comment]
`build.gradle`... you did follow the setup guide right?

**Comment by spyhunter99** [comment]
https://github.com/osmdroid/osmdroid/wiki

**Comment by Ponywka** [comment]
I did not understand him at all, for I'm new.

**Comment by spyhunter99** [comment]
are you using android studio or something else? I suggest you start googling stuff for getting starting with android development and gradle

**Comment by Ponywka** [comment]
I'm using Android Studio. 
I already managed to initialize the cards! https://pp.userapi.com/c840632/v840632251/1724b/207-EHRTsY8.jpg
