### ISSUE TITLE
Add id fields for polyline and polygon

### ISSUE THREAD

**Issue by spyhunter99** [osmdroid/osmdroid#749]
Please note: issues related to or caused by osmbonuspack will be closed with a
suggested to open the issue at https://github.com/MKergall/osmbonuspack

(feel free to delete whatever doesn't apply)

## Issue Type

[ ] Question
[ ] Bug
[x ] Improvement
[ ] Build system related
[ ] Performance
[ ] Documentation

## Description and/or steps/code to reproduce the problem

Adds gettings/settings for polyline and polygon objects to aid with kml parsing, as described https://github.com/MKergall/osmbonuspack/issues/306

**Comment by jenia** [comment]
Hi. I think the problem is in the [buildOverlay](https://github.com/MKergall/osmbonuspack/blob/master/OSMBonusPack/src/main/java/org/osmdroid/bonuspack/kml/KmlLineString.java#L59) function. I think we need to add functionality there to set the ID on the `Polyline lineStringOverlay`
