### ISSUE TITLE
osmdroid vs google map api v2

### ISSUE THREAD

**Issue by ahmadii** [osmdroid/osmdroid#75]
Hi,
i want to know is it possible to use google map api v2 features (like 3d view) in osmdroid?

**Comment by barbeau** [comment]
Isn't there a wrapper, though, that allows use of methods from the Maps V2 spec?

https://code.google.com/p/osmdroid/issues/detail?id=478

Is there any documentation that describes how to use this?

**Comment by neilboyd** [comment]
There's no documentation, but there is an example app.

**Comment by barbeau** [comment]
@neilboyd Sorry - I wasn't very clear in my original post - are you referring to https://github.com/osmdroid/osmdroid/blob/master/GoogleWrapperSample/src/org/osmdroid/google/sample/GoogleWrapperSample.java?

It looks like this uses an interface (`org.osmdroid.api.IMap`) to interact with multiple underlying implementations.  This is nice, but I was actually looking for way to essentially swap out the import statements for a Google Maps API v2 implementation, and use osmdroid instead.  I already have this set up using Gradle build flavors for Amazon Maps, and osmdroid would be a simple addition as another build flavor if the classes followed the same Maps API v2 structure.  

For example, the following imports for Amazon Maps v2:

~~~
import com.amazon.geo.mapsv2.AmazonMap;
import com.amazon.geo.mapsv2.Projection;
import com.amazon.geo.mapsv2.model.BitmapDescriptor;
import com.amazon.geo.mapsv2.model.BitmapDescriptorFactory;
import com.amazon.geo.mapsv2.model.LatLng;
import com.amazon.geo.mapsv2.model.Marker;
import com.amazon.geo.mapsv2.model.MarkerOptions;
~~~

...would be changed to something like:

~~~
import org.osmdroid.geo.mapsv2.AmazonMap;
import org.osmdroid.geo.mapsv2.Projection;
import org.osmdroid.geo.mapsv2.model.BitmapDescriptor;
import org.osmdroid.geo.mapsv2.model.BitmapDescriptorFactory;
import org.osmdroid.geo.mapsv2.model.LatLng;
import org.osmdroid.geo.mapsv2.model.Marker;
import org.osmdroid.geo.mapsv2.model.MarkerOptions;
~~~

Is this possible given the current osmdroid library?

I was searching the repo for equivalent objects like LatLng and couldn't find them, but I wanted to make sure I wasn't missing something (or if these objects could be imported from the Google namespace instead, and still be functional with OSM).

If not, I'll probably need to look at adopting something like wrappers/interfaces currently used in osmdroid.
