### ISSUE TITLE
Can Osmdroid be tested with Robelectric?

### ISSUE THREAD

**Issue by pasniak** [osmdroid/osmdroid#750]
Can Osmdroid be tested with Robelectric?  Does anyone have an example of an app with osmdroid tested with Robelectric?

## Issue Type

[x] Question

I get NullPointerException exception in setOnZoomListener when I try to run my test. The android app works fine but I do not break in this location when I run the regular app (AS says "no executable code found at line 290 in android.widgets.ZoomButtonsController).  It is a bit strange...

 ```
    public void setOnZoomListener(OnZoomListener listener) {
        mCallback = listener; // NullPointerException here....
    }
 ```

 ```
   testCompile 'junit:junit:4.12'
    testCompile "org.mockito:mockito-core:2.4.0"
    testCompile 'org.powermock:powermock-module-junit4:1.7.0RC2'
    testCompile 'org.powermock:powermock-api-mockito2:1.7.0RC2'
    testCompile 'org.powermock:powermock-classloading-xstream:1.7.0RC2'
    testCompile 'org.powermock:powermock-module-junit4-rule:1.7.0RC2'
    testCompile "org.robolectric:robolectric:3.4.2"
    testCompile "org.robolectric:shadows-maps:3.4-rc2"
    testCompile "org.robolectric:shadows-play-services:3.4-rc2"
    testCompile "org.robolectric:shadows-support-v4:3.4-rc2"
    testCompile 'org.robolectric:shadows-multidex:3.4-rc2'
```
and my test prototype (Kotlin):

```
@RunWith(RobolectricTestRunner::class)
class SandwichTest {


    @Test
    fun testDbReady () {
        val activity = Robolectric.setupActivity(FullscreenActivity::class.java)
    }

    @Before
    fun setUpMockito() {
        MockitoAnnotations.initMocks(this)
    }

    @After
    fun tearDownMockito() {
        Mockito.validateMockitoUsage()
    }
}
```

### Version of osmdroid the issue relates to:

5.6.5 from jar

**Comment by pasniak** [comment]
I created a sample test similar to the Android instrumentation test which runs in 8s. Now need to figure out why my app's test fails...
https://github.com/osmdroid/osmdroid/compare/master...pasniak:feature/%23750?expand=1

**Comment by spyhunter99** [comment]
not too familiar with robo...how is it different from the android instrumentation test runners? (hopefully it's better)

**Comment by spyhunter99** [comment]
was leak canary causing issues with the test?

**Comment by pasniak** [comment]
I have not focused too much on the canary, thinking it could be made optional or I could spend time checking how to fix.

Robo does not require emulator running, so we can have a fast battery of tests, much faster than Android's instrumentation. Ex: https://github.com/apps4av/avare/blob/master/app/src/test/java/com/ds/avare/test/DestinationGpsTest.java

**Comment by spyhunter99** [comment]
well that's neat

**Comment by pasniak** [comment]
On my new Linux box (AS 3.0.0, SSD) the tests run in 3.7s ! I had to upgrade the canary to 1.5.4 and android.minSdkVersion=14 (from 8)

**Comment by pasniak** [comment]
I am trying to run the robolectric test with the latest 6.0.0 local debug build and it hangs on `edit.commit()` in

```
            Editor edit = prefs.edit();
            edit.putString("osmdroid.basePath", discoveredBestPath.getAbsolutePath());
            edit.putString("osmdroid.cachePath", discoveredCachPath.getAbsolutePath());
            edit.commit();
```

I was able to repro this hang in my test outside osmdroid. I can set these location in the "Before" code so I can avoid the hang but I am curious why not use edit.apply() here? (which works in my test as `!prefs.contains("osmdroid.basePath")` is true)

**Comment by spyhunter99** [comment]
it was probably from looking at the javadocs. commit is written immediately, apply is written eventually. If it's hanging on commit,  could it be an issue with permissions? Was commit changed at some point?

**Comment by monsieurtanuki** [comment]
If I remember well, `apply` is recommended: same result and no lock. "Eventually" here means that the value will be _immediately_ set and available, and _eventually_ committed. Something like a data immediately available in memory and eventually written to the preferences file.

**Comment by spyhunter99** [comment]
commit is save now, apply is save eventually. I'm not sure what the actual recommendation is.

**Comment by monsieurtanuki** [comment]
[https://developer.android.com/reference/android/content/SharedPreferences.Editor.html#apply()](https://developer.android.com/reference/android/content/SharedPreferences.Editor.html#apply())

> Unlike commit(), which writes its preferences out to persistent storage synchronously, apply() commits its changes to the in-memory SharedPreferences immediately but starts an asynchronous commit to disk and you won't be notified of any failures. If another editor on this SharedPreferences does a regular commit() while a apply() is still outstanding, the commit() will block until all async commits are completed as well as the commit itself.
As SharedPreferences instances are singletons within a process, it's safe to replace any instance of commit() with apply() if you were already ignoring the return value.

**Comment by pasniak** [comment]
I would suggest this change: https://github.com/pasniak/osmdroid/commit/fe2cc6144f47ef21bf229b89993cd8e63ce710ec

**Comment by monsieurtanuki** [comment]
@pasniak Now that the code is merged, should the issue be closed?
