### ISSUE TITLE
Publish 6.0.0-SNAPSHOT

### ISSUE THREAD

**Issue by Vandalko** [osmdroid/osmdroid#756]
I may be blind, but can't find it on https://oss.sonatype.org/content/groups/public/org/osmdroid/osmdroid-android/

What is blocking publications ?

**Comment by spyhunter99** [comment]
Nothing is being blocked. It hasn't been published yet.  If you want I can publish a snapshot tonight. Keep in mind, there are so several open issues that are still being worked

**Comment by Vandalko** [comment]
Well, unless there are some regressions, I would like to see a new build.
Mainly due to `zoomToBoundingBox` fix - I've noticed a slight improvement comparing to 5.6.5 version.

**Comment by spyhunter99** [comment]
k, working on publishing a snapshot now... I was a bit hesitant to cut 6.0 due to a number of open issues and discussions regarding hardware acceleration

**Comment by spyhunter99** [comment]
https://oss.sonatype.org/content/repositories/snapshots/org/osmdroid/osmdroid-android/6.0.0-SNAPSHOT/
