### ISSUE TITLE
Work with SQLIte file

### ISSUE THREAD

**Issue by geminixandroid** [osmdroid/osmdroid#759]
## Issue Type
[ ] Question
## Description and/or steps/code to reproduce the problem
If i have map from MOBAC in osmdroid sqlite format, put it in /osmdroid/map.sqlite,
what source need to write in programm?
Need simple example of SQLite usage.
`map.setTileSource(???) ;`

**Comment by spyhunter99** [comment]
The name of the layer in mobac becomes the tile source name. This can be verified by using the following sql statement against the sqlite database using sqlite3 (cmd line executable) or by using the firefox sqlite plugin

`SELECT distinct(provider) from tiles`

whatever the output is becomes the tile source name, so `new XYSource(provider, 0 18, 256, "", new String[0]);`

**Comment by spyhunter99** [comment]
@geminixandroid did you get it working?

**Comment by spyhunter99** [comment]
closing due to no feedback
