### ISSUE TITLE
Question : Detect touch on map

### ISSUE THREAD

**Issue by mf-mindcrewtech** [osmdroid/osmdroid#765]
How can I detect touch on mapview?

**Comment by pasniak** [comment]
In general: add an overlay and a click listener. For example:
https://github.com/osmdroid/osmdroid/wiki/How-to-use-the-osmdroid-library#how-do-i-place-icons-on-the-map-with-a-click-listener

**Comment by mf-mindcrewtech** [comment]
No no my question is about getting touch on map as I need to built some functionality like stop my tabs to swipe when map is in  touch mode

**Comment by spyhunter99** [comment]
one method is to add a transparent view on top of the map, then override the touch input listener on that view. If you aren't handling it, pass to the new view (the map). There's an example here:
https://github.com/osmdroid/osmdroid/blob/master/OpenStreetMapViewer/src/main/java/org/osmdroid/samplefragments/drawing/CustomPaintingSurface.java

it's used in the following sample fragment in the demo app
https://github.com/osmdroid/osmdroid/blob/master/OpenStreetMapViewer/src/main/java/org/osmdroid/samplefragments/drawing/SampleDrawPolyline.java

**Comment by vnhnhm** [comment]
https://github.com/osmdroid/osmdroid/issues/295
