### ISSUE TITLE
Question: Can we convert OSM map to english

### ISSUE THREAD

**Issue by mf-mindcrewtech** [osmdroid/osmdroid#769]
I don't want to use in native languages for the countries, Its better to translate the whole map in english? Is it possible?? @spyhunter99

**Comment by secaw** [comment]
Sorry, osmdroid is not responsible for the content of map sources like OpenStreetMap. If you want to have a map in english only you have to look for a different map source, e.g. other flavors of OSM like Thunderforest for example.

**Comment by spyhunter99** [comment]
exactly. osmdroid just displays the map tiles and has no knowledge of the content of the tiles.
