### ISSUE TITLE
Add a getBoundingBox method in Overlay class

### ISSUE THREAD

**Issue by MKergall** [osmdroid/osmdroid#770]
## Issue Type

[ ] Question
[ ] Bug
[X] Improvement
[ ] Build system related
[ ] Performance
[ ] Documentation

Purpose: allow generic objects to compute bounding boxes.
One key usage will be in FolderOverlay:

1. We will be able to implement an optimized FolderOverlay.draw method, handling culling based on bounding boxes. We can get massive performance improvement when displaying big structured overlays (a common use case when loading KML/GeoJson files).
2. The bounding box is needed to zoom on a specific overlay.

Implementation: Overlay.getBoundingBox could be either abstract (imposing all derived classes to implement it), or return a default bounding box planet-wide, or return null. Not sure yet what is the best choice.

**Comment by spyhunter99** [comment]
there are some related algorithms in the geopackage source. Everytime something is added to a overlay that contains multiple items, it runs a function to expand the bounds of the parent overlay as needed. Fairly simply to port

**Comment by MKergall** [comment]
The algorithm for FolderOverlay is very simple to implement. I already have something similar in my KML stuff. 
My request is just: can we add this getBoundingBox method at Overlay level, or not.

**Comment by monsieurtanuki** [comment]
My two cents:
* I would implement `getBoundingBox` as null by default
* It might be tricky to dismiss the display of some `Overlay`s because of their "beyond the current map" bounding box, if you take the example of `Marker`s slightly outside of the `MapView` but to be displayed with a big icon that should appear (partly) on the map. Cf. a code I edited in `ItemizedOverlay.onDrawItem` that now involves `Rect.intersects`

**Comment by spyhunter99** [comment]
@MKergall you don' t have to ask for permission. Of course we can. Are you writing this or is this just a good idea kind of thing and you're looking for someone else to write it?

**Comment by spyhunter99** [comment]
@MKergall ping

**Comment by spyhunter99** [comment]
working this now, it makes a huge difference!
