### ISSUE TITLE
MapView in a ViewPager don't scroll horizontally

### ISSUE THREAD

**Issue by ycuicui** [osmdroid/osmdroid#771]
## Issue Type
[x] Bug
[x] Improvement

## Description
A MapView in a ViewPager can't scroll horizontally because the ViewPager intercept the scroll gesture and swipe the views. Note that vertical scrolling works fine.
 
After searching around a solution was found by adding two lines in the `onTouchEvent()` method:
```java
@Override
public boolean onTouchEvent(MotionEvent event) {
	// Prevent  the ViewPager to swipe its views
	// See https://stackoverflow.com/questions/8594361/horizontal-scroll-view-inside-viewpager
	if (event.getAction() == MotionEvent.ACTION_MOVE && getParent() != null) {
		getParent().requestDisallowInterceptTouchEvent(true);
	}
	return false;
} 
```
This could be enhanced by detecting (in an `ACTION_DOWN`) that the user initiate the scroll near the left or right border and then not calling `requestDisallowInterceptTouchEvent(true)` in that case.

This was suggested [here](https://stackoverflow.com/questions/8594361/horizontal-scroll-view-inside-viewpager)

My 2 cents
Yves

**Comment by spyhunter99** [comment]
Related sample
https://github.com/osmdroid/osmdroid/blob/master/OpenStreetMapViewer/src/main/java/org/osmdroid/samplefragments/layouts/MapInAViewPagerFragment.java

**Comment by spyhunter99** [comment]
@ycuicui was that line of code added in map view or in the view pager?

**Comment by ycuicui** [comment]
The lines where added in the MapView

**Comment by spyhunter99** [comment]
Thanks for the code. I'm a bit leary to commit this, but it's fairly simple for someone to extend MapView and just copy and paste your fix. Not everyone uses the map in a view pager and i'm unsure if there will be an unintended side effects from the code.

**Comment by ycuicui** [comment]
I think that use of ViewPager is a common pattern. However i did not notice any regression and this is so simple that you could commit it without fear!
To be complete, and for those that could be interrested in the workaround, i use the following code to allow swiping the ViewPager by touching the screen borders:

```java
// true if we intercep MOVE events in order to prevent the view pager to swipe views
private boolean intercepMove = false;

@Override
public boolean onTouchEvent(MotionEvent event) {
	// Prevent  the ViewPager to swipe instead of scrolling
	// See https://stackoverflow.com/questions/8594361/horizontal-scroll-view-inside-viewpager
	// Touching the borders allow the view pager to swipe
	switch (event.getAction()) {
		case MotionEvent.ACTION_DOWN:
			// See if we touch the screen borders
			intercepMove = event.getX() > rightLimit && event.getX() < leftLimit;
			break;
		case MotionEvent.ACTION_MOVE:
			if (intercepMove && getParent() != null) {
				getParent().requestDisallowInterceptTouchEvent(true);
			}
	}
	return false;
}
```

**Comment by spyhunter99** [comment]
@ycuicui what are you using for right and left limits?

**Comment by ycuicui** [comment]
I use 5% of map width for left limit and 95% for right limit 

Sorry just saw i made a mistake in the above code. Should be read as:

```Java
// true if we intercep MOVE events in order to prevent the view pager to swipe views
private boolean intercepMove = false;

@Override
public boolean onTouchEvent(MotionEvent event) {
	// Prevent  the ViewPager to swipe instead of scrolling
	// See https://stackoverflow.com/questions/8594361/horizontal-scroll-view-inside-viewpager
	// Touching the borders allow the view pager to swipe
	switch (event.getAction()) {
		case MotionEvent.ACTION_DOWN:
			// See if we touch the screen borders
			intercepMove = 100 * event.getX() > 5 * getWidth() && 100 * event.getX() < 95 * getWidth();
			break;
		case MotionEvent.ACTION_MOVE:
			if (intercepMove && getParent() != null) {
				getParent().requestDisallowInterceptTouchEvent(true);
			}
	}
	return false;
}
```
Sorry.

**Comment by spyhunter99** [comment]
i'm going to close this as it is super simple to extend the MapView in your own class and add the fix. Users (like @ycuicui ) may want to use custom values for the buffer sizes based on use cases

**Comment by spyhunter99** [comment]
thanks for the contribution though!

**Comment by ycuicui** [comment]
OK
Anyway, if you want to see this in action, you can try my app https://play.google.com/store/apps/details?id=com.panaustik.geotrack
Thanks for your nice work.

**Comment by spyhunter99** [comment]
looks great! i'll add it to the wiki
