### ISSUE TITLE
hide map on high zoom level

### ISSUE THREAD

**Issue by turrigni** [osmdroid/osmdroid#772]
Please note: issues related to or caused by osmbonuspack will be closed with a
suggested to open the issue at https://github.com/MKergall/osmbonuspack

(feel free to delete whatever doesn't apply)

## Issue Type

[X] Question
[ ] Bug
[ ] Improvement
[ ] Build system related
[ ] Performance
[ ] Documentation

## Description and/or steps/code to reproduce the problem

I use only offline map with max zoom level 9.
Is possible hide map and show only polylines when zoom is greater of 9?

### If it's a bug, version(s) of android this affects:

All

### Version of osmdroid the issue relates to:

5.6.5

**Comment by spyhunter99** [comment]
If you set your own tile provider chain when you hit zoom 9, then reset to make whatever your business rules are, it should be possible.

**Comment by turrigni** [comment]
On attach of fragment I load file with this code:

```
        File[] list = f.listFiles();
        if (list != null) {
            for (int i = 0; i < list.length; i++) {
                final File fileTemp = list[i];
                if (fileTemp.isDirectory())
                    continue;
                String name = fileTemp.getName().toLowerCase();
                if (!name.contains("."))
                    continue;
                name = name.substring(name.lastIndexOf(".") + 1);
                if (name.length() == 0)
                    continue;
                if (ArchiveFileFactory.isFileExtensionRegistered(name) && name.equals("mbtiles")) {
                    try {
                        OfflineTileProvider tileProvider = new OfflineTileProvider(new SimpleRegisterReceiver(getActivity()), new File[]{fileTemp});
                        readZoomLevel(fileTemp);
                        mapView.setTileProvider(tileProvider);
                        mapView.invalidate();
                        return;
                    } catch (Exception ex) {
                        ex.printStackTrace();
                    }
                }
            }
        }
```
can you help me with other indication?

**Comment by Maradox** [comment]
You can subclass `OfflineTileProvider ` and override `getMapTile()` accordingly (e.g.: return null if zoom is greater than 9).
