### ISSUE TITLE
Change Green arrow icon to custom icon for current location

### ISSUE THREAD

**Issue by mf-mindcrewtech** [osmdroid/osmdroid#777]
Hi, I am trying to change the green arrow icon for current location with my custom icon.

MyLocationNewOverlay myLocationoverlay = new MyLocationNewOverlay(new GpsMyLocationProvider(getActivity()), country_all_mapview);

            Drawable currentDraw = ResourcesCompat.getDrawable(getResources(), R.drawable.current_location, null);
            Bitmap currentIcon = null;
            if (currentDraw != null) {
                currentIcon = ((BitmapDrawable) currentDraw).getBitmap();
            }

            myLocationoverlay.setPersonIcon(currentIcon);
            myLocationoverlay.setDrawAccuracyEnabled(true);
          
            myLocationoverlay.enableMyLocation();
            country_all_mapview.getOverlays().add(myLocationoverlay);

But this still shows the green icon. Can anyone please let me know, what i am doing incorrect here.

Thanks

**Comment by carcme** [comment]
Does your myLocationoverlay extend DirectedLocationOverlay?? If it does, use setDirectionArrow(<bitmap>)

**Comment by mf-mindcrewtech** [comment]
Thanks @carcme. Appreciate your help 👍
