### ISSUE TITLE
Cannot use maperitive generated mbtiles

### ISSUE THREAD

**Issue by deaapt** [osmdroid/osmdroid#778]
My code.

 ```
@Override
protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        // Check permissions.
        checkPermissions();

        Configuration.getInstance().setDebugMode(true);
        MapView mapView = findViewById(R.id.map);
        mapView.setClickable(true);
        mapView.setBuiltInZoomControls(true);
        mapView.setMultiTouchControls(true);
        mapView.setUseDataConnection(false);
        mapView.setTileSource(new XYTileSource("My Map", 0, 16, 256, ".png", new String[]{}));

        IMapController mapViewController = mapView.getController();
        mapViewController.setZoom(1);
}
```

I have generated a mbtiles file using Maperitive.net program with the following command: generate-mbtiles minzoom=0 maxzoom=16. Then I placed the file in the osmdroid folder and running the program just shows me blank tiles, with the word "scaled" all over these white tiles. Logcat shows a bunch of "Tile doesn't exist"

I've checked the name in the metadata table, it's the same. Also there's a json file created with the name on the tiles but even so I went ahead and checked the tables with a sqlite reader. I'm out of ideas, it should be supported since it's on wiki...

Weird enough, using MOBAC with the sqlite mode, it worked fine.

**Comment by spyhunter99** [comment]
use the sqlite3 command line utility and run the following query

select distinct (provider) from tiles;

**Comment by spyhunter99** [comment]
related https://github.com/osmdroid/osmdroid/issues/759

**Comment by deaapt** [comment]
Tiles table doesn't have a provider field, so that query doesn't return me anything. Metadata table has a name field and that's the one I used on for the source name.

I managed to make it work by comparing two sqlite files (one from MOBAC that was working and the one not working from Maperitive) , I noticed Maperitive sqlite db didn't had indexes while MOBAC had indexes created. So I edited the db, created the two missing indexes and changed the page size to 4096 (it was 1024), saved the changes and it started working.

**Comment by spyhunter99** [comment]
cool, thanks for the fix info.

**Comment by cityofkokomo** [comment]
> Tiles table doesn't have a provider field, so that query doesn't return me anything. Metadata table has a name field and that's the one I used on for the source name.
> 
> I managed to make it work by comparing two sqlite files (one from MOBAC that was working and the one not working from Maperitive) , I noticed Maperitive sqlite db didn't had indexes while MOBAC had indexes created. So I edited the db, created the two missing indexes and changed the page size to 4096 (it was 1024), saved the changes and it started working.

@deaapt I know this thread is a bit old, but I was hoping you'd be able to help me out. I am attempting to use the MBtiles file made by Maperitive on a tileserver-gl server that I am running. I am running into the same issue, the metadata is missing, and I was wondering if you have documentation, or a work flow, to add that missing metadata as you did with your file.

I am working with tileserver-gl on an EC2 instance of Ubuntu 20.04, but Maperitive is running on a windows 10 machine.

**Comment by CodeK1988** [comment]
@spyhunter99 @cityofkokomo @deaapt hi mate, has your problem been solved? I encountered that the mbtiles file downloaded on maptiler could not be loaded normally, but the one downloaded on mobac could be loaded. But there are tile limit on downloading maps on mobac.
