### ISSUE TITLE
Permission Infliction

### ISSUE THREAD

**Issue by Maradox** [osmdroid/osmdroid#779]
Currently osmdroid uses the following permissions:

* `ACCESS_FINE_LOCATION`
* `ACCESS_COARSE_LOCATION`
* `ACCESS_WIFI_STATE`
* `ACCESS_NETWORK_STATE`
* `INTERNET`
* `WRITE_EXTERNAL_STORAGE`
* `READ_EXTERNAL_STORAGE`

However, not all of these permissions are mandatory. For example the location permissions are only required if you want to show your own location. I would propose that only the permissions which are absolutely required should be included automatically. Otherwise users of the library either add unnecessary permissions without knowing, or have to exclude them in their manifest.

If I know which permissions are mandatory, and which are required for certain featues, I would create a PR.

**Comment by spyhunter99** [comment]
write store is only needed for storing tiles. If it's not available osmdroid should default to application private storage. Fine location is needed for GPS related stuff. It's not required.  Internet is needed for downloading tiles. Wifi and network state used to detect if you are network connected or not. Does this help?

**Comment by Maradox** [comment]
@spyhunter99 Thanks for the info. Created a PR.
