### ISSUE TITLE
Map don't work without SD card.

### ISSUE THREAD

**Issue by nightmare00** [osmdroid/osmdroid#78]
Hi! Is it possible to use osmdroid 4.3 without a SD card?

**Comment by k3b** [comment]
Currently all osmdroid apps on one device share the same cache so one app might have downloaded map-tiles that are used by an other app. Will this still be possible with android4.4 ?

**Comment by k3b** [comment]
> Map don't work without SD card

Has anybody tried to use OsmDroid with "org.osmdroid.tileprovider.modules.MapTileAssetsProvider.java" and without android.permission.INTERNET and without android.permission.WRITE_EXTERNAL_STORAGE?

SD-Card-cache should only be necessary when downloading map-tiles from internet. If the tiles are loaded from app-s asset folder there should be no need for WRITE_EXTERNAL_STORAGE.

**Comment by spyhunter99** [comment]
Yes, it should work. We'll be merge a branch soon to let you change the download location using @MKergall's patch. the next version will also let you change tile providers at runtime

**Comment by spyhunter99** [comment]
fix is merged
