### ISSUE TITLE
Problem of getting my current location.

### ISSUE THREAD

**Issue by MohammadAvrahem** [osmdroid/osmdroid#783]
Hallo, i have tried to get my current location using osmdroid, then getting the location of the client address from database. 

First, i make it sure that i have the permissions inside manifestfile.xml:

`    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION"/>
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION"/>
    <uses-permission android:name="android.permission.INTERNET"/>
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
    <uses-permission android:name="android.permission.ACCESS_WIFI_STATE"/>`

I am implementing the map related code inside a Fragment. My problem is that i can not get my current location, i have tried the following:

`    private void trackingMyLocationTow() {
      locationProvider = new GpsMyLocationProvider(this);
        myLocationoverlay = new MyLocationNewOverlay(locationProvider, mapView);
        myLocationoverlay.enableMyLocation();
        myLocationoverlay.setDrawAccuracyEnabled(true);
        myLocationoverlay.runOnFirstFix(new Runnable() {
            public void run() {
               myLatitude =  myLocationoverlay.getMyLocation().getAltitude();
               myLongitude =  myLocationoverlay.getMyLocation().getLongitude();
            }
        });
        mapView.getOverlays().add(myLocationoverlay);
        mapView.invalidate();
    }`

**Then i got 0 for both   myLatitude and myLongitude.**

I have also tried to get my current location using another code:

`import android.app.Service;
import android.content.Context;
import android.content.Intent;
import android.location.Location;
import android.location.LocationListener;
import android.location.LocationManager;
import android.os.Bundle;
import android.os.IBinder;
import android.util.Log;
import android.widget.Toast;

public class LocationService extends Service
{
    public static final String BROADCAST_ACTION = "Hello World";
    private static final int TWO_MINUTES = 1000 * 60 * 2;
    public LocationManager locationManager;
    public MyLocationListener listener;
    public Location previousBestLocation = null;

    Intent intent;
    int counter = 0;

    @Override
    public void onCreate()
    {
        super.onCreate();
        intent = new Intent(BROADCAST_ACTION);
    }

    @Override
    public void onStart(Intent intent, int startId)
    {
        locationManager = (LocationManager) getSystemService(Context.LOCATION_SERVICE);
        listener = new MyLocationListener();
        locationManager.requestLocationUpdates(LocationManager.NETWORK_PROVIDER, 4000, 0, listener);
        locationManager.requestLocationUpdates(LocationManager.GPS_PROVIDER, 4000, 0, listener);
    }

    @Override
    public IBinder onBind(Intent intent)
    {
        return null;
    }

    protected boolean isBetterLocation(Location location, Location currentBestLocation) {
        if (currentBestLocation == null) {
            // A new location is always better than no location
            return true;
        }

        // Check whether the new location fix is newer or older
        long timeDelta = location.getTime() - currentBestLocation.getTime();
        boolean isSignificantlyNewer = timeDelta > TWO_MINUTES;
        boolean isSignificantlyOlder = timeDelta < -TWO_MINUTES;
        boolean isNewer = timeDelta > 0;

        // If it's been more than two minutes since the current location, use the new location
        // because the user has likely moved
        if (isSignificantlyNewer) {
            return true;
            // If the new location is more than two minutes older, it must be worse
        } else if (isSignificantlyOlder) {
            return false;
        }

        // Check whether the new location fix is more or less accurate
        int accuracyDelta = (int) (location.getAccuracy() - currentBestLocation.getAccuracy());
        boolean isLessAccurate = accuracyDelta > 0;
        boolean isMoreAccurate = accuracyDelta < 0;
        boolean isSignificantlyLessAccurate = accuracyDelta > 200;

        // Check if the old and new location are from the same provider
        boolean isFromSameProvider = isSameProvider(location.getProvider(),
                currentBestLocation.getProvider());

        // Determine location quality using a combination of timeliness and accuracy
        if (isMoreAccurate) {
            return true;
        } else if (isNewer && !isLessAccurate) {
            return true;
        } else if (isNewer && !isSignificantlyLessAccurate && isFromSameProvider) {
            return true;
        }
        return false;
    }

    /** Checks whether two providers are the same */
    private boolean isSameProvider(String provider1, String provider2) {
        if (provider1 == null) {
            return provider2 == null;
        }
        return provider1.equals(provider2);
    }

    @Override
    public void onDestroy() {
        // handler.removeCallbacks(sendUpdatesToUI);
        super.onDestroy();
        Log.v("STOP_SERVICE", "DONE");
        locationManager.removeUpdates(listener);
    }

    public static Thread performOnBackgroundThread(final Runnable runnable) {
        final Thread t = new Thread() {
            @Override
            public void run() {
                try {
                    runnable.run();
                } finally {

                }
            }
        };
        t.start();
        return t;
    }

    public class MyLocationListener implements LocationListener {

        public void onLocationChanged(final Location loc) {
            if(isBetterLocation(loc, previousBestLocation)) {
                Toast.makeText( getApplicationContext(), "Your Lat is:"+loc.getLatitude(), Toast.LENGTH_LONG).show();
                Toast.makeText( getApplicationContext(), "Your Lng is:"+loc.getLongitude(), Toast.LENGTH_LONG).show();
                loc.getLatitude();
                loc.getLongitude();
                intent.putExtra("Latitude", loc.getLatitude());
                intent.putExtra("Longitude", loc.getLongitude());
                intent.putExtra("Provider", loc.getProvider());
                sendBroadcast(intent);
            }
        }

        public void onProviderDisabled(String provider) {
            Toast.makeText( getApplicationContext(), "Gps Disabled", Toast.LENGTH_LONG).show();
        }

        public void onProviderEnabled(String provider) {
            Toast.makeText( getApplicationContext(), "Gps Enabled", Toast.LENGTH_LONG).show();
        }

        public void onStatusChanged(String provider, int status, Bundle extras) {

        }

    }
}
`
**And again i got 0 for both lat and lng.**

**Comment by spyhunter99** [comment]
Hmm, did you do the whole permissions thing?

**Comment by MohammadAvrahem** [comment]
Yeah sure!

**Comment by spyhunter99** [comment]
are you outside with gps service? does the device even have gps? is the gps turned on?

**Comment by MohammadAvrahem** [comment]
Yeah i am always asking for permissions before displaying anything on map:

` if(ActivityCompat.checkSelfPermission(this, Manifest.permission.ACCESS_FINE_LOCATION) != PackageManager.PERMISSION_GRANTED
                && ActivityCompat.checkSelfPermission(this, Manifest.permission.ACCESS_COARSE_LOCATION) != PackageManager.PERMISSION_GRANTED
                && ActivityCompat.checkSelfPermission(this, Manifest.permission.WRITE_EXTERNAL_STORAGE) != PackageManager.PERMISSION_GRANTED
                && ActivityCompat.checkSelfPermission(this, Manifest.permission.ACCESS_NETWORK_STATE) != PackageManager.PERMISSION_GRANTED
                && ActivityCompat.checkSelfPermission(this, Manifest.permission.ACCESS_WIFI_STATE) != PackageManager.PERMISSION_GRANTED
                && ActivityCompat.checkSelfPermission(this, Manifest.permission.INTERNET) != PackageManager.PERMISSION_GRANTED){
            //Requesting for permession from user if your don't have it
            requestRuntimePermession();`

**Comment by spyhunter99** [comment]
what api level is the device?

**Comment by MohammadAvrahem** [comment]
API 22, and the osmdroid: 'org.osmdroid:osmdroid-android:5.6.5'

**Comment by RagnarR** [comment]
Have the same thing with API 23 and Osmdroid version 5.6.5. I checking permission during runtime and in the manifest.

**Comment by spyhunter99** [comment]
both are very strange. Does it work on the demo app? https://play.google.com/store/apps/details?id=org.osmdroid

**Comment by MohammadAvrahem** [comment]
I will check and come back to you

**Comment by spyhunter99** [comment]
@MohammadAvrahem ping

**Comment by lumeshadow** [comment]
I have the same problem. Location fixes take very long, sometimes 20 minutes or never. I installed the demo app but none of the samples with location overlays could find my location. Please help, I upgraded to the latest osmdroid and now my app doesn't work right anymore. The client is unhappy.

**Comment by perezreina** [comment]
Try this, it worked for me:

mGpsMyLocationProvider = new GpsMyLocationProvider(this);        mGpsMyLocationProvider.addLocationSource(android.location.LocationManager.NETWORK_PROVIDER);

If it does not work for you either, make sure that the location mode is high accuracy.

**Comment by spyhunter99** [comment]
@lumeshadow what exactly did you revert?

**Comment by lumeshadow** [comment]
In GpsMyLocationProvider:

`public GpsMyLocationProvider(Context context) {
//		mLocationManager = (LocationManager) context.getSystemService(Context.LOCATION_SERVICE);
//		locationSources.add(LocationManager.GPS_PROVIDER);

		mLocationManager = (LocationManager) context.getSystemService(Context.LOCATION_SERVICE);
	}`

`/**
	 * Enable location updates and show your current location on the map. By default this will
	 * request location updates as frequently as possible, but you can change the frequency and/or
	 * distance by calling {@link #setLocationUpdateMinTime} and/or {@link
	 * #setLocationUpdateMinDistance} before calling this method.
	 */
	@Override
	public boolean startLocationProvider(IMyLocationConsumer myLocationConsumer) {
//		mMyLocationConsumer = myLocationConsumer;
//		boolean result = false;
//		for (final String provider : mLocationManager.getProviders(true)) {
//			if (locationSources.contains(provider)) {
//				result = true;
//				mLocationManager.requestLocationUpdates(provider, mLocationUpdateMinTime,
//						mLocationUpdateMinDistance, this);
//			}
//		}

		mMyLocationConsumer = myLocationConsumer;
		boolean result = false;
		for (final String provider : mLocationManager.getProviders(true)) {
			if (LocationManager.GPS_PROVIDER.equals(provider)
					|| LocationManager.NETWORK_PROVIDER.equals(provider)) {
				result = true;
				mLocationManager.requestLocationUpdates(provider, mLocationUpdateMinTime,
						mLocationUpdateMinDistance, this);
			}
		}
		return result;
	}`

`@Override
	public void stopLocationProvider() {
//		mMyLocationConsumer = null;
//		if(mLocationManager != null){
//			mLocationManager.removeUpdates(this);
//		}

		mMyLocationConsumer = null;
		mLocationManager.removeUpdates(this);
	}`

`@Override
	public void onLocationChanged(final Location location) {
//		if (mIgnorer==null) {
//			Log.w(IMapView.LOGTAG, "GpsMyLocation proivider, mIgnore is null, unexpected. Location update will be ignored");
//			return;
//		}
//		if (location==null || location.getProvider()==null)
//			return;
//		// ignore temporary non-gps fix
//		if (mIgnorer.shouldIgnore(location.getProvider(), System.currentTimeMillis()))
//			return;
//
//		mLocation = location;
//		if (mMyLocationConsumer != null && mLocation !=null)
//			mMyLocationConsumer.onLocationChanged(mLocation, this);

		// ignore temporary non-gps fix
		if (mIgnorer.shouldIgnore(location.getProvider(), System.currentTimeMillis()))
			return;

		mLocation = location;
		if (mMyLocationConsumer != null)
			mMyLocationConsumer.onLocationChanged(mLocation, this);
	}`

**Comment by spyhunter99** [comment]
looks like the only real difference is that you're adding the network provider. That should be doable without the code change.
````
GpsMyLocationProvider provider = new GpsMyLocationProvider(context);
provider.addLocationSource(LocationManager.NETWORK_PROVIDER);
MyLocationNewOverlay overlay = new MyLocationNewOverlay(provider, map);
map.getOverlayManager().add(overlay);
````

**Comment by spyhunter99** [comment]
thanks for the code. see also #917. I think i added all my comments for this ticket to that one. I added network provider to the overlay by default
