### ISSUE TITLE
Question:: Change OSM map background layer color

### ISSUE THREAD

**Issue by mf-mindcrewtech** [osmdroid/osmdroid#784]
Hi, is there any way to change the background layer color of OSM map.

I tried this, but no success.

country_all_mapview.setBackgroundColor(ContextCompat.getColor(getActivity(),R.color.colorAccent));

**Comment by spyhunter99** [comment]
mapView.getOverlayManager().getTilesLayer().setBackground....

**Comment by mf-mindcrewtech** [comment]
Hi @spyhunter99 , Thanks but the code you shared is not working with ver 5.6.5

I tried this, 

country_all_mapview.getOverlayManager().getTilesOverlay().setLoadingBackgroundColor(ContextCompat.getColor(this, R.color.black));

But still not able to change the color. Any help?

**Comment by spyhunter99** [comment]
that will set the color of the gray grid. If that isn't what you mean, trying setting the color of the mapview defined in your layout file or it's parent

**Comment by mf-mindcrewtech** [comment]
Okay but this was still not changing the gray color to any other color. What's the issue?

**Comment by spyhunter99** [comment]
No idea. That's always for me. Perhaps there is something else in the android view hierarchy that is causing it? Perhaps a clean? gradlew has strange caching issues from time to time

**Comment by spyhunter99** [comment]
closing due to no feedback or reply. reopen if this is still an issue for you
