### ISSUE TITLE
Get rid of `MapView` scale by using the floating point zoom

### ISSUE THREAD

**Issue by monsieurtanuki** [osmdroid/osmdroid#790]
## Issue Type
[v] Improvement

## Description and/or steps/code to reproduce the problem
Now that we have floating point zooms (instead of integer zooms), we could get rid of the notion of `MapView` _scale_.
For the moment, the scale always equals 1.0f, except during pinch gesture where it reflects the delta zoom in/out. The idea would be to compute directly the next zoom and forget the notion of scale:
* The code would be simpler and easier to maintain.
* The behavior (especially the tiles display) would be the same during pinch gesture and when the gesture stops
* The best possible tiles would always be displayed, instead of a scaled version of the tiles that where on screen at pinch gesture start.

Please feel free to comment!

### Version of osmdroid the issue relates to:
6.0.0

**Comment by monsieurtanuki** [comment]
Additional thoughts if we get rid of the notion of scale:
* we won't use it on Canvas and as a result we may avoid related problems about hardware acceleration
* I think there's a pending issue about "some layers being scaled when some others are not", which displays smaller/bigger marker pop-ups. We would solve that too

**Comment by monsieurtanuki** [comment]
Could solve #595 too.

**Comment by secaw** [comment]
Sounds great! Would probably reduce some CPU overhead too, right?

**Comment by monsieurtanuki** [comment]
I guess so. And in the supposedly common case of a 0 degree map orientation, we could get rid of the whole canvas manipulation (save / rotate / scale / restore).

**Comment by monsieurtanuki** [comment]
I can tell you, so far it looks great! Still working on it.

**Comment by secaw** [comment]
Sounds promising - really looking forward to this!

**Comment by spyhunter99** [comment]
merged

**Comment by MKergall** [comment]
After all these changes related to "floating point map scale", the overall result is wonderful. 
Seeing for instance the marker clustering operating during the pinch zoom gesture (without any code change needed on my side), that's really great. 

@spyhunter99 & @monsieurtanuki Do you see something else absolutely required before releasing a new version? (could V6.0 land under the christmas tree?)

**Comment by spyhunter99** [comment]
@MKergall that can be arranged! depends on what you want to do for the zoon button overlay

**Comment by monsieurtanuki** [comment]
@MKergall I'm glad you enjoyed the new pinch gesture!
Regarding pending issues I have an interest in:
* #817 is minor but could be quickly fixed.
* I'm currently working on #809, which is very interesting but not altogether a core feature, and which is already working - I'm just expanding the feature
I don't see anything absolutely required before the new release.
