### ISSUE TITLE
Add directional arrows to polylines

### ISSUE THREAD

**Issue by jmarks213** [osmdroid/osmdroid#791]
## Issue Type
[x] Improvement

I needed to add directional arrows to the polylines for indicating direction between points and wanted to share the end result.  Maybe someone else will find it useful.

For example,
![screenshot_20171128-155839](https://user-images.githubusercontent.com/15203304/33344851-51cdc122-d458-11e7-8aa4-1abaccca855d.jpg)

**Comment by spyhunter99** [comment]
#611 related issue

This is pretty cool! Testing now, i can see lots of use cases for aviation maps, vectors and waypoints, etc

**Comment by pasniak** [comment]
Is it doable to have labels aligned to polylines? Something like:
![screenshot from 2017-12-21 20-44-18](https://user-images.githubusercontent.com/19778666/34281899-c64affee-e68f-11e7-9e78-24576939669e.png)

**Comment by monsieurtanuki** [comment]
@pasniak I think this goes far beyond the "arrow" feature for many reasons, among them: what parametrized text should we display and how should we split the text if the segment zigzags? In comparison, for arrows we just always display the same small `Path` (or bitmap in  #809).
That being said, the implementation of the angled text would be something like
````java
canvas.save();
canvas.rotate(orientation, centerX, centerY);
// here it's a bitmap, but you can put a text instead
canvas.drawBitmap(bitmap, centerX - bitmap.getWidth() / 2, centerY - bitmap.getHeight() / 2, null);
canvas.restore();
````

**Comment by spyhunter99** [comment]
@pasniak one approach you could take is to look at the milstd2525 renderer. There's a standardized graphic for this. It looks a lot like an air space corridor or something like that. Your (developer) workflow would be:

- add the renderer to your project
- add osmbonusback
- figure out what the symbol code is
- figure out your control points (basically the start/end points and a width)
- have the renderer make you a kml doc
- use osmbonus pack to convert the kml to a folder overlay
- add the folder overlay to the map

the following is what it looks like in the spec (milstd2525c), which is in the ball park of what you're looking for. http://www.dtic.mil/doctrine/doctrine/other/ms_2525c.pdf for the full spec

![image](https://user-images.githubusercontent.com/1975321/34316530-ccee8b78-e765-11e7-92e9-09d9c19805fd.png)

of course, you could just build the polygons yourself. The text labels can be created on the fly too with the marker class
