### ISSUE TITLE
getMercatorXFromLongitude signature mismatch

### ISSUE THREAD

**Issue by pasniak** [osmdroid/osmdroid#794]
After code refresh to 0bad623dfd9bafb1632d8f87f2734ffc218128d7 the build fails with 

```
            final long left = TileSystem.getMercatorXFromLongitude(west, mapSize);
            final long top = TileSystem.getMercatorYFromLatitude(north, mapSize);
            final long right = TileSystem.getMercatorXFromLongitude(east, mapSize);
            final long bottom = TileSystem.getMercatorYFromLatitude(south, mapSize);
```

because of

`	public static long getMercatorXFromLongitude(final double pLongitude, final double pMapSize, boolean wrapEnabled) `

[x] Build system related

### Version of osmdroid the issue relates to:

6.0.0-SNAPSHOT

**Comment by pasniak** [comment]
This test compilation error is due to commit c38260cd99c260ffae74b286ac05f892872e85bf by @Maradox

**Comment by spyhunter99** [comment]
Hmm travis has been building just fine. If you're building from source, you probably need to run `gradle clean`

**Comment by spyhunter99** [comment]
hmm this is rather sad, looks like `gradlew connectedCheck` only builds and runs android instrumentation tests and skips all junit tests, which means that our travis config is broken. This same signature mismatch causes the junit tests to fail to compile. ugh
