### ISSUE TITLE
3d visualization on low level zoom

### ISSUE THREAD

**Issue by turrigni** [osmdroid/osmdroid#795]
## Issue Type

[ ] Question
[ ] Bug
[X ] Improvement
[ ] Build system related
[ ] Performance
[ ] Documentation

## Description 
Add new visualization 3d on low level zoom.
When you have low zoom values, rather than seeing a flat representation with polar deformations, show a sphere (orthografic projection).
In orthographic projection, geodesic line is  straight line, and other lines are arcs

rectangular projection
![04_medium](https://user-images.githubusercontent.com/16482229/33426034-cbb693ce-d5c0-11e7-9e0b-190dda924bf7.jpg)

orthografic projection
![03_medium](https://user-images.githubusercontent.com/16482229/33426049-d9cc4f26-d5c0-11e7-933e-2c3e3adea810.jpg)

**Comment by spyhunter99** [comment]
great idea, but it's not trivial. I'd suggest you look into NASA's world wind for android

**Comment by monsieurtanuki** [comment]
It's even beyond "not trivial", it's unfeasible if we stick to our slippy map tiles.
Of course we could warp tiles, but anyway we wouldn't be able to display the poles as we don't have tiles beyond N85 and S85.

**Comment by turrigni** [comment]
you could have a background color (white, or other color that can be set), so that at the poles over 85 ° you can see the background, or you could create tiles with uniform color over 85°.
I think that the complication is warping tiles.

**Comment by spyhunter99** [comment]
yeah. if you want this, try out nasa worldwind for android.
