### ISSUE TITLE
TileSystem question

### ISSUE THREAD

**Issue by ruizhang81** [osmdroid/osmdroid#798]
hi

can i change TileSystem.java or other file to adapt this Tile System

![2011070216561045](https://user-images.githubusercontent.com/3723124/33541957-0c8309fc-d90c-11e7-86f8-402931a8628a.jpg)

![2011070217022613](https://user-images.githubusercontent.com/3723124/33541953-0a8af7c2-d90c-11e7-9813-c043ad75bbf8.png)

thanks

**Comment by monsieurtanuki** [comment]
If I were you I wouldn't change `TileSystem`, even only locally.

Here's how I can help you figure out what to do:
* In osmdroid we use slippy map tiles
* The world has no restriction in longitude, but is restricted to latitudes between N85 and S85 => is that OK with your tile system?
* The input tiles are typically 256x256 bitmap files, but the input size can be changed => here you can fine tune to your input tile size
* For zoom level 0, the world has one tile
* For zoom level 1, the world has 2x2 tiles, top left (north-west) is "0,0", top right (north-east) is "1,0", 
bottom left (south-west) is "0,1", bottom right (south-east) is "1,1"
* I assume your second screenshot is for zoom level 3 (8x8 tiles). It looks like your tiles coordinates are just a simple operation compared to osmdroid's tiles: "your x = osmdroid's - 4" and "your y = 4 - osmdroid's". For instance, your top left seems to be "-4,4" as we expect "0,0"

The solution to "how can I download tiles whose coordinates need a simple operation as described -- x-4 and 4-y -- and whose size is different" is
* to extend `OnlineTileSourceBase`
* to override `getTileURLString`.
* to specify the adequate tile size

Doing so, you would use the same coordinates as everyone using osmdroid, but you would download the tiles that comply with your different tile coordinate system.

Does that answer your question?

**Comment by ruizhang81** [comment]
thanks

but override getTileURLString like this:

    public String getTileURLString(MapTile aTile) {
        int x = aTile.getX();
        int y = aTile.getY();
        int z = aTile.getZoomLevel();

        int offset = (int) Math.pow(2, z - 1);
        x = x - offset;
        y = offset - y - 1;

        return getBaseUrl() + "&x=" + x + "&y=" + y + "&z=" + z;
    }

set center in here (mapController.setCenter(point);)
Actually it should be center

![057e8a85e52f33adcda6bc07576f1218](https://user-images.githubusercontent.com/3723124/33588970-a8d902c6-d9b0-11e7-8f4c-820d389b2d65.jpg)

but display center in here

![2b3653679579657c0ae3ec71db3f6e7d](https://user-images.githubusercontent.com/3723124/33588981-bc492c1e-d9b0-11e7-9e30-23bcb9cda04c.jpg)

in Projection.java
i print center,neGeoPoint and swGeoPoint
is  40.046054 116.35001, 68.3775992080266 147.890625 and -7.071819582723464 84.609375
seem correct

it look like coordinate has be moved @@

**Comment by ruizhang81** [comment]
The error is very close
lat:14.8990753736,lon:46.8618771272

**Comment by monsieurtanuki** [comment]
My comments:
* is it possible for you to share your `getBaseUrl()`?
* I just tried with a recent version of osmdroid (6.0.0), by adding `mMapView.setCenter(new GeoPoint(40.06686199, 116.32324218));` in `StarterMapFragment.onActivityCreated`, and this is the corresponding screenshot, which seems to meet your expectations. I guess there's something to fix in your way of getting the tiles.
![device-2017-12-05-102119](https://user-images.githubusercontent.com/11576431/33599447-7d8600ba-d9a6-11e7-8b3e-40285ee2aa0e.png)

**Comment by ruizhang81** [comment]
getBaseUrl() is  a Internal network , i try resolve it. thank you very much

**Comment by ruizhang81** [comment]
getBaseUrl() is http://online3.map.bdimg.com/onlinelabel/?qt=tile&styles=pl&udt=20170712&scaler=1&p=1

i feel it 's projection problem

**Comment by monsieurtanuki** [comment]
I'm very surprised by the (-2,0) / (1,0) tiles!
What I recommend is a tile converter - from Baidu to osmdroid. Something like "give me the (1,2) osmdroid tile on zoom 4 computed from Baidu". Then everything is solved!
In first approach I would say this should be done on a server side: much easier.
But I don't speak Chinese, therefore I won't be able to understand the Baidu docs.
Can you work on the Baidu-to-osmdroid tile converter algorithm?

**Comment by ruizhang81** [comment]
baidu tile can't convert osmdroid or other system tile，because the tile count is deferent in any zoom level. baidu map projection is deferent from other.

my friend implements baidu map by Leaflet
it look like easy to change

the core code is here:

    export const BaiduMercator = {
    project: function (latLng) {
        var a = projection.baiduMercator.forward([latLng.lng, latLng.lat]);
        var leafletPoint = new L.Point(a[0], a[1]);
        return leafletPoint;
    }

    , unproject: function (bpoint) {
        var a = projection.baiduMercator.inverse([bpoint.x, bpoint.y]);
        var latLng = new L.LatLng(a[1], a[0]);
        return latLng;
    }

    , bounds: (function () {
        var MAX = 33554432;
        var bounds = new L.Bounds(
            [-MAX, -MAX],
            [MAX, MAX]
        );
        return bounds;
    })()};

    export default L.extend({}, L.CRS.Earth, {
       code: 'baidu'
       , projection: BaiduMercator
       , transformation: (function () {
           var z = -18 - 8;
           var scale = Math.pow(2, z);
           return new L.Transformation(scale, 0.5, -scale, 0.5);
    }())});

but i cant to change it in osmdroid.
i find TileSystem.java and Projection.java need to change a lots.
the IProjection look like not very good   :-P

**Comment by spyhunter99** [comment]
yes it looks like the projection is different, that makes things much more complex. I agree that we should have a more flexible way to support different projections, however this makes osmdroid much more complex. It's really the pairing of the map project, map tile coordinate system, and all associated storage mechanisms, pixel to lat,lon and lat,lon to pixel

**Comment by xfeng-github** [comment]
Has the author problem been solved? I have the same problem now
作者问题解决了吗, 我现在也遇到了这个问题

**Comment by monsieurtanuki** [comment]
@xfeng-github Now you have a possibility to extend [`TileSystem`](https://github.com/osmdroid/osmdroid/blob/master/osmdroid-android/src/main/java/org/osmdroid/util/TileSystem.java), like in [`TileSystemWebMercator`](https://github.com/osmdroid/osmdroid/blob/master/osmdroid-android/src/main/java/org/osmdroid/util/TileSystemWebMercator.java).
Is that enough to implement Baidu? I don't know. But if it works, please share your code ;)

**Comment by xfeng-github** [comment]
> @xfeng-github Now you have a possibility to extend [`TileSystem`](https://github.com/osmdroid/osmdroid/blob/master/osmdroid-android/src/main/java/org/osmdroid/util/TileSystem.java), like in [`TileSystemWebMercator`](https://github.com/osmdroid/osmdroid/blob/master/osmdroid-android/src/main/java/org/osmdroid/util/TileSystemWebMercator.java).
> Is that enough to implement Baidu? I don't know. But if it works, please share your code ;)

抱歉，我不知道如何实现百度系统
Sorry，I don't know how to implement Baidu TileSystem.

我认为百度瓦片和谷歌瓦片不仅仅实在编号上的区别， 还有是在瓦片包含信息大小分隔上有区别， 现在不知道该怎么去解决。
In my opinion, baidu tile and Google tile are not only different in number, but also different in size separation of tile containing information. Now I don't know how to solve this problem.
