### ISSUE TITLE
Performance problem with Markers

### ISSUE THREAD

**Issue by mlendl** [osmdroid/osmdroid#799]
## Issue Type

[x] Question

## Description and/or steps/code to reproduce the problem
In case of certain big number of Markers I hit a perfromance problem. I know about SimpleFastPointOverlay, but I need draggable markers (to implement GPX editor). Is there a way to solve this?

### Version of osmdroid the issue relates to:

5.6.5

**Comment by spyhunter99** [comment]
any idea how many? several thousand should be fine

**Comment by mlendl** [comment]
I think at several hundreds of Markers the reactions of MapView are visibly slower. But it's not critical, only question, if I can do seomething with it?

**Comment by MKergall** [comment]
Marker Clustering may help.

**Comment by mlendl** [comment]
It really helps, but the clustering feature is unwished for my usage and if I switch it off, the performance is the same as without the clustering. As I said, it is not critical, so I give up of further attempts.

**Comment by monsieurtanuki** [comment]
@mlendl I wrote a possible performance enhancement in `ItemizedOverlay.onDrawItem` in 6.0.0.
Before, it was something like:
````java
marker.draw(canvas);
````
And now it is:
````java
final boolean displayed = Rect.intersects(marker.getBounds(), canvas.getClipBounds());
if (displayed) {
	marker.draw(canvas);
}
````
The difference being that I don't try to draw on the canvas if I'm certain the marker doesn't intersect. It might be faster, especially if you have many markers outside of the canvas.

I'm also currently working on #790, which will reduce the number of operations on the canvas in general.

**Comment by mlendl** [comment]
Sounds goood!

**Comment by spyhunter99** [comment]
adding to the conversation on optimizing markers. It may be possible to have an in memory geospatial index. The current setup calls draw for all overlays. If we track the bounds of each overlay, can may be able to remove the  `for each overlay` loop with something a bit more sophisticated, which may solve problems when there's a large number of overlays. It would most likely be only useful if the number of markers/overlays is above some threshold, maybe 100k. The index in this case would be something similar to a z,x,y tree structure which would allow for a selection of icons within the current screen bounds, thus skipping the loop.

#770 is related. Maybe i'll work on 770 this weekend as it would be a prerequisite for this

**Comment by monsieurtanuki** [comment]
@mlendl Canvas performances should be better thanks to #800, especially if you don't use map orientation. Could you give it a try?

**Comment by mlendl** [comment]
Not clear, what shall I do, I'd wait for new release

**Comment by spyhunter99** [comment]
I can publish a snapshot release if it will help, then you can experiment with the newer version

**Comment by spyhunter99** [comment]
version 6.0.0-SNAPSHOT has been published
https://oss.sonatype.org/service/local/repositories/snapshots/content/org/osmdroid/osmdroid-android/6.0.0-SNAPSHOT/osmdroid-android-6.0.0-SNAPSHOT.aar

**Comment by spyhunter99** [comment]
linking related tickets #890 #182 #906 . On one of the branches, I added code to check if the view's bounding box includes/overlaps with the overlay's bounds. This greatly improves performance if the overlays are out of bounds of the current view.

**Comment by spyhunter99** [comment]
i'll also add that it causes some issues with the infowindow setup that still needs to be resolved

**Comment by mlendl** [comment]
good news! thanks a lot
when we can expect new version?

**Comment by mlendl** [comment]
it seems, that this issue is absolutly resolved in the v. 6.0, even if all markers are visible on the screen, thank you guys
