### ISSUE TITLE
mousewheel is not zooming?

### ISSUE THREAD

**Issue by pasniak** [osmdroid/osmdroid#805]
[ ] Question
[x] Bug
[ ] Improvement

I run the sample pack in Android emulator.  I tried mouse wheel but it is not zooming. The emulator responds to the wheel: the map image shifts up and down.

## Environment
Emulator of Nexus 7 API 26

6.0.0

**Comment by spyhunter99** [comment]
It's probably an emulator thing try https://www.genymotion.com/ there is a free setup for personal use,  works ok there,  or a physsdical device with a real mouse, or x86

**Comment by pasniak** [comment]
I tried on my tablet/physical mouse : "Lat/Lon Gridlines" demo does indeed zoom in out with mouse wheel; "StarterMapFragment" also zooms in/out with keyboard PgUp/PdDn (but not mouse wheel).  None of those work on AS's Emulator.
