### ISSUE TITLE
Polygon with holes are invisible

### ISSUE THREAD

**Issue by monsieurtanuki** [osmdroid/osmdroid#808]
## Issue Type
[v] Bug

## Description and/or steps/code to reproduce the problem

* In the demo app, go to "More Samples / Drawing / Draw a polygon with holes on screen"
* select the paint brush and draw a polygon: at the end a polygon without hole appears
* select the butcher knife and draw a second polygon inside the first polygon: at the end the first polygon disappears and the second polygon doesn't appear either

### Version of osmdroid the issue relates to:

6.0.0

**Comment by spyhunter99** [comment]
well that's a fun one

**Comment by spyhunter99** [comment]
@monsieurtanuki when did this break? it might have been one of the recent PRs

**Comment by monsieurtanuki** [comment]
@spyhunter99 I imagine it is due to the devs on the horizontal/vertical on/off world map replication.
I remember that when I changed the code in order to display `Polygon`s with hardware acceleration on, I had to fine tune my devs in order to display the hole in a relevant place compared to the master polygon.
And now that there's this additional world map replication management, I guess it's a bit more complex.
But I haven't had a look at the code, maybe it's something else.
Btw we should think once more about testing the polygon and its hole, using the expected pixel color.

**Comment by monsieurtanuki** [comment]
If I go to "More Samples / Drawing / Draw a polygon with holes on screen":
* I can draw n polygons
* but when I draw a hole, the nth polygon disappears. And all the next polygons: from now on I'll see first n-1 polygons

It could be rather a problem on the Fragment UI than on the Polygon/ LinearRing code.

I'll have a look at it this week.

**Comment by monsieurtanuki** [comment]
Just found out why we don't see anything: there's a NPE when dealing with the hole. The polygon and its hole share the same `Path`: when the hole step crashes, the path isn't displayed at all.
It looks like the NPE is due to the latest changes around "arrow" polygons. I'm about to PR.

**Comment by monsieurtanuki** [comment]
Fixed
