### ISSUE TITLE
Displaying refined milestones on Polyline/Polygon

### ISSUE THREAD

**Issue by monsieurtanuki** [osmdroid/osmdroid#809]
## Issue Type

[v] Improvement

## Description

@jmarks213 added arrows to `Polyline` and `Polygon` in #791 and #792.
As discussed already, there are several ways to still improve that new feature.

For the moment we display arrow as `Path`. We should be able to display bitmaps too.
For instance, we should create `interface Milestone`, with method `void draw(Canvas c, int x, int y, float orientation)`. New classes `PathMilestone`, `ArrowPathMilestone` and `BitmapMilestone` would implement `Milestone`.

For the moment one arrow is displayed between two consecutive polyline vertices only if there are enough pixels between them. Which means for instance that a 2-vertice polyline between Paris and Sydney will display only one arrow. And a 10K-vertice polyline will display no arrow at all.
This is how @jmarks213 wanted things to be for his own project, but we should be able to propose also alternate arrow recurrence, computed in distance from the first vertex, like every 100 pixels.

**Comment by jmarks213** [comment]
@monsieurtanuki Great verbiage, "Milestones" sounds appropriate!  Have you started to implement arrows over the pixel distance of the line?  I should have some time to work on it over the next week or two if you have not started.

**Comment by monsieurtanuki** [comment]
@jmarks213 Oh, I just started working on the subject.

**Comment by monsieurtanuki** [comment]
Displaying bitmaps: done.
Next step: implementing the distance feature.

![device-2017-12-21-120357](https://user-images.githubusercontent.com/11576431/34253276-311f4e90-e647-11e7-98cd-25d543f278b0.png)

**Comment by monsieurtanuki** [comment]
Using distance: done.
Now I need to clean the code.
![device-2017-12-21-124132](https://user-images.githubusercontent.com/11576431/34254435-673c13c8-e64c-11e7-83ec-847e4707879e.png)

**Comment by monsieurtanuki** [comment]
There are funny side effects with the "pixel distance" feature:
1. When you zoom in or out, the distance in pixels change, and therefore the arrows move on the polyline. And I don't know what would make sense functionally n that case.
1. When you pan the map, the arrows move on the polyline too, because the pixel distances are computed after the clipping. I can fix that and compute the distances before the clipping.

Any user experience view on both points is welcomed!

**Comment by spyhunter99** [comment]
pretty cool, i'd have to see it in action. Another thing to keep in mind is that ground resolution changes with latitude so the distance on the ground can greatly differ from relative distance in pixels on screen

**Comment by monsieurtanuki** [comment]
@spyhunter99 My goal so far was to display a milestone every x pixels, in order to display a regularly pixel spaced set of bitmaps. Of course if we implement "milestones every x meters", we will have the "meter distance against varying latitude" side effect. But we could live with it on high zoom (where latitude is not supposed to vary that much), and in low zoom it will be obviously as preposterous as the scale we display on the world map on zoom 0 in the "start here" demo.

**Comment by monsieurtanuki** [comment]
Developed and merged in #826
