### ISSUE TITLE
NOT showing current location by using GPS PROVIDER

### ISSUE THREAD

**Issue by jesuvijay** [osmdroid/osmdroid#810]
Please note: issues related to or caused by osmbonuspack will be closed with a
suggestion to open an issue at https://github.com/MKergall/osmbonuspack

(feel free to delete whatever doesn't apply)

## RED icon not shown on higher API level

##When i checked in android 5.0 it shows location with green marker with arrow
but on 6.0 like  Asus zenfone series and above not showing  icon(green marker icon with arrow).  check it

### If it's a bug, version(s) of android this affects:

All

### Version of osmdroid the issue relates to:

5.6.5

**Comment by spyhunter99** [comment]
Can you reproduce with the play store app? I'm using android 6 with no issues

**Comment by jesuvijay** [comment]
no hunter..

   gpsMyLocationProvider = new GpsMyLocationProvider(mContext);
            gpsMyLocationProvider.addLocationSource(LocationManager.GPS_PROVIDER);
            // 0 metres
            gpsMyLocationProvider.setLocationUpdateMinDistance(0);
            //3 seconds once location updates
            gpsMyLocationProvider.setLocationUpdateMinTime(3 * 1000);
//                        add location overlay
            myLocationNewOverlay = new MyLocationNewOverlay(gpsMyLocationProvider, mMapView);

**Comment by jesuvijay** [comment]
can u give example of gps provider

**Comment by jesuvijay** [comment]
I missed add to overlay sry

**Comment by jesuvijay** [comment]
gpsMyLocationProvider.startLocationProvider() Imapconsumer

**Comment by jesuvijay** [comment]
how to change green dot with direction to blue dot 

   myLocationNewOverlay.setPersonIcon(BitmapFactory.decodeResource(mContext.getResources(), R.drawable.ic_mylocation));
I used but not getting location
