### ISSUE TITLE
Animate To vs Map Repeating

### ISSUE THREAD

**Issue by spyhunter99** [osmdroid/osmdroid#816]
## Issue Type

[x ] Bug

## Description and/or steps/code to reproduce the problem

Minor issue, when at zoom 0, with GPS service and you enable follow me, the map will center on your location, however on the next gps update, your location can be displayed on the top most map. This causes a never ending loop of map animation

### Version of osmdroid the issue relates to:

6.0.0-SNAPSHOT

video coming soon

**Comment by spyhunter99** [comment]
repeated using the sample introduced with #815
more samples > location > custom my location

**Comment by spyhunter99** [comment]
https://www.youtube.com/watch?v=XIc-UODJDZU

**Comment by monsieurtanuki** [comment]
@spyhunter99 I cannot reproduce this issue, but:
* I recently changed the `animateTo` process
* your screen height is bigger than mine

Could you please check again if this issue is still there, and tell me which demo you used to reproduce it?

**Comment by monsieurtanuki** [comment]
@spyhunter99 ping

**Comment by spyhunter99** [comment]
looks like it's fixed
