### ISSUE TITLE
CopyrightOverlay doesn't draw when zooming

### ISSUE THREAD

**Issue by spyhunter99** [osmdroid/osmdroid#817]
## Issue Type

[ ] Bug

## Description and/or steps/code to reproduce the problem

minor issue but the copyright overlay disappears while zooming, perhaps @monsieurtanuki can apply the same fix from the minimap to this overlay.

### Version of osmdroid the issue relates to:

6.0.0

**Comment by monsieurtanuki** [comment]
Correction: it becomes invisible during the _zoom animation_ (double click or zoom button), but it's visible during the _pinch gesture_.
Btw the same thing happens with the scale bar.

To fix that, just remove the following test from `CopyrightOverlay.draw`:
````java
if (map.isAnimating()) {
	return;
}
````
Same thing with `ScaleBarOverlay.draw`.

If I had the slightest idea on how to safely handle 2 branches on my PC I would have already PR'ed that fix. Anyone please PR that fix, I won't complain.

**Comment by spyhunter99** [comment]
k on it
