### ISSUE TITLE
Ruler tool or how to draw line on mapView canvas while touching multiple points and disable zoom?

### ISSUE THREAD

**Issue by pasniak** [osmdroid/osmdroid#818]
[x] Question
6.0.0

I have a TapLayer inhering from Overlay which detects mulitouch events, and I would like user to be able to draw (A) a line between touched points and (B) text with its real life distance. 

A and B "work" but multitouch triggers zoom, which is kind of ok from UX pov but then on 2-finger-touch-slide the zoom changes the scale which:
 a) makes distance calculated off as zoom happens...
 b) makes the line drawn on the map's canvas, shorter or longer than 2 finger span...

I tried to disable zoom using subclassing MapView and overriding canZoomIn/Out but they only control the zoom buttons...

a) and b) seem complicated so how do I obtain c)? ie how to disable zoom (temporarily...)

Michael

**Comment by spyhunter99** [comment]
Have you thought about making on custom transparent view on top of the map? We do similar stuff to toggle between a drawing mode and panning mode.

**Comment by pasniak** [comment]
let me try that.. the transparent view would have its own canvas which would be unaffected by scaling? is that the trick?

**Comment by pasniak** [comment]
ok, drawing line on a separate custom View works nicely.

But the distance calculated between 2 GeoPoints (obtained in the overlay in onTouchEvent as below) still varies with the zoom! Increases as I zoom-in (pinch-out), decreases as I zoom-out (pinch-in).  The touchpoints on the map are the same as I maintain the touch.

```
class TapOverlay () : Overlay() {

    override fun onTouchEvent(event: MotionEvent?, mapView: MapView?):Boolean {
     ....
       mapView.projection.fromPixels(touchPoint.x.toInt(), touchPoint.y.toInt())
```

**Comment by spyhunter99** [comment]
i'm not sure i'm following you exactly. distance between two geo poins (lat,lon) should be same at any zoom, however you're converting from screen pixels to lat,lon, which will change with zoom levels

zoom =2, pixel coordinates 0,0 to pixel coordinate 150,150, let's just say the distance is 200 meters
zoom=3,, pixel coordinates 0,0 to pixel coordinate 150,150, let's just say the distance is 150 meters

this is expected since the ground resolution (distance per screen pixel) changes with zoom

**Comment by spyhunter99** [comment]
https://github.com/osmdroid/osmdroid/tree/master/OpenStreetMapViewer/src/main/java/org/osmdroid/samplefragments/drawing

for reference

**Comment by pasniak** [comment]
FYI I just add a polyline with 2 points in MotionEvent.ACTION_MOVE event (and then remove it). Looks smooth.
