### ISSUE TITLE
Here is a working sonatype URL

### ISSUE THREAD

**Issue by InI4** [osmdroid/osmdroid#824]
## Issue Type

[ X] Question
[ ] Bug
[ X] Improvement
[ X] Build system related
[ ] Performance
[ ] Documentation

## Description and/or steps/code to reproduce the problem
I wanted to try 6.0.0-SNAPSHOT without using the aar. As it turned out, the sonatype URL you give, requires a login. However I found one, that is working for me:

`https://oss.sonatype.org/content/repositories/snapshots/`

or in full`, the following repository works for me:

`repositories {`
`    maven{
`        url 'https://oss.sonatype.org/content/repositories/snapshots/'`
`        name 'OSS-Sonatype'`
`    }`
`}`

You might want to change your page correspondingly?!

As  I have plenty of situtations where I have double/int issues now, I must decide next, if I really do the jump ...

### If it's a bug, version(s) of android this affects:

All

### Version of osmdroid the issue relates to:

6.0.0-SNAPSHOT

**Comment by spyhunter99** [comment]
Thanks il get it updated shortly

**Comment by spyhunter99** [comment]
did you run into any issues other than deprecated method calls? FYI, I just pushed another snapshot

**Comment by InI4** [comment]
Looked good overall. Elsewhere I posted that zoom button stuff and mentioned the missing close() statements. I have a branch for 6.0.0-SNAPSHOT now and plan to revisit occasional.
