### ISSUE TITLE
java.lang.NoSuchFieldError: No field DEBUG_TILE_PROVIDERS of type Z in class Lorg/osmdroid/tileprovider/constants/OpenStreetMapTileProviderConstants

### ISSUE THREAD

**Issue by johan974** [osmdroid/osmdroid#828]
Please note: issues related to or caused by osmbonuspack will be closed with a
suggestion to open an issue at https://github.com/MKergall/osmbonuspack

(feel free to delete whatever doesn't apply)

## Issue Type

[X] Bug

## Description and/or steps/code to reproduce the problem
A DEBUG field seems to be missing in the code. 
When using Osmdrdoid to load a Mapsforge maps file, then the following message is shown: 

I/OsmDroid: Error downloading tile: /13/4247/2696
            java.lang.NoSuchFieldError: No field DEBUG_TILE_PROVIDERS of type Z in class Lorg/osmdroid/tileprovider/constants/OpenStreetMapTileProviderConstants; or its superclasses (declaration of 'org.osmdroid.tileprovider.constants.OpenStreetMapTileProviderConstants' appears in /data/app/nl.deholtmans.osmdroidmapsforgedemo-2/split_lib_dependencies_apk.apk)
                at org.osmdroid.mapsforge.MapsForgeTileModuleProvider$TileLoader.loadTile(MapsForgeTileModuleProvider.java:92)
                at org.osmdroid.tileprovider.modules.MapTileModuleProviderBase$TileLoader.run(MapTileModuleProviderBase.java:297)
                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                at java.lang.Thread.run(Thread.java:761)

## Environment
You can find the program in this Github project; https://github.com/johan974/osmdroid-mapsforge-demo. 
After giving the permissions, selecting a mapsforge file, the error always occurs. Re-producable. 

### If it's a bug, version(s) of android this affects:
See the project info. 

### Version of osmdroid the issue relates to:
5.6.5

Hope you can solve this. 
Enjoy this holiday season and have a good 2018!
Kind regards, Johan

**Comment by spyhunter99** [comment]
Is it possible that you have mismatched versions of osmdroid-android and osmdroid-mapsforge? The maps forge demo was actually removed and merged into the main demo app on master (and will be fore v6)

**Comment by spyhunter99** [comment]
can you post the dependencies section of the apk?

**Comment by spyhunter99** [comment]
version mismatch in your build file. 

https://github.com/johan974/osmdroid-mapsforge-demo/blob/master/app/build.gradle#L34

**Comment by spyhunter99** [comment]
@johan974 i got it working
![image](https://user-images.githubusercontent.com/1975321/34412479-7604cc10-ebab-11e7-98be-096209a4b5b2.png)
