### ISSUE TITLE
SqlTileWriter clears most recent tiles

### ISSUE THREAD

**Issue by shiroyagi** [osmdroid/osmdroid#829]
## Issue Type

[ ] Question
[ *] Bug
[ ] Improvement
[ ] Build system related
[ ] Performance
[ ] Documentation

## Description and/or steps/code to reproduce the problem

The most recently used rather than least recently used are deleted in runCleanupOperation().
Since expiry is ms from the epoch the order should be ascending for oldest first:
`db.execSQL("DELETE FROM " + TABLE + " WHERE " + COLUMN_KEY + " in (SELECT " + COLUMN_KEY + " FROM " + TABLE + " ORDER BY " + COLUMN_EXPIRES + " ASC LIMIT " + tilesToKill + ")");`
I have verified this now works with getFirstExpiry().

### Version of osmdroid the issue relates to:

6.0, 5.6.5

**Comment by spyhunter99** [comment]
@shiroyagi good catch. thanks!
