### ISSUE TITLE
is therepossible to place circle around marker in osm like google map Circle class and how to place number counter inside marker dynamically example needed

### ISSUE THREAD

**Issue by jesuvijay** [osmdroid/osmdroid#831]
Please note: issues related to or caused by osmbonuspack will be closed with a
suggestion to open an issue at https://github.com/MKergall/osmbonuspack

(feel free to delete whatever doesn't apply)

## Issue Type

[ ] Question
[ ] Bug
[ ] Improvement
[ ] Build system related
[ ] Performance
[ ] Documentation

### If it's a bug, version(s) of android this affects:

All

### Version of osmdroid the issue relates to:

5.6.5

**Comment by spyhunter99** [comment]
there's no built in way at the moment. It's possible to create a polygon around a marker by calculating the points of a circle. This has been asked recently

**Comment by spyhunter99** [comment]
Just added some code to make plotting circle's simple. feel free to use in your own code. it will be added in v6

**Comment by MKergall** [comment]
You already had Polyline.pointsAsCircle(center, radius) utility method.

**Comment by spyhunter99** [comment]
@MKergall doh! fixed

**Comment by jesuvijay** [comment]
Hi i found one bug that , In marker class, I wanna to rotate marker .when i try  to rotate marker like this sample code

public void tmpMarker() {


        markerTmp = new Marker(mMapView);
        markerTmp.setTitle("test");
        markerTmp.setPosition(geoPointTmp);
        markerTmp.setAnchor(Marker.ANCHOR_BOTTOM, Marker.ANCHOR_CENTER);

        markerTmp.setIcon(ContextCompat.getDrawable(getActivity(), R.drawable.direction_arrow));
        mMapView.getOverlays().add(markerTmp);

        mMapView.invalidate();
        iMapController.animateTo(mgeoPoint);
        final Handler handler = new Handler();
        final Runnable runnable = new Runnable() {
            @Override
            public void run() {

                markerTmp.setRotation(rotateMarker);
                markerTmp.
//                mMapView.invalidate();
                rotateMarker = rotateMarker + 30.0f;
                if (rotateMarker >= 360f) {
                    rotateMarker = 0.0f;
                }
                handler.postDelayed(this, 2000);

            }
        };
        handler.postDelayed(runnable, 2000);

    }
 i got the marker is moving little bit and rotate its like , rounding with small circle radius.. I wanna to rotate marker not moving even single bit just rotation..
