### ISSUE TITLE
MapView should handle onPause/onResume of the parent application

### ISSUE THREAD

**Issue by spyhunter99** [osmdroid/osmdroid#832]
## Issue Type

[ ] Improvement

## Description and/or steps/code to reproduce the problem

There's a whole bunch of strange and silly code that users of osmdroid have to work around in order to prevent memory leaks, sensor leaks, etc. This primarily happens when the application is paused (screen off or switch to a different app). This issue will add onPause and onResume on the map view and will clean up all the nonsense copy and paste boilerplate code.

This will be an API change that is unfortunately unavoidable. Affected classes

- OverlayManager
- DefaultOverlayManager
- MapView
- ZoomButtonsOverlay
- MyNewGpsLocationOverlay
- CompassOverlay

**Comment by spyhunter99** [comment]
implemented on branch feature/#823

**Comment by InI4** [comment]
That sounds good, though I need to work out the details to learn, what code I can throw away.
