### ISSUE TITLE
Polyline rendering issue with repetition on

### ISSUE THREAD

**Issue by spyhunter99** [osmdroid/osmdroid#835]
## Issue Type

[ ] Bug

## Description and/or steps/code to reproduce the problem

In the draw polyline sample, if I draw some reasonable length lines, then switch to panning move and pan the map in any direction, the previous configuration would draw lines/markers/polygons on instance of the world that was mostly within the view port. In other words, as you keep panning the map, the map overlays would continue to be drawn on a map instance that is on screen. This still functions fine for markers, but it stopped working recently for lines (vertical and horizontal) and for polygons (horizontal panning doesn't work as expected, however panning vertically does)

### Version of osmdroid the issue relates to:

6.0.0/master

**Comment by monsieurtanuki** [comment]
I guess it's related to the recent "world replication on/off" devs. I'll have a look at it.

**Comment by monsieurtanuki** [comment]
Solved in #838
