### ISSUE TITLE
New built in zoom controls do not work with map rotation

### ISSUE THREAD

**Issue by spyhunter99** [osmdroid/osmdroid#837]
## Issue Type

[ ] Bug

## Description and/or steps/code to reproduce the problem

set screen rotation, the try to use the buttons. I think the hit test is not taking into consideration canvas orientation

### Version of osmdroid the issue relates to:

6.0.0-snapshot

**Comment by monsieurtanuki** [comment]
@spyhunter99 I believe the same kind of "oops we don't take into account the map rotation" bug happens with the "Polyline" demos.
In the case of the poly demos, in `CustomPaintingSurface.touch_up`, there should be an additional `projection.unrotateAndScalePoint` before `projection.fromPixels` - or the other way around :)
I'll have a look at that when I'm through with the whole polyline performance x world replication issues.

**Comment by monsieurtanuki** [comment]
@spyhunter99 I can't find the custom zoom buttons anymore. Is that issue still relevant?

**Comment by spyhunter99** [comment]
It is, the integration points in mapview and the overlay were removed/reverted. We'll deal with it for the next version. I think just #888 is the last issue for release

**Comment by monsieurtanuki** [comment]
Fixed by #1190. Feel free to reopen.
