### ISSUE TITLE
exception opening MapView without zoom controls

### ISSUE THREAD

**Issue by shiroyagi** [osmdroid/osmdroid#839]
## Issue Type

[ ] Question
[*] Bug
[ ] Improvement
[ ] Build system related
[ ] Performance
[ ] Documentation

## Description and/or steps/code to reproduce the problem
`mMapView.setBuiltInZoomControls(false);`
results in:
```
01-01 13:31:12.759 E/AndroidRuntime( 2622): java.lang.NullPointerException: Attempt to invoke virtual method 'void org.osmdroid.views.overlay.ZoomButtonsOverlay.setZoomInEnabled(boolean)' on a null object reference
01-01 13:31:12.759 E/AndroidRuntime( 2622): 	at org.osmdroid.views.MapView.checkZoomButtons(MapView.java:1146)
01-01 13:31:12.759 E/AndroidRuntime( 2622): 	at org.osmdroid.views.MapView.setZoomLevel(MapView.java:415)
01-01 13:31:12.759 E/AndroidRuntime( 2622): 	at org.osmdroid.views.MapController.setZoom(MapController.java:235)

```
Fixed  by a test for null in checkZoomButtons()

### Version of osmdroid the issue relates to:

6.0.0

**Comment by spyhunter99** [comment]
I just pushed another snapshot, please update and retry. it should be fixed now

**Comment by shiroyagi** [comment]
Thanks, I was just testing 2924944
