### ISSUE TITLE
Unnecessary manifest permissions advised in Documentation

### ISSUE THREAD

**Issue by secaw** [osmdroid/osmdroid#841]
## Issue Type

[X] Documentation

Having just looked at `NetworkAvailabliltyCheck.java` in #840, I noticed that the permission "android.permission.ACCESS_WIFI_STATE" is not needed here and as far as I can see nowhere else in osmdroid. "android.permission.ACCESS_NETWORK_STATE" is sufficient, because only `ConnectivityManager` is called and not `WifiManager` for good reason.

Because every useless permission is bad for any app, I strongly suggest to remove the "android.permission.ACCESS_WIFI_STATE" permission recommendation from the how-to page https://github.com/osmdroid/osmdroid/wiki/How-to-use-the-osmdroid-library

In addition, the explicit permission "android.permission.ACCESS_COARSE_LOCATION" is useless too, because it is included in "android.permission.ACCESS_FINE_LOCATION".
See https://developer.android.com/guide/topics/location/strategies.html#Permission
> If you are using both NETWORK_PROVIDER and GPS_PROVIDER, then you need to request only the ACCESS_FINE_LOCATION permission, because it includes permission for both providers.

"android.permission.ACCESS_COARSE_LOCATION" actually does add a visible (useless) permission to the apps permission list, so I absolutely recommend to also remove this one from the advised permissions on the how-to page.

**Comment by spyhunter99** [comment]
ok i'll take a look at it. i also questioned it but it's been there for ages so i just figured it was needed

**Comment by secaw** [comment]
@spyhunter99 Great, luckily, all explicit permissions have been removed from the osmdroid manifest in #780, so it's only about the documentation now.

In order to reduce your own investigation work regarding "android.permission.ACCESS_WIFI_STATE", there is wrong information in some stackoverflow threads regarding network checks for example. Better directly take a look at https://developer.android.com/training/basics/network-ops/managing.html where it clearly states that you only need the "android.permission.ACCESS_NETWORK_STATE" permission for the checks we do in `NetworkAvailabliltyCheck.java` using `ConnectivityManager`, which are basically the same as the example ones on above page, including checking for "ConnectivityManager.TYPE_WIFI" vs. "ConnectivityManager.TYPE_MOBILE".
We do not use and do not need to use the `WifiManager`, that would need "android.permission.ACCESS_WIFI_STATE".

**Comment by spyhunter99** [comment]
wiki updated, thanks for bringing it up

**Comment by secaw** [comment]
@spyhunter99 Just checked the wiki: Unfortunately you removed too much! Please add "android.permission.ACCESS_NETWORK_STATE" again to the general permission list and under "Online tile provider" We need that one to do the NetworkAvailabliltyCheck. Thanks!

**Comment by spyhunter99** [comment]
better now?

**Comment by secaw** [comment]
Yes!
