### ISSUE TITLE
Sometimes i get java.io.FileNotFoundException: renderthemes/rendertheme-v4.xml

### ISSUE THREAD

**Issue by jesuvijay** [osmdroid/osmdroid#844]
W/System.err:android.content.res.AssetManager.openAsset(Native Method)
   at android.content.res.AssetManager.open(AssetManager.java:313)
W/System.err:     at android.content.res.AssetManager.open(AssetManager.java:287)
Below code

` xmlRenderTheme = new AssetsRenderTheme(getContext().getApplicationContext(), "renderthemes/", "rendertheme-v4.xml");`

**Comment by spyhunter99** [comment]
Is this a sometimes or an everytime issue?

I believe this was answered over on maps forge issue tracker. https://github.com/mapsforge/mapsforge/issues/980 

Basically, they moved some stuff around in mapsforge land and we didn't get the memo. You should be able to work around it by adding a dependency in your app for their theme library

**Comment by jesuvijay** [comment]
some times occured .and map loading takes time .. how to add custom render  theme to hide area,and some features

**Comment by jesuvijay** [comment]
how to change render theme in osmdroid maps forge 


            //this creates the forge provider and tile sources

            //protip: when changing themes, you should also change the tile source name to prevent cached tiles

            //null is ok here, uses the default rendering theme if it's not set
            XmlRenderTheme theme = null;
            try {
                theme = new AssetsRenderTheme(getContext().getApplicationContext(), "renderthemes/", "rendertheme-v4.xml");
            } catch (Exception ex) {
                ex.printStackTrace();
            }

            fromFiles = MapsForgeTileSource.createFromFiles(maps, theme, "rendertheme-v4");
            forge = new MapsForgeTileProvider(
                new SimpleRegisterReceiver(getContext()),
                fromFiles, null);


            mMapView.setTileProvider(forge);
solution if posssible example

**Comment by spyhunter99** [comment]
this should have been fixed in #597 with commit https://github.com/osmdroid/osmdroid/commit/71c1c03279bdd634ff036e0af984d450f62a5d95

Basically, i had to update some of our code and our dependencies. It should be fixed in 5.6.5 of osmdroid. what version are you using?

**Comment by jesuvijay** [comment]
5.6.5
