### ISSUE TITLE
6.0 Snapshot error can't find resources

### ISSUE THREAD

**Issue by grimace** [osmdroid/osmdroid#847]
Please note: issues related to or caused by osmbonuspack will be closed with a
suggestion to open an issue at https://github.com/MKergall/osmbonuspack

(feel free to delete whatever doesn't apply)

## Issue Type

[x] Question
[x ] Bug
[ ] Improvement
[ ] Build system related
[ ] Performance
[ ] Documentation

## Description and/or steps/code to reproduce the problem
I moved from 5.x to 6.0-SNAPSHOT by extracting the classes.jar and including in my android project.  When I try to load the map view I get:

`java.lang.NoClassDefFoundError: Failed resolution of: Lorg/osmdroid/library/R$drawable;`

### If it's a bug, version(s) of android this affects:

All

### Version of osmdroid the issue relates to:

6.0-Snapshot

**Comment by spyhunter99** [comment]
you also need to copy all the AAR resources and they need to land in the right package. Why aren't you just using the AAR outright?

**Comment by grimace** [comment]
Android Studio can't handle it : 
`Warning:Project app: Only Jar-type local dependencies are supported. Cannot handle: /libs/osmdroid-android-6.0.0-SNAPSHOT.aar`
me, I'm just trying to work around a bug in 5.x , fixed in 6.0

**Comment by spyhunter99** [comment]
Ahh "jar-type local dependencies". Do you have the aar in the libs folder? Regardless, there is a way to make gradle load a local aar. Try this:
https://stackoverflow.com/a/33214781/1203182

or include the aar normally using the following
https://github.com/osmdroid/osmdroid/wiki/How-to-add-the-osmdroid-library-via-Gradle
