### ISSUE TITLE
hi when u will update compile "org.osmdroid:osmdroid-mapsforge:<VERSION>". current verrsion is 5.6.5 same osmdroid version.. in latest update all icons are converted to svg and need faster render like google maps if possible

### ISSUE THREAD

**Issue by jesuvijay** [osmdroid/osmdroid#848]
Please note: issues related to or caused by osmbonuspack will be closed with a
suggestion to open an issue at https://github.com/MKergall/osmbonuspack

(feel free to delete whatever doesn't apply)

## Issue Type

[ ] Question
[ ] Bug
[ ] Improvement
[ ] Build system related
[ ] Performance
[ ] Documentation

### If it's a bug, version(s) of android this affects:

All

### Version of osmdroid the issue relates to:

5.6.5

**Comment by spyhunter99** [comment]
what icons are you talking about?

**Comment by jesuvijay** [comment]
Mapforge offline map  petrol,stations,shopping,traffic signal icons are
changed to svg .... Ie mapsforge offline  icons are changed. I'm using
osmdroid mapview  so i cant use the separated mapsforge latest (0.9)
version class to load map files.. In mapsforge,they use mapsforge mapview,
so icant use the latest version in osmdroidmapview...solution plz

**Comment by secaw** [comment]
So you're talking about mapsforge rendertheme icons? Osmdroid does not change them.
Re mapsforge performance:  Those vector maps need to be rendered to bitmaps, this is pretty heavy CPU wise and therefore takes some time, depending on the map details. There's nothing you can do about it.

**Comment by jesuvijay** [comment]
thk u
