### ISSUE TITLE
Allow touches to be handled by both MultiTouchController and GestureDetector

### ISSUE THREAD

**Issue by kurtzmarc** [osmdroid/osmdroid#85]
We pass MotionEvents to be passed to MultiTouchController and if they handle it, we stop processing. I propose we instead allow MotionEvents to pass by both MultiTouchController and GestureDetector and then stop processing if either one handles it.

This will provide two things:

1. It will allow two-finger scrolling. So while pinching, we could also scroll.
1. It will prevent two-finger taps from triggering onSingleTapConfirmed from being fired. For example, when you go into the Itemized overlay w/focus sample and then touch the screen with two fingers, it can trigger a tap on one of the items.

**Comment by spyhunter99** [comment]
looking at the current code, the MTC and the gesture detector both get an opportunity to handle it, even if the first has handled it already. Since this code is already in for 4.3, might at well close it.
