### ISSUE TITLE
Map Repetition Improvement

### ISSUE THREAD

**Issue by monsieurtanuki** [osmdroid/osmdroid#851]
From @secaw in #845

> I would love to use the map with no vertical repetition and seamless horizontal repetition, just like Google Maps V1 does, but currently it is not really usable, because with max north / south scrolling, the map now disappears. Instead, with max scroll the map should stay half in the view in order to still be able to do a proper setCenter(), exactly like it behaves in Google Maps V1.
I actually think, this way with vertical repetition off should be the default behaviour for osmdroid. Is that possible?

**Comment by monsieurtanuki** [comment]
I'm not a big fan of the current "no vertical replication" implementation either.
Though, personally I'd prefer to have the north of the map on the top of the screen, when you'd prefer to see it on the center of the screen.

So far we have 3 ways of seeing things:
* unlimited scroll (current implementation)
* scroll limited to the center of the screen (your suggestion)
* scroll limited to the border of the screen (my suggestion)

Guys, any other way of seeing things? Let's talk about it, and either find the best suggestion or agree on implementing different suggestions.

**Comment by secaw** [comment]
@monsieurtanuki Thanks for starting a new issue on this. Definitely clearer that way.

Your suggestion of course would be visually most desirable. BUT `setCenter()` would not work for points between mapview middle and respective border, because there would be no space on top/bottom of the map! That's why we need the center screen solution, except you have another idea for the functioning of `setCenter()`. Again, Google Maps V1 also has the scroll limit to center screen probably for this reason.

**Comment by Maradox** [comment]
Technically speaking this would be a change to the 'scrollableAreaLimit' right? Currently it only supports "no restrictions" or "restrictions in all directions". If it could be limited to '(-infinite,-90, infinite, +90)' it would have the desired effect.

**Comment by monsieurtanuki** [comment]
@Maradox That can be part of the answer: being able to set separate west-east and north-south limits, with the possibility to set one (e.g. north-south) but not the other (e.g. west-east).

But there's also the question: "When there's a limit, what's the impact on the UX?"
If we were to update the code in order to have a north-south limit (+85° -85°) without any west-east limit (should be very easy to implement btw), if you're on zoom 5 and want to go to the north again and again, you end up with the top of your screen at the north limit (+85°). That's fine for me as an end user.
But @secaw has a different point of view, and in the same circumstances would like to see the north limit (85°) at the middle of the screen (am I correct?). Fair enough.

@secaw Regardless of this 851 issue, do you agree with the current UX for scroll limit? (cf. More Samples / Events / Limited scroll area)
Could we also say that _only_ in the case we're dealing with +-85° latitude limit, you would like to be able to add an offset to the map so that the north limit is displayed x pixel from the top of the screen? (same for south)

**Comment by secaw** [comment]
@monsieurtanuki Yes, I still think, we should be able to center the map even on far northern / southern coordinates at low zoom levels, so the pixel space seems necessary to me. I think, your drafted solution sounds great and agree with all of this. Thanks you!

**Comment by monsieurtanuki** [comment]
@secaw Oh, there's something I just understood in your expressed needs: the possible incoherence between `setCenter` and the scrollable limits. What you actually need is a method called `setCenterRegardlessOfThePossibleScrollLimits`, don't you?

**Comment by monsieurtanuki** [comment]
@secaw Well that wouldn't work that way: even if you manage to center the map the very first time, the slightest scroll in any direction will apply the scroll limits and make the map jump.

This is a UX problem:
* imagine the scroll limits are on France and the set center is in Tokyo - what should happen? Today Tokyo would be dismissed and the map center would be the center of France. What shall we do when the center is not inside the limits?
* imagine the scroll limits are on California and the center is set to San Diego - you said you expected the actual map center to be on San Diego. From San Diego, where am I able to scroll? To the south so that the top of my map is San Diego? If I scroll to Los Angeles: should I be allowed to scroll back to San Diego? But not further south or west? Or north or east?

Could you clarify this confusion? Maybe with use cases.

**Comment by secaw** [comment]
@monsieurtanuki In regards of disabling vertical map replication gracefully, initially I dind't think about using `setScrollableAreaLimitDouble`, but by somehow improving the current implementation.

I absolutely agree, that it can not be possible to set the map center outside the scroll area limit lat/lons, that wouldn't make sense at all.

But I liked your idea to be able to set an additional scroll space in pixels around the scrollable area (x,y). E.g. if I would set this to mapview half width /  half height respectively, then I'd be able to actually _really_ center any point _within_ the ScrollableAreaLimit in mapview on any zoom level.

Examples hopefully make it clear:

![osmdroid_mapview_scrolllimit-setcenter](https://user-images.githubusercontent.com/28442368/34830370-ef9b637a-f6e3-11e7-83a3-64bb76a8711a.png)

![osmdroid_mapview_ideal-setcenter](https://user-images.githubusercontent.com/28442368/34830376-f65169c6-f6e3-11e7-91b1-9e942bed75f9.png)

![osmdroid_mapview_setcenter-with-bbox](https://user-images.githubusercontent.com/28442368/34830390-fdbe0200-f6e3-11e7-9663-4539cd283183.png)

![osmdroid_mapview_setcenter-with-bbox-and-pixel-space](https://user-images.githubusercontent.com/28442368/34830400-0377cbea-f6e4-11e7-8e1a-0a445ca650af.png)

**Comment by monsieurtanuki** [comment]
@secaw Thank you for these screenshots; I guess now the goal is clear.
Just one question: how are we supposed to react if you try to set a center that is not is the current scroll limit area? Who wins?

**Comment by monsieurtanuki** [comment]
@secaw Just PR'ed #867, which should work OK regarding your needs.

**Comment by secaw** [comment]
@monsieurtanuki Sorry for late reply on last comment. I think if you try to set a center that is not in the current scroll limit area, this should not be possible. I guess, it would end up stopping at the area bounds in direction of the given center point? That would be logical. Will comment on #867 there in a minute...

**Comment by monsieurtanuki** [comment]
@secaw I know this doesn't make sense to set the center beyond the scroll limit.
But there's no way I can't prevent anybody to try to do that.
My question is: what should we do in this case?
* ignore the setCenter statement and keep the scroll limits
* disable the scroll limits and set the map center
* let the algorithm run with those distorted values and hope it's for the best (current default implementation btw)

**Comment by secaw** [comment]
Ok, understand - most times `animateTo` is probably used in such cases instead of `setCenter` anyways, which will then stop at area bounds as described, I guess. I would leave setCenter behaviour at current state, meaning that it centers outside, but jumps back to area when map is being moved again, right? Would be an obvious case of contradiction and not seem like a bug by osmdroid.

**Comment by secaw** [comment]
@monsieurtanuki Thanks to your advice in the comments to #867 it's now working beautifully. Great work as usual. For the past year, user experience with map visibility and interaction has improved dramatically with tile approximation, floating point zoom / scale etc. Now finally being able to have a useful "single" map, that only repeats horizontally for me really is the completion of all of this. Thank you.

**Comment by monsieurtanuki** [comment]
@secaw Thank you for your "thank you" note ;)

To be 100% honest if I remember well the "no horizontal and/or vertical map replication" was @Maradox 's idea and dev (#722), possibly enhanced by @spyhunter99 's additional suggestions.
In this particular case I just added the "limit longitudes and/or latitudes with extra size" feature.

Good team work!

**Comment by monsieurtanuki** [comment]
Solved by #867

**Comment by secaw** [comment]
> Good team work!

Absolutely, thanks to everybody!!!
