### ISSUE TITLE
SimpleFastPointOverlay redraw bug (working on it)

### ISSUE THREAD

**Issue by miguel-porto** [osmdroid/osmdroid#853]
Hi,
Just to let you know that I'm fixing a bug on SimpleFastPointOverlay which prevented the points to be correctly drawn during pinch zoom. Will do a PR soon, that increases the UX when drawing and overlay with tens of thousands of points.
Cheers.

**Comment by spyhunter99** [comment]
ok, i'd like to cut the version shortly
