### ISSUE TITLE
DefaultConfigurationProvider inconsistencies

### ISSUE THREAD

**Issue by cbalster** [osmdroid/osmdroid#858]
## Issue Type

[x] Bug
[x] Improvement

## Description and/or steps/code to reproduce the problem

In DefaultConfigurationProvider.load() - if no basepath has been saved before and the default discovery heuristics don't return a writable path - base and cache paths are set to the applications data directory. Currently these are set to the same path which is inconsistent with the /osmdroid/tiles path used everywhere else. Also Context.GetFilesDir() can be used instead of construction the path by hand.

When loading the preferences the default values are not all using the defaults defined as member variables and thus duplicate code and possibly introduce inconsistencies.

**Comment by spyhunter99** [comment]
thanks!
