### ISSUE TITLE
Zoom to bounding box not working

### ISSUE THREAD

**Issue by MKergall** [osmdroid/osmdroid#866]
## Issue Type

[ ] Question
[ X] Bug
[ ] Improvement
[ ] Build system related
[ ] Performance
[ ] Documentation

## Description and/or steps/code to reproduce the problem
Easy to observe with the "Zoom to bounding box" sample of the demo app: 
The map is zooming, apparently to the correct level, but is not moving at the specified bounding box. 
I tried changes on: animated flag (true or false), border (0 or 10), no improvement. 

We have 2 issues: 

1) in zoomToBoundingBox, replace: 
getController().setCenter(boundingBox.getCenterWithDateLine());
by: 
getController().setCenter(boundingBox.getCenter());
and it will be OK when animated=false. 

This means boundingBox.getCenterWithDateLine is wrong. 

2) But even with this change, it's still KO when animated=true. 

### Version of osmdroid the issue relates to:
Head (6.0)

**Comment by monsieurtanuki** [comment]
@MKergall I think there's a combination of:
* a bug in `BoundingBox.getCenterLongitude()` - I'm about to fix it
* a bad representation of `Polygon` when the west is on the right of the east - I'm about to fix it
* and possibly something to fix during the animation

**Comment by monsieurtanuki** [comment]
@MKergall Just PR'ed #882 as a fix.
Regarding the animation (which is still set to `false` in the demo), anyway it won't look fantastic as we try at the same time to set immediately the center and to start a slow zoom animation. Which is prone to bring side effect approximations.
In a better world we would have an animation that animates at the same time towards a new zoom level and towards a new center.

**Comment by spyhunter99** [comment]
@MKergall i've updated the snapshot please retest this

**Comment by MKergall** [comment]
The animation could be improved (I've seen superb animations on other map tools, "flying" from origin to destination), but yes, it works, definitely.
