### ISSUE TITLE
NPE with mapView.setBuiltInZoomControls(false)

### ISSUE THREAD

**Issue by secaw** [osmdroid/osmdroid#871]
## Issue Type

[ ] Question
[X] Bug
[ ] Improvement
[ ] Build system related
[ ] Performance
[ ] Documentation

## Description and/or steps/code to reproduce the problem

MapView crashes with `mapView.setBuiltInZoomControls(false)`

Logcat:
_Attempt to invoke virtual method 'void org.osmdroid.views.overlay.ZoomButtonsOverlay.setZoomInEnabled(boolean)' on a null object reference_

### Version of osmdroid the issue relates to:

6.0.0

**Comment by spyhunter99** [comment]
Doesn't make sense, references to that class were removed a week or so ago

**Comment by spyhunter99** [comment]
actually the class was removed too.

**Comment by secaw** [comment]
Ok sorry, it actually happened with branch https://github.com/osmdroid/osmdroid/tree/feature/%23851
Thought it was based on current master, will check again tomorrow.

**Comment by spyhunter99** [comment]
k i just pushed another updated snapshot to central. either use that or update that branch
