### ISSUE TITLE
Missing FAQ for basic customization

### ISSUE THREAD

**Issue by E3V3A** [osmdroid/osmdroid#88]
Hello, 
We over at [AIMSICD](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector) really love your maps, and have helped us avoid the Gmap bloatware. 
But, please add some information on how to do simple changes to the map items. Basic things like customization of:
 - the map *pins* and their colors, 
 - how to include a compass? 
 - how to draw lines between two points

I just can't find this anywhere, or maybe I'm Googling for the wrong stuff...

**Comment by E3V3A** [comment]
> No problem. I will try to take on this task. Just give me some time.

Hi @ziem perhaps you have more time now that all the holidays are over?

**Comment by ziem** [comment]
@E3V3A In the last two weeks I haven't had much time ;(.

**Comment by a2800276** [comment]
maybe just publishing the javadoc somewhere to browse would be a good start. That way people can provide some documentation patches ....

**Comment by neilboyd** [comment]
@a2800276 that's a good idea. I'll work on that.

**Comment by neilboyd** [comment]
I uploaded the javadoc and added a link to the front page readme.

**Comment by spyhunter99** [comment]
wiki updated.
https://github.com/osmdroid/osmdroid/wiki/How-to-use-the-osmdroid-library
