### ISSUE TITLE
Provide a utility method to get ground scale resolution from the current map view

### ISSUE THREAD

**Issue by spyhunter99** [osmdroid/osmdroid#881]
## Issue Type

[x] Improvement
[ ] Build system related
[ ] Performance
[ ] Documentation

**Comment by monsieurtanuki** [comment]
@spyhunter99 Wouldn't that be something like `TileSystem.GroundResolution(final double latitude, final double zoomLevel)`?

**Comment by spyhunter99** [comment]
ha yup, didn't even know that was there. What unit of measure is that in? looks like meters/pixel or what?

**Comment by spyhunter99** [comment]
i'll update the docs and close this...
