### ISSUE TITLE
Draw a bitmap with corners 4 coordinates

### ISSUE THREAD

**Issue by pasniak** [osmdroid/osmdroid#883]
## Issue Type

[x] Question

6.0.0

Do you maybe have an example of code overlying a bitmap (big, as in continent-sized) according to 2 corner coordinates? 

I looked at the GroundOverlay in bonuspack but it takes middle point.

**Comment by MKergall** [comment]
Googla Maps API "setPositionFromBounds(LatLngBounds bounds)" is not implemented yet in bonuspack. I agree it would make sense to add it. I will try to do that ... "soon". 

In the meantime, from your 2 corner coordinates, it's quite easy to determine :
- the middle: GeoPoint myMiddle.fromCenterBetween(c1, c2)
- the lat and lon spans in meters: using GeoPoint.distanceToAsDouble

(if you code that and provide me the piece of code, it will be even shorter for me to add the missing API...)

**Comment by spyhunter99** [comment]
https://github.com/osmdroid/osmdroid/issues/684 related issue, probably a duplicate.

Placing an image on the map is one thing, but getting it to scale properly so that the control points are at the correct locations is the difficult part. Since the reset floating point zoom and map tile approximately now exist, the logic should be available for this purpose

**Comment by pasniak** [comment]
I have a working "GroundOverlay2" , where should I check it in for PR?

**Comment by spyhunter99** [comment]
we'll gladly take it here.

**Comment by MKergall** [comment]
@spyhunter99 Effectively, having the GroundOverlay in osmdroid makes sense. 
@pasniak Did you started from the OsmBonusPack GroundOverlay, or did you started from scratch?

**Comment by spyhunter99** [comment]
@MKergall if you're ok with it, I can start the preparations for merging GroundOverlay from osmbonuspack into osmdroid, including the change history. It's a bit of a pain with history but worth it. Is there anything else? Perhaps the Douglas Peucker point reducer?

**Comment by pasniak** [comment]
Sorry for delay, I was out of town. I took Ground Overlay it looks quite a different, I'll PR soon.
