### ISSUE TITLE
Displaying contributors on OSMDroid map

### ISSUE THREAD

**Issue by Eirpote** [osmdroid/osmdroid#886]
Hi, I'm developping an android app on Android studio 2.2.3. For that I've used Osmdroid 5.6.1 and it works correctly.
My problem is that I cannot find how to display "© OpenStreetMap contributors" on the corner of the Map as I am supposed to. I haven't been able to find any hint on the web for that. Anyone could help me ?

Thanks !

**Comment by spyhunter99** [comment]
according to the wiki https://github.com/osmdroid/osmdroid/wiki/Changelog#563
it was added in 5.6.3

looks like there's some example code here:
https://github.com/osmdroid/osmdroid/blob/master/OpenStreetMapViewer/src/main/java/org/osmdroid/StarterMapFragment.java#L152

**Comment by spyhunter99** [comment]
guess i'll mark this as answered, feel free to comment back if there are more questions

**Comment by Eirpote** [comment]
Thanks for the fast answer spyhunter. I didn't thought about checking lastest release.
Regards
