### ISSUE TITLE
API 10, can't zoom in

### ISSUE THREAD

**Issue by spyhunter99** [osmdroid/osmdroid#888]
## Issue Type

[ ] Bug

## Description and/or steps/code to reproduce the problem

can't zoom in via double tap or the built in zoom buttons. pinch zoom works fine though

## Environment

API 10 genymotion vm

### If it's a bug, version(s) of android this affects:

10

### Version of osmdroid the issue relates to:

master/6.0.0-SNAPSHOT

**Comment by spyhunter99** [comment]
the animation works by at the end of the animation, the map snaps back to the original zoom level

**Comment by spyhunter99** [comment]
looks like the issue is in map controller and the zoom animators

**Comment by spyhunter99** [comment]
zoom out works, however map tiles don't load immediately...
![image](https://user-images.githubusercontent.com/1975321/35197731-db7e6cc2-feb1-11e7-9374-3ecb12874909.png)

**Comment by spyhunter99** [comment]
@monsieurtanuki i stepped through this one several times and can't seem to figure out what the cause is. I also did some diff's between current master and from the last release. It's not clear what's causing this. Do you have any ideas?

**Comment by monsieurtanuki** [comment]
@spyhunter99 An idea about which part - the double click zoom in going back to initial zoom level, or the slow zoom out?
I don't even know how to test in the "API 10 genymotion vm" context - is that some kind of emulator I should run the app on via Android Studio?
Anyway, I'll have a look at the code tomorrow

**Comment by spyhunter99** [comment]
API10 on AVD would work too. Genymotion is a VirtualBox based solution to get relatively fast emulation on windows. I used it because i have no choice (AMD cpu). The google provided android emulator only works on intel CPUs.

Anyone, i can take a video, hang on...

**Comment by spyhunter99** [comment]
https://youtu.be/ALgIiCWBGRQ

**Comment by monsieurtanuki** [comment]
From the video, I guess the problem in both cases is the action just after the animation:
* for the zoom out, an `invalidate` should do the trick
* for the zoom in, perhaps an explicit `setZoom`
Why are the behaviors different between zoom in and out? Now I need to have a look at the code.

**Comment by monsieurtanuki** [comment]
In the code there are explicit mentions of API 10.
More specifically, in `MapController.onAnimationEnd`, there are distinct statements depending on `if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.HONEYCOMB)` (i.e. `>= 11`).
My guess would be, in the API 10 case, to store the target zoom before the animation starts and to perform something like a `MapView.setZoomLevel` in `MapController.onAnimationEnd`.
@spyhunter99 Would you do that fix? Of course I could type the fix, but I'm afraid it would take me a lot of energy to understand how to specifically run on API 10.

**Comment by spyhunter99** [comment]
on it
