### ISSUE TITLE
Poor performance with 1000s of points

### ISSUE THREAD

**Issue by hanokhaloni** [osmdroid/osmdroid#89]
Working off of the latest code branch, we had something like 500 points on the same overlay and performance was reasonable. Under load testing with 2000 points - the app usually crashed with a "Application wait/close" message.

**Comment by neilboyd** [comment]
How are you drawing the points? Is there any relevant code you can share?
How is this issue different to #86?

**Comment by hanokhaloni** [comment]
I use something like this:
 
    mapOverlayItems = new ItemizedIconOverlay(context, buildOverlayItemList(mapInfoList), null);
    if(overlayIndex > 0) { //I make sure that the 1st overlay is the mapOverlayItems               
        overlayManager.set(overlayIndex, mapOverlayItems);
    } else {
        overlayManager.add(mapOverlayItems);     
    }
    mapView.invalidate();

**Comment by kurtzmarc** [comment]
It sounds like this ticket can be closed. Please reopen if you need additional information.
