### ISSUE TITLE
how to place maker above all the other overlay,such as polyline,polygon?

### ISSUE THREAD

**Issue by xiaozuozi** [osmdroid/osmdroid#896]
Please note: issues related to or caused by osmbonuspack will be closed with a
suggestion to open an issue at https://github.com/MKergall/osmbonuspack

(feel free to delete whatever doesn't apply)

## Issue Type

[ ] Question
[ ] Bug
[ ] Improvement
[ ] Build system related
[ ] Performance
[ ] Documentation

### If it's a bug, version(s) of android this affects:

All

### Version of osmdroid the issue relates to:

5.6.5

**Comment by spyhunter99** [comment]
stuff is rendered on top of the map in the order that they added to the overlay manager. easiest solution, remove it from the map and add it again

**Comment by xiaozuozi** [comment]
do you have the other ways to deal with the question?

**Comment by spyhunter99** [comment]
Not at the moment no

**Comment by xiaozuozi** [comment]
thank you
