### ISSUE TITLE
Smooth animation to new zoom + new center

### ISSUE THREAD

**Issue by monsieurtanuki** [osmdroid/osmdroid#897]
## Issue Type
- [x] Improvement

## Description and/or steps/code to reproduce the problem
cf. comments in #866
@monsieurtanuki
> In a better world we would have an animation that animates at the same time towards a new zoom level and towards a new center.

@MKergall 
> The animation could be improved (I've seen superb animations on other map tools, "flying" from origin to destination)

### Version of osmdroid the issue relates to:

6.0.0

**Comment by pierre-binauld** [comment]
Hi,
Do you know where this enhancement will be implemented ?
Or do you know some workaround ?

**Comment by monsieurtanuki** [comment]
For the moment we only have `MapController.animateTo(IGeoPoint point)`: if you're already on the same zoom level, that's perfect.

A workaround would be to set the zoom first and then use `animateTo`, possibly using something like `View.post(Runnable)` in order to ensure that the zoom is correctly set before the animation starts.

The current `animateTo(IGeoPoint point)` method uses a `Scroller`, which scrolls a `View` step by step in order to play an animation.
But for `animateTo(IGeoPoint point, double zoom)` we would also need to "scroll the zoom" from the current zoom to the destination zoom. The whole thing can probably be done with a [`ValueAnimator`](https://developer.android.com/reference/android/animation/ValueAnimator.html).

I'll have a look at that in the following weeks.

**Comment by monsieurtanuki** [comment]
I confirm: the idea is to use something similar to `MapController.ZoomAnimatorListener`.
I'll merge the solution within a week.

**Comment by monsieurtanuki** [comment]
@pierre-binauld Implemented in #991 
@MKergall Enjoy the new "More Samples / Events / Animate To" flying carpet effect
