### ISSUE TITLE
how to remove marker from map?

### ISSUE THREAD

**Issue by xiaozuozi** [osmdroid/osmdroid#899]
Please note: issues related to or caused by osmbonuspack will be closed with a
suggestion to open an issue at https://github.com/MKergall/osmbonuspack

(feel free to delete whatever doesn't apply)

## Issue Type

[ ] Question
[ ] Bug
[ ] Improvement
[ ] Build system related
[ ] Performance
[ ] Documentation

### If it's a bug, version(s) of android this affects:

All

### Version of osmdroid the issue relates to:

5.6.5

**Comment by spyhunter99** [comment]
map.getOverlayManager().remove(marker);

**Comment by xiaozuozi** [comment]
if map.getOverlaysr().remove(marker) can remove marker?

**Comment by xiaozuozi** [comment]
if (focusMarker == null) {
                focusMarker = addPointFocusToMap(context, latLng, R.drawable.vertice_focus, map);
            } else {
                focusMarker.setPosition(new GeoPoint(latLng.latitude, latLng.longitude));
                focusMarker.setEnabled(true);
            }
if (focusMarker == null) {
                focusMarker = addPointFocusToMap(context, latLng, R.drawable.vertice_focus, map);
            } else {
                focusMarker.setPosition(new GeoPoint(latLng.latitude, latLng.longitude));
                focusMarker.setEnabled(true);
            }
when i use map.getOverlaysr().remove(marker) to remove marker from map,but i can't remove the maker?

**Comment by xiaozuozi** [comment]
if (focusMarker == null) {
                focusMarker = addPointFocusToMap(context, latLng, R.drawable.vertice_focus, map);
            } else {
                focusMarker.setPosition(new GeoPoint(latLng.latitude, latLng.longitude));
                focusMarker.setEnabled(true);
            }
            if (focus2Marker != null) {
                focus2Marker.setEnabled(false);
            }
 private static Marker addPointFocusToMap(Context context, LatLng latLng, int var0, MapView map) {

        GeoPoint geoPoint = new GeoPoint(latLng.latitude, latLng.longitude);
        Marker marker = new Marker(map);
        marker.setIcon(ContextCompat.getDrawable(context, var0));
        marker.setPosition(geoPoint);
        marker.setFlat(true);
        marker.setInfoWindow(null);
        verticeMarkers2.add(marker);
        map.getOverlayManager().add(marker);
        return marker;
    }
when i use map.getOverlayManager().remove(marker) to remove marker from map,i cant't remove the marker,the marker will still show on the map

**Comment by spyhunter99** [comment]
add a `map.invalidate();`

**Comment by xiaozuozi** [comment]
if (focusMarker != null) {
            mapView.getOverlayManager().remove(focusMarker);
        }
        if (focus2Marker != null) {
            mapView.getOverlayManager().remove(focus2Marker);
        }
it useless to add a map.invalidate();

**Comment by xiaozuozi** [comment]
if (focusMarker != null) {
mapView.getOverlayManager().remove(focusMarker);
}
if (focus2Marker != null) {
mapView.getOverlayManager().remove(focus2Marker);
}
it is useless to add a map.invalidate();

**Comment by spyhunter99** [comment]
mmk anything else i can help you with?

**Comment by xiaozuozi** [comment]
no,thanks
