### ISSUE TITLE
4.3 version of osmdroid

### ISSUE THREAD

**Issue by courdi95** [osmdroid/osmdroid#90]
Hello
Is there any schedule for 4.3 version avalaibility ?

Will this version correct offset map center bug ? Today i am using 4.2 with the delay patch.

What will the modification of 4.3 vs 4.2 ?

**Comment by ziem** [comment]
When can we expect 4.3?

**Comment by neilboyd** [comment]
Is now a good time to do it? What do you think @kurtzmarc?

**Comment by kurtzmarc** [comment]
Yes, I think now is a good time for a release.

**Comment by neilboyd** [comment]
What is the patch you refer to @courdi95? Is it already in the code base?

**Comment by devemux86** [comment]
I think he's referring to the ```ViewTreeObserver``` method mentioned in #22.
But that's now properly corrected in master code.

**Comment by neilboyd** [comment]
I've released to Maven Central. I'll release to Play tomorrow.

**Comment by courdi95** [comment]
Thank you !!!

4.3 is now on Maven :
https://oss.sonatype.org/content/groups/public/org/osmdroid/osmdroid-android/4.3/


2015-01-12 23:22 GMT+01:00 Neil Boyd <notifications@github.com>:

**Comment by neilboyd** [comment]
Also released to Google Play
