### ISSUE TITLE
Snapshot maven target again not working

### ISSUE THREAD

**Issue by InI4** [osmdroid/osmdroid#901]
Please note: issues related to or caused by osmbonuspack will be closed with a
suggestion to open an issue at https://github.com/MKergall/osmbonuspack

(feel free to delete whatever doesn't apply)

## Issue Type

[ ] Question
[ ] Bug
[ ] Improvement
[ X] Build system related
[ ] Performance
[ ] Documentation

## Description and/or steps/code to reproduce the problem
This is related to #824. I wanted to check back, how 6.0.0 is doing. Switching to my apps osmdroid 6.0.0 branch, I realized, that the maven target fails to download the snapshot jar again. This time it is not access rights. I am not sure what it is, but can it be, the XML Metadata on Sonatype is wrong now?

### Version of osmdroid the issue relates to:

6.0.0

**Comment by spyhunter99** [comment]
https://oss.sonatype.org/service/local/repositories/snapshots/content/org/osmdroid/osmdroid-android/6.0.0-SNAPSHOT/

https://oss.sonatype.org/service/local/repositories/snapshots/content/org/osmdroid/osmdroid-android/6.0.0-SNAPSHOT/osmdroid-android-6.0.0-SNAPSHOT.pom

it "looks" ok. Is there any other error message?

**Comment by InI4** [comment]
I will retry soon. So far I am watching gradle and it simply tells me, it does not find the SNAPSHOT. Wait for me.

**Comment by spyhunter99** [comment]
i just updated the snapshot, give it a try

**Comment by InI4** [comment]
It's just I still wanted to get gradle to do the downloading for me. I do get neither repository working:
        url 'https://oss.sonatype.org/content/repositories/snapshots/' 
        url 'https://oss.sonatype.org/service/local/repositories/snapshots/content/'

**Comment by spyhunter99** [comment]
can you run gradle with -x ( i think that's it) in turns on debug output, you're looking for the full url that it's trying to download from
