### ISSUE TITLE
The mapview shows grid

### ISSUE THREAD

**Issue by Diaislam** [osmdroid/osmdroid#905]
## Mapview only shows grid

i have made a simple usage for osm mapview and it wokrs fine very the issue is , it doesn't work in phones it shows the grid and the position and the marker but not the map , but in my virtual device it shows the map !

my device configuration is android 7 , and tried it with another android 6.0 device same results
i'm using osmdroid 5.6.5

 Manifest 
             `  <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>
    <uses-permission android:name="android.permission.ACCESS_WIFI_STATE"/>
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />`

here is my mapview activity :

`Intent intent = getIntent();
        String latitude = intent.getStringExtra("latitude");
        String longitude = intent.getStringExtra("longitude");

        // --------- the OSM VIEW ----------- //

        osm = (MapView) findViewById(R.id.streetmap);
        osm.setTileSource(TileSourceFactory.MAPNIK);

        osm.setBuiltInZoomControls(true);
        osm.setMultiTouchControls(true);

        osmController =(MapController) osm.getController();
        osmController.setZoom(22);
        GeoPoint location;

           location = new GeoPoint(Double.valueOf(latitude),Double.valueOf(longitude));
addMarker(location);
            osmController.animateTo(location);

 public void addMarker(GeoPoint location){

        Marker marker = new Marker(osm);
        marker.setPosition(location);
        marker.setAnchor(Marker.ANCHOR_CENTER, Marker.ANCHOR_BOTTOM);
        marker.setIcon(getResources().getDrawable(R.drawable.ic_dashboard_truck));

        osm.getOverlays().clear();
        osm.getOverlays().add(marker);
        osm.invalidate();
    }

`

5.6.5

**Comment by secaw** [comment]
`osmController.setZoom(22);`

MAPNIK has maxZoom of 19 !

**Comment by spyhunter99** [comment]
good catch, that's probably it

**Comment by spyhunter99** [comment]
closing due to lack of feedback, reopen or comment back if this is still an issue

**Comment by neoacevedo** [comment]
After one year, I have the same issue, and the maxZoom is set to 19

**Comment by spyhunter99** [comment]
@neoacevedo  is it broken in your app or one of the demo apps?
check the usual

grant runtime permissions before displaying the map and/or inflating the view containing the map
set the user agent before displaying the map
turn on logging and debugging using Configuration.getInstance().set.....
monitor logcat for error messages.

**Comment by neoacevedo** [comment]
Hi, both apps (demo and prod).
In prod, only around the marker when the app is launched for first time the
tile is loaded but no after no tile is displayed.
In this app we are using an old version (5.2 I think)

**Comment by neoacevedo** [comment]
In this issue (https://github.com/osmdroid/osmdroid/issues/1288) says that I have to change the user-agent. I did it. 

I don't know if network performance for tiles server is too slow. Question, what are the ports for mapnik? 80, 443?

**Comment by spyhunter99** [comment]
when you say 'demo app', are you referring to this one?  https://play.google.com/store/apps/details?id=org.osmdroid

**Comment by neoacevedo** [comment]
No, my app demo. I'm sorry. I had to be more clear.
But I am finding, some devices can load the map, but some others no.

**Comment by spyhunter99** [comment]
mmk, please see if you can reproduce with our demo app

**Comment by neoacevedo** [comment]
@spyhunter99 I can't reproduce it. The tiles take time to be displayed but they are.
This code I use to display the tiles:
```java
try {
        PackageManager pm = activity.getPackageManager();
        String packageName = activity.getPackageName();
        PackageInfo pInfo = pm.getPackageInfo(packageName, 0);
        String version = pInfo.versionName;
        Configuration.getInstance().setUserAgentValue(activity.getPackageName() + "/" + version);
} catch (PackageManager.NameNotFoundException e) {
        e.printStackTrace();
}

final ITileSource tileSource = TileSourceFactory.DEFAULT_TILE_SOURCE;
map.setTileSource(tileSource);
```
But again, in some devices it works.

**Comment by neoacevedo** [comment]
UPDATE: my co-workers said me after a very very very long time the tiles are displayed. I am seeing it just now. The map shows the grid but I will have to wait I think for 2-3 hours with the app opened to check if it works (what my team said works).

**Comment by spyhunter99** [comment]
you need to figure out what's common on those devices and to turn on the debugging settings `Configuration.getInstance().set...`   while watching logcat.  I can't reproduce it here

**Comment by monsieurtanuki** [comment]
@neoacevedo My 2 cents: in your screenshot the grid seems very tightened. Could the current issue be a side effect problem that it's too demanding for the tile cache with its standard size to store that many tiles?

**Comment by neoacevedo** [comment]
Mmm in that screenshot I was using the version 4.1.
Currently I'm using the version 6.0.3 with zoom = 15.
