### ISSUE TITLE
Esri Shape file support

### ISSUE THREAD

**Issue by spyhunter99** [osmdroid/osmdroid#906]
## Issue Type

[x] Improvement

## Description and/or steps/code to reproduce the problem

Support importing/convert an esri shape file to osm style overlays

**Comment by spyhunter99** [comment]
I found an ASF compatible library and at least reads the important fields of shape files. I was able to get it imported and was able to convert a low res country border shape file.  This produced 250+ polygons, many with holes. There was a few rendering artifacts that @monsieurtanuki may be interested in, looks like it's isolated to polygons + date line rendering at a low zoom level.

Panning performance was also...poor to say the least. In genymotion it's rendering at about 1 fps. It's slightly better on real hardware but it's still rather poor.

related tickets 
#857 #820 #770 #890

I think this highlights that we could do a better job of optimizing what needs to be rendered and what doesn't and to run point reduction based on what's on screen + the zoom level.

**Comment by spyhunter99** [comment]
https://www.youtube.com/watch?v=Ly7tZ_8LG1s

**Comment by spyhunter99** [comment]
Sample file set is here: http://thematicmapping.org/downloads/TM_WORLD_BORDERS_SIMPL-0.3.zip

**Comment by spyhunter99** [comment]
![image](https://user-images.githubusercontent.com/1975321/35485642-a6063f5a-0430-11e8-9e28-94321995701d.png)
![image](https://user-images.githubusercontent.com/1975321/35485650-b9946e02-0430-11e8-9ef7-8f580f576d95.png)
![image](https://user-images.githubusercontent.com/1975321/35485653-cb777bdc-0430-11e8-9243-2526d0b56eaa.png)
![image](https://user-images.githubusercontent.com/1975321/35485664-dbc72a50-0430-11e8-9abd-66b810a721f0.png)

after profiling, it looks like most of the time is spent in SegmentIntersection.divisionByZeroSideEffect

**Comment by spyhunter99** [comment]
I also found a dbase reader so that we can attach the meta data with each shape. 

![image](https://user-images.githubusercontent.com/1975321/35486970-fb5e4fb6-0443-11e8-9a72-a292d253bdf8.png)

**Comment by spyhunter99** [comment]
this issue depends on #910

**Comment by monsieurtanuki** [comment]
> This produced 250+ polygons, many with holes. There was a few rendering artifacts that @monsieurtanuki may be interested in, looks like it's isolated to polygons + date line rendering at a low zoom level.

From the video the only strange thing I saw was with Antartica, which is by construction a side effect in osmdroid's Mercator projection: what kind of `Polygon` is that supposed to be? It even goes beyond our minimum latitude!

> Panning performance was also...poor to say the least. In genymotion it's rendering at about 1 fps. It's slightly better on real hardware but it's still rather poor.

Regardless of the Douglas-Peucker algorithm or the possible improvements of `Path` construction, rendering many `Path`s is slow. Remember the heat map: very stupid square `Path`s, but numerous, therefore slow panning.

> after profiling, it looks like most of the time is spent in SegmentIntersection.divisionByZeroSideEffect

I had a look at the code. The best I could do so far was to optimize `Math.min` (!). Another step would be to split `SegmentIntersection.check` in two, in order to avoid some computing for Y's if we already know that X's don't fit. But doing so we just avoid multiplications.
Or just rethink the whole thing...

**Comment by spyhunter99** [comment]
@monsieurtanuki are you aware of any kind of padding or anything to that effect when calling `mapView.getBoundingBox`? It almost looks like there is an 18dp padding that is subtracked from the actual bounding box of the view

**Comment by spyhunter99** [comment]
never mind, i've spent hours trying to debug some boundbox issues, turns out it was my code that cause the issue

**Comment by spyhunter99** [comment]
@monsieurtanuki do we have a method to determine if there are multiple worlds currently in the view?

**Comment by monsieurtanuki** [comment]
It's rather @Maradox that worked on that multiple world feature and I don't know if he implemented something specific about that need, but depending on what you mean exactly I would check `MapView.isHorizontalMapRepetitionEnabled`, `MapView.isVerticalMapRepetitionEnabled`, `MapView.getWidth`, `MapView.getHeight` and `TileSystem.MapSize`.

**Comment by spyhunter99** [comment]
thanks

**Comment by Maradox** [comment]
@spyhunter99 When I implemented the no-repetition feature I didn't implement a method that determines if there are multiple worlds visible (since it wasn't necessary).

**Comment by spyhunter99** [comment]
no problem. I was trying to find an elegant solution to determining if the map view's boundbox was abnormal, meaning multiple worlds present. This branch adds bounding box checks on lines and polygons to reduce draw time. Calculating if the bounds of the overlay overlap the bounds of the map view turned out to be difficult when multiple worlds are present. As a work around, I just checked if the zoom was less than 3

**Comment by pasniak** [comment]
Why dbase and not sqlite?

**Comment by spyhunter99** [comment]
That's the esri spec. Normally it's a zip file with 5 or 6 files in it.

**Comment by pasniak** [comment]
there's a typo mMinmiumZoom

**Comment by pasniak** [comment]
Polyline.addPoint() seems gone. Maybe add a depreciation notice?

**Comment by spyhunter99** [comment]
ill look into it, i dont remember deleting it, probably a merge issue

**Comment by spyhunter99** [comment]
fixed
