### ISSUE TITLE
Port build from maven to gradle2.2 with support for AndroidStudio

### ISSUE THREAD

**Issue by k3b** [osmdroid/osmdroid#91]
Goals

* Being able to build osmdroid (with its subprojects and with the demo app OpenStreetMapViewer) using gradle2.2ff and/or Androidstudio1.0ff.
* Being able to create osm-based android apps that do not depend on non-free components to support fdroid (see [ osmdroid issue #71:Non-free libraries in dependencies](https://github.com/osmdroid/osmdroid/issues/71) )
* Being able to easy create osm-based android apps where only gradle references to osmdroid and other libs are needed

Currently building osmdroid (with its subprojects) is mainly based on maven-pom-files.

I have startet doing this in [my AndroidStudio-Branch](https://github.com/k3b/osmdroid/tree/AndroidStudio). For details see [current status](https://github.com/k3b/osmdroid/blob/AndroidStudio/README.GRADLE.md)

**Comment by ziem** [comment]
:+1:

**Comment by k3b** [comment]
Hello osmdroid core developper community

##status summary

* AndroidStudio1+/gradle2.2+ project
    * works with sub-moduls `OpenStreetMapViewer`, `osmdroid-android` and `osmdroid-third-party`
    * does not work with sub-moduls `osmdroid-android-it` and `OSMMapTilePackager`
    * **Risks**
        * when using AndroidStuio with
            * making changes to supported modules may break sourcecode/functionality of non supportet modules
            * making changes to submodules/filenames may break maven build scripts

Should we integrate these changes into main osmdroid repository now and are we willing to accept the risks i mentioned?

What do you think?

Links to subproject and current status see first comment

**Comment by gaurav-fueled** [comment]
+1

**Comment by k3b** [comment]
I donot know how to gradle build "osmdroid-android-it" and "OSMMapTilePackager".

therefore i havent checked in my changes

**Comment by spyhunter99** [comment]
My two cents, avoid gradle. Maven has reasonable android support now.

**Comment by gaurav-fueled** [comment]
Android officially supports android studio with gradle. So if we can port this library to gradle then we wont have a **reasonable** support

**Comment by spyhunter99** [comment]
ok so most of the project now builds with both maven and gradle. only thing left is the tile packager.

**Comment by spyhunter99** [comment]
GoogleWrapperApp still needs conversion
