### ISSUE TITLE
Add Douglas Peucker point reducer

### ISSUE THREAD

**Issue by spyhunter99** [osmdroid/osmdroid#910]
## Issue Type

See #865 migrating class from osmbonuspack to osmdroid. Thanks @MKergall 

[x ]Enhancement

## Description and/or steps/code to reproduce the problem

See #865

**Comment by spyhunter99** [comment]
@monsieurtanuki think we can wire this into the polygon and polyline rendering routines? Looks like that renders using pixel coordinates, so maybe we can write a comparable version for integer based stuff

**Comment by monsieurtanuki** [comment]
@spyhunter99 Oops, looks like I've lost the thread, plus my mind is still in the "slight pause" issue. Could you please be more explicit in your question? Hopefully we could reuse code.

**Comment by spyhunter99** [comment]
basically, at numerically low zoom levels, we can run the point reducer on lines and polygons (with an appropriate tolerance setting). This should have the net effect of reducing drawing time significantly

**Comment by monsieurtanuki** [comment]
From what I saw in the Douglas-Peucker algorithm, we reduce the number of `GeoPoint`s.
We could store both versions of the `List<GeoPoint>`: the complete and the reduced ones.
Then, depending on the current zoom level, we can apply the current `Polyline` / `Polygon` "hardware acceleration" routines to the more relevant list, precision-wise.
I'm not sure if that was your initial question, but as the hardware acceleration algorithm takes `List<GeoPoint>` as an input, we can of course run it on a reduced list of `GeoPoint`.
