### ISSUE TITLE
[VOTE] osmdroid v6.0.0 release

### ISSUE THREAD

**Issue by spyhunter99** [osmdroid/osmdroid#914]
osmdroid has had a ton of new committers and contributors lately, Thank you all so much for your hard work! I feel that we are near ready for a release. It's been a long time since 5.6.5 and we are well past due. That said, osmdroid has never really had an governance processes (that I know of), I figured we should start probably start with v6.0.0's release. It stands now at 88 closed issues for this release. 

If you're new to open source governance, it's worth the time to read some of ASF's guidelines for releases, specifically [decision making](https://www.apache.org/foundation/how-it-works.html#decision-making). Normally projects require a majority of the committers to have a +1 vote with no -1 votes.
This is used for lots of purposes in ASF but most commonly it is used for voting on a release. In the past, most of the conversation regarding cutting a new osmdroid release has been through email but there's probably a better way. We currently stand at about 10 individuals with commit privileges. Opening this up to the community makes sense as people do fun and creative things with maps and we don't always have test cases for everything (nor do we really know how it is used).

The best we have for group communication right now is google groups, which hardly anyone uses, so the next best option is to just use a github issue. Since v6.0.0 has **[significant changes](https://github.com/osmdroid/osmdroid/issues?q=is%3Aclosed+milestone%3Av6.0.0)**, I'd like to open this one up for the broader community to test and/or provide feedback before we cut the final artifacts. As of this writing, osmdroid has 129 people watching this project and over 1200 stars. That's a 129 people that will get an email regarding this vote. If you don't make your voice heard than there's not much we can do about it.

That said, it would be nice if most recent committers vote an opinion and/or test results. Snapshots are up to date on central. According to github, here's some of the recent contributors

@Maradox  @monsieurtanuki  @MKergall  @secaw  @pasniak  @cbalster  @miguel-porto  @shiroyagi 
 @neilboyd  @k3b  @kurtzmarc @jmarks213 

So, when you have time, please comment below with a +1, 0, or -1 with explanation of what the issue is. Since everyone is probably super busy and working on open source is probably not a high priority for many, we'll keep the vote open for 2 weeks, ending on February 16, 2018 00:00 hrs UTC.

There is currently 1 pull request open which may resolve a bug with loading map tiles related to in memory caches. It's a rather large change set and although it may solve some issues, I have some minor concerns that there is a possibility that it may introduce unforeseen issues. 

That's said, I'll happily give this a +1 from me.

**Comment by shiroyagi** [comment]
+1 lots of good work, works well for me

**Comment by secaw** [comment]
+1 All seems to work well, I already have latest snapshots in production. An incredible amount of improvements and new features have been introduced! Special thanks to @spyhunter99 for your work and presence. Cheers.

**Comment by cbalster** [comment]
All for it! +1

**Comment by MKergall** [comment]
+1 !

and 100% in line with @secaw comment.

**Comment by monsieurtanuki** [comment]
+1 (with a little hope that #776 is fixed - possibly by @secaw and #915)

**Comment by jmarks213** [comment]
+1 In a few sparse tests 6.0 worked great for me.

**Comment by k3b** [comment]
+-0 I am currently busy with other job. My app works stable with the old 5.x version

**Comment by miguel-porto** [comment]
Yep, +1 as there have been great improvements in the cache management (we can finally go offline for days without the panic of losing our tiles!) and in the UX in general (very smooth zoom and pan), but I think #908 should be incorporated, cause it really seems to fix the hang-on-detach bug, which is a very inconvenient bug!
BTW thank you for including me in the vote!

**Comment by Maradox** [comment]
+1 I tested 6.0.0 via the OpenStreetMapViewer as well as via my own application and I didn't find any bigger problems, besides the following issues (which are minor):
* https://github.com/osmdroid/osmdroid/issues/929 
* https://github.com/osmdroid/osmdroid/issues/928 - Maybe not that important for 6.0.0
* https://github.com/osmdroid/osmdroid/issues/933 - PR pending
* https://github.com/osmdroid/osmdroid/issues/926 - PR merged

**Comment by pasniak** [comment]
+1 I was using the map on and offline for a week or so, and haven't observed tiling hangs.

**Comment by spyhunter99** [comment]
thanks for the feedback everyone. I'll work as soon as I can to get the result cut. As always, please continue to report issues

**Comment by spyhunter99** [comment]
done
