### ISSUE TITLE
Polyline.enablePointReduction(true) removes all points

### ISSUE THREAD

**Issue by shiroyagi** [osmdroid/osmdroid#916]
## Issue Type

[* ] Bug

## Description and/or steps/code to reproduce the problem

By default all my Polylines are invisible unless I set this to false.

I'm building osmdroid from source, I can't get gradle to download:
`compile 'org.osmdroid:osmdroid-android:6.0.0-SNAPSHOT'`

## Environment

Hardware accn on

### If it's a bug, version(s) of android this affects:

5.1

### Version of osmdroid the issue relates to:

6.0.0

3b909549 (ok in 67cf8fa2)

**Comment by spyhunter99** [comment]
well that's not good.

**Comment by spyhunter99** [comment]
do you have a set of input values that i can test with? and maybe the dpi for the device that this happened on?

**Comment by shiroyagi** [comment]
Any points seem to be removed eg 2 at 1km separation.  XT1052 with 312ppi.

**Comment by spyhunter99** [comment]
so you have a line with 2 points and ran through the reducer it became two points?

**Comment by spyhunter99** [comment]
can you get some points and the zoom level?

**Comment by shiroyagi** [comment]
Any number of points and span at any zoom level.  I am not able to make any line visible unless I turn it off.

**Comment by shiroyagi** [comment]
With some debugging I have this in Polyline.draw():
densityDpi=320 latSpan=0.0559770206137955 tol=1.7492818941811095E-4

**Comment by shiroyagi** [comment]
Ok, I see the problem: originalPoints is empty because I am using addPoint() rather than setPoints().

**Comment by shiroyagi** [comment]
As an aside, I'm storing my points in a couple of double[] with the idea of avoiding object instantiation costs.  It would be interesting to compare the efficiency of this with ArrayList<GeoPoint> in LinearRing, is the difference negligible?

**Comment by spyhunter99** [comment]
ahh i missed add point

**Comment by spyhunter99** [comment]
alright holy hell. i'm rolling back the point reduction integration on master for polyline and polygon, then updating the snapshot. it can wait for the next release

**Comment by shiroyagi** [comment]
Where should I find the snapshot these don't seem to exist:
```
https://repo1.maven.org/maven2/org/osmdroid/osmdroid-android/6.0.0-SNAPSHOT
http://jcenter.bintray.com/org/osmdroid/osmdroid-android/6.0.0-SNAPSHOT
```

**Comment by spyhunter99** [comment]
stand by

**Comment by spyhunter99** [comment]
https://github.com/osmdroid/osmdroid/blob/master/README.md#want-the-latest-and-greatest

**Comment by spyhunter99** [comment]
snapshot updated

**Comment by shiroyagi** [comment]
sorry, I should have seen that...

**Comment by spyhunter99** [comment]
it's relatively new, don't worry about it. I'm glad this was discovered before cutting the version
