### ISSUE TITLE
Current location is not displayed

### ISSUE THREAD

**Issue by tacmanvsa** [osmdroid/osmdroid#917]
## Issue Type

[ ] Question
[ ] Bug

## Description and/or steps/code to reproduce the problem

I had issues in my own project to display the users current location even after asking for permissions and allowing them. So I started to search for a possible solution in osmdroid repo.
The [wiki](https://github.com/osmdroid/osmdroid/wiki/How-to-use-the-osmdroid-library#how-to-add-the-my-location-overlay) says that it is enough to add those 3 lines + the correct permissions. But when I navigate to the activity **osmdroid/OpenStreetMapViewer/src/main/java/org/osmdroid/StarterMapActivity.java** (clicking on _OSMDroid Sample map (Start here)_ in the application after intro) my current location is not displayed, however in [StarterMapFragment.java](https://github.com/osmdroid/osmdroid/blob/master/OpenStreetMapViewer/src/main/java/org/osmdroid/StarterMapFragment.java#L170) the location overlay is added as stated in the documentation. I allowed the permissions in the intro too. What am I missing?
I'm testing on a Huawei device, API level 24.

### If it's a bug, version(s) of android this affects:

API 24

### Version of osmdroid the issue relates to:

5.6.5

**Comment by tacmanvsa** [comment]
Yeah I agree that it is easy to miss. However thats not my case right now. I agreed to the permissions (when I navigate back to the intro from the demo app, the permission button is not displayed anymore) on the first run but my location is still not displated.

**Comment by spyhunter99** [comment]
https://play.google.com/store/apps/details?id=org.osmdroid
can you confirm that the sample app works for you?

**Comment by spyhunter99** [comment]
looking at it now...

**Comment by tacmanvsa** [comment]
The sample app from play store works as the cloned app, so my location is not displayeed. 
I went through the intro couple of times and I allow all permissions. If I check the locations permissions from my settings then It says, that it is allowed for the osmdroid app, however the location is still missing. See the attached screenshots.
![first](https://user-images.githubusercontent.com/10064488/35796755-d1fd0ae8-0a5d-11e8-83d3-40142a7804b9.png)
![fourth](https://user-images.githubusercontent.com/10064488/35796756-d218bf7c-0a5d-11e8-805f-a03c8838681e.png)
![second](https://user-images.githubusercontent.com/10064488/35796757-d23360fc-0a5d-11e8-88f1-1e5131a41718.png)
![third](https://user-images.githubusercontent.com/10064488/35796758-d24f1c3e-0a5d-11e8-9019-08a78e49531f.png)

**Comment by spyhunter99** [comment]
Try `mapView.invalidate()` or just panning the map a bit? I'm not entirely sure what's going on. You might want to step through the code, specifically this class
https://github.com/osmdroid/osmdroid/blob/master/osmdroid-android/src/main/java/org/osmdroid/views/overlay/mylocation/MyLocationNewOverlay.java

**Comment by tacmanvsa** [comment]
OK, thank you for your response. I can not try It right now, but I will do it as soon as possible and I will add some feedback here. Thanks.

**Comment by tacmanvsa** [comment]
Ok, so It is finally working, but I don't know why...
I've tried literally everything, the things you linked, every possible solution from stackoverflow etc. So I searched for some solutions in the demo app. The sample of the fragment **SampleCustomIconDirectedLocationOverlay** showed the location on my phone, so I tried to copy&paste the code and use it in my own project. Now my location is displayed, but only WHEN these lines are added in the onResume method, as in the demo app:
```
LocationManager lm = (LocationManager) getActivity().getSystemService(Context.LOCATION_SERVICE);
try {
   //on API15 AVDs,network provider fails. no idea why
   lm.requestLocationUpdates(LocationManager.GPS_PROVIDER, 0, 0, (LocationListener) this);
   lm.requestLocationUpdates(LocationManager.NETWORK_PROVIDER, 0, 0, (LocationListener) this);
}
catch (Exception ex){}
```
Can you explain me, what this is doing exactly? If I delete these lines my location is not displayed, if they are there it is OK.

**Comment by spyhunter99** [comment]
It could be a device specific thing. Android is weird to say the least and frequently has inconsistent behavior with stuff. I've seen devices throw a runtime exception when asking for gps updates, others just don't do anything. I'm not sure about your issue. There are some APIs with location manager than you can use to discovery what location sources are available on your device. It might be worth making a quick hello world app that probes for those things and then attempts to get updates. Maybe i'll                                            add something to the sample app one day

**Comment by spyhunter99** [comment]
did you call `overlay.enableMyLocation()`? like this https://github.com/osmdroid/osmdroid/blob/master/OpenStreetMapViewer/src/main/java/org/osmdroid/StarterMapFragment.java#L193

**Comment by tacmanvsa** [comment]
Yes of course.
I really don’t know what the problem is. The only examples which are showing my current location are using DirectedLocationOverlay. Maybe it is rly something special with my device.

**Comment by spyhunter99** [comment]
From device to device, the variations can be huge. Here's a few samples

- samsung devices measure screen sizes differently than non-samsung devices
- some devices without gps can throw when access it but most do not
- versions of android handle class loading differently than others
- some android devices can report partitions/mount points as writable but are read only
- huge variations in opengl support and any kind of graphics acceleration

so my recommendation for your setup is to add the network service as a provider and be done with it. I'll added some try/catches in mylocationnewoverlay to prevent possible crashes too.

**Comment by spyhunter99** [comment]
i'll add the network provider too, wth

**Comment by spyhunter99** [comment]
@tacmanvsa i did add to our sample app a simple diagnostics tool to print out what location providers are available, you might want to play around with it your device to debug it

**Comment by tacmanvsa** [comment]
Thank you very much, I'm currently on a holiday but I will look at it as soon as possible and I post a feedback here.
Thanks.

**Comment by tacmanvsa** [comment]
OK, I pulled the updated version and it works. So it was caused probably by not requesting for `LocationManager.NETWORK_PROVIDER`. However is there any reason for that? After studying the android docs I couldn't find nothing.

Thanks for the fix!

**Comment by spyhunter99** [comment]
No idea, GPS may not be enabled on the device or perhaps it's only google's location services

**Comment by tacmanvsa** [comment]
And will be the fix [commit](https://github.com/osmdroid/osmdroid/commit/ce1abebd9591cff5cbc91705f837e83bd513cd86) part of the new release?

**Comment by spyhunter99** [comment]
yes, cutting it now actually

**Comment by tacmanvsa** [comment]
could you tell me when the new release will be published cca?

**Comment by spyhunter99** [comment]
i just hit the button, should be rolled out globally within a few hours
