### ISSUE TITLE
Using osmdroid for offline (tilesource .osm.pbf)

### ISSUE THREAD

**Issue by a7med-95** [osmdroid/osmdroid#918]
## Issue Type
[x] Question

I am developing an application that will use OSM offline. I downloaded a map source (.osm.pbf) from [link](http://download.geofabrik.de/). I wonder of how to use it further. I already added osmdroid by gradle. 

For some reason i feel like there is a gap in the offline description, or maybe it's just me how didn't understand it, for example using OSMMapTilePackager .

## Environment
Android Studio

### If it's a bug, version(s) of android this affects:
All

### Version of osmdroid the issue relates to:
5.6.5

**Comment by spyhunter99** [comment]
Add you probably figured out, it's not supported and is unlikely to be supported in the near future
