### ISSUE TITLE
Thread-safe, functionally relevant and async map tile memory cache

### ISSUE THREAD

**Issue by monsieurtanuki** [osmdroid/osmdroid#919]
## Issue Type

[v] Improvement
[v] Performance

## Description and/or steps/code to reproduce the problem

As experienced in bugs #776 and #812, the map tile cache management could be improved:
* bullet-proof thread-safe access - in order to avoid #776
* async garbage collecting - in order to avoid #812, slow Activity detach or ANR
* fine grained functional relevancy of the tiles stored in the cache and possible deprecation of LRU - depending on each app's expressed needs

All the new stuff must be explicitly unit tested as it's a core feature.

### Version of osmdroid the issue relates to:

6.0.0

**Comment by monsieurtanuki** [comment]
Following points were fixed by #908:
* bullet-proof thread-safe access - in order to avoid #776
* async garbage collecting - in order to avoid #812, slow Activity detach or ANR

Now the focus is on fine grained functional relevancy of the tiles stored in the cache.

**Comment by pasniak** [comment]
I am on the master as of 2/25 and I observe the below code going into an infinite loop, when I switch between the tile sources:
```
    public void clear() {
        while(!this.isEmpty()) {
            try {
                this.remove(this.keySet().iterator().next());
            } catch (NoSuchElementException var2) {
                ;
            }
        }

        super.clear();
    }
```

![screenshot from 2018-02-25 21-05-32](https://user-images.githubusercontent.com/19778666/36650127-ab816072-1a6f-11e8-97e9-4c4d7423f7bb.png)

**Comment by monsieurtanuki** [comment]
@pasniak In which class do you see this code, which is an old version? Obviously there's confusion: what I see in `MapTileCache` is
````java
public void clear() {
	// remove them all individually so that they get recycled
	final MapTileList list = new MapTileList(mCachedTiles.size());
	populateSyncCachedTiles(list);
	for (int i = 0; i < list.getSize() ; i ++) {
		final long index = list.get(i);
		remove(index);
	}

	// and then clear
	mCachedTiles.clear();
}
````

**Comment by pasniak** [comment]
My code was for decompiled LRUMapTileCache.

**Comment by monsieurtanuki** [comment]
@pasniak `LRUMapTileCache` is now deprecated and not used anymore. Its code is more or less embedded in `MapTileCache` now.

**Comment by monsieurtanuki** [comment]
@pasniak I'm definitely not an expert in git and I don't know what's in `master`, but the code I mentioned is part of the current Code version of [MapTileCache](https://github.com/osmdroid/osmdroid/blob/master/osmdroid-android/src/main/java/org/osmdroid/tileprovider/MapTileCache.java)

**Comment by pasniak** [comment]
Thanks, this was another case of AS 3.0 not updating my projects's dependencies... Argh! I built osmdroid with:
```
./gradlew clean publishToMavenLocal
```
Yet my projects linked with stale osmdroid...  I had to manually delete /home/pasniak/.android/build-cache

**Comment by monsieurtanuki** [comment]
Solve by #956
