### ISSUE TITLE
OverlayItems don't keep their size during zoom

### ISSUE THREAD

**Issue by ziem** [osmdroid/osmdroid#92]
I recorded video showing this issue:
https://www.dropbox.com/s/87w0anrxksb9c0k/device-2015-01-08-114918.mp4?dl=0

[Here](https://gist.github.com/ziem/c8b9d90e0d0ec5db3a7f) you can find modified ItemizedOverlay class (based on MyLocationNewOverlay) which seems to solve this problem. I also recorded video with updated version: https://www.dropbox.com/s/xrt4i8h51fuq3cl/device-2015-01-08-115050.mp4?dl=0

@kurtzmarc @neilboyd - where should this be implemented? In [Overlay.drawAt()](https://github.com/osmdroid/osmdroid/blob/master/osmdroid-android/src/main/java/org/osmdroid/views/overlay/Overlay.java#L261)?

**Comment by spyhunter99** [comment]
i really like this, but i'm concerned at what the overhead would be with many icons on screen.like 100s. I'd love to see a before and after with a significant amount of icons, polylines and polygons

**Comment by spyhunter99** [comment]
I've added tests with tons of icons and haven't seen any real performance delta. I'm fine with merging this unless anyone else had an issue with it. I'll keep this open until for another week or so, then merge and close

**Comment by spyhunter99** [comment]
merged
