### ISSUE TITLE
Deprecation inconsistencies

### ISSUE THREAD

**Issue by Maradox** [osmdroid/osmdroid#928]
I found some deprecated methods which should either be removed or not be deprecated.

1. `Projection.toPixelsFromProjected` is deprecated, though I think it correct and the `deprecated` should be removed
2. `Projection.adjustOffsets ` is deprecated, though it is marked as `@since 6.0.0`
3. `TileSystem.LatLongToPixelXYMapSize` is deprecated, though it is marked as `@since 6.0.0`
4. `TileSystem.PixelXYToLatLong ` is deprecated, though it is marked as `@since 6.0.0`
5. `TileSystem.PixelXYToLatLongMapSize ` is deprecated, though it is marked as `@since 6.0.0`
6. `TileSystem.PixelXYToTileXY ` is deprecated, though it is marked as `@since 6.0.0`
7. `TileSystem.TileXYToPixelXY ` is deprecated, though it is marked as `@since 6.0.0`

### Version of osmdroid the issue relates to:

6.0.0-Snapshot

**Comment by spyhunter99** [comment]
looks like these are cleaned up, closing
