### ISSUE TITLE
Async tile pre-caching

### ISSUE THREAD

**Issue by monsieurtanuki** [osmdroid/osmdroid#930]
## Issue Type

- [x] Improvement
- [x] Performance

## Description and/or steps/code to reproduce the problem

Now that the zoom pinch gesture is smoother (no `View.scale` anymore but floating point zoom only), there are some side effects when zooming across integer zoom boundaries:
* @spyhunter99 mentioned "on mapnik a momentary full screen flicker" (#908)
* @miguel-porto mentioned a "slight pause" (#812)

That makes sense, because when we cross the integer zoom boundaries, we need to get at the same time (in the same `TilesOverlay` display loop, playing in the UI thread) a dozen of new tiles, that we need to extract either from the memory, from the database or from the network.

The screen flickering @spyhunter99 experienced is probably the case when all tiles belonging to the new zoom are in the database but not in the memory yet: before we put them from database to memory, we have nothing to display and therefore we display empty gray tiles.
Async'ly pre-caching tiles from database to memory would solve this issue, assuming the speed of access to memory is not the issue there.

The slight pause @miguel-porto experienced would probably be fixed if we implement the async pre-caching. In his case there seems to be an additional issue regarding access to memory, possibly because the tiles he uses are heavier, memory-wise, but the slight pause doesn't seem to appear when the tiles are already in memory, therefore it should be OK too.

What would be the scope of the pre-cache? In the version of `MapTileCache` implemented in #908, we cache the tiles currently displayed PLUS the equivalent tiles of zooms +-1. I guess we could use the same tile spans.

Then there's the question of how aggressive we are in pre-caching: should we only rely on stored data or get data from the network?

### Version of osmdroid the issue relates to:

6.0.0

**Comment by miguel-porto** [comment]
> What would be the scope of the pre-cache?
This is a fundamental question. I'll also try to think about some proposal on this. I think the +-1 zooms should be combined with some kind of LRU (not strictly LRU, but something to think).
In an ideal scenario, one could have an option to choose the best approach for each use case (plain LRU, +-1 zoom cache or other possibility, like the frequency-based LRU).

**Comment by monsieurtanuki** [comment]
@miguel-porto Fair enough. And this flexibility also applies to the memory cache tile list.

I guess we need a new `interface` (`MapTileListDestination`?) with a `MapTileList computeListFromSource(MapTileList source)` method where the list of tiles will be computed from the currently displayed tiles (as a source list).
Classes would implement it as "zoom+-x" (for "zoom+1", "zoom-1") or "border+-x".
Other classes would implement it without caring at all about the source: "lru", "fixed-tile-list".

And an array class would gather all the results, according to the users need: "I want systematically Portugal tiles from zoom 4 to zoom 7, the 2-tile-wide border around the displayed tiles, zoom+1 up to zoom level 15 and zoom-2 up to zoom level 4".

**Comment by monsieurtanuki** [comment]
@miguel-porto I'm so cunning: I knew I could persuade you by mentioning a map of Portugal ;)

**Comment by monsieurtanuki** [comment]
About when to pre-cache, the zoom pinch gesture seems appropriate - at least as an option.

**Comment by monsieurtanuki** [comment]
Fortunately I now fully experience the not-that-slight pause on my own app with the latest osmdroid release.
That gives me pause examples and energy to solve this issue.

**Comment by monsieurtanuki** [comment]
Coded in #975, and merged.
