### ISSUE TITLE
Polygon: Clip path to screen-rect

### ISSUE THREAD

**Issue by Maradox** [osmdroid/osmdroid#933]
In order to improve the performance of the polygon, the path of the polygon should be clipped to the screen rect. Thus, only the visible path segments are drawn. 

### Version of osmdroid the issue relates to:

6.0.0

**Comment by pasniak** [comment]
Yesterday I drew ~5000 small Polylines using Polygon.pointsAsCircle() and I get quite a pref hit even if only one  of circles was  on the screen... 

6.0.2-SNAPSHOT

**Comment by pasniak** [comment]
If:
> The fix was to clip the Path into a relatively small square before displaying it: with this fix we could display Polygons with hardware acceleration on

How do I do that?  By overriding `draw`? Is there a code sample?

**Comment by monsieurtanuki** [comment]
@pasniak Here it's @Maradox 's issue, and he PR'ed in #934.
When you say "_The fix was to clip the Path..._" the quote is mine, therefore we're talking about different issues, as there are many about performances with `Polygon`s:
* #934 is an open PR (issue is #933)
* #937 is an open PR (issues are #906 and #890)
* #857 is an open issue
* #820 is an open issue

What I can say now is that:
* "_The fix was to clip the Path..._" is currently implemented in `LinearRing` and `SegmentClipper` for `Polygon`s
* from what I read here and there, the `Path` are notoriously slow with HW acceleration on, cf. the simple and though sluggish "HeatMap" demo
* maybe you'll find good performances with the currently open PRs

**Comment by monsieurtanuki** [comment]
cf. #934
