### ISSUE TITLE
Can't access database in /sdcard/storage on Android 5.0.2

### ISSUE THREAD

**Issue by kofee-cup** [osmdroid/osmdroid#935]
Hello everyone ! I'm fairly new to Android and OSM. 

## Issue Type
[X] Bug

## Description and/or steps/code to reproduce the problem

When launching a custom app on the Android 5.0.2 emulator, Logcat shows errors of the SQLwriter saying it can't access database in specific location (here, default). 

### If it's a bug, version(s) of android this affects:
5.0.2 so far, maybe less. 

### Version of osmdroid the issue relates to:
5.6.5

--

I've got this issue, but it seems to be quite weird. 
I've test my app (which is basically a main activity with a button checking your current position and a map view that display this position) on 3 differents AVD : 
 - 6.0 - API 23 --> Android is showing me popup to allow the app to write on the storage. The map is showing perfectly. 
 - 5.1 - API 22 --> Nothing is shown to ask for permissions. But the maps is loading fine. 
 - 5.0.2 - API 21 (the minimal one needed) --> Nothing is shown. The map doesn't load. I've check the app rights on the settings and it can access external storage. 

Since I can't modify the path using `OpenStreetMapTileProviderConstants.setCachePath(new File("/sdcard/osmdroid2/").getAbsolutePath());` since it's not available on the 5.6.5. 

I admit I'm a little bit overhelmed by this, I don't understand why it works on newer version and why it can't access a path even with the right authorizations... 

Thank you very much,
Julien

**Comment by cfsbhawkins** [comment]
I think you are seeing the nice issue android created then fixed to work better when they locked down external storage devices. If I remember it was 5.1 loosened some of the issues, and 6.0 introduced the runtime permission requirements. What you are looking for is the storage access framework from google, this requires users to grant permissions to directories on external storage devices. (You still have access to internal storage with app permissions)

**Comment by kofee-cup** [comment]
Thanks for the answer. 
The thing is, I can't modify the path OSMdroid uses to store the tiles database. And, from what I saw in Logcat, the location /storage/sdcard/osmdroid isn't writable. And, if I understand the marvelous Android file system, sdcard is also the "internal"(device's storage) that is called "external". 
So what, I can't use any other API to change the path. 

Do I need to downgrade the OSMdroid API ?

**Comment by spyhunter99** [comment]
most likely the problem is that the partitions available to the application is being marked as writable but it is actually not writable. There's all kinds of strange storage permissions issues on various versions of android. 

Recommendation, on the broken device, try calling StorageUtils.getStorageList() to see what's available, then call isWritable to find a writable location. Configuration.getInstance().getOsmdroidBasePath and getOsmdroidTileCache will tell you where osmdroid is currently pointing at.

**Comment by kofee-cup** [comment]
Thank you! 
I will test what you wrote Monday. I have to test the app on a real device too, maybe it's just the emulator that is broken. 

Still, I have another question : since the `setCachePath`method is commented inside the 5.6.5 API, what method can I use to force OSMdroid to write to another path?

**Comment by kofee-cup** [comment]
Okay, because I'm a genius, I didn't read the Javadoc.
I can change the path by using, if I understood well : `Configuration.getInstance().setBasePath()` and its tiles equivalent.

I will test this on Monday and give you a feedback.
Thank you again.

**Comment by djnotes** [comment]
So, did it work? I have the same problem. And as the logs say, everything is writable. So, quite puzzled over here. No explicit red errors. The app just keeps closing as soon as launched.

**Comment by spyhunter99** [comment]
setBasePath only comes into effect after the map is loaded so if it's an activity, put it before setContetView

**Comment by kofee-cup** [comment]
I can't test it since the project is on my professional laptop at work and I'm not working until Monday. I still can reproduce the issue at home, see if it's a solution.

@spyhunter99 : thanks for the tips. I will use both method to set every writable contents into a writable directory.

**Comment by spyhunter99** [comment]
you can always use application private storage, usually /data/data/packagename/cache.db

**Comment by kofee-cup** [comment]
Okay, so I tried what @spyhunter99 said. 
Apparently, it shows the same error. Even if I'm changing the tiles cache's path to /data/data or even, and that's really strange, by creating a new folder. 
I used : 

`if (Build.VERSION.SDK_INT < Build.VERSION_CODES.LOLLIPOP_MR1){
            File cache_tile_directory = new File(Environment.getExternalStorageDirectory()+File.separator+"OSMdroidPOC");
            cache_tile_directory.mkdirs();
            Configuration.getInstance().setOsmdroidTileCache(cache_tile_directory);
        }`

It creates the directory for sure and it changes the path, but the TilesWriterSQL can't write to it. 
I'm still searching !

**Comment by kofee-cup** [comment]
Okay, so, after many hours... I managed to get this thing working ! 
Here's globally what I did, in addition to recreating a new device with AVD manager : 
```java
if (Build.VERSION.SDK_INT < Build.VERSION_CODES.LOLLIPOP_MR1){
            boolean success = false;
            File cache_tile_directory = new File(getFilesDir().toString()
                    +File.separator+"cache");
            Log.i("CreateDir",cache_tile_directory.toString());
            if(!cache_tile_directory.exists()){
                success = cache_tile_directory.mkdirs();
            }
            if(success){
                Log.i("CreateDir","Directory created!");
                Configuration.getInstance().setOsmdroidTileCache(cache_tile_directory);
            }else{
                Log.w("CreateDir","Unable to create dir!");
            }
}```

Before `java setContentView` of course. 
Thank you !

**Comment by kofee-cup** [comment]
Closing issue since it's been corrected.
