### ISSUE TITLE
Zoom double in 6.0.0/1

### ISSUE THREAD

**Issue by mlendl** [osmdroid/osmdroid#944]
Really not clear why zoom is double in the newest version??? Anyways, everyone should know it. It can cause wrong behaviour (w/o compile error)!!!

**Comment by spyhunter99** [comment]
Can you elaborate on the wrong behavior?

**Comment by spyhunter99** [comment]
https://github.com/osmdroid/osmdroid/wiki/Upgrade-Guide

**Comment by jmarks213** [comment]
I have an issue related to the double zoom, maybe this is what @mlendl means?

I have gotten feedback that the map displayed is "fuzzier" on 6.0 than the previous version.  The pinch zoom controls previously were snapping the map to the different zoom levels but now they can exist between them.

I have an offline tile source that has low res tiles and, for example, if I zoom in using the button controls from say…8 to 9 everything looks as expected.  If I then use the touch controls to expand and zoom out just small amount I will see the zoom level 8 tile but it will be scaled and pixelated.  

Here are a few screencaps.  They are not zoom level 8 and 9 but that idea is the same.

Using the zoom control in button I land on this zoom level:
![image](https://user-images.githubusercontent.com/15203304/36567129-8ac48338-17f3-11e8-85f7-6428ab70d453.png)

This is the next zoom level in using the zoom control button:
![image](https://user-images.githubusercontent.com/15203304/36567146-987eb62e-17f3-11e8-8b4a-ba09278b9902.png)

This is pinch expanding zooming out a little:
![image](https://user-images.githubusercontent.com/15203304/36567179-a9831686-17f3-11e8-8422-c0f9341a314c.png)

For my case it is preferred to never exist between zoom levels.  Without changing anything and upgrading to 6.0 this is the new default behavior.

**Comment by spyhunter99** [comment]
@monsieurtanuki doh!
@jklimke @mlendl if this is the issue (and thanks for the screenshots), we'll look into restoring the discrete zoom functionality. It should be doable. If needed, the previous of osmdroid can always be used

**Comment by monsieurtanuki** [comment]
@spyhunter99 I guess we could just add a piece of code in final pinch gesture's method `MapView.selectObject`, something like `setZoomLevel(Math.round(getZoomLevelDouble()))`.
Do you see any use case where that wouldn't be enough?

**Comment by mlendl** [comment]
My issue was simple, I have code like this:
      getIntent().putExtra(EXTRA_ZOOM, mMapView.getController().getZoom());
      int zoom = getIntent().getIntExtra(EXTRA_ZOOM, -1);
if getZoom() is changed from int to double, you get -1.
I have resolved it with current double methods, for me no issue anymore.

**Comment by monsieurtanuki** [comment]
@mlendl @jmarks213 I just added method `MapView.setZoomRounding(boolean)` in #963.
That should fix this issue, though the pinch-gesture-in-double-zoom-to-integer-zoom transition may seem a bit rough (no animation).

**Comment by jmarks213** [comment]
@monsieurtanuki Thanks, it works similarly enough to pre 6.0 :+1:

**Comment by monsieurtanuki** [comment]
@jmarks213 Cool!
Now closing this issue; @mlendl please feel free to reopen this issue if #963 is not satisfactory.
