### ISSUE TITLE
Question: Is this possible to add overlay on priority basis ?

### ISSUE THREAD

**Issue by mdakram** [osmdroid/osmdroid#95]
I am Using osmdroid for long time, now using tilelayer overlay. behaviour i want is when i am adding tileoverlay for tile label its drawing over polylines i am drawing polyline for visible area only, main problem begins when user scrolls and i am adding polylines its covering label tileOverlay. cant we introduce overlay priority e.g polyline overlay 1 tileoverlay 2 and so on.

PS: i know i should have posted this on stackoverflow but its more theoretical than programmatic.

**Comment by MKergall** [comment]
You can set an overlay at a specific position in the display list, this way: 
map.getOverlays().add(0, myBottomOverlay);

This is roughly equivalent to priorities.

**Comment by kurtzmarc** [comment]
Yes, the order that you add or insert overlays determines their drawing priority.
