### ISSUE TITLE
 mMapView.zoomToBoundingBox(bounds, true) does not seem to be working correctly

### ISSUE THREAD

**Issue by spyhunter99** [osmdroid/osmdroid#955]
## Issue Type

[ ] Bug

## Description and/or steps/code to reproduce the problem

Starting at
zoom=1, then calling
zoomToBoundingBox
N:60.930432202923335; E:-135.0; S:60.759159502269895; W:-135.3515625
then setMinZoom(11) 

doesn't appear to bring us anywhere near the correct zoom or bounding box.

### Version of osmdroid the issue relates to:

it appears to be in 6.0.1, not sure what the root cause is yet

**Comment by monsieurtanuki** [comment]
> Starting at zoom=1, then calling zoomToBoundingBox
N:60.930432202923335; E:-135.0; S:60.759159502269895; W:-135.3515625
then setMinZoom(11) doesn't appear to bring us anywhere near the correct zoom or bounding box.

[presumably in "animation" mode given the title of this issue]
@spyhunter99 What you're trying to achieve is very bold:
* starting an animation that will last 100ths of second
* at the same time immediately set the minimum zoom (that is much higher than the current zoom level)

This causes confusion in the animation, that started with a given zoom level, assumed everything would be quiet during the animation and computed its step accordingly. Additional confusion: a zoom level is also computed during the `zoomToBoundingBox` operation, which possibly is lower than the minimum zoom level you want to set.

As commented in `MapView.zoomToBoundingBox`:
> in a perfect world there would be an animation for both center and zoom level

Another solution to the issue - and to other issues related to the drawing code collision - would be to be able to explicitly _queue_ drawing actions in some cases.
Something like:
* set the minimum zoom to 11
* AND THEN (after the map view drawing) zoom to bounding box (therefore with no collision)

Maybe something using `MapView.post(Runnable)`. This kind of method would also help use avoid the classic "how come mapView.getHeight() is 0"?

**Comment by monsieurtanuki** [comment]
@spyhunter99 As a test, I added the following lines at the end of method `StarterMapFragment.onResume`:
````java
mMapView.post(new Runnable() {
	@Override
	public void run() {
		mMapView.zoomToBoundingBox(new BoundingBox(60.930432202923335, -135.0, 60.759159502269895, -135.3515625), true);
		mMapView.setMinZoomLevel(11.);
	}
});
````
And the results are:
* an animation towards the center of the bounding box
* at zoom level 11 (as the computed zoom level is 10.321928094887362 on my smartphone)

Hence my questions:
* isn't that what you expect?
* can you add the code and reproduce this same behavior on your smartphone/emulator?
* is what actually bothers you the fact that we need to use `View.post(Runnable)`?

**Comment by spyhunter99** [comment]
On my end,  I started at zoom 1, after the call, I was at zoom 3. Clearly
not at an appropriate zoom level for zoomtobounds, nor at the min zoom level

On Mar 5, 2018 1:09 PM, "monsieurtanuki" <notifications@github.com> wrote:

@spyhunter99 <https://github.com/spyhunter99> As a test, I added the
following lines at the end of method StarterMapFragment.onResume:

mMapView.post(new Runnable() {
	@Override
	public void run() {
		mMapView.zoomToBoundingBox(new BoundingBox(60.930432202923335,
-135.0, 60.759159502269895, -135.3515625), true);
		mMapView.setMinZoomLevel(11.);
	}
});

And the results are:

   - an animation towards the center of the bounding box
   - at zoom level 11 (as the computed zoom level is 10.321928094887362 on
   my smartphone)

Hence my questions:

   - isn't that what you expect?
   - can you add the code and reproduce this same behavior on your
   smartphone/emulator?
   - is what actually bothers you the fact that we need to use
   View.post(Runnable)?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/osmdroid/osmdroid/issues/955#issuecomment-370509751>,
or mute the thread

**Comment by monsieurtanuki** [comment]
@spyhunter99 My remarks:
* would you test again the `post` solution setting min zoom _before_ zooming to bounding box? I really think this should work OK that way
* by the way I just noticed it's a bit awkward to set the min zoom and to call the zoom to bounding box - in this particular case it may make sense to set the min zoom and set the map center instead
* perhaps part of the problem comes from `setMinZoomLevel`, that doesn't even refresh the map view (invoking `invalidate` for instance)

**Comment by secaw** [comment]
Just slightly related: I started using `zoomToBoundingBox()` lately, which in my case sometimes got called before MapView got its layout, which resulted in heavy ANRs. Wouldn't it make sense to check against `isLayoutOccurred()` in `zoomToBoundingBox()` just to be safe?

**Comment by secaw** [comment]
Also I noticed when doing `zoomToBoundingBox()` from a low zoom level like 3 to a bounding box that basically fills zoom level 11 on a tablet screen (with animation), then after zoom the bounding box is not centered correctly. The lower the start zoom level the larger the offset after zoom.
Possibly related: When I center a point on a low zoom level and zoom in further just with zoom buttons (with animation), the point gradually loses it's center.
May all this be resolved with #948 by any chance?

**Comment by spyhunter99** [comment]
@monsieurtanuki sorry for my absence. I made the changes locally and it appeared to resolve the issue.

**Comment by monsieurtanuki** [comment]
@spyhunter99 OK to close this issue?
