### ISSUE TITLE
Change cache directory

### ISSUE THREAD

**Issue by dsokolov** [osmdroid/osmdroid#96]
Now cache direcory hardcoded in OpenStreetMapTileProviderConstants.OSMDROID_PATH. I would like to have a way to change cache directory.
Thanks

**Comment by MKergall** [comment]
Have a look here: 
http://stackoverflow.com/questions/28062562/osmdroid-change-tiles-cache-in-storage

**Comment by RezApp** [comment]
Hello MKergall,
i am using jar library, how can i use TilesCacheSettings.java patch?
thanks

**Comment by MKergall** [comment]
@RezApp : You have to rebuild the osmdroid lib. 
You add TilesCacheSettings.java in the project, and you replace OpenStreetMapTileProviderConstants.OSMDROID_PATH and OpenStreetMapTileProviderConstants.TILE_PATH_BASE by TilesCacheSettings equivalents.

**Comment by neilboyd** [comment]
See previous [issue 234](https://code.google.com/p/osmdroid/issues/detail?id=234)

**Comment by SamWhited** [comment]
I would like to suggest that you don't just allow changing the cache directory, but allow specifying multiple cache directories (if a tile does not exist in one directory, fallback to the next one and look there; similarly, write to the first directory in the list which exists and for which you have r/w permissions). This would allow one to use shared tile directories from other apps (eg. of OSMand already exists and is storing its map cache to `/sdcard/osmand/tiles` one could add that directory to the search path and possibly save a lot of network bandwidth).

**Comment by MKergall** [comment]
This hard-coded path brings a lot of issues: 
- no way to push the tiles cache on a (huge) external SD card
- no way to benefit from recent Android API like getExternalCacheDirs

As osmdroid seems quite active again - could you consider integrating [this patch](http://stackoverflow.com/questions/28062562/osmdroid-change-tiles-cache-in-storage) (or a better one) for the next release?

**Comment by spyhunter99** [comment]
I'll see what I can do :)

**Comment by spyhunter99** [comment]
@MKergall while your patch is appreciated, as is won't exactly fit. looks like meeting both requirements(1. change the cache dir. and 2. have an extensible list of places to look for tiles offline) is bigger than a bread basket and will cause a number of things to change

**Comment by spyhunter99** [comment]
@MKergall i just pushed changes based on your patch to branch #96. Would you mind reviewing to see if that meets your needs?

Basically, we can change the current "download files here" cache dir and add additional cache directories for search for tile sets/zips/sqlite/etc. I also added the default file location for most samsung devices with sdcards (/storage/extSdCard)

**Comment by neilboyd** [comment]
@spyhunter99 I have a couple of comments on the branch:

1. It would be clearer if you separated the actual change from the unrelated changes in 3ac6d961f9af1b6300c9550b8a06fe32309c3979
2. [Any app that declares the WRITE_EXTERNAL_STORAGE permission is implicitly granted READ_EXTERNAL_STORAGE](https://developer.android.com/reference/android/Manifest.permission.html#READ_EXTERNAL_STORAGE)
3. Why do you set TILE_PATH_BASE in addCachePath?
4. Shouldn't OSMDROID_PATH and TILE_PATH_BASE be final and private? Or at least final if they need to stay for deprecation reasons.
5. It's probably a good idea to check if the list already contains the path being added, or use a `Set` if order doesn't matter.
6. I'm not sure that it's a good idea to add extSdCard by default. It's probably better to leave that to the user like it's done in the example. It's probably tricky depending on lots of factors such as device and API version.

**Comment by MKergall** [comment]
@spyhunter99 - at first glance: 
1) Very good news. 
2) I see you didn't kept the setCachePath method, and ask users to change directly the  DEFAULT_CACHE_DIR. 
I think the approach with a method is safer. For readibility, and securing other possible changes around cache management. 

I agree with @neilboyd that adding extSdCard by default is not a good idea. 

And there is something to check: TileWriter.java has a background task for cache cleaning in its constructor. We should check this how this remains valid, having now various values not constants anymore.

**Comment by spyhunter99** [comment]
first of all, thanks to everyone that took time out of their busy lives to look at the commit. i appreciate it and you've both brought up good points. Sorry for not replying sooner, i was off working on another branch

@neilboyd
1. point taken. i may have been a bit overzealous
2. noted, i can remove the read permission, but it seems like it doesn't matter
3-6 roger

@MKergall 
I'll flip it back. For some reason, I had the thought that it may make more sense to have more than one cache location, i.e. internal and external storage. Looking back, not sure if that's a reasonable thing to assume or not.

changed pused

**Comment by MKergall** [comment]
@spyhunter99 
I looked at your latest change. 
Your setCachePath updates TILE_PATH_BASE, the root for tiles, but not OSMDROID_PATH, which is the root for offline maps. 
So offline maps are still sticked to /sdcard/osmdroid

Maybe the 2 features should be made distinct, changing the offline maps path with a dedicated method:

void setOfflineMapsPath(String fullPath){
  OSMDROID_PATH = File(fullPath);
  //or even better, rename OSMDROID_PATH : 
  //OFFLINE_MAPS_PATH = File(fullPath);
}

**Comment by spyhunter99** [comment]
For offline maps, I also added the ability to change the map tile provider at runtime. This enables you to build your own stack of 'where to load tiles from'. This includes off tiles. Basically you can tell it to look where ever you want and then load the tiles that way. i think there's a class specifically for loading offline zip/sqlite/etc now too

**Comment by spyhunter99** [comment]
To add, the default MapTileProvider first checks assets, then the cache dir, then offline, then online for map tiles based on the ITileSource name.

**Comment by spyhunter99** [comment]
@MKergall are we good to merge on this? i just added your last suggested change

**Comment by MKergall** [comment]
Yes, it looks fine.

**Comment by spyhunter99** [comment]
merged

**Comment by PlayerFour** [comment]
Is there a way I can change the path of the tiles.zip folder from sdcard/osmdroid to the internal storage easily? I'm developing on a tablet with no sd slot

**Comment by spyhunter99** [comment]
Yes. https://github.com/osmdroid/osmdroid/blob/master/osmdroid-android/src/main/java/org/osmdroid/tileprovider/constants/OpenStreetMapTileProviderConstants.java

**Comment by PlayerFour** [comment]
Thank you spyhunter! So if I wanted to change the path of the tiles for offline use to internal storage what exactly would I change? 
OSMDROID_PATH = new File(Environment.getExternalStorageDirectory(), "osmdroid");
would i change to getInteranlStorage....?
Right now I have an sdcard in my tablet with a folder osmdroid with a tiles.zip inside but no tiles are loading

**Comment by spyhunter99** [comment]
It varies by device, but you can try 

OpenStreetMapTileProviderConstants.setOfflineMapsPath("/storage/extSdCard/osmdroid");

**Comment by PlayerFour** [comment]
I'm getting the error cannot resolve method setOfflineMapsPath but I have imported the class.
Any idea why?

**Comment by spyhunter99** [comment]
The ability to have the offline path location is on v5+. You're probably running a 4.x version

**Comment by PlayerFour** [comment]
Okay I'm using 4.3. When I change my compile 'org.osmdroid:osmdroid-android:4.3' in my gradle file I get an error with ....
setContentView(R.layout.activity_main);
MapView mapView = (MapView) findViewById(R.id.mapview);a
because the R is highlighted red

**Comment by MKergall** [comment]
dependencies {
  compile 'org.osmdroid:osmdroid-android:5.0.1@aar'
}
