### ISSUE TITLE
Vectors

### ISSUE THREAD

**Issue by pasniak** [osmdroid/osmdroid#961]
How do I add vectors (arrows) of varying length on a layer?

**Comment by spyhunter99** [comment]
There's a few samples that enable you to draw a line with milestones. perhaps that would meet your needs

**Comment by spyhunter99** [comment]
https://github.com/osmdroid/osmdroid/blob/master/OpenStreetMapViewer/src/main/java/org/osmdroid/samplefragments/drawing/CustomPaintingSurface.java#L150

**Comment by pasniak** [comment]
It's about drawing an ad-hoc path/paths at some geopoint. 

Paths should displays nicely (ex: arrow has some fixed-length shaft) and efficiently when the map is zoomed.

I have an Overlay-inheriting VectorOverlay class which can draw my 10k "vectors" (each is a few Paths) fine. Right now I'm trying try to declutter them with PointReducer.reduceWithTolerance. 

I think MilStdMultipointOverlay is the closest I found (when looking for decluttering)

**Comment by pasniak** [comment]
I struggle a bit with calling reduceWithTolerance, as it takes ArrayList of GeoPoints and I have a longish List of my Vectors (I guess that is also why reduceWithTolerance is commented out in MilStdMultipointOverlay?)
