### ISSUE TITLE
Invalid map file

### ISSUE THREAD

**Issue by johan974** [osmdroid/osmdroid#962]
## Issue Type

[X] Improvement

## Description and/or steps/code to reproduce the problem
Using osmdroid 6 (and 5.6.5) when the map file is missing or invalid, then an Exception is thrown. Please use a blank screen as was used in the past. In the past there was a yellow screen. 
This avoids unnecessary crashes. Of course exceptions should be handled, but sometimes this is difficult when you have many seperate screens based on the MapView. 

More important - I am automtically REGRESSION testing my apps via the emulator. Loading maps on all emulators takes a lot of space is often unwanted. It is also unpractically. 

And still more important - suppose the user has no valid map file at all. Then showing a warning (of course) and a missing-card screen is better. Otherwise the app developer must supply any simple-default map screen. 

## Environment
osmdroid 6.0 and 5.6.5

### If it's a bug, version(s) of android this affects:
Of course an exception could be thrown, but please use the approach as used in the past. 

### Version of osmdroid the issue relates to:
5.6.5 and 6.0

**Comment by spyhunter99** [comment]
do you have a trace of where it's coming from?

**Comment by spyhunter99** [comment]
@johan974 ping. I don't recall anything being changed with regards to this

**Comment by johan974** [comment]
Sorry to let you wait that long. 
When I pass an invalid map-file-name to MapsForgeTileSource.createFromFiles( maps, theme, "rendertheme-v4") then I get a dump. So maps = new File[1]; maps[0] = notExistingMapFile ... will give a dump. 
I "solved" the issue in my app by passing a maps = new File[0]; when no valid mapFile is present yet. 
THANK YOU - that works.
