### ISSUE TITLE
tile server with limited coverage

### ISSUE THREAD

**Issue by shiroyagi** [osmdroid/osmdroid#964]
## Issue Type

[ *] Bug

## Description and/or steps/code to reproduce the problem

If a tile server only provides tiles for a limited geographic region, I have seen strange behaviour when the map is scrolled outside this region.  Rather than the empty grey checked tiles, I see a mixture of these, black tiles, and random tiles from elsewhere on the map.  Sometimes there is a rapid cycling of random tiles drawn.

The log contains:
`Problem downloading MapTile: /14/8167/5502 HTTP response: Not Found`
It repeatedly tries to download the same tile, but in this scenario it should stop trying.  The in-memory (and possibly sql?) cache could contain a flag to prevent this with minimal memory cost.

### If it's a bug, version(s) of android this affects:
5.1

### Version of osmdroid the issue relates to:
6.0.1

**Comment by spyhunter99** [comment]
known issue, duplicate of #131
