### ISSUE TITLE
how to load offline map

### ISSUE THREAD

**Issue by rudda** [osmdroid/osmdroid#966]
hello,
i downloaded tile file .sqlite from MOBAC.
so i add file .sqlite in sdcard/osmdroid folder and i have  one question
how to load map from .sqlite file?

**Comment by spyhunter99** [comment]
It should be automatic. If not, you'll have to set the `mapView.setTileSource` to a tile source who's name matches the tile source provider column in the sqlite database. There's a bunch of examples in the sample app

**Comment by spyhunter99** [comment]
if it's still not loading, check the configuration, it may not be pointed at the right location for your device. `Configuration.getInstance().getBasePath()` i think.

**Comment by MaskeZen** [comment]
In the assets folder is posible put the sqlite file too, no?

**Comment by spyhunter99** [comment]
yes but you'll have to copy it from assets to somewhere else (like  /sdcard or app private storage) at app start up (although my knowledge on this is a bit dated, it may be different now).

**Comment by MaskeZen** [comment]
I tried it, put tiles in png format, and work fine from the assets folder, but must be unzipped.
