### ISSUE TITLE
Map Display Lag in Long Running App

### ISSUE THREAD

**Issue by InI4** [osmdroid/osmdroid#969]
## Issue Type

[ x] Question
[ ] Bug
[ ] Improvement
[ ] Build system related
[x ] Performance
[ ] Documentation

## Description and/or steps/code to reproduce the problem

It just happens, I have an emulator here running for several days with my app. What happens is, that my app still runs smooth, seemingly stable and fine, however there is a lag, when I scroll or zoom the map until tiles get rendered. By huge I mean, it can take 30 seconds until tiles appear, while my apps items on the map (in a self written overlay, loaded from a server) are shown kind of instantly. After a while of scrolling things go back to normal and both my overlay and the tiles render kind of immediately or with the expected network lag.

## Environment
Android 7.1.1
Emulator, Nexus 5x
(self advertisement, app) https://play.google.com/store/apps/details?id=de.spieleck.app.badgers

### If it's a bug, version(s) of android this affects:

All

### Version of osmdroid the issue relates to:

6.0.1

**Comment by spyhunter99** [comment]
i wonder if this is related to the cache deletion issue discussed in #965

**Comment by InI4** [comment]
The symptoms would fit. I am really hoping for #965 code to merge into Osmdroid soon.

**Comment by monsieurtanuki** [comment]
@InI4 Should be OK now. Could you try again?

**Comment by monsieurtanuki** [comment]
@InI4 ping

**Comment by InI4** [comment]
Sry, I need to learn about Github messages, cause I get too many. These symptoms are way better here now, yes. going to close.
