### ISSUE TITLE
Error: Building OSMdroid Third Party 4.4-SNAPSHOT

### ISSUE THREAD

**Issue by sawsaw0023** [osmdroid/osmdroid#97]
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running org.osmdroid.DefaultResourceProxyTest
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.391 sec
Running org.osmdroid.util.GeoPointTest
Tests run: 15, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.047 sec

Results :

Tests run: 18, Failures: 0, Errors: 0, Skipped: 0

[INFO] 
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ osmdroid-android ---
[INFO] Downloading: http://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-archiver/2.1/plexus-archiver-2.1.pom
[INFO] Downloaded: http://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-archiver/2.1/plexus-archiver-2.1.pom (3 KB at 3.3 KB/sec)
[INFO] Downloading: http://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-io/2.0.2/plexus-io-2.0.2.pom
[INFO] Downloaded: http://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-io/2.0.2/plexus-io-2.0.2.pom (2 KB at 1.9 KB/sec)
[INFO] Downloading: http://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-components/1.1.19/plexus-components-1.1.19.pom
[INFO] Downloaded: http://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-components/1.1.19/plexus-components-1.1.19.pom (3 KB at 3.3 KB/sec)
[INFO] Downloading: http://repo.maven.apache.org/maven2/commons-lang/commons-lang/2.1/commons-lang-2.1.pom
[INFO] Downloaded: http://repo.maven.apache.org/maven2/commons-lang/commons-lang/2.1/commons-lang-2.1.pom (10 KB at 10.9 KB/sec)
[INFO] Downloading: http://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-archiver/2.1/plexus-archiver-2.1.jar
[INFO] Downloaded: http://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-archiver/2.1/plexus-archiver-2.1.jar (181 KB at 72.6 KB/sec)
[INFO] Downloading: http://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-io/2.0.2/plexus-io-2.0.2.jar
[INFO] Downloaded: http://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-io/2.0.2/plexus-io-2.0.2.jar (57 KB at 33.7 KB/sec)
[INFO] Downloading: http://repo.maven.apache.org/maven2/commons-lang/commons-lang/2.1/commons-lang-2.1.jar
[INFO] Downloaded: http://repo.maven.apache.org/maven2/commons-lang/commons-lang/2.1/commons-lang-2.1.jar (203 KB at 96.1 KB/sec)
[INFO] Downloading: http://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-utils/3.0/plexus-utils-3.0.jar
[INFO] Downloaded: http://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-utils/3.0/plexus-utils-3.0.jar (221 KB at 88.9 KB/sec)
[INFO] Building jar: C:\TEMP\osmdroid-master\osmdroid-android\target\osmdroid-android-4.4-SNAPSHOT.jar
[INFO] 
[INFO] --- maven-install-plugin:2.4:install (default-install) @ osmdroid-android ---
[INFO] Installing C:\TEMP\osmdroid-master\osmdroid-android\target\osmdroid-android-4.4-SNAPSHOT.jar to C:\Users\USERNAME\.m2\repository\org\osmdroid\osmdroid-android\4.4-SNAPSHOT\osmdroid-android-4.4-SNAPSHOT.jar
[INFO] Installing C:\TEMP\osmdroid-master\osmdroid-android\pom.xml to C:\Users\USERNAME\.m2\repository\org\osmdroid\osmdroid-android\4.4-SNAPSHOT\osmdroid-android-4.4-SNAPSHOT.pom
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building OSMdroid Third Party 4.4-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for android.support:compatibility-v4:jar:21.0.3 is missing, no dependency information available
[WARNING] The POM for com.google.android.maps:maps:jar:21_r1 is missing, no dependency information available
[WARNING] The POM for com.google.android.gms:google-play-services:jar:22.0.0 is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] OSMdroid parent ................................... SUCCESS [01:12 min]
[INFO] OSMdroid Android .................................. SUCCESS [ 45.172 s]
[INFO] OSMdroid Third Party .............................. FAILURE [  0.141 s]
[INFO] OpenStreetMap viewer .............................. SKIPPED
[INFO] osmdroid-android-it - Integration tests ........... SKIPPED
[INFO] Google wrapper sample application ................. SKIPPED
[INFO] OSM map tile packager ............................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 02:01 min
[INFO] Finished at: 2015-02-16T01:32:20+08:00
[INFO] Final Memory: 9M/21M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project osmdroid-third-party: Could not resolve dependencies for project org.osmdroid:osmdroid-third-party:jar:4.4-SNAPSHOT: The following artifacts could not be resolved: android.support:compatibility-v4:jar:21.0.3, com.google.android.maps:maps:jar:21_r1, com.google.android.gms:google-play-services:jar:22.0.0: Failure to find android.support:compatibility-v4:jar:21.0.3 in http://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :osmdroid-third-party

Please help me with this.

**Comment by sawsaw0023** [comment]
Oh sorry for this post, this problem has nothing to do with OSMdroid, this was a maven issue, this is also my first time using maven. I fixed this problem by manually adding missing dependency on local repository of maven.

**Comment by trofimchyk** [comment]
Could you please explain me how you added google play services to your local maven repo? It will be very helpful for me.

**Comment by ChuyingHe** [comment]
hi, im new in maven too, can you show me how to fix it?? thx

**Comment by spyhunter99** [comment]
It's broken at the moment.  Use gradle
