### ISSUE TITLE
scale bar incorrect

### ISSUE THREAD

**Issue by shiroyagi** [osmdroid/osmdroid#970]
## Issue Type
[*] Bug

## Description and/or steps/code to reproduce the problem
At some (probably fractional) zoom levels, the scale bar has the wrong length (but at others is correct).  Most easily seen on a map with kilometre squares.

### If it's a bug, version(s) of android this affects:

All

### Version of osmdroid the issue relates to:

6.0.1

**Comment by monsieurtanuki** [comment]
@shiroyagi Could you give a precise example? I just zoomed in with pinch gesture from level 0 to Paris and could not find any scale length jump.

**Comment by shiroyagi** [comment]
Create a east-west polyline of 1km long, or find two marks on a map appropriately spaced.  At a particular zoom level, the scale bar will be marked 1km and correspond to the distance between the points.  As you zoom in, the points get further apart but the scale bar does not change in length and the distance marked on it does not change.

**Comment by monsieurtanuki** [comment]
@shiroyagi I did not manage to reproduce the bug as you described it.

Nevertheless I may have good news.
While working on a different issue, I noticed bad things in `ScaleBarOverlay` regarding refresh.
For some reasons (performance I guess), the scale bar is refreshed only on 2 conditions (cf. `ScaleBarOverlay.draw`):
* the zoom level changed
* the latitude changed

Fair enough, but in both cases the values are compared as `int` (and not as `double`), which may cause inaccuracies.
Do you think that would explain the current issue?

**Comment by shiroyagi** [comment]
Well spotted, that seems quite likely to be the cause.  The scale bar seems to be behaving as if zoom were still an int.

**Comment by monsieurtanuki** [comment]
@shiroyagi Should be fixed by #991

**Comment by monsieurtanuki** [comment]
@shiroyagi ping
OK to close this issue?

**Comment by monsieurtanuki** [comment]
@shiroyagi ping

**Comment by monsieurtanuki** [comment]
@shiroyagi ping

**Comment by monsieurtanuki** [comment]
I assume it's fixed. Feel free to reopen if necessary.
