### ISSUE TITLE
Custom projection using 6.0.1

### ISSUE THREAD

**Issue by janekp** [osmdroid/osmdroid#971]
I'm aware that osmdroid is designed to use the Web Mercator projection. However, it was trivial to use another projection in v5.6.5 simply by subclassing the Projection class, overriding few methods and MapView.getProjection(). This is not true anymore, for myriad of reasons.

This is mainly due to heavy usage of private instance methods with complex getters/logic. MapView.getProjection() is a good example of this problem (new Projection(this) should probably be in a separate protected method. Perhaps the same with new MapController()). The constructor for the Projection class is another example (mOffsetX/Y & TileSystem).

Sadly, it's quite hard to write a new class from scratch, because interfaces are not used much - for example observe how IGeoPoint is cast to GeoPoint in MapView.setExpectedCenter(). Projection, MapView, MapController etc are all tightly connected. Overall, it's much easier to add customisation hooks to key points.

**Comment by spyhunter99** [comment]
I agree. I'll see what we can do. If you want to open a PR we'll gladly accept it

**Comment by janekp** [comment]
I'll have a look over the weekend

**Comment by monsieurtanuki** [comment]
In `Projection` there are now just a couple of methods actually dealing with the geo projection. The other methods are needed to handle map scrolling, world wrapping and so on.
Maybe a new `GeoProjection` interface should be created, dealing only with the toPixel / fromPixel aspects. That would make things easier when dealing with alternate projections.

**Comment by janekp** [comment]
TileSystem/Projection parts need further refactoring. I created a new ITileSystem interface. I also created a small [demo](https://github.com/janekp/osmdroid/tree/example/%23971)

```java
public interface ITileSystem {

    BoundingBox getGeographicBoundingBox();

    double getMapSize(double pZoomLevel);

    double getTileSize(double pZoomLevel);

    PointL toPixels(double pLatitude, double pLongitude, double pMapSize, PointL pReuse);

    GeoPoint fromPixels(long pX, long pY, double pMapSize, GeoPoint pReuse);
}
```

[feature/#971](https://github.com/janekp/osmdroid/commit/8f175be592cb44e6bbbbc66aeb50c5d586a804b5)

**Comment by monsieurtanuki** [comment]
@janekp Sorry for the late reply: I'll send you comments on your commit within a week.

**Comment by janekp** [comment]
Great!

**Comment by monsieurtanuki** [comment]
@janekp As you saw I commented your commit. An additional thought: there are many places in the osmdroid code where you can see `TileSystem.MinLatitude` and so on. I don't know how that could be impacted too. Could you tell us a bit more about your specific implementation of the abstract `TileSystem` methods (cf. my comments on your code), just to check how much impact we're talking about?

**Comment by janekp** [comment]
TileSystem.MinLatitude is used for checking GeoPoint bounds and assumes WGS84. Ideally one could use their own bounds/system, but this is not a big problem. I can convert input coordinates to WGS84 and areas are always smaller subsets of TileSystem bounds.

**Comment by monsieurtanuki** [comment]
@janekp I just PR'ed #1029.
Feel free to:
* extend your own `TileSystem` (like what I did in `TileSystemWebMercator`)
* use `MapView.setTileSystem` to make this implementation active
* and tell me if if works or if something is missing

**Comment by janekp** [comment]
Nice! I added couple of comments.

**Comment by janekp** [comment]
PR looks good.

**Comment by spyhunter99** [comment]
merged
