### ISSUE TITLE
Expose fillPaint in Polygon

### ISSUE THREAD

**Issue by cknight** [osmdroid/osmdroid#972]
### Problem
org.osmdroid.views.overlay.Polygon exposes the private variable mOutlinePaint via getOutlinePaint().  This is useful for setting rounded corners for example.  E.g.

`polygon.getOutlinePaint().setPathEffect(new CornerPathEffect(50.0f));`

However, the private variable mFillPaint is not similiarly exposed.  This means the fill paint cannot be set to have rounded corners or other advanced effects.

### Suggested solution:

Add the following method:

`public Paint getFillPaint() { return mFillPaint; }` 

### Version of osmdroid the issue relates to:
6.0.1

**Comment by spyhunter99** [comment]
sure thing
