### ISSUE TITLE
Performances: using upsert/replace instead of delete+insert

### ISSUE THREAD

**Issue by monsieurtanuki** [osmdroid/osmdroid#974]
## Issue Type

- [x] Improvement
- [x] Performance

## Description and/or steps/code to reproduce the problem
In `SqlTileWriter.saveFile`, the tile is saved into the database in 2 statements: `delete` then `insert`.
There's a SQLite statement that could be run instead of those 2 - `replace`:
* supposedly faster
* more compact
* functionally cleaner if someone tries to get the tile after the `delete` but before the `insert`

Are there good reasons why we shouldn't switch to `replace` - something like previous bad experiences?

**Comment by spyhunter99** [comment]
What makes you think it's faster? If it is, we'll gladly take a PR for it. I think this needs to be benchmarked both ways to confirm.

**Comment by monsieurtanuki** [comment]
My assumptions are that:
* in SQLite, as they created a command that works a bit like the succession of 2 commands, this command shouldn't be slower
* in Java, we'll use one SQLite command call instead of 2

But it definitely needs to be benchmarked; something like:
* removing all tiles from zoom level 29
* saving 100 tiles on z[29]/x[0]/y[0-99] using the same png, and computing the elapsed time
* saving 100 tiles on the same z[29]/x[0]/y[0-99], and computing the elapsed time
* doing that with both delete+insert and replace methods
* comparing results

What do you think about it?

**Comment by monsieurtanuki** [comment]
Closed as PR'ed in #996
