### ISSUE TITLE
Change TileOverlay cause OOM

### ISSUE THREAD

**Issue by qq86262363** [osmdroid/osmdroid#976]
`mapView.getOverlayManager().setTilesOverlay(tilesOverlay);`
ZoomIn zoomOut and scroll the map,   Memory usage gets bigger and bigger.

### Version of osmdroid the issue relates to:

6.0.1

**Comment by monsieurtanuki** [comment]
@qq86262363 There were recent changes in the code regarding memory cache.
Now we specifically keep in memory the tiles that are displayed, and also the corresponding tiles for zoom +-1 (cf. the constructor and the `garbageCollection` method in `MapTileCache`).
The cache capacity is no longer a relevant value regarding UX. Could you try with a low value for the capacity, something like `Configuration.getInstance().setCacheMapTileCount(0)`?

**Comment by qq86262363** [comment]
It cant solve the porblem . 
If I havent call the method 'mapView.getOverlayManager().setTilesOverlay(tilesOverlay);', its no problem .
Has I change the config after call the method ?

**Comment by qq86262363** [comment]
`mapNikTileOverlay = new TilesOverlay(new MapTileProviderBasic(this, TileSourceFactory.MAPNIK), this);
        mapView.getOverlayManager().setTilesOverlay(mapNikTileOverlay);`
I just do like that and it went wrong. What should I do if I want to change the base tileOverlay?

**Comment by spyhunter99** [comment]
i'm looking into it now

**Comment by spyhunter99** [comment]
what exactly is in your tile chain?

**Comment by qq86262363** [comment]
Just use the default tile chain TileSourceFactory.MAPNIK ,it went wrong .
I think i find the problem , if I call the method `mapView.setTileSource(TileSourceFactory.MAPNIK)`,its no problem .

**Comment by spyhunter99** [comment]
ahh i see. the only you need to create a new tiles overlay is if you want to have two map sources active at the same time. The usual use case if you have a base layer (satellite) and an overlay that is served up using tiles, such as weather, gridlines, etc.
