### ISSUE TITLE
Sometimes CacheManager#downloadAreaAsync too slow

### ISSUE THREAD

**Issue by Tester2012** [osmdroid/osmdroid#977]
Please note: issues related to or caused by osmbonuspack will be closed with a
suggestion to open an issue at https://github.com/MKergall/osmbonuspack

(feel free to delete whatever doesn't apply)

## Issue Type

[ ] Performance

## Description and/or steps/code to reproduce the problem
**Steps to reproduce:**
        1. Try to download an area using downloadAreaAsync(Context ctx, BoundingBox bb, final int zoomMin, final int zoomMax)
        1.1. BoundingBox boundingBox = new BoundingBox(55.09422305343428, 15.598154960661958,
                49.903598241529004, 11.009939948878667);//this is somewhat a map of Berlin, Germany
        1.2. zoomMin = zoomMax = 19

**Expected result:**
       The main thread is not busy for longer than 100 ms.

**Actual Result:**
       The main thread is busy ~ 2 secs (for Samsung Note 8)

**Note:**
       The problem lies here:

    public CacheManagerTask downloadAreaAsync(Context ctx, BoundingBox bb, final int zoomMin, final int zoomMax) {
            final CacheManagerTask task = new CacheManagerTask(this, getDownloadingAction(), bb, zoomMin, zoomMax);//creating this constructor is taking too long
            task.addCallback(getDownloadingDialog(ctx, task));
            return execute(task);  
    }
    ...
    public CacheManagerTask(final CacheManager pManager,  final CacheManagerAction pAction,
                                final BoundingBox pBB,
                                final int pZoomMin, final int pZoomMax) {
         this(pManager, pAction, getTilesCoverage(pBB, pZoomMin, pZoomMax), pZoomMin, 
         pZoomMax);//because  getTilesCoverage(pBB, pZoomMin, pZoomMax) is taking too long
    }
    ...
    public static Collection<Long> getTilesCoverage(final BoundingBox pBB, final int pZoomLevel){
        final Set<Long> result = new HashSet<>();
        final int mapTileUpperBound = 1 << pZoomLevel;
        final Point lowerRight = getMapTileFromCoordinates(
                pBB.getLatSouth(), pBB.getLonEast(), pZoomLevel);
        final Point upperLeft = getMapTileFromCoordinates(
                pBB.getLatNorth(), pBB.getLonWest(), pZoomLevel);
        int width = lowerRight.x - upperLeft.x + 1; // handling the modulo
        if (width <= 0) {
            width += mapTileUpperBound;
        }
        int height = lowerRight.y - upperLeft.y + 1; // handling the modulo
        if (height <= 0) {
            height += mapTileUpperBound;
        }
        
        //2 loops are taking too long
        for (int i = 0 ; i < width ; i ++) {
            for (int j = 0 ; j < height ; j ++) {
                final int x = MyMath.mod(upperLeft.x + i, mapTileUpperBound);
                final int y = MyMath.mod(upperLeft.y + j, mapTileUpperBound);
                result.add((long) x + y);
                result.add(MapTileIndex.getTileIndex(pZoomLevel, x, y));// 
            }
        }
        return result;
    }

2 loops are taking too long.     

**Simple test:**

    @RunWith(RobolectricTestRunner.class)
    public class CacheManagerTest {
        @Test
        public void testGetTilesCoverage() {
            long start = System.currentTimeMillis();
            BoundingBox boundingBox = new BoundingBox(52.95131467958858, 13.6473953271975,
            52.186830733534954, 12.971551530793647);
            CacheManager.getTilesCoverage(boundingBox, 19, 19);
            long end = System.currentTimeMillis();
            System.out.println("Total exec time : " + (end - start)); //it's taking around 1.5 secs
       }
    } 

**How to fix:**
I have several suggestions:

1. Move getTilesCoverage into doInBackground
2. Consider optimising getTilesCoverage by not using 2 loops in it because for each zoom level all we need is upperLeft, height and width. Then, we could just extract consecutive numbers in the corresponding range (for X and Y)

### If it's a bug, version(s) of android this affects:

All

### Version of osmdroid the issue relates to:

6.0.1

**Comment by monsieurtanuki** [comment]
@Tester2012 I could not reproduce this issue because my app crashed before!
For the given bounding box and zoom level, you're trying to download _83.116.471 tiles_ (6.683 * 12.437), which is - in first approach - not reasonable.

**Comment by Tester2012** [comment]
@monsieurtanuki yep, I'm trying to do so because I'd like to use this map at such zoom level offline.

**Comment by monsieurtanuki** [comment]
@Tester2012 If we admit that each tile weights 10 Kb as a bitmap, it means that you want to download (and query and store and regularly refresh) around 800 Gb.
Perhaps you'll be better off asking your tile provider to send you a 800 Gb tile set as a (big) archive file.

Fell free to PR if still needed. Your fix suggestions are technically correct, though the current process uses only one piece of code to handle all cases (tile list, tile bounding box and geo point list). If you implement what you suggest, you'll have a different piece of code dealing with bounding boxes, or you'll have to implement some kind of iterator in order to get the next tile to deal with in all cases.

**Comment by Tester2012** [comment]
@monsieurtanuki thanks for your comment! I'll create a PR dealing only with bounding boxes for now..
