### ISSUE TITLE
integeroverflow TileSystem.GroundResolution(latitude, zoom) and MapSize()

### ISSUE THREAD

**Issue by k3b** [osmdroid/osmdroid#978]
## Issue Type

[X] Bug

Versions

* org.osmdroid:osmdroid-android:6.0.1
* org.osmdroid:osmdroid-mapsforge:6.0.1
* org.mapsforge:mapsforge-map-android:0.6.1
* org.mapsforge:mapsforge-map:0.6.1
* android-7.1

When using osmdroid-0.6.0.1 i get 
`tileProvider.getMaximumZoomLevel() = 29.0.`

Calculating `double roundResolution = TileSystem.GroundResolution(8.0 , 29);` results in an integer overflow

	public final class TileSystem {
		protected static int mTileSize = 256;

		public static double GroundResolution(double latitude, final int levelOfDetail) {
			latitude = Clip(latitude, MinLatitude, MaxLatitude);
			return Math.cos(latitude * Math.PI / 180) * 2 * Math.PI * EarthRadius
					/ MapSize(levelOfDetail);
		}
		
		public static int MapSize(final int levelOfDetail) {
			return mTileSize << (levelOfDetail < getMaximumZoomLevel() ? levelOfDetail
					: getMaximumZoomLevel());
		}
	}

		public static int MapSize(final int levelOfDetail=29) {
			return 256 << 29; // this is more than maxint=4 294 967 295
		}

Changing `int MapSize()` to `long MapSize()` should fix the problem

**Comment by monsieurtanuki** [comment]
@k3b You should use `org.osmdroid.util.TileSystem` rather than `microsoft.mappoint.TileSystem`. That solves everything.

@spyhunter99 Couldn't we just remove `microsoft.mappoint.TileSystem`?

**Comment by k3b** [comment]
thanks @monsieurtanuki that solved my problem. I was not aware that there are two classes.

I am not closing this ticket as a reminder for  remove `microsoft.mappoint.TileSystem`

**Comment by spyhunter99** [comment]
removing it will resolve #111 `org.osmdroid.util.TileSystem` used to be wrapper for the microsoft setup. If we no longer use it, let's deprecate it and schedule it for removal in 6.1

**Comment by monsieurtanuki** [comment]
Closed as:
* the problem of this issue is solved
* the removal of to-be-deprecated-and-removed class `microsoft.mappoint.TileSystem` will be dealt with very soon by solving #111 (the eldest open issue)
