### ISSUE TITLE
Polyline's InfoWindow shows up even when TapOverlay already handled the tap

### ISSUE THREAD

**Issue by pasniak** [osmdroid/osmdroid#985]
[x] Question
[x] Bug

## Description and/or steps/code to reproduce the problem

I have Polylines (routes) with InfoWindow and a TapOverlay (to handle some points on the map; airports).  

I tap the map on the polyline: my TapOverLay::onSingleTapUp fires, opens an airport dialog (good!), returning true. MEANWHILE, the Polyline also catches onShowPress and pops up its route InfoWindow (bad!).  

The end result is 2 changes (infowindow and dialog) to the view when 1 is intended (dialog):

![screenshot from 2018-04-06 21-49-44](https://user-images.githubusercontent.com/19778666/38450076-e222a330-39e5-11e8-896e-cab3ef2782f3.png)

How do I avoid the Polyline's InfoWindow to show when TapOverlay already handled the tap? 

TapOverlay inherits from Overlay:

```
/**
 * handle taps on the map
 */
class TapOverlay (
        private val onLongPress: (Context, IGeoPoint) -> Boolean = {_,_->false},
        private val onSingleTapUp: (Context, IGeoPoint) -> Boolean = {_,_->false},
        private val onShowPress: (Context, IGeoPoint) -> Boolean = {_,_->false}) : Overlay() {

    override fun onSingleTapUp(e: MotionEvent, mapView: MapView): Boolean =
        if (onSingleTapUp(mapView.context, getGeoPoint(e, mapView as MapView2))) {
            true
        }
        else
        super.onSingleTapUp(e, mapView)
```

hardware/emulator

6.0.2-SNAPSHOT

**Comment by spyhunter99** [comment]
isn't there an interface for handling click events for lines?
https://github.com/osmdroid/osmdroid/blob/osmdroid-parent-6.0.1/osmdroid-android/src/main/java/org/osmdroid/views/overlay/Polyline.java#L143

**Comment by MKergall** [comment]
The root cause is that Polyline implements onSingleTapConfirmed event, when you implement onSingleTapUp: 2 different events. 
Can you implement onSingleTapConfirmed in your TapOverlay instead? This will solve your issue.

**Comment by pasniak** [comment]
That fixed it, thanks!
