### ISSUE TITLE
using wms sample in osm 

### ISSUE THREAD

**Issue by sheeranahmedsheikh** [osmdroid/osmdroid#988]
Please note: issues related to or caused by osmbonuspack will be closed with a
suggestion to open an issue at https://github.com/MKergall/osmbonuspack

(feel free to delete whatever doesn't apply)

## Issue Type

[ ] Question
[ ] Bug
[ ] Improvement
[ ] Build system related
[ ] Performance
[ ] Documentation

### If it's a bug, version(s) of android this affects:

All

### Version of osmdroid the issue relates to:

5.6.5

**Comment by spyhunter99** [comment]
What is the problem?

**Comment by spyhunter99** [comment]
@sheeranahmedsheikh need more info
