### ISSUE TITLE
Add ability to change the my location marker

### ISSUE THREAD

**Issue by spyhunter99** [osmdroid/osmdroid#99]
It would be nice if the my location overlay would allow for a custom marker icon. (Not that there's anything wrong with the default icon)

**Comment by trofimchyk** [comment]
Vote for it!

**Comment by ziem** [comment]
Since `mPersonBitmap` is protected you can extend `MyLocationNewOverlay` class and set your own bitmap in constructor. Don't forget to set [mPersonHotspot](https://github.com/osmdroid/osmdroid/blob/master/osmdroid-android/src/main/java/org/osmdroid/views/overlay/mylocation/MyLocationNewOverlay.java#L123).

**Comment by trofimchyk** [comment]
@ziem [mPersonBitmap](https://github.com/osmdroid/osmdroid/blob/master/osmdroid-android/src/main/java/org/osmdroid/views/overlay/mylocation/MyLocationNewOverlay.java#L57) and [mDirectionArrowBitmap](https://github.com/osmdroid/osmdroid/blob/master/osmdroid-android/src/main/java/org/osmdroid/views/overlay/mylocation/MyLocationNewOverlay.java#L58) are final fields, so you can't override them in your constructor.

**Comment by spyhunter99** [comment]
exactly. i was able to do this on my own implementation by c&p'ing the entire overlay class, but that's hardly ideal.

**Comment by trofimchyk** [comment]
@spyhunter99 I know about this way, it really works but it is a little bit tricky :)

**Comment by neilboyd** [comment]
@trofimchyk since those fields are final, you **have to** set them in the constructor. Couldn't you make your own constructor in your subclass?

**Comment by devemux86** [comment]
Don't forget also the actual use of ```ResourceProxy``` classes.
You can override the icons you want, by simply putting your own in the app and using the same names as in Osmdroid lib.
e.g. look at [OpenStreetMapViewer](https://github.com/osmdroid/osmdroid/tree/master/OpenStreetMapViewer/res/drawable) drawable folder.

**Comment by trofimchyk** [comment]
@neilboyd Here is part of me code:
```java
public class CustomLocationOverlay extends MyLocationNewOverlay {
    public CustomLocationOverlay(Context context, MapView mapView) {
        super(context, mapView);

        mPersonBitmap = BitmapFactory.decodeResource(getResources(), drawableResId);
        mDirectionArrowBitmap = BitmapFactory.decodeResource(getResources(), drawableResId);
    }
}
```
But I've got errors from Java compiler:
~cannot assign a value to final variable mPersonBitmap~
and
~cannot assign a value to final variable mDirectionArrowBitmap~
What I'm doing wrong?

**Comment by ziem** [comment]
@trofimchyk you are right, I overlooked final...

**Comment by neilboyd** [comment]
That's because you called super. You can only set a final variable once.

**Comment by emdete** [comment]
the proxy works quite well (but is limited to the predefined resources). i even "translate" IDs to own resources of the app, if these already exist. see:

https://github.com/emdete/tabulae/blob/emdetes/src/main/java/org/pyneo/tabulae/map/ResourceProxyImpl.java#L53

on top of that if converts vector drawables to bitmaps on the fly if needed (my app lacks raster drawables entirely, which is quite handy and reduces app size alot).
