### ISSUE TITLE
MapView "lite mode" as in Google Maps

### ISSUE THREAD

**Issue by monsieurtanuki** [osmdroid/osmdroid#990]
## Issue Type

- [x] Improvement

## Description and/or steps/code to reproduce the problem

As mentioned by @AbduazizKayumov in #958, it would be nice to have a lite mode in `MapView`, similar to GoogleMaps':

> [A lite mode map is a bitmap image of a map at a specified location and zoom level](https://developers.google.com/maps/documentation/android-api/lite)

**Comment by spyhunter99** [comment]
i feel like this was requested before. Someone had asked for a mechanism to fetch a specific tile from the cache, would that satisfy this need?

**Comment by monsieurtanuki** [comment]
@spyhunter99 Rather than just a tile fetch, it's more like "I would like to put `MapView` snapshots into a `ListView` or a `CardView`"
I know that in my app I used some kind of `MapView` bitmap export (including tiles, markers, polylines, ...).
I believe most of the export part is already coded. We just need to make it easy to use.

And with a nice demo! I'm currently building another demo with all US states and gathered their geo bounding boxes.
A `ListView` with 50 US states snapshots would be the target demo. Possibly with rounded corners ;)

**Comment by pasniak** [comment]
I'd use it for thumbnails of locations

**Comment by monsieurtanuki** [comment]
A problem might be to know when a `MapView` is fully rendered and ready to export:
* when are ALL the needed tiles available?
* possible downgraded mode that includes `MapTileApproximater`?

For the record, when I exported a `MapView` into a `Bitmap` in my app, I used `View.getDrawingCache(false)`. Can we do the same with many distinct maps to exports? I don't think so.

**Comment by monsieurtanuki** [comment]
Working on it...

**Comment by monsieurtanuki** [comment]
Knowing when all the needed tiles are available is not an issue, a simple loop is enough.

I managed to export a large png from a geo area, but only the tiles.
I didn't have to create a `MapView` for that.

Now the problem is: should I create a dummy `MapView` just to use its `draw` method, and will it work in background mode, even if the `MapView` is not visible? Or is it possible to ignore the `View` aspect and draw directly on a `Canvas`? Of course the additional views like info windows would be ignored...

The problem is that `MapView` is at the same time a `View`, a Canvas drawer, a touch listener and - thanks to Android technology - a kind of repository for `Context`, `Resources` or `Bitmap`s.

**Comment by monsieurtanuki** [comment]
Working again on the subject.

A way to include all kinds of `Overlay`s in the snapshot is to use `Projection` instead of `MapView` in method `Overlay.draw(Canvas canvas, MapView mapView, boolean shadow)`.

@spyhunter99 While I'm creating `Overlay.draw(Canvas canvas, Projection projection, boolean shadow)`, wouldn't we be even better off without the "shadow" parameter, which in the code comments seems to be deemed finally useless, cf. `DefaultOverlayManager` - _always pass false, the shadow parameter will be removed in a later version of osmdroid_. What do you think about that?

**Comment by spyhunter99** [comment]
A good compromise for removing the method with the `pShadow` argument is exactly this. Make a new method without it, deprecate the old one and have the old one call the new one. Then may be few versions down the road, add an annoying log statement, that it will go away, then finally remove it

**Comment by monsieurtanuki** [comment]
Step 1 was #1245 - merged.

**Comment by monsieurtanuki** [comment]
Currently working on step 2. The goal is to put map snapshots in a `ListView` (as `ImageView`s)

**Comment by monsieurtanuki** [comment]
Done. I've just PR'ed #1277.

**Comment by monsieurtanuki** [comment]
Done in #1277. Closed.

**Comment by s-ilnar** [comment]
Hello, I did not understand how to use this :(
If it’s not difficult for you, tell me, please.
How can I generate images with the image of a track in a RecyclerView?

**Comment by monsieurtanuki** [comment]
@s-ilnar As stated in #1277, try to find inspiration in [`SampleMapSnapshot`](https://github.com/osmdroid/osmdroid/blob/master/OpenStreetMapViewer/src/main/java/org/osmdroid/samplefragments/data/SampleMapSnapshot.java) sample class, especially [when a `MapSnapshot` is created](https://github.com/osmdroid/osmdroid/blob/master/OpenStreetMapViewer/src/main/java/org/osmdroid/samplefragments/data/SampleMapSnapshot.java#L126).

**Comment by s-ilnar** [comment]
@monsieurtanuki Thank you!
Is this a normal result or am I doing something wrong? Why is the level of zoom low?

my code:
```
private final List<Overlay> mOverlays;
private final TileSystem mTileSystem = new TileSystemWebMercator();
final MapTileProviderBase mapTileProvider;

this.mOverlays = new ArrayList<>();
this.mapTileProvider = new MapTileProviderBasic(context);

final DisplayMetrics displayMetrics = getActivity().getResources().getDisplayMetrics();
int mapWidth = displayMetrics.widthPixels;
int height = (int) TypedValue.applyDimension(TypedValue.COMPLEX_UNIT_DIP, 150, getResources().getDisplayMetrics());


ScaleBarOverlay mScaleBarOverlay = new ScaleBarOverlay(context, mapWidth, mapHeight);
mScaleBarOverlay.setCentred(true);
mScaleBarOverlay.setScaleBarOffset(mapWidth / 2, 10);
this.mOverlays.add(mScaleBarOverlay);

private void download() {
	Marker marker = new Marker(new MapView(App.getAppContext()));
	marker.setPosition(new GeoPoint(55.724668, 52.444936));
	BoundingBox boundingBox = marker.getBounds();
	mOverlays.add(marker);

	final double zoom = mTileSystem.getBoundingBoxZoom(boundingBox, mapWidth, mapHeight);
	final MapSnapshot mapSnapshot = new MapSnapshot(new MapSnapshot.MapSnapshotable() {
		@Override
		public void callback(final MapSnapshot pMapSnapshot) {
			if (pMapSnapshot.getStatus() != MapSnapshot.Status.CANVAS_OK) {
				return;
			}
			bitmap = Bitmap.createBitmap(pMapSnapshot.getBitmap());

			recyclerView.post(new Runnable() {
				@Override
				public void run() {
					notifyDataSetChanged();
				}
			});
		}
	}, MapSnapshot.INCLUDE_FLAG_UPTODATE, mapTileProvider, mOverlays,
			new Projection(zoom, mapWidth, mapHeight, boundingBox.getCenterWithDateLine(), 0, true, true, 0, 0));
   // mMapSnapshots.put(key, mapSnapshot);
	new Thread(mapSnapshot).start(); // TODO use AsyncTask, Executors instead?
}

<androidx.appcompat.widget.AppCompatImageView
	android:id="@+id/mapImage"
	android:layout_width="match_parent"
	android:layout_height="150dp"
	app:layout_constraintEnd_toEndOf="parent"
	app:layout_constraintStart_toStartOf="parent"
	app:layout_constraintTop_toTopOf="parent" />
```

result  (small zoom)
<a href="https://ibb.co/5xNj0fs"><img src="https://i.ibb.co/5xNj0fs/7c69149f-3e49-46fb-84ec-397dbfa1567f.jpg" alt="7c69149f-3e49-46fb-84ec-397dbfa1567f" border="0"></a>
