### ISSUE TITLE
Oriented info window + display side effect

### ISSUE THREAD

**Issue by monsieurtanuki** [osmdroid/osmdroid#994]
## Issue Type

- [x] Bug

## Description and/or steps/code to reproduce the problem

When we display markers in an oriented map, the corresponding info window follows the map orientation but the icon does not. What is the expected behavior: both oriented as the map, or both oriented as the screen?
Besides, there seems to be some kind of side effect: probably the info window footer doesn't strictly match the icon.

![device-2018-04-12-164902](https://user-images.githubusercontent.com/11576431/38685470-4a190bce-3e72-11e8-970e-7c3cf2ea3eed.png)
![device-2018-04-12-165514](https://user-images.githubusercontent.com/11576431/38685484-4fa406de-3e72-11e8-9322-02594d2591d3.png)

### Version of osmdroid the issue relates to:

6.0.1

**Comment by MKergall** [comment]
This doesn't happen to Markers, but to Itemized(X)Overlays(Y). 
My opinion is that all those Itemized(X)Overlays(Y) are a mess, and should be deprecated...

**Comment by monsieurtanuki** [comment]
@Maradox and I recently spent time coding on `ItemizedOverlay`.
If `Marker` is the best choice I'm not against deprecating the other classes and coding only in `Marker`.

I don't have a clear view on all those classes (`Marker`, `ItemizedOverlay`, `ItemizedIconOverlay`, `ItemizedOverlayWithFocus` and `SampleItemizedOverlay`) though:
* are there known issues specific to `Marker` that we don't have in `ItemizedOverlay`s?
* are the features that we have in `ItemizedOverlay`s but not in `Marker`?
* are there similar, performance-wise?

**Comment by monsieurtanuki** [comment]
Fixed by #1205
